Repository highfidelity/hifi, pull requests merged in 2018-08, with the labels that each got.

#13703 Edit handles trigger fixes
  scripts/system/controllers/controllerModules/inEditMode.js
  scripts/system/edit.js
  scripts/system/libraries/entitySelectionTool.js
Labels: Create, Development Approved, HMD required, Oculus Required, QA Approved :tada:, Vive Required, bug

#13671 Fix duplication not working as expected on grabbed entities
  scripts/system/libraries/entitySelectionTool.js
Labels: Create, Development Approved, QA Approved :tada:

#13681 Fix ParticleEffect entity JSDoc
  libraries/entities/src/EntityItemProperties.cpp
Labels: Create, Development Approved, JSDocs

#13709 MS17041: Fix for require fail when the same script loaded simultaneously from another entity script
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.h
  libraries/entities/src/EntityItemID.cpp
  libraries/entities/src/EntityItemID.h
  libraries/script-engine/src/ScriptEngine.cpp
  libraries/script-engine/src/ScriptEngine.h
Labels: Create, Development Approved, QA Approved :tada:

#13713 Leg IK fixes
  interface/resources/avatar/avatar-animation.json
  interface/resources/avatar/old-avatar-animation.json
  libraries/animation/src/AnimBlendLinear.cpp
  libraries/animation/src/AnimBlendLinear.h
  libraries/animation/src/AnimBlendLinearMove.cpp
  libraries/animation/src/AnimBlendLinearMove.h
  libraries/animation/src/AnimChain.h
  libraries/animation/src/AnimClip.cpp
  libraries/animation/src/AnimClip.h
  libraries/animation/src/AnimDefaultPose.cpp
  libraries/animation/src/AnimDefaultPose.h
  libraries/animation/src/AnimInverseKinematics.cpp
  libraries/animation/src/AnimInverseKinematics.h
  libraries/animation/src/AnimManipulator.cpp
  libraries/animation/src/AnimManipulator.h
  libraries/animation/src/AnimNode.cpp
  libraries/animation/src/AnimNode.h
  libraries/animation/src/AnimNodeLoader.cpp
  libraries/animation/src/AnimOverlay.cpp
  libraries/animation/src/AnimOverlay.h
  libraries/animation/src/AnimPoleVectorConstraint.cpp
  libraries/animation/src/AnimPoleVectorConstraint.h
  libraries/animation/src/AnimPose.cpp
  libraries/animation/src/AnimPose.h
  libraries/animation/src/AnimSkeleton.cpp
  libraries/animation/src/AnimSkeleton.h
  libraries/animation/src/AnimStateMachine.cpp
  libraries/animation/src/AnimStateMachine.h
  libraries/animation/src/AnimTwoBoneIK.cpp
  libraries/animation/src/AnimTwoBoneIK.h
  libraries/animation/src/AnimUtil.cpp
  libraries/animation/src/AnimUtil.h
  libraries/animation/src/Rig.cpp
  libraries/animation/src/Rig.h
Labels: Avatar, Development Approved, HMD required, QA Approved :tada:

#13642 Fix HMD.mountedChanged() API signal
  interface/src/Application.cpp
  interface/src/scripting/HMDScriptingInterface.h
  libraries/display-plugins/src/display-plugins/AbstractHMDScriptingInterface.h
  libraries/display-plugins/src/display-plugins/hmd/HmdDisplayPlugin.h
  plugins/oculus/src/OculusBaseDisplayPlugin.cpp
  plugins/oculus/src/OculusBaseDisplayPlugin.h
  plugins/openvr/src/OpenVrDisplayPlugin.cpp
  plugins/openvr/src/OpenVrDisplayPlugin.h
Labels: Create, QA Approved :tada:

#13679 FB16840 - Qml spinboxes in UI toolkit should focus the underlying fie…
  interface/resources/qml/controls-uit/SpinBox.qml
Labels: Client, Development Approved, QA Approved :tada:

#13689 Move scriptable caches' APIs into scripting interfaces
  assignment-client/src/Agent.cpp
  assignment-client/src/AssignmentClient.cpp
  assignment-client/src/scripts/EntityScriptServer.cpp
  interface/src/Application.cpp
  interface/src/ui/overlays/Web3DOverlay.cpp
  libraries/animation/src/AnimationCache.h
  libraries/animation/src/AnimationCacheScriptingInterface.cpp
  libraries/animation/src/AnimationCacheScriptingInterface.h
  libraries/audio/src/SoundCache.h
  libraries/audio/src/SoundCacheScriptingInterface.cpp
  libraries/audio/src/SoundCacheScriptingInterface.h
  libraries/model-networking/src/model-networking/ModelCache.h
  libraries/model-networking/src/model-networking/ModelCacheScriptingInterface.cpp
  libraries/model-networking/src/model-networking/ModelCacheScriptingInterface.h
  libraries/model-networking/src/model-networking/TextureCache.h
  libraries/model-networking/src/model-networking/TextureCacheScriptingInterface.cpp
  libraries/model-networking/src/model-networking/TextureCacheScriptingInterface.h
  libraries/networking/src/ResourceCache.cpp
  libraries/networking/src/ResourceCache.h
Labels: Create, Development Approved, QA Approved :tada:, Scripting API change

#13668 Avatarapp: base 'SquareLabel' on button from Uit
  interface/resources/qml/controls-uit/Button.qml
  interface/resources/qml/hifi/AvatarApp.qml
  interface/resources/qml/hifi/avatarapp/SquareLabel.qml
Labels: Client, Development Approved, QA Approved :tada:

#13686 Fix added entities not being undoable in Create
  scripts/system/edit.js
Labels: Create, Development Approved, QA Approved :tada:

#13721 Update bubble context for RC 71
  cmake/externals/serverless-content/CMakeLists.txt
Labels: Development Approved, QA Approved :tada:

#13622 Raise POSIX descriptor-limit in AC Monitor if necessary
  assignment-client/src/AssignmentClientMonitor.cpp
  assignment-client/src/AssignmentClientMonitor.h
Labels: Development Approved, Server & Network, Unix Required

#13704 Enable physics after ES indicates all nearby entities received
  assignment-client/src/entities/EntityTreeSendThread.cpp
  assignment-client/src/entities/EntityTreeSendThread.h
  assignment-client/src/octree/OctreeSendThread.cpp
  assignment-client/src/octree/OctreeSendThread.h
  interface/src/Application.cpp
  interface/src/octree/OctreePacketProcessor.cpp
  interface/src/octree/OctreePacketProcessor.h
  libraries/networking/src/udt/PacketHeaders.h
  libraries/octree/src/OctreeProcessor.cpp
  libraries/octree/src/OctreeProcessor.h
  libraries/octree/src/OctreeQuery.cpp
  libraries/octree/src/OctreeQuery.h
  libraries/shared/src/shared/ConicalViewFrustum.cpp
  libraries/shared/src/shared/ConicalViewFrustum.h
  tools/dissectors/1-hfudt.lua
Labels: Development Approved, Packet Version Change, QA Approved :tada:, Server & Network

#13738 Fix MS17215: Auto-show Confirmed txns in Recent Activity when many Pending txns present
  interface/resources/qml/hifi/commerce/wallet/WalletHome.qml
  interface/resources/qml/hifi/models/PSFListModel.qml
Labels: Commerce, Development Approved, QA Approved :tada:, bug

#13741 hotfix port for 0.70.2: reduced physics load from otherAvatars
  interface/src/avatar/AvatarMotionState.cpp
  interface/src/avatar/AvatarMotionState.h
  libraries/physics/src/ObjectMotionState.cpp
  libraries/physics/src/ObjectMotionState.h
  libraries/shared/src/PhysicsCollisionGroups.h
Labels: Development Approved, Engine, QA Approved :tada:

#13742 HMD Flying Settings Fix for 70.2
  interface/resources/qml/hifi/tablet/ControllerSettings.qml
  interface/src/Application.cpp
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  interface/src/ui/PreferencesDialog.cpp
Labels: Client, Development Approved, QA Approved :tada:

#13747 RC70.2: Fix the other avatars not being removed when Avatar mixer reset
  interface/src/avatar/AvatarManager.cpp
Labels: Development Approved, QA Approved :tada:

#13732 reduce physics simulation cost of other-avatars
  interface/src/avatar/AvatarMotionState.cpp
  interface/src/avatar/AvatarMotionState.h
  libraries/physics/src/ObjectMotionState.cpp
  libraries/physics/src/ObjectMotionState.h
  libraries/shared/src/PhysicsCollisionGroups.h
Labels: Development Approved, Engine, QA Approved :tada:

#13536 ScriptsModel instances should be created & destroyed on the same thread (for Agent)
  assignment-client/src/Agent.cpp
  assignment-client/src/Agent.h
  libraries/networking/src/ThreadedAssignment.cpp
  libraries/networking/src/ThreadedAssignment.h
Labels: Development Approved, QA Approved :tada:, Server & Network

#13737 Don't allow Web surfaces created by non-client scripts to access files
  interface/resources/qml/QmlWebWindow.qml
  interface/src/Application.cpp
  libraries/qml/src/qml/OffscreenSurface.cpp
  libraries/qml/src/qml/OffscreenSurface.h
  libraries/ui/src/QmlFragmentClass.cpp
  libraries/ui/src/QmlFragmentClass.h
  libraries/ui/src/QmlWebWindowClass.cpp
  libraries/ui/src/QmlWebWindowClass.h
  libraries/ui/src/QmlWindowClass.cpp
  libraries/ui/src/QmlWindowClass.h
  libraries/ui/src/ui/OffscreenQmlSurface.cpp
  libraries/ui/src/ui/TabletScriptingInterface.cpp
  libraries/ui/src/ui/types/ContextAwareProfile.cpp
  libraries/ui/src/ui/types/ContextAwareProfile.h
  libraries/ui/src/ui/types/FileTypeProfile.cpp
  libraries/ui/src/ui/types/FileTypeProfile.h
  libraries/ui/src/ui/types/FileTypeRequestInterceptor.cpp
  libraries/ui/src/ui/types/FileTypeRequestInterceptor.h
  libraries/ui/src/ui/types/HFTabletWebEngineProfile.h
  libraries/ui/src/ui/types/HFTabletWebEngineRequestInterceptor.h
  libraries/ui/src/ui/types/HFWebEngineProfile.cpp
  libraries/ui/src/ui/types/HFWebEngineProfile.h
  libraries/ui/src/ui/types/HFWebEngineRequestInterceptor.cpp
  libraries/ui/src/ui/types/HFWebEngineRequestInterceptor.h
  libraries/ui/src/ui/types/RequestFilters.cpp
  libraries/ui/src/ui/types/RequestFilters.h
Labels: Development Approved, Engine, QA Approved :tada:

#13749 Fix the other avatars not being removed when Avatar mixer reset
  interface/src/avatar/AvatarManager.cpp
Labels: Development Approved, Engine, QA Ready

#13637 Audio API JSDoc
  interface/src/scripting/Audio.h
  libraries/audio/src/AudioEffectOptions.cpp
  libraries/audio/src/AudioEffectOptions.h
  libraries/audio/src/AudioInjectorOptions.cpp
  libraries/audio/src/Sound.h
  libraries/audio/src/SoundCacheScriptingInterface.h
  libraries/script-engine/src/AudioScriptingInterface.h
  libraries/script-engine/src/ScriptAudioInjector.h
Labels: Create, Development Approved, JSDocs, QA Approved :tada:, stowaway

#13643 Add DS option to disable HMAC packet authentication
  domain-server/resources/describe-settings.json
  domain-server/src/DomainServer.cpp
  libraries/networking/src/LimitedNodeList.cpp
  libraries/networking/src/LimitedNodeList.h
  libraries/networking/src/NodeList.cpp
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
Labels: Development Approved, QA Approved :tada:, Server & Network

#13751 fix flying
  interface/resources/qml/hifi/tablet/ControllerSettings.qml
  interface/src/avatar/MyAvatar.cpp
  interface/src/ui/PreferencesDialog.cpp
Labels: Client, Development Approved, QA Approved :tada:

#13754 Rc70.3 fix flying
  interface/src/avatar/MyAvatar.cpp
  interface/src/ui/PreferencesDialog.cpp
Labels: Client, Development Approved, QA Ready

#13756 70.4 Flying Fix
  interface/src/avatar/MyAvatar.cpp
  interface/src/ui/PreferencesDialog.cpp
Labels: Client, Development Approved, QA Ready

#13762 Fix possible assert in HRTF
  libraries/audio/src/AudioHRTF.cpp
Labels: Development Approved, QA Approved :tada:, Server & Network, bug

#13763 Added readme and size field to avatar data packet dissector
  tools/dissectors/3-hf-avatar.lua
  tools/dissectors/README.md
Labels: Avatar, Development Approved, Server & Network

#13735 Use key codes for entity camera keys
  scripts/system/libraries/entityCameraTool.js
Labels: Create, Development Approved, QA Approved :tada:, bug

#13743 Fix primitives always drawing as transparents
  libraries/entities-renderer/src/RenderableEntityItem.cpp
  libraries/entities-renderer/src/RenderableShapeEntityItem.cpp
Labels: Engine, QA Approved :tada:

#13733 Elbow pole vectors improvements
  libraries/animation/src/Rig.cpp
Labels: Avatar, Development Approved, QA Approved :tada:

#13750 Fix edit log spam with -1 hand
  scripts/system/libraries/controllers.js
Labels: Client, Create, Development Approved, HMD required, QA Approved :tada:

#13725 Export test suite to TestRail
  tools/auto-tester/CMakeLists.txt
  tools/auto-tester/src/Test.cpp
  tools/auto-tester/src/Test.h
  tools/auto-tester/src/TestRailInterface.cpp
  tools/auto-tester/src/TestRailInterface.h
  tools/auto-tester/src/ui/AutoTester.cpp
  tools/auto-tester/src/ui/AutoTester.h
  tools/auto-tester/src/ui/AutoTester.ui
  tools/auto-tester/src/ui/BusyWindow.cpp
  tools/auto-tester/src/ui/BusyWindow.h
  tools/auto-tester/src/ui/BusyWindow.ui
  tools/auto-tester/src/ui/MismatchWindow.cpp
  tools/auto-tester/src/ui/MismatchWindow.h
  tools/auto-tester/src/ui/MismatchWindow.ui
  tools/auto-tester/src/ui/TestRailRunSelectorWindow.cpp
  tools/auto-tester/src/ui/TestRailRunSelectorWindow.h
  tools/auto-tester/src/ui/TestRailRunSelectorWindow.ui
  tools/auto-tester/src/ui/TestRailTestCasesSelectorWindow.cpp
  tools/auto-tester/src/ui/TestRailTestCasesSelectorWindow.h
  tools/auto-tester/src/ui/TestRailTestCasesSelectorWindow.ui
Labels: Engine

#13775 Don't bind materials during shadow pass
  libraries/entities-renderer/src/RenderableMaterialEntityItem.cpp
  libraries/entities-renderer/src/RenderableShapeEntityItem.cpp
  libraries/render-utils/src/MeshPartPayload.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#13776 Fix bug with texel opaque and transparent cut off shader function
  libraries/graphics/src/graphics/MaterialTextures.slh
  libraries/render-utils/src/forward_model_translucent.slf
  libraries/render-utils/src/model_translucent.slf
  libraries/render-utils/src/model_translucent_normal_map.slf
  libraries/render-utils/src/model_translucent_normal_map_fade.slf
  libraries/render-utils/src/model_translucent_unlit.slf
  libraries/render-utils/src/model_translucent_unlit_fade.slf
Labels: Development Approved, Engine, QA Approved :tada:

#13726 Fix angleBetween potential NaN return value
  libraries/shared/src/GLMHelpers.cpp
Labels: Development Approved, QA Approved :tada:, Server & Network

#13720 Stack tester changes
  assignment-client/src/Agent.cpp
  assignment-client/src/AssignmentClientApp.cpp
  domain-server/src/DomainServer.cpp
  domain-server/src/DomainServer.h
  domain-server/src/DomainServerSettingsManager.cpp
  domain-server/src/DomainServerSettingsManager.h
  domain-server/src/main.cpp
  interface/src/main.cpp
  libraries/gpu/src/gpu/Texture.cpp
  libraries/script-engine/src/ScriptEngine.cpp
  libraries/script-engine/src/StackTestScriptingInterface.cpp
  libraries/script-engine/src/StackTestScriptingInterface.h
  libraries/shared/src/HifiConfigVariantMap.cpp
  libraries/shared/src/HifiConfigVariantMap.h
  libraries/shared/src/LogHandler.cpp
  libraries/shared/src/PathUtils.cpp
Labels: QA Approved :tada:, Server & Network

#13766 Miscellaneous shader fixes
  libraries/entities-renderer/src/RenderableShapeEntityItem.cpp
  libraries/entities-renderer/src/textured_particle.slv
  libraries/procedural/src/procedural/proceduralSkybox.slf
  libraries/render-utils/src/forward_simple.slf
  libraries/render-utils/src/forward_simple_transparent.slf
  libraries/render-utils/src/parabola.slv
  libraries/render-utils/src/simple.slf
  libraries/render-utils/src/simple_transparent.slf
  libraries/render/src/render/DrawSceneOctree.cpp
  libraries/render/src/render/DrawSceneOctree.h
  libraries/render/src/render/DrawStatus.cpp
  libraries/render/src/render/DrawStatus.h
  libraries/render/src/render/Item.h
  libraries/render/src/render/drawCellBounds.slv
  libraries/render/src/render/drawItemBounds.slv
  scripts/developer/utilities/render/culling.qml
Labels: Development Approved, Engine, QA Approved :tada:

#13760 Render Touch controllers at physical hands's locations
  scripts/system/controllers/touchControllerConfiguration.js
Labels: Client, Development Approved, QA Approved :tada:

#13774 Revert to using overlays instead of material entities for button highlighting.
  interface/resources/images/buttonBezel.png
  interface/resources/images/buttonBezel_highlight.png
  interface/src/scripting/HMDScriptingInterface.h
  scripts/system/controllers/controllerModules/inEditMode.js
  scripts/system/libraries/WebTablet.js
  scripts/system/libraries/entityList.js
  scripts/system/libraries/utils.js
  scripts/system/marketplaces/marketplaces.js
  scripts/system/tablet-ui/tabletUI.js
Labels: Client, Development Approved, QA Approved :tada:

#13769 Fix duplicating multiple entities causing infinite looping (RC71 fix)
  scripts/system/libraries/entitySelectionTool.js
Labels: Development Approved, QA Approved :tada:, Release Blocker

#13770 Fix duplicating multiple entities causing infinite looping
  scripts/system/libraries/entitySelectionTool.js
Labels: Development Approved, QA Approved :tada:

#13786 In CCD IK chains, remove the LeftHand and RightHand constraint
  libraries/animation/src/AnimInverseKinematics.cpp
Labels: Avatar, QA Approved :tada:

#13787 [RC71] In CCD IK chains, remove the LeftHand and RightHand constraint completely
  libraries/animation/src/AnimInverseKinematics.cpp
  libraries/animation/src/Rig.cpp
Labels: Avatar, QA Approved :tada:, Release Blocker

#13764 Relocate Avatar Spawn Point from the Hips to the Feet
  interface/src/Application.cpp
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
Labels: Client, Development Approved, QA Approved :tada:

#13767 Fix entity stay highlighted after hand leaves when far grabbing another
  scripts/system/controllers/controllerModules/nearParentGrabEntity.js
Labels: Client, QA Approved :tada:

#13739 Fix cloning a parented entity
  libraries/entities/src/EntityItemProperties.cpp
  scripts/system/controllers/controllerModules/nearActionGrabEntity.js
  scripts/system/controllers/controllerModules/nearParentGrabEntity.js
Labels: Client, Development Approved, HMD required, QA Approved :tada:, bug

#13715 Enable parabolic teleport
  interface/src/raypick/ParabolaPointer.cpp
  interface/src/raypick/ParabolaPointer.h
  interface/src/raypick/PickScriptingInterface.h
  interface/src/raypick/PointerScriptingInterface.cpp
  libraries/pointers/src/Pick.h
  scripts/system/controllers/controllerModules/teleport.js
Labels: Client, Development Approved, Engine, Feedback Welcome, QA Approved :tada:

#13790 v0.71.0: Fix MS17469: Fix conditionals for needing more paginated results when ListView changes
  interface/resources/qml/hifi/models/PSFListModel.qml
Labels: Development Approved, Discovery, QA Approved :tada:, bug

#13791 Alpha 1 for edit handles
  scripts/system/libraries/entitySelectionTool.js
Labels: Create, Development Approved, QA Approved :tada:

#13765 Fix server script status
  scripts/system/edit.js
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, QA Approved :tada:, bug

#13773 check for null node data pointers in handleIgnoreRequestPacket
  assignment-client/src/avatars/AvatarMixer.cpp
Labels: QA Approved :tada:, Server & Network

#13768 MS17413 Triggerable value does not reset on entity deselect
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, QA Approved :tada:

#13780 Fix memory corruption in PerformanceTimer when Stats are active
  interface/src/ui/Stats.cpp
  libraries/shared/src/PerfStat.cpp
  libraries/shared/src/PerfStat.h
Labels: Avatar, Beware: Threading/Deadlock, Development Approved, Engine, QA Approved :tada:

#13794 Fix MS17495: Initially wire sendMessage to ignore in appUi module
  scripts/modules/appUi.js
Labels: Development Approved, Discovery, QA Ready, bug

#13793 Fixing web tablet JavaScript error
  scripts/system/libraries/WebTablet.js
Labels: Client, Development Approved, QA Approved :tada:, bug

#13795 Remove unused uniform buffer from polylines
  libraries/entities-renderer/src/RenderablePolyLineEntityItem.cpp
  libraries/entities-renderer/src/RenderablePolyLineEntityItem.h
  libraries/entities-renderer/src/paintStroke.slf
  libraries/entities-renderer/src/paintStroke.slv
Labels: Development Approved, Engine, QA Approved :tada:

#13772 RC71: check node data pointers in handleNodeIgnoreRequestPacket
  assignment-client/src/avatars/AvatarMixer.cpp
Labels: QA Approved :tada:, Server & Network

#13771 Reselecting same entity in list will unselect it
  scripts/system/html/js/entityList.js
Labels: Create, Development Approved, QA Approved :tada:, bug

#13801 MS17434: modifying MyAvatar.scale get property
  interface/src/avatar/MyAvatar.h
  libraries/avatars/src/AvatarData.h
Labels: Client, Development Approved, QA Approved :tada:, Scripting API change

#13711 MyAvatar's RigidBody ignores collisions with backfacing triangles
  libraries/physics/src/CharacterController.cpp
  libraries/physics/src/PhysicsEngine.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#13797 Edit handle rotation ring size
  scripts/system/libraries/entitySelectionTool.js
Labels: Create, Development Approved, QA Approved :tada:

#13800 Fixing PR13731 shader error on Mac
  interface/src/SecondaryCamera.cpp
  interface/src/workload/GameWorkloadRenderer.cpp
  libraries/render-utils/src/RenderDeferredTask.cpp
  libraries/render-utils/src/RenderDeferredTask.h
  libraries/render-utils/src/RenderForwardTask.cpp
  libraries/render-utils/src/RenderShadowTask.cpp
  libraries/render-utils/src/RenderShadowTask.h
  libraries/render-utils/src/RenderViewTask.cpp
  libraries/render-utils/src/Shadow.slh
  libraries/render-utils/src/ShadowCore.slh
  libraries/render/src/render/CullTask.cpp
  libraries/render/src/render/CullTask.h
  libraries/render/src/render/DrawTask.cpp
  libraries/render/src/render/DrawTask.h
  libraries/render/src/render/SortTask.cpp
  libraries/shared/src/ViewFrustum.cpp
  libraries/shared/src/ViewFrustum.h
  scripts/developer/utilities/render/debugShadow.js
  scripts/developer/utilities/render/shadow.qml
Labels: Development Approved, Engine, QA Approved :tada:

#13785 don't call Avatar::simulate() on fading avatars
  interface/src/avatar/AvatarManager.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#13807 Fixing fading
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities-renderer/src/RenderableEntityItem.cpp
  libraries/entities-renderer/src/RenderableEntityItem.h
  libraries/entities-renderer/src/RenderableModelEntityItem.h
Labels: Development Approved, Engine, QA Approved :tada:, bug

#13761 Reordered build.md instructions
  BUILD.md
Labels: Development Approved

#13811 MS16958: deactivate Create App when desktop windows are closed
  scripts/system/edit.js
  scripts/system/libraries/entityList.js
  scripts/system/modules/createWindow.js
Labels: Create, Development Approved, QA Approved :tada:

#13818 fix desktop press-x handshake
  scripts/system/makeUserConnection.js
Labels: Avatar, Client, Development Approved, QA Approved :tada:

#13816 Fix parabola shader
  libraries/render-utils/src/parabola.slv
Labels: Development Approved, Engine, QA Approved :tada:, bug

#13804 MS17291: Create-app increase focus distance limit
  scripts/system/libraries/entityCameraTool.js
Labels: Create, Development Approved, QA Approved :tada:

#13817 fix desktop press-x handshake
  scripts/system/makeUserConnection.js
Labels: Avatar, Client, Development Approved, QA Approved :tada:

#13752 Improve text in Avatar app's pop-ups
  interface/resources/qml/hifi/avatarapp/MessageBoxes.qml
Labels: Client, Development Approved, QA Approved :tada:

#13819 Avatar bookmarks missing from Avatar Favorites
  interface/src/AvatarBookmarks.cpp
Labels: Client, Development Approved, QA Approved :tada:

#13714 Create CollisionPick API
  interface/src/Application.cpp
  interface/src/raypick/CollisionPick.cpp
  interface/src/raypick/CollisionPick.h
  interface/src/raypick/PickScriptingInterface.cpp
  interface/src/raypick/PickScriptingInterface.h
  libraries/physics/src/PhysicsEngine.cpp
  libraries/physics/src/PhysicsEngine.h
  libraries/pointers/src/Pick.h
  libraries/pointers/src/PickManager.cpp
  libraries/pointers/src/PickManager.h
  libraries/shared/src/RegisteredMetaTypes.h
  libraries/shared/src/ShapeInfo.cpp
  libraries/shared/src/ShapeInfo.h
Labels: Development Approved, Engine, Feedback Welcome, QA Approved :tada:

#13781 MS17380: Create App fix for angularVelocity zeroing out on duplication or undo
  scripts/system/libraries/entitySelectionTool.js
Labels: Create, Development Approved, QA Approved :tada:

#13810 Don't auto-action entry in HMD file dialog when single-click
  interface/resources/qml/dialogs/TabletFileDialog.qml
Labels: Create, Development Approved, QA Approved :tada:

#13724 Android audio tests
  libraries/audio-client/src/AudioClient.cpp
Labels: Android, Engine, QA Approved :tada:

#13706 use updated 'Last Legends: Male' from Mukul
  interface/resources/avatar/bookmarks/avatarbookmarks.json
Labels: Client, Development Approved, QA Approved :tada:

#13784 Far point joints
  interface/src/avatar/MyAvatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
  libraries/shared/src/ThreadSafeValueCache.h
  scripts/system/controllers/controllerDispatcher.js
  scripts/system/controllers/controllerModules/farActionGrabEntityDynOnly.js
  scripts/system/controllers/controllerModules/farParentGrabEntity.js
  scripts/system/controllers/controllerScripts.js
  scripts/system/libraries/controllerDispatcherUtils.js
  scripts/system/libraries/pointersUtils.js
Labels: Client, Development Approved, HMD required, Packet Version Change, QA Approved :tada:

#13748 FB16831 qml-related warnings in log
  interface/src/Application.cpp
  interface/src/ui/overlays/Web3DOverlay.cpp
  interface/src/ui/overlays/Web3DOverlay.h
  libraries/ui/src/ui/OffscreenQmlSurfaceCache.cpp
  libraries/ui/src/ui/OffscreenQmlSurfaceCache.h
Labels: Client, Development Approved, QA Approved :tada:

#13825 Auto scroll
  interface/resources/qml/hifi/Feed.qml
  interface/resources/qml/hifi/Pal.qml
  interface/resources/qml/hifi/tablet/TabletAddressDialog.qml
Labels: QA Ready

#13746 updating emote app icon
  interface/resources/icons/tablet-icons/EmoteAppIcon.svg
  interface/resources/icons/tablet-icons/emote-a.svg
  interface/resources/icons/tablet-icons/emote-i.svg
  scripts/system/emote.js
Labels: Client, Development Approved, QA Approved :tada:

#13809 make avatar kill packets from mixer reliable
  assignment-client/src/avatars/AvatarMixer.cpp
  assignment-client/src/avatars/AvatarMixerClientData.cpp
Labels: Development Approved, QA Approved :tada:, Server & Network

#13604 Add ETC2 support to Oven
  libraries/baking/src/TextureBaker.cpp
  libraries/gpu-gles/src/gpu/gles/GLESBackendTexture.cpp
  libraries/gpu/src/gpu/Texture.cpp
  libraries/gpu/src/gpu/Texture.h
  libraries/image/CMakeLists.txt
  libraries/image/src/image/Image.cpp
  libraries/image/src/image/Image.h
  libraries/model-networking/CMakeLists.txt
  libraries/model-networking/src/model-networking/TextureCache.cpp
Labels: Android, Development Approved, Engine, QA Approved :tada:, Server & Network

#13555 Trying to fix dependency shutdown
  assignment-client/src/Agent.cpp
  domain-server/src/DomainGatekeeper.cpp
  domain-server/src/DomainServer.cpp
  interface/src/AboutUtil.cpp
  interface/src/Application.cpp
  interface/src/AvatarBookmarks.cpp
  interface/src/Menu.cpp
  interface/src/avatar/AvatarManager.cpp
  interface/src/avatar/MyAvatar.cpp
  interface/src/commerce/QmlCommerce.cpp
  interface/src/commerce/Wallet.cpp
  interface/src/scripting/Audio.cpp
  interface/src/scripting/AudioDevices.cpp
  interface/src/ui/JSConsole.cpp
  interface/src/ui/LoginDialog.cpp
  interface/src/ui/PreferencesDialog.cpp
  interface/src/ui/Stats.cpp
  interface/src/ui/TestingDialog.cpp
  libraries/audio-client/src/AudioClient.cpp
  libraries/audio-client/src/AudioClient.h
  libraries/audio-client/src/AudioIOStats.cpp
  libraries/avatars/src/AvatarData.cpp
  libraries/entities/src/EntityScriptingInterface.cpp
  libraries/entities/src/EntityTree.cpp
  libraries/script-engine/src/ScriptEngines.cpp
  libraries/shared/src/DependencyManager.h
  libraries/ui/src/ui/OffscreenQmlSurface.cpp
Labels: Development Approved, Engine, Mac Required, QA Approved :tada:, Windows Required

#13632 Fix potential reliable connection lockup.
  assignment-client/src/assets/AssetServer.cpp
  libraries/networking/src/udt/CongestionControl.cpp
  libraries/networking/src/udt/CongestionControl.h
  libraries/networking/src/udt/Connection.cpp
  libraries/networking/src/udt/Connection.h
  libraries/networking/src/udt/ConnectionStats.cpp
  libraries/networking/src/udt/ConnectionStats.h
  libraries/networking/src/udt/ControlPacket.h
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketTimeWindow.cpp
  libraries/networking/src/udt/PacketTimeWindow.h
  libraries/networking/src/udt/SendQueue.cpp
  libraries/networking/src/udt/SendQueue.h
  libraries/networking/src/udt/Socket.cpp
  libraries/networking/src/udt/Socket.h
  libraries/networking/src/udt/TCPVegasCC.cpp
  libraries/networking/src/udt/TCPVegasCC.h
  tools/dissectors/1-hfudt.lua
  tools/udt-test/src/UDTTest.cpp
  tools/udt-test/src/main.cpp
Labels: Development Approved, Packet Version Change, QA Approved :tada:, Server & Network

#13755 Fix for ScriptEngines not being released upon AC shutdown
  assignment-client/src/Agent.cpp
Labels: Development Approved, QA Approved :tada:, Server & Network

#13827 Replacing jump_takeoff.fbx and jump_land.fbx animations to fix transition to fly bug
  interface/resources/avatar/animations/jump_land.fbx
  interface/resources/avatar/animations/jump_takeoff.fbx
  interface/resources/avatar/animations/walk_fwd.fbx
  interface/resources/avatar/animations/walk_fwd_fast.fbx
Labels: Avatar, Development Approved, QA Approved :tada:, bug

#13835 fix for vanishing other avatars
  interface/src/avatar/AvatarManager.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#13730 Android - Friends in home screen menu
  android/app/build.gradle
  android/app/src/main/cpp/native.cpp
  android/app/src/main/java/io/highfidelity/hifiinterface/InterfaceActivity.java
  android/app/src/main/java/io/highfidelity/hifiinterface/MainActivity.java
  android/app/src/main/java/io/highfidelity/hifiinterface/fragment/FriendsFragment.java
  android/app/src/main/java/io/highfidelity/hifiinterface/provider/EndpointUsersProvider.java
  android/app/src/main/java/io/highfidelity/hifiinterface/provider/UsersProvider.java
  android/app/src/main/java/io/highfidelity/hifiinterface/view/UserListAdapter.java
  android/app/src/main/res/drawable/ic_delete_black_24dp.xml
  android/app/src/main/res/drawable/ic_star.xml
  android/app/src/main/res/drawable/ic_teleporticon.xml
  android/app/src/main/res/layout/fragment_friends.xml
  android/app/src/main/res/layout/user_item.xml
  android/app/src/main/res/menu/menu_navigation.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/dimens.xml
  android/app/src/main/res/values/strings.xml
  android/build.gradle
Labels: Android, Development Approved, Engine, QA Approved :tada:

#13815 MS17562: CreateApp - newly created Entity rotation should be zero
  scripts/system/edit.js
Labels: Create, Development Approved, QA Ready

#13369 Don't sign a production Windows installer if there's no key file
  cmake/macros/SetPackagingParameters.cmake
  cmake/templates/CPackProperties.cmake.in
  cmake/templates/NSIS.template.in
Labels: Development Approved, QA Approved :tada:, Server & Network

#13826 Disable Vive teleport button if transitioning from direction button
  scripts/system/controllers/controllerModules/teleport.js
Labels: Client, Development Approved, QA Approved :tada:

#13839 RC 72 Tutorial - MS17378
  cmake/externals/serverless-content/CMakeLists.txt
Labels: Development Approved, QA Approved :tada:

#13844 Fix killing of single node from DS web interface
  domain-server/src/DomainServer.cpp
Labels: QA Approved :tada:, Server & Network

#13840 fix MyAvatar collision bug at transitions between meshes
  libraries/physics/src/PhysicsEngine.cpp
Labels: Critical Fix, Development Approved, Engine, QA Approved :tada:, bug

#13833 Performance improvements for Collision Pick API
  interface/src/raypick/CollisionPick.cpp
  interface/src/raypick/CollisionPick.h
  libraries/physics/src/PhysicsEngine.cpp
  libraries/physics/src/PhysicsEngine.h
  libraries/shared/src/PhysicsCollisionGroups.h
Labels: Development Approved, Engine, QA Approved :tada:

#13812 Safe landing client-side improvements
  interface/src/Application.cpp
  interface/src/octree/OctreePacketProcessor.cpp
  interface/src/octree/OctreePacketProcessor.h
  interface/src/octree/SafeLanding.cpp
  interface/src/octree/SafeLanding.h
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
Labels: Client, Development Approved, QA Approved :tada:

#13779 Perspective bug
  libraries/render-utils/src/Model.cpp
Labels: Avatar, Development Approved, HMD required, QA Approved :tada:

#13846 Reduce strength of teleport parabola
  scripts/system/controllers/controllerModules/teleport.js
Labels: Client, Development Approved, QA Approved :tada:

#13851 Fix the local lights not working on AMD
  libraries/gpu-gl-common/src/gpu/gl/GLBackendShader.cpp
  libraries/render-utils/src/DeferredLightingEffect.cpp
  libraries/render-utils/src/deferred_light.slv
Labels: Development Approved, Engine, QA Approved :tada:

#13855 Fix parabola rendering on AMD GPUs
  libraries/render-utils/src/parabola.slf
Labels: Development Approved, Engine, QA Approved :tada:

#13803 introduce avatar traits system, migrate skeleton URL and avatar entities
  assignment-client/src/Agent.cpp
  assignment-client/src/Agent.h
  assignment-client/src/AssignmentClient.cpp
  assignment-client/src/audio/AudioMixer.cpp
  assignment-client/src/audio/AudioMixerClientData.cpp
  assignment-client/src/audio/AudioMixerClientData.h
  assignment-client/src/avatars/AvatarMixer.cpp
  assignment-client/src/avatars/AvatarMixer.h
  assignment-client/src/avatars/AvatarMixerClientData.cpp
  assignment-client/src/avatars/AvatarMixerClientData.h
  assignment-client/src/avatars/AvatarMixerSlave.cpp
  assignment-client/src/avatars/AvatarMixerSlave.h
  assignment-client/src/avatars/AvatarMixerSlavePool.cpp
  assignment-client/src/avatars/AvatarMixerSlavePool.h
  assignment-client/src/avatars/ScriptableAvatar.cpp
  assignment-client/src/avatars/ScriptableAvatar.h
  assignment-client/src/entities/EntityServer.cpp
  assignment-client/src/scripts/EntityScriptServer.cpp
  interface/src/Application.cpp
  interface/src/avatar/AvatarManager.cpp
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars/src/AssociatedTraitValues.h
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
  libraries/avatars/src/AvatarHashMap.cpp
  libraries/avatars/src/AvatarHashMap.h
  libraries/avatars/src/AvatarTraits.h
  libraries/avatars/src/ClientTraitsHandler.cpp
  libraries/avatars/src/ClientTraitsHandler.h
  libraries/avatars/src/ScriptAvatarData.cpp
  libraries/avatars/src/ScriptAvatarData.h
  libraries/entities/src/EntityEditPacketSender.cpp
  libraries/entities/src/EntityEditPacketSender.h
  libraries/entities/src/EntityScriptingInterface.cpp
  libraries/networking/src/ExtendedIODevice.h
  libraries/networking/src/NodeData.cpp
  libraries/networking/src/NodeData.h
  libraries/networking/src/udt/BasePacket.cpp
  libraries/networking/src/udt/BasePacket.h
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
  libraries/networking/src/udt/PacketList.h
Labels: Development Approved, QA Approved :tada:, Server & Network

#13856 don't squash delete events during shutdown so that QtWebEngine process gets destoryed
  interface/src/Application.cpp
Labels: Client, Development Approved, QA Approved :tada:

#13858 fix a crash in ESS from missing dependency
  assignment-client/src/scripts/EntityScriptServer.cpp
  libraries/script-engine/src/ScriptEngine.cpp
  libraries/script-engine/src/ScriptEngine.h
Labels: Development Approved, QA Approved :tada:, Server & Network

#13863 MS17774: Enable advanced movement on first run
  interface/src/avatar/MyAvatar.cpp
  interface/src/ui/PreferencesDialog.cpp
Labels: Client, Development Approved, QA Approved :tada:

#13861 Fix safe-landing protocol for sparse domains
  assignment-client/src/entities/EntityTreeSendThread.cpp
  interface/src/octree/SafeLanding.cpp
  interface/src/octree/SafeLanding.h
  libraries/networking/src/udt/PacketHeaders.cpp
Labels: Packet Version Change, QA Approved :tada:, Server & Network

#13841 Don't include old attachment data on new avatar recordings
  interface/src/avatar/MyAvatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
Labels: Client, Development Approved, QA Approved :tada:

#13868 fix traits re-send after node unignored, agent crash
  assignment-client/src/Agent.cpp
  assignment-client/src/avatars/AvatarMixer.cpp
  assignment-client/src/avatars/AvatarMixerClientData.cpp
  assignment-client/src/avatars/AvatarMixerClientData.h
  assignment-client/src/scripts/EntityScriptServer.cpp
Labels: Development Approved, QA Approved :tada:, Server & Network

#13859 Wallet Locker
  interface/resources/qml/hifi/commerce/wallet/Help.qml
  interface/resources/qml/hifi/commerce/wallet/Security.qml
  interface/resources/qml/hifi/commerce/wallet/Wallet.qml
  interface/src/commerce/Ledger.cpp
  interface/src/commerce/Ledger.h
  interface/src/commerce/Wallet.cpp
  interface/src/commerce/Wallet.h
Labels: Commerce

#13869 Fix MS17738: Fix a case where the BLAST icon didn't show up in Snapshot Review
  scripts/system/snapshot.js
Labels: Discovery, QA Approved :tada:, bug

#13870 Implement Wallet Security feature - Auto Logout checkbox
  interface/resources/qml/LoginDialog/LinkAccountBody.qml
  interface/resources/qml/hifi/commerce/wallet/Security.qml
  interface/resources/qml/hifi/commerce/wallet/Wallet.qml
  interface/src/Application.cpp
  scripts/system/commerce/wallet.js
Labels: Commerce, Development Approved

#13847 workload tracks other avatars and adds/removes from physics simulation accordingly
  interface/resources/qml/Stats.qml
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/avatar/AvatarManager.cpp
  interface/src/avatar/AvatarManager.h
  interface/src/avatar/AvatarMotionState.cpp
  interface/src/avatar/AvatarMotionState.h
  interface/src/avatar/OtherAvatar.cpp
  interface/src/avatar/OtherAvatar.h
  interface/src/ui/Stats.cpp
  interface/src/ui/Stats.h
  interface/src/workload/PhysicsBoundary.cpp
  interface/src/workload/PhysicsBoundary.h
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/physics/src/PhysicsEngine.cpp
  libraries/physics/src/PhysicsEngine.h
  libraries/shared/src/SpatiallyNestable.cpp
  libraries/shared/src/SpatiallyNestable.h
Labels: Development Approved, Engine, QA Approved :tada:

#13778 Enable bloom in zone properties
  libraries/entities-renderer/src/RenderableZoneEntityItem.cpp
  libraries/entities-renderer/src/RenderableZoneEntityItem.h
  libraries/entities/src/BloomPropertyGroup.cpp
  libraries/entities/src/BloomPropertyGroup.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityPropertyFlags.h
  libraries/entities/src/ZoneEntityItem.cpp
  libraries/entities/src/ZoneEntityItem.h
  libraries/graphics/src/graphics/Bloom.cpp
  libraries/graphics/src/graphics/Bloom.h
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
  libraries/render-utils/src/BloomEffect.cpp
  libraries/render-utils/src/BloomEffect.h
  libraries/render-utils/src/BloomStage.cpp
  libraries/render-utils/src/BloomStage.h
  libraries/render-utils/src/HazeStage.h
  libraries/render-utils/src/RenderDeferredTask.cpp
  libraries/render-utils/src/UpdateSceneTask.cpp
  libraries/render-utils/src/ZoneRenderer.cpp
  libraries/render/src/render/BlurTask.cpp
  libraries/render/src/render/BlurTask.h
  scripts/developer/utilities/render/bloom.qml
  scripts/developer/utilities/render/debugBloom.js
  scripts/system/html/entityProperties.html
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, Engine, Packet Version Change, QA Approved :tada:, Scripting API change

#13845 Move blendshape packing to worker thread
  interface/src/Menu.cpp
  interface/src/Menu.h
  interface/src/avatar/AvatarManager.cpp
  libraries/fbx/src/FBX.h
  libraries/fbx/src/FBXReader.h
  libraries/graphics/src/graphics/BufferViewHelpers.cpp
  libraries/graphics/src/graphics/BufferViewHelpers.h
  libraries/render-utils/src/CauterizedModel.cpp
  libraries/render-utils/src/MeshPartPayload.cpp
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
  libraries/render-utils/src/SoftAttachmentModel.cpp
Labels: Avatar, Development Approved, Engine, QA Approved :tada:

#13871 force NodeList reset if DS changes session or local ID
  domain-server/src/DomainGatekeeper.cpp
  libraries/networking/src/NodeList.cpp
Labels: Development Approved, QA Approved :tada:, Server & Network

#13879 RC72: force NL reset if the domain changes session ID or local ID
  domain-server/src/DomainGatekeeper.cpp
  libraries/networking/src/NodeList.cpp
Labels: Development Approved, QA Approved :tada:, Server & Network

#13588 Working on pauses in tomb domain
  libraries/gpu-gl-common/src/gpu/gl/GLBackend.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLTextureTransfer.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#13877 Create N replicas of each other-avatar on the client side
  interface/src/Application.h
  interface/src/scripting/TestScriptingInterface.cpp
  interface/src/scripting/TestScriptingInterface.h
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
  libraries/avatars/src/AvatarHashMap.cpp
  libraries/avatars/src/AvatarHashMap.h
Labels: Avatar, Development Approved, Engine, QA Ready

#13874 Phase walk fix bug 17770
  libraries/animation/src/AnimBlendLinearMove.cpp
Labels: Avatar, Development Approved, QA Ready, bug

#13880 Fix crash on shutdown in domain with material
  interface/src/Application.cpp
Labels: Development Approved, Engine, QA Approved :tada:, bug

#13887 fix far-grab laser-lock on entities with non-default registration point
  interface/src/raypick/PathPointer.cpp
  scripts/system/controllers/controllerModules/farActionGrabEntity.js
  scripts/system/controllers/controllerModules/farActionGrabEntityDynOnly.js
  scripts/system/controllers/controllerModules/farParentGrabEntity.js
  scripts/system/libraries/controllerDispatcherUtils.js
Labels: Client, Development Approved, Engine, QA Approved :tada:

#13843 Read glTF resources from other than the main directory
  libraries/fbx/src/GLTFReader.cpp
Labels: Client, Development Approved, QA Approved :tada:

#13849 Fix MS16003: In PAL/GoTo WebView, 'BACK' closes app when you can't go back
  interface/resources/qml/controls/TabletWebView.qml
Labels: Client, Development Approved, QA Approved :tada:, bug

#13898 filter out left/right hands from joints list in avatarapp (RC72)
  interface/resources/qml/hifi/AvatarApp.qml
  interface/resources/qml/hifi/avatarapp/AdjustWearables.qml
Labels: Client, Development Approved, QA Approved :tada:

#13888 Edit mode controller mapping using new platform state variables
  interface/src/Application.cpp
  libraries/input-plugins/src/input-plugins/KeyboardMouseDevice.cpp
  scripts/system/edit.js
Labels: Create, Development Approved, Engine, Mac Required, QA Approved :tada:, Windows Required

#13899 Improve Pointer performance
  interface/src/raypick/PathPointer.cpp
  interface/src/raypick/PathPointer.h
  interface/src/raypick/StylusPointer.cpp
  interface/src/raypick/StylusPointer.h
Labels: Development Approved, Engine, QA Approved :tada:

#13867 findRayIntersection/findParabolaIntersection performance improvements
  interface/resources/qml/Stats.qml
  interface/src/Menu.cpp
  interface/src/Menu.h
  interface/src/avatar/AvatarManager.cpp
  interface/src/avatar/AvatarManager.h
  interface/src/raypick/LaserPointer.cpp
  interface/src/raypick/ParabolaPick.cpp
  interface/src/raypick/ParabolaPointer.cpp
  interface/src/raypick/RayPick.cpp
  interface/src/ui/Stats.cpp
  interface/src/ui/Stats.h
  interface/src/ui/overlays/ContextOverlayInterface.cpp
  interface/src/ui/overlays/Volume3DOverlay.cpp
  libraries/avatars/src/AvatarData.h
  libraries/entities-renderer/src/RenderablePolyVoxEntityItem.cpp
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/EntityTreeElement.cpp
  libraries/entities/src/EntityTreeElement.h
  libraries/entities/src/ShapeEntityItem.cpp
  libraries/octree/src/Octree.cpp
  libraries/octree/src/Octree.h
  libraries/pointers/src/Pick.cpp
  libraries/pointers/src/PickCacheOptimizer.h
  libraries/pointers/src/PickManager.cpp
  libraries/pointers/src/PickManager.h
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
  libraries/render-utils/src/PickItemsJob.cpp
  libraries/shared/src/AABox.cpp
  libraries/shared/src/AABox.h
  libraries/shared/src/AACube.cpp
  libraries/shared/src/AACube.h
  libraries/shared/src/GeometryUtil.cpp
  libraries/shared/src/GeometryUtil.h
  libraries/shared/src/TriangleSet.cpp
  libraries/shared/src/TriangleSet.h
Labels: Development Approved, Engine, Feedback Welcome, QA Approved :tada:

#13902 72: send MyAvatar avatar entity updates through entity tree
  interface/src/AvatarBookmarks.cpp
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
Labels: Client, Development Approved, QA Approved :tada:, Server & Network

#13905 Fixup PR13870: Make the feature work in Master
  interface/src/Application.cpp
  libraries/networking/src/AccountManager.h
  scripts/system/commerce/wallet.js
Labels: Commerce, QA Approved :tada:, bug

#13908 Fix Android StateController assert
  interface/src/Application.cpp
Labels: Android, Android Smoke Required, Create, Critical Fix, Development Approved, Engine, Mac Required, QA Approved :tada:, Windows Required

#13641 Hand Azimuth Controls Shoulder Rotation
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  interface/src/avatar/MySkeletonModel.cpp
  libraries/shared/src/AvatarConstants.h
Labels: Avatar, Development Approved, HMD required, QA Approved :tada:

#13796 Avatar without Neck Joint bug 14620
  interface/src/avatar/MyAvatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/SkeletonModel.cpp
Labels: Avatar, Development Approved, QA Approved :tada:, bug

#13900 Fix blendshape crash
  libraries/render-utils/src/CauterizedModel.cpp
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
Labels: Development Approved, Engine, QA Approved :tada:

#13896 Filter timings used in feedback logic for workload region sizes
  interface/src/Application.cpp
  libraries/shared/src/NumericalConstants.h
  libraries/workload/src/workload/Space.h
  libraries/workload/src/workload/ViewTask.cpp
  libraries/workload/src/workload/ViewTask.h
Labels: Development Approved, Engine, QA Approved :tada:

#13913 After PR13898, joints list in Avatar app's Joint dropdown menu do not match actual joints
  interface/resources/qml/hifi/avatarapp/AdjustWearables.qml
Labels: Client, Development Approved, QA Approved :tada:

#13915 RC72: Send ignoring avatar removal to ignored avatar
  assignment-client/src/avatars/AvatarMixer.cpp
Labels: Development Approved, QA Approved :tada:, Server & Network

#13873 Collision Pick Parenting
  interface/src/avatar/MyAvatarHeadTransformNode.cpp
  interface/src/avatar/MyAvatarHeadTransformNode.h
  interface/src/raypick/CollisionPick.cpp
  interface/src/raypick/CollisionPick.h
  interface/src/raypick/LaserPointer.cpp
  interface/src/raypick/LaserPointer.h
  interface/src/raypick/MouseTransformNode.cpp
  interface/src/raypick/MouseTransformNode.h
  interface/src/raypick/ParabolaPick.cpp
  interface/src/raypick/ParabolaPick.h
  interface/src/raypick/ParabolaPointer.cpp
  interface/src/raypick/ParabolaPointer.h
  interface/src/raypick/PickScriptingInterface.cpp
  interface/src/raypick/PickScriptingInterface.h
  interface/src/raypick/PointerScriptingInterface.cpp
  interface/src/raypick/PointerScriptingInterface.h
  interface/src/raypick/RayPick.cpp
  interface/src/raypick/RayPick.h
  interface/src/raypick/StylusPick.cpp
  interface/src/raypick/StylusPick.h
  interface/src/raypick/StylusPointer.cpp
  interface/src/raypick/StylusPointer.h
  libraries/physics/src/PhysicsEngine.cpp
  libraries/physics/src/PhysicsEngine.h
  libraries/pointers/src/Pick.h
  libraries/pointers/src/PickCacheOptimizer.h
  libraries/pointers/src/PickManager.cpp
  libraries/pointers/src/PickManager.h
  libraries/pointers/src/PickTransformNode.cpp
  libraries/pointers/src/PickTransformNode.h
  libraries/pointers/src/Pointer.h
  libraries/pointers/src/PointerManager.cpp
  libraries/pointers/src/PointerManager.h
  libraries/shared/src/NestableTransformNode.cpp
  libraries/shared/src/NestableTransformNode.h
  libraries/shared/src/RegisteredMetaTypes.h
  libraries/shared/src/TransformNode.h
Labels: Development Approved, Engine, HMD required, JSDocs, QA Approved :tada:, Scripting API change
