Repository highfidelity/hifi, pull requests merged in 2018-06, with the labels that each got.

#13285 Make RotationConstraintTests pass
  tests/animation/src/RotationConstraintTests.cpp
Labels: Avatar, Development Approved, QA Approved :tada:

#13254 adding back reload scripts shortcut and clean up AboutUtil
  interface/src/AboutUtil.cpp
  interface/src/AboutUtil.h
  interface/src/Application.cpp
Labels: Client, QA Approved :tada:

#13266 Fix properties not populating particle explorer tab (RC68)
  scripts/system/edit.js
  scripts/system/particle_explorer/particleExplorerTool.js
Labels: Content/Create, Development Approved, QA Approved :tada:

#13258 JavaScript exception in toggleAdvancedMovementForHandControllers.js
  scripts/system/controllers/toggleAdvancedMovementForHandControllers.js
Labels: Client, Critical Fix, Development Approved, QA Approved :tada:

#13260 JavaScript exception in toggleAdvancedMovementForHandControllers.js (RC68)
  scripts/system/controllers/toggleAdvancedMovementForHandControllers.js
Labels: Client, Critical Fix, Development Approved, QA Approved :tada:

#12789 make legacy ignoreForCollision property work right
  libraries/entities/src/EntityItemProperties.cpp
Labels: Client, Development Approved, QA Approved :tada:

#13257 adding back reload scripts shortcut and clean up AboutUtil(RC68)
  interface/src/AboutUtil.cpp
  interface/src/AboutUtil.h
  interface/src/Application.cpp
Labels: Client, Development Approved, QA Approved :tada:

#13288 MS15529: Add secondary camera snapshot notification flag
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/scripting/WindowScriptingInterface.cpp
  interface/src/scripting/WindowScriptingInterface.h
  interface/src/ui/Snapshot.cpp
  interface/src/ui/Snapshot.h
Labels: Discovery, QA Approved :tada:

#13289 Workaround buffer corruption rc68
  android/app/src/main/java/io/highfidelity/hifiinterface/InterfaceActivity.java
Labels: Android, Development Approved, Engine, QA Approved :tada:, QA Ready, Release Blocker

#13287 Workaround for android buffer corruption issue
  android/app/src/main/java/io/highfidelity/hifiinterface/InterfaceActivity.java
Labels: Android, Development Approved, Engine, QA Approved :tada:

#13244 fix copy delete cut paste commands and menus (RC68)
  interface/src/Menu.cpp
Labels: Client, Development Approved, QA Approved :tada:

#13227 Add local-only isVisibleInSecondaryCamera flag to entities
  interface/src/ui/overlays/OverlaysPayload.cpp
  libraries/entities-renderer/src/RenderableEntityItem.cpp
  libraries/entities-renderer/src/RenderableEntityItem.h
  libraries/entities-renderer/src/RenderableMaterialEntityItem.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.h
  libraries/entities-renderer/src/RenderableParticleEffectEntityItem.cpp
  libraries/entities-renderer/src/RenderablePolyLineEntityItem.cpp
  libraries/entities-renderer/src/RenderablePolyVoxEntityItem.h
  libraries/entities-renderer/src/RenderableShapeEntityItem.cpp
  libraries/entities-renderer/src/RenderableZoneEntityItem.cpp
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityItemPropertiesDefaults.h
  libraries/entities/src/EntityPropertyFlags.h
  unpublishedScripts/marketplace/spectator-camera/spectatorCamera.js
Labels: Development Approved, Engine, HMD required, QA Approved :tada:, Scripting API change

#13176 Try reducing concurrent downloads
  interface/src/Application.cpp
Labels: Android, Development Approved, QA Approved :tada:, Server & Network

#13256 remove dead code in Application::keyPressEvent
  interface/src/Application.cpp
Labels: Client, Development Approved, QA Approved :tada:

#13243 fix copy delete cut paste commands and menus
  interface/src/Menu.cpp
Labels: Client, Development Approved, QA Approved :tada:

#13296 Update serverless content to v2
  cmake/externals/serverless-content/CMakeLists.txt
Labels: Development Approved, QA Approved :tada:

#13302 Fix MS15500: Ensure Connection usernames show up in PAL
  interface/resources/qml/hifi/NameCard.qml
Labels: Development Approved, Discovery, QA Approved :tada:, bug

#13251 JSDoc updates
  interface/src/AboutUtil.h
  interface/src/avatar/MyAvatar.h
  interface/src/raypick/PickScriptingInterface.cpp
  interface/src/raypick/PickScriptingInterface.h
  interface/src/raypick/PointerScriptingInterface.h
  interface/src/scripting/WindowScriptingInterface.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityScriptingInterface.h
  libraries/task/src/task/Config.h
Labels: Create, Development Approved, JSDocs, QA Approved :tada:

#13224 Allow using the key 1,2,3 to swicth views and also to enter text in web entity or overlay
  interface/src/Application.cpp
  interface/src/Menu.cpp
Labels: Client, Development Approved, QA Approved :tada:

#13186 Android: Local texture compression using Etc2Comp
  android/build.gradle
  cmake/externals/etc2comp/CMakeLists.txt
  cmake/macros/TargetEtc2Comp.cmake
  cmake/modules/FindEtc2Comp.cmake
  libraries/gpu/src/gpu/Texture.cpp
  libraries/gpu/src/gpu/Texture_ktx.cpp
  libraries/image/CMakeLists.txt
  libraries/image/src/image/Image.cpp
Labels: Android, Android Smoke Required, Development Approved, Engine, QA Approved :tada:

#13290 update server-side bounding box more correctly for grabbed things
  interface/src/avatar/MyAvatar.cpp
  libraries/physics/src/EntityMotionState.cpp
Labels: Development Approved, Engine, HMD required, QA Approved :tada:

#13294 Add isGroupCulled property to ModelOverlays
  interface/src/ui/overlays/Base3DOverlay.cpp
  interface/src/ui/overlays/Base3DOverlay.h
  interface/src/ui/overlays/ModelOverlay.cpp
  interface/src/ui/overlays/ModelOverlay.h
  interface/src/ui/overlays/Overlay.cpp
  interface/src/ui/overlays/Overlay.h
  interface/src/ui/overlays/OverlaysPayload.cpp
  libraries/render/src/render/Item.h
  scripts/system/libraries/WebTablet.js
Labels: Development Approved, Engine, QA Approved :tada:, tablet-ui

#13297 Remove some deprecated functions from the Controller API
  interface/src/scripting/ControllerScriptingInterface.h
  libraries/controllers/src/controllers/ScriptingInterface.cpp
  libraries/controllers/src/controllers/ScriptingInterface.h
Labels: Client, Development Approved, Scripting API change

#13318 Fix MS14925: Don't double-emit signal for display plugin change
  interface/src/Application.cpp
Labels: Client, Development Approved, HMD required, Oculus Required, QA Approved :tada:, bug

#13217 Fix uploaded content archives taking too much memory
  assignment-client/src/octree/OctreeServer.cpp
  assignment-client/src/octree/OctreeServer.h
  domain-server/src/DomainGatekeeper.cpp
  domain-server/src/DomainServer.cpp
  domain-server/src/DomainServer.h
  ice-server/src/IceServer.cpp
  interface/src/SecondaryCamera.cpp
  libraries/embedded-webserver/src/HTTPConnection.cpp
  libraries/embedded-webserver/src/HTTPConnection.h
  libraries/embedded-webserver/src/HTTPManager.cpp
  libraries/embedded-webserver/src/HTTPManager.h
  libraries/embedded-webserver/src/HTTPSConnection.h
  libraries/embedded-webserver/src/HTTPSManager.cpp
  libraries/embedded-webserver/src/HTTPSManager.h
Labels: Development Approved, QA Approved :tada:, Server & Network

#13317 Use binary resources on OSX
  interface/CMakeLists.txt
  interface/src/Application.cpp
  libraries/shared/src/PathUtils.cpp
  libraries/shared/src/PathUtils.h
Labels: Engine, QA Ready

#13279 Fix MS13500: create-app camera orbit to not jump around on secondary monitor
  scripts/system/libraries/entityCameraTool.js
Labels: Create, Development Approved, QA Approved :tada:

#13292 File Dialog Fixes
  interface/resources/qml/dialogs/+android/FileDialog.qml
  interface/resources/qml/dialogs/FileDialog.qml
  interface/resources/qml/dialogs/TabletFileDialog.qml
  interface/resources/qml/hifi/tablet/tabletWindows/TabletFileDialog.qml
Labels: Client, Development Approved, QA Approved :tada:

#13275 Check for null material pointer in CauterizedModel
  libraries/render-utils/src/CauterizedModel.cpp
Labels: Avatar, Development Approved, Engine, QA Approved :tada:

#13310 FB15569 - Debug default scripts no longer on developer menu
  scripts/defaultScripts.js
Labels: Development Approved, QA Approved :tada:

#13255 Fix properties not populating particle explorer tab
  scripts/system/edit.js
  scripts/system/particle_explorer/particleExplorerTool.js
Labels: Create, Development Approved, QA Approved :tada:

#13316 FB15569 - Debug default scripts no longer on developer menu (for RC68)
  scripts/defaultScripts.js
Labels: Client, Development Approved, QA Approved :tada:

#13272 MS14615: Prevent memory overuse when minimized
  interface/src/Application.cpp
  interface/src/Application_render.cpp
Labels: Client, Development Approved, QA Approved :tada:, QA Ready, bug

#13271 Fix joystick and view control bug that makes it bounce
  libraries/input-plugins/src/input-plugins/TouchscreenVirtualPadDevice.cpp
Labels: Android, Development Approved, Engine, QA Approved :tada:

#13265 Re-adding toggleSpaceMode function
  scripts/system/libraries/entitySelectionTool.js
Labels: Development Approved, QA Approved :tada:

#13311 terminate thread if it didn't complete during MAX_SCRIPT_QUITTING_TIME
  libraries/script-engine/src/ScriptEngine.cpp
Labels: Client, Development Approved, QA Approved :tada:, bug

#13273 fixing show overlays menu item on start up
  interface/src/Application.cpp
Labels: Client, Development Approved, QA Approved :tada:

#13314 Update Oculus integration
  cmake/externals/LibOVR/CMakeLists.txt
  cmake/externals/LibOVR/LibOVRCMakeLists.txt
  plugins/oculus/src/OculusBaseDisplayPlugin.cpp
  plugins/oculus/src/OculusBaseDisplayPlugin.h
  plugins/oculus/src/OculusControllerManager.cpp
  plugins/oculus/src/OculusControllerManager.h
  plugins/oculus/src/OculusDisplayPlugin.cpp
  plugins/oculus/src/OculusHelpers.cpp
  plugins/oculus/src/OculusHelpers.h
Labels: Development Approved, Engine, Oculus Required, QA Approved :tada:

#13313 Enable gamepad by default
  plugins/hifiSdl2/src/SDL2Manager.cpp
Labels: Avatar, Client, Development Approved, QA Approved :tada:

#13295 Fix MS15574: Tiny memory leak in Wallet.h
  interface/src/commerce/Wallet.cpp
  interface/src/commerce/Wallet.h
Labels: Commerce, Development Approved, QA Approved :tada:, bug

#13293 Fix MS7224: Add dimensions to printed Snapshot entity
  scripts/system/snapshot.js
Labels: Discovery, QA Approved :tada:, bug

#13327 terminate thread if it didn't complete during MAX_SCRIPT_QUITTING_TIME
  libraries/script-engine/src/ScriptEngine.cpp
Labels: Client, Critical Fix, Development Approved, QA Approved :tada:

#13300 Fix MS15582: In My Purchases, invisible buttons shouldn't be clickable
  interface/resources/qml/hifi/commerce/purchases/PurchasedItem.qml
Labels: Commerce, QA Approved :tada:, bug

#13270 Use version from JSON on domain restore
  libraries/octree/src/OctreeDataUtils.cpp
  libraries/octree/src/OctreeDataUtils.h
  libraries/octree/src/OctreePersistThread.cpp
Labels: Development Approved, QA Ready

#13336 Set UAL default value earlier to be caught by crashpad - RC68
  interface/src/Application.cpp
  interface/src/main.cpp
Labels: Client, Development Approved, QA Approved :tada:

#13326 Fix models starting as green boxes
  libraries/entities-renderer/src/RenderableModelEntityItem.h
Labels: Development Approved, Engine, QA Approved :tada:, bug

#13319 Android - Allow search among protocol compatible user stories and not only tagged ones
  android/app/src/main/java/io/highfidelity/hifiinterface/provider/UserStoryDomainProvider.java
  android/app/src/main/java/io/highfidelity/hifiinterface/view/DomainAdapter.java
Labels: Android, Development Approved, Engine, QA Approved :tada:

#13276 Protect against null resource
  libraries/networking/src/ResourceCache.cpp
Labels: Android, Development Approved, Engine, QA Approved :tada:, Server & Network

#13309 Android - Double Click crash and dev-mobile crash with Pixel XL
  android/app/src/main/java/io/highfidelity/hifiinterface/fragment/HomeFragment.java
  libraries/render-utils/src/RenderViewTask.cpp
Labels: Android, Android Smoke Required, Development Approved, Engine, QA Approved :tada:

#13329 Fix MS15663/15664: Don't set Wallet Status to 'ready' too early
  interface/src/commerce/Wallet.cpp
Labels: Commerce, Development Approved, QA Approved :tada:, bug

#13148 add SHA to PR/master version, add build_type (stable/master/pr/dev)
  android/app/build.gradle
  android/build.gradle
  cmake/macros/SetPackagingParameters.cmake
  cmake/templates/BuildInfo.h.in
  cmake/templates/console-build-info.json.in
  domain-server/src/DomainServer.cpp
  interface/src/Application.cpp
  interface/src/Crashpad.cpp
  libraries/auto-updater/src/AutoUpdater.cpp
  server-console/src/main.js
Labels: Development Approved, QA Approved :tada:

#13333 Fix MS15673: Ensure offscreenUI exists before updating SecurityImageProvider
  interface/src/commerce/Wallet.cpp
Labels: Commerce, Development Approved, QA Approved :tada:, bug

#13133 Center of Gravity Leaning
  interface/src/Menu.cpp
  interface/src/Menu.h
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  interface/src/avatar/MySkeletonModel.cpp
  interface/src/avatar/MySkeletonModel.h
  libraries/animation/src/AnimUtil.cpp
  libraries/animation/src/AnimUtil.h
  libraries/shared/src/AvatarConstants.h
  libraries/shared/src/GLMHelpers.cpp
  libraries/shared/src/GLMHelpers.h
  scripts/defaultScripts.js
Labels: Avatar, Development Approved, QA Approved :tada:

#13334 Fix tablet not disappearing
  interface/src/ui/overlays/ModelOverlay.cpp
Labels: Development Approved, Engine, QA Approved :tada:, bug, tablet-ui

#13325 Use third person camera mode when switching to My View from Top View mode.
  scripts/system/+android/radar.js
Labels: Android, Development Approved, Engine, QA Approved :tada:

#13339 Possibly fix avatarHash crash
  interface/src/avatar/AvatarManager.cpp
  libraries/avatars/src/AvatarHashMap.cpp
  libraries/avatars/src/AvatarHashMap.h
Labels: Development Approved, Engine, QA Approved :tada:

#13343 Fix tablet attaching to hand while far-grabbing an entity
  scripts/system/controllers/controllerModules/farActionGrabEntity.js
Labels: Client, Development Approved, QA Approved :tada:

#13278 Domain-unreachable message remaining on slow connects
  interface/resources/qml/hifi/tablet/TabletRoot.qml
  interface/src/ui/DialogsManager.cpp
  interface/src/ui/DialogsManager.h
  libraries/ui/src/ui/TabletScriptingInterface.cpp
  libraries/ui/src/ui/TabletScriptingInterface.h
Labels: Development Approved, HMD required, QA Approved :tada:, Server & Network, tablet-ui

#13241 Don't mark backups from domains with no asset server corrupted
  domain-server/src/AssetsBackupHandler.cpp
  domain-server/src/AssetsBackupHandler.h
  domain-server/src/DomainServer.cpp
  domain-server/src/DomainServer.h
Labels: Development Approved, QA Approved :tada:, Server & Network

#12917 CMake fixes
  cmake/templates/FixupBundlePostBuild.cmake.in
  tools/oven/CMakeLists.txt
Labels: Client, Development Approved, Server & Network

#13337 Don't save user location if not connected to domain
  libraries/networking/src/AddressManager.cpp
Labels: Client, Development Approved, QA Approved :tada:

#13341 Fix MS13761: Change the move conditions under which overlays hide
  interface/src/ui/OverlayConductor.cpp
  interface/src/ui/OverlayConductor.h
Labels: Client, Development Approved, QA Approved :tada:, bug

#13221 Add more texture options to Oven CLI
  libraries/baking/src/TextureBaker.cpp
  libraries/networking/src/ResourceManager.cpp
  libraries/networking/src/ResourceManager.h
  tools/oven/src/BakerCLI.cpp
  tools/oven/src/OvenCLIApplication.cpp
Labels: QA Approved :tada:

#13346 Fix particle entity shader
  libraries/entities-renderer/src/textured_particle.slv
Labels: Development Approved, Engine, QA Approved :tada:

#13322 Fix Hifi-Grab-Hand message for equipping
  scripts/system/controllers/controllerModules/equipEntity.js
Labels: Client, Development Approved, QA Approved :tada:

#13347 Fix MS15721: Delete app.json if installed script isn't running
  interface/src/commerce/QmlCommerce.cpp
Labels: Commerce, Development Approved, QA Approved :tada:, bug

#13253 Move Sandbox logs to AppDataLocal
  server-console/src/main.js
Labels: Development Approved, QA Approved :tada:, Server & Network

#13252 remove confusing sandbox content update/backup system
  server-console/src/main.js
Labels: Development Approved, QA Approved :tada:

#13328 MS15673: Do some experiments on bubble size
  assignment-client/src/audio/AudioMixerClientData.cpp
  assignment-client/src/avatars/AvatarMixerSlave.cpp
Labels: Discovery, QA Approved :tada:

#13340 Try to fix ModelOverlay texture loading
  interface/src/ui/overlays/ModelOverlay.cpp
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
  scripts/system/pal.js
Labels: Development Approved, Engine, QA Approved :tada:

#13308 Fix for black text rendering white in web elements
  interface/src/Application.cpp
Labels: Development Approved, Engine, Mac Required, QA Approved :tada:

#13352 Rc68 without pr13162
  interface/src/avatar/AvatarMotionState.cpp
  interface/src/avatar/AvatarMotionState.h
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/physics/src/ObjectMotionState.h
  libraries/physics/src/PhysicsEngine.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#13342 keep small masses from introducing NaN into bullet's calculations
  libraries/physics/src/PhysicsEngine.cpp
Labels: Client, Development Approved, QA Failed :sob:

#13348 Fix MS14129: Prevent Marketplace buttons from getting stuck in hover state
  scripts/system/html/js/marketplacesInject.js
Labels: Commerce, Development Approved, QA Approved :tada:, bug

#13171 Enable Avatar Hand Touch Script by Default
  scripts/system/controllers/controllerScripts.js
  scripts/system/controllers/handTouch.js
Labels: Avatar, Development Approved, QA Approved :tada:

#13332 Large avatars should instantly shrink when entering small height domains
  interface/src/Application.cpp
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
Labels: Avatar, Development Approved, QA Approved :tada:

#13358 MS15788: drillDownToPlace and isStacked based on server data.
  interface/resources/qml/hifi/Feed.qml
Labels: Development Approved, Discovery, QA Approved :tada:

#12854 fix skybox bake assert on HDR_FORMAT static order initialization
  libraries/image/src/image/Image.cpp
Labels: Development Approved, Server & Network

#13363 The last merge back
  cmake/externals/serverless-content/CMakeLists.txt
  interface/src/Application.cpp
  interface/src/Menu.cpp
  interface/src/avatar/AvatarMotionState.cpp
  interface/src/avatar/AvatarMotionState.h
  interface/src/main.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/physics/src/ObjectMotionState.h
  libraries/physics/src/PhysicsEngine.cpp
Labels: Merge stable -> master

#13356 Don't hide jump button while moving
  libraries/display-plugins/src/display-plugins/Basic2DWindowOpenGLDisplayPlugin.cpp
Labels: Android, Development Approved, Engine, QA Approved :tada:

#13338 Scripted Blendshapes and Procedural Face Movement Flags
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  interface/src/avatar/MyHead.cpp
  libraries/avatars-renderer/src/avatars-renderer/Head.cpp
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
  libraries/avatars/src/HeadData.h
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
  libraries/shared/src/SharedUtil.cpp
  libraries/shared/src/SharedUtil.h
  scripts/developer/facialExpressions.js
Labels: Avatar, Development Approved, Packet Version Change, QA Approved :tada:, Scripting API change

#13365 Fix crash in image baking due to undefined mip format
  libraries/image/src/image/Image.cpp
Labels: Development Approved, QA Approved :tada:

#13344 handle semantic version numbers in interface/sandbox update
  cmake/macros/SetPackagingParameters.cmake
  cmake/templates/console-build-info.json.in
  interface/src/Application.cpp
  interface/src/ui/UpdateDialog.cpp
  libraries/auto-updater/src/AutoUpdater.cpp
  libraries/auto-updater/src/AutoUpdater.h
  libraries/shared/src/ApplicationVersion.cpp
  libraries/shared/src/ApplicationVersion.h
  server-console/src/main.js
  server-console/src/modules/hf-updater.js
Labels: Development Approved, QA Approved :tada:, Server & Network

#13283 Add uncompressed KTX files to baked texture output
  assignment-client/src/assets/AssetServer.cpp
  assignment-client/src/assets/AssetServer.h
  libraries/baking/src/TextureBaker.cpp
  libraries/baking/src/TextureBaker.h
  libraries/image/src/image/Image.cpp
  libraries/image/src/image/Image.h
  libraries/ktx/src/TextureMeta.cpp
  libraries/ktx/src/TextureMeta.h
  libraries/model-networking/src/model-networking/TextureCache.cpp
  libraries/shared/src/OwningBuffer.h
  tools/oven/src/Oven.cpp
  tools/oven/src/OvenCLIApplication.cpp
Labels: Development Approved, QA Approved :tada:, Server & Network

#13359 Fix resources path URLs not working with Script.resolvePath
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
Labels: Development Approved, QA Approved :tada:

#13367 Fix MS15858: Prevent Interface deadlock during 360 Snap capture
  unpublishedScripts/marketplace/spectator-camera/SpectatorCamera.qml
Labels: Development Approved, Discovery, bug

#12999 allow avatar data to use full segment size
  assignment-client/src/avatars/AvatarMixerSlave.cpp
Labels: Development Approved, QA Approved :tada:, Server & Network

#12901 Fixed banning users
  libraries/networking/src/LimitedNodeList.cpp
Labels: Development Approved, QA Approved :tada:, Server & Network, bug

#13286 Introduce test 'controls gallery' application for controls testing & few spinbox fixes
  interface/resources/qml/controls-uit/SpinBox.qml
  scripts/developer/tests/ControlsGallery.qml
  scripts/developer/tests/Introspector.qml
  scripts/developer/tests/controlsGallery.js
Labels: Client, Development Approved, QA Approved :tada:

#13298 Controller Confguration Page fixes
  interface/resources/qml/controls-uit/ComboBox.qml
  interface/resources/qml/hifi/tablet/ControllerSettings.qml
  interface/resources/qml/hifi/tablet/OpenVrConfiguration.qml
Labels: Client, QA Approved :tada:

#13351 Fix Avatar > Attachments joint and spinboxes
  interface/resources/qml/controls-uit/SpinBox.qml
  interface/resources/qml/hifi/dialogs/attachments/Attachment.qml
Labels: Client, Development Approved, QA Approved :tada:

#13321 Tablet improvements
  interface/resources/images/buttonBezel.png
  interface/resources/images/buttonBezel_highlight.png
  interface/resources/meshes/tablet-with-home-button-small-bezel.fbx
  interface/src/scripting/HMDScriptingInterface.h
  interface/src/ui/overlays/Base3DOverlay.cpp
  interface/src/ui/overlays/Base3DOverlay.h
  interface/src/ui/overlays/Circle3DOverlay.cpp
  interface/src/ui/overlays/Circle3DOverlay.h
  interface/src/ui/overlays/Grid3DOverlay.h
  interface/src/ui/overlays/Image3DOverlay.cpp
  interface/src/ui/overlays/Image3DOverlay.h
  interface/src/ui/overlays/ModelOverlay.cpp
  interface/src/ui/overlays/ModelOverlay.h
  interface/src/ui/overlays/Overlays.cpp
  interface/src/ui/overlays/Planar3DOverlay.cpp
  interface/src/ui/overlays/Planar3DOverlay.h
  interface/src/ui/overlays/Volume3DOverlay.cpp
  interface/src/ui/overlays/Volume3DOverlay.h
  interface/src/ui/overlays/Web3DOverlay.cpp
  interface/src/ui/overlays/Web3DOverlay.h
  scripts/system/libraries/WebTablet.js
  scripts/system/libraries/utils.js
  scripts/system/marketplaces/marketplaces.js
  scripts/system/tablet-ui/tabletUI.js
Labels: Client, Development Approved, QA Approved :tada:

#13374 [RC69] fix cloneDynamic
  scripts/system/libraries/controllerDispatcherUtils.js
Labels: Create, Development Approved, QA Approved :tada:

#13323 Support MP3 files as sound assets
  libraries/audio/src/Sound.cpp
  libraries/audio/src/Sound.h
  libraries/audio/src/flump3dec.cpp
  libraries/audio/src/flump3dec.h
Labels: Client, Development Approved, Feedback Welcome, QA Approved :tada:

#13230 Windows install - use an app ID with toaster popups
  INSTALL.md
  cmake/macros/SetPackagingParameters.cmake
  cmake/templates/CPackProperties.cmake.in
  cmake/templates/NSIS.template.in
  cmake/templates/console-build-info.json.in
  server-console/src/main.js
Labels: Development Approved, QA Approved :tada:, Server & Network, Windows Required

#13375 MS15916: Fix multiple issues with Spectator Camera
  unpublishedScripts/marketplace/spectator-camera/SpectatorCamera.qml
  unpublishedScripts/marketplace/spectator-camera/flashOff.wav
  unpublishedScripts/marketplace/spectator-camera/flashOn.wav
  unpublishedScripts/marketplace/spectator-camera/spectatorCamera.app.json
  unpublishedScripts/marketplace/spectator-camera/spectatorCamera.js
Labels: Development Approved, Discovery, bug

#13380 Remove Limitless API
  interface/src/Application.cpp
  interface/src/scripting/LimitlessConnection.cpp
  interface/src/scripting/LimitlessConnection.h
  interface/src/scripting/LimitlessVoiceRecognitionScriptingInterface.cpp
  interface/src/scripting/LimitlessVoiceRecognitionScriptingInterface.h
  unpublishedScripts/interaction/Interaction.js
  unpublishedScripts/interaction/NPCHelpers.js
  unpublishedScripts/interaction/NPC_AC.js
  unpublishedScripts/interaction/Sphinx.json
Labels: Create, Development Approved, QA Approved :tada:, outsource

#13376 Fix MS13202: Don't save incomplete list of scripts to Settings while reloading scripts
  libraries/script-engine/src/ScriptEngines.cpp
Labels: Client, Development Approved, QA Approved :tada:, bug

#13350 Remove functionality for rendering collision models directly in the Model class
  interface/src/Application.cpp
  interface/src/Application_render.cpp
  interface/src/Menu.cpp
  interface/src/Menu.h
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.h
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.h
  libraries/render-utils/src/CauterizedModel.cpp
  libraries/render-utils/src/CauterizedModel.h
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
Labels: Development Approved, Engine, QA Approved :tada:

#13368 MS15501: Fix keyboard in Create -> Model in HMD
  interface/resources/qml/hifi/tablet/NewModelDialog.qml
Labels: Create, Development Approved, HMD required, QA Approved :tada:, bug

#13371 fix focus issues when mouse is offscreen
  scripts/system/away.js
Labels: Client, Development Approved, QA Approved :tada:

#13366 fixing invisible cursor when coming from HMD mode
  scripts/system/controllers/controllerModules/mouseHMD.js
Labels: Client, Development Approved, QA Approved :tada:

#13377 prevent having more than one instance of a script running after reloading the script
  libraries/script-engine/src/ScriptEngines.cpp
Labels: Client, Development Approved, QA Approved :tada:

#13388 Fix touch controller button handling when Oculus remote is paired (MASTER)
  plugins/oculus/src/OculusControllerManager.cpp
  plugins/oculus/src/OculusControllerManager.h
Labels: Development Approved

#13389 crash fixes, removing unnecessary writes, and misc cleanup
  interface/src/Menu.cpp
  interface/src/ui/overlays/Circle3DOverlay.cpp
  libraries/animation/src/AnimationCache.cpp
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/SimulationOwner.h
  libraries/gpu/src/gpu/Sysmem.cpp
  libraries/gpu/src/gpu/Texture_ktx.cpp
  libraries/networking/src/PacketSender.cpp
  libraries/octree/src/Octree.cpp
  libraries/physics/src/ObjectMotionState.cpp
  libraries/recording/src/recording/impl/PointerClip.cpp
  libraries/ui/src/ui/Menu.cpp
Labels: Development Approved, Engine, QA Approved :tada:, bug

#13387 Fix Oculus touch controller button handling when remote is paired (RC69)
  plugins/oculus/src/OculusControllerManager.cpp
  plugins/oculus/src/OculusControllerManager.h
Labels: Development Approved, Oculus Required, QA Approved :tada:

#13304 Use optimized Bullet raytest function in CharacterGhostObject::rayTest()
  libraries/physics/src/CharacterGhostObject.cpp
  libraries/physics/src/CharacterGhostObject.h
Labels: Development Approved, Engine, QA Approved :tada:

#13331 Breakpad integration for android Interface
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/io/highfidelity/hifiinterface/BreakpadUploaderService.java
  android/app/src/main/java/io/highfidelity/hifiinterface/PermissionChecker.java
  android/build.gradle
  cmake/macros/TargetBreakpad.cmake
  interface/CMakeLists.txt
  interface/src/Application.cpp
  interface/src/CrashHandler.h
  interface/src/CrashHandler_Breakpad.cpp
  interface/src/CrashHandler_Crashpad.cpp
  interface/src/CrashHandler_None.cpp
  interface/src/CrashRecoveryHandler.cpp
  interface/src/CrashRecoveryHandler.h
  interface/src/Crashpad.h
  interface/src/DiscoverabilityManager.cpp
  interface/src/main.cpp
  scripts/system/+android/audio.js
Labels: Android, Engine

#13393 fix concurrency drillDown
  interface/resources/qml/hifi/Feed.qml
Labels: Discovery, bug

#13330 Android - Make sure we call Interface enterBackground when opening
  android/app/src/main/java/io/highfidelity/hifiinterface/InterfaceActivity.java
Labels: Android, Development Approved, Engine, QA Approved :tada:

#13405 Implement MS16007: Add support for PNG snapshots
  interface/src/scripting/WindowScriptingInterface.h
  interface/src/ui/Snapshot.cpp
Labels: Development Approved, Discovery, Engine, QA Approved :tada:

#13312 Fix layered overlay rendering and highlight
  interface/src/ui/overlays/Overlays.cpp
  libraries/render-utils/src/HighlightEffect.cpp
  libraries/render-utils/src/HighlightEffect.h
  libraries/render-utils/src/RenderCommonTask.cpp
  libraries/render-utils/src/RenderDeferredTask.cpp
  libraries/render-utils/src/RenderForwardTask.cpp
  libraries/render-utils/src/RenderPipelines.cpp
  libraries/render-utils/src/overlay3D.slf
  libraries/render-utils/src/overlay3D.slv
  libraries/render-utils/src/overlay3D_model.slf
  libraries/render-utils/src/overlay3D_model_translucent.slf
  libraries/render-utils/src/overlay3D_model_translucent_unlit.slf
  libraries/render-utils/src/overlay3D_model_unlit.slf
  libraries/render-utils/src/overlay3D_translucent.slf
  libraries/render-utils/src/overlay3D_translucent_unlit.slf
  libraries/render-utils/src/overlay3D_unlit.slf
  tests-manual/shaders/src/main.cpp
Labels: Android Smoke Required, Engine, QA Approved :tada:

#13381 Add main & render thread ids to crashpad annotations
  interface/src/Application.cpp
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.cpp
Labels: Client, Development Approved, QA Approved :tada:

#13391 RC69: crash fixes
  libraries/animation/src/AnimationCache.cpp
  libraries/gpu/src/gpu/Sysmem.cpp
  libraries/physics/src/ObjectMotionState.cpp
  libraries/ui/src/ui/Menu.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#13418 Implement MS16052: Use quality '50' when saving PNG Snapshots
  interface/src/ui/Snapshot.cpp
Labels: Development Approved, Discovery, Engine, QA Approved :tada:

#13408 Fix MS16012: Correct the criteria used to determine empty txn history
  interface/resources/qml/hifi/commerce/wallet/WalletHome.qml
Labels: Commerce, Development Approved, QA Ready, bug

#13416 Fix MS15154: Remove focused button color
  interface/resources/qml/controls-uit/Button.qml
Labels: Client, Development Approved, QA Approved :tada:, bug

#13417 RC69: Fix MS15545, MS16012, MS15154, MS15965
  interface/resources/qml/controls-uit/Button.qml
  interface/resources/qml/controls/TabletWebView.qml
  interface/resources/qml/hifi/Feed.qml
  interface/resources/qml/hifi/commerce/wallet/WalletHome.qml
Labels: Client, Commerce, Development Approved, QA Approved :tada:, bug

#13412 RC69: avatars collide again (again, for reals this time)
  interface/src/avatar/AvatarMotionState.cpp
  interface/src/avatar/AvatarMotionState.h
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/physics/src/ObjectMotionState.h
  libraries/physics/src/PhysicsEngine.cpp
  libraries/shared/src/AvatarConstants.h
Labels: Development Approved, Engine, QA Approved :tada:

#13424 Fix crash in display plugin caused by audio device changed
  interface/src/Application.cpp
Labels: Development Approved, Engine

#13425 Fix crash when walking sideways
  interface/src/avatar/MyCharacterController.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#13422 Fix crash in display plugin caused by audio device changed
  interface/src/Application.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#13383 Fix auto lasering locked web entities & only auto laser tablet and web overlays
  scripts/system/controllers/controllerModules/webSurfaceLaserInput.js
Labels: Client, Development Approved, HMD required, QA Approved :tada:

#13403 Breakpad android rc69
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/io/highfidelity/hifiinterface/BreakpadUploaderService.java
  android/app/src/main/java/io/highfidelity/hifiinterface/PermissionChecker.java
  android/build.gradle
  cmake/macros/TargetBreakpad.cmake
  interface/CMakeLists.txt
  interface/src/Application.cpp
  interface/src/CrashHandler.h
  interface/src/CrashHandler_Breakpad.cpp
  interface/src/CrashHandler_Crashpad.cpp
  interface/src/CrashHandler_None.cpp
  interface/src/CrashRecoveryHandler.cpp
  interface/src/CrashRecoveryHandler.h
  interface/src/Crashpad.h
  interface/src/DiscoverabilityManager.cpp
  interface/src/main.cpp
Labels: Android, Development Approved, Engine, QA Approved :tada:

#13269 Billboardable::pointTransformAtCamera div by zero asan warning
  interface/src/ui/overlays/Billboardable.cpp
Labels: Client, Development Approved, QA Approved :tada:, QA Ready

#13421 fix crash on Mac when watching someone else turn with HMD
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
Labels: Development Approved, Engine, QA Approved :tada:, bug

#13434 Fix for Avatar Lean in Direction of Movement: Bug 16075
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MySkeletonModel.cpp
Labels: Avatar, Development Approved, HMD required, QA Approved :tada:, bug

#13362 Fix transparent textures rendering wrong sometimes
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities-renderer/src/RenderableEntityItem.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.h
  libraries/model-networking/src/model-networking/ModelCache.cpp
  libraries/networking/src/ResourceCache.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#13411 Fix crash when deleting objects in serverless mode
  libraries/physics/src/EntityMotionState.cpp
  libraries/physics/src/PhysicalEntitySimulation.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#13426 Highest loading priorities for avatars and attachments
  interface/src/avatar/MyAvatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
  libraries/avatars-renderer/src/avatars-renderer/OtherAvatar.cpp
Labels: Avatar, Development Approved, Engine, QA Approved :tada:

#13433 Simplify Etc2Comp cmake
  cmake/externals/etc2comp/CMakeLists.txt
Labels: Development Approved, Engine, QA Approved :tada:

#13440 RC69 Fix for the point light test flashing in HMD
  libraries/gpu-gl-common/src/gpu/gl/GLBackend.h
  libraries/gpu-gl-common/src/gpu/gl/GLBackendInput.cpp
  libraries/gpu-gl/src/gpu/gl41/GL41BackendInput.cpp
  libraries/gpu-gl/src/gpu/gl45/GL45BackendInput.cpp
Labels: Development Approved, Engine, HMD required, QA Approved :tada:

#13445 RC69: Fix MS16074, MS16076, MS16012: Fix links to Go To BankOfHighFidelity
  interface/resources/qml/hifi/commerce/wallet/Help.qml
  interface/resources/qml/hifi/commerce/wallet/WalletHome.qml
Labels: Commerce, Development Approved, QA Approved :tada:, bug

#13447 68.1: Fix avatarHash crash
  interface/src/avatar/AvatarManager.cpp
  libraries/avatars/src/AvatarHashMap.cpp
  libraries/avatars/src/AvatarHashMap.h
Labels: Development Approved, Engine, QA Approved :tada:

#13392 Remove debug logging message spam for avatar entities that have scripts
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
Labels: Client, Development Approved, QA Approved :tada:

#13396 Temp disable MyAvatar collisions when stretching entities
  scripts/system/libraries/entitySelectionTool.js
Labels: Create, Development Approved, QA Approved :tada:, bug

#13390 Prevent edit press events when pointing at tablet or desktop windows
  scripts/system/controllers/controllerModules/inEditMode.js
  scripts/system/libraries/entitySelectionTool.js
Labels: Create, Development Approved, HMD required, QA Approved :tada:, bug

#13446 Fix MS16088: Prevent long usernames from overlapping HFC logo in Wallet Home
  interface/resources/qml/hifi/commerce/wallet/WalletHome.qml
Labels: Commerce, Development Approved, QA Ready, bug

#13444 Fix MS16074, MS16076: Fix links to Go To BankOfHighFidelity
  interface/resources/qml/hifi/commerce/wallet/Help.qml
  interface/resources/qml/hifi/commerce/wallet/WalletHome.qml
Labels: Commerce, Development Approved, QA Ready, bug

#13451 Beta Release 68.1
  interface/src/avatar/AvatarManager.cpp
  libraries/avatars/src/AvatarHashMap.cpp
  libraries/avatars/src/AvatarHashMap.h
Labels: Development Approved, QA Approved :tada:, Release Candidate

#13456 RC69: 16089: test wearables for wear before gifting and wearing
  interface/resources/qml/hifi/commerce/purchases/PurchasedItem.qml
  interface/resources/qml/hifi/commerce/purchases/Purchases.qml
Labels: Commerce, Development Approved, QA Approved :tada:, bug

#13452 fix physics deactivation of avatar-entities
  interface/src/avatar/AvatarManager.cpp
  interface/src/avatar/AvatarMotionState.cpp
  interface/src/avatar/AvatarMotionState.h
  libraries/physics/src/PhysicalEntitySimulation.cpp
  libraries/physics/src/PhysicalEntitySimulation.h
Labels: Development Approved, Engine, QA Approved :tada:

#13455 16089: test wearables for wear before gifting and wearing
  interface/resources/qml/hifi/commerce/purchases/PurchasedItem.qml
  interface/resources/qml/hifi/commerce/purchases/Purchases.qml
Labels: Commerce, QA Ready, bug

#13435 Breakpad integration for android Interface (part II)
  android/app/build.gradle
  android/build.gradle
  interface/src/CrashHandler_Breakpad.cpp
  scripts/system/+android/audio.js
Labels: Android, Development Approved, Engine, QA Approved :tada:

#13443 report FIx from rc69 to master: Fix for the point light test flashing in HMD
  libraries/gpu-gl-common/src/gpu/gl/GLBackend.h
  libraries/gpu-gl-common/src/gpu/gl/GLBackendInput.cpp
  libraries/gpu-gl/src/gpu/gl41/GL41BackendInput.cpp
  libraries/gpu-gl/src/gpu/gl45/GL45BackendInput.cpp
Labels: Development Approved, Engine, HMD required, QA Approved :tada:

#13448 Fix multi-selection color setting visible/locked to false
  scripts/system/edit.js
  scripts/system/html/js/colpick.js
Labels: Create, Development Approved, QA Approved :tada:, bug

#13459 Fix MS16113: Use alternate method for creating backup instructions
  interface/src/commerce/Wallet.cpp
Labels: Commerce, Development Approved, QA Approved :tada:, bug

#13465 RC69: Fix MS16113: Use alternate method for creating backup instructions
  interface/src/commerce/Wallet.cpp
Labels: Commerce, Development Approved, QA Approved :tada:, bug

#13441 Fixing collisionless grabbing
  scripts/system/controllers/grab.js
Labels: Client, Development Approved, QA Approved :tada:

#13439 Edit handle fixes
  scripts/system/libraries/entitySelectionTool.js
Labels: Create, Development Approved, QA Approved :tada:, bug
