Repository highfidelity/hifi, pull requests merged in 2018-09, with the labels that each got.

#13919 Fix blendshapes crash one last time
  libraries/render-utils/src/CauterizedModel.cpp
  libraries/render-utils/src/CauterizedModel.h
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
  libraries/render-utils/src/SoftAttachmentModel.cpp
  libraries/render-utils/src/SoftAttachmentModel.h
Labels: Development Approved, Engine, QA Approved :tada:

#13883 Added read of map_d from MTL files
  libraries/fbx/src/OBJReader.cpp
  libraries/fbx/src/OBJReader.h
Labels: Development Approved, Engine, QA Ready, bug

#13906 RC72: mark and cycle trait instances needing to be sent on mixer reconnect
  interface/src/Application.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
  libraries/avatars/src/AvatarHashMap.cpp
  libraries/avatars/src/AvatarTraits.h
  libraries/avatars/src/ClientTraitsHandler.cpp
  libraries/avatars/src/ClientTraitsHandler.h
Labels: Development Approved, QA Approved :tada:, Server & Network

#13927 Low-level performance improvements to audio-mixer
  libraries/audio/src/AudioHRTF.cpp
  libraries/audio/src/avx2/AudioHRTF_avx2.cpp
  libraries/audio/src/avx512/AudioHRTF_avx512.cpp
Labels: Development Approved, Feedback Welcome, QA Approved :tada:, Server & Network

#13929 Fix MS17902: Prevent case where My Purchases says Open instead of Uninstall
  interface/src/commerce/QmlCommerce.cpp
Labels: Commerce, QA Ready, bug

#13920 don't bid for simulation ownership of locked entities
  libraries/physics/src/EntityMotionState.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#13914 Miscellaneous low-level performance improvements
  assignment-client/src/avatars/AvatarMixerSlave.cpp
  interface/src/avatar/AvatarManager.cpp
  interface/src/avatar/OtherAvatar.cpp
  libraries/controllers/src/controllers/UserInputMapper.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/graphics/src/graphics/BufferViewHelpers.h
  libraries/shared/src/AABox.cpp
  libraries/shared/src/AABox.h
  libraries/shared/src/GLMHelpers.h
  libraries/shared/src/PrioritySortUtil.h
  tests/shared/src/AACubeTests.cpp
  tests/shared/src/GLMHelpersTests.cpp
  tests/shared/src/GLMHelpersTests.h
Labels: Android, Development Approved, Engine, QA Approved :tada:, Server & Network

#13926 Updated and Revised BUILD_LINUX.md - Includes Ubuntu 18.04 steps
  BUILD.md
  BUILD_LINUX.md
Labels: Development Approved

#13935 Fix for glitch when entering in-air state from takeoff.
  libraries/animation/src/Rig.cpp
Labels: Avatar, Development Approved, QA Approved :tada:

#13918 HMD mode bug fix for avatars with no eyes
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  libraries/controllers/src/controllers/Input.h
  libraries/shared/src/AvatarConstants.h
Labels: Avatar, Development Approved, QA Approved :tada:

#13907 mark and cycle trait instances needing to be sent on mixer reconnect
  interface/src/Application.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
  libraries/avatars/src/AvatarHashMap.cpp
  libraries/avatars/src/AvatarTraits.h
  libraries/avatars/src/ClientTraitsHandler.cpp
  libraries/avatars/src/ClientTraitsHandler.h
Labels: Development Approved, QA Approved :tada:, Server & Network

#13930 Fix MS 17828: Explore Desktop Text Visible
  cmake/externals/serverless-content/CMakeLists.txt
Labels: Development Approved, FTUE, QA Approved :tada:, bug

#13891 Improving the LOD manager behavior for better scaling
  interface/resources/qml/+android/Stats.qml
  interface/resources/qml/Stats.qml
  interface/src/Application.cpp
  interface/src/LODManager.cpp
  interface/src/LODManager.h
  interface/src/ui/PreferencesDialog.cpp
  interface/src/ui/Stats.cpp
  interface/src/ui/Stats.h
  libraries/octree/src/OctreeUtils.cpp
  libraries/octree/src/OctreeUtils.h
  libraries/render-utils/src/RenderShadowTask.cpp
  libraries/render/src/render/Args.h
  libraries/render/src/render/CullTask.cpp
  libraries/render/src/render/CullTask.h
  scripts/developer/utilities/lib/plotperf/PlotPerf.qml
  scripts/developer/utilities/render/configSlider/RichSlider.qml
  scripts/developer/utilities/render/configSlider/qmldir
  scripts/developer/utilities/render/lod.js
  scripts/developer/utilities/render/lod.qml
  tests-manual/render-perf/src/main.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#13932 Fix framebuffer debugging
  libraries/render-utils/src/DebugDeferredBuffer.cpp
  libraries/render-utils/src/debug_deferred_buffer.slf
  libraries/render-utils/src/render-utils/ShaderConstants.h
Labels: Engine, QA Approved :tada:

#13857 MS17463: only show InteractiveWindow on top of interface window
  interface/resources/qml/InteractiveWindow.qml
  libraries/ui/src/InteractiveWindow.cpp
  libraries/ui/src/InteractiveWindow.h
  libraries/ui/src/MainWindow.cpp
  libraries/ui/src/MainWindow.h
  libraries/ui/src/OffscreenUi.cpp
Labels: Client, Create, Development Approved, QA Approved :tada:

#13945 volume slider on individual users in PAL remembers setting now
  interface/resources/qml/hifi/NameCard.qml
Labels: QA Approved :tada:

#13928 enable workload regulation by default
  libraries/workload/src/workload/ViewTask.h
Labels: Development Approved, Engine, QA Approved :tada:

#13947 Fix blendshapes crash one last time, one last time
  libraries/render-utils/src/CauterizedModel.cpp
  libraries/render-utils/src/CauterizedModel.h
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
  libraries/render-utils/src/SoftAttachmentModel.cpp
  libraries/render-utils/src/SoftAttachmentModel.h
Labels: Development Approved, Engine, QA Approved :tada:, bug

#13950 fix a crash related to setting an overlay's name
  interface/src/ui/overlays/Base3DOverlay.cpp
  interface/src/ui/overlays/Base3DOverlay.h
Labels: Client, Development Approved, QA Approved :tada:

#13955 Fix MS17877: Persist Connections table sort choice
  interface/resources/qml/hifi/Pal.qml
Labels: Discovery, QA Ready, bug

#13952 Fix for lurching walk(case 16945), when walking in hmd.
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  interface/src/avatar/MySkeletonModel.cpp
  libraries/shared/src/AvatarConstants.h
Labels: Avatar, Development Approved, HMD required, QA Approved :tada:, bug

#13838 fixing scripting window visiblity and size issues
  scripts/developer/debugging/debugWindow.js
Labels: Client, QA Approved :tada:

#13949 Scale Collision Pick to match parent
  interface/src/avatar/MyAvatarHeadTransformNode.cpp
  interface/src/raypick/CollisionPick.cpp
  interface/src/raypick/CollisionPick.h
  interface/src/raypick/PickScriptingInterface.cpp
  interface/src/ui/overlays/OverlayTransformNode.cpp
  interface/src/ui/overlays/OverlayTransformNode.h
  libraries/avatars-renderer/src/avatars-renderer/AvatarTransformNode.cpp
  libraries/avatars-renderer/src/avatars-renderer/AvatarTransformNode.h
  libraries/entities/src/EntityTransformNode.cpp
  libraries/entities/src/EntityTransformNode.h
  libraries/shared/src/NestableTransformNode.cpp
  libraries/shared/src/NestableTransformNode.h
  libraries/shared/src/RegisteredMetaTypes.h
Labels: Development Approved, Engine, HMD required, QA Approved :tada:, Scripting API change

#13958 Fix bloom on edges
  libraries/render-utils/src/DeferredFramebuffer.cpp
Labels: Development Approved, Engine, QA Approved :tada:, bug

#13956 Move animation stats into its own Menu
  interface/resources/qml/AnimStats.qml
  interface/resources/qml/Stats.qml
  interface/src/Application.cpp
  interface/src/Menu.cpp
  interface/src/Menu.h
  interface/src/ui/AnimStats.cpp
  interface/src/ui/AnimStats.h
  interface/src/ui/Stats.cpp
  interface/src/ui/Stats.h
  libraries/animation/src/AnimBlendLinear.cpp
  libraries/animation/src/AnimBlendLinearMove.cpp
  libraries/animation/src/AnimContext.h
  libraries/animation/src/AnimNode.cpp
  libraries/animation/src/AnimNode.h
  libraries/animation/src/AnimStateMachine.cpp
  libraries/animation/src/AnimStateMachine.h
  libraries/animation/src/AnimVariant.cpp
  libraries/animation/src/AnimVariant.h
  libraries/animation/src/Rig.cpp
  libraries/animation/src/Rig.h
Labels: Avatar, QA Approved :tada:, QA Ready

#13931 Remove some debug logging left in the safe landing module
  interface/src/octree/SafeLanding.cpp
Labels: Development Approved, QA Approved :tada:

#13916 send ignoring avatar removal to ignored avatar
  assignment-client/src/avatars/AvatarMixer.cpp
Labels: Development Approved, QA Approved :tada:

#13934 Check that a requested listening port is able to be used
  libraries/networking/src/LimitedNodeList.cpp
Labels: QA Approved :tada:, Server & Network

#13663 Enable LOD manager on android
  interface/src/Application.cpp
  interface/src/LODManager.h
Labels: Android, Engine, QA Approved :tada:

#13960 Add detailed profile range for avatar unpacking
  libraries/avatars/src/AvatarHashMap.cpp
Labels: Development Approved, Engine, QA Approved :tada:, Server & Network

#13885 fix Agent teardown of recording and ScriptEngine(s)
  assignment-client/src/Agent.cpp
  libraries/avatars-renderer/src/avatars-renderer/Head.cpp
Labels: QA Approved :tada:, Server & Network

#13886 Improve HMD Menu page navigation
  interface/resources/qml/hifi/audio/Audio.qml
  interface/resources/qml/hifi/dialogs/TabletDCDialog.qml
  interface/resources/qml/hifi/dialogs/TabletEntityStatistics.qml
  interface/resources/qml/hifi/tablet/ControllerSettings.qml
  interface/resources/qml/hifi/tablet/TabletMenu.qml
  interface/resources/qml/hifi/tablet/TabletMenuStack.qml
  interface/resources/qml/hifi/tablet/tabletWindows/TabletPreferencesDialog.qml
  interface/src/Menu.cpp
Labels: Client, Development Approved, QA Approved :tada:

#13967 Add comment to Assets.sendFakeHandshake about excluding jsdoc
  libraries/script-engine/src/AssetScriptingInterface.h
Labels: Development Approved, QA Approved :tada:

#13957 fix keyboard collapsing in VR/goto
  interface/resources/qml/hifi/tablet/TabletAddressDialog.qml
Labels: Client, Development Approved, QA Approved :tada:

#13964 Destroy script thread on finish instead of on ScriptEngine destroyed
  libraries/script-engine/src/ScriptEngine.cpp
Labels: Create, Development Approved, QA Approved :tada:

#13959 MS17841: CreateApp - Adjust default position of new entities
  scripts/system/edit.js
Labels: Development Approved, QA Approved :tada:

#13968 MS18269: Fix Reloading Scripts with Create open crashes system
  scripts/system/modules/createWindow.js
Labels: Create, Development Approved, QA Approved :tada:

#13922 Optimize the vertex formats of meshes for less input buffer bindings
  libraries/fbx/src/FBXReader_Mesh.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLBackend.h
  libraries/gpu-gl-common/src/gpu/gl/GLBackendInput.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLBackendPipeline.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLBuffer.h
  libraries/gpu-gl/src/gpu/gl41/GL41Backend.h
  libraries/gpu-gl/src/gpu/gl41/GL41BackendBuffer.cpp
  libraries/gpu-gl/src/gpu/gl41/GL41BackendInput.cpp
  libraries/gpu-gl/src/gpu/gl45/GL45Backend.h
  libraries/gpu-gl/src/gpu/gl45/GL45BackendBuffer.cpp
  libraries/gpu-gl/src/gpu/gl45/GL45BackendInput.cpp
  libraries/gpu-gles/src/gpu/gles/GLESBackend.h
  libraries/gpu-gles/src/gpu/gles/GLESBackendBuffer.cpp
  libraries/gpu/src/gpu/Batch.h
  libraries/gpu/src/gpu/Stream.h
  libraries/graphics/src/graphics/Geometry.cpp
  libraries/graphics/src/graphics/Geometry.h
Labels: Android Smoke Required, Development Approved, Engine, HMD required, Mac Required, QA Approved :tada:

#13722 MS13955: Audio Stats are blank
  scripts/developer/utilities/audio/Stats.qml
  scripts/developer/utilities/audio/TabletStats.qml
Labels: Client, Development Approved, QA Approved :tada:, bug

#13962 Fix for blendshapes playing back in recordings at 2x their proper values
  assignment-client/src/Agent.cpp
  assignment-client/src/avatars/ScriptableAvatar.cpp
  assignment-client/src/avatars/ScriptableAvatar.h
Labels: Avatar, Development Approved, QA Approved :tada:

#13970 Ensure a web overlay doesn't access an invalid tabletScriptingInterface
  interface/src/ui/overlays/Web3DOverlay.cpp
Labels: Development Approved, Engine, QA Approved :tada:, bug

#13943 Improvements to entity list loading times
  scripts/system/html/entityList.html
  scripts/system/html/js/entityList.js
  scripts/system/libraries/EditEntityList.qml
  scripts/system/libraries/entityList.js
Labels: Create, Development Approved, QA Approved :tada:

#13897 filter out left/right hands from joints list in avatarapp
  interface/resources/qml/hifi/AvatarApp.qml
  interface/resources/qml/hifi/avatarapp/AdjustWearables.qml
Labels: Client, Development Approved, QA Approved :tada:

#13865 Edit handle scale improvements
  scripts/system/libraries/entitySelectionTool.js
Labels: Create, Development Approved, QA Approved :tada:

#13911 Avatar App: stop reloading existing selected bookmarks on app relaunch (master)
  interface/resources/qml/hifi/AvatarApp.qml
Labels: Client, Development Approved, QA Approved :tada:

#13972 Replacing cpu timing calls from gl to std::chrono
  libraries/gpu-gl-common/src/gpu/gl/GLBackendQuery.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLQuery.h
Labels: Development Approved, Engine, HMD required, Mac Required, QA Approved :tada:

#13912 handle agent avatar clear on avatar mixer disconnect
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/avatar/AvatarManager.h
  libraries/avatars/src/AvatarHashMap.cpp
  libraries/avatars/src/AvatarHashMap.h
Labels: Development Approved, QA Approved :tada:, Server & Network

#13961 Pop up login dialog on launch
  interface/resources/images/eyeClosed.svg
  interface/resources/images/eyeOpen.svg
  interface/resources/qml/LoginDialog.qml
  interface/resources/qml/LoginDialog/+android/LinkAccountBody.qml
  interface/resources/qml/LoginDialog/LinkAccountBody.qml
  interface/resources/qml/windows/ModalFrame.qml
  interface/resources/qml/windows/ModalWindow.qml
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/ui/LoginDialog.cpp
  interface/src/ui/LoginDialog.h
  libraries/networking/src/UserActivityLogger.cpp
Labels: Client, Development Approved, QA Approved :tada:

#13973 Avatar loading orb now indicates loading status
  interface/src/avatar/OtherAvatar.cpp
  interface/src/avatar/OtherAvatar.h
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
Labels: Avatar, Development Approved, QA Approved :tada:

#13974 Fix a missing std::chrono::duration_cast
  libraries/gpu-gl-common/src/gpu/gl/GLBackendQuery.cpp
Labels: Development Approved, Engine, QA Ready

#13938 Interstitial Page with 404 Redirect
  interface/CMakeLists.txt
  interface/resources/images/loadingBar_placard.png
  interface/resources/images/loadingBar_progress.png
  interface/resources/meshes/redirect/oopsDialog_auth.fbx
  interface/resources/meshes/redirect/oopsDialog_auth.png
  interface/resources/meshes/redirect/oopsDialog_protocol.fbx
  interface/resources/meshes/redirect/oopsDialog_protocol.png
  interface/resources/meshes/redirect/oopsDialog_vague.fbx
  interface/resources/meshes/redirect/oopsDialog_vague.png
  interface/resources/qml/hifi/tablet/TabletAddressDialog.qml
  interface/resources/serverless/redirect.json
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/ConnectionMonitor.cpp
  interface/src/ConnectionMonitor.h
  interface/src/avatar/AvatarManager.cpp
  interface/src/avatar/AvatarManager.h
  interface/src/octree/OctreePacketProcessor.cpp
  interface/src/octree/OctreePacketProcessor.h
  interface/src/octree/SafeLanding.cpp
  interface/src/octree/SafeLanding.h
  interface/src/scripting/WindowScriptingInterface.cpp
  interface/src/scripting/WindowScriptingInterface.h
  interface/src/ui/Stats.cpp
  libraries/audio-client/src/AudioClient.cpp
  libraries/audio-client/src/AudioClient.h
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities-renderer/src/RenderableZoneEntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/entities/src/ModelEntityItem.cpp
  libraries/entities/src/ZoneEntityItem.cpp
  libraries/networking/src/AddressManager.cpp
  libraries/networking/src/AddressManager.h
  libraries/networking/src/DomainHandler.cpp
  libraries/networking/src/DomainHandler.h
  scripts/defaultScripts.js
  scripts/system/interstitialPage.js
Labels: Android Smoke Required, Client, Feedback Welcome, QA Approved :tada:

#13623 MS16192: Fix Near Grabbing After Using Web Entity
  scripts/system/controllers/controllerModules/highlightNearbyEntities.js
  scripts/system/controllers/controllerModules/inEditMode.js
  scripts/system/controllers/controllerModules/inVREditMode.js
  scripts/system/controllers/controllerModules/nearActionGrabEntity.js
  scripts/system/controllers/controllerModules/nearGrabHyperLinkEntity.js
  scripts/system/controllers/controllerModules/nearParentGrabEntity.js
  scripts/system/controllers/controllerModules/nearTrigger.js
  scripts/system/controllers/controllerModules/webSurfaceLaserInput.js
Labels: Client, Development Approved, QA Approved :tada:, bug

#13980 revert avatar entity XORing, perform avatar entity cleanup in handleRemovedAvatar
  interface/src/avatar/AvatarManager.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
  libraries/avatars/src/AvatarHashMap.cpp
  libraries/avatars/src/AvatarTraits.h
  libraries/avatars/src/ClientTraitsHandler.cpp
  libraries/avatars/src/ClientTraitsHandler.h
Labels: Development Approved, QA Approved :tada:, Server & Network

#13954 Reduce needless smart pointer duplication
  libraries/gpu-gl-common/src/gpu/gl/GLBackend.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLBackend.h
  libraries/gpu-gl-common/src/gpu/gl/GLBackendInput.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLBackendOutput.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLBackendPipeline.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLBackendTexture.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLPipeline.cpp
  libraries/gpu-gl/src/gpu/gl41/GL41Backend.h
  libraries/gpu-gl/src/gpu/gl41/GL41BackendBuffer.cpp
  libraries/gpu-gl/src/gpu/gl41/GL41BackendInput.cpp
  libraries/gpu-gl/src/gpu/gl45/GL45Backend.h
  libraries/gpu-gl/src/gpu/gl45/GL45BackendBuffer.cpp
  libraries/gpu-gl/src/gpu/gl45/GL45BackendInput.cpp
  libraries/gpu-gles/src/gpu/gles/GLESBackend.h
  libraries/gpu-gles/src/gpu/gles/GLESBackendBuffer.cpp
  libraries/gpu/src/gpu/Batch.cpp
  libraries/gpu/src/gpu/Batch.h
  libraries/gpu/src/gpu/Framebuffer.cpp
  libraries/gpu/src/gpu/Framebuffer.h
Labels: Android Smoke Required, Development Approved, Engine, QA Approved :tada:

#13985 Fixing user activity logging for encourage login
  interface/resources/qml/LoginDialog/LinkAccountBody.qml
Labels: Client, Critical Fix, Development Approved, QA Approved :tada:

#13982 HMD Edit Handles - add highlighting and fix center scale cube
  scripts/system/edit.js
  scripts/system/libraries/entitySelectionTool.js
Labels: Create, Development Approved, HMD required, QA Approved :tada:, bug

#13988 Fix crash when teleporting into avatars with bubble active
  libraries/physics/src/PhysicsEngine.cpp
Labels: Development Approved, Engine, HMD required, QA Approved :tada:, bug

#13894 Performance improvements for Avatar Mixer
  assignment-client/src/avatars/AvatarMixerClientData.cpp
  assignment-client/src/avatars/AvatarMixerClientData.h
  assignment-client/src/avatars/AvatarMixerSlave.cpp
  interface/src/avatar/AvatarManager.cpp
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
  libraries/networking/src/udt/Socket.cpp
  libraries/networking/src/udt/Socket.h
  libraries/shared/src/PrioritySortUtil.h
Labels: Development Approved, Engine, QA Approved :tada:, Server & Network

#13983 disable interstitial by default and fix crash
  interface/src/Application.cpp
  interface/src/octree/SafeLanding.cpp
  scripts/defaultScripts.js
Labels: Client, Critical Fix, Development Approved, QA Approved :tada:

#13984 Fixing Error State for Timeout/localhost Redirection
  interface/resources/meshes/redirect/oopsDialog_timeout.fbx
  interface/resources/meshes/redirect/oopsDialog_timeout.png
  interface/resources/meshes/redirect/oopsDialog_vague.fbx
  interface/src/Application.cpp
  libraries/networking/src/AddressManager.cpp
  libraries/networking/src/DomainHandler.cpp
  libraries/networking/src/DomainHandler.h
Labels: Client, Critical Fix, Development Approved, QA Approved :tada:, Server & Network, bug

#13989 Fix login fail twice call
  libraries/networking/src/AccountManager.cpp
  libraries/networking/src/AccountManager.h
Labels: Development Approved, QA Approved :tada:, Server & Network

#13993 Revert "Fix login fail twice call"
  libraries/networking/src/AccountManager.cpp
  libraries/networking/src/AccountManager.h
Labels: Server & Network

#13991 Fix GOTO TheSpot Button in Interstitial Page
  interface/resources/images/interstitialPage/goTo_button.png
  scripts/system/interstitialPage.js
Labels: Client, Critical Fix, Development Approved, QA Approved :tada:

#13986 Fix ESS crash caused by concurrent access to _entityScripts
  libraries/script-engine/src/ScriptEngine.cpp
  libraries/script-engine/src/ScriptEngine.h
Labels: Development Approved, QA Approved :tada:, Server & Network

#13995 Attempt to fix LOD setting getting stuck
  interface/src/LODManager.cpp
Labels: Development Approved, Engine, QA Approved :tada:, QA Ready, bug

#13996 Text tuning for wallet setup call to action
  scripts/system/html/js/marketplacesInject.js
  scripts/system/notifications.js
Labels: Commerce, QA Approved :tada:

#13992 Fix entity list search case-sensitivity and allow id search
  scripts/system/html/js/entityList.js
Labels: Create, Development Approved, QA Approved :tada:, bug

#13937 Safe Teleport Target
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  interface/src/raypick/CollisionPick.cpp
  interface/src/raypick/CollisionPick.h
  interface/src/raypick/PickScriptingInterface.cpp
  interface/src/raypick/PickScriptingInterface.h
  libraries/avatars/src/AvatarData.h
  libraries/physics/src/PhysicsEngine.cpp
  libraries/physics/src/PhysicsEngine.h
  libraries/shared/src/RegisteredMetaTypes.h
  scripts/system/controllers/controllerModules/teleport.js
Labels: Client, Development Approved, QA Approved :tada:, Scripting API change

#13998 don't zero kinematic velocities when releasing simulation ownership
  libraries/physics/src/EntityMotionState.cpp
  libraries/physics/src/PhysicalEntitySimulation.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#14003 Fix snapshot settings issue in HMD
  interface/resources/qml/hifi/tablet/tabletWindows/TabletPreferencesDialog.qml
Labels: Client, Development Approved, QA Approved :tada:

#13999 Don't popup login dialog in android
  interface/src/Application.cpp
Labels: Android Smoke Required, Client, Development Approved, QA Approved :tada:

#13969 Fixing Model animation bugs
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.h
  libraries/entities/src/ModelEntityItem.cpp
  libraries/entities/src/ModelEntityItem.h
Labels: Development Approved, Engine, QA Approved :tada:, bug

#14014 Fix entity list selection failing when selecting entities not in list
  scripts/system/html/js/entityList.js
Labels: Create, Development Approved, QA Approved :tada:

#14019 Fix sorting of entity list not working as expected for visible/lock
  scripts/system/html/js/entityList.js
Labels: Create, Development Approved, QA Approved :tada:

#13971 Correct transparent parabola shader
  interface/src/raypick/ParabolaPointer.cpp
  libraries/render-utils/src/parabola_translucent.slf
  libraries/render-utils/src/render-utils/parabola_translucent.slp
Labels: Development Approved, Engine, QA Approved :tada:, bug

#13933 Fix particle acceleration spread
  libraries/entities-renderer/src/RenderableParticleEffectEntityItem.cpp
Labels: Development Approved, Engine, QA Approved :tada:, bug

#13987 Discovery Notifications Project Checkpoint: Discovery apps now use AppUI module; PEOPLE app notifications
  interface/resources/icons/tablet-icons/people-a-msg.svg
  interface/resources/icons/tablet-icons/people-i-msg.svg
  interface/resources/qml/hifi/Pal.qml
  interface/resources/qml/hifi/commerce/wallet/Wallet.qml
  interface/src/ui/overlays/ContextOverlayInterface.cpp
  interface/src/ui/overlays/ContextOverlayInterface.h
  scripts/modules/appUi.js
  scripts/system/commerce/wallet.js
  scripts/system/help.js
  scripts/system/html/js/marketplacesInject.js
  scripts/system/marketplaces/marketplaces.js
  scripts/system/pal.js
  scripts/system/snapshot.js
  scripts/system/tablet-goto.js
Labels: Commerce, Development Approved, Discovery, QA Approved :tada:

#14017 RC73: fix for deadlock in other avatar entity removal from tree
  interface/src/avatar/AvatarManager.cpp
  interface/src/avatar/AvatarManager.h
  libraries/avatars/src/AvatarHashMap.cpp
  libraries/avatars/src/AvatarHashMap.h
Labels: Client, Development Approved, QA Approved :tada:, Server & Network

#14030 Toggle going to 404 redirect domain (RC73)
  interface/src/ConnectionMonitor.cpp
  interface/src/ConnectionMonitor.h
  libraries/networking/src/AddressManager.h
  libraries/networking/src/DomainHandler.cpp
  libraries/networking/src/DomainHandler.h
Labels: Android Smoke Required, Client, QA Approved :tada:, Server & Network

#14022 Fix AMD highlighting effect
  libraries/gpu-gl/src/gpu/gl41/GL41BackendShader.cpp
  libraries/render-utils/src/Highlight.slh
  libraries/render-utils/src/Highlight_aabox.slv
Labels: Development Approved, Engine, Mac Required, QA Approved :tada:

#14036 tweak avatar update priority coefficients for load tests
  libraries/avatars/src/AvatarData.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#14039 0.73.0: tweak avatar update priority coefs for load tests
  libraries/avatars/src/AvatarData.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#14001 Fixing double loginFailed
  libraries/networking/src/AccountManager.cpp
  libraries/networking/src/AccountManager.h
Labels: Client, Development Approved, QA Approved :tada:, Server & Network

#14050 tweak avatar update priority coefs for load tests
  libraries/avatars/src/AvatarData.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#14043 Fix sorting of entity list not working as expected
  scripts/system/html/js/entityList.js
Labels: Create, Development Approved, QA Approved :tada:

#14038 Fix Interstitial GoTo button stretch
  scripts/system/interstitialPage.js
Labels: Client, Development Approved, QA Approved :tada:

#14056 make settings thread safe
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  libraries/shared/src/SettingManager.cpp
  libraries/shared/src/SettingManager.h
Labels: Client, QA Approved :tada:, bug

#14048 don't call enterEntity before the entity's script is loaded
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/script-engine/src/ScriptEngine.cpp
  libraries/script-engine/src/ScriptEngine.h
Labels: Client, Development Approved, QA Approved :tada:, bug

#14041 Fix entity list selection failing when selecting entities not in list
  scripts/system/html/js/entityList.js
Labels: Create, Development Approved, QA Approved :tada:

#14057 make settings thread safe
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  libraries/shared/src/SettingManager.cpp
  libraries/shared/src/SettingManager.h
Labels: Client, QA Approved :tada:, bug

#14004 Small Improvements to Anim Stats
  interface/resources/qml/AnimStats.qml
  interface/src/ui/AnimStats.cpp
  interface/src/ui/AnimStats.h
  libraries/animation/src/AnimStateMachine.cpp
  libraries/animation/src/AnimVariant.cpp
Labels: Avatar, Development Approved, QA Approved :tada:

#14066 73: Fix blendshape crash on avatar removal
  libraries/render-utils/src/Model.cpp
Labels: Critical Fix, Development Approved, Engine, QA Approved :tada:, bug

#14065 Fix blendshape crash on avatar removal
  libraries/render-utils/src/Model.cpp
Labels: Development Approved, Engine, QA Approved :tada:, bug

#14067 73.1: Fix blendshape crash on avatar removal
  libraries/render-utils/src/Model.cpp
Labels: Development Approved, Engine, QA Approved :tada:, bug

#14029 Remove verbose logging of keyboard messages in edit.js and gridTool.js
  scripts/system/edit.js
  scripts/system/libraries/gridTool.js
Labels: Create, Development Approved, QA Approved :tada:

#13981 Android settings (AEC)
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/cpp/native.cpp
  android/app/src/main/java/io/highfidelity/hifiinterface/InterfaceActivity.java
  android/app/src/main/java/io/highfidelity/hifiinterface/MainActivity.java
  android/app/src/main/java/io/highfidelity/hifiinterface/fragment/SettingsFragment.java
  android/app/src/main/java/io/highfidelity/hifiinterface/receiver/HeadsetStateReceiver.java
  android/app/src/main/res/menu/menu_navigation.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/xml/settings.xml
  android/build.gradle
  interface/src/AndroidHelper.cpp
  interface/src/AndroidHelper.h
  libraries/audio-client/src/AudioClient.cpp
  libraries/audio-client/src/AudioClient.h
Labels: Android, Engine, QA Approved :tada:

#14008 fix bug that caused localAngularVelocity to get zeroed out
  libraries/entities/src/EntityScriptingInterface.cpp
  scripts/system/libraries/entitySelectionTool.js
Labels: Client, Development Approved, QA Approved :tada:, bug

#14061 Patch for toggle 404 redirect (RC 73)
  interface/src/Application.cpp
  interface/src/ConnectionMonitor.cpp
  interface/src/ConnectionMonitor.h
  interface/src/octree/SafeLanding.cpp
  interface/src/scripting/WindowScriptingInterface.cpp
  interface/src/scripting/WindowScriptingInterface.h
  libraries/networking/src/DomainHandler.cpp
  libraries/networking/src/DomainHandler.h
Labels: Client, Critical Fix, Development Approved, QA Approved :tada:, Server & Network, bug

#14070 0.73.0 fix MyAvatar-vs-OtherAvatar collisions
  interface/src/avatar/AvatarManager.cpp
  interface/src/avatar/OtherAvatar.cpp
  interface/src/avatar/OtherAvatar.h
Labels: Development Approved, Engine, QA Approved :tada:

#14073 Working on Vive shutdown issues
  interface/src/Application.cpp
  libraries/audio-client/src/AudioClient.cpp
  libraries/audio-client/src/AudioClient.h
  libraries/audio-client/src/AudioPeakValues.cpp
  libraries/audio/src/Sound.cpp
  libraries/audio/src/Sound.h
Labels: Development Approved, Engine, QA Approved :tada:

#14072 Fix avatar highlighting
  libraries/render-utils/src/HighlightEffect.cpp
  libraries/render-utils/src/HighlightEffect.h
Labels: Development Approved, Engine, QA Approved :tada:, bug

#14082 FB18069 - rc73
  interface/src/Application.cpp
  libraries/audio-client/src/AudioClient.cpp
  libraries/audio-client/src/AudioClient.h
  libraries/audio-client/src/AudioPeakValues.cpp
  libraries/audio/src/Sound.cpp
  libraries/audio/src/Sound.h
Labels: Development Approved, Engine, QA Approved :tada:, Vive Required

#14024 Toggle going to 404 redirect domain
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/ConnectionMonitor.cpp
  interface/src/ConnectionMonitor.h
  interface/src/scripting/WindowScriptingInterface.cpp
  interface/src/scripting/WindowScriptingInterface.h
  libraries/networking/src/AddressManager.h
  libraries/networking/src/DomainHandler.cpp
  libraries/networking/src/DomainHandler.h
Labels: Android Smoke Required, Client, Development Approved, QA Approved :tada:, Server & Network

#14018 fix for deadlock in other avatar entity removal from tree
  interface/src/avatar/AvatarManager.cpp
  interface/src/avatar/AvatarManager.h
  libraries/avatars/src/AvatarHashMap.cpp
  libraries/avatars/src/AvatarHashMap.h
Labels: Client, Critical Fix, Development Approved, QA Approved :tada:, Server & Network

#14058 fix equip while keeping new functionality
  scripts/system/controllers/controllerModules/highlightNearbyEntities.js
  scripts/system/controllers/controllerModules/inEditMode.js
  scripts/system/controllers/controllerModules/inVREditMode.js
  scripts/system/controllers/controllerModules/nearActionGrabEntity.js
  scripts/system/controllers/controllerModules/nearGrabHyperLinkEntity.js
  scripts/system/controllers/controllerModules/nearParentGrabEntity.js
  scripts/system/controllers/controllerModules/nearTrigger.js
  scripts/system/controllers/controllerModules/webSurfaceLaserInput.js
Labels: Client, Development Approved, QA Approved :tada:

#14077 Prevent thread issues with PickResults modified by Pointers
  interface/src/raypick/LaserPointer.cpp
  interface/src/raypick/LaserPointer.h
  interface/src/raypick/ParabolaPointer.cpp
  interface/src/raypick/ParabolaPointer.h
  interface/src/raypick/StylusPointer.cpp
  interface/src/raypick/StylusPointer.h
  libraries/pointers/src/Pointer.cpp
  libraries/pointers/src/Pointer.h
Labels: Development Approved, Engine, QA Approved :tada:, bug

#14081 Improve ModelBlender queuing
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
Labels: Development Approved, Engine, QA Approved :tada:

#14084 Fix avatars loading below the ground bug
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
Labels: Avatar, Development Approved, QA Approved :tada:

#14090 73.1: Improve ModelBlender queuing
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
Labels: Development Approved, Engine, QA Approved :tada:

#14031 Discovery Notifications Project: Notifications for PEOPLE, WALLET, MARKET, and GOTO
  interface/resources/icons/tablet-icons/goto-a-msg.svg
  interface/resources/icons/tablet-icons/goto-i-msg.svg
  interface/resources/icons/tablet-icons/wallet-a-msg.svg
  interface/resources/icons/tablet-icons/wallet-i-msg.svg
  interface/resources/qml/hifi/commerce/purchases/Purchases.qml
  interface/resources/qml/hifi/commerce/wallet/WalletHome.qml
  scripts/modules/appUi.js
  scripts/modules/request.js
  scripts/system/commerce/wallet.js
  scripts/system/marketplaces/marketplaces.js
  scripts/system/pal.js
  scripts/system/tablet-goto.js
Labels: Commerce, Development Approved, Discovery, QA Approved :tada:

#14002 Tray Notifier updates
  interface/src/Application.cpp
  interface/src/commerce/QmlCommerce.cpp
  interface/src/commerce/QmlCommerce.h
  interface/src/main.cpp
  libraries/networking/src/NetworkingConstants.h
  scripts/modules/appUi.js
  server-console/resources/tray-menu-notification.png
  server-console/src/main.js
  server-console/src/modules/hf-acctinfo.js
  server-console/src/modules/hf-app.js
  server-console/src/modules/hf-notifications.js
  server-console/src/modules/hf-process.js
Labels: Development Approved, Discovery, QA Approved :tada:

#14097 73.1: remove hifiSixense DLL on install
  cmake/templates/NSIS.template.in
Labels: Server & Network

#14107 Fix application uninstall in marketplace item tester
  interface/resources/qml/hifi/commerce/marketplaceItemTester/MarketplaceItemTester.qml
Labels: Commerce, Development Approved, QA Approved :tada:

#14009 fix scaling of worn shape entities
  libraries/entities-renderer/src/RenderableShapeEntityItem.cpp
Labels: Client, Development Approved, QA Approved :tada:, bug

#14045 don't call enterEntity before the entity's script is loaded
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/script-engine/src/ScriptEngine.cpp
  libraries/script-engine/src/ScriptEngine.h
Labels: Client, Development Approved, Project Approved, QA Approved :tada:, bug

#14103 minimal time handshake
  scripts/system/makeUserConnection.js
Labels: Development Approved, Discovery, Project Approved, QA Approved :tada:

#14095 Audio-mixer optimizations
  libraries/audio/src/AudioHRTF.h
Labels: Development Approved, Project Approved, QA Approved :tada:, Server & Network

#14023 Only call selectEntity once triggered when using edit handles
  scripts/system/controllers/controllerModules/inEditMode.js
Labels: Create, Development Approved, HMD required, Project Approved, QA Approved :tada:, bug
