Repository highfidelity/hifi, pull requests merged in 2018-07, with the labels that each got.

#13510 Fix ACs startup crash
  assignment-client/src/Agent.cpp
  assignment-client/src/audio/AudioMixer.cpp
  assignment-client/src/audio/AudioMixer.h
  assignment-client/src/scripts/EntityScriptServer.cpp
  libraries/plugins/src/plugins/PluginManager.cpp
  libraries/plugins/src/plugins/PluginManager.h
Labels: QA Approved :tada:, Release Blocker, Server & Network

#13481 Optional particle explorer properties fixes
  scripts/system/edit.js
  scripts/system/particle_explorer/hifi-entity-ui.js
  scripts/system/particle_explorer/particleExplorerTool.js
Labels: Create, Development Approved, QA Ready

#13494 Particle spreads backwards compatibility
  libraries/entities/src/EntityTree.cpp
Labels: Create, Development Approved, Engine, QA Approved :tada:

#13493 Resolving issue where VR input for movement stops emotes
  scripts/system/emote.js
Labels: Development Approved, QA Approved :tada:

#13511 Fix SpinnerSliderPreference Class, Update Mouse Sensitivity Menu
  interface/resources/qml/dialogs/preferences/SpinnerSliderPreference.qml
  interface/src/ui/PreferencesDialog.cpp
Labels: Client, Development Approved, QA Approved :tada:

#13040 [BugFix] EntityList UncaughtException in that.sendUpdate
  scripts/system/libraries/entityList.js
Labels: Create, Development Approved, QA Approved :tada:

#13518 Fix MS16390: Correctly update UI when Buy endpoint fails
  interface/resources/qml/hifi/commerce/checkout/Checkout.qml
Labels: Commerce, QA Approved :tada:, bug

#13515 Shadow on Mac bug fix
  libraries/gpu-gl-common/src/gpu/gl/GLBackendPipeline.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLTexture.cpp
  libraries/gpu-gl/src/gpu/gl41/GL41BackendOutput.cpp
  libraries/gpu-gl/src/gpu/gl41/GL41BackendTexture.cpp
  libraries/gpu-gl/src/gpu/gl45/GL45BackendOutput.cpp
  libraries/gpu-gl/src/gpu/gl45/GL45BackendTexture.cpp
  libraries/gpu-gles/src/gpu/gles/GLESBackendOutput.cpp
  libraries/gpu-gles/src/gpu/gles/GLESBackendTexture.cpp
  libraries/gpu/src/gpu/Texture.cpp
  libraries/gpu/src/gpu/Texture.h
  libraries/gpu/src/gpu/Texture_ktx.cpp
  libraries/ktx/src/ktx/KTX.h
  libraries/render-utils/src/DebugDeferredBuffer.cpp
  libraries/render-utils/src/DebugDeferredBuffer.h
  libraries/render-utils/src/DeferredLightingEffect.cpp
  libraries/render-utils/src/LightStage.cpp
  libraries/render-utils/src/LightStage.h
  libraries/render-utils/src/RenderShadowTask.cpp
  libraries/render-utils/src/Shadow.slh
  libraries/render-utils/src/debug_deferred_buffer.slf
  libraries/render-utils/src/debug_deferred_buffer_shared.slh
  libraries/render/src/render/CullTask.cpp
Labels: Development Approved, Engine, QA Approved :tada:, outsource

#13512 Hitting Enter Key in Password Field To Login
  interface/resources/qml/LoginDialog/+android/LinkAccountBody.qml
  interface/resources/qml/LoginDialog/LinkAccountBody.qml
  interface/resources/qml/LoginDialog/SignUpBody.qml
Labels: Client, Development Approved, QA Approved :tada:

#13509 fix case where vegas congestion control would not re-send lost ACK
  libraries/networking/src/udt/Connection.cpp
Labels: Development Approved, Server & Network

#13505 Fixing a bug if the last session display plugin is an invalid name, resolve to default
  interface/src/Application.cpp
Labels: Engine, QA Approved :tada:

#13523 Fix blurry tablet if overlay is drawing
  libraries/render-utils/src/RenderCommonTask.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#13530 Really add safe check for targetDisplayPLugin
  interface/src/Application.cpp
Labels: Development Approved, Engine, QA Ready

#13532 Remove ray pick print statement
  scripts/system/controllers/handTouch.js
Labels: Avatar, Client

#13516 Use case-insensitive matching on friends lists in DomainGatekeeper
  domain-server/src/DomainGatekeeper.cpp
Labels: Development Approved, QA Approved :tada:, Server & Network

#13526 fixing still only snap in snap app
  scripts/system/html/js/SnapshotReview.js
Labels: Client, Development Approved, QA Approved :tada:

#13437 Fix for Avatar Lean in Direction of Movement: Bug 16075 (for RC70)
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MySkeletonModel.cpp
Labels: Avatar, Development Approved, HMD required, QA Approved :tada:, bug

#13525 fix for erroneous deactivation of slow-spinning kinematic objects
  libraries/entities/src/SimpleEntitySimulation.cpp
  libraries/physics/src/EntityMotionState.cpp
  libraries/physics/src/EntityMotionState.h
  libraries/physics/src/ObjectMotionState.cpp
  libraries/physics/src/ObjectMotionState.h
  libraries/physics/src/ThreadSafeDynamicsWorld.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#13524 fix configuration page
  interface/resources/qml/hifi/tablet/ControllerSettings.qml
  interface/resources/qml/hifi/tablet/OpenVrConfiguration.qml
Labels: Client, Development Approved, QA Approved :tada:, Vive Required

#13513 Tablet Asset Server dialog was instantiated twice
  interface/src/Application.cpp
Labels: Client, QA Approved :tada:

#13492 ScriptsModel instances should be created & destroyed on the same thread (for ESS)
  assignment-client/src/scripts/EntityScriptServer.cpp
Labels: Development Approved, QA Approved :tada:, Server & Network

#13410 Fix toggling edit handles between local/world space
  scripts/system/edit.js
  scripts/system/libraries/entitySelectionTool.js
Labels: Create, Development Approved, QA Approved :tada:

#13537 Moved "Show Overlays" menu item to Developer Menu
  interface/src/Menu.cpp
Labels: Client, Development Approved, QA Approved :tada:

#13540 Updating keyboard mapping .jpg to reflect keyboard/mouse mapping
  interface/resources/html/img/tablet-help-keyboard.jpg
Labels: Client, Development Approved

#13519 Bug fix for unexpected avatar knee shifts for users wearing Vive Trackers.
  interface/src/avatar/MySkeletonModel.cpp
  libraries/animation/src/Rig.cpp
  libraries/animation/src/Rig.h
Labels: Avatar, Development Approved, QA Approved :tada:, Vive Tracker Required

#13529 Fix number of rendering issues with some transparent objects on Mac and AMD GPUs
  libraries/gpu-gl-common/src/gpu/gl/GLBackendPipeline.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLBackendTransform.cpp
  libraries/render-utils/src/DeferredGlobalLight.slh
  libraries/render-utils/src/ForwardGlobalLight.slh
  libraries/render-utils/src/LightLocal.slh
  libraries/render-utils/src/LightingModel.slh
  libraries/render-utils/src/MaterialTextures.slh
  libraries/render-utils/src/forward_model_translucent.slf
  libraries/render-utils/src/model_translucent.slf
  libraries/render-utils/src/model_translucent_fade.slf
  libraries/render-utils/src/model_translucent_normal_map.slf
  libraries/render-utils/src/model_translucent_normal_map_fade.slf
  libraries/render-utils/src/model_translucent_unlit.slf
  libraries/render-utils/src/model_translucent_unlit_fade.slf
Labels: Development Approved, Engine, QA Approved :tada:, outsource

#13502 Fix closed eyelids when head is tilted down
  libraries/animation/src/Rig.cpp
  libraries/avatars-renderer/src/avatars-renderer/Head.cpp
  libraries/avatars/src/HeadData.cpp
  libraries/avatars/src/HeadData.h
  libraries/shared/src/FaceshiftConstants.cpp
  libraries/shared/src/FaceshiftConstants.h
Labels: Avatar, Development Approved, QA Approved :tada:, bug

#13539 Implement MS16413: Improve angularVelocity of printed Snaps
  scripts/system/snapshot.js
Labels: Discovery, QA Ready

#13546 keep buttons from drifing away from in-world display of controllers
  scripts/system/controllers/controllerDisplay.js
Labels: Client, Development Approved, HMD required, QA Approved :tada:

#13357 Entity Script Server memory leak when taking down EntityTree
  assignment-client/src/entities/EntityTreeHeadlessViewer.cpp
  assignment-client/src/scripts/EntityScriptServer.cpp
  libraries/networking/src/NLPacket.cpp
  libraries/octree/src/OctreeProcessor.cpp
  libraries/octree/src/OctreeProcessor.h
Labels: Development Approved, QA Approved :tada:, Server & Network

#13554 grab correct commit hash for conflicting PR
  cmake/macros/SetPackagingParameters.cmake
Labels: QA Approved :tada:

#13548 Fix avatar become more and more slanted over time while in HMD mode
  libraries/physics/src/CharacterController.cpp
Labels: Avatar, Development Approved, QA Approved :tada:, bug

#13545 Update BUILD_WIN.md
  BUILD_WIN.md
Labels: Development Approved, QA Approved :tada:

#13353 Remove extra textfield fro address bar input
  interface/resources/qml/hifi/tablet/TabletAddressDialog.qml
Labels: Client, Development Approved, QA Approved :tada:

#13496 InteractiveWindow scripting API
  interface/resources/qml/InteractiveWindow.qml
  interface/resources/qml/OverlayWindowTest.qml
  interface/src/Application.cpp
  interface/src/scripting/DesktopScriptingInterface.cpp
  interface/src/scripting/DesktopScriptingInterface.h
  libraries/qml/src/qml/OffscreenSurface.cpp
  libraries/ui/src/InteractiveWindow.cpp
  libraries/ui/src/InteractiveWindow.h
  scripts/developer/tests/interactiveWindowTest.js
Labels: Android Smoke Required, Client, Create, Development Approved, Engine, QA Approved :tada:, Scripting API change

#13458 Send repeated check-in requests for greater resilience
  libraries/networking/src/DomainHandler.cpp
  libraries/networking/src/DomainHandler.h
  libraries/networking/src/NodeList.cpp
Labels: Development Approved, QA Approved :tada:, Server & Network

#13550 fix crash in workload on timeout with entity-server
  libraries/workload/src/workload/Space.cpp
  libraries/workload/src/workload/Space.h
  libraries/workload/src/workload/Transaction.cpp
  libraries/workload/src/workload/Transaction.h
Labels: Development Approved, Engine, QA Approved :tada:

#13453 Support web3d overlays in android
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/cpp/native.cpp
  android/app/src/main/java/io/highfidelity/hifiinterface/InterfaceActivity.java
  android/app/src/main/java/io/highfidelity/hifiinterface/WebViewActivity.java
  android/app/src/main/java/io/highfidelity/hifiinterface/fragment/WebViewFragment.java
  android/app/src/main/java/org/qtproject/qt5/android/bindings/QtActivity.java
  android/app/src/main/res/drawable/ic_close.xml
  android/app/src/main/res/drawable/ic_expand.xml
  android/app/src/main/res/layout/activity_web_view.xml
  android/app/src/main/res/layout/fragment_web_view.xml
  android/app/src/main/res/layout/web_drawer.xml
  interface/resources/fonts/Cairo-SemiBold.ttf
  interface/resources/icons/+android/hand.svg
  interface/resources/qml/+android/Web3DOverlay.qml
  interface/resources/qml/controls/+android/WebEntityView.qml
  interface/src/AndroidHelper.cpp
  interface/src/AndroidHelper.h
  interface/src/Application.cpp
  interface/src/scripting/WindowScriptingInterface.cpp
  scripts/system/+android/clickWeb.js
  scripts/system/+android/modes.js
Labels: Android, Development Approved, Engine, QA Approved :tada:

#13558 Fix falling through floor
  interface/src/avatar/MyAvatar.cpp
  libraries/physics/src/CharacterController.cpp
Labels: Client, Development Approved, QA Approved :tada:

#13559 Fix AddressManager copyAddress/copyPath functionality
  interface/src/Application.cpp
  interface/src/Application.h
  libraries/networking/src/AddressManager.cpp
Labels: Client, Development Approved, QA Approved :tada:, Server & Network, bug

#13450 MS14398: Make tutorial not grabbable
  cmake/externals/serverless-content/CMakeLists.txt
Labels: Development Approved, QA Approved :tada:

#13521 Fixed Readme instructions on JSDoc
  tools/jsdoc/README.md
Labels: Create, Development Approved

#13561 Fix pointing at non-web overlays
  scripts/system/controllers/controllerModules/webSurfaceLaserInput.js
Labels: Client, Development Approved, HMD required, QA Approved :tada:, bug

#13549 Re-parent entities after duplicating and duplicate children with parents
  scripts/system/libraries/entitySelectionTool.js
Labels: Create, Development Approved, QA Approved :tada:, bug

#13432 Implement AvatarRequestIdentity and use if interface gets unknown avatar data
  assignment-client/src/avatars/AvatarMixer.cpp
  assignment-client/src/avatars/AvatarMixer.h
  interface/src/Application.cpp
  interface/src/avatar/AvatarManager.cpp
  interface/src/avatar/AvatarManager.h
  libraries/avatars/src/AvatarData.h
  libraries/avatars/src/AvatarHashMap.cpp
  libraries/avatars/src/AvatarHashMap.h
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
  tools/dissectors/1-hfudt.lua
Labels: Development Approved, QA Approved :tada:, Server & Network

#13556 Change deselecting entities to Ctrl + D and prevent W/A/S/D/E/Q movements with Ctrl
  interface/resources/controllers/keyboardMouse.json
  scripts/system/edit.js
Labels: Client, Create, Development Approved, QA Approved :tada:

#13543 Create snap-to-grid and translation fixes
  scripts/system/libraries/entitySelectionTool.js
Labels: Create, Development Approved, QA Approved :tada:

#13551 Improve punctuation on README.md
  README.md
Labels: Development Approved, QA Approved :tada:

#13538 Edit handle undefined event fix
  scripts/system/libraries/entitySelectionTool.js
Labels: Create, Development Approved, Mac Required, QA Approved :tada:, bug

#13562 Fix copyAddress/copyPath (RC69.1)
  interface/src/Application.cpp
  interface/src/Application.h
  libraries/networking/src/AddressManager.cpp
Labels: Client, Development Approved, QA Approved :tada:

#13571 Removing unused variables from lambda capture expressions
  interface/src/workload/GameWorkloadRenderer.cpp
  libraries/render-utils/src/Model.cpp
Labels: Development Approved

#13528 Step Detection From Head and Hands Tracking
  interface/resources/avatar/avatar-animation.json
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  libraries/shared/src/AvatarConstants.h
Labels: Avatar, Development Approved, HMD required, QA Approved :tada:

#13575 fix PAL connections count
  interface/resources/qml/hifi/Pal.qml
  interface/resources/qml/hifi/models/PSFListModel.qml
Labels: Development Approved, Discovery, QA Approved :tada:

#13563 Fix MS16480: Disable active ContextOverlays when disabling ContextOverlayInterface
  interface/src/ui/overlays/ContextOverlayInterface.cpp
  scripts/system/pal.js
Labels: Commerce, Development Approved, QA Ready, bug

#13565 [rc69.1] The client should render "something" for an avatar even if mesh or identity is not available
  interface/src/avatar/AvatarManager.cpp
  interface/src/avatar/MyAvatar.h
  interface/src/avatar/OtherAvatar.cpp
  interface/src/avatar/OtherAvatar.h
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
  libraries/avatars-renderer/src/avatars-renderer/OtherAvatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/OtherAvatar.h
Labels: Avatar, Development Approved, QA Approved :tada:

#13578 Fix MS16600: Prevent duplicate Spectator Camera models after crash
  unpublishedScripts/marketplace/spectator-camera/spectatorCamera.js
Labels: Development Approved, Discovery, QA Approved :tada:, bug

#13568 [rc69.1] - Fix closed eyelids when head is tilted down
  libraries/animation/src/Rig.cpp
  libraries/avatars-renderer/src/avatars-renderer/Head.cpp
  libraries/avatars/src/HeadData.cpp
  libraries/avatars/src/HeadData.h
  libraries/shared/src/FaceshiftConstants.cpp
  libraries/shared/src/FaceshiftConstants.h
Labels: Avatar, Development Approved, QA Approved :tada:, bug

#13557 Fix Bloom on Mac and hopefully Windows AMD (bug #15434)
  libraries/render-utils/src/BloomApply.shared.slh
  libraries/render-utils/src/BloomApply.slf
  libraries/render-utils/src/BloomEffect.cpp
  libraries/render-utils/src/BloomEffect.h
  libraries/render-utils/src/BloomThreshold.shared.slh
  libraries/render-utils/src/BloomThreshold.slf
  libraries/render-utils/src/HighlightEffect.cpp
  libraries/render-utils/src/HighlightEffect.h
  libraries/render-utils/src/Highlight_aabox.slv
Labels: Development Approved, Engine, QA Approved :tada:, outsource

#13574 more correct kinematic motion of grabbed things
  libraries/entities/src/EntityItem.cpp
  libraries/physics/src/EntityMotionState.cpp
  libraries/physics/src/PhysicalEntitySimulation.cpp
  libraries/shared/src/PhysicsHelpers.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#13583 Bump version of Spec Cam QML to 2.3
  unpublishedScripts/marketplace/spectator-camera/SpectatorCamera.qml
Labels: Discovery, QA Approved :tada:, bug

#13544 Fix haze on Mac (bug #15515)
  interface/resources/qml/Stats.qml
  interface/src/ui/Stats.cpp
  interface/src/ui/Stats.h
  libraries/graphics/src/graphics/Haze.cpp
  libraries/render-utils/src/DeferredGlobalLight.slh
  libraries/render-utils/src/DrawHaze.cpp
  libraries/render-utils/src/DrawHaze.h
  libraries/render-utils/src/ForwardGlobalLight.slh
  libraries/render-utils/src/Haze.slf
  libraries/render-utils/src/Haze.slh
  libraries/render-utils/src/RenderDeferredTask.cpp
Labels: Development Approved, Engine, QA Approved :tada:, outsource

#13579 RC70: Add Crashpad to Mac
  cmake/compiler.cmake
  cmake/externals/crashpad/CMakeLists.txt
  cmake/macros/AddCrashpad.cmake
  interface/src/Application.cpp
  interface/src/CrashHandler.h
  interface/src/CrashHandler_Breakpad.cpp
  interface/src/CrashHandler_Crashpad.cpp
  interface/src/CrashHandler_None.cpp
  interface/src/main.cpp
Labels: Development Approved, QA Approved :tada:

#13584 MS14743 again: More bandaids for preventing Snappy printouts from falling thru floor
  scripts/system/snapshot.js
Labels: Development Approved, Discovery, QA Approved :tada:, bug

#13587 MS9539: Update Controls Reference pages
  interface/resources/html/img/tablet-help-gamepad.jpg
  interface/resources/html/img/tablet-help-keyboard.jpg
  interface/resources/html/img/tablet-help-oculus.jpg
  interface/resources/html/img/tablet-help-vive.jpg
  interface/resources/html/img/tablet-help-windowsMR.jpg
  interface/resources/html/tabletHelp.html
  interface/src/Application.cpp
Labels: Client, Development Approved, QA Approved :tada:

#13572 Repair Transition effect
  libraries/render-utils/src/Fade.slh
  libraries/render-utils/src/FadeEffect.cpp
  libraries/render-utils/src/FadeObjectParams.shared.slh
  libraries/render/src/render/ShapePipeline.cpp
  libraries/render/src/render/ShapePipeline.h
  libraries/render/src/render/Transition.h
Labels: Development Approved, Engine, QA Approved :tada:

#13582 Render Scale Resolution applied only to 3D rendering not HUD
  interface/src/Application.cpp
  interface/src/Application_render.cpp
  interface/src/ui/ApplicationOverlay.cpp
  interface/src/ui/overlays/Overlays.cpp
  libraries/display-plugins/src/display-plugins/CompositorHelper.cpp
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.cpp
  libraries/render-utils/src/DeferredLightingEffect.cpp
  libraries/render-utils/src/DeferredLightingEffect.h
  libraries/render-utils/src/RenderDeferredTask.cpp
  libraries/render-utils/src/RenderDeferredTask.h
  libraries/render/src/render/ResampleTask.cpp
  libraries/render/src/render/ResampleTask.h
Labels: Development Approved, Engine, QA Ready, outsource

#13585 MS14979: Fix Animation FPS changeability
  libraries/entities/src/AnimationPropertyGroup.cpp
Labels: Create, Development Approved, Engine, QA Approved :tada:, bug

#13590 Fix MS16615: Don't early-remove .app.json we JUST installed
  interface/resources/qml/hifi/commerce/checkout/Checkout.qml
  interface/resources/qml/hifi/commerce/purchases/PurchasedItem.qml
  interface/resources/qml/hifi/commerce/purchases/Purchases.qml
  interface/src/commerce/QmlCommerce.cpp
  interface/src/commerce/QmlCommerce.h
Labels: Commerce, QA Approved :tada:, bug

#13591 Rollback PR 12888 by deleting alternative +android files
  interface/resources/qml/controls-uit/+android/Button.qml
  interface/resources/qml/controls-uit/+android/Table.qml
  interface/resources/qml/desktop/+android/Desktop.qml
  interface/resources/qml/dialogs/+android/CustomQueryDialog.qml
  interface/resources/qml/dialogs/+android/FileDialog.qml
  interface/resources/qml/dialogs/+android/QueryDialog.qml
  interface/resources/qml/dialogs/assetDialog/+android/AssetDialogContent.qml
Labels: Android, Development Approved, Engine, QA Approved :tada:

#13431 Android - Prevent pending downloads to happen when going back to home
  android/app/src/main/cpp/native.cpp
  android/app/src/main/java/io/highfidelity/hifiinterface/InterfaceActivity.java
  interface/src/AndroidHelper.cpp
  interface/src/AndroidHelper.h
  interface/src/Application.cpp
  interface/src/Application.h
  libraries/networking/src/NodeList.cpp
  libraries/networking/src/NodeList.h
Labels: Android, Development Approved, Engine, QA Approved :tada:, Server & Network

#13595 Fix for "PAL orbs are no longer visible through tablet/toolbar and objects in world"
  libraries/render-utils/src/RenderCommonTask.cpp
Labels: Development Approved, Engine, QA Approved :tada:, bug

#13594 Remove deprecated Window.raiseMainWindow API function
  interface/src/scripting/WindowScriptingInterface.cpp
  interface/src/scripting/WindowScriptingInterface.h
Labels: Client, Development Approved, Scripting API change

#13586 Remove AudioScriptingInterface.setStereoInput’s return value
  libraries/script-engine/src/AudioScriptingInterface.cpp
  libraries/script-engine/src/AudioScriptingInterface.h
Labels: Development Approved, QA Approved :tada:, Server & Network

#13601 Fix for "PAL orbs are no longer visible through tablet/toolbar and objects in world"
  libraries/render-utils/src/RenderCommonTask.cpp
Labels: Development Approved, Engine, QA Approved :tada:, bug

#13607 16683 Avatar App - Add to Favorites Button Not Working
  scripts/system/avatarapp.js
Labels: Client, Development Approved, QA Approved :tada:

#13592 Fix blue screen in VR mode due to NaN values
  libraries/physics/src/CharacterController.cpp
Labels: Avatar, Development Approved, QA Approved :tada:

#13603 Fix MS16701: Uninstall installed app before updating
  interface/resources/qml/hifi/commerce/purchases/PurchasedItem.qml
  interface/resources/qml/hifi/commerce/purchases/Purchases.qml
Labels: Commerce, Development Approved, QA Approved :tada:, bug

#13605 Fix not functional avatarapp when avatar bookmarks doesn't have 'avatarEntites' property
  scripts/system/avatarapp.js
Labels: Client, Development Approved, QA Approved :tada:

#13599 fixing combo boxes
  interface/resources/qml/controls-uit/ComboBox.qml
  interface/resources/qml/hifi/avatarapp/AdjustWearables.qml
Labels: Client, Development Approved, QA Approved :tada:

#13569 Only clamp edit handles in HMD when outside bounding box
  scripts/system/libraries/entitySelectionTool.js
Labels: Create, Development Approved, HMD required, QA Approved :tada:, bug

#13611 Fix blue screen in VR mode due to NaN values
  libraries/physics/src/CharacterController.cpp
Labels: Avatar, Development Approved, QA Approved :tada:

#13606 Re-host dependencies and update URLs to highfidelity.com
  cmake/externals/GifCreator/CMakeLists.txt
  cmake/externals/LibOVR/CMakeLists.txt
  cmake/externals/LibOVRPlatform/CMakeLists.txt
  cmake/externals/boostconfig/CMakeLists.txt
  cmake/externals/bullet/CMakeLists.txt
  cmake/externals/crashpad/CMakeLists.txt
  cmake/externals/draco/CMakeLists.txt
  cmake/externals/etc2comp/CMakeLists.txt
  cmake/externals/glad32es/CMakeLists.txt
  cmake/externals/glad41/CMakeLists.txt
  cmake/externals/glad45/CMakeLists.txt
  cmake/externals/gli/CMakeLists.txt
  cmake/externals/glm/CMakeLists.txt
  cmake/externals/hifiAudioCodec/CMakeLists.txt
  cmake/externals/neuron/CMakeLists.txt
  cmake/externals/nvtt/CMakeLists.txt
  cmake/externals/openvr/CMakeLists.txt
  cmake/externals/polyvox/CMakeLists.txt
  cmake/externals/quazip/CMakeLists.txt
  cmake/externals/sdl2/CMakeLists.txt
  cmake/externals/sixense/CMakeLists.txt
  cmake/externals/steamworks/CMakeLists.txt
  cmake/externals/tbb/CMakeLists.txt
  cmake/externals/vhacd/CMakeLists.txt
  cmake/externals/wasapi/CMakeLists.txt
  cmake/externals/zlib/CMakeLists.txt
Labels: Development Approved

#13608 Fix aligning selection to grid
  scripts/system/edit.js
  scripts/system/libraries/gridTool.js
Labels: Create, Development Approved, QA Approved :tada:, bug

#13613 Fix JSDoc for MyAvatar.getLeftPalmRotation and getRightPalmRotation
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
Labels: Create, Development Approved

#13612 FB16560 Active Avatar App - New Bookmarks Not correctly Starred
  interface/resources/qml/hifi/avatarapp/AvatarsModel.qml
Labels: Client, Development Approved, QA Approved :tada:

#13597 Fix entity list refresh when entity deleted
  scripts/system/edit.js
  scripts/system/libraries/entityList.js
Labels: Create, Development Approved, QA Approved :tada:, bug

#13609 Android - Refresh domains list with swipe
  android/app/src/main/java/io/highfidelity/hifiinterface/fragment/HomeFragment.java
  android/app/src/main/java/io/highfidelity/hifiinterface/provider/DomainProvider.java
  android/app/src/main/java/io/highfidelity/hifiinterface/provider/UserStoryDomainProvider.java
  android/app/src/main/java/io/highfidelity/hifiinterface/view/DomainAdapter.java
  android/app/src/main/res/layout/fragment_home.xml
Labels: Android, Development Approved, Engine, QA Approved :tada:

#13602 Fix MS16562: Massive PAL speedup!
  interface/resources/qml/hifi/Pal.qml
  interface/src/avatar/AvatarManager.cpp
  interface/src/avatar/AvatarManager.h
  scripts/system/pal.js
Labels: Development Approved, Discovery, QA Approved :tada:, bug

#13560 fix parent grab dropping and cullig flickering when flying at high velocities
  libraries/entities-renderer/src/RenderableEntityItem.cpp
  libraries/entities-renderer/src/RenderableEntityItem.h
  libraries/entities-renderer/src/RenderableParticleEffectEntityItem.cpp
  libraries/entities-renderer/src/RenderableShapeEntityItem.cpp
  libraries/entities-renderer/src/RenderableTextEntityItem.cpp
  libraries/entities-renderer/src/RenderableWebEntityItem.cpp
  scripts/system/controllers/controllerModules/nearParentGrabEntity.js
  scripts/system/libraries/controllerDispatcherUtils.js
Labels: Client, Development Approved, Engine, QA Ready

#13617 Reduce Frequent Flipping of Avatar Facing Direction By Resetting _headControllerFacingMovingAverage
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
Labels: Avatar, Development Approved, QA Approved :tada:

#13620 [RC70][FIX] Use create app in tablet mode when choosing to use tablet in desktop mode
  scripts/system/edit.js
  scripts/system/libraries/entityList.js
  scripts/system/libraries/gridTool.js
Labels: Create, Development Approved, QA Approved :tada:

#12656 Fix inability to 'bake' models on Windows
  tools/oven/src/BakerCLI.cpp
Labels: Development Approved, QA Approved :tada:, Server & Network, outsource

#13535 Fix potential map.json corruption in Asset Server
  assignment-client/src/assets/AssetServer.cpp
Labels: Development Approved, QA Approved :tada:

#13615 glTF importer fixes (Corruption while reading .bin files and allows loading local files)
  libraries/fbx/src/GLTFReader.cpp
  libraries/fbx/src/GLTFReader.h
Labels: Client, Development Approved, QA Approved :tada:

#13621 [FIX] Use create app in tablet mode when choosing to use tablet in desktop mode
  scripts/system/edit.js
  scripts/system/libraries/entityList.js
  scripts/system/libraries/gridTool.js
Labels: Create, Development Approved, QA Approved :tada:

#13619 Allow creators to disable hand touch from javascript
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  scripts/system/controllers/handTouch.js
Labels: Avatar, Development Approved, QA Approved :tada:, Scripting API change

#13625 Fix MS16802: In Purchases, there shouldn't be a glyph associated with the Open button
  interface/resources/qml/hifi/commerce/purchases/PurchasedItem.qml
Labels: Commerce, Development Approved, QA Approved :tada:, bug

#13618 Fix quickly clicking an edit handle causing selected entity change
  scripts/system/edit.js
  scripts/system/libraries/entitySelectionTool.js
Labels: Create, Development Approved, QA Approved :tada:, bug

#13633 pre-fetch infinite scroll pages before reaching the end
  interface/resources/qml/hifi/Feed.qml
  interface/resources/qml/hifi/Pal.qml
  interface/resources/qml/hifi/commerce/common/sendAsset/SendAsset.qml
  interface/resources/qml/hifi/commerce/purchases/Purchases.qml
  interface/resources/qml/hifi/commerce/wallet/WalletHome.qml
  interface/resources/qml/hifi/models/PSFListModel.qml
Labels: Development Approved, Discovery, QA Approved :tada:

#13629 MS16537: Updating "Forgot Username/Forgot Password" behavior
  interface/resources/qml/Browser.qml
  interface/src/ui/LoginDialog.cpp
Labels: Client, Development Approved, QA Approved :tada:

#13639 RC70: 404 malformed agent script requests
  domain-server/src/DomainServer.cpp
  libraries/embedded-webserver/src/HTTPManager.cpp
Labels: Development Approved, QA Approved :tada:, Server & Network

#13640 404 malformed agent script requests
  domain-server/src/DomainServer.cpp
  libraries/embedded-webserver/src/HTTPManager.cpp
Labels: Development Approved, Server & Network

#13630 Disable showing the entity edit tools when undoing while disabled
  scripts/system/edit.js
Labels: Create, Development Approved, QA Approved :tada:

#13624 appUi module, and use in People app
  scripts/modules/appUi.js
  scripts/system/pal.js
Labels: Development Approved, Discovery, QA Approved :tada:

#13631 fix 'the drop down does not shows the wearable'
  interface/resources/qml/hifi/avatarapp/AdjustWearables.qml
Labels: Client, Development Approved, QA Approved :tada:

#13628 16726 - Remove Black Boxes ( HMD.requestShowHandControllers() )
  scripts/system/controllers/viveControllerConfiguration.js
Labels: Client, Development Approved, QA Approved :tada:

#13644 put back old-style avatar-attachments menu-item
  interface/src/Menu.cpp
Labels: Client, Development Approved, QA Approved :tada:

#13638 Fix for audio continuing on destroyed Web 3D overlays
  interface/src/ui/overlays/Web3DOverlay.cpp
Labels: Development Approved, Engine, QA Approved :tada:, bug

#13635 Fix for bug16645 "disturbing flash when adding an overlay (even when everything is cached)"
  interface/src/ui/overlays/ModelOverlay.cpp
Labels: Development Approved, Engine, QA Approved :tada:, bug

#13647 Fix for audio continuing on destroyed Web 3D overlays (RC70.1)
  interface/src/ui/overlays/Web3DOverlay.cpp
Labels: Development Approved, Engine, QA Approved :tada:, bug

#13651 Prevent webviews from reading arbitrary local files
  interface/resources/qml/QmlWebWindow.qml
  libraries/ui/src/ui/types/RequestFilters.cpp
Labels: Development Approved, QA Approved :tada:

#13614 Android - App freezes on opening randomly - Fix
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/io/highfidelity/hifiinterface/PermissionChecker.java
  android/app/src/main/java/io/highfidelity/hifiinterface/fragment/HomeFragment.java
  android/app/src/main/java/org/qtproject/qt5/android/bindings/QtActivity.java
  android/app/src/main/res/drawable/launch_screen.xml
  android/app/src/main/res/layout/activity_splash.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/styles.xml
  interface/src/main.cpp
Labels: Android, Development Approved, Engine, QA Approved :tada:

#13662 MS16206: flying fix (RC70.1)
  interface/resources/qml/hifi/tablet/ControllerSettings.qml
  interface/src/Application.cpp
  interface/src/avatar/MyAvatar.cpp
  interface/src/ui/PreferencesDialog.cpp
Labels: Client, Development Approved, QA Approved :tada:

#13570 clean up tablet material entities and don't display them in create menu
  scripts/system/controllers/controllerModules/inEditMode.js
  scripts/system/libraries/WebTablet.js
  scripts/system/libraries/entityList.js
  scripts/system/tablet-ui/tabletUI.js
Labels: Client, Development Approved, QA Approved :tada:

#13661 fix avatar app from crashing when avatar entity variable is undefined.
  scripts/system/avatarapp.js
Labels: Client, Development Approved, QA Approved :tada:

#13648 Fix xz guides not showing when translating with Shift
  scripts/system/libraries/entitySelectionTool.js
Labels: Create, Development Approved, QA Approved :tada:

#13665 Changed Step Back Threshold to Stop Unnatural Backward Lean
  libraries/shared/src/AvatarConstants.h
Labels: Avatar, Development Approved, HMD required, QA Approved :tada:

#13580 Validate user-supplied avatar height range before accepting
  domain-server/resources/describe-settings.json
  domain-server/resources/web/settings/js/settings.js
Labels: Development Approved, QA Approved :tada:, Server & Network

#13669 70.1 version of Personal space bubble is defaulted off for now.
  libraries/networking/src/NodeList.h
Labels: Critical Fix, Development Approved, Discovery

#13667 Android - fix crash when returning from a Domain back to Home
  android/app/src/main/cpp/native.cpp
Labels: Android, Development Approved, Engine, QA Approved :tada:

#13652 MS16206 - Enable flight by default in desktop, controls menu changes re: flying
  interface/resources/qml/hifi/tablet/ControllerSettings.qml
  interface/src/Application.cpp
  interface/src/avatar/MyAvatar.cpp
  interface/src/ui/PreferencesDialog.cpp
Labels: Client, Development Approved, QA Approved :tada:

#13653 FB16870: Avatar Wearables showing incorrect number
  interface/src/AvatarBookmarks.cpp
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  scripts/system/avatarapp.js
Labels: Client, Development Approved, QA Approved :tada:, bug

#13656 Fix the Create selection box not always matching outline
  scripts/system/libraries/entitySelectionTool.js
Labels: Development Approved, QA Approved :tada:

#13674 Added _aboutToQuit guard on eventFilter()
  interface/src/Application.cpp
Labels: Client, Development Approved, QA Approved :tada:

#13636 Android audio fixes
  libraries/audio-client/CMakeLists.txt
  libraries/audio-client/src/AudioClient.cpp
Labels: Android, Development Approved, QA Approved :tada:

#13677 remove thread-unsafe socket errorString call
  libraries/networking/src/udt/Socket.cpp
Labels: Development Approved, Server & Network

#13684 FB17036 Avatar App causes error on cache reload (CTRL+R)
  scripts/system/avatarapp.js
Labels: Client, Development Approved, QA Approved :tada:

#13690 Fix audio page being set to desktop when starting in HMD.
  interface/src/scripting/Audio.cpp
Labels: Client, Development Approved, QA Approved :tada:

#13682 Fix MS16704: Remove worn Avatar/Wearable before updating
  interface/resources/qml/hifi/commerce/purchases/PurchasedItem.qml
  interface/resources/qml/hifi/commerce/purchases/Purchases.qml
Labels: Commerce, Development Approved, QA Approved :tada:, bug

#13534 Fix crash when editing avatar entities with no myAvatar
  libraries/entities/src/EntityEditPacketSender.cpp
Labels: Client, Development Approved, QA Approved :tada:

#13691 Revert "Prevent webviews from reading arbitrary local files"
  interface/resources/qml/QmlWebWindow.qml
  libraries/ui/src/ui/types/RequestFilters.cpp
Labels: Development Approved, Engine, QA Ready

#13693 Corrects loading of texture and default visibility.
  interface/src/ui/overlays/ModelOverlay.cpp
  interface/src/ui/overlays/ModelOverlay.h
Labels: Development Approved, Engine, QA Approved :tada:, QA Ready, bug

#13672 Redesign and enable hand's Pole Vectors for elbow simulation
  interface/src/avatar/MyAvatar.h
  libraries/animation/src/Rig.cpp
  libraries/animation/src/Rig.h
Labels: Avatar, Development Approved, QA Approved :tada:, bug

#13654 Fix computePickRay when in mirror mode
  interface/src/Application.cpp
Labels: Create, Development Approved, QA Approved :tada:

#13702 17016 flying settings
  interface/src/Application.cpp
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  interface/src/ui/PreferencesDialog.cpp
Labels: Client, Development Approved, QA Approved :tada:, bug

#13616 remove cruft for rendering collision shapes
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.h
  libraries/entities/src/EntityItem.h
  libraries/physics/src/CollisionRenderMeshCache.cpp
  libraries/physics/src/CollisionRenderMeshCache.h
  libraries/physics/src/EntityMotionState.cpp
  libraries/physics/src/EntityMotionState.h
  tests/physics/src/CollisionRenderMeshCacheTests.cpp
  tests/physics/src/CollisionRenderMeshCacheTests.h
Labels: Development Approved, Engine, QA Approved :tada:

#13692 Fix For Unnatural Hips Behaviour When Sitting In HMD
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  libraries/shared/src/AvatarConstants.h
Labels: Avatar, Development Approved, HMD required, QA Approved :tada:, bug

#13687 Fix ScriptEngine begin held onto after script stopped runnning
  assignment-client/src/Agent.cpp
  interface/src/Application.cpp
  libraries/script-engine/src/RecordingScriptingInterface.cpp
  libraries/script-engine/src/RecordingScriptingInterface.h
Labels: Client, QA Approved :tada:

#13705 Maintain virtual and real world orientations when teleport
  scripts/system/controllers/controllerModules/teleport.js
Labels: Client, Development Approved, QA Approved :tada:

#13708 fix a crash when grabbing a non-dynamic entity with an overlay child
  interface/src/avatar/MyAvatar.cpp
Labels: Client, Development Approved, QA Approved :tada:

#13695 Fix edit.js not being able to delete after creating entity
  scripts/system/edit.js
Labels: Development Approved, QA Approved :tada:

#13707 more correct continuous collision detection for thin objects
  libraries/physics/src/ObjectMotionState.cpp
Labels: Development Approved, Engine, QA Approved :tada:, bug

#13696 Particles don't spin with head roll, new spin + rotateWithEntity properties
  libraries/entities-renderer/src/RenderableParticleEffectEntityItem.cpp
  libraries/entities-renderer/src/RenderableParticleEffectEntityItem.h
  libraries/entities-renderer/src/textured_particle.slv
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityPropertyFlags.h
  libraries/entities/src/ParticleEffectEntityItem.cpp
  libraries/entities/src/ParticleEffectEntityItem.h
  libraries/gpu/src/gpu/Transform.slh
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
  scripts/system/particle_explorer/particleExplorer.js
  scripts/system/particle_explorer/particleExplorerTool.js
Labels: Create, Development Approved, Engine, HMD required, Packet Version Change, QA Approved :tada:, Scripting API change, bug

#13678 FB17023 - Make visible avatar url in the avatar app
  interface/resources/qml/hifi/AvatarApp.qml
  interface/resources/qml/hifi/avatarapp/MessageBoxes.qml
Labels: Client, Development Approved, QA Approved :tada:

#13683 Implement MS17039: Don't delete entities during DDV when Metaverse API call returns error
  assignment-client/src/entities/EntityServer.cpp
Labels: Commerce, Development Approved

#13577 Allow empty web entities to be rendered
  libraries/entities-renderer/src/RenderableWebEntityItem.cpp
Labels: Client, Development Approved, QA Approved :tada:

#13698 Reset entity property fields when no selection
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, QA Approved :tada:

#13675 pal refresh fixes
  interface/resources/qml/hifi/Pal.qml
  interface/resources/qml/hifi/models/PSFListModel.qml
  scripts/system/pal.js
Labels: Discovery, QA Approved :tada:

#13676 MS15184: Remove deprecated functions in Agent API
  assignment-client/src/Agent.cpp
  assignment-client/src/Agent.h
  assignment-client/src/AgentScriptingInterface.cpp
  assignment-client/src/AgentScriptingInterface.h
  libraries/networking/src/ThreadedAssignment.h
  scripts/developer/tests/agentAPITest.js
Labels: Create, Development Approved, QA Approved :tada:, Scripting API change, Server & Network

#13701 FB16702 - Avatar App does not save Animation JSON Override URL
  interface/resources/qml/hifi/AvatarApp.qml
  interface/resources/qml/hifi/avatarapp/Settings.qml
  interface/src/avatar/MyAvatar.cpp
  scripts/system/avatarapp.js
Labels: Client, Development Approved, QA Approved :tada:
