Repository highfidelity/hifi, pull requests merged in 2018-04, with the labels that each got.

#12749 RC66: Fix crash on Macos when looking at a mirror or when secondary camera is enabled
  libraries/render-utils/src/AntialiasingEffect.cpp
Labels: Critical Fix, Development Approved, Engine, Mac Required, QA Approved :tada:, bug

#12683 Reduce avatar elbow fluttering by disabling pole vectors
  libraries/animation/src/Rig.cpp
Labels: Avatar, Development Approved, QA Approved :tada:

#12653 Bubble button blink fix
  scripts/system/bubble.js
Labels: Client, Development Approved, QA Approved :tada:, outsource

#12659 Updating char controller
  interface/src/avatar/MyAvatar.cpp
Labels: Client, Development Approved, QA Approved :tada:

#12727 Trigger Avatar Recenter Behaviour
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
Labels: Avatar, Development Approved, QA Approved :tada:

#12684 Fix invalid message if cancel adding asset to AssetServer
  interface/src/scripting/AssetMappingsScriptingInterface.cpp
Labels: Client, Development Approved, QA Approved :tada:, outsource

#12712 Fix cert location for content sets; handle .content.zip content sets
  assignment-client/src/entities/EntityServer.cpp
  interface/resources/qml/hifi/commerce/checkout/Checkout.qml
  interface/resources/qml/hifi/commerce/purchases/PurchasedItem.qml
  interface/resources/qml/hifi/commerce/purchases/Purchases.qml
  interface/src/commerce/Ledger.cpp
  interface/src/commerce/Ledger.h
  interface/src/commerce/QmlCommerce.cpp
  interface/src/commerce/QmlCommerce.h
Labels: Commerce, Critical Fix, Development Approved, QA Approved :tada:, bug

#12566 Bindless Textures
  libraries/gpu-gl-common/src/gpu/gl/GLBackend.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLBackend.h
  libraries/gpu-gl-common/src/gpu/gl/GLBackendPipeline.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLBackendShader.cpp
  libraries/gpu-gl/src/gpu/gl41/GL41BackendTexture.cpp
  libraries/gpu-gl/src/gpu/gl45/GL45Backend.h
  libraries/gpu-gl/src/gpu/gl45/GL45BackendShader.cpp
  libraries/gpu-gl/src/gpu/gl45/GL45BackendTexture.cpp
  libraries/gpu-gl/src/gpu/gl45/GL45BackendVariableTexture.cpp
  libraries/gpu/src/gpu/Batch.cpp
  libraries/gpu/src/gpu/Batch.h
  libraries/gpu/src/gpu/Forward.h
  libraries/gpu/src/gpu/Texture.h
  libraries/gpu/src/gpu/TextureTable.cpp
  libraries/gpu/src/gpu/TextureTable.h
  libraries/gpu/src/gpu/TextureTable.slh
  libraries/gpu/src/gpu/Texture_ktx.cpp
  libraries/graphics/src/graphics/Material.h
  libraries/render-utils/src/MaterialTextures.slh
  libraries/render-utils/src/MeshPartPayload.cpp
  libraries/render-utils/src/RenderPipelines.cpp
  libraries/render-utils/src/RenderPipelines.h
Labels: Development Approved, Engine, QA Approved :tada:

#12722 fix ContextOverlayInferface highlighing unspecified entities.
  interface/src/raypick/LaserPointer.cpp
  interface/src/raypick/LaserPointer.h
  libraries/pointers/src/Pointer.cpp
  libraries/pointers/src/Pointer.h
  scripts/system/controllers/controllerModules/farActionGrabEntity.js
Labels: Client, Development Approved, QA Approved :tada:

#12739 map flying down back to C key
  interface/resources/controllers/keyboardMouse.json
Labels: Client, Development Approved, QA Approved :tada:

#12768 Fix regression with 'Log in/Sign up' dialog is missing "Forgot Username?" and "Forgot Password?" links
  interface/resources/qml/controls-uit/TextField.qml
Labels: Client, Development Approved, QA Approved :tada:

#12770 Fix move after import
  scripts/system/libraries/entitySelectionTool.js
Labels: Client, Content/Create, Development Approved, QA Approved :tada:

#12741 Remove Entities.currentAvatarEnergy and related from the API
  libraries/entities/src/EntityScriptingInterface.cpp
  libraries/entities/src/EntityScriptingInterface.h
Labels: Client, Development Approved, QA Approved :tada:

#12706 adding python baking scripts
  tools/bake-tools/bake.py
  tools/bake-tools/convertToRelativePaths.py
Labels: Client, Development Approved, Feedback Welcome

#12778 Prevent Context Overlay from flashing when briefly hovering over certified entity
  scripts/system/controllers/controllerModules/farActionGrabEntity.js
Labels: Client, Commerce, Development Approved, HMD required, QA Approved :tada:, bug

#12760 Inspection: Tweak mouse-right-click-to-inspect behavior
  interface/src/ui/overlays/ContextOverlayInterface.cpp
  interface/src/ui/overlays/ContextOverlayInterface.h
Labels: Commerce, HMD required, QA Approved :tada:

#12776 Fix 'Private' HMD preview texture enable/disable...again
  interface/resources/qml/hifi/commerce/wallet/PassphraseChange.qml
  interface/resources/qml/hifi/commerce/wallet/PassphraseModal.qml
  interface/resources/qml/hifi/commerce/wallet/PassphraseSelection.qml
  interface/resources/qml/hifi/commerce/wallet/SecurityImageChange.qml
  interface/resources/qml/hifi/commerce/wallet/SecurityImageSelection.qml
  interface/resources/qml/hifi/commerce/wallet/Wallet.qml
  interface/resources/qml/hifi/commerce/wallet/WalletSetup.qml
Labels: Commerce, Development Approved, HMD required, QA Approved :tada:, bug

#12762 Remove notifications and print outs when degrading LOD
  interface/src/LODManager.cpp
  scripts/system/notifications.js
Labels: Development Approved, Engine, QA Approved :tada:

#12774 Rc66 commerce workaround for broken qt5.10
  interface/resources/qml/controls/FlickableWebViewCore.qml
  scripts/system/help.js
Labels: Client, Commerce, Development Approved, Engine, QA Approved :tada:, bug

#12771 Add .md creation to autoTester
  tools/auto-tester/src/Test.cpp
  tools/auto-tester/src/Test.h
  tools/auto-tester/src/ui/AutoTester.cpp
  tools/auto-tester/src/ui/AutoTester.h
  tools/auto-tester/src/ui/AutoTester.ui
Labels: Development Approved, Engine, QA Approved :tada:

#12714 Fix Y arrow translation handle issues
  scripts/system/libraries/entitySelectionTool.js
Labels: Content/Create, Development Approved, QA Approved :tada:

#12747 Update to Transitions debugging / editing script
  interface/src/scripting/SelectionScriptingInterface.cpp
  interface/src/scripting/SelectionScriptingInterface.h
  libraries/render-utils/src/FadeEffectJobs.cpp
  libraries/render-utils/src/FadeEffectJobs.h
  scripts/developer/utilities/render/debugTransition.js
  scripts/developer/utilities/render/transition.qml
Labels: Development Approved, Engine, QA Approved :tada:

#12791 on first run, send user to serverless tutorial rather than checking for local sandbox
  interface/src/Application.cpp
Labels: Client, Development Approved, QA Approved :tada:

#12793 RC66: Fixing the shader pipelines used for translucent with normal maps
  libraries/render-utils/src/RenderPipelines.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#12748 cleanup around simulation-ownership
  assignment-client/src/avatars/AvatarMixerClientData.cpp
  assignment-client/src/avatars/AvatarMixerClientData.h
  interface/src/Application.cpp
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntitySimulation.cpp
  libraries/entities/src/EntitySimulation.h
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/MaterialEntityItem.cpp
  libraries/entities/src/SimpleEntitySimulation.cpp
  libraries/entities/src/SimpleEntitySimulation.h
  libraries/entities/src/SimulationOwner.cpp
  libraries/entities/src/SimulationOwner.h
  libraries/physics/src/EntityMotionState.cpp
  libraries/physics/src/EntityMotionState.h
  libraries/physics/src/ObjectMotionState.h
  libraries/physics/src/PhysicalEntitySimulation.cpp
  libraries/physics/src/PhysicalEntitySimulation.h
  libraries/physics/src/PhysicsEngine.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#12792 Minor changes to autoTester
  tools/auto-tester/src/Test.cpp
Labels: Development Approved, Engine

#12798 workload: stubbed prototype job for feedback to physics
  interface/src/Application.cpp
  interface/src/workload/GameWorkload.cpp
  interface/src/workload/GameWorkload.h
  interface/src/workload/PhysicsBoundary.h
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/workload/src/workload/Engine.cpp
  libraries/workload/src/workload/Proxy.h
  libraries/workload/src/workload/Space.cpp
  libraries/workload/src/workload/Space.h
  libraries/workload/src/workload/Transaction.cpp
  libraries/workload/src/workload/Transaction.h
Labels: Development Approved, Engine

#12799 Prevent Interface from crashing when a Snapshot upload fails
  interface/src/ui/SnapshotUploader.cpp
  scripts/system/snapshot.js
Labels: Development Approved, Discovery, QA Ready, bug

#12806 Workload: Splitting the creation of the Workload engine from the setup
  interface/src/workload/GameWorkload.cpp
  interface/src/workload/GameWorkload.h
  interface/src/workload/PhysicsBoundary.h
  libraries/workload/src/workload/Engine.cpp
  libraries/workload/src/workload/Engine.h
  libraries/workload/src/workload/RegionTracker.cpp
  libraries/workload/src/workload/RegionTracker.h
Labels: Development Approved, Engine

#12804 update to serverless tutorial with RC66 fixes
  cmake/externals/serverless-content/CMakeLists.txt
Labels: Critical Fix, Development Approved, QA Approved :tada:

#12801 fix -- don't tell steam about serverless domain urls
  interface/src/DiscoverabilityManager.cpp
  interface/src/ui/Snapshot.cpp
  libraries/networking/src/AddressManager.cpp
  libraries/networking/src/AddressManager.h
Labels: Client, Critical Fix, Development Approved, QA Approved :tada:

#12800 Remove lock file recovery in entity server
  libraries/octree/src/OctreePersistThread.cpp
Labels: Critical Fix, QA Approved :tada:

#12815 workload: add/remove entities to physics simulation according to workload boundaries
  cmake/externals/serverless-content/CMakeLists.txt
  interface/resources/qml/controls/FlickableWebViewCore.qml
  interface/src/Application.cpp
  interface/src/DiscoverabilityManager.cpp
  interface/src/ui/Snapshot.cpp
  interface/src/ui/SnapshotUploader.cpp
  interface/src/workload/PhysicsBoundary.cpp
  interface/src/workload/PhysicsBoundary.h
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.h
  libraries/networking/src/AddressManager.cpp
  libraries/networking/src/AddressManager.h
  libraries/octree/src/OctreePersistThread.cpp
  libraries/physics/CMakeLists.txt
  libraries/physics/src/PhysicalEntitySimulation.cpp
  libraries/physics/src/PhysicalEntitySimulation.h
  libraries/physics/src/PhysicsEngine.cpp
  libraries/render-utils/src/RenderPipelines.cpp
  libraries/workload/src/workload/Proxy.h
  libraries/workload/src/workload/Space.cpp
  libraries/workload/src/workload/Space.h
  scripts/system/help.js
  scripts/system/snapshot.js
Labels: Engine

#12802 66 fix - installer changes for client only name and clean install
  cmake/macros/GenerateInstallers.cmake
  cmake/templates/CPackProperties.cmake.in
  cmake/templates/NSIS.template.in
Labels: Critical Fix, Development Approved, QA Approved :tada:

#12816 RC66: Possible fix for QML texture leak
  libraries/entities-renderer/src/RenderableEntityItem.cpp
  libraries/entities-renderer/src/RenderableWebEntityItem.cpp
  libraries/qml/src/qml/impl/SharedObject.cpp
  libraries/qml/src/qml/impl/TextureCache.cpp
  libraries/qml/src/qml/impl/TextureCache.h
Labels: Development Approved, Engine, QA Approved :tada:, bug

#12821 Workload: FIxing the compilation on windows with math constants
  libraries/workload/src/workload/View.h
Labels: Development Approved

#12820 RC66 - move file ~ expansion from AddressManager to DomainHandler
  libraries/networking/src/AddressManager.cpp
  libraries/networking/src/DomainHandler.cpp
Labels: Critical Fix, QA Approved :tada:

#12823 fix enableHighlightList and disableHihglightList function for Selection API
  interface/src/scripting/SelectionScriptingInterface.cpp
  interface/src/scripting/SelectionScriptingInterface.h
  scripts/developer/utilities/render/debugHighlight.js
Labels: Client, Development Approved, Engine, QA Approved :tada:

#12825 only add to physics simulation that when necessary
  libraries/physics/src/PhysicalEntitySimulation.cpp
Labels: Development Approved, Engine

#12827 Workload: low hanging fruit optimization: don't unneccessarily update() entities
  interface/src/scripting/SelectionScriptingInterface.cpp
  interface/src/scripting/SelectionScriptingInterface.h
  libraries/entities-renderer/src/RenderableZoneEntityItem.h
  libraries/entities/src/ModelEntityItem.cpp
  libraries/entities/src/PolyLineEntityItem.h
  scripts/developer/utilities/render/debugHighlight.js
Labels: Development Approved, Engine

#12808 Fix for auto-reopening of closed query dialogs (aka hack-on-top-of-hack)
  interface/resources/qml/dialogs/CustomQueryDialog.qml
  interface/resources/qml/dialogs/QueryDialog.qml
  interface/resources/qml/windows/Fadable.qml
Labels: Development Approved, QA Approved :tada:

#12819 Fix location.hostname
  libraries/networking/src/AddressManager.cpp
  libraries/networking/src/AddressManager.h
Labels: Development Approved, QA Approved :tada:

#12833 Close 'goto' app on pressing 'forward' / 'backward' buttons
  interface/resources/qml/hifi/tablet/TabletAddressDialog.qml
Labels: Client, Development Approved, QA Approved :tada:

#12828 Fix skybox baking
  assignment-client/src/assets/AssetServer.cpp
Labels: Development Approved, QA Approved :tada:

#12838 RC66 merge back to master
  assignment-client/src/assets/AssetServer.cpp
  cmake/macros/GenerateInstallers.cmake
  cmake/templates/CPackProperties.cmake.in
  cmake/templates/NSIS.template.in
  interface/resources/qml/dialogs/CustomQueryDialog.qml
  interface/resources/qml/dialogs/QueryDialog.qml
  interface/resources/qml/hifi/tablet/TabletAddressDialog.qml
  interface/resources/qml/windows/Fadable.qml
  libraries/entities-renderer/src/RenderableEntityItem.cpp
  libraries/entities-renderer/src/RenderableWebEntityItem.cpp
  libraries/networking/src/AddressManager.cpp
  libraries/networking/src/AddressManager.h
  libraries/networking/src/DomainHandler.cpp
  libraries/qml/src/qml/impl/SharedObject.cpp
  libraries/qml/src/qml/impl/TextureCache.cpp
  libraries/qml/src/qml/impl/TextureCache.h
Labels: Development Approved

#12775 Android Control - jump and view sensitivity
  interface/resources/controllers/touchscreenvirtualpad.json
  interface/resources/images/fly.png
  libraries/display-plugins/src/display-plugins/Basic2DWindowOpenGLDisplayPlugin.cpp
  libraries/display-plugins/src/display-plugins/Basic2DWindowOpenGLDisplayPlugin.h
  libraries/input-plugins/src/input-plugins/TouchscreenVirtualPadDevice.cpp
  libraries/input-plugins/src/input-plugins/TouchscreenVirtualPadDevice.h
  libraries/ui/src/VirtualPadManager.cpp
  libraries/ui/src/VirtualPadManager.h
Labels: Android, Development Approved, QA Approved :tada:

#12846 Remove lock file recovery in entity server
  libraries/octree/src/OctreePersistThread.cpp
Labels: Critical Fix, Development Approved, QA Approved :tada:, bug

#12758 Commerce: Fix Certificate Info error
  interface/resources/qml/hifi/commerce/inspectionCertificate/InspectionCertificate.qml
  interface/src/commerce/Ledger.cpp
Labels: Commerce, Development Approved, QA Approved :tada:, bug

#12729 Settings API JSDoc
  interface/src/scripting/SettingsScriptingInterface.h
Labels: Content/Create, QA Approved :tada:, outsource

#12699 Fix for edit preferences not persisting
  scripts/system/edit.js
Labels: Content/Create, Development Approved, QA Approved :tada:

#12701 Fix for grid color changes not applying
  scripts/system/libraries/gridTool.js
Labels: Content/Create, Development Approved, QA Approved :tada:

#12761 Add Controller.Actions.Sprint as synonym of Controller.Actions.SPRINT
  libraries/controllers/src/controllers/Actions.cpp
Labels: Client, Development Approved, QA Approved :tada:

#12763 allow ESS to make relative-to-parent edits when entity is not in ESS's octree
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityScriptingInterface.cpp
Labels: Client, Development Approved, QA Approved :tada:

#12765 Fix text sizing per text3d overlay lineHeight property
  interface/src/ui/overlays/Text3DOverlay.cpp
Labels: Client, Development Approved, QA Approved :tada:

#12853 RC66: fix unreadable baked textures in serverless tutorial
  cmake/externals/serverless-content/CMakeLists.txt
Labels: Development Approved, QA Approved :tada:

#12777 Fix Window API position and size reporting
  interface/src/scripting/WindowScriptingInterface.cpp
  interface/src/scripting/WindowScriptingInterface.h
  libraries/ui/src/MainWindow.cpp
Labels: Client, Development Approved, QA Approved :tada:

#12783 Hack: Adding more budget options for memory texture
  interface/src/Menu.cpp
  interface/src/Menu.h
Labels: Development Approved, Engine, QA Approved :tada:

#12841 Fix asserts on domain switch
  libraries/entities/src/EntityItem.cpp
  libraries/physics/src/PhysicalEntitySimulation.cpp
Labels: Android, Development Approved, Engine, QA Approved :tada:

#12668 Updating repo script to match marketplace script
  scripts/tutorials/entity_scripts/sit.js
Labels: Client

#12679 Typo corrected: getAnimatationRoles to getAnimationRoles
  interface/src/avatar/MyAvatar.h
Labels: Development Approved, QA Approved :tada:, outsource

#12790 Bugfix for #12759 Overlays.editOverlay not applying subImage property
  interface/resources/qml/hifi/overlays/ImageOverlay.qml
Labels: Client, Development Approved, QA Approved :tada:

#12669 Fix several styling/alignment/overlapping issues in 'Add to world' and 'Rename' dialogs in Asset Browser
  interface/resources/qml/controls-uit/Keyboard.qml
  interface/resources/qml/controls-uit/TextField.qml
  interface/resources/qml/dialogs/CustomQueryDialog.qml
  interface/resources/qml/dialogs/TabletCustomQueryDialog.qml
Labels: Client, Development Approved, QA Approved :tada:, outsource

#12813 Fix Controller.getActions(), .getHardware(), and .getStandard()
  libraries/controllers/src/controllers/ScriptingInterface.h
Labels: Client, Development Approved, QA Approved :tada:

#12784 Potential bug correction when constructing eye position from Z-buffer depths in shaders
  libraries/render-utils/src/DeferredBufferRead.slh
  libraries/render-utils/src/DeferredTransform.slh
  libraries/render-utils/src/lightClusters_drawClusterContent.slf
  libraries/render-utils/src/lightClusters_drawClusterFromDepth.slf
Labels: Development Approved, Engine, QA Approved :tada:

#12857 Added recursive creation of MD files.
  tools/auto-tester/src/Test.cpp
  tools/auto-tester/src/Test.h
  tools/auto-tester/src/ui/AutoTester.cpp
  tools/auto-tester/src/ui/AutoTester.h
  tools/auto-tester/src/ui/AutoTester.ui
Labels: Development Approved, Engine, QA Approved :tada:

#12835 ktxInitialDataRequestFinished call to qcDebug(networking) - only in DEBUG
  interface/src/scripting/TestScriptingInterface.cpp
  interface/src/scripting/TestScriptingInterface.h
  libraries/model-networking/src/model-networking/TextureCache.cpp
Labels: Development Approved, Engine, QA Approved :tada:, Scripting API change

#12773 entity-server will expire stale simulation ownership
  assignment-client/src/entities/EntityTreeSendThread.cpp
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/entities/src/EntityScriptingInterface.cpp
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/EntityTreeElement.h
  libraries/entities/src/SimpleEntitySimulation.cpp
  libraries/entities/src/SimpleEntitySimulation.h
  libraries/octree/src/DirtyOctreeElementOperator.cpp
  libraries/octree/src/OctreeElement.h
  libraries/physics/src/EntityMotionState.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#12866 RC66: use serverless content with baked skybox and help textures
  cmake/externals/serverless-content/CMakeLists.txt
Labels: Development Approved, QA Approved :tada:

#12788 set lastEditedBy in local tree whenever a script adds or edits an entity
  libraries/entities/src/EntityScriptingInterface.cpp
Labels: Client, Development Approved, QA Approved :tada:

#12847 Fix client-only materials on non-avatars
  libraries/entities-renderer/src/RenderableMaterialEntityItem.cpp
  libraries/entities-renderer/src/RenderableMaterialEntityItem.h
  libraries/entities/src/MaterialEntityItem.cpp
  libraries/entities/src/MaterialEntityItem.h
Labels: Development Approved, Engine, QA Approved :tada:

#12859 Fix a bug when switching shadow on/off in front of mirror
  libraries/gpu/src/gpu/Texture.h
  libraries/render-utils/src/DeferredLightingEffect.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#12824 Fix non-client-only material entities applied to avatar by session ID not being removed on domain switch
  libraries/entities/src/MaterialEntityItem.cpp
  libraries/entities/src/MaterialEntityItem.h
Labels: Development Approved, Engine, QA Approved :tada:, bug

#12880 workload: more correct stats names
  interface/src/Application.cpp
  interface/src/ui/Stats.cpp
  libraries/physics/src/EntityMotionState.h
  libraries/physics/src/PhysicsEngine.cpp
Labels: Engine

#12812 Support ETC2/EAC compressed textures
  libraries/gpu-gl-common/src/gpu/gl/GLTexelFormat.cpp
  libraries/gpu-gl/src/gpu/gl41/GL41Backend.h
  libraries/gpu-gl/src/gpu/gl41/GL41BackendTexture.cpp
  libraries/gpu-gl/src/gpu/gl45/GL45BackendTexture.cpp
  libraries/gpu-gles/src/gpu/gles/GLESBackendTexture.cpp
  libraries/gpu/src/gpu/Format.cpp
  libraries/gpu/src/gpu/Format.h
  libraries/gpu/src/gpu/Texture_ktx.cpp
  libraries/graphics/src/graphics/GpuHelpers.cpp
  libraries/image/src/image/Image.cpp
  libraries/ktx/src/khronos/KHR.h
Labels: Android, Development Approved, Engine, QA Approved :tada:

#12867 Fix location.protocol value for serverless domains
  libraries/networking/src/AddressManager.cpp
  libraries/networking/src/AddressManager.h
Labels: Client, Development Approved, QA Approved :tada:

#12868 Fix for missing alpha on server restart
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/ShapeEntityItem.cpp
  libraries/entities/src/ShapeEntityItem.h
Labels: Development Approved, Engine, QA Approved :tada:

#12831 Model overlay fixes
  interface/src/ui/overlays/ModelOverlay.cpp
Labels: Client, Development Approved, QA Approved :tada:

#12839 Migrate materials from userData to materialData
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityPropertyFlags.h
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/MaterialEntityItem.cpp
  libraries/entities/src/MaterialEntityItem.h
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
  scripts/system/edit.js
  scripts/system/html/css/edit-style.css
  scripts/system/html/entityProperties.html
  scripts/system/html/js/entityProperties.js
Labels: Engine, Packet Version Change, QA Approved :tada:, Scripting API change

#12875 Update baking script to include skyboxes.
  tools/bake-tools/bake.py
  tools/bake-tools/convertToRelativePaths.py
Labels: Client, Development Approved

#12863 Support per-avatar gain adjustment on stereo input streams
  assignment-client/src/audio/AudioMixerSlave.cpp
Labels: Development Approved, Feedback Welcome, QA Approved :tada:

#12884 Update docs with correct qt version
  BUILD.md
  BUILD_LINUX.md
  BUILD_OSX.md
  BUILD_WIN.md
  cmake/macros/SetupQt.cmake
  interface/src/Application.cpp
Labels: QA Approved :tada:

#12787 hide desktop windows when switching into HMD mode
  interface/resources/qml/desktop/Desktop.qml
  libraries/ui/src/OffscreenUi.cpp
  libraries/ui/src/OffscreenUi.h
  libraries/ui/src/ui/TabletScriptingInterface.cpp
Labels: Client, Development Approved, QA Approved :tada:

#12887 RC66: Exposing more texture memory budget options
  interface/src/Menu.cpp
  interface/src/Menu.h
Labels: Development Approved, Engine, QA Approved :tada:

#12877 Fix for avatar recording playback on avatars with many joints
  libraries/avatars/src/AvatarData.cpp
Labels: Avatar, Development Approved, QA Approved :tada:

#12851 serverless-domain named landing-points(RC66)
  interface/src/Application.cpp
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/EntityTree.h
  libraries/networking/src/AddressManager.cpp
  libraries/networking/src/DomainHandler.cpp
  libraries/networking/src/DomainHandler.h
  libraries/networking/src/NodeList.cpp
Labels: Client, Development Approved, QA Approved :tada:

#12864 switch to backtrace's newer crashpad blob
  cmake/externals/crashpad/CMakeLists.txt
Labels: Client, Development Approved, QA Approved :tada:

#12888 Rollback some recent QML changes on Android
  interface/resources/qml/controls-uit/+android/Button.qml
  interface/resources/qml/controls-uit/+android/Table.qml
  interface/resources/qml/desktop/+android/Desktop.qml
  interface/resources/qml/dialogs/+android/CustomQueryDialog.qml
  interface/resources/qml/dialogs/+android/FileDialog.qml
  interface/resources/qml/dialogs/+android/QueryDialog.qml
  interface/resources/qml/dialogs/assetDialog/+android/AssetDialogContent.qml
Labels: Android, Development Approved, QA Approved :tada:

#12571 Fix unprotected tree traversals
  assignment-client/src/entities/EntityServer.cpp
  assignment-client/src/octree/OctreeSendThread.cpp
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/SimpleEntitySimulation.cpp
Labels: Beware: Threading/Deadlock, Development Approved, QA Approved :tada:, Server & Network

#12886 Remove dead code
  cmake/modules/FindGverb.cmake
  script-archive/example/audio/audioReverbOn.js
Labels: Development Approved, QA Approved :tada:

#12850 Enable Interface tracing from earliest execution point
  interface/src/Application.cpp
  interface/src/main.cpp
  libraries/gpu/src/gpu/Context.cpp
  libraries/gpu/src/gpu/Shader.cpp
  libraries/qml/src/qml/OffscreenSurface.cpp
  libraries/qml/src/qml/impl/SharedObject.cpp
  libraries/render/src/render/Engine.cpp
  libraries/render/src/render/ShapePipeline.cpp
  libraries/shared/src/Profile.cpp
  libraries/shared/src/Profile.h
  libraries/task/src/task/Task.h
  libraries/ui/src/ui/OffscreenQmlSurface.cpp
  libraries/ui/src/ui/OffscreenQmlSurfaceCache.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#12723 HMD API JSDoc
  interface/resources/qml/windows/Decoration.qml
  interface/src/scripting/HMDScriptingInterface.h
  libraries/display-plugins/src/display-plugins/AbstractHMDScriptingInterface.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityScriptingInterface.h
  tools/jsdoc/plugins/hifi.js
Labels: Content/Create, Development Approved, QA Approved :tada:, outsource

#12909 RC66: Fix for avatar glitches, head and legs folding into chest.
  interface/src/Application.cpp
  libraries/avatars-renderer/src/avatars-renderer/SkeletonModel.cpp
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
Labels: Avatar, Development Approved, QA Approved :tada:

#12914 fix bookmarks, don't put :0 in urls
  libraries/networking/src/AddressManager.cpp
Labels: Client, Critical Fix, Development Approved, QA Approved :tada:

#12764 Make BakedAssetType a scoped enum
  assignment-client/src/assets/AssetServer.cpp
  assignment-client/src/assets/AssetServer.h
Labels: Development Approved, QA Approved :tada:

#12892 Batch compile shaders
  libraries/render-utils/src/DrawHaze.cpp
  libraries/render-utils/src/SubsurfaceScattering.cpp
  libraries/render-utils/src/SurfaceGeometryPass.cpp
  libraries/render-utils/src/SurfaceGeometryPass.h
  libraries/render-utils/src/ToneMappingEffect.cpp
  libraries/render-utils/src/ToneMappingEffect.h
Labels: Development Approved, Engine, QA Approved :tada:

#12928 Merge back stable to master after RC66 promotion
  interface/src/Application.cpp
  libraries/avatars-renderer/src/avatars-renderer/SkeletonModel.cpp
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/EntityTree.h
  libraries/networking/src/AddressManager.cpp
  libraries/networking/src/DomainHandler.cpp
  libraries/networking/src/DomainHandler.h
  libraries/networking/src/NodeList.cpp
Labels: Stable Mergeback

#12696 add single quote tests to JS baking tests
  tests/baking/src/JSBakerTest.cpp
Labels: Development Approved

#12836 Go to tablet home / close Create menu when changing domains
  scripts/system/edit.js
Labels: Client, Content/Create, Development Approved, QA Approved :tada:, bug

#12931 Corrected BUILD_LINUX.md regarding QT
  BUILD_LINUX.md
Labels: Client

#12893 Fix overlay toggling
  interface/src/Application.cpp
Labels: Client, Development Approved, QA Approved :tada:

#12897 Include JSDoc Web pages in the install
  interface/CMakeLists.txt
  tools/jsdoc/CMakeLists.txt
Labels: Content/Create, Development Approved, QA Approved :tada:

#12907 more correct stats names
  interface/src/Application.cpp
  interface/src/Menu.cpp
  interface/src/Menu.h
  interface/src/ui/Stats.cpp
  libraries/physics/src/EntityMotionState.h
  libraries/physics/src/PhysicalEntitySimulation.cpp
  libraries/physics/src/PhysicsEngine.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#12919 Fixed crash when importing entities from JSON multiple times
  libraries/entities/src/EntityTree.cpp
Labels: Client, Development Approved, QA Approved :tada:

#12933 Add more detailed AvatarData packet support to Wireshark dissector plugin
  tools/hfudt.lua
Labels: Development Approved, Server & Network

#12923 Don't allow users to spam Still Only snapshot capture
  scripts/system/html/js/SnapshotReview.js
Labels: Discovery, QA Approved :tada:, bug

#12913 delay NL reset on login until new username is known
  libraries/networking/src/NodeList.cpp
Labels: Development Approved, QA Approved :tada:

#12924 Fix paths to various Snapshot resource files
  interface/resources/sounds/snapshot/snap.wav
  interface/resources/sounds/snapshot/sound-print-photo.wav
  scripts/system/snapshot.js
Labels: Development Approved, Discovery, QA Approved :tada:, bug

#12929 Fix edit icon behavior
  scripts/system/edit.js
Labels: Content/Create, Development Approved, QA Approved :tada:, bug

#12894 fix bug that caused tractor action to go crazy
  libraries/physics/src/ObjectActionTractor.cpp
Labels: Client, Development Approved, QA Approved :tada:

#12920 edit.js - remove ability to clone non-owned avatar-entities
  scripts/system/libraries/entitySelectionTool.js
Labels: Content/Create, Critical Fix, Development Approved, QA Approved :tada:

#12844 Highlight grabbable and equippable entities.
  scripts/system/controllers/controllerDispatcher.js
  scripts/system/controllers/controllerModules/equipEntity.js
  scripts/system/controllers/controllerModules/farActionGrabEntity.js
  scripts/system/controllers/controllerModules/highlightNearbyEntities.js
  scripts/system/controllers/controllerModules/mouseHighlightEntities.js
  scripts/system/controllers/controllerModules/nearActionGrabEntity.js
  scripts/system/controllers/controllerModules/nearParentGrabEntity.js
  scripts/system/controllers/controllerModules/nearTrigger.js
  scripts/system/controllers/controllerScripts.js
  scripts/system/controllers/grab.js
  scripts/system/libraries/controllerDispatcherUtils.js
Labels: Client, Development Approved, Feedback Welcome, QA Approved :tada:

#12782 Replace LogHandler repeated regex scheme with assigned ID tracking scheme
  domain-server/src/DomainServer.cpp
  interface/src/Application.cpp
  interface/src/InterfaceDynamicFactory.cpp
  libraries/audio/src/AudioRingBuffer.cpp
  libraries/audio/src/PositionalAudioStream.cpp
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityTree.cpp
  libraries/fbx/src/FBXReader_Mesh.cpp
  libraries/networking/src/LimitedNodeList.cpp
  libraries/networking/src/SequenceNumberStats.cpp
  libraries/networking/src/udt/Packet.cpp
  libraries/networking/src/udt/SendQueue.cpp
  libraries/networking/src/udt/Socket.cpp
  libraries/octree/src/Octree.cpp
  libraries/octree/src/OctreeElement.cpp
  libraries/octree/src/OctreeSceneStats.cpp
  libraries/physics/src/ObjectConstraintBallSocket.cpp
  libraries/physics/src/ObjectConstraintConeTwist.cpp
  libraries/physics/src/ObjectConstraintHinge.cpp
  libraries/physics/src/ObjectConstraintSlider.cpp
  libraries/render-utils/src/BackgroundStage.cpp
  libraries/render/src/render/DrawTask.cpp
  libraries/shared/src/LogHandler.cpp
  libraries/shared/src/LogHandler.h
Labels: Development Approved

#12871 Remove dead Octree code
  assignment-client/src/entities/EntityTreeSendThread.h
  assignment-client/src/octree/OctreeSendThread.cpp
  assignment-client/src/octree/OctreeSendThread.h
  assignment-client/src/octree/OctreeServer.cpp
  assignment-client/src/octree/OctreeServer.h
  libraries/entities/src/EntityItem.h
  libraries/entities/src/EntityTree.h
  libraries/entities/src/EntityTreeElement.cpp
  libraries/entities/src/EntityTreeElement.h
  libraries/entities/src/LightEntityItem.cpp
  libraries/entities/src/LineEntityItem.cpp
  libraries/entities/src/LineEntityItem.h
  libraries/entities/src/MaterialEntityItem.cpp
  libraries/entities/src/MaterialEntityItem.h
  libraries/entities/src/ModelEntityItem.cpp
  libraries/entities/src/ModelEntityItem.h
  libraries/entities/src/ParticleEffectEntityItem.cpp
  libraries/entities/src/PolyLineEntityItem.cpp
  libraries/entities/src/PolyLineEntityItem.h
  libraries/entities/src/PolyVoxEntityItem.cpp
  libraries/entities/src/PolyVoxEntityItem.h
  libraries/entities/src/ShapeEntityItem.cpp
  libraries/entities/src/TextEntityItem.cpp
  libraries/entities/src/TextEntityItem.h
  libraries/entities/src/WebEntityItem.cpp
  libraries/entities/src/WebEntityItem.h
  libraries/entities/src/ZoneEntityItem.cpp
  libraries/entities/src/ZoneEntityItem.h
  libraries/octree/src/Octree.cpp
  libraries/octree/src/Octree.h
  libraries/octree/src/OctreeElement.cpp
  libraries/octree/src/OctreeElement.h
  libraries/octree/src/OctreeElementBag.cpp
  libraries/octree/src/OctreeElementBag.h
  libraries/octree/src/OctreeProcessor.cpp
  libraries/octree/src/OctreeQueryNode.cpp
  libraries/octree/src/OctreeQueryNode.h
  libraries/octree/src/OctreeSceneStats.cpp
  libraries/octree/src/OctreeSceneStats.h
  libraries/shared/src/OctalCode.cpp
  libraries/shared/src/OctalCode.h
  tests/entities/src/main.cpp
Labels: Development Approved, QA Approved :tada:

#12925 Create app: Save light selection menu option properly
  scripts/system/edit.js
Labels: Content/Create, Development Approved, QA Approved :tada:, bug

#12898 In Material resources, support relative paths for 'emissiveMap'
  libraries/model-networking/src/model-networking/MaterialCache.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#12936 Change tablet model and spawn position
  interface/resources/meshes/tablet-with-home-button-small-bezel.fbx
  interface/resources/qml/hifi/tablet/TabletMenu.qml
  interface/resources/qml/hifi/tablet/TabletMenuStack.qml
  interface/resources/qml/hifi/tablet/TabletMenuView.qml
  scripts/system/libraries/WebTablet.js
  scripts/system/libraries/utils.js
Labels: Client, Development Approved, QA Approved :tada:

#12910 Only dismiss letterbox when clicking on grey areas
  interface/resources/qml/hifi/LetterboxMessage.qml
Labels: HMD required, QA Approved :tada:, bug

#12915 Add Entities materialData JSDoc
  libraries/entities/src/EntityItemProperties.cpp
Labels: Content/Create, Development Approved, QA Approved :tada:

#12926 Fix QT typo
  BUILD_LINUX.md
Labels: Development Approved, QA Approved :tada:

#12873 Fix for weird color shifting of teleportation target in Rust domain
  libraries/graphics/src/graphics/Haze.h
  libraries/render-utils/src/DeferredGlobalLight.slh
  libraries/render-utils/src/ForwardGlobalLight.slh
  libraries/render-utils/src/Haze.slf
  libraries/render-utils/src/Haze.slh
  libraries/render-utils/src/MaterialTextures.slh
  libraries/render-utils/src/forward_model_normal_map.slf
  libraries/render-utils/src/model_fade.slf
  libraries/render-utils/src/model_fade.slv
  libraries/render-utils/src/model_normal_map.slf
  libraries/render-utils/src/model_normal_map.slv
  libraries/render-utils/src/model_normal_map_fade.slf
  libraries/render-utils/src/model_normal_map_fade.slv
  libraries/render-utils/src/model_translucent.slf
  libraries/render-utils/src/model_translucent.slv
  libraries/render-utils/src/model_translucent_fade.slf
  libraries/render-utils/src/model_translucent_normal_map.slf
  libraries/render-utils/src/model_translucent_normal_map.slv
  libraries/render-utils/src/model_translucent_normal_map_fade.slf
  libraries/render-utils/src/model_translucent_unlit_fade.slf
  libraries/render-utils/src/model_unlit_fade.slf
  libraries/render-utils/src/skin_model_fade.slv
  libraries/render-utils/src/skin_model_fade_dq.slv
  libraries/render-utils/src/skin_model_normal_map.slv
  libraries/render-utils/src/skin_model_normal_map_dq.slv
  libraries/render-utils/src/skin_model_normal_map_fade.slv
  libraries/render-utils/src/skin_model_normal_map_fade_dq.slv
Labels: Development Approved, Engine, QA Approved :tada:, outsource

#12786 Fix avatars not coming back when briefly disconnected from avatar mixer
  domain-server/src/DomainGatekeeper.cpp
  libraries/networking/src/LimitedNodeList.cpp
  libraries/networking/src/LimitedNodeList.h
  libraries/networking/src/NodeList.cpp
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
Labels: Development Approved, QA Approved :tada:

#12690 Change packet authentication to use HMAC
  libraries/networking/src/HMACAuth.cpp
  libraries/networking/src/HMACAuth.h
  libraries/networking/src/LimitedNodeList.cpp
  libraries/networking/src/LimitedNodeList.h
  libraries/networking/src/NLPacket.cpp
  libraries/networking/src/NLPacket.h
  libraries/networking/src/Node.cpp
  libraries/networking/src/Node.h
  libraries/networking/src/udt/PacketHeaders.cpp
Labels: Development Approved, Packet Version Change, QA Approved :tada:, Server & Network

#12948 RC66.1: Re apply extra sanity check that hasn't been applied correctly in rc66
  libraries/render/src/render/Item.cpp
Labels: Development Approved, Engine, QA Approved :tada:, bug

#12858 Update location.hostname JSDoc per serverless domains
  interface/src/scripting/WindowScriptingInterface.h
  libraries/networking/src/AddressManager.h
Labels: Client, Content/Create, QA Approved :tada:

#12785 fix some xcode warnings for unnecessary captured this
  assignment-client/src/Agent.cpp
  domain-server/src/DomainServer.cpp
  libraries/entities-renderer/src/RenderableWebEntityItem.cpp
Labels: Client, Development Approved

#12779 update to latest electron version for server console
  .gitignore
  server-console/package-lock.json
  server-console/package.json
  server-console/src/downloader.js
  server-console/src/main.js
  server-console/src/modules/hf-process.js
Labels: Development Approved, QA Approved :tada:

#12937 Make Audio.cpp threadsafe
  interface/src/Application.cpp
  interface/src/scripting/Audio.cpp
  interface/src/scripting/Audio.h
  libraries/audio-client/src/AudioClient.cpp
  libraries/audio-client/src/AudioClient.h
Labels: Android, Beware: Threading/Deadlock, Development Approved, Engine, QA Approved :tada:, bug

#12743 Use 16-bit local IDs for Nodes in NL packets
  assignment-client/src/assets/AssetServer.cpp
  assignment-client/src/audio/AudioMixer.cpp
  assignment-client/src/avatars/AvatarMixer.cpp
  domain-server/src/DomainGatekeeper.cpp
  domain-server/src/DomainGatekeeper.h
  domain-server/src/DomainServer.cpp
  interface/src/octree/OctreePacketProcessor.cpp
  libraries/audio/src/InboundAudioStream.cpp
  libraries/networking/src/DomainHandler.h
  libraries/networking/src/LimitedNodeList.cpp
  libraries/networking/src/LimitedNodeList.h
  libraries/networking/src/NLPacket.cpp
  libraries/networking/src/NLPacket.h
  libraries/networking/src/NLPacketList.h
  libraries/networking/src/NetworkPeer.cpp
  libraries/networking/src/NetworkPeer.h
  libraries/networking/src/Node.cpp
  libraries/networking/src/NodeList.cpp
  libraries/networking/src/NodeList.h
  libraries/networking/src/PacketReceiver.cpp
  libraries/networking/src/ReceivedMessage.cpp
  libraries/networking/src/ReceivedMessage.h
  libraries/networking/src/SequenceNumberStats.cpp
  libraries/networking/src/SequenceNumberStats.h
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/octree/src/OctreeProcessor.cpp
  libraries/shared/src/UUID.h
Labels: Development Approved, Packet Version Change, QA Approved :tada:, Server & Network

#12952 Vec3 API JSDoc
  libraries/script-engine/src/Quat.h
  libraries/script-engine/src/Vec3.h
  libraries/shared/src/RegisteredMetaTypes.h
Labels: Content/Create, QA Approved :tada:

#12922 Controller API JSDoc
  interface/src/Application.cpp
  interface/src/scripting/ControllerScriptingInterface.h
  libraries/controllers/src/controllers/Actions.cpp
  libraries/controllers/src/controllers/InputDevice.h
  libraries/controllers/src/controllers/Pose.cpp
  libraries/controllers/src/controllers/ScriptingInterface.h
  libraries/controllers/src/controllers/StandardController.cpp
  libraries/controllers/src/controllers/impl/MappingBuilderProxy.h
  libraries/controllers/src/controllers/impl/RouteBuilderProxy.h
  libraries/entities/src/EntityScriptingInterface.h
  libraries/input-plugins/src/input-plugins/KeyboardMouseDevice.cpp
  libraries/script-engine/src/KeyEvent.cpp
  libraries/script-engine/src/MouseEvent.cpp
  libraries/script-engine/src/TouchEvent.cpp
  libraries/script-engine/src/WheelEvent.cpp
  libraries/shared/src/PointerEvent.cpp
  plugins/oculus/src/OculusControllerManager.cpp
  plugins/openvr/src/ViveControllerManager.cpp
  tools/jsdoc/plugins/hifi.js
Labels: Content/Create

#12918 Fixed null pointer exception if importing an entity from JSON fails
  libraries/entities/src/EntityTree.cpp
Labels: Client, Development Approved

#12921 Fix AMD shader compilation
  libraries/gpu-gl-common/src/gpu/gl/GLBackend.h
  libraries/gpu-gl-common/src/gpu/gl/GLBackendShader.cpp
  libraries/gpu-gl/src/gpu/gl41/GL41BackendShader.cpp
  libraries/gpu-gl/src/gpu/gl45/GL45BackendShader.cpp
  libraries/gpu-gles/src/gpu/gles/GLESBackendShader.cpp
  libraries/graphics/src/graphics/Light.slh
  libraries/graphics/src/graphics/LightIrradiance.shared.slh
  libraries/graphics/src/graphics/LightVolume.shared.slh
  libraries/graphics/src/graphics/Material.slh
  libraries/graphics/src/graphics/SphericalHarmonics.shared.slh
  libraries/render-utils/src/LightingModel.slh
Labels: Development Approved, Engine, Mac Required, QA Approved :tada:, QA Ready, bug

#12943 Fix SpinBox.
  interface/resources/qml/controls-uit/Slider.qml
  interface/resources/qml/controls-uit/SpinBox.qml
  interface/resources/qml/dialogs/preferences/SpinBoxPreference.qml
  interface/resources/qml/dialogs/preferences/SpinnerSliderPreference.qml
  interface/resources/qml/hifi/dialogs/attachments/Attachment.qml
  interface/resources/qml/hifi/dialogs/attachments/Vector3.qml
  interface/resources/qml/hifi/tablet/OpenVrConfiguration.qml
  libraries/shared/src/Preferences.h
Labels: Client, Development Approved, QA Approved :tada:

#12881 Minimum entity dimension (1mm)
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItemPropertiesDefaults.h
  libraries/render-utils/src/Model.cpp
Labels: Android, Development Approved, Engine, QA Approved :tada:, bug

#12965 Fix for bug #12979: Setting colors [0, 0, 254] from js api ends up as black color
  libraries/shared/src/ColorUtils.h
Labels: Development Approved, Engine, QA Approved :tada:

#12968 fix setting of domain local ID from domain list
  libraries/networking/src/NodeList.cpp
Labels: Development Approved, QA Approved :tada:

#12949 add default or campaigned marketing slideshow during install
  INSTALL.md
  cmake/templates/NSIS.template.in
Labels: Development Approved, QA Approved :tada:, Server & Network

#12967 Fix for null sourceNode use
  domain-server/src/DomainServer.cpp
  libraries/networking/src/LimitedNodeList.cpp
Labels: Development Approved, QA Approved :tada:, bug

#12905 Desktop equip/unequip
  scripts/system/controllers/controllerModules/equipEntity.js
  scripts/system/controllers/grab.js
  scripts/system/libraries/controllerDispatcherUtils.js
Labels: Client, Content/Create, Critical Fix, Development Approved, QA Approved :tada:

#12959 Don't populate user list in pal until you connect the events up
  scripts/system/pal.js
Labels: Development Approved, Discovery, QA Approved :tada:, bug

#12966 Fix audio level meter
  interface/src/scripting/Audio.cpp
Labels: Client, Development Approved, Engine, QA Approved :tada:, bug

#12969 Attempt to shutdown web surfaces more consistently
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/ui/overlays/Web3DOverlay.cpp
  libraries/entities-renderer/src/RenderableWebEntityItem.cpp
  libraries/qml/src/qml/OffscreenSurface.cpp
  libraries/qml/src/qml/impl/RenderEventHandler.cpp
  libraries/qml/src/qml/impl/SharedObject.cpp
  libraries/render-utils/src/AbstractViewStateInterface.h
  tests/render-perf/src/main.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#12983 HOTFIX version of PR 12969: Attempt to shutdown web surfaces more consistently
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/ui/overlays/Web3DOverlay.cpp
  libraries/entities-renderer/src/RenderableWebEntityItem.cpp
  libraries/qml/src/qml/OffscreenSurface.cpp
  libraries/qml/src/qml/impl/RenderEventHandler.cpp
  libraries/qml/src/qml/impl/SharedObject.cpp
  libraries/render-utils/src/AbstractViewStateInterface.h
  tests/render-perf/src/main.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#12953 Hotfix, avatars disappear on quick reconnect
  domain-server/src/DomainGatekeeper.cpp
  libraries/networking/src/LimitedNodeList.cpp
  libraries/networking/src/LimitedNodeList.h
  libraries/networking/src/NodeList.cpp
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
Labels: Critical Fix, Development Approved, Packet Version Change, QA Approved :tada:

#12978 RC66.1: don't try to build convex hulls with nan data
  libraries/physics/src/ShapeFactory.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#12903 Get the correct device name connect to OpenVr
  interface/resources/qml/hifi/tablet/ControllerSettings.qml
  interface/resources/qml/hifi/tablet/OpenVrConfiguration.qml
  libraries/plugins/src/plugins/InputConfiguration.cpp
  libraries/plugins/src/plugins/InputPlugin.h
  plugins/openvr/src/OpenVrDisplayPlugin.cpp
  plugins/openvr/src/OpenVrDisplayPlugin.h
  plugins/openvr/src/OpenVrHelpers.cpp
  plugins/openvr/src/OpenVrHelpers.h
  plugins/openvr/src/ViveControllerManager.cpp
  plugins/openvr/src/ViveControllerManager.h
Labels: Client, Development Approved, QA Approved :tada:

#12971 Add memory corruption crash handler
  interface/src/Crashpad.cpp
  interface/src/Menu.cpp
Labels: Development Approved, QA Approved :tada:

#12974 don't try to build convex hulls with nan data
  libraries/physics/src/ShapeFactory.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#12961 Enforce correct lock order between EntityTree and EntitySimulation
  assignment-client/src/entities/EntityServer.cpp
  libraries/entities/src/SimpleEntitySimulation.cpp
Labels: Beware: Threading/Deadlock, Development Approved, QA Approved :tada:

#12981 revert HMAC packet verification for now
  libraries/networking/src/HMACAuth.cpp
  libraries/networking/src/HMACAuth.h
  libraries/networking/src/LimitedNodeList.cpp
  libraries/networking/src/LimitedNodeList.h
  libraries/networking/src/NLPacket.cpp
  libraries/networking/src/NLPacket.h
  libraries/networking/src/Node.cpp
  libraries/networking/src/Node.h
  libraries/networking/src/udt/PacketHeaders.cpp
Labels: Critical Fix, Development Approved, QA Approved :tada:, Release Blocker
