Repository highfidelity/hifi, pull requests merged in 2018-02, with the labels that each got.

#12340 Fix overlimit shader char strings
  CMakeLists.txt
  android/app/build.gradle
  android/build.gradle
  cmake/macros/AutoScribeShader.cmake
  libraries/display-plugins/src/display-plugins/hmd/HmdDisplayPlugin.cpp
  libraries/entities-renderer/src/RenderableParticleEffectEntityItem.cpp
  libraries/entities-renderer/src/RenderablePolyLineEntityItem.cpp
  libraries/entities-renderer/src/RenderablePolyVoxEntityItem.cpp
  libraries/entities-renderer/src/RenderableShapeEntityItem.cpp
  libraries/gpu/src/gpu/StandardShaderLib.cpp
  libraries/graphics/src/graphics/Skybox.cpp
  libraries/procedural/src/procedural/Procedural.cpp
  libraries/procedural/src/procedural/ProceduralSkybox.cpp
  libraries/render-utils/src/AmbientOcclusionEffect.cpp
  libraries/render-utils/src/AnimDebugDraw.cpp
  libraries/render-utils/src/AntialiasingEffect.cpp
  libraries/render-utils/src/BloomEffect.cpp
  libraries/render-utils/src/DebugDeferredBuffer.cpp
  libraries/render-utils/src/DeferredLightingEffect.cpp
  libraries/render-utils/src/DrawHaze.cpp
  libraries/render-utils/src/GeometryCache.cpp
  libraries/render-utils/src/HighlightEffect.cpp
  libraries/render-utils/src/LightClusters.cpp
  libraries/render-utils/src/RenderPipelines.cpp
  libraries/render-utils/src/StencilMaskPass.cpp
  libraries/render-utils/src/SubsurfaceScattering.cpp
  libraries/render-utils/src/SurfaceGeometryPass.cpp
  libraries/render-utils/src/ToneMappingEffect.cpp
  libraries/render-utils/src/ZoneRenderer.cpp
  libraries/render-utils/src/text/Font.cpp
  libraries/render/src/render/BlurTask.cpp
  libraries/render/src/render/DrawSceneOctree.cpp
  libraries/render/src/render/DrawStatus.cpp
  libraries/render/src/render/DrawTask.cpp
  libraries/render/src/render/drawItemBounds.slf
  tests/shaders/src/main.cpp
  tools/scribe/CMakeLists.txt
  tools/scribe/src/main.cpp
Labels: Development Approved, Mac Required, QA Approved

#12372 RC64: Commerce: Inspection Certificate Redesign (Fixed!)
  .gitignore
  interface/resources/qml/hifi/commerce/inspectionCertificate/InspectionCertificate.qml
  interface/resources/qml/hifi/commerce/inspectionCertificate/images/cert-bg-gold-split.png
  interface/resources/qml/hifi/commerce/inspectionCertificate/images/cert-bg.jpg
  interface/resources/qml/hifi/commerce/inspectionCertificate/images/nocert-bg-split.png
  interface/resources/qml/hifi/commerce/wallet/sendMoney/SendMoney.qml
  interface/resources/qml/hifi/commerce/wallet/sendMoney/images/loader.gif
  interface/src/ui/overlays/ContextOverlayInterface.cpp
  interface/src/ui/overlays/ContextOverlayInterface.h
  scripts/system/marketplaces/marketplaces.js
Labels: Commerce, Critical Fix, Development Approved, QA Approved, disco-free

#12377 Fixing the forward rendering and more clean up for android
  libraries/render-utils/src/ForwardBuffer.slh
  libraries/render-utils/src/ForwardBufferWrite.slh
  libraries/render-utils/src/ForwardGlobalLight.slh
  libraries/render-utils/src/LightingModel.slh
  libraries/render-utils/src/MaterialTextures.slh
  libraries/render-utils/src/MeshPartPayload.cpp
  libraries/render-utils/src/RenderForwardTask.cpp
  libraries/render-utils/src/RenderPipelines.cpp
  libraries/render-utils/src/ZoneRenderer.cpp
  libraries/render-utils/src/forward_model.slf
  libraries/render-utils/src/forward_model_normal_map.slf
  libraries/render-utils/src/forward_model_normal_specular_map.slf
  libraries/render-utils/src/forward_model_specular_map.slf
  libraries/render-utils/src/forward_model_translucent.slf
  libraries/render-utils/src/forward_model_unlit.slf
  libraries/render-utils/src/model.slf
  libraries/render-utils/src/model_fade.slf
  libraries/render-utils/src/model_lightmap.slf
  libraries/render-utils/src/model_lightmap_fade.slf
  libraries/render-utils/src/model_lightmap_normal_map.slf
  libraries/render-utils/src/model_lightmap_normal_map_fade.slf
  libraries/render-utils/src/model_lightmap_normal_specular_map.slf
  libraries/render-utils/src/model_lightmap_normal_specular_map_fade.slf
  libraries/render-utils/src/model_lightmap_specular_map.slf
  libraries/render-utils/src/model_lightmap_specular_map_fade.slf
  libraries/render-utils/src/model_normal_map.slf
  libraries/render-utils/src/model_normal_map_fade.slf
  libraries/render-utils/src/model_normal_specular_map.slf
  libraries/render-utils/src/model_normal_specular_map_fade.slf
  libraries/render-utils/src/model_specular_map.slf
  libraries/render-utils/src/model_specular_map_fade.slf
  libraries/render/src/render/ShapePipeline.h
  tests/shaders/src/main.cpp
Labels: Android, Engine

#12375 RC64 - fix lasers going to origin
  interface/src/ui/overlays/Base3DOverlay.cpp
  interface/src/ui/overlays/Line3DOverlay.cpp
  libraries/avatars/src/AvatarData.h
  scripts/system/controllers/controllerModules/farActionGrabEntity.js
  scripts/system/libraries/pointersUtils.js
Labels: Development Approved, QA Approved, clavatar

#12348 Fix lasers going to origin when trying to far grab.
  interface/src/ui/overlays/Base3DOverlay.cpp
  interface/src/ui/overlays/Line3DOverlay.cpp
  libraries/avatars/src/AvatarData.h
  scripts/system/controllers/controllerModules/farActionGrabEntity.js
  scripts/system/libraries/pointersUtils.js
Labels: Critical Fix, Development Approved, QA Approved, clavatar

#12234 New Edit Selected Entity Manipulation Handles
  scripts/system/edit.js
  scripts/system/libraries/entitySelectionTool.js
Labels: Content/Create, Development Approved, QA Approved

#12243 Some improvements to the log window
  interface/resources/styles/log_dialog.qss
  interface/src/ui/BaseLogDialog.cpp
  interface/src/ui/LogDialog.cpp
  interface/src/ui/LogDialog.h
  libraries/shared/src/shared/AbstractLoggerInterface.h
Labels: Development Approved, QA Approved

#12114 Additional mtl spec support & fixes for Poly & more
  interface/resources/qml/js/Utils.jsc
  libraries/fbx/src/FBX.h
  libraries/fbx/src/OBJReader.cpp
  libraries/fbx/src/OBJReader.h
Labels: Content/Create, Development Approved, QA Ready, clavatar

#12379 fixing the scattering bad ambient lighting
  libraries/render-utils/src/LightAmbient.slh
Labels: Development Approved, Engine, QA Approved

#12363 Commerce: Inspection Certificate Redesign (Fixed!)
  .gitignore
  interface/resources/qml/hifi/commerce/inspectionCertificate/InspectionCertificate.qml
  interface/resources/qml/hifi/commerce/inspectionCertificate/images/cert-bg-gold-split.png
  interface/resources/qml/hifi/commerce/inspectionCertificate/images/cert-bg.jpg
  interface/resources/qml/hifi/commerce/inspectionCertificate/images/nocert-bg-split.png
  interface/resources/qml/hifi/commerce/wallet/sendMoney/SendMoney.qml
  interface/resources/qml/hifi/commerce/wallet/sendMoney/images/loader.gif
  interface/src/ui/overlays/ContextOverlayInterface.cpp
  interface/src/ui/overlays/ContextOverlayInterface.h
  scripts/system/marketplaces/marketplaces.js
Labels: Commerce, Development Approved, QA Approved, disco-free

#12381 RC64 : Fixing the bad ambient lighting on scattering surfaces
  libraries/render-utils/src/LightAmbient.slh
Labels: Development Approved, Engine, QA Approved, Release Blocker, bug

#12378 save avatarUrl when setting new skeletonModelUrl
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
Labels: Development Approved, QA Approved, clavatar

#12367 Fix shared unit tests
  libraries/shared/src/BitVectorHelpers.h
  tests/shared/src/BitVectorHelperTests.cpp
  tests/shared/src/FileCacheTests.cpp
  tests/shared/src/GeometryUtilTests.cpp
  tests/shared/src/PathUtilsTests.cpp
Labels: Development Approved

#12328 Misc bug fixes
  assignment-client/src/audio/AudioMixerSlave.cpp
  interface/src/AvatarBookmarks.cpp
  interface/src/AvatarEntitiesBookmarks.cpp
  libraries/animation/src/Rig.cpp
  libraries/networking/src/AddressManager.cpp
  libraries/networking/src/NodeList.cpp
  libraries/plugins/src/plugins/PluginManager.cpp
  libraries/recording/src/recording/Deck.cpp
  libraries/render-utils/src/DeferredLightingEffect.cpp
  libraries/shared/src/QVariantGLM.cpp
  libraries/shared/src/TriangleSet.h
  libraries/ui/src/QmlWindowClass.cpp
  libraries/ui/src/ui/Menu.cpp
  plugins/oculus/src/OculusBaseDisplayPlugin.cpp
Labels: Development Approved, QA Approved

#12323 Shadow performance / acnee improvements
  interface/src/SecondaryCamera.cpp
  libraries/gpu/src/gpu/Framebuffer.cpp
  libraries/octree/src/OctreeUtils.cpp
  libraries/octree/src/OctreeUtils.h
  libraries/render-utils/src/LightStage.cpp
  libraries/render-utils/src/LightStage.h
  libraries/render-utils/src/RenderShadowTask.cpp
  libraries/render-utils/src/RenderShadowTask.h
  libraries/render-utils/src/RenderViewTask.cpp
  libraries/render-utils/src/Shadow.slh
  libraries/render-utils/src/ShadowCore.slh
  libraries/render-utils/src/Shadows_shared.slh
  libraries/render-utils/src/directional_ambient_light_shadow.slf
  libraries/render-utils/src/directional_skybox_light_shadow.slf
  libraries/render/src/render/CullTask.cpp
  libraries/render/src/render/CullTask.h
  libraries/render/src/render/DrawSceneOctree.cpp
  libraries/render/src/render/RenderFetchCullSortTask.cpp
  libraries/render/src/render/SpatialTree.cpp
  libraries/render/src/render/SpatialTree.h
  libraries/shared/src/ViewFrustum.cpp
  libraries/shared/src/ViewFrustum.h
  scripts/developer/utilities/render/debugShadow.js
  scripts/developer/utilities/render/shadow.qml
Labels: Development Approved, Engine, QA Approved

#12383 HOTFIX 63.4
  interface/src/Application.cpp
  interface/src/Application_render.cpp
  libraries/render/src/render/Scene.cpp
Labels: QA Approved, master -> stable

#11537 Migrating QML rendering off the main thread
  android/app/CMakeLists.txt
  interface/CMakeLists.txt
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/scripting/LimitlessConnection.cpp
  interface/src/ui/AvatarInputs.cpp
  interface/src/ui/Stats.cpp
  interface/src/ui/overlays/Web3DOverlay.cpp
  libraries/entities-renderer/CMakeLists.txt
  libraries/entities-renderer/src/RenderableWebEntityItem.cpp
  libraries/gl/src/gl/GLHelpers.cpp
  libraries/gl/src/gl/GLHelpers.h
  libraries/gpu-gl/src/gpu/gl/GLShared.cpp
  libraries/gpu-gl/src/gpu/gl/GLShared.h
  libraries/gpu-gl/src/gpu/gl41/GL41BackendTexture.cpp
  libraries/gpu-gles/src/gpu/gl/GLShared.h
  libraries/qml/CMakeLists.txt
  libraries/qml/src/qml/Logging.cpp
  libraries/qml/src/qml/Logging.h
  libraries/qml/src/qml/OffscreenSurface.cpp
  libraries/qml/src/qml/OffscreenSurface.h
  libraries/qml/src/qml/impl/Profiling.cpp
  libraries/qml/src/qml/impl/Profiling.h
  libraries/qml/src/qml/impl/RenderControl.cpp
  libraries/qml/src/qml/impl/RenderControl.h
  libraries/qml/src/qml/impl/RenderEventHandler.cpp
  libraries/qml/src/qml/impl/RenderEventHandler.h
  libraries/qml/src/qml/impl/SharedObject.cpp
  libraries/qml/src/qml/impl/SharedObject.h
  libraries/qml/src/qml/impl/TextureCache.cpp
  libraries/qml/src/qml/impl/TextureCache.h
  libraries/shared/src/shared/MiniPromises.h
  libraries/ui/CMakeLists.txt
  libraries/ui/src/OffscreenUi.cpp
  libraries/ui/src/OffscreenUi.h
  libraries/ui/src/ui/OffscreenQmlSurface.cpp
  libraries/ui/src/ui/OffscreenQmlSurface.h
  libraries/ui/src/ui/OffscreenQmlSurfaceCache.cpp
  plugins/hifiNeuron/CMakeLists.txt
  plugins/oculus/CMakeLists.txt
  plugins/openvr/CMakeLists.txt
  tests/qml/CMakeLists.txt
  tests/qml/qml/main.qml
  tests/qml/qml/qml/+android/UI.js
  tests/qml/qml/qml/+ios/UI.js
  tests/qml/qml/qml/+osx/UI.js
  tests/qml/qml/qml/ButtonPage.qml
  tests/qml/qml/qml/InputPage.qml
  tests/qml/qml/qml/ProgressPage.qml
  tests/qml/qml/qml/UI.js
  tests/qml/src/main.cpp
  tests/render-perf/CMakeLists.txt
Labels: Beware: Threading/Deadlock, Engine, QA Approved

#12346 Fix transition (ex-fade) debugging scripts
  libraries/render-utils/src/FadeEffectJobs.cpp
  libraries/render-utils/src/FadeEffectJobs.h
  scripts/developer/utilities/render/debugFade.js
  scripts/developer/utilities/render/debugTransition.js
  scripts/developer/utilities/render/fade.qml
  scripts/developer/utilities/render/transition.qml
Labels: Development Approved, Engine, QA Approved, outsource

#12359 Fix collapse headers in edit.js
  scripts/system/html/entityProperties.html
  scripts/system/html/js/entityProperties.js
Labels: Content/Create, Development Approved, QA Approved

#12365 moving Job/Task framework out of 'render' library and into its own 'task' library
  android/app/CMakeLists.txt
  interface/CMakeLists.txt
  libraries/avatars-renderer/CMakeLists.txt
  libraries/entities-renderer/CMakeLists.txt
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/EntityTree.h
  libraries/render-utils/CMakeLists.txt
  libraries/render-utils/src/ZoneRenderer.h
  libraries/render/CMakeLists.txt
  libraries/render/src/render/Engine.h
  libraries/render/src/render/SortTask.h
  libraries/shared/src/Profile.cpp
  libraries/shared/src/Profile.h
  libraries/shared/src/SpatialParentFinder.h
  libraries/task/CMakeLists.txt
  libraries/task/src/task/Config.cpp
  libraries/task/src/task/Config.h
  libraries/task/src/task/Task.h
  libraries/task/src/task/Varying.h
  libraries/workload/CMakeLists.txt
  libraries/workload/src/workload/Space.cpp
  libraries/workload/src/workload/Space.h
  plugins/oculus/CMakeLists.txt
  plugins/openvr/CMakeLists.txt
  tests/gpu-test/CMakeLists.txt
  tests/render-perf/CMakeLists.txt
  tests/render-texture-load/CMakeLists.txt
  tests/workload/CMakeLists.txt
  tests/workload/src/SpaceTests.cpp
  tests/workload/src/SpaceTests.h
Labels: Development Approved, QA Approved

#12387 Merge stable back into master
  libraries/render/src/render/Scene.cpp
Labels: Development Approved, Stable Mergeback

#12239 Do not override sensorToWorldMatrix if animGraph is loading or failed to load
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  libraries/animation/src/AnimNodeLoader.cpp
  libraries/animation/src/Rig.cpp
  libraries/animation/src/Rig.h
Labels: Development Approved, QA Approved, clavatar

#12286 Add asset server backups capabilities to the Domain Server
  assignment-client/src/assets/AssetServer.cpp
  assignment-client/src/assets/AssetServer.h
  assignment-client/src/assets/SendAssetTask.cpp
  assignment-client/src/assets/UploadAssetTask.cpp
  domain-server/src/BackupSupervisor.cpp
  domain-server/src/BackupSupervisor.h
  domain-server/src/DomainServer.cpp
  domain-server/src/DomainServer.h
  libraries/networking/src/AssetClient.cpp
  libraries/networking/src/AssetUtils.h
  libraries/networking/src/DomainHandler.h
  libraries/networking/src/LimitedNodeList.cpp
  libraries/networking/src/LimitedNodeList.h
  libraries/networking/src/MappingRequest.cpp
  libraries/networking/src/MappingRequest.h
  libraries/networking/src/NodeList.h
  libraries/networking/src/PacketReceiver.cpp
  libraries/networking/src/udt/PacketHeaders.h
Labels: Development Approved, QA Approved, Server & Network

#12394 Commerce: Fix wrap mode for very long P2P memos
  interface/resources/qml/hifi/commerce/wallet/WalletHome.qml
Labels: Commerce, Development Approved, QA Ready, bug, disco-free

#12366 fix -- get children of animated entity joints to follow along, again
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/shared/src/SpatiallyNestable.h
Labels: Client, Development Approved, QA Approved, bug

#12291 [Case 10865] Make Asset Browser multi-select work with Ctrl/Cmd/Shift+Click
  interface/resources/qml/controls-uit/Tree.qml
  interface/resources/qml/hifi/AssetServer.qml
  interface/resources/qml/hifi/dialogs/TabletAssetServer.qml
Labels: Development Approved, QA Approved, Server & Network, outsource

#12398 Fix spectator camera crash
  interface/src/Application.cpp
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.cpp
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.h
  libraries/gl/src/gl/OffscreenGLCanvas.cpp
  libraries/gl/src/gl/OffscreenGLCanvas.h
  libraries/qml/src/qml/impl/RenderEventHandler.cpp
  plugins/openvr/src/OpenVrDisplayPlugin.cpp
Labels: Development Approved, Engine, QA Approved

#12390 add control button mapping for controller API
  interface/resources/controllers/keyboardMouse.json
  libraries/input-plugins/src/input-plugins/KeyboardMouseDevice.cpp
Labels: Client, Development Approved, QA Approved

#12399 Introducing group culling to avoid the avatar model to be partially culled
  interface/src/avatar/MyAvatar.cpp
  interface/src/ui/overlays/ModelOverlay.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/render-utils/src/MeshPartPayload.cpp
  libraries/render-utils/src/MeshPartPayload.h
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
  libraries/render/src/render/CullTask.cpp
  libraries/render/src/render/Item.cpp
  libraries/render/src/render/Item.h
  libraries/render/src/render/RenderFetchCullSortTask.cpp
Labels: Development Approved, Engine, QA Approved

#12403 [EntityPropertiesJS] Fix for 801 Uncaught TypeError (details below).
  scripts/system/html/js/entityProperties.js
Labels: Development Approved, QA Approved

#12405 Fix for privacy screen not displayed during wallet creation on step 3, while user entering password for the wallet
  interface/resources/qml/hifi/commerce/wallet/WalletSetup.qml
Labels: Commerce, Development Approved, QA Approved

#12376 get Avatars In Range
  libraries/avatars/src/AvatarHashMap.cpp
  libraries/avatars/src/AvatarHashMap.h
Labels: Development Approved, QA Approved

#12295 initial separation of DS into domain settings and content settings
  domain-server/resources/describe-settings.json
  domain-server/resources/web/base-settings-scripts.html
  domain-server/resources/web/base-settings.html
  domain-server/resources/web/content/index.shtml
  domain-server/resources/web/content/js/content.js
  domain-server/resources/web/css/style.css
  domain-server/resources/web/header.html
  domain-server/resources/web/images/hmd-w-eyes.svg
  domain-server/resources/web/js/base-settings.js
  domain-server/resources/web/js/bootstrap-switch.min.js
  domain-server/resources/web/js/domain-server.js
  domain-server/resources/web/js/form2js.min.js
  domain-server/resources/web/js/shared.js
  domain-server/resources/web/js/underscore-min.js
  domain-server/resources/web/settings/index.shtml
  domain-server/resources/web/settings/js/settings.js
  domain-server/src/DomainServer.cpp
  domain-server/src/DomainServerSettingsManager.cpp
  domain-server/src/DomainServerSettingsManager.h
  libraries/embedded-webserver/src/HTTPManager.cpp
Labels: Development Approved, QA Approved, Server & Network

#12406 Backup APIs
  domain-server/src/BackupHandler.h
  domain-server/src/DomainContentBackupManager.cpp
  domain-server/src/DomainContentBackupManager.h
  domain-server/src/DomainServer.cpp
  libraries/embedded-webserver/src/HTTPConnection.cpp
  libraries/embedded-webserver/src/HTTPConnection.h
  libraries/embedded-webserver/src/HTTPManager.cpp
Labels: Server & Network

#12385 updates to electron-packager and node-notifier for CVEs
  server-console/package-lock.json
  server-console/package.json
Labels: Development Approved, QA Approved

#12393 PAL: Prevent opening of Availability from WebView
  interface/resources/qml/hifi/Pal.qml
Labels: Development Approved, Discovery, QA Approved, bug, disco-free

#12413 Asset Server deplays queries until fully setup
  assignment-client/src/assets/AssetServer.cpp
  assignment-client/src/assets/AssetServer.h
  domain-server/src/AssetsBackupHandler.cpp
  domain-server/src/AssetsBackupHandler.h
  domain-server/src/BackupHandler.h
  domain-server/src/DomainContentBackupManager.cpp
  domain-server/src/DomainContentBackupManager.h
  domain-server/src/DomainServer.cpp
  domain-server/src/DomainServer.h
  domain-server/src/EntitiesBackupHandler.cpp
  domain-server/src/EntitiesBackupHandler.h
Labels: Server & Network

#12412 Introduce task abort feature for early exit of task branch
  libraries/render-utils/src/HighlightEffect.cpp
  libraries/task/src/task/Task.cpp
  libraries/task/src/task/Task.h
Labels: Development Approved, Engine, QA Approved

#12420 Add a content settings backup handler
  domain-server/src/ContentSettingsBackupHandler.cpp
  domain-server/src/ContentSettingsBackupHandler.h
  domain-server/src/DomainContentBackupManager.cpp
  domain-server/src/DomainServer.cpp
  domain-server/src/DomainServerSettingsManager.cpp
  domain-server/src/DomainServerSettingsManager.h
  domain-server/src/EntitiesBackupHandler.cpp
  libraries/shared/src/GenericThread.cpp
  libraries/shared/src/GenericThread.h
Labels: Server & Network

#12423 Return Backup and Recovery status and progress
  assignment-client/src/assets/AssetServer.cpp
  assignment-client/src/assets/AssetServer.h
  domain-server/src/AssetsBackupHandler.cpp
  domain-server/src/AssetsBackupHandler.h
  domain-server/src/BackupHandler.h
  domain-server/src/ContentSettingsBackupHandler.h
  domain-server/src/DomainContentBackupManager.cpp
  domain-server/src/DomainContentBackupManager.h
  domain-server/src/DomainServer.cpp
  domain-server/src/EntitiesBackupHandler.h
Labels: Server & Network

#12386 WL 21668 - Make sure all Prompts are correctly emitting a signal on cancel and that cancellations return null
  interface/src/scripting/WindowScriptingInterface.cpp
  libraries/ui/src/OffscreenUi.cpp
Labels: Content/Create, Development Approved, QA Approved, outsource

#12421 don't update avatar entities if the avatars ID is AVATAR_SELF_ID
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
Labels: Client, Development Approved, QA Approved

#12417 RC64: Bug fix for Scramlbed Avaatrs
  libraries/fbx/src/FBXReader.cpp
Labels: Avatar, Development Approved, QA Approved

#12419 Don't update avatar entities of the avatars ID is AVATAR_SELF_ID
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
Labels: Client, Development Approved, QA Approved

#12424 fix overwrite of general description object with filtered
  domain-server/src/DomainServerSettingsManager.cpp
Labels: Development Approved, Server & Network

#12409 Add content archive tables to DS content page
  domain-server/resources/describe-settings.json
  domain-server/resources/web/base-settings-scripts.html
  domain-server/resources/web/content/index.shtml
  domain-server/resources/web/content/js/bootstrap-sortable.min.js
  domain-server/resources/web/content/js/content.js
  domain-server/resources/web/content/js/moment-locale.min.js
  domain-server/resources/web/css/bootstrap-sortable.css
  domain-server/resources/web/css/style.css
  domain-server/resources/web/footer.html
  domain-server/resources/web/header.html
  domain-server/resources/web/js/base-settings.js
  domain-server/resources/web/js/domain-server.js
  domain-server/resources/web/js/shared.js
  domain-server/resources/web/settings/js/settings.js
  domain-server/resources/web/wizard/index.shtml
  domain-server/src/DomainContentBackupManager.cpp
  domain-server/src/DomainContentBackupManager.h
  domain-server/src/DomainServer.cpp
  domain-server/src/DomainServerSettingsManager.cpp
  domain-server/src/DomainServerSettingsManager.h
Labels: Server & Network

#12433 Fix filename not being passed in correctly
  domain-server/src/DomainContentBackupManager.cpp
Labels: Server & Network

#12436 Fixed extra " in backup_instructions.html
  interface/resources/html/commerce/backup_instructions.html
Labels: Development Approved

#12414 Bug fix for Scrambled Avatars
  libraries/fbx/src/FBXReader.cpp
Labels: Avatar, Development Approved, QA Approved

#12395 Prevent adding the same tablet url to the tabletApps list
  interface/resources/qml/hifi/tablet/TabletRoot.qml
Labels: Client, Development Approved, QA Approved

#12426 fix for toolbar slowly drifting on switching between HMD/Desktop modes
  interface/resources/qml/windows/Window.qml
Labels: Client, Development Approved, QA Approved, outsource

#12422 Show outline for zones when rotating
  scripts/system/libraries/entitySelectionTool.js
Labels: Content/Create, Development Approved, QA Approved

#12442 Update isCorrupted with name indexing
  domain-server/src/AssetsBackupHandler.cpp
  domain-server/src/AssetsBackupHandler.h
  domain-server/src/BackupHandler.h
  domain-server/src/ContentSettingsBackupHandler.h
  domain-server/src/DomainContentBackupManager.cpp
  domain-server/src/EntitiesBackupHandler.h
Labels: Server & Network

#12396 fix 4x 'fromQml' slots execution
  libraries/qml/src/qml/OffscreenSurface.cpp
  libraries/ui/src/ui/OffscreenQmlSurface.cpp
Labels: Client, Development Approved, QA Approved, outsource

#12443 Commerce: Wallet/Send Money UI fixes
  interface/resources/qml/hifi/commerce/wallet/PassphraseModal.qml
  interface/resources/qml/hifi/commerce/wallet/sendMoney/SendMoney.qml
Labels: Development Approved, QA Approved, bug, disco-free

#12435 Make sure Flickable for GridView for TabletHome will not flick
  interface/resources/qml/hifi/tablet/TabletHome.qml
Labels: Client, Development Approved, QA Approved, outsource

#12438 Fix selecting values when tabbing between entity properties fields
  scripts/system/html/js/entityProperties.js
Labels: Client, Development Approved, QA Approved, outsource

#12446 more logging for fogbugz 11748
  libraries/animation/src/Rig.cpp
Labels: Client, Development Approved, QA Approved

#12453 Fix new material UI indentation
  interface/resources/qml/hifi/tablet/NewMaterialDialog.qml
Labels: Engine, QA Approved

#12445 handle permissions save with no existing permissions
  domain-server/resources/web/wizard/js/wizard.js
Labels: Development Approved, Server & Network

#12334 Remove some deprecated JavaScript API items
  interface/src/Application.cpp
  interface/src/Menu.cpp
  interface/src/scripting/MenuScriptingInterface.cpp
  interface/src/scripting/MenuScriptingInterface.h
  interface/src/scripting/WindowScriptingInterface.cpp
  interface/src/scripting/WindowScriptingInterface.h
  interface/src/ui/ApplicationOverlay.h
  interface/src/ui/overlays/Cube3DOverlay.cpp
  interface/src/ui/overlays/Cube3DOverlay.h
  interface/src/ui/overlays/Overlays.cpp
  interface/src/ui/overlays/Overlays.h
  interface/src/ui/overlays/Shape3DOverlay.cpp
  interface/src/ui/overlays/Shape3DOverlay.h
  libraries/ui/src/OffscreenUi.cpp
  libraries/ui/src/OffscreenUi.h
  libraries/ui/src/ui/Menu.cpp
  libraries/ui/src/ui/Menu.h
  scripts/developer/debugging/queryAACubeInspector.js
  scripts/system/help.js
  scripts/system/libraries/WebTablet.js
Labels: Client, Content/Create, Development Approved, QA Approved, Scripting API change

#12344 Recording app fixes
  unpublishedScripts/marketplace/record/html/js/record.js
  unpublishedScripts/marketplace/record/record.js
Labels: Client, Development Approved, QA Approved, outsource

#12460 mark corrupted backups and refuse to restore from them in web UI
  domain-server/resources/web/content/js/content.js
Labels: Development Approved

#12434 check for recovery complete always, reload content page on restore
  domain-server/resources/web/content/js/content.js
  domain-server/src/DomainContentBackupManager.cpp
Labels: Development Approved

#12461 fix badging for changes in tables
  domain-server/resources/web/js/base-settings.js
Labels: Development Approved

#12465 fix restore of object settings for content or domain settings
  domain-server/src/DomainServerSettingsManager.cpp
Labels: Development Approved

#12467 Ignore baked assets in backups
  domain-server/src/AssetsBackupHandler.cpp
Labels: Server & Network

#12356 Handle tablet entities and overlays not being available
  scripts/system/audio.js
  scripts/system/controllers/controllerDispatcher.js
  scripts/system/controllers/controllerModules/inEditMode.js
  scripts/system/controllers/controllerModules/inVREditMode.js
  scripts/system/controllers/controllerModules/nearParentGrabOverlay.js
  scripts/system/controllers/controllerModules/stylusInput.js
  scripts/system/controllers/grab.js
  scripts/system/edit.js
  scripts/system/help.js
  scripts/system/libraries/WebTablet.js
  scripts/system/libraries/entitySelectionTool.js
  scripts/system/libraries/utils.js
  scripts/system/marketplaces/marketplaces.js
  scripts/system/menu.js
  scripts/system/tablet-ui/tabletUI.js
  scripts/system/tablet-users.js
  unpublishedScripts/marketplace/shapes/modules/laser.js
Labels: Client, Development Approved, QA Approved :tada:, outsource

#12463 Fix two bugs with Create Menu
  interface/resources/qml/hifi/dialogs/TabletAssetServer.qml
  interface/resources/qml/hifi/tablet/EditTabView.qml
Labels: Content/Create, Development Approved, QA Approved :tada:

#12469 Merge from stable back into RC64
  interface/src/LODManager.cpp
  interface/src/LODManager.h
  libraries/render/src/render/Scene.cpp
Labels: Development Approved, QA Approved :tada:

#12451 Add #include of Forward.h to AudioMixer.h
  assignment-client/src/audio/AudioMixer.cpp
  assignment-client/src/audio/AudioMixer.h
  assignment-client/src/audio/AudioMixerClientData.cpp
  assignment-client/src/audio/AudioMixerClientData.h
  assignment-client/src/audio/AudioMixerSlave.cpp
Labels: Development Approved

#12444 Commerce: Extended Certificate Support, V1
  interface/resources/fonts/hifi-glyphs.ttf
  interface/resources/qml/controls-uit/Separator.qml
  interface/resources/qml/controls-uit/TextField.qml
  interface/resources/qml/hifi/commerce/checkout/Checkout.qml
  interface/resources/qml/hifi/commerce/common/CommerceLightbox.qml
  interface/resources/qml/hifi/commerce/common/FirstUseTutorial.qml
  interface/resources/qml/hifi/commerce/inspectionCertificate/InspectionCertificate.qml
  interface/resources/qml/hifi/commerce/purchases/PurchasedItem.qml
  interface/resources/qml/hifi/commerce/purchases/Purchases.qml
  interface/resources/qml/styles-uit/HifiConstants.qml
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/avatar/MyAvatar.cpp
  interface/src/commerce/Ledger.cpp
  interface/src/commerce/Ledger.h
  interface/src/commerce/QmlCommerce.cpp
  interface/src/commerce/QmlCommerce.h
  interface/src/scripting/AccountServicesScriptingInterface.h
  libraries/avatars/src/AvatarData.h
  libraries/avatars/src/ScriptAvatarData.cpp
  libraries/avatars/src/ScriptAvatarData.h
  libraries/entities/src/EntityScriptingInterface.cpp
  libraries/entities/src/EntityScriptingInterface.h
  scripts/system/marketplaces/marketplaces.js
Labels: Commerce, Development Approved, QA Approved :tada:, disco-free

#12481 immediately show restore, set restore filename, cleanup old AS baked content on start
  assignment-client/src/assets/AssetServer.cpp
  assignment-client/src/assets/AssetServer.h
  domain-server/resources/web/content/js/content.js
  domain-server/src/DomainContentBackupManager.cpp
Labels: Development Approved

#12462 Fix EntityItems not getting destroyed
  interface/src/octree/OctreePacketProcessor.cpp
  libraries/entities/src/EntityTypes.cpp
Labels: Development Approved, Engine, QA Approved :tada:, bug

#12484 Relax deadlock watchdog
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/Menu.cpp
  interface/src/Menu.h
Labels: Development Approved, QA Approved :tada:

#12494 Remove the avatarEntitiesBookmark menu option
  interface/src/Application.cpp
  interface/src/AvatarBookmarks.cpp
  interface/src/AvatarBookmarks.h
  interface/src/AvatarEntitiesBookmarks.cpp
  interface/src/AvatarEntitiesBookmarks.h
  interface/src/Menu.cpp
  interface/src/Menu.h
Labels: Client, Development Approved, QA Approved :tada:

#12480 Commerce: Extended Certificates - Apps!
  interface/resources/fonts/hifi-glyphs.ttf
  interface/resources/qml/hifi/commerce/checkout/Checkout.qml
  interface/resources/qml/hifi/commerce/common/images/loader-blue.gif
  interface/resources/qml/hifi/commerce/purchases/PurchasedItem.qml
  interface/resources/qml/hifi/commerce/purchases/Purchases.qml
  interface/src/commerce/QmlCommerce.cpp
  interface/src/commerce/QmlCommerce.h
  scripts/system/marketplaces/marketplaces.js
Labels: Commerce, QA Ready, disco-free

#12458 Corrected edge case of creating a snapshot with "" as the filename.
  interface/src/Application.h
  interface/src/scripting/WindowScriptingInterface.h
Labels: Development Approved, Engine, QA Approved :tada:, Scripting API change

#12407 Shadow control for zones, models and shapes
  interface/resources/qml/hifi/dialogs/GraphicsPreferencesDialog.qml
  interface/resources/qml/hifi/tablet/TabletGraphicsPreferences.qml
  interface/src/Menu.cpp
  interface/src/Menu.h
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  libraries/entities-renderer/src/RenderableEntityItem.cpp
  libraries/entities-renderer/src/RenderableEntityItem.h
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities-renderer/src/RenderableZoneEntityItem.cpp
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityItemPropertiesDefaults.h
  libraries/entities/src/EntityPropertyFlags.h
  libraries/entities/src/KeyLightPropertyGroup.cpp
  libraries/entities/src/KeyLightPropertyGroup.h
  libraries/entities/src/ModelEntityItem.cpp
  libraries/entities/src/ShapeEntityItem.cpp
  libraries/entities/src/ShapeEntityItem.h
  libraries/graphics/src/graphics/Light.cpp
  libraries/graphics/src/graphics/Light.h
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
  libraries/render-utils/src/CauterizedModel.cpp
  libraries/render-utils/src/DeferredLightingEffect.cpp
  libraries/render-utils/src/DeferredLightingEffect.h
  libraries/render-utils/src/MeshPartPayload.cpp
  libraries/render-utils/src/MeshPartPayload.h
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
  libraries/render-utils/src/RenderShadowTask.cpp
  libraries/render-utils/src/RenderShadowTask.h
  libraries/render/src/render/Item.h
  scripts/system/html/entityProperties.html
  scripts/system/html/js/entityProperties.js
Labels: Development Approved, Engine, Packet Version Change, QA Approved :tada:, Scripting API change

#12489 Make sure sort indicator is attached to the right of title
  interface/resources/qml/controls-uit/Table.qml
  interface/resources/qml/hifi/Pal.qml
Labels: Client, Development Approved, QA Approved :tada:

#12485 Add dynamic mode for scripted avatar motor
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
Labels: Content/Create, Development Approved, QA Approved :tada:

#12449 change default add to world shape for asset browser
  interface/resources/qml/hifi/AssetServer.qml
  interface/resources/qml/hifi/dialogs/TabletAssetServer.qml
Labels: Development Approved, QA Approved :tada:

#12493 fix osx shadows
  libraries/render-utils/src/Shadow.slh
Labels: Client, Development Approved, Engine, Mac Required, QA Ready

#12498 Search main window by checking object name
  libraries/ui/src/OffscreenUi.cpp
Labels: Client, Development Approved, QA Approved :tada:

#12437 fix Qt 5.10 udt packet reading
  libraries/networking/src/udt/Socket.cpp
Labels: Client, QA Approved :tada:, Server & Network

#12503 timing CR for content archives
  assignment-client/src/assets/AssetServer.cpp
  domain-server/src/AssetsBackupHandler.cpp
  domain-server/src/AssetsBackupHandler.h
Labels: Server & Network

#12500 fixes for comments from code reviews
  domain-server/resources/web/content/js/content.js
  domain-server/src/ContentSettingsBackupHandler.cpp
  domain-server/src/DomainGatekeeper.cpp
  domain-server/src/DomainServer.cpp
  domain-server/src/DomainServerSettingsManager.cpp
  domain-server/src/DomainServerSettingsManager.h
Labels: Server & Network

#12477 Merge stable back into master
  interface/resources/qml/hifi/commerce/wallet/WalletSetup.qml
Labels: QA Approved :tada:, Stable Mergeback

#12456 Fix crash when passing --checkMinSpec flag
  assignment-client/src/main.cpp
  domain-server/src/main.cpp
  ice-server/src/main.cpp
  interface/src/Application.cpp
  interface/src/main.cpp
  libraries/shared/src/LogHandler.cpp
  libraries/shared/src/SettingInterface.cpp
  libraries/shared/src/SettingManager.cpp
  libraries/shared/src/SettingManager.h
  libraries/shared/src/SharedUtil.cpp
  libraries/shared/src/SharedUtil.h
  tests/entities/src/main.cpp
  tests/gpu-test/src/main.cpp
  tests/ktx/src/KtxTests.cpp
  tests/qml/src/main.cpp
  tests/qt59/src/main.cpp
  tests/recording/src/main.cpp
  tests/render-perf/src/main.cpp
  tests/render-texture-load/src/main.cpp
  tests/render-utils/src/main.cpp
  tests/shaders/src/main.cpp
  tools/ac-client/src/main.cpp
  tools/atp-client/src/main.cpp
  tools/auto-tester/src/main.cpp
  tools/ice-client/src/main.cpp
  tools/oven/src/main.cpp
  tools/skeleton-dump/src/main.cpp
  tools/udt-test/src/UDTTest.cpp
  tools/udt-test/src/main.cpp
  tools/vhacd-util/src/main.cpp
Labels: Development Approved, QA Approved :tada:

#12440 Leopoly_Phase1_010 Graphics Scripting
  interface/CMakeLists.txt
  interface/src/Application.cpp
  interface/src/ui/overlays/Base3DOverlay.h
  interface/src/ui/overlays/Cube3DOverlay.cpp
  interface/src/ui/overlays/Cube3DOverlay.h
  interface/src/ui/overlays/ModelOverlay.cpp
  interface/src/ui/overlays/ModelOverlay.h
  interface/src/ui/overlays/Shape3DOverlay.cpp
  interface/src/ui/overlays/Shape3DOverlay.h
  interface/src/ui/overlays/Sphere3DOverlay.cpp
  interface/src/ui/overlays/Sphere3DOverlay.h
  libraries/avatars-renderer/CMakeLists.txt
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
  libraries/entities-renderer/CMakeLists.txt
  libraries/entities-renderer/src/RenderableEntityItem.h
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.h
  libraries/entities-renderer/src/RenderablePolyLineEntityItem.cpp
  libraries/entities-renderer/src/RenderablePolyLineEntityItem.h
  libraries/entities-renderer/src/RenderablePolyVoxEntityItem.cpp
  libraries/entities-renderer/src/RenderablePolyVoxEntityItem.h
  libraries/entities-renderer/src/RenderableShapeEntityItem.cpp
  libraries/entities-renderer/src/RenderableShapeEntityItem.h
  libraries/fbx/src/FBX.h
  libraries/fbx/src/FBXReader.cpp
  libraries/fbx/src/OBJWriter.cpp
  libraries/gpu/src/gpu/Stream.cpp
  libraries/gpu/src/gpu/Stream.h
  libraries/graphics-scripting/CMakeLists.txt
  libraries/graphics-scripting/src/graphics-scripting/Forward.h
  libraries/graphics-scripting/src/graphics-scripting/GraphicsScriptingInterface.cpp
  libraries/graphics-scripting/src/graphics-scripting/GraphicsScriptingInterface.h
  libraries/graphics-scripting/src/graphics-scripting/GraphicsScriptingUtil.cpp
  libraries/graphics-scripting/src/graphics-scripting/GraphicsScriptingUtil.h
  libraries/graphics-scripting/src/graphics-scripting/ScriptableMesh.cpp
  libraries/graphics-scripting/src/graphics-scripting/ScriptableMesh.h
  libraries/graphics-scripting/src/graphics-scripting/ScriptableMeshPart.cpp
  libraries/graphics-scripting/src/graphics-scripting/ScriptableMeshPart.h
  libraries/graphics-scripting/src/graphics-scripting/ScriptableModel.cpp
  libraries/graphics-scripting/src/graphics-scripting/ScriptableModel.h
  libraries/graphics/src/graphics/BufferViewHelpers.cpp
  libraries/graphics/src/graphics/BufferViewHelpers.h
  libraries/graphics/src/graphics/Geometry.cpp
  libraries/graphics/src/graphics/Geometry.h
  libraries/graphics/src/graphics/GpuHelpers.cpp
  libraries/graphics/src/graphics/GpuHelpers.h
  libraries/render-utils/CMakeLists.txt
  libraries/render-utils/src/GeometryCache.cpp
  libraries/render-utils/src/GeometryCache.h
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
  libraries/script-engine/src/AssetScriptingInterface.cpp
  libraries/script-engine/src/ScriptEngines.cpp
  libraries/script-engine/src/ScriptEngines.h
  libraries/shared/src/shared/ScriptInitializerMixin.h
  tests/render-perf/CMakeLists.txt
Labels: Development Approved, Engine, QA Approved :tada:, outsource

#12492 Export boolean entity properties properly
  libraries/entities/src/EntityItemPropertiesMacros.h
Labels: Development Approved, QA Approved :tada:

#12513 Revert can cast shadow work
  interface/resources/qml/hifi/dialogs/GraphicsPreferencesDialog.qml
  interface/resources/qml/hifi/tablet/TabletGraphicsPreferences.qml
  interface/src/Menu.cpp
  interface/src/Menu.h
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  libraries/entities-renderer/src/RenderableEntityItem.cpp
  libraries/entities-renderer/src/RenderableEntityItem.h
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities-renderer/src/RenderableZoneEntityItem.cpp
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityItemPropertiesDefaults.h
  libraries/entities/src/EntityPropertyFlags.h
  libraries/entities/src/KeyLightPropertyGroup.cpp
  libraries/entities/src/KeyLightPropertyGroup.h
  libraries/entities/src/ModelEntityItem.cpp
  libraries/entities/src/ShapeEntityItem.cpp
  libraries/entities/src/ShapeEntityItem.h
  libraries/graphics/src/graphics/Light.cpp
  libraries/graphics/src/graphics/Light.h
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
  libraries/render-utils/src/CauterizedModel.cpp
  libraries/render-utils/src/DeferredLightingEffect.cpp
  libraries/render-utils/src/DeferredLightingEffect.h
  libraries/render-utils/src/MeshPartPayload.cpp
  libraries/render-utils/src/MeshPartPayload.h
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
  libraries/render-utils/src/RenderShadowTask.cpp
  libraries/render-utils/src/RenderShadowTask.h
  libraries/render/src/render/Item.h
  scripts/system/html/entityProperties.html
  scripts/system/html/js/entityProperties.js
Labels: Development Approved, Engine, QA Approved :tada:

#12497 End seeding
  interface/resources/qml/hifi/commerce/checkout/Checkout.qml
  interface/resources/qml/hifi/commerce/common/CommerceLightbox.qml
  interface/resources/qml/hifi/commerce/common/EmulatedMarketplaceHeader.qml
  interface/resources/qml/hifi/commerce/purchases/Purchases.qml
  interface/resources/qml/hifi/commerce/wallet/Wallet.qml
  interface/resources/qml/hifi/commerce/wallet/WalletChoice.qml
  interface/resources/qml/hifi/commerce/wallet/WalletHome.qml
  interface/src/commerce/Ledger.cpp
  interface/src/commerce/Ledger.h
  interface/src/commerce/QmlCommerce.cpp
  interface/src/commerce/QmlCommerce.h
  interface/src/commerce/Wallet.cpp
  interface/src/commerce/Wallet.h
  interface/src/ui/overlays/Web3DOverlay.cpp
  scripts/system/commerce/wallet.js
Labels: Commerce, Development Approved, QA Approved :tada:, disco-free

#12505 new wallet help
  interface/resources/qml/hifi/commerce/wallet/Help.qml
Labels: Commerce, disco-free

#12473 Logspam fix for editing in HMD mode
  scripts/system/edit.js
Labels: Content/Create, Development Approved, QA Approved :tada:

#12479 Near-field HRTF
  assignment-client/src/audio/AudioMixerSlave.cpp
  libraries/audio-client/src/AudioClient.cpp
  libraries/audio/src/AudioHRTF.cpp
  libraries/audio/src/AudioHRTF.h
Labels: Development Approved, QA Approved :tada:

#12474 workload: update space view and compute classification changes
  interface/src/Application.cpp
  libraries/workload/src/workload/ClassificationTracker.cpp
  libraries/workload/src/workload/ClassificationTracker.h
  libraries/workload/src/workload/Space.h
  tests/workload/src/SpaceTests.cpp
Labels: Development Approved, Engine

#12520 Fixed log spam undefined error
  scripts/system/libraries/entitySelectionTool.js
Labels: Development Approved, QA Approved :tada:

#12523 Adding more detailed stats
  interface/resources/qml/Stats.qml
  interface/src/ui/Stats.cpp
  interface/src/ui/Stats.h
Labels: Development Approved, Engine, QA Approved :tada:
