Repository highfidelity/hifi, pull requests merged in 2018-05, with the labels that each got.

#13056 RC67: add a missing unsafe_erase for local node ID map
  libraries/networking/src/LimitedNodeList.cpp
Labels: Critical Fix, Development Approved

#13061 JSDoc Entity preload, unload, startFarTrigger, etc.
  interface/src/scripting/ControllerScriptingInterface.h
  libraries/controllers/src/controllers/impl/MappingBuilderProxy.h
  libraries/controllers/src/controllers/impl/RouteBuilderProxy.h
  libraries/script-engine/src/ScriptEngine.cpp
Labels: Content/Create, Development Approved, JSDocs, QA Approved :tada:

#13062 fix physics related crash-on-exit
  libraries/physics/src/PhysicalEntitySimulation.cpp
Labels: Development Approved, QA Approved :tada:

#13063 Fix a crash in Image Provider when logging in or reloading all scripts
  interface/src/commerce/Wallet.cpp
Labels: Commerce, Development Approved, HMD required, QA Approved :tada:, bug

#13058 Fix LODManager JSDoc
  interface/src/LODManager.h
Labels: Content/Create, Development Approved, JSDocs, QA Approved :tada:

#13027 Some fixes for QML surfaces
  interface/resources/qml/controls/FlickableWebViewCore.qml
  interface/resources/qml/controls/WebView.qml
  libraries/entities-renderer/src/RenderableWebEntityItem.cpp
  libraries/qml/src/qml/impl/SharedObject.cpp
  libraries/shared/src/Trace.h
  libraries/ui/src/ui/OffscreenQmlSurface.cpp
  libraries/ui/src/ui/OffscreenQmlSurface.h
  tests/qml/qml/controls/WebEntityView.qml
  tests/qml/src/main.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#13064 merge changes in 66.2 to 67
  interface/src/ui/AddressBarDialog.cpp
  libraries/networking/src/AddressManager.cpp
  libraries/networking/src/DomainHandler.cpp
Labels: Development Approved, QA Approved :tada:

#13057 Remove 'Create Items as Grabbable' Menu item in cleanup for edit
  scripts/system/edit.js
Labels: Content/Create, Development Approved, QA Approved :tada:, bug

#13070 Prevent call of getDomainLocalID() by domain server itself more robustly
  libraries/networking/src/LimitedNodeList.cpp
Labels: Development Approved, Server & Network

#13071 RC67: Fix a crash in Image Provider when logging in or reloading all scripts
  interface/src/commerce/Wallet.cpp
Labels: Development Approved, HMD required, QA Ready, bug

#13052 Eliminated warnings in gcc
  assignment-client/src/assets/AssetServer.h
  libraries/audio/src/InboundAudioStream.cpp
  libraries/entities/src/EntityTree.cpp
  libraries/fbx/src/FBXWriter.cpp
  libraries/networking/src/ResourceCache.cpp
  libraries/shared/src/Gzip.cpp
Labels: Client, Development Approved, QA Approved :tada:

#13013 fix bug: interface sends too many updates on settle
  libraries/physics/src/EntityMotionState.cpp
Labels: Development Approved, Engine, QA Approved :tada:, bug

#12960 Added items to the developer menu for debugging physics
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/Menu.cpp
  interface/src/Menu.h
  libraries/physics/src/PhysicsDebugDraw.cpp
  libraries/physics/src/PhysicsDebugDraw.h
  libraries/physics/src/PhysicsEngine.cpp
  libraries/physics/src/PhysicsEngine.h
  libraries/render-utils/src/AnimDebugDraw.cpp
Labels: Avatar, Development Approved, Engine, QA Approved :tada:

#13077 Make resource swapchains immutable
  libraries/gpu-gl-common/src/gpu/gl/GLBackendOutput.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLBackendPipeline.cpp
  libraries/gpu/src/gpu/ResourceSwapChain.h
  libraries/render-utils/src/AntialiasingEffect.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#13054 workload: yield simulation ownership of objects outside nearby region
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/SimulationOwner.h
  libraries/physics/src/EntityMotionState.cpp
  libraries/physics/src/EntityMotionState.h
  libraries/physics/src/PhysicalEntitySimulation.cpp
Labels: Engine

#12985 fixing avatr attachments not being visible when coming out of first person
  interface/src/avatar/MyAvatar.cpp
Labels: Client, Development Approved, Engine, QA Approved :tada:, bug

#13049 List which contexts each namespace and class is available in
  interface/src/AvatarBookmarks.h
  interface/src/LODManager.h
  interface/src/SpeechRecognizer.h
  interface/src/audio/AudioScope.h
  interface/src/avatar/AvatarManager.h
  interface/src/devices/DdeFaceTracker.h
  interface/src/raypick/PickScriptingInterface.h
  interface/src/raypick/PointerScriptingInterface.h
  interface/src/scripting/AccountServicesScriptingInterface.h
  interface/src/scripting/Audio.h
  interface/src/scripting/ClipboardScriptingInterface.h
  interface/src/scripting/ControllerScriptingInterface.h
  interface/src/scripting/GooglePolyScriptingInterface.h
  interface/src/scripting/HMDScriptingInterface.h
  interface/src/scripting/MenuScriptingInterface.h
  interface/src/scripting/SelectionScriptingInterface.h
  interface/src/scripting/SettingsScriptingInterface.h
  interface/src/scripting/WindowScriptingInterface.h
  interface/src/ui/AvatarInputs.h
  interface/src/ui/overlays/ContextOverlayInterface.h
  interface/src/ui/overlays/Overlays.h
  libraries/animation/src/AnimationCache.h
  libraries/audio-client/src/AudioIOStats.h
  libraries/audio/src/SoundCache.h
  libraries/controllers/src/controllers/impl/MappingBuilderProxy.h
  libraries/controllers/src/controllers/impl/RouteBuilderProxy.h
  libraries/display-plugins/src/display-plugins/CompositorHelper.h
  libraries/entities/src/EntityScriptingInterface.h
  libraries/graphics-scripting/src/graphics-scripting/GraphicsScriptingInterface.h
  libraries/model-networking/src/model-networking/ModelCache.h
  libraries/model-networking/src/model-networking/TextureCache.h
  libraries/networking/src/AddressManager.h
  libraries/networking/src/MessagesClient.h
  libraries/networking/src/ResourceCache.h
  libraries/script-engine/src/AssetScriptingInterface.h
  libraries/script-engine/src/Quat.h
  libraries/script-engine/src/RecordingScriptingInterface.h
  libraries/script-engine/src/SceneScriptingInterface.h
  libraries/script-engine/src/ScriptEngine.h
  libraries/script-engine/src/ScriptEngines.h
  libraries/script-engine/src/ScriptUUID.h
  libraries/script-engine/src/ScriptsModel.h
  libraries/script-engine/src/ScriptsModelFilter.h
  libraries/script-engine/src/UsersScriptingInterface.h
  libraries/script-engine/src/Vec3.h
  libraries/shared/src/DebugDraw.h
  libraries/shared/src/PathUtils.h
  libraries/shared/src/RegisteredMetaTypes.h
  libraries/shared/src/shared/Camera.h
  libraries/ui/src/ui/TabletScriptingInterface.h
Labels: Content/Create, JSDocs, QA Approved :tada:

#13087 Fix MS14640: Default audio meter overlay to "on"
  interface/src/ui/AvatarInputs.cpp
Labels: Client, Development Approved, QA Approved :tada:

#13081 Fix MS14741, allowing uninstall of apps whose scripts are no longer running
  interface/src/commerce/QmlCommerce.cpp
Labels: Commerce, QA Approved :tada:, bug

#13080 Fix asan warnings
  libraries/audio/src/AudioDynamics.h
  libraries/audio/src/AudioReverb.cpp
  libraries/audio/src/AudioSRC.cpp
Labels: Client, Development Approved, QA Approved :tada:

#13076 JSDoc fixes
  interface/src/scripting/SelectionScriptingInterface.h
  libraries/animation/src/AnimationCache.h
  libraries/audio/src/SoundCache.h
  libraries/graphics-scripting/src/graphics-scripting/GraphicsScriptingInterface.h
  libraries/model-networking/src/model-networking/ModelCache.h
  libraries/model-networking/src/model-networking/TextureCache.h
  libraries/networking/src/ResourceCache.h
Labels: Content/Create, Development Approved, JSDocs

#13089 RC 67 fix entity highlighting
  scripts/system/controllers/controllerModules/highlightNearbyEntities.js
  scripts/system/controllers/controllerModules/mouseHighlightEntities.js
  scripts/system/controllers/grab.js
Labels: Client, Development Approved, QA Approved :tada:

#13092 Fix uninitialized boolean (asan warning)
  libraries/networking/src/NodeList.h
Labels: Development Approved, QA Approved :tada:

#13086 RC 66.2: Fixing the strobing light effect, aka Translucent lighting by ponctual lights
  libraries/entities-renderer/src/RenderableParticleEffectEntityItem.cpp
  libraries/entities-renderer/src/RenderablePolyLineEntityItem.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLBackend.h
  libraries/gpu/src/gpu/Batch.cpp
Labels: Development Approved, Engine, Mac Required, QA Approved :tada:, bug

#13084 Fix wizard wording
  domain-server/resources/web/wizard/index.shtml
Labels: QA Approved :tada:, Server & Network

#13007 Keep CrashpadClient around for application lifetime
  interface/src/Crashpad.cpp
  libraries/shared/src/CrashHelpers.cpp
  libraries/shared/src/CrashHelpers.h
Labels: Development Approved, QA Approved :tada:, Server & Network

#12930 Add support for multifrustum entity queries
  assignment-client/src/entities/EntityPriorityQueue.cpp
  assignment-client/src/entities/EntityPriorityQueue.h
  assignment-client/src/entities/EntityTreeSendThread.cpp
  assignment-client/src/entities/EntityTreeSendThread.h
  assignment-client/src/octree/OctreeHeadlessViewer.cpp
  assignment-client/src/octree/OctreeHeadlessViewer.h
  assignment-client/src/octree/OctreeSendThread.cpp
  assignment-client/src/scripts/EntityScriptServer.cpp
  interface/src/Application.cpp
  interface/src/Application.h
  libraries/entities/src/DiffTraversal.cpp
  libraries/entities/src/DiffTraversal.h
  libraries/entities/src/EntityTree.h
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
  libraries/octree/src/Octree.h
  libraries/octree/src/OctreeQuery.cpp
  libraries/octree/src/OctreeQuery.h
  libraries/octree/src/OctreeQueryNode.cpp
  libraries/octree/src/OctreeQueryNode.h
  libraries/octree/src/OctreeUtils.cpp
  libraries/octree/src/OctreeUtils.h
  libraries/shared/src/ViewFrustum.cpp
  libraries/shared/src/ViewFrustum.h
Labels: Development Approved, QA Approved :tada:, Server & Network

#13091 Master: Fixing the strobing light effect, aka Translucent lighting by ponctual lights
  libraries/entities-renderer/src/RenderableParticleEffectEntityItem.cpp
  libraries/entities-renderer/src/RenderablePolyLineEntityItem.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLBackend.h
  libraries/gpu/src/gpu/Batch.cpp
Labels: Development Approved, Engine, Mac Required, QA Approved :tada:, bug

#13069 Remove deprecated location.domainId from API
  libraries/networking/src/AddressManager.h
Labels: Client, Development Approved, QA Approved :tada:

#13018 Fix old log files not being cleaned up
  libraries/shared/src/shared/FileLogger.cpp
Labels: Development Approved, QA Approved :tada:

#13101 MS14758: Fix avatar reset when gifting worn avatar
  interface/resources/qml/hifi/commerce/purchases/Purchases.qml
Labels: Commerce, Development Approved, QA Approved :tada:, bug

#13100 Don't highlight entities during edit mode
  scripts/system/controllers/controllerModules/mouseHighlightEntities.js
Labels: Client, Development Approved, QA Approved :tada:

#13094 Fix for crash deep in QML after useFullAvatarURL
  interface/src/avatar/MyAvatar.cpp
  libraries/model-networking/src/model-networking/ModelCache.cpp
  libraries/model-networking/src/model-networking/ModelCache.h
Labels: Avatar, Development Approved, QA Approved :tada:

#13097 workload: stop locally-owned dynamic entities when removed from Bullet simulation
  libraries/entities/src/SimpleEntitySimulation.cpp
  libraries/physics/src/PhysicalEntitySimulation.cpp
Labels: Engine

#13098 update server-console dependency hook
  server-console/package-lock.json
  server-console/package.json
Labels: Development Approved, QA Approved :tada:

#12992 Fixed procedural shaders
  libraries/render-utils/src/forward_simple.slf
  libraries/render-utils/src/forward_simple_transparent.slf
  libraries/render-utils/src/simple.slf
  libraries/render-utils/src/simple_fade.slf
  libraries/render-utils/src/simple_transparent.slf
Labels: Development Approved, Engine, QA Approved :tada:

#13074 Multifrustum queries punchlist
  assignment-client/src/Agent.cpp
  assignment-client/src/Agent.h
  assignment-client/src/avatars/AvatarMixer.cpp
  assignment-client/src/avatars/AvatarMixer.h
  assignment-client/src/avatars/AvatarMixerClientData.cpp
  assignment-client/src/avatars/AvatarMixerClientData.h
  assignment-client/src/entities/EntityPriorityQueue.cpp
  assignment-client/src/entities/EntityTreeSendThread.cpp
  assignment-client/src/entities/EntityTreeSendThread.h
  assignment-client/src/octree/OctreeHeadlessViewer.cpp
  assignment-client/src/octree/OctreeSendThread.cpp
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/avatar/AvatarManager.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.h
  libraries/entities/src/DiffTraversal.cpp
  libraries/entities/src/DiffTraversal.h
  libraries/entities/src/EntityPriorityQueue.h
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
  libraries/octree/src/OctreeQuery.cpp
  libraries/octree/src/OctreeQuery.h
  libraries/octree/src/OctreeQueryNode.cpp
  libraries/octree/src/OctreeQueryNode.h
  libraries/octree/src/OctreeUtils.h
  libraries/render-utils/src/AbstractViewStateInterface.h
  libraries/shared/src/GLMHelpers.cpp
  libraries/shared/src/GLMHelpers.h
  libraries/shared/src/NumericalConstants.h
  libraries/shared/src/PrioritySortUtil.h
  libraries/shared/src/ViewFrustum.cpp
  libraries/shared/src/ViewFrustum.h
  libraries/shared/src/shared/ConicalViewFrustum.cpp
  libraries/shared/src/shared/ConicalViewFrustum.h
  tests/render-perf/src/main.cpp
Labels: Development Approved, QA Approved :tada:, Server & Network

#12956 Add support for client texture selection
  assignment-client/src/assets/AssetServer.h
  interface/src/Application.cpp
  libraries/baking/src/FBXBaker.cpp
  libraries/baking/src/FBXBaker.h
  libraries/baking/src/ModelBaker.cpp
  libraries/baking/src/ModelBaker.h
  libraries/baking/src/OBJBaker.cpp
  libraries/baking/src/OBJBaker.h
  libraries/baking/src/TextureBaker.cpp
  libraries/baking/src/TextureBaker.h
  libraries/gpu-gl/src/gpu/gl41/GL41Backend.h
  libraries/gpu-gl/src/gpu/gl45/GL45Backend.h
  libraries/gpu-gl/src/gpu/gl45/GL45BackendTexture.cpp
  libraries/gpu-gles/src/gpu/gles/GLESBackend.h
  libraries/gpu/src/gpu/Context.h
  libraries/gpu/src/gpu/Texture.h
  libraries/gpu/src/gpu/Texture_ktx.cpp
  libraries/ktx/src/TextureMeta.cpp
  libraries/ktx/src/TextureMeta.h
  libraries/ktx/src/khronos/KHR.h
  libraries/model-networking/src/model-networking/ModelCache.cpp
  libraries/model-networking/src/model-networking/TextureCache.cpp
  libraries/model-networking/src/model-networking/TextureCache.h
  libraries/networking/src/ResourceCache.cpp
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
  tools/oven/src/DomainBaker.cpp
Labels: Development Approved, QA Approved :tada:

#12996 Fix debug assert in manipulating thread local data to store GL surfaces
  libraries/gl/src/gl/OffscreenGLCanvas.cpp
  libraries/gl/src/gl/OffscreenGLCanvas.h
Labels: Development Approved, Engine, QA Approved :tada:

#13107 RC67: Fix for crash deep in QML after useFullAvatarURL
  interface/src/avatar/MyAvatar.cpp
  libraries/model-networking/src/model-networking/ModelCache.cpp
  libraries/model-networking/src/model-networking/ModelCache.h
Labels: Avatar, Development Approved, QA Approved :tada:, bug

#13105 fix-another-highlighting-issue
  scripts/system/controllers/controllerModules/highlightNearbyEntities.js
  scripts/system/controllers/controllerModules/inEditMode.js
Labels: Client, Development Approved, QA Approved :tada:

#13106 RC67: MS14758: Fix avatar reset when gifting worn avatar
  interface/resources/qml/hifi/commerce/purchases/Purchases.qml
Labels: Commerce, Development Approved, QA Approved :tada:, bug

#13032 don't spam resetSensors function when holding down Qt::Key_Apostrophe
  interface/src/Application.cpp
Labels: Client, Development Approved, QA Approved :tada:

#13116 Fix for 'Login page for steam is blank'
  interface/resources/qml/LoginDialog/SignInBody.qml
Labels: Critical Fix, Development Approved, QA Approved :tada:, bug

#13123 remove highlight on entity when point to the sky (RC67)
  scripts/system/controllers/controllerModules/farActionGrabEntity.js
  scripts/system/controllers/controllerModules/mouseHighlightEntities.js
Labels: Client, Development Approved, QA Approved :tada:

#13121 MS3128: Remove vestigial Edit menu item
  scripts/system/edit.js
Labels: Content/Create, Development Approved, QA Approved :tada:, bug

#13113 avoid misaligned pointer deref in ktx code
  libraries/gpu/src/gpu/Texture_ktx.cpp
Labels: Client, Development Approved, QA Approved :tada:

#13119 MS14878: Prevent wallet passphrase leak in specific case
  scripts/system/marketplaces/marketplaces.js
Labels: Commerce, Development Approved, HMD required, QA Approved :tada:, bug

#13132 MS14937: Fix Replace button for content sets during Checkout
  interface/resources/qml/hifi/commerce/checkout/Checkout.qml
Labels: Commerce, Development Approved, QA Ready, bug

#13129 Fix hmd js
  scripts/system/hmd.js
Labels: Client, Development Approved, QA Ready

#13055 Do not open help on first run
  interface/src/Application.cpp
Labels: Client, Content/Create, Development Approved, QA Approved :tada:, bug

#13046 Command line parameters for autotester
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/ui/Snapshot.cpp
  interface/src/ui/Snapshot.h
  libraries/script-engine/src/ScriptEngine.h
  libraries/script-engine/src/ScriptEngines.cpp
  libraries/script-engine/src/ScriptEngines.h
  tools/auto-tester/src/Downloader.cpp
  tools/auto-tester/src/Test.cpp
  tools/auto-tester/src/Test.h
  tools/auto-tester/src/main.cpp
  tools/auto-tester/src/ui/AutoTester.cpp
  tools/auto-tester/src/ui/AutoTester.h
  tools/auto-tester/src/ui/AutoTester.ui
Labels: Development Approved, Engine, QA Approved :tada:, QA Ready

#13135 MS14951: Fix Snapshot hotkey sound playback
  interface/src/Application.cpp
Labels: Development Approved, Discovery, QA Ready, bug

#13136 RC67: MS14951: Fix Snapshot hotkey sound playback
  interface/src/Application.cpp
Labels: Development Approved, Discovery, QA Approved :tada:, bug

#13130 Fix size calculation of compressed textures #13120
  libraries/gpu/src/gpu/Format.h
Labels: Development Approved, Engine, QA Approved :tada:

#13137 when in serverless mode, short-circuit simulation ownership bids
  libraries/entities/src/EntityEditPacketSender.cpp
  libraries/octree/src/OctreeEditPacketSender.cpp
  libraries/octree/src/OctreeEditPacketSender.h
  libraries/physics/src/EntityMotionState.cpp
  libraries/physics/src/EntityMotionState.h
  libraries/physics/src/PhysicalEntitySimulation.cpp
Labels: Client, Development Approved, Engine, QA Approved :tada:, bug

#13131 MS14937: Fix Replace button for content sets during Checkout
  interface/resources/qml/hifi/commerce/checkout/Checkout.qml
Labels: Commerce, Development Approved, QA Approved :tada:, bug

#13102 Fix JSDoc for Users.requestUsernameFromID
  libraries/script-engine/src/UsersScriptingInterface.h
Labels: Content/Create, JSDocs, QA Approved :tada:

#13117 Test highp floats for Android
  libraries/gpu-gl/src/gpu/gl41/GL41BackendShader.cpp
  libraries/gpu-gl/src/gpu/gl45/GL45BackendShader.cpp
  libraries/gpu-gles/src/gpu/gles/GLESBackendShader.cpp
  libraries/graphics/src/graphics/Light.slh
  libraries/graphics/src/graphics/LightIrradiance.shared.slh
  libraries/graphics/src/graphics/LightVolume.shared.slh
  libraries/graphics/src/graphics/Material.slh
  libraries/graphics/src/graphics/SphericalHarmonics.shared.slh
  libraries/render-utils/src/LightingModel.slh
Labels: Android, Android Smoke Required, Development Approved, Engine, QA Approved :tada:

#13114 more suppression of logging
  interface/src/Application.cpp
  libraries/entities/src/EntityItem.cpp
  libraries/qml/src/qml/Logging.h
  libraries/script-engine/src/ScriptEngine.cpp
  libraries/script-engine/src/ScriptEngineLogging.cpp
  libraries/script-engine/src/ScriptEngineLogging.h
Labels: Client, Development Approved, QA Approved :tada:

#12746 Android: Fix zoom in unresponsive in radar mode
  scripts/system/+android/radar.js
Labels: Android, Android Smoke Required, Development Approved, QA Approved :tada:

#13005 Use HMAC authentication for network packets - 2nd attempt
  libraries/networking/src/HMACAuth.cpp
  libraries/networking/src/HMACAuth.h
  libraries/networking/src/LimitedNodeList.cpp
  libraries/networking/src/LimitedNodeList.h
  libraries/networking/src/NLPacket.cpp
  libraries/networking/src/NLPacket.h
  libraries/networking/src/Node.cpp
  libraries/networking/src/Node.h
  libraries/networking/src/udt/PacketHeaders.cpp
Labels: Development Approved, Packet Version Change, QA Approved :tada:, Server & Network

#13153 [RC67.1] Bug fix for Vive Tracker Calibration Settings
  interface/resources/qml/hifi/tablet/ControllerSettings.qml
Labels: Avatar, Client, Critical Fix, Development Approved, HMD required, QA Approved :tada:, Vive Tracker Required, bug

#13149 RC67.1: Fixed procedural shaders
  libraries/entities-renderer/src/RenderableZoneEntityItem.cpp
  libraries/render-utils/src/forward_simple.slf
  libraries/render-utils/src/forward_simple_transparent.slf
  libraries/render-utils/src/simple.slf
  libraries/render-utils/src/simple_fade.slf
  libraries/render-utils/src/simple_transparent.slf
Labels: Critical Fix, Development Approved, Engine, bug

#13156 Bug fix for Manuscript issue 15019 : "Translucent Model over Procedural SHader is broken"
  libraries/graphics/src/graphics/skybox.slf
  libraries/procedural/src/procedural/Procedural.cpp
Labels: Development Approved, Engine, QA Ready, bug

#12989 Worklist #21774: Fix Windows.browseAssets() bugs
  interface/resources/qml/dialogs/assetDialog/AssetDialogContent.qml
Labels: Client, Development Approved, QA Approved :tada:

#13155 Beta Release 67.1 - branched at Developer Release 8260
  interface/resources/qml/hifi/tablet/ControllerSettings.qml
  libraries/entities-renderer/src/RenderableZoneEntityItem.cpp
  libraries/graphics/src/graphics/skybox.slf
  libraries/procedural/src/procedural/Procedural.cpp
  libraries/render-utils/src/forward_simple.slf
  libraries/render-utils/src/forward_simple_transparent.slf
  libraries/render-utils/src/simple.slf
  libraries/render-utils/src/simple_fade.slf
  libraries/render-utils/src/simple_transparent.slf
Labels: Critical Fix, Development Approved, QA Ready, master -> stable

#13146 don't enable so much logging when 'verbose logging' is turned on
  interface/src/Application.cpp
  libraries/audio/src/AudioLogging.cpp
Labels: Client, Development Approved, QA Approved :tada:

#12947 Additional work on splash screen
  interface/resources/shaders/splashSkybox.frag
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/Application_render.cpp
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.cpp
  libraries/procedural/src/procedural/Procedural.cpp
  libraries/ui-plugins/src/ui-plugins/PluginContainer.h
  plugins/oculus/src/OculusBaseDisplayPlugin.cpp
Labels: Android Smoke Required, Development Approved, Engine, QA Approved :tada:

#13157 fix qml crash on start up
  interface/resources/qml/dialogs/assetDialog/AssetDialogContent.qml
Labels: Client, Critical Fix, Development Approved, QA Ready

#13045 Reset pending domain check-in count more frequently
  libraries/networking/src/DomainHandler.h
  libraries/networking/src/NodeList.cpp
Labels: Android, Development Approved, Server & Network

#13159 don't assert when unserializing a 'spring' action
  libraries/physics/src/ObjectActionTractor.cpp
Labels: Client, Development Approved

#13147 Fix JSDoc function definitions specifying properties instead of params
  libraries/entities/src/EntityScriptingInterface.h
  libraries/script-engine/src/AssetScriptingInterface.h
Labels: Content/Create, Development Approved, JSDocs, QA Approved :tada:

#13139 Autotester: Now remembers the previous folder.
  tools/auto-tester/src/Test.cpp
  tools/auto-tester/src/Test.h
Labels: Development Approved, Engine, QA Approved :tada:

#12814 Shadow bug fix : incorrect shadow map far plane when casting shadow on non-'shadow casters'
  libraries/render-utils/src/RenderShadowTask.cpp
  libraries/render-utils/src/RenderShadowTask.h
  libraries/render/src/render/CullTask.cpp
  libraries/render/src/render/CullTask.h
Labels: Development Approved, Engine, Mac Required, QA Approved :tada:, outsource

#13138 avoid div by zero when measuring RigidBody effective acceleration
  libraries/physics/src/EntityMotionState.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#13150 fix lastEdited vs pal
  scripts/system/pal.js
Labels: Development Approved, QA Approved :tada:

#13166 Show invalidated items in My Purchases
  interface/resources/qml/hifi/commerce/purchases/PurchasedItem.qml
  interface/resources/qml/hifi/commerce/purchases/Purchases.qml
Labels: Commerce, Development Approved, QA Approved :tada:, bug

#13163 fix near-grab attaching entity to hips
  scripts/system/controllers/controllerModules/equipEntity.js
  scripts/system/controllers/controllerModules/nearActionGrabEntity.js
  scripts/system/controllers/controllerModules/nearGrabHyperLinkEntity.js
  scripts/system/controllers/controllerModules/nearParentGrabEntity.js
  scripts/system/controllers/controllerModules/nearParentGrabOverlay.js
  scripts/system/controllers/controllerModules/teleport.js
  scripts/system/libraries/controllerDispatcherUtils.js
Labels: Client, Development Approved, QA Approved :tada:

#13169 OpenVR: Remove reference to HMD Standing Mode menu item
  interface/src/Menu.h
  plugins/openvr/src/OpenVrDisplayPlugin.cpp
Labels: Avatar, Development Approved, Engine, HMD required, QA Approved :tada:, Vive Required

#13154 Added method to test namespace to save JSON object to a file.
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/scripting/TestScriptingInterface.cpp
  interface/src/scripting/TestScriptingInterface.h
Labels: Development Approved, Engine, QA Approved :tada:, Scripting API change

#13115 fix divide-by-zero asan warning in LODManager::autoAdjustLOD
  interface/src/LODManager.cpp
Labels: Client, Development Approved

#13110 Don't unnecessarily scroll HTML content when keyboard is raised
  interface/resources/html/raiseAndLowerKeyboard.js
  scripts/system/html/entityList.html
  scripts/system/html/entityProperties.html
  scripts/system/html/gridControls.html
  scripts/system/html/js/entityList.js
  scripts/system/html/js/entityProperties.js
  scripts/system/html/js/gridControls.js
  scripts/system/html/js/keyboardControl.js
Labels: Client, Content/Create, Development Approved, QA Approved :tada:

#13112 Fix overlay asan warning
  interface/src/ui/overlays/Overlays.h
  tests-manual/render-texture-load/src/GLIHelpers.h
Labels: Client, Development Approved, QA Approved :tada:

#13173 TAA fix for highlight
  libraries/render-utils/src/AntialiasingEffect.cpp
  libraries/render-utils/src/HighlightEffect.cpp
  libraries/render-utils/src/HighlightEffect.h
  libraries/render-utils/src/RenderDeferredTask.cpp
  libraries/render-utils/src/RenderDeferredTask.h
  libraries/render/src/render/DrawStatus.cpp
  libraries/render/src/render/DrawStatus.h
Labels: Development Approved, Engine, QA Approved :tada:

#12939 Android Search & Go To
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/assets/hifi_domains.json
  android/app/src/main/cpp/native.cpp
  android/app/src/main/java/io/highfidelity/hifiinterface/GotoActivity.java
  android/app/src/main/java/io/highfidelity/hifiinterface/HifiUtils.java
  android/app/src/main/java/io/highfidelity/hifiinterface/HomeActivity.java
  android/app/src/main/java/io/highfidelity/hifiinterface/InterfaceActivity.java
  android/app/src/main/java/io/highfidelity/hifiinterface/LoginActivity.java
  android/app/src/main/java/io/highfidelity/hifiinterface/PermissionChecker.java
  android/app/src/main/java/io/highfidelity/hifiinterface/QtPreloader/QtPreloader.java
  android/app/src/main/java/io/highfidelity/hifiinterface/SplashActivity.java
  android/app/src/main/java/io/highfidelity/hifiinterface/provider/Callback.java
  android/app/src/main/java/io/highfidelity/hifiinterface/provider/DomainProvider.java
  android/app/src/main/java/io/highfidelity/hifiinterface/provider/UserStoryDomainProvider.java
  android/app/src/main/java/io/highfidelity/hifiinterface/view/DomainAdapter.java
  android/app/src/main/java/org/qtproject/qt5/android/bindings/QtActivity.java
  android/app/src/main/res/drawable/domain_bg.xml
  android/app/src/main/res/drawable/hifi_header.xml
  android/app/src/main/res/drawable/ic_clear.xml
  android/app/src/main/res/drawable/ic_search.xml
  android/app/src/main/res/drawable/rounded_button.xml
  android/app/src/main/res/drawable/rounded_edit.xml
  android/app/src/main/res/layout/activity_home.xml
  android/app/src/main/res/layout/activity_login.xml
  android/app/src/main/res/layout/activity_splash.xml
  android/app/src/main/res/layout/content_home.xml
  android/app/src/main/res/layout/domain_view.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/dimens.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
  interface/src/AndroidHelper.cpp
  interface/src/AndroidHelper.h
  interface/src/Application.cpp
  libraries/display-plugins/src/display-plugins/Basic2DWindowOpenGLDisplayPlugin.cpp
  libraries/networking/src/AccountManager.cpp
  libraries/networking/src/AccountManager.h
  libraries/ui/src/VirtualPadManager.h
Labels: Android, Android Smoke Required, Development Approved

#13178 Rc67.2 : Fixing translucents objects in ambient lighting
  libraries/render-utils/src/DeferredBufferWrite.slh
  libraries/render-utils/src/DeferredGlobalLight.slh
  libraries/render-utils/src/DeferredLightingEffect.cpp
  libraries/render-utils/src/DeferredLightingEffect.h
  libraries/render-utils/src/GeometryCache.cpp
  libraries/render-utils/src/Haze.slf
  libraries/render-utils/src/LightClusters.cpp
  libraries/render-utils/src/LightingModel.cpp
  libraries/render-utils/src/LightingModel.h
  libraries/render-utils/src/LightingModel.slh
  libraries/render-utils/src/RenderDeferredTask.cpp
  libraries/render-utils/src/RenderForwardTask.cpp
  libraries/render/src/render/ShapePipeline.cpp
  libraries/render/src/render/ShapePipeline.h
  scripts/developer/utilities/render/deferredLighting.qml
Labels: Android Smoke Required, Development Approved, Engine, Mac Required, QA Approved :tada:, Windows Required

#13175 Fix hips position when flying
  interface/src/avatar/MySkeletonModel.cpp
Labels: Avatar, Development Approved, QA Approved :tada:, bug

#13141 Spectator Camera V2
  interface/resources/qml/controls-uit/CheckBox.qml
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/SecondaryCamera.cpp
  interface/src/scripting/WindowScriptingInterface.cpp
  interface/src/scripting/WindowScriptingInterface.h
  interface/src/ui/PreferencesDialog.cpp
  interface/src/ui/Snapshot.cpp
  interface/src/ui/Snapshot.h
  scripts/system/notifications.js
  unpublishedScripts/marketplace/spectator-camera/Spectator Camera Marketplace Image.jpg
  unpublishedScripts/marketplace/spectator-camera/SpectatorCamera.qml
  unpublishedScripts/marketplace/spectator-camera/processing.gif
  unpublishedScripts/marketplace/spectator-camera/snap.wav
  unpublishedScripts/marketplace/spectator-camera/spectatorCamera.app.json
  unpublishedScripts/marketplace/spectator-camera/spectatorCamera.js
  unpublishedScripts/marketplace/spectator-camera/static.gif
Labels: Development Approved, Discovery, HMD required, QA Approved :tada:, Scripting API change

#13181 Fix MS15103: Interface crashes on snap if snap dir is deleted
  interface/src/Application.cpp
  interface/src/ui/Snapshot.cpp
  interface/src/ui/SnapshotAnimated.cpp
  interface/src/ui/SnapshotAnimated.h
Labels: Development Approved, Discovery, QA Approved :tada:, bug

#13180 Fix Joystick/Control not showing up in Samsung after typing address (Android)
  libraries/input-plugins/src/input-plugins/TouchscreenVirtualPadDevice.cpp
Labels: Android, Android Smoke Required, Development Approved, QA Approved :tada:

#13185 Rc67.2 Provide a toggle switch for TAA in the menu developer/render to opt-out
  interface/src/Menu.cpp
  interface/src/Menu.h
  libraries/render-utils/src/AntialiasingEffect.h
  scripts/developer/utilities/render/antialiasing.qml
Labels: Android Smoke Required, Development Approved, Engine, HMD required, Mac Required, QA Ready, Vive Required, Vive Tracker Required, Windows Required

#13177 Beta Release 67.2 - branched at Developer Release 8265
  interface/src/Menu.cpp
  interface/src/Menu.h
  libraries/render-utils/src/AntialiasingEffect.cpp
  libraries/render-utils/src/AntialiasingEffect.h
  libraries/render-utils/src/DeferredBufferWrite.slh
  libraries/render-utils/src/DeferredGlobalLight.slh
  libraries/render-utils/src/DeferredLightingEffect.cpp
  libraries/render-utils/src/DeferredLightingEffect.h
  libraries/render-utils/src/GeometryCache.cpp
  libraries/render-utils/src/Haze.slf
  libraries/render-utils/src/HighlightEffect.cpp
  libraries/render-utils/src/HighlightEffect.h
  libraries/render-utils/src/LightClusters.cpp
  libraries/render-utils/src/LightingModel.cpp
  libraries/render-utils/src/LightingModel.h
  libraries/render-utils/src/LightingModel.slh
  libraries/render-utils/src/RenderDeferredTask.cpp
  libraries/render-utils/src/RenderDeferredTask.h
  libraries/render-utils/src/RenderForwardTask.cpp
  libraries/render/src/render/DrawStatus.cpp
  libraries/render/src/render/DrawStatus.h
  libraries/render/src/render/ShapePipeline.cpp
  libraries/render/src/render/ShapePipeline.h
  scripts/developer/utilities/render/antialiasing.qml
  scripts/developer/utilities/render/deferredLighting.qml
Labels: Development Approved, QA Approved :tada:, master -> stable

#13190 RC67.2 stable mergeback to master
  interface/src/Menu.cpp
  interface/src/Menu.h
  libraries/render-utils/src/AntialiasingEffect.cpp
  libraries/render-utils/src/AntialiasingEffect.h
  libraries/render-utils/src/DeferredBufferWrite.slh
  libraries/render-utils/src/DeferredGlobalLight.slh
  libraries/render-utils/src/DeferredLightingEffect.cpp
  libraries/render-utils/src/DeferredLightingEffect.h
  libraries/render-utils/src/GeometryCache.cpp
  libraries/render-utils/src/Haze.slf
  libraries/render-utils/src/HighlightEffect.cpp
  libraries/render-utils/src/HighlightEffect.h
  libraries/render-utils/src/LightClusters.cpp
  libraries/render-utils/src/LightingModel.cpp
  libraries/render-utils/src/LightingModel.h
  libraries/render-utils/src/LightingModel.slh
  libraries/render-utils/src/RenderDeferredTask.cpp
  libraries/render-utils/src/RenderDeferredTask.h
  libraries/render-utils/src/RenderForwardTask.cpp
  libraries/render/src/render/DrawStatus.cpp
  libraries/render/src/render/DrawStatus.h
  libraries/render/src/render/ShapePipeline.cpp
  libraries/render/src/render/ShapePipeline.h
  scripts/developer/utilities/render/antialiasing.qml
  scripts/developer/utilities/render/deferredLighting.qml
Labels: Development Approved, Merge stable -> master

#12935 Android new login
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/assets/privacy_policy.html
  android/app/src/main/cpp/native.cpp
  android/app/src/main/java/io/highfidelity/hifiinterface/GotoActivity.java
  android/app/src/main/java/io/highfidelity/hifiinterface/HifiUtils.java
  android/app/src/main/java/io/highfidelity/hifiinterface/HomeActivity.java
  android/app/src/main/java/io/highfidelity/hifiinterface/InterfaceActivity.java
  android/app/src/main/java/io/highfidelity/hifiinterface/LoginActivity.java
  android/app/src/main/java/io/highfidelity/hifiinterface/MainActivity.java
  android/app/src/main/java/io/highfidelity/hifiinterface/SplashActivity.java
  android/app/src/main/java/io/highfidelity/hifiinterface/fragment/HomeFragment.java
  android/app/src/main/java/io/highfidelity/hifiinterface/fragment/LoginFragment.java
  android/app/src/main/java/io/highfidelity/hifiinterface/fragment/PolicyFragment.java
  android/app/src/main/java/io/highfidelity/hifiinterface/task/DownloadProfileImageTask.java
  android/app/src/main/res/drawable/default_profile_avatar.xml
  android/app/src/main/res/drawable/hifi_logo_header.xml
  android/app/src/main/res/drawable/hifi_logo_splash.xml
  android/app/src/main/res/font/raleway_italic.xml
  android/app/src/main/res/layout/activity_goto.xml
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/layout/activity_splash.xml
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/layout/fragment_login.xml
  android/app/src/main/res/layout/fragment_policy.xml
  android/app/src/main/res/layout/navigation_header.xml
  android/app/src/main/res/menu/menu_home.xml
  android/app/src/main/res/menu/menu_navigation.xml
  android/app/src/main/res/values/dimens.xml
  android/app/src/main/res/values/preloaded_fonts.xml
  android/app/src/main/res/values/strings.xml
  interface/src/AndroidHelper.cpp
  interface/src/AndroidHelper.h
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/Application_jni.cpp
  interface/src/scripting/WindowScriptingInterface.cpp
  interface/src/scripting/WindowScriptingInterface.h
  interface/src/ui/LoginDialog.cpp
  libraries/input-plugins/src/input-plugins/TouchscreenVirtualPadDevice.cpp
  libraries/input-plugins/src/input-plugins/TouchscreenVirtualPadDevice.h
  libraries/ui/src/VirtualPadManager.cpp
  libraries/ui/src/VirtualPadManager.h
  scripts/system/+android/actionbar.js
  scripts/system/+android/audio.js
  scripts/system/+android/modes.js
  unpublishedScripts/marketplace/shapes/modules/createPalette.js
  unpublishedScripts/marketplace/shapes/modules/groups.js
  unpublishedScripts/marketplace/shapes/modules/preload.js
  unpublishedScripts/marketplace/shapes/modules/selection.js
  unpublishedScripts/marketplace/shapes/modules/toolIcon.js
  unpublishedScripts/marketplace/shapes/modules/toolsMenu.js
  unpublishedScripts/marketplace/shapes/shapes.js
Labels: Android, Android Smoke Required, Development Approved, QA Approved :tada:

#13165 JSDoc stubs for various APIs
  assignment-client/src/Agent.h
  assignment-client/src/avatars/ScriptableAvatar.h
  assignment-client/src/entities/EntityTreeHeadlessViewer.h
  assignment-client/src/octree/OctreeHeadlessViewer.h
  interface/src/Bookmarks.h
  interface/src/LocationBookmarks.h
  interface/src/avatar/AvatarManager.h
  interface/src/avatar/MyAvatar.h
  interface/src/raypick/LaserPointerScriptingInterface.h
  interface/src/raypick/PickScriptingInterface.cpp
  interface/src/raypick/PickScriptingInterface.h
  interface/src/raypick/PointerScriptingInterface.cpp
  interface/src/raypick/PointerScriptingInterface.h
  interface/src/raypick/RayPickScriptingInterface.h
  interface/src/scripting/Audio.h
  interface/src/scripting/WalletScriptingInterface.h
  interface/src/scripting/WindowScriptingInterface.h
  interface/src/ui/Snapshot.h
  interface/src/ui/Stats.h
  libraries/audio/src/AudioEffectOptions.cpp
  libraries/audio/src/AudioEffectOptions.h
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
  libraries/avatars/src/AvatarHashMap.h
  libraries/graphics-scripting/src/graphics-scripting/Forward.h
  libraries/graphics-scripting/src/graphics-scripting/GraphicsScriptingInterface.cpp
  libraries/graphics-scripting/src/graphics-scripting/GraphicsScriptingInterface.h
  libraries/graphics-scripting/src/graphics-scripting/ScriptableMesh.h
  libraries/graphics-scripting/src/graphics-scripting/ScriptableMeshPart.h
  libraries/graphics-scripting/src/graphics-scripting/ScriptableModel.h
  libraries/graphics/src/graphics/Geometry.h
  libraries/midi/src/Midi.h
  libraries/networking/src/AddressManager.h
  libraries/networking/src/ResourceCache.h
  libraries/networking/src/ResourceScriptingInterface.h
  libraries/networking/src/ThreadedAssignment.h
  libraries/plugins/src/plugins/SteamClientPlugin.h
  libraries/pointers/src/Pick.h
  libraries/script-engine/src/FileScriptingInterface.h
  libraries/script-engine/src/Mat4.h
  libraries/shared/src/RegisteredMetaTypes.cpp
  libraries/task/src/task/Config.h
  libraries/ui/src/OffscreenUi.cpp
  libraries/ui/src/QmlWebWindowClass.h
  libraries/ui/src/QmlWindowClass.cpp
  libraries/ui/src/QmlWindowClass.h
  libraries/ui/src/ui/TabletScriptingInterface.h
  libraries/ui/src/ui/ToolbarScriptingInterface.h
  tools/jsdoc/plugins/hifi.js
Labels: Content/Create, Development Approved, JSDocs, QA Approved :tada:

#13151 eslint config update [ skip builds ]
  .eslintrc.js
Labels: Development Approved, Feedback Welcome

#13096 Faster texture transfers
  interface/resources/qml/Stats.qml
  interface/src/ui/Stats.cpp
  interface/src/ui/Stats.h
  libraries/gpu-gl-common/src/gpu/gl/GLBackend.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLBackend.h
  libraries/gpu-gl-common/src/gpu/gl/GLShared.h
  libraries/gpu-gl-common/src/gpu/gl/GLTexture.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLTexture.h
  libraries/gpu-gl-common/src/gpu/gl/GLTextureTransfer.cpp
  libraries/gpu-gl/src/gpu/gl41/GL41Backend.h
  libraries/gpu-gl/src/gpu/gl41/GL41BackendTexture.cpp
  libraries/gpu-gl/src/gpu/gl45/GL45Backend.h
  libraries/gpu-gl/src/gpu/gl45/GL45BackendTexture.cpp
  libraries/gpu-gl/src/gpu/gl45/GL45BackendVariableTexture.cpp
  libraries/gpu-gles/src/gpu/gles/GLESBackend.h
  libraries/gpu-gles/src/gpu/gles/GLESBackendTexture.cpp
  libraries/gpu/src/gpu/Context.cpp
  libraries/gpu/src/gpu/Context.h
  tests/gpu/src/TextureTest.cpp
  tests/gpu/src/TextureTest.h
Labels: Android, Development Approved, Engine, Mac Required, QA Approved :tada:

#13198 Updated auto-tester.
  tools/auto-tester/src/Test.cpp
  tools/auto-tester/src/Test.h
Labels: Development Approved, Engine, QA Approved :tada:

#13199 workload: distributed physics: downgrade simulation ownership priority when releasing grab
  interface/src/AvatarBookmarks.cpp
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityScriptingInterface.cpp
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/SimulationOwner.cpp
  libraries/entities/src/SimulationOwner.h
  libraries/physics/src/EntityMotionState.cpp
  libraries/physics/src/EntityMotionState.h
Labels: Development Approved, Engine, QA Approved :tada:

#13200 Fix isHazeEnabled() checks with 0.0 to fix GLES compiler error
  libraries/render-utils/src/DeferredGlobalLight.slh
  libraries/render-utils/src/Haze.slf
Labels: Android, Development Approved, Engine, QA Approved :tada:

#13201 Fix Flickery Procedural Shader
  libraries/procedural/src/procedural/Procedural.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#13085 Fix intermittent ability to select particle and light entities
  scripts/system/controllers/controllerModules/inEditMode.js
  scripts/system/edit.js
  scripts/system/libraries/entityIconOverlayManager.js
  scripts/system/libraries/entitySelectionTool.js
Labels: Content/Create, Development Approved, QA Approved :tada:

#13093 moved checkEditPermissionsAndUpdate function to higher scope
  scripts/system/edit.js
Labels: Content/Create, Development Approved, QA Approved :tada:

#13197 Add "Your Last Location" to Android Home
  android/app/src/main/cpp/native.cpp
  android/app/src/main/java/io/highfidelity/hifiinterface/fragment/HomeFragment.java
  android/app/src/main/java/io/highfidelity/hifiinterface/view/DomainAdapter.java
  android/app/src/main/res/drawable/domain_placeholder.png
  android/app/src/main/res/values/strings.xml
  interface/src/Application.cpp
Labels: Android, Android Smoke Required, Development Approved, QA Approved :tada:

#13204 Protect against null hudTexture
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.cpp
  libraries/display-plugins/src/display-plugins/hmd/HmdDisplayPlugin.cpp
Labels: Android, Android Smoke Required, Development Approved, Engine, QA Approved :tada:

#12906 WorkList #21794: Modify inspect.js to work with Avatars as well as entities
  scripts/system/inspect.js
Labels: Client, Development Approved, outsource

#13164 Move down OctreeQueryNode::_viewMutex to OctreeQuery
  libraries/octree/src/OctreeQuery.cpp
  libraries/octree/src/OctreeQuery.h
  libraries/octree/src/OctreeQueryNode.cpp
  libraries/octree/src/OctreeQueryNode.h
Labels: Development Approved, QA Approved :tada:, Server & Network

#13202 Fix logspam from texture transfer code
  libraries/gpu-gl-common/src/gpu/gl/GLTextureTransfer.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#13192 fix case sensitive comparison in AddressManager::setHost
  libraries/networking/src/AddressManager.cpp
Labels: Client, Development Approved, QA Approved :tada:, Server & Network

#13183 Filter domains by tag 'mobile' in Search (Android)
  android/app/src/main/java/io/highfidelity/hifiinterface/provider/UserStoryDomainProvider.java
Labels: Android, Android Smoke Required, Development Approved, Engine, QA Approved :tada:

#13208 Fixing populated / allocated tracking for textures
  libraries/gpu-gl-common/src/gpu/gl/GLTexture.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLTexture.h
  libraries/gpu-gl-common/src/gpu/gl/GLTextureTransfer.cpp
  libraries/gpu-gl/src/gpu/gl41/GL41BackendTexture.cpp
  libraries/gpu-gl/src/gpu/gl45/GL45BackendVariableTexture.cpp
  libraries/gpu-gles/src/gpu/gles/GLESBackendTexture.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#13127 Incorrectly baked model crashes Interface
  libraries/baking/src/FBXBaker.cpp
  libraries/baking/src/FBXBaker.h
  libraries/baking/src/ModelBaker.cpp
  libraries/fbx/src/FBX.h
  libraries/fbx/src/FBXReader.cpp
  libraries/fbx/src/FBXReader_Node.cpp
  libraries/fbx/src/FBXToJSON.cpp
  libraries/fbx/src/FBXToJSON.h
  libraries/fbx/src/FBXWriter.cpp
Labels: Development Approved, Engine, QA Approved :tada:, bug

#13182 Use pooled gpu batches
  libraries/gpu/src/gpu/Batch.cpp
  libraries/gpu/src/gpu/Batch.h
  libraries/gpu/src/gpu/Context.cpp
  libraries/gpu/src/gpu/Context.h
  libraries/gpu/src/gpu/Forward.h
  libraries/gpu/src/gpu/Frame.cpp
  libraries/gpu/src/gpu/Frame.h
  libraries/render-utils/src/DeferredLightingEffect.cpp
  libraries/render-utils/src/LightClusters.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#13191 More unit testing work
  CMakeLists.txt
  tests/CMakeLists.txt
  tests/QTestExtensions.h
  tests/animation/src/AnimTests.cpp
  tests/shared/src/TransformTests.cpp
Labels: Development Approved

#13179 Server-Managed Cloneables + Cloneable Properties
  assignment-client/src/entities/EntityServer.cpp
  libraries/entities/src/EntityEditPacketSender.cpp
  libraries/entities/src/EntityEditPacketSender.h
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityItemPropertiesDefaults.h
  libraries/entities/src/EntityPropertyFlags.h
  libraries/entities/src/EntityScriptingInterface.cpp
  libraries/entities/src/EntityScriptingInterface.h
  libraries/entities/src/EntitySimulation.cpp
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/EntityTree.h
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
  scripts/system/controllers/controllerModules/equipEntity.js
  scripts/system/controllers/controllerModules/nearActionGrabEntity.js
  scripts/system/controllers/controllerModules/nearParentGrabEntity.js
  scripts/system/html/js/entityProperties.js
  scripts/system/libraries/cloneEntityUtils.js
  scripts/system/libraries/controllerDispatcherUtils.js
Labels: Client, Content/Create, Packet Version Change, QA Approved :tada:, Release Blocker, Server & Network

#13006 Workload: Add more timing intervals for the feedback and regulation of the view
  interface/src/Application.cpp
  interface/src/workload/GameWorkload.cpp
  interface/src/workload/GameWorkload.h
  libraries/workload/src/workload/ViewTask.cpp
  libraries/workload/src/workload/ViewTask.h
Labels: Engine

#13109 upgrade from Bullet-2.83 to Bullet-2.88
  android/build.gradle
  cmake/externals/bullet/CMakeLists.txt
  interface/src/avatar/AvatarMotionState.cpp
  interface/src/avatar/AvatarMotionState.h
  interface/src/avatar/MyAvatar.h
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
  libraries/physics/src/CharacterController.cpp
  libraries/physics/src/CharacterController.h
  libraries/physics/src/CharacterGhostObject.cpp
  libraries/physics/src/CharacterGhostObject.h
  libraries/physics/src/EntityMotionState.cpp
  libraries/physics/src/EntityMotionState.h
  libraries/physics/src/ObjectMotionState.h
  libraries/physics/src/PhysicsEngine.cpp
  libraries/shared/src/PhysicsCollisionGroups.h
  libraries/shared/src/PhysicsHelpers.cpp
  libraries/shared/src/PhysicsHelpers.h
Labels: Android Smoke Required, Development Approved, Engine, Packet Version Change, QA Approved :tada:

#13219 Bringing Evolution to the Job Engine Task library developed in the workload project to master
  interface/src/Application.h
  libraries/render-utils/src/AmbientOcclusionEffect.h
  libraries/render-utils/src/LightClusters.h
  libraries/render-utils/src/SubsurfaceScattering.h
  libraries/render/src/render/Engine.cpp
  libraries/render/src/render/Engine.h
  libraries/render/src/render/Item.h
  libraries/render/src/render/Scene.h
  libraries/task/src/task/Config.h
  libraries/task/src/task/Task.cpp
  libraries/task/src/task/Task.h
  scripts/developer/utilities/lib/jet/jet.js
  scripts/developer/utilities/lib/jet/qml/TaskList.qml
  scripts/developer/utilities/lib/jet/qml/TaskListView.qml
  scripts/developer/utilities/lib/jet/qml/qmldir
  scripts/developer/utilities/render/configSlider/ConfigSlider.qml
  scripts/developer/utilities/render/deferredLighting.qml
  scripts/developer/utilities/render/engineInspector.js
  scripts/developer/utilities/render/engineInspector.qml
  scripts/developer/utilities/render/luci.js
  tests-manual/render-perf/src/main.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#13214 Fix crash in GL45Backend::do_drawIndexedInstanced
  libraries/render-utils/src/GeometryCache.cpp
Labels: Development Approved, Engine, QA Approved :tada:, bug

#13216 never re-use node ID during domain connection
  domain-server/src/DomainGatekeeper.cpp
  domain-server/src/DomainGatekeeper.h
  domain-server/src/DomainServer.cpp
  domain-server/src/DomainServer.h
  domain-server/src/DomainServerNodeData.h
Labels: Development Approved, QA Approved :tada:

#13218 Update serverless tutorial for RC68
  cmake/externals/serverless-content/CMakeLists.txt
Labels: Development Approved, QA Approved :tada:

#13232 Updates to AutoTester
  tools/auto-tester/src/ImageComparer.cpp
  tools/auto-tester/src/Test.cpp
  tools/auto-tester/src/Test.h
  tools/auto-tester/src/ui/AutoTester.cpp
  tools/auto-tester/src/ui/AutoTester.h
  tools/auto-tester/src/ui/AutoTester.ui
Labels: Engine

#13210 Mac: render unsupported BPTC textures as uncompressed
  libraries/gpu-gl/src/gpu/gl41/GL41BackendTexture.cpp
  libraries/gpu-gl/src/gpu/gl45/GL45BackendTexture.cpp
Labels: Android, Android Smoke Required, Development Approved, Engine, Mac Required, QA Approved :tada:, Windows Required

#13206 JSDoc fixes
  interface/src/Application.cpp
  interface/src/FancyCamera.h
  interface/src/avatar/MyAvatar.h
  interface/src/raypick/PickScriptingInterface.h
  interface/src/raypick/PointerScriptingInterface.cpp
  interface/src/scripting/WindowScriptingInterface.cpp
  interface/src/scripting/WindowScriptingInterface.h
  interface/src/ui/overlays/Overlays.h
  libraries/animation/src/AnimationCache.h
  libraries/audio/src/Sound.h
  libraries/audio/src/SoundCache.h
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
  libraries/controllers/src/controllers/Actions.cpp
  libraries/controllers/src/controllers/InputDevice.h
  libraries/controllers/src/controllers/StandardController.cpp
  libraries/entities/src/AnimationPropertyGroup.cpp
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/KeyLightPropertyGroup.h
  libraries/fbx/src/FBX.h
  libraries/input-plugins/src/input-plugins/KeyboardMouseDevice.cpp
  libraries/model-networking/src/model-networking/ModelCache.h
  libraries/model-networking/src/model-networking/TextureCache.h
  libraries/networking/src/AddressManager.h
  libraries/networking/src/DomainHandler.h
  libraries/networking/src/ResourceCache.h
  libraries/script-engine/src/AssetScriptingInterface.h
  libraries/script-engine/src/Quat.h
  libraries/script-engine/src/SceneScriptingInterface.h
  libraries/script-engine/src/ScriptEngine.cpp
  libraries/script-engine/src/ScriptUUID.h
  libraries/script-engine/src/Vec3.h
  libraries/shared/src/shared/Camera.h
  libraries/ui/src/QmlFragmentClass.h
  libraries/ui/src/ui/TabletScriptingInterface.h
  plugins/oculus/src/OculusControllerManager.cpp
  plugins/openvr/src/ViveControllerManager.cpp
  tools/jsdoc/plugins/hifi.js
Labels: Content/Create, Development Approved, JSDocs, QA Approved :tada:

#13233 Merge RC68 back to master
  cmake/externals/serverless-content/CMakeLists.txt
  domain-server/src/DomainGatekeeper.cpp
  domain-server/src/DomainGatekeeper.h
  domain-server/src/DomainServer.cpp
  domain-server/src/DomainServer.h
  domain-server/src/DomainServerNodeData.h
Labels: Development Approved, Merge RC -> master

#13234 Workload: MErge with upstream master and fix conflicts
  android/build.gradle
  cmake/externals/bullet/CMakeLists.txt
  cmake/externals/glm/CMakeLists.txt
  interface/src/Application.h
  interface/src/avatar/AvatarMotionState.cpp
  interface/src/avatar/AvatarMotionState.h
  interface/src/avatar/MyAvatar.h
  interface/src/workload/GameWorkload.cpp
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/gpu-gl/src/gpu/gl41/GL41BackendTexture.cpp
  libraries/gpu-gl/src/gpu/gl45/GL45BackendTexture.cpp
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
  libraries/physics/src/CharacterController.cpp
  libraries/physics/src/CharacterController.h
  libraries/physics/src/CharacterGhostObject.cpp
  libraries/physics/src/CharacterGhostObject.h
  libraries/physics/src/EntityMotionState.cpp
  libraries/physics/src/EntityMotionState.h
  libraries/physics/src/ObjectMotionState.h
  libraries/physics/src/PhysicsEngine.cpp
  libraries/render-utils/src/AmbientOcclusionEffect.h
  libraries/render-utils/src/GeometryCache.cpp
  libraries/render-utils/src/LightClusters.h
  libraries/render/src/render/Engine.cpp
  libraries/render/src/render/Engine.h
  libraries/render/src/render/Scene.h
  libraries/shared/src/PhysicsCollisionGroups.h
  libraries/shared/src/PhysicsHelpers.cpp
  libraries/shared/src/PhysicsHelpers.h
  libraries/task/src/task/Config.h
  libraries/task/src/task/Task.cpp
  libraries/task/src/task/Task.h
  libraries/workload/src/workload/Engine.cpp
  libraries/workload/src/workload/Engine.h
  libraries/workload/src/workload/ViewTask.cpp
  scripts/developer/utilities/lib/jet/jet.js
  scripts/developer/utilities/lib/jet/qml/TaskList.qml
  scripts/developer/utilities/lib/jet/qml/TaskListView.qml
  scripts/developer/utilities/lib/jet/qml/qmldir
  scripts/developer/utilities/render/deferredLighting.qml
  scripts/developer/utilities/render/engineInspector.js
  scripts/developer/utilities/render/engineInspector.qml
  scripts/developer/utilities/render/luci.js
  tests-manual/render-perf/src/main.cpp
  tools/auto-tester/src/ImageComparer.cpp
  tools/auto-tester/src/Test.cpp
  tools/auto-tester/src/Test.h
  tools/auto-tester/src/ui/AutoTester.cpp
  tools/auto-tester/src/ui/AutoTester.h
  tools/auto-tester/src/ui/AutoTester.ui
Labels: Development Approved, Engine

#13222 Fix image and text overlay drifting
  interface/src/ui/overlays/Billboard3DOverlay.cpp
  interface/src/ui/overlays/Billboard3DOverlay.h
  interface/src/ui/overlays/Image3DOverlay.cpp
  interface/src/ui/overlays/Text3DOverlay.cpp
  interface/src/ui/overlays/Text3DOverlay.h
Labels: Development Approved, Engine, QA Approved :tada:, bug

#13205 Minor fix allows import glTF from Substance Painter
  libraries/fbx/src/GLTFReader.cpp
  libraries/fbx/src/GLTFReader.h
Labels: Development Approved, Engine, QA Approved :tada:

#13235 Remove offscreenUi desktop qml object from being a contextProperty for Web3DOverlay
  interface/src/ui/overlays/Web3DOverlay.cpp
Labels: Client, Critical Fix, Development Approved, QA Approved :tada:

#13220 Correct `Camera.mode` command.
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/avatar/MyAvatar.cpp
Labels: Client, Development Approved, Engine, QA Approved :tada:, Scripting API change, bug

#13236 Remove offscreenUi desktop qml object from being a contextProperty for Web3DOverlay (RC68)
  interface/src/ui/overlays/Web3DOverlay.cpp
Labels: Client, Critical Fix, Development Approved, QA Approved :tada:

#13239 Adding fix for enabling saved front/back advanced controls. (RC68)
  scripts/system/controllers/toggleAdvancedMovementForHandControllers.js
Labels: Client, Critical Fix, Development Approved, QA Approved :tada:

#13211 Fixing Log in/Sign up dialog is missing "Forgot Username?" and "Forgot Password"
  interface/resources/qml/controls-uit/TextField.qml
Labels: Client, Development Approved, QA Approved :tada:

#12946 minor cleanup in physics simulation
  libraries/physics/src/EntityMotionState.cpp
  libraries/physics/src/ObjectMotionState.h
  libraries/physics/src/PhysicsEngine.cpp
  libraries/physics/src/PhysicsEngine.h
  libraries/physics/src/ThreadSafeDynamicsWorld.cpp
  libraries/physics/src/ThreadSafeDynamicsWorld.h
Labels: Development Approved, Engine, QA Approved :tada:

#13248 add split wireshark dissectors for avatar/entity protocols
  tools/dissectors/hf-avatar.lua
  tools/dissectors/hf-entity.lua
  tools/dissectors/hfudt.lua
  tools/hfudt.lua
Labels: Development Approved

#13213 Adding showHidden properties to file dialogs to allow for showing hidden files/folders
  interface/resources/qml/dialogs/+android/FileDialog.qml
  interface/resources/qml/dialogs/FileDialog.qml
  interface/resources/qml/dialogs/TabletFileDialog.qml
  interface/resources/qml/hifi/tablet/tabletWindows/TabletFileDialog.qml
Labels: Client, Development Approved, QA Approved :tada:

#13242 Sign release apk. Remove daydream intent from manifest
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
Labels: Android, Development Approved, QA Approved :tada:

#13249 Android: Update Application.cpp
  interface/src/Application.cpp
  libraries/script-engine/src/ScriptEngine.cpp
  libraries/script-engine/src/ScriptEngine.h
  scripts/+android/defaultScripts.js
  scripts/system/+android/stats.js
Labels: Android, Development Approved, QA Approved :tada:

#13226 workload: disable regulation of workload regions by default
  interface/src/workload/GameWorkload.h
  libraries/workload/src/workload/View.h
  libraries/workload/src/workload/ViewTask.cpp
  libraries/workload/src/workload/ViewTask.h
Labels: DO NOT MERGE, Engine

#13261 RC68: Android signing and remove audiobar
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  interface/src/Application.cpp
  libraries/script-engine/src/ScriptEngine.cpp
  libraries/script-engine/src/ScriptEngine.h
  scripts/+android/defaultScripts.js
  scripts/system/+android/stats.js
Labels: Android, Development Approved, QA Approved :tada:

#13215 activate RigidBody when removing physics Action
  libraries/physics/src/ObjectDynamic.cpp
  libraries/physics/src/ObjectDynamic.h
Labels: Development Approved, Engine, QA Approved :tada:

#13262 adding back notifcations to default scripts
  scripts/defaultScripts.js
  scripts/system/notifications.js
Labels: Client, Development Approved, QA Approved :tada:

#12649 Fix addressing the avatar mesh visibility switch bug
  interface/src/avatar/AvatarManager.cpp
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  interface/src/ui/overlays/ModelOverlay.cpp
  interface/src/ui/overlays/Overlay.h
  interface/src/ui/overlays/OverlaysPayload.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
  libraries/avatars-renderer/src/avatars-renderer/SkeletonModel.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/render-utils/src/CauterizedModel.cpp
  libraries/render-utils/src/MeshPartPayload.cpp
  libraries/render-utils/src/MeshPartPayload.h
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
  libraries/render-utils/src/RenderDeferredTask.cpp
  libraries/render-utils/src/RenderForwardTask.cpp
  libraries/render-utils/src/RenderHifi.h
  libraries/render/src/render/CullTask.cpp
  libraries/render/src/render/Item.cpp
  libraries/render/src/render/Item.h
  libraries/shared/src/shared/QtHelpers.h
Labels: Development Approved, Engine, QA Approved :tada:, bug

#13188 Initialize Qt's use of openssl lib before calling RSA code
  libraries/networking/src/AccountManager.cpp
  libraries/networking/src/AccountManager.h
  libraries/networking/src/RSAKeypairGenerator.cpp
  libraries/networking/src/RSAKeypairGenerator.h
Labels: Development Approved, QA Approved :tada:, Server & Network

#13277 RC68: Fix joystick and view control bug that makes it bounce
  libraries/input-plugins/src/input-plugins/TouchscreenVirtualPadDevice.cpp
Labels: Android, Development Approved, Engine, QA Approved :tada:

#13274 workload: fix bug preventing bids for simulation ownership
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/physics/src/CharacterGhostObject.cpp
  libraries/physics/src/EntityMotionState.cpp
  libraries/physics/src/EntityMotionState.h
  libraries/physics/src/PhysicalEntitySimulation.cpp
  libraries/workload/src/workload/Space.cpp
  libraries/workload/src/workload/Transaction.h
Labels: Development Approved, Engine

#13247 Daily tests
  interface/src/scripting/TestScriptingInterface.cpp
  interface/src/scripting/TestScriptingInterface.h
  tools/auto-tester/src/ImageComparer.cpp
  tools/auto-tester/src/Test.cpp
  tools/auto-tester/src/ui/AutoTester.cpp
  tools/auto-tester/src/ui/AutoTester.h
  tools/auto-tester/src/ui/AutoTester.ui
Labels: Development Approved, Engine, QA Approved :tada:, Scripting API change
