Repository highfidelity/hifi, pull requests merged in 2018-11, with the labels that each got.

#14270 Extra joints on soft entities keep their local transform
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
Labels: Avatar, Development Approved, Project Approved, QA Approved :tada:

#14318 Fix default collision values RC75
  scripts/system/edit.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#14324 Fix new models not obeying dynamic checkbox
  scripts/system/edit.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#14317 Move Wallet Security tab to new dialog; fixup Login dialog
  interface/resources/qml/LoginDialog/LinkAccountBody.qml
  interface/resources/qml/hifi/commerce/common/CommerceLightbox.qml
  interface/resources/qml/hifi/commerce/wallet/Help.qml
  interface/resources/qml/hifi/commerce/wallet/Security.qml
  interface/resources/qml/hifi/commerce/wallet/Wallet.qml
  interface/resources/qml/hifi/commerce/wallet/WalletSetup.qml
  interface/resources/qml/hifi/dialogs/security/Security.qml
  interface/resources/qml/hifi/dialogs/security/SecurityImageChange.qml
  interface/resources/qml/hifi/dialogs/security/SecurityImageModel.qml
  interface/resources/qml/hifi/dialogs/security/SecurityImageSelection.qml
  interface/resources/qml/hifi/dialogs/security/images/01.jpg
  interface/resources/qml/hifi/dialogs/security/images/02.jpg
  interface/resources/qml/hifi/dialogs/security/images/03.jpg
  interface/resources/qml/hifi/dialogs/security/images/04.jpg
  interface/resources/qml/hifi/dialogs/security/images/05.jpg
  interface/resources/qml/hifi/dialogs/security/images/06.jpg
  interface/resources/qml/hifi/dialogs/security/images/07.jpg
  interface/resources/qml/hifi/dialogs/security/images/08.jpg
  interface/resources/qml/hifi/dialogs/security/images/09.jpg
  interface/resources/qml/hifi/dialogs/security/images/10.jpg
  interface/resources/qml/hifi/dialogs/security/images/11.jpg
  interface/resources/qml/hifi/dialogs/security/images/12.jpg
  interface/resources/qml/hifi/dialogs/security/images/13.jpg
  interface/resources/qml/hifi/dialogs/security/images/14.jpg
  interface/resources/qml/hifi/dialogs/security/images/15.jpg
  interface/resources/qml/hifi/dialogs/security/images/16.jpg
  interface/resources/qml/hifi/dialogs/security/images/17.jpg
  interface/resources/qml/hifi/dialogs/security/images/18.jpg
  interface/resources/qml/hifi/dialogs/security/images/19.jpg
  interface/resources/qml/hifi/dialogs/security/images/20.jpg
  interface/resources/qml/hifi/dialogs/security/images/21.jpg
  interface/resources/qml/hifi/dialogs/security/images/22.jpg
  interface/resources/qml/hifi/dialogs/security/images/23.jpg
  interface/resources/qml/hifi/dialogs/security/images/24.jpg
  interface/resources/qml/hifi/dialogs/security/images/25.jpg
  interface/resources/qml/hifi/dialogs/security/images/26.jpg
  interface/resources/qml/hifi/dialogs/security/images/27.jpg
  interface/resources/qml/hifi/dialogs/security/images/28.jpg
  interface/resources/qml/hifi/dialogs/security/images/29.jpg
  interface/resources/qml/hifi/dialogs/security/images/30.jpg
  interface/resources/qml/hifi/dialogs/security/images/31.jpg
  interface/resources/qml/hifi/dialogs/security/images/32.jpg
  interface/resources/qml/hifi/dialogs/security/images/33.jpg
  interface/resources/qml/hifi/dialogs/security/images/34.jpg
  interface/src/Application.cpp
  interface/src/Menu.cpp
  interface/src/commerce/Wallet.cpp
  scripts/system/commerce/wallet.js
Labels: Client, Commerce, Project Approved, QA Approved :tada:

#14327 Case 18794 - updates were being reported as gifts in the wallet
  interface/src/commerce/Ledger.cpp
Labels: Commerce, Project Approved, QA Ready

#14308 (case 19302) Re-name FBXGeometry to HFMGeometry and do the same for related classes
  assignment-client/src/avatars/ScriptableAvatar.cpp
  interface/src/ModelPackager.cpp
  interface/src/ModelPackager.h
  interface/src/ModelPropertiesDialog.cpp
  interface/src/ModelPropertiesDialog.h
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MySkeletonModel.cpp
  interface/src/raypick/CollisionPick.cpp
  interface/src/ui/overlays/ModelOverlay.cpp
  libraries/animation/src/AnimClip.cpp
  libraries/animation/src/AnimSkeleton.cpp
  libraries/animation/src/AnimSkeleton.h
  libraries/animation/src/AnimationCache.cpp
  libraries/animation/src/AnimationCache.h
  libraries/animation/src/AnimationObject.cpp
  libraries/animation/src/AnimationObject.h
  libraries/animation/src/Rig.cpp
  libraries/animation/src/Rig.h
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/SkeletonModel.cpp
  libraries/avatars-renderer/src/avatars-renderer/SkeletonModel.h
  libraries/baking/src/FBXBaker.cpp
  libraries/baking/src/FBXBaker.h
  libraries/baking/src/ModelBaker.cpp
  libraries/baking/src/ModelBaker.h
  libraries/baking/src/OBJBaker.cpp
  libraries/baking/src/OBJBaker.h
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/fbx/src/FBX.h
  libraries/fbx/src/FBXReader.cpp
  libraries/fbx/src/FBXReader.h
  libraries/fbx/src/FBXReader_Material.cpp
  libraries/fbx/src/FBXReader_Mesh.cpp
  libraries/fbx/src/GLTFReader.cpp
  libraries/fbx/src/GLTFReader.h
  libraries/fbx/src/OBJReader.cpp
  libraries/fbx/src/OBJReader.h
  libraries/model-networking/src/model-networking/ModelCache.cpp
  libraries/model-networking/src/model-networking/ModelCache.h
  libraries/render-utils/src/CauterizedModel.cpp
  libraries/render-utils/src/MeshPartPayload.cpp
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
  libraries/render-utils/src/SoftAttachmentModel.cpp
  tests-manual/gpu/src/TestFbx.cpp
  tests-manual/gpu/src/TestFbx.h
  tests/animation/src/AnimInverseKinematicsTests.cpp
  tools/skeleton-dump/src/SkeletonDumpApp.cpp
  tools/vhacd-util/src/VHACDUtil.cpp
  tools/vhacd-util/src/VHACDUtil.h
  tools/vhacd-util/src/VHACDUtilApp.cpp
  tools/vhacd-util/src/VHACDUtilApp.h
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14335 Fix horizontal and vertical props in entity properties being swapped
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#14332 Case 19394 for 0.75.0: always keep a workload view around MyAvatar
  libraries/workload/src/workload/ViewTask.cpp
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14345 FB17381 - Reticle.setVisible isn't working (for rc75)
  scripts/system/controllers/controllerModules/mouseHMD.js
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14338 (case 19302) Rename HFMGeometry to HFMModel and adjust related variables
  assignment-client/src/avatars/ScriptableAvatar.cpp
  interface/src/ModelPackager.cpp
  interface/src/ModelPackager.h
  interface/src/ModelPropertiesDialog.cpp
  interface/src/ModelPropertiesDialog.h
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MySkeletonModel.cpp
  interface/src/raypick/CollisionPick.cpp
  interface/src/ui/overlays/ModelOverlay.cpp
  libraries/animation/src/AnimClip.cpp
  libraries/animation/src/AnimSkeleton.cpp
  libraries/animation/src/AnimSkeleton.h
  libraries/animation/src/AnimationCache.cpp
  libraries/animation/src/AnimationCache.h
  libraries/animation/src/Rig.cpp
  libraries/animation/src/Rig.h
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/SkeletonModel.cpp
  libraries/avatars-renderer/src/avatars-renderer/SkeletonModel.h
  libraries/baking/src/FBXBaker.cpp
  libraries/baking/src/FBXBaker.h
  libraries/baking/src/OBJBaker.cpp
  libraries/baking/src/OBJBaker.h
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/fbx/src/FBX.h
  libraries/fbx/src/FBXReader.cpp
  libraries/fbx/src/FBXReader.h
  libraries/fbx/src/GLTFReader.cpp
  libraries/fbx/src/GLTFReader.h
  libraries/fbx/src/OBJReader.cpp
  libraries/fbx/src/OBJReader.h
  libraries/model-networking/src/model-networking/ModelCache.cpp
  libraries/model-networking/src/model-networking/ModelCache.h
  libraries/render-utils/src/CauterizedModel.cpp
  libraries/render-utils/src/MeshPartPayload.cpp
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
  libraries/render-utils/src/SoftAttachmentModel.cpp
  tests-manual/gpu/src/TestFbx.cpp
  tests-manual/gpu/src/TestFbx.h
  tests/animation/src/AnimInverseKinematicsTests.cpp
  tools/skeleton-dump/src/SkeletonDumpApp.cpp
  tools/vhacd-util/src/VHACDUtil.cpp
  tools/vhacd-util/src/VHACDUtil.h
  tools/vhacd-util/src/VHACDUtilApp.cpp
  tools/vhacd-util/src/VHACDUtilApp.h
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14261 Oculus store commerce
  interface/resources/qml/LoginDialog/LinkAccountBody.qml
  interface/resources/qml/controls-uit/FilterBar.qml
  interface/resources/qml/hifi/avatarapp/MessageBoxes.qml
  interface/resources/qml/hifi/commerce/checkout/Checkout.qml
  interface/resources/qml/hifi/commerce/common/EmulatedMarketplaceHeader.qml
  interface/resources/qml/hifi/commerce/common/FirstUseTutorial.qml
  interface/resources/qml/hifi/commerce/common/sendAsset/SendAsset.qml
  interface/resources/qml/hifi/commerce/inspectionCertificate/InspectionCertificate.qml
  interface/resources/qml/hifi/commerce/purchases/PurchasedItem.qml
  interface/resources/qml/hifi/commerce/purchases/Purchases.qml
  interface/resources/qml/hifi/commerce/wallet/Help.qml
  interface/resources/qml/hifi/commerce/wallet/NeedsLogIn.qml
  interface/resources/qml/hifi/commerce/wallet/Wallet.qml
  interface/resources/qml/hifi/commerce/wallet/WalletHome.qml
  interface/resources/qml/hifi/dialogs/security/Security.qml
  interface/src/Application.cpp
  interface/src/commerce/Ledger.cpp
  interface/src/scripting/WalletScriptingInterface.cpp
  interface/src/scripting/WalletScriptingInterface.h
  interface/src/ui/overlays/ContextOverlayInterface.cpp
  interface/src/ui/overlays/Web3DOverlay.cpp
  libraries/networking/src/AccountManager.cpp
  libraries/networking/src/AccountManager.h
  libraries/ui/src/ui/types/RequestFilters.cpp
  scripts/modules/appUi.js
  scripts/modules/request.js
  scripts/system/avatarapp.js
  scripts/system/commerce/wallet.js
  scripts/system/html/js/marketplacesInject.js
  scripts/system/marketplaces/marketplaces.js
  scripts/system/notifications.js
  scripts/system/pal.js
  scripts/system/tablet-goto.js
Labels: Commerce, Project Approved, QA Approved :tada:

#14299 Don't attempt purchase of sold out items
  scripts/system/html/js/marketplacesInject.js
Labels: Commerce, Development Approved, Project Approved, QA Approved :tada:, bug

#14319 Remove tabs from oculus store inventory, and rename to match
  interface/resources/icons/tablet-icons/inventory-a-msg.svg
  interface/resources/icons/tablet-icons/inventory-a.svg
  interface/resources/icons/tablet-icons/inventory-i-msg.svg
  interface/resources/icons/tablet-icons/inventory-i.svg
  interface/resources/icons/tablet-icons/wallet-a-msg.svg
  interface/resources/icons/tablet-icons/wallet-a.svg
  interface/resources/icons/tablet-icons/wallet-i-msg.svg
  interface/resources/icons/tablet-icons/wallet-i.svg
  interface/resources/qml/hifi/commerce/purchases/Purchases.qml
  interface/resources/qml/hifi/commerce/wallet/Wallet.qml
  interface/resources/qml/hifi/commerce/wallet/images/items-tab-a.svg
  scripts/system/commerce/wallet.js
Labels: Commerce, Development Approved, Project Approved, QA Approved :tada:

#14355 RC75: Fix ResourceCache mutex issues
  libraries/networking/src/ResourceCache.cpp
  libraries/networking/src/ResourceCache.h
Labels: Critical Fix, Development Approved, Engine, Project Approved, QA Approved :tada:

#14354 Case 19735: Fix ResourceCache mutex issues
  libraries/networking/src/ResourceCache.cpp
  libraries/networking/src/ResourceCache.h
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14313 Case 19686: Possibly fix mac debug deferred issue
  libraries/gpu/src/gpu/MipGeneration.slh
  libraries/render-utils/src/debug_deferred_buffer.slf
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14311 Case 19682: Disable interstitial on android
  libraries/networking/src/DomainHandler.h
Labels: Android, Development Approved, Engine, Project Approved, QA Approved :tada:

#14301 case 19636 - Make path to VCPKG relative to ENV variable
  tools/auto-tester/CMakeLists.txt
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14227 FB19396 - QML warning qrc:///qml/hifi/tablet/WindowRoot.qml:132: Type…
  interface/resources/qml/hifi/tablet/WindowRoot.qml
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14360 Fix MS19743: Fix case where user couldn't update certain items
  interface/resources/qml/hifi/commerce/checkout/Checkout.qml
  interface/resources/qml/hifi/commerce/wallet/WalletHome.qml
  interface/src/commerce/Ledger.cpp
  interface/src/commerce/Ledger.h
  interface/src/commerce/QmlCommerce.cpp
  interface/src/commerce/QmlCommerce.h
Labels: Commerce, Development Approved, QA Approved :tada:, bug

#14254 Case 19140: Clean up Luci ui to aggregate more tools
  libraries/render/src/render/CullTask.cpp
  scripts/developer/utilities/render/deferredLighting.qml
  scripts/developer/utilities/render/luci.js
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14346 Case 19654: fix crash in btCollisionWorld::updateSingleAabb()
  libraries/physics/src/ObjectMotionState.cpp
  libraries/physics/src/PhysicsEngine.cpp
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14320 Update the default edit.js collidesWith to include myAvatar
  scripts/system/edit.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#14255 Text to Speech App
  assignment-client/src/Agent.cpp
  interface/resources/qml/hifi/tts/TTS.qml
  interface/src/Application.cpp
  interface/src/assets/ATPAssetMigrator.cpp
  interface/src/scripting/TTSScriptingInterface.cpp
  interface/src/scripting/TTSScriptingInterface.h
  libraries/entities-renderer/src/RenderableWebEntityItem.cpp
  libraries/entities/src/EntityEditFilters.cpp
  libraries/model-networking/src/model-networking/TextureCache.cpp
  libraries/networking/src/AddressManager.cpp
  libraries/networking/src/DomainHandler.cpp
  libraries/networking/src/NetworkingConstants.h
  libraries/networking/src/ResourceCache.cpp
  libraries/networking/src/ResourceManager.cpp
Labels: Discovery, Project Approved, QA Approved :tada:

#14310 Create APP tooltip / Adressed CR comments / Regression
  scripts/system/assets/data/createAppTooltips.json
  scripts/system/edit.js
  scripts/system/html/css/edit-style.css
  scripts/system/html/js/createAppTooltip.js
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, HMD required, Project Approved, QA Approved :tada:

#14325 Fix new models not obeying dynamic checkbox
  scripts/system/edit.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#14350 [RC75] Bug fix for head trackers in desktop mode
  interface/resources/qml/AnimStats.qml
  interface/src/Application.cpp
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  interface/src/ui/AnimStats.cpp
  interface/src/ui/AnimStats.h
  plugins/openvr/src/ViveControllerManager.cpp
  plugins/openvr/src/ViveControllerManager.h
Labels: Avatar, Development Approved, Project Approved, QA Approved :tada:

#14370 case 19562: GLES - Use TBO instead of SSBO and make shaders use it when it is not gl45 (v0.75.0-rc)
  interface/src/Application.cpp
  libraries/gpu-gl/src/gpu/gl41/GL41BackendShader.cpp
  libraries/gpu-gles/src/gpu/gles/GLESBackend.h
  libraries/gpu-gles/src/gpu/gles/GLESBackendBuffer.cpp
  libraries/gpu/src/gpu/ShaderConstants.h
  libraries/render-utils/src/Blendshape.slh
  libraries/render-utils/src/Highlight_aabox.slv
  libraries/render-utils/src/MeshPartPayload.cpp
  libraries/render-utils/src/WorkloadResource.slh
  libraries/render/src/render/drawItemBounds.slv
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:, bug

#14237 case 18450: Do not show login dialog if requested not to on the command line.
  interface/src/Application.cpp
  tools/auto-tester/src/TestRunner.cpp
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14356 [v0.75.0] Add audio soloing feature
  assignment-client/src/audio/AudioMixer.cpp
  assignment-client/src/audio/AudioMixerClientData.cpp
  assignment-client/src/audio/AudioMixerClientData.h
  assignment-client/src/audio/AudioMixerSlave.cpp
  assignment-client/src/audio/AudioMixerSlave.h
  interface/src/scripting/Audio.h
  libraries/audio-client/src/AudioClient.cpp
  libraries/audio-client/src/AudioClient.h
  libraries/audio/src/AbstractAudioInterface.h
  libraries/audio/src/AudioSolo.cpp
  libraries/audio/src/AudioSolo.h
  libraries/networking/src/udt/PacketHeaders.h
  libraries/script-engine/src/AudioScriptingInterface.h
Labels: Development Approved, Packet Version Change, Project Approved, QA Approved :tada:, Server & Network

#14256 Fix Interface crash importing JSON with duplicate entity IDs in file
  libraries/entities/src/EntityTree.cpp
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#14368 RC75: Fix tablet culling
  interface/src/ui/overlays/Base3DOverlay.cpp
  interface/src/ui/overlays/Base3DOverlay.h
  interface/src/ui/overlays/ModelOverlay.cpp
  interface/src/ui/overlays/Overlay.cpp
  interface/src/ui/overlays/Volume3DOverlay.cpp
  interface/src/ui/overlays/Volume3DOverlay.h
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14367 Case 17284: Fix tablet culling
  interface/src/ui/overlays/Base3DOverlay.cpp
  interface/src/ui/overlays/Base3DOverlay.h
  interface/src/ui/overlays/ModelOverlay.cpp
  interface/src/ui/overlays/Overlay.cpp
  interface/src/ui/overlays/Volume3DOverlay.cpp
  interface/src/ui/overlays/Volume3DOverlay.h
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14334 Interstitial bug fixes
  interface/src/ui/overlays/Image3DOverlay.cpp
  interface/src/ui/overlays/Image3DOverlay.h
  libraries/model-networking/src/model-networking/ModelCache.cpp
  scripts/system/interstitialPage.js
Labels: Client, Development Approved, Project Approved, QA Rejected :sob:

#14328 Case 19373 - Lowering volume on another user in PAL mutes them
  assignment-client/src/audio/AudioMixerClientData.cpp
  assignment-client/src/audio/AudioMixerClientData.h
Labels: Critical Fix, Development Approved, Discovery, Project Approved, QA Approved :tada:, Server & Network, bug

#14336 Fix horizontal and vertical props in entity properties being swapped
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#13059 Updated the license date
  LICENSE
Labels: Development Approved, Project Approved, QA Ready

#14373 fix image entity crash
  libraries/model-networking/src/model-networking/ModelCache.cpp
Labels: Client, Development Approved, Engine, Project Approved, QA Approved :tada:

#14236 Add logging to the windows installer to track install options and install steps
  cmake/templates/NSIS.template.in
Labels: Development Approved, Discovery, Project Approved, QA Approved :tada:

#14305 Case 19495: zero velocities of non-dynamic entities on nearGrab release
  scripts/system/controllers/controllerModules/farParentGrabEntity.js
  scripts/system/controllers/controllerModules/nearParentGrabEntity.js
Labels: Client, Development Approved, Engine, Project Approved, QA Approved :tada:

#14341 only equip an entity to a hand-controller joint if the hand-controllers are in use, else use avatar hand
  scripts/system/controllers/controllerModules/equipEntity.js
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14380 MS19803: Remove extra "as" in Security.qml
  interface/resources/qml/hifi/dialogs/security/Security.qml
Labels: Discovery, Project Approved, QA Ready, bug

#14167 Make material entities to be presented in avatarapp
  interface/resources/qml/hifi/avatarapp/AdjustWearables.qml
  interface/src/avatar/MyAvatar.cpp
  scripts/system/avatarapp.js
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14164 relax 'isWearable' condition to treat entities like 'ghost.json' as …
  interface/src/avatar/MyAvatar.cpp
  scripts/system/avatarapp.js
Labels: Client, Project Approved, QA Approved :tada:

#14381 Actually fix MS19803: Replace missing imports
  interface/resources/qml/hifi/dialogs/security/SecurityImageChange.qml
  interface/resources/qml/hifi/dialogs/security/SecurityImageSelection.qml
Labels: Discovery, Project Approved, QA Approved :tada:, bug

#14376 [CreateApp] Local/World toggle
  scripts/system/assets/data/createAppTooltips.json
  scripts/system/edit.js
  scripts/system/html/css/edit-style.css
  scripts/system/html/css/hifi-style.css
  scripts/system/html/entityList.html
  scripts/system/html/js/entityList.js
  scripts/system/html/js/entityProperties.js
  scripts/system/libraries/entityList.js
  scripts/system/libraries/entitySelectionTool.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#14351 Tweak transit animations
  interface/resources/avatar/animations/teleport.fbx
  interface/resources/avatar/network-animation.json
  interface/src/avatar/AvatarManager.cpp
  libraries/animation/src/Rig.cpp
  libraries/animation/src/Rig.h
  libraries/avatars/src/AvatarData.h
Labels: Avatar, Development Approved, Project Approved, QA Approved :tada:

#14379 case 19562: GLES - Use TBO instead of SSBO and make shaders use it when it is not gl45 (master)
  interface/src/Application.cpp
  libraries/gpu-gl/src/gpu/gl41/GL41BackendShader.cpp
  libraries/gpu-gles/src/gpu/gles/GLESBackend.h
  libraries/gpu-gles/src/gpu/gles/GLESBackendBuffer.cpp
  libraries/gpu/src/gpu/ShaderConstants.h
  libraries/render-utils/src/Blendshape.slh
  libraries/render-utils/src/Highlight_aabox.slv
  libraries/render-utils/src/MeshPartPayload.cpp
  libraries/render-utils/src/WorkloadResource.slh
  libraries/render/src/render/drawItemBounds.slv
Labels: Android, Development Approved, Engine, Project Approved, QA Approved :tada:

#14339 AnimDebugDraw: Prevent multi-threaded access to shared map collection.
  libraries/render-utils/src/AnimDebugDraw.cpp
  libraries/render-utils/src/AnimDebugDraw.h
Labels: Avatar, Beware: Threading/Deadlock, Development Approved, Project Approved, QA Approved :tada:

#14352 [master] Add audio soloing feature
  assignment-client/src/audio/AudioMixer.cpp
  assignment-client/src/audio/AudioMixerClientData.cpp
  assignment-client/src/audio/AudioMixerClientData.h
  assignment-client/src/audio/AudioMixerSlave.cpp
  assignment-client/src/audio/AudioMixerSlave.h
  interface/src/scripting/Audio.h
  libraries/audio-client/src/AudioClient.cpp
  libraries/audio-client/src/AudioClient.h
  libraries/audio/src/AbstractAudioInterface.h
  libraries/audio/src/AudioSolo.cpp
  libraries/audio/src/AudioSolo.h
  libraries/networking/src/udt/PacketHeaders.h
  libraries/script-engine/src/AudioScriptingInterface.h
Labels: Development Approved, Packet Version Change, Project Approved, QA Approved :tada:, Server & Network

#14230 Hand Azimuth improvement
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  interface/src/avatar/MySkeletonModel.cpp
Labels: Avatar, Development Approved, HMD required, Project Approved, QA Approved :tada:, bug

#14252 Enabled AEC by default (bug 19210)
  android/app/src/main/cpp/native.cpp
  android/app/src/main/java/io/highfidelity/hifiinterface/fragment/SettingsFragment.java
  android/app/src/main/res/xml/settings.xml
  interface/src/AndroidHelper.cpp
  interface/src/AndroidHelper.h
  libraries/audio-client/src/AudioClient.cpp
  libraries/audio-client/src/AudioClient.h
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14384 Case19808 - Sys tray need to remove wallet and market --> inventory
  server-console/src/main.js
  server-console/src/modules/hf-notifications.js
Labels: Commerce, Development Approved, Discovery, Project Approved, QA Approved :tada:, bug

#14385 new inventory icons, and align message waiting light in items tab
  interface/resources/icons/tablet-icons/inventory-a-msg.svg
  interface/resources/icons/tablet-icons/inventory-a.svg
  interface/resources/icons/tablet-icons/inventory-i-msg.svg
  interface/resources/icons/tablet-icons/inventory-i.svg
  interface/resources/qml/hifi/commerce/wallet/Wallet.qml
Labels: Commerce, Development Approved, Project Approved, QA Approved :tada:

#14312 Add option to start up at home location
  interface/src/Application.cpp
  interface/src/Menu.cpp
  interface/src/Menu.h
Labels: Client, Project Approved, QA Approved :tada:

#14298 Fix Goto app cards staying highlighted if move off dialog while dragging
  interface/resources/qml/hifi/Card.qml
  interface/resources/qml/hifi/Feed.qml
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14283 Make tablet page indicators clickable to scroll tablet
  interface/resources/qml/hifi/tablet/TabletHome.qml
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14028 Improve keyboard raising logic for web views
  interface/resources/html/raiseAndLowerKeyboard.js
  interface/resources/qml/controls/FlickableWebViewCore.qml
  interface/resources/qml/controls/TabletWebScreen.qml
  interface/resources/qml/controls/TabletWebView.qml
  interface/resources/qml/controls/WebView.qml
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14204 Fixes for collisionless entities
  scripts/system/controllers/controllerDispatcher.js
  scripts/system/controllers/controllerModules/farActionGrabEntity.js
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14363 Send avatar-joint translations at world scale
  libraries/animation/src/Rig.cpp
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
Labels: Avatar, Development Approved, Project Approved, QA Approved :tada:, Server & Network

#14284 Fix interstitial page not displaying at Interface start-up
  interface/src/scripting/WindowScriptingInterface.h
  scripts/defaultScripts.js
  scripts/system/interstitialPage.js
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14272 Update Spacemouse plugin + Proposal to main build
  plugins/hifiSpacemouse/src/SpacemouseManager.cpp
  plugins/hifiSpacemouse/src/SpacemouseProvider.cpp
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14271 Case 19475: Fix various Oculus Store test failures
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/LODManager.cpp
  libraries/display-plugins/src/display-plugins/hmd/HmdDisplayPlugin.h
  libraries/qml/src/qml/OffscreenSurface.cpp
  plugins/oculus/src/OculusBaseDisplayPlugin.cpp
  plugins/oculus/src/OculusBaseDisplayPlugin.h
  plugins/oculus/src/OculusDisplayPlugin.cpp
  plugins/oculus/src/OculusHelpers.cpp
  plugins/oculus/src/OculusHelpers.h
Labels: Development Approved, Engine, Oculus Required, Project Approved, QA Approved :tada:

#14349 Bug fix for head trackers in desktop mode
  interface/resources/qml/AnimStats.qml
  interface/src/Application.cpp
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  interface/src/ui/AnimStats.cpp
  interface/src/ui/AnimStats.h
  plugins/openvr/src/ViveControllerManager.cpp
  plugins/openvr/src/ViveControllerManager.h
Labels: Avatar, Development Approved, Project Approved, QA Approved :tada:

#14362 Add option to enable/disable the mini tablet
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/scripting/HMDScriptingInterface.cpp
  interface/src/scripting/HMDScriptingInterface.h
  interface/src/ui/PreferencesDialog.cpp
  scripts/system/miniTablet.js
Labels: Client, Development Approved, Project Approved, QA Approved :tada:, Scripting API change

#14265 Bug fix for Users unable to Squat
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MySkeletonModel.cpp
  interface/src/ui/PreferencesDialog.cpp
Labels: Avatar, Development Approved, HMD required, Project Approved, QA Approved :tada:, bug

#14282 Change Android login flow (MS case 19470)
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/cpp/native.cpp
  android/app/src/main/java/io/highfidelity/hifiinterface/HifiUtils.java
  android/app/src/main/java/io/highfidelity/hifiinterface/InterfaceActivity.java
  android/app/src/main/java/io/highfidelity/hifiinterface/LoginMenuActivity.java
  android/app/src/main/java/io/highfidelity/hifiinterface/MainActivity.java
  android/app/src/main/java/io/highfidelity/hifiinterface/SplashActivity.java
  android/app/src/main/java/io/highfidelity/hifiinterface/WebViewActivity.java
  android/app/src/main/java/io/highfidelity/hifiinterface/fragment/FriendsFragment.java
  android/app/src/main/java/io/highfidelity/hifiinterface/fragment/LoginFragment.java
  android/app/src/main/java/io/highfidelity/hifiinterface/fragment/OnBackPressedListener.java
  android/app/src/main/java/io/highfidelity/hifiinterface/fragment/SettingsFragment.java
  android/app/src/main/java/io/highfidelity/hifiinterface/fragment/SignedInFragment.java
  android/app/src/main/java/io/highfidelity/hifiinterface/fragment/SignupFragment.java
  android/app/src/main/java/io/highfidelity/hifiinterface/fragment/StartMenuFragment.java
  android/app/src/main/java/io/highfidelity/hifiinterface/fragment/WebViewFragment.java
  android/app/src/main/res/drawable/encourage_login_background.jpg
  android/app/src/main/res/drawable/hifi_header.xml
  android/app/src/main/res/drawable/ic_right_arrow.xml
  android/app/src/main/res/drawable/ic_steam.xml
  android/app/src/main/res/drawable/rounded_button_color1.xml
  android/app/src/main/res/drawable/rounded_button_color3.xml
  android/app/src/main/res/drawable/rounded_button_color4.xml
  android/app/src/main/res/drawable/rounded_edit.xml
  android/app/src/main/res/layout/activity_encourage_login.xml
  android/app/src/main/res/layout/fragment_login.xml
  android/app/src/main/res/layout/fragment_login_menu.xml
  android/app/src/main/res/layout/fragment_signedin.xml
  android/app/src/main/res/layout/fragment_signup.xml
  android/app/src/main/res/values-w385dp/dimens.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/dimens.xml
  android/app/src/main/res/values/strings.xml
  libraries/networking/src/AccountManager.cpp
  libraries/networking/src/AccountManager.h
Labels: Android, Client, Development Approved, Engine, Project Approved, QA Approved :tada:

#14348 (case 19302) Create the HFM library and namespace
  android/app/CMakeLists.txt
  assignment-client/CMakeLists.txt
  interface/CMakeLists.txt
  interface/src/ModelPackager.cpp
  interface/src/ModelPackager.h
  libraries/animation/CMakeLists.txt
  libraries/avatars-renderer/CMakeLists.txt
  libraries/baking/CMakeLists.txt
  libraries/baking/src/ModelBaker.h
  libraries/display-plugins/CMakeLists.txt
  libraries/entities-renderer/CMakeLists.txt
  libraries/entities/CMakeLists.txt
  libraries/fbx/CMakeLists.txt
  libraries/fbx/src/FBX.h
  libraries/fbx/src/FBXReader.cpp
  libraries/fbx/src/FBXReader.h
  libraries/fbx/src/FBXReader_Material.cpp
  libraries/fbx/src/FBXReader_Mesh.cpp
  libraries/fbx/src/FBXReader_Node.cpp
  libraries/fbx/src/GLTFReader.h
  libraries/fbx/src/OBJReader.cpp
  libraries/fbx/src/OBJWriter.cpp
  libraries/hfm/CMakeLists.txt
  libraries/hfm/src/hfm/HFM.cpp
  libraries/hfm/src/hfm/HFM.h
  libraries/hfm/src/hfm/ModelFormatLogging.cpp
  libraries/hfm/src/hfm/ModelFormatLogging.h
  libraries/model-networking/CMakeLists.txt
  libraries/render-utils/CMakeLists.txt
  libraries/script-engine/CMakeLists.txt
  plugins/openvr/CMakeLists.txt
  tests-manual/gpu/CMakeLists.txt
  tests-manual/gpu/src/TestFbx.h
  tests-manual/render-perf/CMakeLists.txt
  tests-manual/render-texture-load/CMakeLists.txt
  tools/oven/CMakeLists.txt
  tools/skeleton-dump/CMakeLists.txt
  tools/vhacd-util/CMakeLists.txt
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14357 Fix mini tablet JavaScript crash
  scripts/system/miniTablet.js
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#12718 Detect if Interface is running on an android testing device
  interface/src/Application.cpp
Labels: Android, Android Smoke Required, Development Approved, Project Approved, QA Approved :tada:

#14321 Case 19256: Switch back to Qt for GL context creation by default
  libraries/gl/src/gl/Context.cpp
  libraries/gl/src/gl/Context.h
  libraries/gl/src/gl/ContextQt.cpp
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14386 Fix entities not loading when Interface doesn't have focus
  interface/src/Application.cpp
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14143 FB18673 - Last line of GOTO desktop notification text cropped off on …
  scripts/system/notifications.js
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14344 FB19348 - Interface doesn't save changes to avatar animation text field
  interface/src/avatar/MyAvatar.cpp
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14377 Update the styling for the Entity Properties window
  scripts/system/edit.js
  scripts/system/html/css/edit-style.css
  scripts/system/html/css/jsoneditor.css
  scripts/system/html/entityProperties.html
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#14343 FB19514 - Interface crashes on attempt to apply new animation url via…
  libraries/networking/src/ResourceCache.cpp
  libraries/networking/src/ResourceCache.h
Labels: Beware: Threading/Deadlock, Client, Development Approved, Project Approved, QA Approved :tada:

#14093 Case 19409, Case 19468: Fading fixes and shader cleanup
  interface/src/avatar/AvatarManager.cpp
  interface/src/avatar/AvatarManager.h
  interface/src/avatar/MyAvatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
  libraries/entities-renderer/src/paintStroke.slf
  libraries/entities-renderer/src/paintStroke_fade.slf
  libraries/fbx/src/OBJReader.cpp
  libraries/gpu/src/gpu/TextureTable.slh
  libraries/graphics/src/graphics/BufferViewHelpers.cpp
  libraries/graphics/src/graphics/Material.cpp
  libraries/graphics/src/graphics/Material.h
  libraries/graphics/src/graphics/Material.slh
  libraries/graphics/src/graphics/MaterialTextures.slh
  libraries/graphics/src/graphics/ShaderConstants.h
  libraries/render-utils/src/DeferredBufferWrite.slh
  libraries/render-utils/src/Fade.slh
  libraries/render-utils/src/GeometryCache.cpp
  libraries/render-utils/src/HighlightEffect.cpp
  libraries/render-utils/src/RenderPipelines.cpp
  libraries/render-utils/src/RenderShadowTask.cpp
  libraries/render-utils/src/deformed_model_dq.slv
  libraries/render-utils/src/forward_model.slf
  libraries/render-utils/src/forward_model_normal_map.slf
  libraries/render-utils/src/forward_model_translucent.slf
  libraries/render-utils/src/forward_model_unlit.slf
  libraries/render-utils/src/model.slf
  libraries/render-utils/src/model_fade.slf
  libraries/render-utils/src/model_lightmap.slf
  libraries/render-utils/src/model_lightmap_fade.slf
  libraries/render-utils/src/model_lightmap_normal_map.slf
  libraries/render-utils/src/model_lightmap_normal_map_fade.slf
  libraries/render-utils/src/model_normal_map.slf
  libraries/render-utils/src/model_normal_map_fade.slf
  libraries/render-utils/src/model_shadow.slf
  libraries/render-utils/src/model_shadow_fade.slf
  libraries/render-utils/src/model_translucent.slf
  libraries/render-utils/src/model_translucent_fade.slf
  libraries/render-utils/src/model_translucent_normal_map.slf
  libraries/render-utils/src/model_translucent_normal_map_fade.slf
  libraries/render-utils/src/model_translucent_unlit.slf
  libraries/render-utils/src/model_translucent_unlit_fade.slf
  libraries/render-utils/src/model_unlit.slf
  libraries/render-utils/src/model_unlit_fade.slf
  libraries/render-utils/src/parabola_translucent.slf
  libraries/render-utils/src/sdf_text3D_transparent.slf
  libraries/render-utils/src/simple.slf
  libraries/render-utils/src/simple_textured_fade.slf
  libraries/render-utils/src/simple_textured_unlit.slf
  libraries/render-utils/src/simple_textured_unlit_fade.slf
  libraries/render-utils/src/simple_transparent_textured.slf
  libraries/render-utils/src/simple_transparent_web_browser.slf
  libraries/render/src/render/Scene.cpp
  libraries/render/src/render/ShapePipeline.cpp
  libraries/render/src/render/ShapePipeline.h
  scripts/developer/utilities/render/debugHighlight.js
Labels: Android Smoke Required, Development Approved, Engine, Project Approved, QA Approved :tada:

#14238 FB19400 during shutdown -- TypeError: Cannot read property 'buttons' …
  interface/resources/qml/hifi/Desktop.qml
  interface/resources/qml/hifi/tablet/TabletHome.qml
  libraries/qml/src/qml/OffscreenSurface.cpp
  libraries/qml/src/qml/impl/SharedObject.cpp
  libraries/qml/src/qml/impl/SharedObject.h
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14369 Entity list - dynamic columns
  scripts/system/html/css/edit-style.css
  scripts/system/html/entityList.html
  scripts/system/html/js/entityList.js
  scripts/system/html/js/listView.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#14389 Add newly-introduced dependency class to Oven
  tools/oven/src/Oven.cpp
Labels: Development Approved, Project Approved, QA Approved :tada:, Server & Network

#14294 Allow for large Models.json file
  domain-server/src/DomainServer.cpp
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/EntityTree.h
  libraries/entities/src/RecurseOctreeToJSONOperator.cpp
  libraries/entities/src/RecurseOctreeToJSONOperator.h
  libraries/octree/src/Octree.cpp
  libraries/octree/src/Octree.h
  libraries/octree/src/OctreeDataUtils.cpp
  libraries/octree/src/OctreeDataUtils.h
  libraries/octree/src/OctreeEntitiesFileParser.cpp
  libraries/octree/src/OctreeEntitiesFileParser.h
  libraries/octree/src/OctreePersistThread.cpp
  libraries/octree/src/OctreePersistThread.h
Labels: Development Approved, Project Approved, QA Approved :tada:, Server & Network

#14337 [CreateApp] make shortcuts work from windows
  interface/resources/qml/controls/FlickableWebViewCore.qml
  interface/resources/qml/controls/WebView.qml
  interface/resources/qml/hifi/tablet/EditEntityList.qml
  interface/resources/qml/hifi/tablet/EditTabView.qml
  interface/resources/qml/hifi/tablet/EditToolsTabView.qml
  interface/resources/qml/hifi/tablet/EntityList.qml
  interface/src/Application.cpp
  scripts/system/edit.js
  scripts/system/html/js/entityList.js
  scripts/system/html/js/entityProperties.js
  scripts/system/html/js/gridControls.js
  scripts/system/libraries/EditEntityList.qml
  scripts/system/libraries/entityList.js
  scripts/system/libraries/gridTool.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#14403 RC75.1 - Add PolyLine/PolyVox to entity list/properties types
  scripts/system/html/js/entityList.js
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, QA Ready, bug

#14404 V0.75.1-RC disable interstitial
  libraries/networking/src/DomainHandler.h
Labels: Client, Project Approved, QA Ready

#14401 revert PR-14238 "TypeError: Cannot read property 'buttons'" until we can adjust it.
  interface/resources/qml/hifi/Desktop.qml
  interface/resources/qml/hifi/tablet/TabletHome.qml
  libraries/qml/src/qml/OffscreenSurface.cpp
  libraries/qml/src/qml/impl/SharedObject.cpp
  libraries/qml/src/qml/impl/SharedObject.h
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14400 Add PolyLine/PolyVox to entity list/properties types
  scripts/system/html/js/entityList.js
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:, bug

#14407 Case 19876: Fix procedurals using the iGlobalTime input
  libraries/procedural/src/procedural/ProceduralCommon.slh
Labels: Development Approved, Development Ready, Engine, Project Approved, QA Approved :tada:

#14408 Case 19876: Fix procedurals using the iGlobalTime input
  libraries/procedural/src/procedural/ProceduralCommon.slh
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14267 FB17479 - Fix scripted key release events for handshakes.
  interface/src/Application.cpp
  interface/src/Application.h
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14395 Fix Goto app clicks not working
  interface/resources/qml/hifi/Card.qml
  interface/resources/qml/hifi/Feed.qml
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14382 Entity properties - new draggable numbers
  scripts/system/html/css/edit-style.css
  scripts/system/html/entityProperties.html
  scripts/system/html/js/draggableNumber.js
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#14128 Improved Ambient Occlusion
  libraries/gpu-gl-common/src/gpu/gl/GLTexelFormat.cpp
  libraries/gpu-gl/src/gpu/gl41/GL41Backend.cpp
  libraries/gpu-gl/src/gpu/gl45/GL45Backend.cpp
  libraries/gpu-gles/src/gpu/gles/GLESBackend.cpp
  libraries/gpu/src/gpu/Batch.cpp
  libraries/gpu/src/gpu/Context.cpp
  libraries/gpu/src/gpu/Context.h
  libraries/render-utils/src/AmbientOcclusionEffect.cpp
  libraries/render-utils/src/AmbientOcclusionEffect.h
  libraries/render-utils/src/DebugDeferredBuffer.cpp
  libraries/render-utils/src/DebugDeferredBuffer.h
  libraries/render-utils/src/DeferredTransform.slh
  libraries/render-utils/src/SurfaceGeometryPass.cpp
  libraries/render-utils/src/SurfaceGeometryPass.h
  libraries/render-utils/src/render-utils/ShaderConstants.h
  libraries/render-utils/src/render-utils/ssao_bilateralBlur.slp
  libraries/render-utils/src/render-utils/ssao_buildNormals.slp
  libraries/render-utils/src/render-utils/ssao_gather.slp
  libraries/render-utils/src/ssao.slh
  libraries/render-utils/src/ssao_bilateralBlur.slf
  libraries/render-utils/src/ssao_bilateralBlur.slv
  libraries/render-utils/src/ssao_buildNormals.slf
  libraries/render-utils/src/ssao_debugOcclusion.slf
  libraries/render-utils/src/ssao_gather.slf
  libraries/render-utils/src/ssao_makeHorizontalBlur.slf
  libraries/render-utils/src/ssao_makeOcclusion.slf
  libraries/render-utils/src/ssao_makeVerticalBlur.slf
  libraries/render-utils/src/ssao_mip_depth.slf
  libraries/render-utils/src/ssao_shared.h
  libraries/render-utils/src/surfaceGeometry_downsampleDepthNormal.slf
  libraries/render/src/render/BlurTask.slh
  libraries/render/src/render/blurGaussianDepthAwareH.slf
  libraries/render/src/render/blurGaussianDepthAwareV.slf
  libraries/render/src/render/blurGaussianH.slf
  libraries/render/src/render/blurGaussianV.slf
  libraries/shaders/headers/310es/header.glsl
  libraries/shared/src/MathUtils.h
  scripts/developer/utilities/render/ambientOcclusionPass.qml
  scripts/developer/utilities/render/debugAmbientOcclusionPass.js
  scripts/developer/utilities/render/deferredLighting.qml
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14411 Fix for avatar flashing on fade out
  libraries/render/src/render/Item.h
  libraries/render/src/render/Scene.cpp
  libraries/render/src/render/Scene.h
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:, bug

#13975 Fix multiple issues on 'Calibration' tab of 'Controls' dialog
  interface/resources/qml/controlsUit/SpinBox.qml
  interface/resources/qml/hifi/tablet/ControllerSettings.qml
  interface/resources/qml/hifi/tablet/OpenVrConfiguration.qml
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14251 FB18302 Remove deprecated Package Model functionality
  interface/src/Menu.cpp
  interface/src/Menu.h
  interface/src/ModelPackager.cpp
  interface/src/ModelPackager.h
  interface/src/ModelPropertiesDialog.cpp
  interface/src/ModelPropertiesDialog.h
  interface/src/ModelSelector.cpp
  interface/src/ModelSelector.h
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14414 security settings post-oculus-store wording
  interface/resources/qml/hifi/dialogs/security/Security.qml
Labels: Commerce, Development Approved, Project Approved, QA Approved :tada:, bug

#14135 FB18573 - Other avatars' avatar entities may appear to be successfull…
  libraries/entities/src/EntityScriptingInterface.cpp
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14273 Case 19722 - Auto-Tester on Mac.
  interface/src/scripting/TestScriptingInterface.cpp
  interface/src/scripting/TestScriptingInterface.h
  tools/CMakeLists.txt
  tools/auto-tester/AppDataHighFidelity/Interface/AccountInfo.bin
  tools/nitpick/AppDataHighFidelity/Interface.json
  tools/nitpick/AppDataHighFidelity/Interface/avatarbookmarks.json
  tools/nitpick/AppDataHighFidelity/assignment-client/entities/models.json.gz
  tools/nitpick/AppDataHighFidelity/domain-server/AccountInfo.bin
  tools/nitpick/AppDataHighFidelity/domain-server/config.json
  tools/nitpick/AppDataHighFidelity/domain-server/entities/models.json.gz
  tools/nitpick/CMakeLists.txt
  tools/nitpick/Create.PNG
  tools/nitpick/Evaluate.PNG
  tools/nitpick/README.md
  tools/nitpick/Run.PNG
  tools/nitpick/TestRailSelector.PNG
  tools/nitpick/Web Interface.PNG
  tools/nitpick/WebInterface.PNG
  tools/nitpick/Windows.PNG
  tools/nitpick/nitpickMismatchExample.PNG
  tools/nitpick/setup_7z.PNG
  tools/nitpick/src/AWSInterface.cpp
  tools/nitpick/src/AWSInterface.h
  tools/nitpick/src/Downloader.cpp
  tools/nitpick/src/Downloader.h
  tools/nitpick/src/ImageComparer.cpp
  tools/nitpick/src/ImageComparer.h
  tools/nitpick/src/PythonInterface.cpp
  tools/nitpick/src/PythonInterface.h
  tools/nitpick/src/Test.cpp
  tools/nitpick/src/Test.h
  tools/nitpick/src/TestRailInterface.cpp
  tools/nitpick/src/TestRailInterface.h
  tools/nitpick/src/TestRunner.cpp
  tools/nitpick/src/TestRunner.h
  tools/nitpick/src/common.h
  tools/nitpick/src/main.cpp
  tools/nitpick/src/ui/BusyWindow.cpp
  tools/nitpick/src/ui/BusyWindow.h
  tools/nitpick/src/ui/BusyWindow.ui
  tools/nitpick/src/ui/HelpWindow.cpp
  tools/nitpick/src/ui/HelpWindow.h
  tools/nitpick/src/ui/HelpWindow.ui
  tools/nitpick/src/ui/MismatchWindow.cpp
  tools/nitpick/src/ui/MismatchWindow.h
  tools/nitpick/src/ui/MismatchWindow.ui
  tools/nitpick/src/ui/Nitpick.cpp
  tools/nitpick/src/ui/Nitpick.h
  tools/nitpick/src/ui/Nitpick.ui
  tools/nitpick/src/ui/TestRailResultsSelectorWindow.cpp
  tools/nitpick/src/ui/TestRailResultsSelectorWindow.h
  tools/nitpick/src/ui/TestRailResultsSelectorWindow.ui
  tools/nitpick/src/ui/TestRailRunSelectorWindow.cpp
  tools/nitpick/src/ui/TestRailRunSelectorWindow.h
  tools/nitpick/src/ui/TestRailRunSelectorWindow.ui
  tools/nitpick/src/ui/TestRailTestCasesSelectorWindow.cpp
  tools/nitpick/src/ui/TestRailTestCasesSelectorWindow.h
  tools/nitpick/src/ui/TestRailTestCasesSelectorWindow.ui
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14413 Entity list - fix resizing
  scripts/system/html/js/entityList.js
  scripts/system/html/js/listView.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:, bug

#14378 Fixing case of interstitial not finishing loading
  interface/resources/qml/hifi/tablet/TabletAddressDialog.qml
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/octree/SafeLanding.cpp
  scripts/system/interstitialPage.js
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14417 add throttle start and backoff to DS settings
  assignment-client/src/audio/AudioMixer.cpp
  assignment-client/src/audio/AudioMixer.h
  domain-server/resources/describe-settings.json
Labels: Development Approved, Project Approved, QA Approved :tada:, Server & Network

#14347 MS19550 - Don't show help for HMDs that aren't plugged in and active
  interface/resources/html/tabletHelp.html
  interface/src/Application.cpp
  libraries/plugins/src/plugins/PluginUtils.cpp
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14410 CreateApp Fix entity list double click rename / highlight and virtual keyboard issue
  scripts/system/html/js/entityList.js
  scripts/system/html/js/listView.js
  scripts/system/libraries/entityList.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#14406 disable interstitial for master
  libraries/networking/src/DomainHandler.h
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14412 Avatar Pipeline Joint Rotation Offsets Handling
  libraries/animation/src/AnimSkeleton.cpp
  libraries/animation/src/AnimSkeleton.h
  libraries/animation/src/Rig.cpp
  libraries/fbx/src/FBXReader.cpp
  libraries/hfm/src/hfm/HFM.h
  libraries/render-utils/src/CauterizedModel.cpp
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/SoftAttachmentModel.cpp
Labels: Avatar, Development Approved, Project Approved, QA Approved :tada:

#14409 keyboard address some feedback
  interface/resources/config/keyboard.json
  interface/resources/meshes/drumstick.fbx
  interface/resources/sounds/keyboardPress.mp3
  interface/resources/sounds/keyboard_key.mp3
  interface/src/ui/Keyboard.cpp
  interface/src/ui/overlays/Overlays.cpp
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14420 Dismiss keyboard when backout of the login screen
  interface/resources/qml/dialogs/TabletLoginDialog.qml
Labels: Client, Development Approved, Project Approved, QA Ready

#14430 MS19903: don't trigger virtual keyboard scroll on non input focus.
  interface/resources/html/raiseAndLowerKeyboard.js
Labels: Client, Create, Development Approved, Project Approved, QA Approved :tada:

#14428 consider avatar traits bytes in budget and omit if over
  assignment-client/src/avatars/AvatarMixerSlave.cpp
Labels: Development Approved, QA Approved :tada:, Server & Network

#14431 Turn off throttling behavior when not throttling
  assignment-client/src/audio/AudioMixer.cpp
Labels: Development Approved, Project Approved, QA Approved :tada:, Server & Network

#14433 Fix several entity tool window styling issues
  scripts/system/html/css/edit-style.css
  scripts/system/html/gridControls.html
  scripts/system/html/js/draggableNumber.js
  scripts/system/html/js/entityProperties.js
  scripts/system/html/js/gridControls.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#14434 catch QString exceptions that ModelCache can throw
  libraries/model-networking/src/model-networking/ModelCache.cpp
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14391 Upload content to domain server in multiple chunks
  domain-server/resources/web/content/js/content.js
  domain-server/src/DomainContentBackupManager.cpp
  domain-server/src/DomainContentBackupManager.h
  domain-server/src/DomainServer.cpp
  domain-server/src/DomainServer.h
Labels: Development Approved, Project Approved, QA Approved :tada:, QA Ready, Server & Network

#14435 Entity list - prevent draggable number updates while dragging
  scripts/system/edit.js
  scripts/system/html/js/draggableNumber.js
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:, bug

#14280 FB17381 - Reticle.setVisible isn't working
  scripts/system/controllers/controllerModules/mouseHMD.js
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14451 RC76: ensure packets are always added to loss list after estimated timeout
  libraries/networking/src/udt/SendQueue.cpp
  libraries/networking/src/udt/SendQueue.h
Labels: Development Approved, Project Approved, QA Approved :tada:, Server & Network

#14447 v0.76-RC - fixing keyboard mallets dimensions
  interface/src/ui/Keyboard.cpp
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14448 Draggable numbers - fix scale buttons hiding and pressing enter on numbers
  scripts/system/html/js/draggableNumber.js
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:, bug

#14436 ensure packets are always added to loss list after estimated timeout
  libraries/networking/src/udt/SendQueue.cpp
  libraries/networking/src/udt/SendQueue.h
Labels: Development Approved, Project Approved, QA Approved :tada:, Server & Network

#14458 RC 0.75.2: ensure packets are added to loss list after timeout
  libraries/networking/src/udt/SendQueue.cpp
  libraries/networking/src/udt/SendQueue.h
Labels: Development Approved, Project Approved, QA Approved :tada:, Server & Network

#14471 Make vcpkg build default to home directory on mac
  prebuild.py
Labels: Development Approved, Project Approved, QA Ready

#14438 update wireshark dissector with correct control packet types
  tools/dissectors/1-hfudt.lua
Labels: Development Approved, Project Approved, QA Approved :tada:, Server & Network

#14475 RC75.2: Turn off throttling behavior when not throttling
  assignment-client/src/audio/AudioMixer.cpp
Labels: Development Approved, Project Approved, QA Ready, Server & Network

#14468 RC75.2: consider avatar traits bytes in budget and omit if over
  assignment-client/src/avatars/AvatarMixerSlave.cpp
Labels: Development Approved, Project Approved, Server & Network, bug

#14466 Remove Entity Grab Highlighting for RC76
  scripts/system/controllers/controllerDispatcher.js
  scripts/system/controllers/controllerModules/equipEntity.js
  scripts/system/controllers/controllerModules/farActionGrabEntity.js
  scripts/system/controllers/controllerModules/highlightNearbyEntities.js
  scripts/system/controllers/controllerModules/mouseHighlightEntities.js
  scripts/system/controllers/controllerModules/nearActionGrabEntity.js
  scripts/system/controllers/controllerModules/nearParentGrabEntity.js
  scripts/system/controllers/controllerModules/nearTrigger.js
  scripts/system/controllers/controllerScripts.js
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14461 Swap key light directions in Create
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#14459 Fix lifetime slider, make it a regular input
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#14340 Change to English spelling of 'declination'
  libraries/graphics/src/graphics/Stage.cpp
Labels: Development Approved, Engine, Project Approved

#14470 Fix draggable inputs not being tabbable (76)
  scripts/system/html/css/edit-style.css
  scripts/system/html/js/draggableNumber.js
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#14482 add throttle start and backoff to DS settings (RC v0.75.2)
  assignment-client/src/audio/AudioMixer.cpp
  assignment-client/src/audio/AudioMixer.h
  domain-server/resources/describe-settings.json
Labels: Development Approved, Project Approved, Server & Network

#14465 make cmake -DDISABLE_QML=1 work again
  interface/src/Application.cpp
  interface/src/Application_render.cpp
  interface/src/ConnectionMonitor.cpp
  interface/src/ui/ApplicationOverlay.cpp
  interface/src/ui/OverlayConductor.cpp
  interface/src/ui/OverlayConductor.h
  interface/src/ui/overlays/Overlays.cpp
  libraries/shared/src/DependencyManager.h
  libraries/ui/src/OffscreenUi.cpp
  libraries/ui/src/ui/Menu.cpp
  libraries/ui/src/ui/TabletScriptingInterface.cpp
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14484 Keyboard menu option in general settings (RC76)
  interface/resources/qml/controlsUit/Keyboard.qml
  interface/src/Menu.cpp
  interface/src/Menu.h
  interface/src/scripting/KeyboardScriptingInterface.cpp
  interface/src/scripting/KeyboardScriptingInterface.h
  interface/src/ui/Keyboard.cpp
  interface/src/ui/Keyboard.h
  interface/src/ui/PreferencesDialog.cpp
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14476 Pay-In API Frontend, Part One
  interface/resources/qml/hifi/commerce/checkout/Checkout.qml
  interface/resources/qml/hifi/commerce/common/sendAsset/RecipientDisplay.qml
  interface/resources/qml/hifi/commerce/common/sendAsset/SendAsset.qml
  scripts/system/commerce/wallet.js
  scripts/system/html/js/marketplacesInject.js
  scripts/system/marketplaces/marketplaces.js
Labels: Commerce, Development Ready, Project Approved, QA Approved :tada:

#14394 (case 20005) Create HFMSerializer interface for model loaders
  interface/src/ModelPackager.cpp
  interface/src/ModelPackager.h
  interface/src/ModelPropertiesDialog.h
  interface/src/raypick/CollisionPick.cpp
  libraries/animation/src/AnimSkeleton.h
  libraries/animation/src/AnimationCache.cpp
  libraries/animation/src/AnimationCache.h
  libraries/animation/src/AnimationObject.h
  libraries/baking/src/FBXBaker.cpp
  libraries/baking/src/ModelBaker.cpp
  libraries/baking/src/OBJBaker.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/fbx/src/FBX.h
  libraries/fbx/src/FBXSerializer.cpp
  libraries/fbx/src/FBXSerializer.h
  libraries/fbx/src/FBXSerializer_Material.cpp
  libraries/fbx/src/FBXSerializer_Mesh.cpp
  libraries/fbx/src/FBXSerializer_Node.cpp
  libraries/fbx/src/GLTFSerializer.cpp
  libraries/fbx/src/GLTFSerializer.h
  libraries/fbx/src/OBJSerializer.cpp
  libraries/fbx/src/OBJSerializer.h
  libraries/hfm/src/hfm/HFMSerializer.h
  libraries/model-networking/src/model-networking/ModelCache.cpp
  libraries/model-networking/src/model-networking/ModelCache.h
  libraries/shared/src/shared/HifiTypes.h
  tests-manual/gpu/src/TestFbx.cpp
  tools/skeleton-dump/src/SkeletonDumpApp.cpp
  tools/vhacd-util/src/VHACDUtil.cpp
  tools/vhacd-util/src/VHACDUtil.h
  tools/vhacd-util/src/VHACDUtilApp.h
Labels: Development Approved, Engine, QA Approved :tada:

#14478 Fix script engine crashes when reloading scripts.
  libraries/script-engine/src/ScriptEngines.cpp
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14445 fixing keyboard mallets dimensions
  interface/src/ui/Keyboard.cpp
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14456 Draggable numbers - fix undo, particle angles, being disabled, more robust dragging
  scripts/system/edit.js
  scripts/system/html/js/draggableNumber.js
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:, bug

#14493 Fix UBSAN warning
  libraries/audio/src/AudioDynamics.h
Labels: Client, Development Approved, Project Approved, QA Ready

#14429 Remove entity highlighting
  scripts/system/controllers/controllerDispatcher.js
  scripts/system/controllers/controllerModules/equipEntity.js
  scripts/system/controllers/controllerModules/farActionGrabEntity.js
  scripts/system/controllers/controllerModules/highlightNearbyEntities.js
  scripts/system/controllers/controllerModules/mouseHighlightEntities.js
  scripts/system/controllers/controllerModules/nearActionGrabEntity.js
  scripts/system/controllers/controllerModules/nearParentGrabEntity.js
  scripts/system/controllers/controllerModules/nearTrigger.js
  scripts/system/controllers/controllerScripts.js
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14498 Fix the audio injector "pitch" property
  libraries/audio/src/AudioInjector.cpp
Labels: Client, Development Approved, Project Approved, QA Approved :tada:, bug

#14499 RC76: Fix the audio injector "pitch" property
  libraries/audio/src/AudioInjector.cpp
Labels: Client, Development Approved, Project Approved, QA Approved :tada:, bug

#14500 RC76: Entity properties - fix subproperty updates
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:, bug

#14504 Fix empty rgb field in Create going black - 76
  scripts/system/html/js/colpick.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#14440 19942 Mac installation procedure
  tools/nitpick/README.md
Labels: Development Approved, Engine, Mac Required, Project Approved, QA Approved :tada:

#14464 Fix fax grab to near grab transition and haptic pulses
  scripts/system/controllers/controllerModules/farParentGrabEntity.js
  scripts/system/controllers/controllerModules/nearActionGrabEntity.js
  scripts/system/controllers/controllerModules/nearParentGrabEntity.js
  scripts/system/libraries/controllerDispatcherUtils.js
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14489 Remove unused avatar attachment constant
  interface/src/ModelSelector.cpp
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14432 Fix memory accumulating while Interface is minimized
  interface/src/Application.cpp
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14483 Keyboard menu option in general settings
  interface/resources/qml/controlsUit/Keyboard.qml
  interface/src/Menu.cpp
  interface/src/Menu.h
  interface/src/scripting/KeyboardScriptingInterface.cpp
  interface/src/scripting/KeyboardScriptingInterface.h
  interface/src/ui/Keyboard.cpp
  interface/src/ui/Keyboard.h
  interface/src/ui/PreferencesDialog.cpp
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14488 don't save joint information for avatar entities in avatarbookmarks.json
  interface/src/AvatarBookmarks.cpp
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14485 suppress 'No instance available' messages during shutdown. try a dif…
  interface/src/Application.cpp
  libraries/audio-client/src/AudioClient.cpp
  libraries/shared/src/DependencyManager.h
Labels: Client, Development Approved, Project Approved, QA Approved :tada:
