Repository highfidelity/hifi, pull requests merged in 2018-12, with the labels that each got.

#14492 Fix audio mixer crash
  assignment-client/src/audio/AudioMixerClientData.cpp
Labels: Development Approved, Project Approved, QA Approved :tada:, Server & Network

#14505 Fix empty rgb field in Create going black
  scripts/system/html/js/colpick.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#14494 Fix Agent crash on shutdown
  assignment-client/src/avatars/ScriptableAvatar.cpp
  interface/src/avatar/MyAvatar.cpp
  libraries/avatars/src/AvatarData.h
  libraries/avatars/src/ClientTraitsHandler.cpp
  libraries/shared/src/SharedUtil.h
Labels: Development Approved, Project Approved, QA Approved :tada:, Server & Network

#14506 Fix various AC bugs
  assignment-client/src/Agent.cpp
  assignment-client/src/AssignmentClient.cpp
  assignment-client/src/scripts/EntityScriptServer.cpp
  libraries/recording/src/recording/Deck.cpp
Labels: Development Approved, Project Approved, QA Approved :tada:, Server & Network

#14512 76.1: Implement MS19650: Oculus Store mode audio settings modification
  interface/resources/qml/hifi/audio/Audio.qml
  interface/src/scripting/Audio.cpp
  interface/src/scripting/Audio.h
  interface/src/scripting/AudioDevices.cpp
  interface/src/scripting/WindowScriptingInterface.cpp
  interface/src/scripting/WindowScriptingInterface.h
Labels: Client, Development Approved, Oculus Required, Project Approved, QA Approved :tada:

#14514 Case 19740: Improve startup times by pre-compiling shaders with splash screen (RC76.1)
  interface/resources/shaders/splashSkybox.frag
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/Application_render.cpp
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLBackend.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLBackend.h
  libraries/gpu-gl-common/src/gpu/gl/GLShader.cpp
  libraries/gpu/src/gpu/Context.cpp
  libraries/gpu/src/gpu/Context.h
  libraries/gpu/src/gpu/null/NullBackend.h
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14526 Head and Hand offsets for Vive Trackers now function as expected
  interface/resources/qml/hifi/tablet/OpenVrConfiguration.qml
  plugins/openvr/src/ViveControllerManager.cpp
Labels: Avatar, Development Approved, Project Approved, QA Approved :tada:, Vive Tracker Required

#14532 Added DropAfterDelay strategy to Vive Tracker Calibration Dialog
  interface/resources/qml/hifi/tablet/OpenVrConfiguration.qml
  plugins/openvr/src/ViveControllerManager.cpp
  plugins/openvr/src/ViveControllerManager.h
Labels: Avatar, Development Approved, Project Approved, QA Approved :tada:, Vive Tracker Required

#14443 Case 19660: Fix HUD crash
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.cpp
  libraries/display-plugins/src/display-plugins/hmd/HmdDisplayPlugin.cpp
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:, bug

#14528 work around menu-item name hash collision for Home
  interface/src/Menu.h
  libraries/ui/src/ui/Menu.h
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14535 Case 20138: Fix vive crash (RC 76)
  plugins/openvr/src/OpenVrDisplayPlugin.cpp
Labels: Critical Fix, Development Approved, Engine, Project Approved, QA Approved :tada:, bug

#14537 Respect changed audio settings when switch displays (RC76)
  interface/src/Application.cpp
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14522 [RC77] MS20114 [CreateApp] ignore createApp shortcut keys while TEXTAREA elements are in focus
  scripts/system/html/js/entityList.js
  scripts/system/html/js/entityProperties.js
  scripts/system/html/js/gridControls.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#14536 Respect changed audio settings when switch displays (Master)
  interface/src/Application.cpp
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14442 Ensure that hand is in grasp pose during desktop handshake animation
  scripts/system/makeUserConnection.js
Labels: Avatar, Development Approved, Development Ready, Project Approved, QA Approved :tada:

#14508 removed the code that turns off inactive hands in MyAvatar.cpp
  interface/src/avatar/MyAvatar.cpp
Labels: Avatar, Development Approved, HMD required, Project Approved, QA Approved :tada:

#14495 Draggable numbers - RC76 fixes to master
  scripts/system/edit.js
  scripts/system/html/js/draggableNumber.js
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#14372 Case 19798: 3D projected Material Entities and materialRepeat option
  libraries/entities-renderer/src/RenderableMaterialEntityItem.cpp
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityPropertyFlags.cpp
  libraries/entities/src/EntityPropertyFlags.h
  libraries/entities/src/MaterialEntityItem.cpp
  libraries/entities/src/MaterialEntityItem.h
  libraries/graphics/src/graphics/Material.cpp
  libraries/graphics/src/graphics/Material.h
  libraries/graphics/src/graphics/Material.slh
  libraries/graphics/src/graphics/MaterialTextures.slh
  libraries/graphics/src/graphics/TextureMap.h
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
  libraries/render-utils/src/deformed_model.slv
  libraries/render-utils/src/deformed_model_dq.slv
  libraries/render-utils/src/deformed_model_normal_map.slv
  libraries/render-utils/src/deformed_model_normal_map_dq.slv
  libraries/render-utils/src/model.slv
  libraries/render-utils/src/model_normal_map.slv
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, Engine, Feedback Welcome, Packet Version Change, Project Approved, QA Approved :tada:

#14426 FB19400 during shutdown -- TypeError: Cannot read property 'buttons' of null
  interface/resources/qml/hifi/Desktop.qml
  interface/resources/qml/hifi/tablet/TabletHome.qml
  libraries/qml/src/qml/OffscreenSurface.cpp
  libraries/qml/src/qml/impl/SharedObject.cpp
  libraries/qml/src/qml/impl/SharedObject.h
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14544 Improve Create properties for particles + materials
  scripts/system/assets/data/createAppTooltips.json
  scripts/system/html/css/edit-style.css
  scripts/system/html/js/draggableNumber.js
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, QA Approved :tada:

#14502 Update build docs and prebuild.py to warn about HIFI_VCPKG_BASE
  BUILD.md
  BUILD_WIN.md
Labels: Development Approved, Project Approved, QA Approved :tada:

#14441 Prevent dragging and dropping files onto Create windows
  scripts/system/html/entityList.html
  scripts/system/html/entityProperties.html
  scripts/system/html/gridControls.html
  scripts/system/html/js/entityList.js
  scripts/system/html/js/entityProperties.js
  scripts/system/html/js/gridControls.js
  scripts/system/html/js/utils.js
Labels: Create, Development Approved, Mac Required, Project Approved, QA Approved :tada:, Windows Required

#14421 Entity list - reorder columns
  scripts/system/html/css/edit-style.css
  scripts/system/html/js/entityList.js
  scripts/system/html/js/listView.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#14501 MS19567 [CreateApp]: userData error message continues popup fix
  scripts/system/html/css/edit-style.css
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#14529 Don't fetch avatars' .fst files from within the AvatarData class
  assignment-client/src/avatars/ScriptableAvatar.cpp
  assignment-client/src/avatars/ScriptableAvatar.h
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
Labels: Development Approved, Project Approved, QA Approved :tada:, Server & Network

#14549 fix for initial send of non-instanced trait
  libraries/avatars/src/ClientTraitsHandler.cpp
Labels: Critical Fix, Development Approved, Project Approved, QA Approved :tada:, Server & Network

#14539 Fix ESS scripts getting stuck on load
  libraries/script-engine/src/ScriptEngine.cpp
  libraries/script-engine/src/ScriptEngine.h
Labels: Create, Development Approved, Project Approved, QA Approved :tada:, Server & Network

#14531 Added DropAfterDelay strategy to Vive Tracker Calibration Dialog
  interface/resources/qml/hifi/tablet/OpenVrConfiguration.qml
  plugins/openvr/src/ViveControllerManager.cpp
  plugins/openvr/src/ViveControllerManager.h
Labels: Avatar, Development Approved, Project Approved, QA Approved :tada:, Vive Tracker Required

#14480 MS20000: [CreateApp/Tooltips] Add missing start/middle/finish tooltips
  scripts/system/assets/data/createAppTooltips.json
  scripts/system/html/css/edit-style.css
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#14540 Add hiding of certified properties in Create
  scripts/system/html/js/entityList.js
  scripts/system/html/js/entityProperties.js
  scripts/system/libraries/entityList.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#14460 Change lifetime back to a regular input field
  scripts/system/html/css/edit-style.css
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#14450 match domain paths match case-insensitively
  domain-server/resources/web/js/base-settings.js
  domain-server/src/DomainServer.cpp
Labels: Development Approved, Project Approved, QA Approved :tada:, Server & Network

#14419 Case 19740: Improve startup times by pre-compiling shaders with splash screen
  interface/resources/shaders/splashSkybox.frag
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/Application_render.cpp
  interface/src/graphics/GraphicsEngine.cpp
  interface/src/graphics/GraphicsEngine.h
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLBackend.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLBackend.h
  libraries/gpu-gl-common/src/gpu/gl/GLShader.cpp
  libraries/gpu/src/gpu/Batch.cpp
  libraries/gpu/src/gpu/Context.cpp
  libraries/gpu/src/gpu/Context.h
  libraries/gpu/src/gpu/null/NullBackend.h
Labels: Development Approved, Engine, Feedback Welcome, Project Approved, QA Approved :tada:

#14548 Case 19473 (#2): Fix Mirror tonemapping
  libraries/gpu/src/gpu/Color.slh
  libraries/render-utils/src/simple_textured.slf
  libraries/render-utils/src/simple_textured_fade.slf
  libraries/render-utils/src/simple_textured_unlit.slf
  libraries/render-utils/src/simple_textured_unlit_fade.slf
  libraries/render-utils/src/simple_transparent_textured.slf
  libraries/render-utils/src/simple_transparent_textured_fade.slf
  libraries/render-utils/src/simple_transparent_textured_unlit.slf
  libraries/render-utils/src/simple_transparent_textured_unlit_fade.slf
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:, bug

#14486 FST File Joint Name Mapping From FBX Joint Names to Hifi Skeleton Joint Names
  libraries/animation/src/AnimSkeleton.cpp
  libraries/fbx/src/FBXSerializer.cpp
  libraries/fbx/src/FSTReader.h
  libraries/hfm/src/hfm/HFM.h
Labels: Avatar, Create, Development Approved, Project Approved, QA Approved :tada:

#14239 FB19219 - Make avatarapp to handle wearables update via drag&drop
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/entities/src/EntityScriptingInterface.cpp
  libraries/entities/src/EntityScriptingInterface.h
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/EntityTree.h
  libraries/entities/src/ModelEntityItem.cpp
  scripts/system/avatarapp.js
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14276 Make create apps not grab tablet if editing an entity with hand
  scripts/system/controllers/controllerDispatcher.js
  scripts/system/controllers/controllerModules/farActionGrabEntityDynOnly.js
  scripts/system/controllers/controllerModules/farParentGrabEntity.js
  scripts/system/controllers/controllerModules/farTrigger.js
  scripts/system/controllers/controllerModules/inEditMode.js
  scripts/system/controllers/controllerModules/inVREditMode.js
  scripts/system/controllers/controllerModules/nearParentGrabOverlay.js
  scripts/system/controllers/controllerModules/nearTabletHighlight.js
  scripts/system/libraries/entitySelectionTool.js
Labels: Client, Create, Development Approved, Project Approved, QA Approved :tada:

#14546 fix realod all scripts functionality broken by PR14478
  libraries/script-engine/src/ScriptEngines.cpp
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#13966 Added steps to run interface in Ubuntu 18.04 .
  BUILD_LINUX.md
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14552 Pass on dropFaceTracking flag in ScriptableAvatar::toByteArrayStateful()
  assignment-client/src/avatars/ScriptableAvatar.cpp
Labels: Development Approved, Project Approved, QA Approved :tada:, Server & Network

#14550 Fix MS20208: Change an instance of 'ASSETS' to 'INVENTORY'
  interface/resources/qml/hifi/dialogs/security/Security.qml
Labels: Commerce, Development Approved, Development Ready, Project Approved, QA Approved :tada:, bug

#14541 Unity Avatar Exporter
  .gitignore
  tools/unity-avatar-exporter/Assets/Editor.meta
  tools/unity-avatar-exporter/Assets/Editor/AvatarExporter.cs
  tools/unity-avatar-exporter/Assets/Editor/AvatarExporter.cs.meta
  tools/unity-avatar-exporter/avatarExporter.unitypackage
  tools/unity-avatar-exporter/packager.bat
Labels: Avatar, Create, Development Approved, Project Approved, QA Approved :tada:

#14557 Fix MS20215: Fix incorrect display of unavailable items on Marketplace main page
  scripts/system/html/js/marketplacesInject.js
Labels: Commerce, Development Ready, Project Approved, QA Approved :tada:, bug

#14555 Added missed header
  interface/src/graphics/RenderEventHandler.h
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14517 Add method to check entities joint hierarchy
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.h
  libraries/entities/src/EntityItem.h
  libraries/entities/src/EntityScriptingInterface.cpp
  libraries/entities/src/EntityScriptingInterface.h
  libraries/shared/src/SpatiallyNestable.h
Labels: Avatar, Development Approved, Project Approved, QA Approved :tada:, Scripting API change

#14554 fix some parenting loops crashes
  libraries/shared/src/SpatiallyNestable.cpp
  libraries/shared/src/SpatiallyNestable.h
Labels: Client, Development Approved, Project Approved, QA Approved :tada:, bug

#14479 (case 20037) Add robust MIME type detection for loading models in ModelCache
  interface/src/Application.cpp
  libraries/animation/src/AnimationCache.cpp
  libraries/animation/src/AnimationCache.h
  libraries/fbx/src/FBXSerializer.cpp
  libraries/fbx/src/FBXSerializer.h
  libraries/fbx/src/GLTFSerializer.cpp
  libraries/fbx/src/GLTFSerializer.h
  libraries/fbx/src/OBJSerializer.cpp
  libraries/fbx/src/OBJSerializer.h
  libraries/hfm/src/hfm/HFMFormatRegistry.cpp
  libraries/hfm/src/hfm/HFMFormatRegistry.h
  libraries/hfm/src/hfm/HFMSerializer.h
  libraries/hfm/src/hfm/ModelFormatRegistry.cpp
  libraries/hfm/src/hfm/ModelFormatRegistry.h
  libraries/model-networking/src/model-networking/ModelCache.cpp
  libraries/model-networking/src/model-networking/ModelCache.h
  libraries/model-networking/src/model-networking/ModelLoader.cpp
  libraries/model-networking/src/model-networking/ModelLoader.h
  libraries/networking/src/HTTPResourceRequest.cpp
  libraries/networking/src/ResourceRequest.h
  libraries/shared/src/shared/MediaTypeLibrary.cpp
  libraries/shared/src/shared/MediaTypeLibrary.h
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14521 20197: Containerized Android builds
  .gitignore
  BUILD_ANDROID.md
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  android/build_android.sh
  android/containerized_build.sh
  android/docker/Dockerfile
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  hifi_android.py
  hifi_singleton.py
  hifi_utils.py
  hifi_vcpkg.py
  interface/src/Menu.cpp
  prebuild.py
Labels: Android, Client, Development Approved, Development Ready, Engine, Project Approved, QA Ready

#14561 Case 20250: Disable splash screen on android
  interface/src/graphics/GraphicsEngine.cpp
  interface/src/graphics/GraphicsEngine.h
Labels: Android, Critical Fix, Engine, Project Approved, QA Approved :tada:

#14560 Fix MS4382: Add a lifetime to handshake particle effects to prevent persistence
  scripts/system/makeUserConnection.js
Labels: Client, Development Approved, Discovery, Project Approved, QA Approved :tada:, bug

#14559 Fix MS20161: Fix INVENTORY notification dot state
  interface/resources/qml/hifi/commerce/wallet/Wallet.qml
  scripts/system/commerce/wallet.js
Labels: Commerce, Development Approved, Project Approved, QA Approved :tada:, bug

#14563 Adding menu settings to disable teleporting
  interface/resources/qml/dialogs/preferences/CheckBoxPreference.qml
  interface/resources/qml/hifi/tablet/tabletWindows/TabletPreferencesDialog.qml
  interface/src/avatar/MyAvatar.h
  interface/src/ui/PreferencesDialog.cpp
  scripts/system/controllers/controllerModules/teleport.js
Labels: Client, Development Approved, QA Approved :tada:

#14545 20116 nitpick v1.2
  tools/nitpick/README.md
  tools/nitpick/src/AWSInterface.cpp
  tools/nitpick/src/AWSInterface.h
  tools/nitpick/src/Test.cpp
  tools/nitpick/src/Test.h
  tools/nitpick/src/TestRailInterface.cpp
  tools/nitpick/src/TestRunner.cpp
  tools/nitpick/src/ui/Nitpick.cpp
Labels: Development Approved, Engine, Mac Required, QA Approved :tada:, Windows Required, nitpick

#14507 DNM - TEST FOR MAC CRASH ON COMPLETION OF TESTS
  libraries/audio-client/src/AudioClient.cpp
Labels: DO NOT MERGE

#14566 Fix MS17811: Prevent frozen avatars in certain ignore cases
  assignment-client/src/avatars/AvatarMixerClientData.h
  assignment-client/src/avatars/AvatarMixerSlave.cpp
Labels: Development Approved, Discovery, Project Approved, QA Approved :tada:, bug

#14453 Keyboard interaction menus
  interface/resources/config/keyboard.json
  interface/resources/qml/dialogs/PreferencesDialog.qml
  interface/resources/qml/dialogs/preferences/CheckBoxPreference.qml
  interface/resources/qml/dialogs/preferences/RadioButtonsPreference.qml
  interface/resources/qml/hifi/tablet/tabletWindows/TabletPreferencesDialog.qml
  interface/resources/sounds/keySound.mp3
  interface/src/scripting/KeyboardScriptingInterface.cpp
  interface/src/scripting/KeyboardScriptingInterface.h
  interface/src/ui/Keyboard.cpp
  interface/src/ui/Keyboard.h
  interface/src/ui/PreferencesDialog.cpp
  interface/src/ui/overlays/ModelOverlay.cpp
  interface/src/ui/overlays/Overlays.cpp
  libraries/shared/src/Preferences.h
  scripts/system/controllers/controllerDispatcher.js
  scripts/system/controllers/controllerModules/stylusInput.js
  scripts/system/controllers/controllerModules/webSurfaceLaserInput.js
  scripts/system/libraries/controllerDispatcherUtils.js
  scripts/system/libraries/pointersUtils.js
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14572 Case 19740: Improve startup times by pre-compiling shaders with splash screen (RC76.1)
  interface/resources/shaders/splashSkybox.frag
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/Application_render.cpp
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLBackend.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLBackend.h
  libraries/gpu-gl-common/src/gpu/gl/GLShader.cpp
  libraries/gpu/src/gpu/Context.cpp
  libraries/gpu/src/gpu/Context.h
  libraries/gpu/src/gpu/null/NullBackend.h
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14573 76.1 (again): Implement MS19650: Oculus Store mode audio settings modification
  interface/resources/qml/hifi/audio/Audio.qml
  interface/src/scripting/Audio.cpp
  interface/src/scripting/Audio.h
  interface/src/scripting/AudioDevices.cpp
  interface/src/scripting/WindowScriptingInterface.cpp
  interface/src/scripting/WindowScriptingInterface.h
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14574 Fix a bug introduced in PR14566, actually fixing MS17811
  assignment-client/src/avatars/AvatarMixerSlave.cpp
Labels: Development Approved, Project Approved, QA Approved :tada:, bug

#14567 Return more connections in pal
  interface/resources/qml/hifi/Pal.qml
Labels: Development Approved, Discovery, Project Approved, QA Approved :tada:, bug

#14581 Fix MS20308: Allow users to checkout uncertifiable items
  interface/resources/qml/hifi/commerce/checkout/Checkout.qml
Labels: Commerce, Development Ready, QA Approved :tada:, bug

#14582 MS20319: fixing keyboard position offset (RC 77)
  interface/src/Application.cpp
Labels: Client, Critical Fix, Development Approved, QA Approved :tada:, bug

#14580 MS20319: fixing keyboard position offset
  interface/src/Application.cpp
Labels: Client, Critical Fix, Development Approved, Project Approved, QA Approved :tada:, bug

#14590 MS20328: New login breaks nitpick (RC 77)
  interface/src/Application.cpp
Labels: Client, Critical Fix, Development Approved, Project Approved, QA Approved :tada:, bug

#14588 MS20328: New login breaks nitpick
  interface/src/Application.cpp
Labels: Client, Critical Fix, Development Approved, Project Approved, QA Approved :tada:, bug

#14577 Agent needs to be sure audio is ready before trying to use it
  assignment-client/src/Agent.cpp
Labels: QA Approved :tada:, Server & Network, bug

#14587 Deobfuscate packets in dissector
  tools/dissectors/1-hfudt.lua
Labels: Development Approved, QA Approved :tada:, Server & Network

#14589 Avatar eye tracking works again
  interface/src/avatar/MySkeletonModel.cpp
Labels: Avatar, Development Approved, Project Approved, QA Approved :tada:

#14564 (case 20274) Create the HFM Preparation Step
  interface/CMakeLists.txt
  libraries/model-baker/CMakeLists.txt
  libraries/model-baker/src/model-baker/Baker.cpp
  libraries/model-baker/src/model-baker/Baker.h
  libraries/model-baker/src/model-baker/Engine.h
  libraries/model-networking/CMakeLists.txt
  libraries/model-networking/src/model-networking/ModelCache.cpp
  libraries/shared/src/Profile.cpp
  libraries/shared/src/Profile.h
  plugins/openvr/CMakeLists.txt
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14600 MS20352: Keep me logged in checkbox as on by default
  interface/resources/qml/LoginDialog/LinkAccountBody.qml
  interface/resources/qml/LoginDialog/SignUpBody.qml
Labels: Client, Critical Fix, Development Approved, Project Approved, QA Approved :tada:, bug

#14596 MS20332: HMD Login Prompt-- small avatars cannot reach easily
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/avatar/MyAvatar.cpp
Labels: Client, Critical Fix, Development Approved, Project Approved, QA Approved :tada:, bug

#14599 MS20352: Keep me logged in checkbox as on by default
  interface/resources/qml/LoginDialog/LinkAccountBody.qml
  interface/resources/qml/LoginDialog/SignUpBody.qml
Labels: Client, Critical Fix, Development Approved, Project Approved, QA Approved :tada:, bug

#13925 fix a bug that broke Entities.setVoxel(). Fix polyvox textures
  libraries/entities-renderer/src/RenderablePolyVoxEntityItem.cpp
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14593 Remove out-of-date backups on startup
  domain-server/src/DomainContentBackupManager.cpp
Labels: Development Ready, Project Approved, QA Approved :tada:, Server & Network

#14607 MS#20355: HMD persisting extra login windows (RC 77)
  interface/src/ui/LoginDialog.cpp
Labels: Client, Critical Fix, Development Approved, Project Approved, QA Approved :tada:, bug

#14604 Implement MS20089: ACs playing avatar recordings now correctly handle playAvatarSound
  assignment-client/src/Agent.cpp
  assignment-client/src/Agent.h
Labels: Development Approved, Project Approved, QA Approved :tada:, Server & Network, bug

#14606 MS#20355: HMD persisting extra login windows
  interface/src/ui/LoginDialog.cpp
Labels: Client, Critical Fix, Development Approved, Project Approved, QA Approved :tada:, bug

#14598 Fix for Camera-perspective-is-off-in-first-person-view, master branch
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MySkeletonModel.cpp
  libraries/animation/src/Rig.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/SkeletonModel.cpp
  libraries/avatars-renderer/src/avatars-renderer/SkeletonModel.h
  libraries/fbx/src/FBXSerializer.cpp
  libraries/fbx/src/GLTFSerializer.cpp
  libraries/hfm/src/hfm/HFM.h
  libraries/render-utils/src/CauterizedModel.cpp
Labels: Avatar, Development Approved, Project Approved, QA Approved :tada:

#14608 Case 19080: Fix zone with invalid script not loading
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.h
Labels: Development Approved, Engine, QA Approved :tada:, bug

#14611 MS20356: Running Scripts list doesn't persist between Interface restarts
  interface/src/Application.cpp
Labels: Client, Critical Fix, Development Approved, Project Approved, QA Approved :tada:, bug

#14612 MS20356: Running Scripts list doesn't persist between Interface restarts
  interface/src/Application.cpp
Labels: Client, Critical Fix, Development Approved, Project Approved, QA Ready, bug

#14538 FB19355 - When I have avatar entities as children of my avatar, the A…
  interface/resources/qml/hifi/avatarapp/AdjustWearables.qml
Labels: Client, Development Approved, Project Approved, QA Ready

#14523 Case 20131: Cleanup some Entity Properties
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/ModelEntityItem.cpp
  libraries/entities/src/ParticleEffectEntityItem.cpp
  libraries/entities/src/PolyLineEntityItem.cpp
  libraries/entities/src/ShapeEntityItem.cpp
  libraries/entities/src/ZoneEntityItem.cpp
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
Labels: Development Approved, Engine, Packet Version Change, QA Approved :tada:

#14618 MS20374: Issues with overlays - Part 1: Inventory app Log In button
  scripts/system/commerce/wallet.js
Labels: Client, Critical Fix, Development Approved, Project Approved, QA Approved :tada:, bug

#14615 MS20366: Restarting interface and skipping login causes user to appear in serverless
  interface/src/Application.cpp
Labels: Client, Development Approved, HMD required, Project Approved, QA Approved :tada:

#14616 MS20366: Restarting interface and skipping login causes user to appear in serverless
  interface/src/Application.cpp
Labels: Client, Development Approved, HMD required, Project Approved, QA Approved :tada:

#14568 Implement MS20187: Add trash can feature to Inventory
  interface/resources/qml/hifi/commerce/purchases/PurchasedItem.qml
  interface/resources/qml/hifi/commerce/purchases/Purchases.qml
Labels: Commerce, Project Approved, QA Approved :tada:

#14613 MS20253: Only emit screenChanged once screen has changed
  interface/resources/qml/hifi/tablet/TabletRoot.qml
  interface/resources/qml/hifi/tablet/WindowRoot.qml
  libraries/ui/src/ui/TabletScriptingInterface.cpp
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14547 Case 20200: Update EntityScriptingInterface to not find local entities
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/avatar/MyAvatar.cpp
  interface/src/raypick/LaserPointer.cpp
  interface/src/raypick/LaserPointerScriptingInterface.h
  interface/src/raypick/ParabolaPick.cpp
  interface/src/raypick/PathPointer.cpp
  interface/src/raypick/PickScriptingInterface.cpp
  interface/src/raypick/PickScriptingInterface.h
  interface/src/raypick/PointerScriptingInterface.h
  interface/src/raypick/RayPick.cpp
  interface/src/raypick/RayPickScriptingInterface.h
  interface/src/raypick/StylusPointer.cpp
  interface/src/ui/Keyboard.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities/src/EntityScriptingInterface.cpp
  libraries/entities/src/EntityScriptingInterface.h
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/EntityTree.h
  libraries/entities/src/EntityTreeElement.cpp
  libraries/entities/src/EntityTreeElement.h
  libraries/pointers/src/Pick.cpp
  libraries/pointers/src/Pick.h
  libraries/pointers/src/PickCacheOptimizer.h
  libraries/shared/src/PickFilter.h
  scripts/developer/utilities/tests/entityPerfTest.js
  unpublishedScripts/DomainContent/Toybox/pistol/pistol.js
Labels: Client, Development Approved, Engine, Project Approved, QA Approved :tada:

#14524 Case 20132, Case 16928: First class Image Entities
  interface/resources/qml/hifi/AssetServer.qml
  interface/resources/qml/hifi/dialogs/TabletAssetServer.qml
  interface/src/Application.cpp
  interface/src/ui/overlays/Image3DOverlay.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.h
  libraries/entities-renderer/src/RenderableEntityItem.cpp
  libraries/entities-renderer/src/RenderableImageEntityItem.cpp
  libraries/entities-renderer/src/RenderableImageEntityItem.h
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities-renderer/src/RenderableTextEntityItem.cpp
  libraries/entities-renderer/src/RenderableTextEntityItem.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityItemPropertiesMacros.h
  libraries/entities/src/EntityPropertyFlags.cpp
  libraries/entities/src/EntityPropertyFlags.h
  libraries/entities/src/EntityPsuedoPropertyFlags.h
  libraries/entities/src/EntityScriptingInterface.cpp
  libraries/entities/src/EntityTypes.cpp
  libraries/entities/src/EntityTypes.h
  libraries/entities/src/ImageEntityItem.cpp
  libraries/entities/src/ImageEntityItem.h
  libraries/entities/src/TextEntityItem.cpp
  libraries/entities/src/TextEntityItem.h
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
  libraries/octree/src/OctreePacketData.cpp
  libraries/octree/src/OctreePacketData.h
  libraries/shared/src/BillboardMode.cpp
  libraries/shared/src/BillboardMode.h
  libraries/shared/src/RegisteredMetaTypes.cpp
  libraries/shared/src/RegisteredMetaTypes.h
  scripts/system/edit.js
  scripts/system/html/js/entityList.js
  scripts/system/html/js/entityProperties.js
  scripts/system/libraries/entityList.js
Labels: Create, Development Approved, Engine, Feedback Welcome, Packet Version Change, QA Approved :tada:

#14626 Case 20391: Fix crash when importing a glTF model that contains embedded buffers
  libraries/fbx/src/GLTFSerializer.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#14629 Case 20391: Fix crash when importing a glTF model that contains embedded buffers-0.77.0-rc
  libraries/fbx/src/GLTFSerializer.cpp
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14631 Revert "Case 20200: Update EntityScriptingInterface to not find local entities"
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/avatar/MyAvatar.cpp
  interface/src/raypick/LaserPointer.cpp
  interface/src/raypick/LaserPointerScriptingInterface.h
  interface/src/raypick/ParabolaPick.cpp
  interface/src/raypick/PathPointer.cpp
  interface/src/raypick/PickScriptingInterface.cpp
  interface/src/raypick/PickScriptingInterface.h
  interface/src/raypick/PointerScriptingInterface.h
  interface/src/raypick/RayPick.cpp
  interface/src/raypick/RayPickScriptingInterface.h
  interface/src/raypick/StylusPointer.cpp
  interface/src/ui/Keyboard.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities/src/EntityScriptingInterface.cpp
  libraries/entities/src/EntityScriptingInterface.h
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/EntityTree.h
  libraries/entities/src/EntityTreeElement.cpp
  libraries/entities/src/EntityTreeElement.h
  libraries/pointers/src/Pick.cpp
  libraries/pointers/src/Pick.h
  libraries/pointers/src/PickCacheOptimizer.h
  libraries/shared/src/PickFilter.h
  scripts/developer/utilities/tests/entityPerfTest.js
  unpublishedScripts/DomainContent/Toybox/pistol/pistol.js
Labels: Critical Fix, Development Approved, Engine, Project Approved, QA Approved :tada:, bug

#14614 0.77 case 20304: please don't flood the avatar-mixer with unnecessary AvatarEntity udpates
  interface/src/AvatarBookmarks.cpp
  interface/src/ui/overlays/Base3DOverlay.cpp
  interface/src/ui/overlays/Base3DOverlay.h
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/SimulationOwner.h
  libraries/physics/src/EntityMotionState.cpp
Labels: Development Approved, Development Ready, Engine, Project Approved, QA Approved :tada:

#14635 A simple comment to spawn 76.2
  scripts/developer/utilities/render/luci.js
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14602 Case 20303 : Cleaning up the render view tasks and jobs for better 2ndary camera
  interface/resources/config/render.json
  interface/src/Menu.cpp
  interface/src/SecondaryCamera.cpp
  libraries/entities-renderer/src/RenderableZoneEntityItem.cpp
  libraries/entities-renderer/src/RenderableZoneEntityItem.h
  libraries/gpu-gl-common/src/gpu/gl/GLBackendTransform.cpp
  libraries/render-utils/src/AmbientOcclusionEffect.cpp
  libraries/render-utils/src/AmbientOcclusionEffect.h
  libraries/render-utils/src/AssembleLightingStageTask.cpp
  libraries/render-utils/src/AssembleLightingStageTask.h
  libraries/render-utils/src/DebugDeferredBuffer.cpp
  libraries/render-utils/src/DebugDeferredBuffer.h
  libraries/render-utils/src/DeferredLightingEffect.cpp
  libraries/render-utils/src/DeferredLightingEffect.h
  libraries/render-utils/src/LightClusters.cpp
  libraries/render-utils/src/LightClusters.h
  libraries/render-utils/src/LightStage.cpp
  libraries/render-utils/src/LightStage.h
  libraries/render-utils/src/LightingModel.cpp
  libraries/render-utils/src/LightingModel.h
  libraries/render-utils/src/RenderCommonTask.cpp
  libraries/render-utils/src/RenderCommonTask.h
  libraries/render-utils/src/RenderDeferredTask.cpp
  libraries/render-utils/src/RenderDeferredTask.h
  libraries/render-utils/src/RenderForwardTask.cpp
  libraries/render-utils/src/RenderForwardTask.h
  libraries/render-utils/src/RenderShadowTask.cpp
  libraries/render-utils/src/RenderShadowTask.h
  libraries/render-utils/src/RenderViewTask.cpp
  libraries/render-utils/src/ZoneRenderer.cpp
  libraries/render-utils/src/ZoneRenderer.h
  libraries/render/src/render/FilterTask.h
  libraries/render/src/render/RenderFetchCullSortTask.cpp
  libraries/render/src/render/RenderFetchCullSortTask.h
  libraries/task/src/task/Task.cpp
  libraries/task/src/task/Task.h
  libraries/task/src/task/Varying.h
  scripts/developer/utilities/lib/jet/jet.js
  scripts/developer/utilities/lib/jet/qml/TaskList.qml
  scripts/developer/utilities/render/deferredLighting.qml
  scripts/developer/utilities/render/engineList.js
  scripts/developer/utilities/render/engineList.qml
  scripts/developer/utilities/workload/avatars.js
  scripts/developer/utilities/workload/avatars.qml
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14640 Fix version code for android APKs
  android/build_android.sh
  android/containerized_build.sh
Labels: Android, Android Smoke Required, Development Approved, Project Approved, QA Ready

#14625 Case 20392: Deprecated 3D Overlay dashed/isDashed
  interface/src/ui/overlays/Base3DOverlay.cpp
  interface/src/ui/overlays/Circle3DOverlay.cpp
  interface/src/ui/overlays/Cube3DOverlay.cpp
  interface/src/ui/overlays/Grid3DOverlay.cpp
  interface/src/ui/overlays/Image3DOverlay.cpp
  interface/src/ui/overlays/Line3DOverlay.cpp
  interface/src/ui/overlays/ModelOverlay.cpp
  interface/src/ui/overlays/Rectangle3DOverlay.cpp
  interface/src/ui/overlays/Shape3DOverlay.cpp
  interface/src/ui/overlays/Sphere3DOverlay.cpp
  interface/src/ui/overlays/Text3DOverlay.cpp
  interface/src/ui/overlays/Web3DOverlay.cpp
Labels: Development Approved, Engine, JSDocs, QA Approved :tada:

#14583 Avatar Exporter - joint rotation offsets and file workflow changes
  .gitignore
  tools/unity-avatar-exporter/Assets/Editor/AvatarExporter.cs
  tools/unity-avatar-exporter/Assets/README.txt
  tools/unity-avatar-exporter/Assets/README.txt.meta
  tools/unity-avatar-exporter/avatarExporter.unitypackage
  tools/unity-avatar-exporter/packager.bat
Labels: Avatar, Create, Development Approved, Feedback Welcome, Project Approved, QA Approved :tada:

#14491 Case 20080: v3 + v4 procedurals and misc shader fixes
  libraries/entities-renderer/src/RenderableShapeEntityItem.cpp
  libraries/gpu/src/gpu/Pipeline.h
  libraries/procedural/src/procedural/Procedural.cpp
  libraries/procedural/src/procedural/Procedural.h
  libraries/procedural/src/procedural/ProceduralCommon.slh
  libraries/procedural/src/procedural/ProceduralSkybox.cpp
  libraries/render-utils/src/forward_simple.slf
  libraries/render-utils/src/simple.slf
  libraries/render-utils/src/simple_transparent.slf
Labels: Beware: Threading/Deadlock, Development Approved, Engine, Feedback Welcome, Mac Required, Project Approved, QA Approved :tada:, bug
