Repository highfidelity/hifi, pull requests merged in 2018-03, with the labels that each got.

#12527 Adding debuggin tool for workload
  interface/src/Application.cpp
  interface/src/workload/GameWorkload.cpp
  interface/src/workload/GameWorkloadRenderer.cpp
  interface/src/workload/GameWorkloadRenderer.h
  libraries/gpu-gl/src/gpu/gl45/GL45BackendShader.cpp
  libraries/render-utils/src/drawWorkloadProxy.slf
  libraries/render-utils/src/drawWorkloadProxy.slv
  libraries/workload/src/workload/Space.h
Labels: Development Approved, Engine

#12502 Image entity has correct orientation and is collisionless
  interface/resources/meshes/images/default-image-model.fbx
  interface/resources/qml/hifi/AssetServer.qml
  interface/resources/qml/hifi/dialogs/TabletAssetServer.qml
  interface/src/Application.cpp
  libraries/entities/src/EntityScriptingInterface.cpp
  libraries/entities/src/EntityScriptingInterface.h
  scripts/system/edit.js
Labels: Content/Create, Development Approved, QA Approved :tada:

#12528 Animation Unit Tests build and pass
  tests/animation/src/AnimInverseKinematicsTests.cpp
  tests/animation/src/AnimTests.cpp
  tests/animation/src/RigTests.cpp
  tests/animation/src/RigTests.h
Labels: Avatar, Development Approved

#12534 workload: clear orphaned workload::Space proxies when leaving domain
  assignment-client/src/entities/EntityTreeHeadlessViewer.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/EntityTree.h
  libraries/workload/src/workload/Space.cpp
  libraries/workload/src/workload/Space.h
Labels: Development Approved, Engine

#12512 update fs-extra for dependency update of brace-expansion
  server-console/package-lock.json
  server-console/package.json
Labels: Development Approved, QA Approved :tada:

#12521 if a node can't change locks, don't allow it to create an already-locked entity
  libraries/entities/src/EntityTree.cpp
Labels: Client, Development Approved, QA Approved :tada:

#12532 RC65 Fix: Applying the fix for shadows and transitions on Dual Quat Skinned meshes
  libraries/render-utils/src/RenderPipelines.cpp
  libraries/render-utils/src/RenderShadowTask.cpp
  libraries/render-utils/src/skin_model_normal_map_fade_dq.slv
  libraries/render/src/render/ShapePipeline.h
Labels: Development Approved, Engine, QA Approved :tada:, Release Blocker

#12542 RC65: Fix undefined request from JS
  scripts/modules/request.js
Labels: QA Approved :tada:, bug, disco-free

#12538 Fix Edit -> Export Entities exporting gzipped json
  libraries/octree/src/Octree.cpp
  libraries/octree/src/Octree.h
  libraries/octree/src/OctreePersistThread.cpp
Labels: Content/Create, Development Approved, QA Approved :tada:, bug

#12544 Disable virtual trackpad rendering on non-Android builds
  libraries/display-plugins/src/display-plugins/Basic2DWindowOpenGLDisplayPlugin.cpp
  libraries/display-plugins/src/display-plugins/Basic2DWindowOpenGLDisplayPlugin.h
Labels: Development Approved, QA Approved :tada:

#12537 Fix undefined request from JS
  scripts/modules/request.js
Labels: QA Approved :tada:, bug, disco-free

#12543 Improve font loading via QRC instead of file path
  interface/resources/qml/CurrentAPI.qml
  interface/resources/qml/controls-uit/CheckBoxQQC2.qml
  interface/resources/qml/controls-uit/Keyboard.qml
  interface/resources/qml/controls-uit/SpinBox.qml
  interface/resources/qml/controls-uit/TextEdit.qml
  interface/resources/qml/controls-uit/TextField.qml
  interface/resources/qml/controls-uit/qmldir
  interface/resources/qml/controls/FontAwesome.qml
  interface/resources/qml/dialogs/FileDialog.qml
  interface/resources/qml/dialogs/TabletFileDialog.qml
  interface/resources/qml/dialogs/assetDialog/AssetDialogContent.qml
  interface/resources/qml/hifi/AssetServer.qml
  interface/resources/qml/hifi/ComboDialog.qml
  interface/resources/qml/hifi/DesktopLetterboxMessage.qml
  interface/resources/qml/hifi/LetterboxMessage.qml
  interface/resources/qml/hifi/NameCard.qml
  interface/resources/qml/hifi/Pal.qml
  interface/resources/qml/hifi/commerce/common/EmulatedMarketplaceHeader.qml
  interface/resources/qml/hifi/commerce/wallet/sendMoney/SendMoney.qml
  interface/resources/qml/hifi/dialogs/TabletAssetServer.qml
  interface/resources/qml/hifi/tablet/tabletWindows/TabletFileDialog.qml
  interface/resources/qml/styles-uit/AnonymousProRegular.qml
  interface/resources/qml/styles-uit/FiraSansRegular.qml
  interface/resources/qml/styles-uit/FiraSansSemiBold.qml
  interface/resources/qml/styles-uit/HiFiGlyphs.qml
  interface/resources/qml/styles-uit/RalewayBold.qml
  interface/resources/qml/styles-uit/RalewayLight.qml
  interface/resources/qml/styles-uit/RalewayRegular.qml
  interface/resources/qml/styles-uit/RalewaySemiBold.qml
  interface/resources/qml/styles-uit/qmldir
  interface/src/ui/overlays/Web3DOverlay.cpp
  libraries/ui/src/ui/OffscreenQmlSurface.cpp
Labels: Development Approved, HMD required, QA Approved :tada:, disco-free

#12531 Purge RayPick and LaserPointers from default scripts
  scripts/system/controllers/controllerDispatcher.js
  scripts/system/controllers/controllerModules/farActionGrabEntity.js
  scripts/system/controllers/controllerModules/farTrigger.js
  scripts/system/controllers/controllerModules/hudOverlayPointer.js
  scripts/system/controllers/controllerModules/inEditMode.js
  scripts/system/controllers/controllerModules/teleport.js
  scripts/system/controllers/controllerModules/webSurfaceLaserInput.js
  scripts/system/controllers/grab.js
Labels: Client, Development Approved, QA Approved :tada:

#12530 Fixing the graphics bugs introduced since last recent dual quaternion change
  libraries/render-utils/src/RenderPipelines.cpp
  libraries/render-utils/src/RenderShadowTask.cpp
  libraries/render-utils/src/skin_model_normal_map_fade_dq.slv
  libraries/render/src/render/ShapePipeline.h
Labels: Development Approved, Engine, QA Approved :tada:

#12546 Fix hyperlink when far/near grabbing enitities
  interface/src/Application.cpp
  scripts/system/controllers/controllerModules/farActionGrabEntity.js
  scripts/system/controllers/controllerModules/nearGrabHyperLinkEntity.js
  scripts/system/controllers/controllerScripts.js
  scripts/system/libraries/controllerDispatcherUtils.js
Labels: Client, Development Approved, QA Approved :tada:

#12547 Protect session UUID from concurrent read/writes
  domain-server/src/DomainServer.cpp
  domain-server/src/DomainServer.h
  libraries/networking/src/LimitedNodeList.cpp
  libraries/networking/src/LimitedNodeList.h
  libraries/networking/src/NodeList.cpp
Labels: Development Approved, QA Approved :tada:, Server & Network

#12555 fix controllerDispatcher error in logs
  scripts/system/controllers/controllerDispatcher.js
Labels: Client, Development Approved, QA Approved :tada:

#12533 Adding Stereo checkbox in Audio settings
  interface/resources/qml/hifi/audio/Audio.qml
  libraries/audio-client/src/AudioClient.cpp
  libraries/audio-client/src/AudioClient.h
  libraries/audio/src/AbstractAudioInterface.h
  libraries/script-engine/src/AudioScriptingInterface.cpp
  libraries/script-engine/src/AudioScriptingInterface.h
Labels: Client, Development Approved, QA Approved :tada:

#12557 correctly use default values and don't delete userData in entitiesProperties.js
  scripts/system/html/js/entityProperties.js
Labels: Client, Content/Create, Development Approved, QA Approved :tada:

#12550 FIX: make the grabbable checkbox function again when dynamic disabled
  scripts/system/html/js/entityProperties.js
Labels: Content/Create, Critical Fix, Development Approved, QA Approved :tada:

#12567 Added fixed log spam undefined error to RC65
  scripts/system/libraries/entitySelectionTool.js
Labels: QA Approved :tada:

#12491 fix for not re-enabling preview on leaving security-sensitive pages in marketplace
  interface/resources/qml/hifi/commerce/wallet/PassphraseModal.qml
  interface/resources/qml/hifi/commerce/wallet/Wallet.qml
  scripts/system/marketplaces/marketplaces.js
Labels: Development Approved, QA Approved :tada:, outsource

#12582 fix JSDOC typo rule -> role
  interface/src/avatar/MyAvatar.h
Labels: Development Approved, QA Approved :tada:

#12548 Prevent crash during long backup web requests
  domain-server/src/DomainServer.cpp
Labels: Development Approved, QA Approved :tada:, Release Blocker, Server & Network

#12573 fix for getSetting QVariant ref in DomainServer
  domain-server/src/DomainServer.cpp
Labels: Development Approved, QA Approved :tada:, Server & Network

#12447 use QCoreApplication for Oven when headless version is used
  tools/oven/src/BakerCLI.cpp
  tools/oven/src/BakerCLI.h
  tools/oven/src/DomainBaker.cpp
  tools/oven/src/Oven.cpp
  tools/oven/src/Oven.h
  tools/oven/src/OvenCLIApplication.cpp
  tools/oven/src/OvenCLIApplication.h
  tools/oven/src/OvenGUIApplication.cpp
  tools/oven/src/OvenGUIApplication.h
  tools/oven/src/main.cpp
  tools/oven/src/ui/BakeWidget.cpp
  tools/oven/src/ui/DomainBakeWidget.cpp
  tools/oven/src/ui/ModelBakeWidget.cpp
  tools/oven/src/ui/SkyboxBakeWidget.cpp
Labels: Development Approved, QA Approved :tada:, Server & Network

#12515 Material reflection
  interface/src/ui/overlays/ModelOverlay.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities-renderer/src/RenderableShapeEntityItem.cpp
  libraries/gpu/src/gpu/Texture.cpp
  libraries/gpu/src/gpu/Texture.h
  libraries/graphics-scripting/CMakeLists.txt
  libraries/graphics-scripting/src/graphics-scripting/Forward.h
  libraries/graphics-scripting/src/graphics-scripting/GraphicsScriptingInterface.cpp
  libraries/graphics-scripting/src/graphics-scripting/ScriptableMesh.cpp
  libraries/graphics-scripting/src/graphics-scripting/ScriptableModel.cpp
  libraries/graphics-scripting/src/graphics-scripting/ScriptableModel.h
  libraries/graphics/src/graphics/Material.h
  libraries/model-networking/src/model-networking/MaterialCache.cpp
  libraries/model-networking/src/model-networking/TextureCache.cpp
  libraries/render-utils/src/CauterizedModel.cpp
  libraries/render-utils/src/Model.cpp
Labels: Content/Create, Development Approved, Engine, QA Approved :tada:

#12579 Fix for avatar record only replaying once
  libraries/networking/src/udt/Connection.cpp
Labels: Development Approved, QA Approved :tada:, Server & Network

#12594 Workload: update with upstream master
  domain-server/src/DomainServer.cpp
  interface/resources/qml/Stats.qml
  interface/resources/qml/hifi/audio/Audio.qml
  interface/resources/qml/hifi/commerce/wallet/PassphraseModal.qml
  interface/resources/qml/hifi/commerce/wallet/Wallet.qml
  interface/src/avatar/MyAvatar.h
  interface/src/ui/Stats.cpp
  interface/src/ui/Stats.h
  interface/src/ui/overlays/ModelOverlay.cpp
  libraries/audio-client/src/AudioClient.cpp
  libraries/audio-client/src/AudioClient.h
  libraries/audio/src/AbstractAudioInterface.h
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities-renderer/src/RenderableShapeEntityItem.cpp
  libraries/gpu/src/gpu/Texture.cpp
  libraries/gpu/src/gpu/Texture.h
  libraries/graphics-scripting/CMakeLists.txt
  libraries/graphics-scripting/src/graphics-scripting/Forward.h
  libraries/graphics-scripting/src/graphics-scripting/GraphicsScriptingInterface.cpp
  libraries/graphics-scripting/src/graphics-scripting/ScriptableMesh.cpp
  libraries/graphics-scripting/src/graphics-scripting/ScriptableModel.cpp
  libraries/graphics-scripting/src/graphics-scripting/ScriptableModel.h
  libraries/graphics/src/graphics/Material.h
  libraries/model-networking/src/model-networking/MaterialCache.cpp
  libraries/model-networking/src/model-networking/TextureCache.cpp
  libraries/networking/src/udt/Connection.cpp
  libraries/octree/src/Octree.cpp
  libraries/octree/src/Octree.h
  libraries/octree/src/OctreePersistThread.cpp
  libraries/render-utils/src/CauterizedModel.cpp
  libraries/render-utils/src/Model.cpp
  libraries/script-engine/src/AudioScriptingInterface.cpp
  libraries/script-engine/src/AudioScriptingInterface.h
  scripts/system/controllers/controllerDispatcher.js
  scripts/system/html/js/entityProperties.js
  scripts/system/marketplaces/marketplaces.js
  tools/oven/src/BakerCLI.cpp
  tools/oven/src/BakerCLI.h
  tools/oven/src/DomainBaker.cpp
  tools/oven/src/Oven.cpp
  tools/oven/src/Oven.h
  tools/oven/src/OvenCLIApplication.cpp
  tools/oven/src/OvenCLIApplication.h
  tools/oven/src/OvenGUIApplication.cpp
  tools/oven/src/OvenGUIApplication.h
  tools/oven/src/main.cpp
  tools/oven/src/ui/BakeWidget.cpp
  tools/oven/src/ui/DomainBakeWidget.cpp
  tools/oven/src/ui/ModelBakeWidget.cpp
  tools/oven/src/ui/SkyboxBakeWidget.cpp
Labels: Engine

#12595 Workload: Fixing a bug in RegionState and more ui to debug the Regions of the view
  libraries/render-utils/src/RenderDeferredTask.cpp
  libraries/workload/src/workload/RegionState.cpp
  libraries/workload/src/workload/View.cpp
  libraries/workload/src/workload/View.h
  libraries/workload/src/workload/ViewTask.cpp
  libraries/workload/src/workload/ViewTask.h
  scripts/developer/utilities/workload/workload.qml
Labels: Engine

#12591 Don't default unknown Marketplace item types to 'Entity'
  interface/resources/qml/hifi/commerce/checkout/Checkout.qml
Labels: Commerce, Development Approved, QA Approved :tada:, bug, disco-free

#12482 Add a Q_DECLARE_METATYPE in TextureCache.
  libraries/model-networking/src/model-networking/TextureCache.h
Labels: Development Approved, Engine, QA Approved :tada:

#12583 Fix Local lights not showing anymore
  libraries/render-utils/src/RenderDeferredTask.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#12572 Show Connection instructions in Send Money when 0 connections
  interface/resources/qml/hifi/commerce/wallet/sendMoney/SendMoney.qml
Labels: Commerce, Development Approved, HMD required, QA Approved :tada:, disco-free

#12570 Redo entity scale handles to fix scaling into avatars causing undesirable physics/dimensions
  scripts/system/libraries/entitySelectionTool.js
Labels: Content/Create, Development Approved, QA Approved :tada:

#12580 Fixed blocks importer textures being interpreted as image entities
  interface/src/Application.cpp
  interface/src/Application.h
  libraries/script-engine/src/FileScriptingInterface.cpp
  libraries/script-engine/src/FileScriptingInterface.h
Labels: Content/Create, Development Approved, QA Approved :tada:

#12558 Shadow control for zones, models and shapes
  interface/resources/qml/hifi/dialogs/GraphicsPreferencesDialog.qml
  interface/src/Menu.cpp
  interface/src/Menu.h
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  libraries/entities-renderer/src/RenderableEntityItem.cpp
  libraries/entities-renderer/src/RenderableEntityItem.h
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities-renderer/src/RenderableZoneEntityItem.cpp
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityItemPropertiesDefaults.h
  libraries/entities/src/EntityPropertyFlags.h
  libraries/entities/src/KeyLightPropertyGroup.cpp
  libraries/entities/src/KeyLightPropertyGroup.h
  libraries/graphics/src/graphics/Light.cpp
  libraries/graphics/src/graphics/Light.h
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
  libraries/render-utils/src/CauterizedModel.cpp
  libraries/render-utils/src/DeferredLightingEffect.cpp
  libraries/render-utils/src/DeferredLightingEffect.h
  libraries/render-utils/src/MeshPartPayload.cpp
  libraries/render-utils/src/MeshPartPayload.h
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
  libraries/render-utils/src/RenderShadowTask.cpp
  libraries/render-utils/src/RenderShadowTask.h
  scripts/system/html/entityProperties.html
  scripts/system/html/js/entityProperties.js
Labels: Content/Create, Development Approved, Engine, Packet Version Change, QA Ready, Scripting API change

#12599 RC65: Don't hit certain Commerce backend endpoints when wallet isn't yet auth'd
  interface/src/commerce/Ledger.cpp
Labels: Commerce, Development Approved, QA Approved :tada:, bug, disco-free

#12585 tablet scale and position changes
  interface/src/Application.cpp
  scripts/system/libraries/WebTablet.js
  scripts/system/libraries/utils.js
  scripts/system/tablet-ui/tabletUI.js
Labels: Client, Development Approved, QA Approved :tada:

#12536 Remove deprecated Window.openFileChanged() signal from API
  interface/src/scripting/WindowScriptingInterface.cpp
  interface/src/scripting/WindowScriptingInterface.h
Labels: Content/Create, Development Approved, QA Approved :tada:

#12472 [Case 4315] Resolves Particle Tab Color Picker visual inconstency
  scripts/system/particle_explorer/hifi-entity-ui.js
  scripts/system/particle_explorer/particleExplorer.html
  scripts/system/particle_explorer/particleExplorer.js
Labels: Content/Create, Development Approved, QA Approved :tada:, outsource

#12539 Remove deprecated Window.location.protocolVersion() function from API
  libraries/networking/src/AddressManager.cpp
  libraries/networking/src/AddressManager.h
Labels: Content/Create, Development Approved, QA Approved :tada:

#12596 Fix font loading for MacOS via completely different font loading method
  interface/resources/qml/CurrentAPI.qml
  interface/resources/qml/controls-uit/CheckBoxQQC2.qml
  interface/resources/qml/controls-uit/Keyboard.qml
  interface/resources/qml/controls-uit/SpinBox.qml
  interface/resources/qml/controls-uit/TextEdit.qml
  interface/resources/qml/controls-uit/TextField.qml
  interface/resources/qml/controls/FontAwesome.qml
  interface/resources/qml/dialogs/FileDialog.qml
  interface/resources/qml/dialogs/TabletFileDialog.qml
  interface/resources/qml/dialogs/assetDialog/AssetDialogContent.qml
  interface/resources/qml/hifi/AssetServer.qml
  interface/resources/qml/hifi/ComboDialog.qml
  interface/resources/qml/hifi/DesktopLetterboxMessage.qml
  interface/resources/qml/hifi/LetterboxMessage.qml
  interface/resources/qml/hifi/NameCard.qml
  interface/resources/qml/hifi/Pal.qml
  interface/resources/qml/hifi/commerce/common/EmulatedMarketplaceHeader.qml
  interface/resources/qml/hifi/commerce/wallet/sendMoney/SendMoney.qml
  interface/resources/qml/hifi/dialogs/TabletAssetServer.qml
  interface/resources/qml/hifi/tablet/tabletWindows/TabletFileDialog.qml
  interface/resources/qml/styles-uit/AnonymousProRegular.qml
  interface/resources/qml/styles-uit/FiraSansRegular.qml
  interface/resources/qml/styles-uit/FiraSansSemiBold.qml
  interface/resources/qml/styles-uit/HiFiGlyphs.qml
  interface/resources/qml/styles-uit/RalewayBold.qml
  interface/resources/qml/styles-uit/RalewayLight.qml
  interface/resources/qml/styles-uit/RalewayRegular.qml
  interface/resources/qml/styles-uit/RalewaySemiBold.qml
  interface/src/Application.cpp
Labels: Development Approved, HMD required, Mac Required, QA Approved :tada:, bug

#12602 RC65: Fix font loading for MacOS via completely different font loading method
  interface/resources/qml/CurrentAPI.qml
  interface/resources/qml/controls-uit/CheckBoxQQC2.qml
  interface/resources/qml/controls-uit/Keyboard.qml
  interface/resources/qml/controls-uit/SpinBox.qml
  interface/resources/qml/controls-uit/TextEdit.qml
  interface/resources/qml/controls-uit/TextField.qml
  interface/resources/qml/controls/FontAwesome.qml
  interface/resources/qml/dialogs/FileDialog.qml
  interface/resources/qml/dialogs/TabletFileDialog.qml
  interface/resources/qml/dialogs/assetDialog/AssetDialogContent.qml
  interface/resources/qml/hifi/AssetServer.qml
  interface/resources/qml/hifi/ComboDialog.qml
  interface/resources/qml/hifi/DesktopLetterboxMessage.qml
  interface/resources/qml/hifi/LetterboxMessage.qml
  interface/resources/qml/hifi/NameCard.qml
  interface/resources/qml/hifi/Pal.qml
  interface/resources/qml/hifi/commerce/common/EmulatedMarketplaceHeader.qml
  interface/resources/qml/hifi/commerce/wallet/sendMoney/SendMoney.qml
  interface/resources/qml/hifi/dialogs/TabletAssetServer.qml
  interface/resources/qml/hifi/tablet/tabletWindows/TabletFileDialog.qml
  interface/resources/qml/styles-uit/AnonymousProRegular.qml
  interface/resources/qml/styles-uit/FiraSansRegular.qml
  interface/resources/qml/styles-uit/FiraSansSemiBold.qml
  interface/resources/qml/styles-uit/HiFiGlyphs.qml
  interface/resources/qml/styles-uit/RalewayBold.qml
  interface/resources/qml/styles-uit/RalewayLight.qml
  interface/resources/qml/styles-uit/RalewayRegular.qml
  interface/resources/qml/styles-uit/RalewaySemiBold.qml
  interface/src/Application.cpp
Labels: Development Approved, HMD required, Mac Required, QA Approved :tada:, bug, disco-free

#12603 clear wallet when picking a new one
  interface/resources/qml/hifi/commerce/wallet/Wallet.qml
  interface/src/commerce/QmlCommerce.cpp
  interface/src/commerce/QmlCommerce.h
  interface/src/commerce/Wallet.cpp
  interface/src/commerce/Wallet.h
Labels: Commerce, Development Approved, QA Approved :tada:, bug, disco-free

#12601 clear wallet when picking a new one
  interface/resources/qml/hifi/commerce/wallet/Wallet.qml
  interface/src/commerce/QmlCommerce.cpp
  interface/src/commerce/QmlCommerce.h
  interface/src/commerce/Wallet.cpp
  interface/src/commerce/Wallet.h
Labels: Commerce, Development Approved, QA Approved :tada:, bug, disco-free

#12606 Fix for broken 'toggle audio meter' button
  interface/resources/qml/AvatarInputsBar.qml
  interface/src/Application.cpp
  interface/src/ui/AvatarInputs.cpp
  interface/src/ui/AvatarInputs.h
Labels: Client, Development Approved, QA Approved :tada:, bug

#12496 faster per-entity raypick culling and time-boxed picks
  interface/src/raypick/PickScriptingInterface.cpp
  interface/src/raypick/PickScriptingInterface.h
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.h
  libraries/entities-renderer/src/RenderablePolyVoxEntityItem.cpp
  libraries/entities-renderer/src/RenderablePolyVoxEntityItem.h
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/entities/src/EntityTreeElement.cpp
  libraries/entities/src/EntityTreeElement.h
  libraries/entities/src/LightEntityItem.cpp
  libraries/entities/src/LightEntityItem.h
  libraries/entities/src/LineEntityItem.h
  libraries/entities/src/PolyLineEntityItem.h
  libraries/entities/src/PolyVoxEntityItem.h
  libraries/entities/src/ShapeEntityItem.cpp
  libraries/entities/src/ShapeEntityItem.h
  libraries/entities/src/TextEntityItem.cpp
  libraries/entities/src/TextEntityItem.h
  libraries/entities/src/WebEntityItem.cpp
  libraries/entities/src/WebEntityItem.h
  libraries/entities/src/ZoneEntityItem.cpp
  libraries/entities/src/ZoneEntityItem.h
  libraries/pointers/src/PickCacheOptimizer.h
  libraries/pointers/src/PickManager.cpp
  libraries/pointers/src/PickManager.h
  libraries/shared/src/AABox.cpp
  libraries/shared/src/AABox.h
Labels: Development Approved, Engine, QA Approved :tada:

#12578 use correct scripting api for audio in Audio.qml
  interface/resources/qml/hifi/audio/Audio.qml
  libraries/audio-client/src/AudioClient.h
  libraries/audio/src/AbstractAudioInterface.h
  libraries/script-engine/src/AudioScriptingInterface.cpp
  libraries/script-engine/src/AudioScriptingInterface.h
Labels: Client, Development Approved, QA Approved :tada:

#12614 Loghandler
  libraries/shared/src/LogHandler.cpp
  libraries/shared/src/LogHandler.h
Labels: Development Approved, QA Ready

#12554 Pull test images from GitHub
  tools/auto-tester/CMakeLists.txt
  tools/auto-tester/src/Downloader.cpp
  tools/auto-tester/src/Downloader.h
  tools/auto-tester/src/ImageComparer.cpp
  tools/auto-tester/src/Test.cpp
  tools/auto-tester/src/Test.h
  tools/auto-tester/src/main.cpp
  tools/auto-tester/src/ui/AutoTester.cpp
  tools/auto-tester/src/ui/AutoTester.h
  tools/auto-tester/src/ui/AutoTester.ui
Labels: Engine, Feedback Welcome

#12613 Correct can cast shadow flag being visible on entities that can't cast shadows
  scripts/system/html/entityProperties.html
Labels: Content/Create, Development Approved, Engine, QA Approved :tada:, bug

#12617 Fix shadow: other avatars casting shadow, graphics settings checkboxes & menu layout
  interface/src/Menu.cpp
  interface/src/Menu.h
  interface/src/avatar/MyAvatar.cpp
  interface/src/ui/PreferencesDialog.cpp
  libraries/avatars-renderer/src/avatars-renderer/SkeletonModel.cpp
Labels: Development Approved, Engine, QA Approved :tada:, bug

#12608 Update Hifi icon for android
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/drawable/ic_launcher.xml
  android/app/src/main/res/drawable/icon.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
Labels: Android, Development Approved, QA Approved :tada:

#12616 Mitigation of Manuscript issue 12435
  libraries/physics/src/CharacterController.cpp
Labels: Avatar, Development Approved, Engine, QA Approved :tada:

#12526 Entities API JSDoc
  interface/src/avatar/AvatarActionFarGrab.h
  interface/src/avatar/AvatarActionHold.cpp
  interface/src/ui/overlays/Overlays.h
  interface/src/ui/overlays/Shape3DOverlay.cpp
  libraries/entities-renderer/src/RenderableZoneEntityItem.cpp
  libraries/entities/src/AmbientLightPropertyGroup.h
  libraries/entities/src/AnimationPropertyGroup.cpp
  libraries/entities/src/EntityDynamicInterface.cpp
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityScriptingInterface.cpp
  libraries/entities/src/EntityScriptingInterface.h
  libraries/entities/src/EntityTypes.h
  libraries/entities/src/HazePropertyGroup.h
  libraries/entities/src/KeyLightPropertyGroup.h
  libraries/entities/src/PolyVoxEntityItem.h
  libraries/entities/src/ShapeEntityItem.cpp
  libraries/entities/src/ShapeEntityItem.h
  libraries/entities/src/SkyboxPropertyGroup.h
  libraries/graphics-scripting/src/graphics-scripting/GraphicsScriptingInterface.h
  libraries/model-networking/src/model-networking/MaterialCache.cpp
  libraries/octree/src/OctreeScriptingInterface.h
  libraries/physics/src/ObjectActionOffset.cpp
  libraries/physics/src/ObjectActionTractor.cpp
  libraries/physics/src/ObjectActionTravelOriented.cpp
  libraries/physics/src/ObjectConstraintBallSocket.cpp
  libraries/physics/src/ObjectConstraintConeTwist.cpp
  libraries/physics/src/ObjectConstraintHinge.cpp
  libraries/physics/src/ObjectConstraintSlider.cpp
  libraries/physics/src/ObjectDynamic.cpp
  libraries/physics/src/ObjectMotionState.h
  libraries/render-utils/src/GeometryCache.cpp
  libraries/script-engine/src/Quat.h
  libraries/script-engine/src/Vec3.h
  libraries/shared/src/PhysicsCollisionGroups.h
  libraries/shared/src/RegisteredMetaTypes.cpp
  libraries/shared/src/RegisteredMetaTypes.h
  libraries/shared/src/ShapeInfo.cpp
  libraries/ui/src/ui/TabletScriptingInterface.h
  scripts/developer/tests/dynamics/dynamicsTests.js
  tools/jsdoc/plugins/hifi.js
Labels: Content/Create, Development Approved, QA Approved :tada:, outsource

#12621 Fix CPU and GPU not throttling when Interface minimized from maximized
  libraries/ui/src/MainWindow.cpp
Labels: Client, Development Approved, QA Approved :tada:

#12553 Fix CheckBox on Mac
  interface/resources/qml/controls-uit/CheckBox.qml
Labels: Client, Development Approved, QA Approved :tada:, outsource

#12623 Android: Fix corruption on startup
  BUILD_ANDROID.md
  interface/CMakeLists.txt
  interface/resources/qml/+android/AddressBarDialog.qml
  interface/resources/qml/hifi/+android/AvatarOption.qml
  interface/resources/qml/hifi/+android/HifiConstants.qml
  interface/src/Application.cpp
  interface/src/Application.h
  libraries/display-plugins/src/display-plugins/Basic2DWindowOpenGLDisplayPlugin.cpp
  libraries/display-plugins/src/display-plugins/CompositorHelper.h
  libraries/input-plugins/src/input-plugins/TouchscreenVirtualPadDevice.cpp
  libraries/shared/src/shared/Storage.cpp
  libraries/ui/src/VirtualPadManager.cpp
  libraries/ui/src/VirtualPadManager.h
Labels: Android, Development Approved, QA Approved :tada:

#12615 Fix local KTX files never being removed from pending downloads
  libraries/model-networking/src/model-networking/TextureCache.cpp
  libraries/model-networking/src/model-networking/TextureCache.h
Labels: Development Approved, Engine, QA Approved :tada:

#12626 Android hifi audio codec
  android/build.gradle
  interface/resources/qml/windows/Frame.qml
  libraries/plugins/src/plugins/PluginManager.cpp
  libraries/qml/src/qml/OffscreenSurface.cpp
Labels: Android, Development Approved, QA Approved :tada:

#12586 Fix crash when closing the Audio menu
  libraries/audio-client/src/AudioPeakValues.cpp
Labels: Client, Critical Fix, Development Approved, QA Approved :tada:, bug

#12620 Fix rotation and position of avatar meshes attached to eye joints
  libraries/animation/src/AnimSkeleton.cpp
  libraries/animation/src/AnimSkeleton.h
  libraries/animation/src/Rig.cpp
  libraries/animation/src/Rig.h
Labels: Avatar, Development Approved, QA Approved :tada:

#12529 Fix NVTT for mac
  cmake/externals/nvtt/CMakeLists.txt
Labels: Development Approved, Mac Required, QA Ready

#12631 Apply TAA to text and web entities/overlays
  interface/src/ui/overlays/Text3DOverlay.cpp
  libraries/entities-renderer/src/RenderableTextEntityItem.cpp
  libraries/render-utils/src/GeometryCache.cpp
  libraries/render-utils/src/GeometryCache.h
  libraries/render-utils/src/text/Font.cpp
Labels: Development Approved, Engine, HMD required, Mac Required, QA Approved :tada:

#12633 Fix HUD sphere rendering after TAA changes
  libraries/render-utils/src/RenderCommonTask.cpp
Labels: Development Approved, HMD required, QA Approved :tada:, bug

#12642 Change default mode to My View in Android
  scripts/system/+android/modes.js
Labels: Android, Development Approved, QA Approved :tada:

#12643 Possible fix for keyboard crash
  libraries/qml/src/qml/OffscreenSurface.cpp
Labels: Android, Development Approved, QA Approved :tada:

#12636 Workload: Applying the transaction model to the Space & Proxies
  interface/src/workload/GameWorkloadRenderer.cpp
  interface/src/workload/GameWorkloadRenderer.h
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.h
  libraries/workload/src/workload/Engine.cpp
  libraries/workload/src/workload/Engine.h
  libraries/workload/src/workload/Proxy.h
  libraries/workload/src/workload/Space.cpp
  libraries/workload/src/workload/Space.h
  libraries/workload/src/workload/Transaction.cpp
  libraries/workload/src/workload/Transaction.h
Labels: Engine

#12619 Improved audio quality for streaming music
  libraries/audio/src/AudioSRCData.h
Labels: QA Approved :tada:

#12640 Don't leave trash web processes when changing web entity urls
  libraries/entities-renderer/src/RenderableWebEntityItem.cpp
  libraries/entities-renderer/src/RenderableWebEntityItem.h
Labels: Development Approved, QA Approved :tada:, bug

#12645 Rename getpos3
  libraries/graphics/src/graphics/Geometry.h
  libraries/model-networking/src/model-networking/SimpleMeshProxy.cpp
  libraries/model-networking/src/model-networking/SimpleMeshProxy.h
  libraries/shared/src/RegisteredMetaTypes.h
Labels: Client, Development Approved, QA Approved :tada:

#12658 Stable merge back into master
  interface/resources/qml/AvatarInputsBar.qml
  interface/src/Application.cpp
  interface/src/ui/AvatarInputs.cpp
  interface/src/ui/AvatarInputs.h
Labels: Development Approved, Stable Mergeback

#12655 Fix for hand IK jitter
  libraries/animation/src/ElbowConstraint.cpp
Labels: Avatar, Development Approved, QA Approved :tada:

#11860 OBJ Baking
  libraries/baking/src/FBXBaker.cpp
  libraries/baking/src/FBXBaker.h
  libraries/baking/src/ModelBaker.cpp
  libraries/baking/src/ModelBaker.h
  libraries/baking/src/OBJBaker.cpp
  libraries/baking/src/OBJBaker.h
  libraries/fbx/src/FBXWriter.cpp
  libraries/fbx/src/OBJReader.cpp
  libraries/fbx/src/OBJReader.h
  libraries/model-networking/src/model-networking/ModelCache.cpp
  libraries/networking/src/ResourceManager.cpp
  libraries/networking/src/ResourceManager.h
  tools/oven/src/DomainBaker.cpp
  tools/oven/src/DomainBaker.h
  tools/oven/src/Oven.cpp
  tools/oven/src/Oven.h
  tools/oven/src/ui/BakeWidget.cpp
  tools/oven/src/ui/ModelBakeWidget.cpp
  tools/oven/src/ui/ModelBakeWidget.h
  tools/oven/src/ui/OvenMainWindow.cpp
  tools/vhacd-util/src/VHACDUtil.cpp
Labels: Development Approved, QA Approved :tada:

#12670 RC65 Hotfix: Model behaves correctly if missing material
  libraries/render-utils/src/MeshPartPayload.cpp
  libraries/render-utils/src/MeshPartPayload.h
  libraries/render-utils/src/Model.cpp
Labels: Critical Fix, Development Approved, Engine, QA Approved :tada:, bug

#12593 Android joystick rotate move
  interface/resources/controllers/touchscreenvirtualpad.json
  interface/resources/qml/+android/LoginDialog.qml
  interface/resources/qml/LoginDialog/+android/LinkAccountBody.qml
  libraries/input-plugins/src/input-plugins/InputPlugin.cpp
  libraries/input-plugins/src/input-plugins/TouchscreenVirtualPadDevice.cpp
  libraries/input-plugins/src/input-plugins/TouchscreenVirtualPadDevice.h
  scripts/system/+android/avatarSelection.js
Labels: Android, Development Approved, QA Approved :tada:

#12673 Fix DS settings issues on IE and Edge
  domain-server/resources/web/js/shared.js
  domain-server/src/DomainServer.cpp
  libraries/embedded-webserver/src/HTTPConnection.cpp
  libraries/embedded-webserver/src/HTTPConnection.h
Labels: Development Approved, QA Approved :tada:

#12678 RC65.1: Fix ray cast checks on tablet ID lists in edit.js
  scripts/system/edit.js
Labels: Content/Create, Development Approved, QA Approved :tada:

#12667 HOTFIX RC65: Fix invalid QML surface cache interaction
  interface/src/ui/overlays/Web3DOverlay.cpp
  interface/src/ui/overlays/Web3DOverlay.h
  scripts/developer/tests/webOverlayTool.js
Labels: Critical Fix, Development Approved, QA Approved :tada:, bug

#12650 Messages API JSDoc
  libraries/networking/src/MessagesClient.h
  scripts/developer/tests/messagesTests.js
Labels: Content/Create, Development Approved, QA Approved :tada:, outsource

#12651 Fix "text" overlay not clipping to right and bottom margins
  interface/resources/qml/hifi/overlays/TextOverlay.qml
  interface/src/ui/overlays/TextOverlay.cpp
Labels: Development Approved, QA Approved :tada:

#12654 Add support for .content.zip content uploads
  cmake/externals/quazip/CMakeLists.txt
  domain-server/src/DomainServer.cpp
  domain-server/src/DomainServer.h
  interface/src/Application.cpp
  interface/src/Application.h
  libraries/networking/src/udt/PacketHeaders.h
Labels: Development Approved, QA Approved :tada:

#12664 Android - Prevent crash when setting the url property to _webSurface.
  libraries/entities-renderer/src/RenderableWebEntityItem.cpp
Labels: Android, Development Approved, QA Approved :tada:

#12644 Add Google Analytics to installer
  INSTALL.md
  cmake/macros/SetPackagingParameters.cmake
  cmake/templates/CPackProperties.cmake.in
  cmake/templates/NSIS.template.in
Labels: Development Approved, QA Approved :tada:, Server & Network

#12524 switch back to app-local VC runtimes and UCRT
  CMakeLists.txt
  cmake/macros/GenerateInstallers.cmake
  cmake/macros/PackageLibrariesForDeployment.cmake
  cmake/templates/NSIS.template.in
  interface/CMakeLists.txt
  libraries/render-utils/CMakeLists.txt
  plugins/CMakeLists.txt
Labels: Development Approved, QA Approved :tada:, Server & Network

#12680 Support relative paths for material images
  libraries/entities/src/MaterialEntityItem.cpp
  libraries/model-networking/src/model-networking/MaterialCache.cpp
  libraries/model-networking/src/model-networking/MaterialCache.h
  libraries/model-networking/src/model-networking/ModelCache.cpp
  libraries/model-networking/src/model-networking/ModelCache.h
Labels: Development Approved, Engine, QA Approved :tada:

#12666 Fix invalid QML surface cache interaction
  interface/src/ui/overlays/Web3DOverlay.cpp
  interface/src/ui/overlays/Web3DOverlay.h
  scripts/developer/tests/webOverlayTool.js
Labels: Development Approved, Engine, QA Approved :tada:

#12675 Model behaves correctly if missing material
  libraries/render-utils/src/MeshPartPayload.cpp
  libraries/render-utils/src/MeshPartPayload.h
  libraries/render-utils/src/Model.cpp
Labels: Engine, QA Approved :tada:, bug

#12639 Use correct platform-specific gpu library
  plugins/oculus/CMakeLists.txt
  tests/render-perf/CMakeLists.txt
Labels: Development Approved, Engine, Mac Required, QA Approved :tada:

#12635 Fix Window hasFocus(), setFocus(), and raiseMainWindow()
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/scripting/WindowScriptingInterface.cpp
  interface/src/scripting/WindowScriptingInterface.h
  libraries/display-plugins/src/display-plugins/NullDisplayPlugin.cpp
  libraries/display-plugins/src/display-plugins/NullDisplayPlugin.h
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.cpp
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.h
  libraries/plugins/src/plugins/DisplayPlugin.h
Labels: Client, Content/Create, Development Approved, QA Approved :tada:, outsource

#12674 Beta Release 65.1, includes up to build 7977
  domain-server/resources/web/js/shared.js
  domain-server/src/DomainServer.cpp
  interface/src/ui/overlays/Web3DOverlay.cpp
  interface/src/ui/overlays/Web3DOverlay.h
  libraries/embedded-webserver/src/HTTPConnection.cpp
  libraries/embedded-webserver/src/HTTPConnection.h
  libraries/render-utils/src/MeshPartPayload.cpp
  libraries/render-utils/src/MeshPartPayload.h
  libraries/render-utils/src/Model.cpp
  scripts/developer/tests/webOverlayTool.js
  scripts/system/edit.js
Labels: Development Approved, QA Approved :tada:, master -> stable

#12648 EntityScriptServer should wait for script engine to complete for deleting itself
  assignment-client/src/scripts/EntityScriptServer.cpp
Labels: Development Approved, QA Approved :tada:

#12647 add a CLIENT_ONLY build option and handle for installer
  CMakeLists.txt
  cmake/macros/GenerateInstallers.cmake
  cmake/macros/SetPackagingParameters.cmake
  cmake/templates/CPackProperties.cmake.in
  cmake/templates/NSIS.template.in
  interface/CMakeLists.txt
  plugins/hifiCodec/CMakeLists.txt
  plugins/pcmCodec/CMakeLists.txt
  tools/oven/CMakeLists.txt
Labels: Development Approved, QA Approved :tada:, Server & Network

#12691 Fix crashes on exit because of ResourceManager thread destruction
  tools/oven/src/Oven.cpp
Labels: Development Approved, QA Approved :tada:

#12588 Materials on primitives
  libraries/entities-renderer/src/RenderableMaterialEntityItem.cpp
  libraries/entities-renderer/src/RenderableMaterialEntityItem.h
  libraries/entities-renderer/src/RenderableShapeEntityItem.cpp
  libraries/entities-renderer/src/RenderableShapeEntityItem.h
  libraries/render-utils/src/GeometryCache.cpp
  libraries/render-utils/src/GeometryCache.h
  libraries/render-utils/src/MaterialTextures.slh
  libraries/render-utils/src/forward_model_normal_map.slf
  libraries/render-utils/src/model_lightmap_normal_map.slf
  libraries/render-utils/src/model_lightmap_normal_map_fade.slf
  libraries/render-utils/src/model_normal_map.slf
  libraries/render-utils/src/model_normal_map_fade.slf
  libraries/render-utils/src/model_translucent_normal_map.slf
  libraries/render-utils/src/model_translucent_normal_map_fade.slf
  libraries/shared/src/shared/Shapes.cpp
  libraries/shared/src/shared/Shapes.h
Labels: Development Approved, Engine, QA Approved :tada:

#12618 Hificonstants as object
  interface/resources/qml/styles-uit/HifiConstants.qml
Labels: Client, Development Approved, QA Approved :tada:, outsource

#12665 Android - Resize bottombar after window size changes (to always fill …
  interface/resources/qml/hifi/+android/bottombar.qml
Labels: Android, Development Approved, QA Approved :tada:

#12369 Lexer code has confusion between strings and chars
  libraries/baking/src/JSBaker.cpp
Labels: Development Approved, QA Approved :tada:, Server & Network

#12685 Update content backup downloads to be asynchronous
  domain-server/resources/web/content/js/content.js
  domain-server/src/DomainContentBackupManager.cpp
  domain-server/src/DomainContentBackupManager.h
  domain-server/src/DomainServer.cpp
Labels: Development Approved, QA Approved :tada:

#12510 Serverless domains
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/DiscoverabilityManager.cpp
  interface/src/main.cpp
  interface/src/scripting/WindowScriptingInterface.cpp
  interface/src/scripting/WindowScriptingInterface.h
  interface/src/ui/AddressBarDialog.cpp
  interface/src/ui/AddressBarDialog.h
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/entities/src/EntityEditPacketSender.cpp
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityScriptingInterface.cpp
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/EntityTree.h
  libraries/model-networking/src/model-networking/TextureCache.cpp
  libraries/networking/src/AddressManager.cpp
  libraries/networking/src/AddressManager.h
  libraries/networking/src/AssetUtils.cpp
  libraries/networking/src/DomainHandler.cpp
  libraries/networking/src/DomainHandler.h
  libraries/networking/src/FileResourceRequest.cpp
  libraries/networking/src/NetworkingConstants.cpp
  libraries/networking/src/NetworkingConstants.h
  libraries/networking/src/NodeList.cpp
  libraries/networking/src/ResourceManager.h
  libraries/octree/src/Octree.cpp
  libraries/shared/src/PathUtils.cpp
  libraries/shared/src/PathUtils.h
  tools/ac-client/src/ACClientApp.cpp
  tools/ac-client/src/ACClientApp.h
  tools/atp-client/src/ATPClientApp.cpp
  tools/atp-client/src/ATPClientApp.h
Labels: Client, Critical Fix, QA Approved :tada:

#12638 Commerce: Item Updates!
  interface/resources/icons/tablet-icons/market-a-msg.svg
  interface/resources/icons/tablet-icons/market-a.svg
  interface/resources/icons/tablet-icons/market-i-msg.svg
  interface/resources/icons/tablet-icons/market-i.svg
  interface/resources/qml/controls-uit/FilterBar.qml
  interface/resources/qml/hifi/commerce/checkout/Checkout.qml
  interface/resources/qml/hifi/commerce/common/EmulatedMarketplaceHeader.qml
  interface/resources/qml/hifi/commerce/purchases/PurchasedItem.qml
  interface/resources/qml/hifi/commerce/purchases/Purchases.qml
  interface/resources/qml/hifi/commerce/wallet/WalletHome.qml
  interface/src/commerce/Ledger.cpp
  interface/src/commerce/Ledger.h
  interface/src/commerce/QmlCommerce.cpp
  interface/src/commerce/QmlCommerce.h
  scripts/system/commerce/wallet.js
  scripts/system/html/js/marketplacesInject.js
  scripts/system/marketplaces/marketplaces.js
Labels: Commerce, Development Approved, HMD required, QA Approved :tada:

#12682 JSDoc that an entity's clientOnly property can be set at entity creation
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityScriptingInterface.h
Labels: Content/Create, Development Approved, QA Approved :tada:, outsource

#12552 Wrap text in query dialogs. Add right margins for input field and but…
  interface/resources/qml/controls-uit/TextField.qml
  interface/resources/qml/dialogs/TabletQueryDialog.qml
  interface/src/scripting/AssetMappingsScriptingInterface.cpp
Labels: Client, Development Approved, QA Approved :tada:, outsource

#12661 Android: Stats, disable IK, reduce impact of InputRecorder
  interface/resources/icons/+android/stats.svg
  interface/resources/qml/+android/StatText.qml
  interface/resources/qml/hifi/+android/StatsBar.qml
  libraries/animation/src/AnimInverseKinematics.cpp
  libraries/controllers/src/controllers/UserInputMapper.cpp
  libraries/controllers/src/controllers/impl/endpoints/ActionEndpoint.cpp
  scripts/+android/defaultScripts.js
  scripts/system/+android/stats.js
Labels: Android, Development Approved, Engine, QA Approved :tada:

#12702 Android: Fix tonemapping
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.cpp
Labels: Android, Development Approved

#12709 RC66: Fix infinite loading when authing wallet during Checkout
  interface/resources/qml/hifi/commerce/checkout/Checkout.qml
Labels: Commerce, Development Approved, QA Approved :tada:, bug

#12711 Serverless tutorial rc66
  CMakeLists.txt
  cmake/externals/serverless-content/CMakeLists.txt
  cmake/macros/SetPackagingParameters.cmake
  interface/CMakeLists.txt
  interface/resources/serverless/tutorial.json
  libraries/networking/src/AddressManager.cpp
Labels: Client, Development Approved, QA Approved :tada:

#12660 Update away image and image paths
  scripts/system/assets/images/Overlay-Viz-blank.png
  scripts/system/away.js
Labels: Client, Development Approved, QA Approved :tada:

#12717 fix -- work around asset-upload dialog crash
  interface/resources/qml/dialogs/CustomQueryDialog.qml
  interface/resources/qml/dialogs/QueryDialog.qml
Labels: Client, Critical Fix, Development Approved, QA Approved :tada:

#12676 fixing AddressManager keyboard when switching domains
  interface/resources/qml/hifi/tablet/TabletAddressDialog.qml
Labels: Client, Development Approved, QA Approved :tada:

#12574 changing keyboard mapping
  interface/resources/controllers/keyboardMouse.json
  interface/resources/html/img/tablet-help-keyboard.jpg
  interface/resources/qml/hifi/AssetServer.qml
  interface/resources/qml/hifi/dialogs/RunningScripts.qml
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/Menu.cpp
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  libraries/controllers/src/controllers/Actions.cpp
  libraries/controllers/src/controllers/Actions.h
  libraries/shared/src/AvatarConstants.h
Labels: Client, Development Approved, QA Approved :tada:

#12724 fix entity importing
  interface/src/Application.cpp
Labels: Client, Development Approved, QA Approved :tada:

#12637 Fix asset server qml sorting
  interface/resources/qml/hifi/AssetServer.qml
  interface/resources/qml/hifi/dialogs/TabletAssetServer.qml
  interface/src/scripting/AssetMappingsScriptingInterface.cpp
  interface/src/scripting/AssetMappingsScriptingInterface.h
Labels: Client, Development Approved, QA Approved :tada:

#12721 RC66 - Mergeback
  interface/resources/qml/dialogs/CustomQueryDialog.qml
  interface/resources/qml/dialogs/QueryDialog.qml
  interface/src/Application.cpp
Labels: RC -> master

#12671 WL#21794: Modify inspect.js to work with Avatars as well as entities
  script-archive/inspect.js
Labels: Client, Development Approved, QA Approved :tada:, outsource

#12689 Reinstate Overlays.getOverlayObject API function
  interface/src/ui/overlays/Overlays.cpp
  interface/src/ui/overlays/Overlays.h
  scripts/system/libraries/WebTablet.js
Labels: Client, Development Approved, QA Approved :tada:, Scripting API change

#12732 fix cmake changes for script copy for dev builds
  interface/CMakeLists.txt
Labels: Development Approved, QA Approved :tada:

#12686 Android - Prevent Camera movement with UI (especially Windows and Radar mode)
  interface/resources/qml/+android/AddressBarDialog.qml
  interface/resources/qml/hifi/+android/avatarSelection.qml
  interface/resources/qml/hifi/+android/button.qml
  libraries/qml/src/qml/OffscreenSurface.cpp
  scripts/system/+android/audio.js
  scripts/system/+android/avatarSelection.js
  scripts/system/+android/modes.js
  scripts/system/+android/radar.js
Labels: Android, Development Approved, QA Approved :tada:

#12726 Attempt to resolve potential overlay crashes at shutdown
  interface/src/Application.cpp
  interface/src/ui/overlays/Overlays.cpp
  interface/src/ui/overlays/Overlays.h
  interface/src/ui/overlays/QmlOverlay.cpp
  interface/src/ui/overlays/QmlOverlay.h
  libraries/qml/src/qml/impl/SharedObject.cpp
Labels: Development Approved, Engine, QA Approved :tada:, bug

#12719 Fix ESS remote method calls for connect only users
  assignment-client/src/scripts/EntityScriptServer.cpp
  domain-server/src/DomainServer.cpp
Labels: Development Approved, QA Approved :tada:

#12728 Android: Fix octal code signed char issue
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/UpdateEntityOperator.cpp
  libraries/shared/src/OctalCode.cpp
  libraries/shared/src/OctalCode.h
Labels: Android, Development Approved, Engine, QA Approved :tada:

#12742 Fix/rc66 crashes
  interface/src/Application.cpp
  interface/src/ui/overlays/Overlays.cpp
  interface/src/ui/overlays/Overlays.h
  interface/src/ui/overlays/QmlOverlay.cpp
  interface/src/ui/overlays/QmlOverlay.h
  libraries/qml/src/qml/impl/SharedObject.cpp
Labels: Development Approved, Engine, QA Approved :tada:, bug

#12715 Add Window.raise() as replacement for Window.raiseMainWindow()
  interface/src/scripting/WindowScriptingInterface.cpp
  interface/src/scripting/WindowScriptingInterface.h
Labels: Client, Development Approved, QA Approved :tada:, Scripting API change, outsource

#12704 Improve audio devices selection logic
  interface/src/scripting/AudioDevices.cpp
  interface/src/scripting/AudioDevices.h
Labels: Client, Development Approved, QA Approved :tada:

#12720 Fix far grabbing a grabbable child when the parent is not grabbable.
  scripts/system/controllers/controllerModules/farActionGrabEntity.js
Labels: Client, Development Approved, QA Approved :tada:

#12745 RC66: Fix shadows on primitives
  libraries/entities-renderer/src/RenderableShapeEntityItem.cpp
Labels: Development Approved, Engine, QA Approved :tada:, bug

#12740 Fix name conflict with c++ class and qml file(master)
  interface/resources/qml/AudioScopeUI.qml
  scripts/developer/utilities/audio/audioScope.js
Labels: Client, Development Approved, QA Approved :tada:
