Repository highfidelity/hifi, pull requests merged in 2018-10, with the labels that each got.

#13997 Fix switch from Top View to My View
  scripts/system/+android/clickWeb.js
Labels: Android, Development Approved, Engine, Project Approved, QA Approved :tada:

#14013 Fix android login infinite loading (case 18459)
  android/app/build.gradle
  android/app/src/main/cpp/native.cpp
  android/app/src/main/java/io/highfidelity/hifiinterface/fragment/LoginFragment.java
  android/app/src/main/res/drawable/ic_eye_noshow.xml
  android/app/src/main/res/drawable/ic_eye_show.xml
  android/app/src/main/res/drawable/selector_show_password.xml
  android/app/src/main/res/layout/fragment_login.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
Labels: Android, Development Approved, Engine, Project Approved, QA Approved :tada:

#14020 Login Dialog UI improvements
  interface/resources/qml/LoginDialog/LinkAccountBody.qml
Labels: Client, Development Approved, Project Approved, QA Approved :tada:, bug

#14025 use current wearable index, not joint index!
  interface/resources/qml/hifi/avatarapp/AdjustWearables.qml
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14026 Fix edit rotation handle fidgeting
  interface/src/ui/overlays/Circle3DOverlay.cpp
  scripts/system/libraries/entitySelectionTool.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#14042 Speed up Entity List properties fetching by adding Entities.getMultipleEntities API
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.h
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityItemPropertiesMacros.h
  libraries/entities/src/EntityPsuedoPropertyFlags.h
  libraries/entities/src/EntityScriptingInterface.cpp
  libraries/entities/src/EntityScriptingInterface.h
  libraries/entities/src/EntityTypes.h
  libraries/entities/src/LightEntityItem.cpp
  libraries/entities/src/LightEntityItem.h
  libraries/entities/src/LineEntityItem.cpp
  libraries/entities/src/LineEntityItem.h
  libraries/entities/src/MaterialEntityItem.cpp
  libraries/entities/src/MaterialEntityItem.h
  libraries/entities/src/ModelEntityItem.cpp
  libraries/entities/src/ModelEntityItem.h
  libraries/entities/src/ParticleEffectEntityItem.cpp
  libraries/entities/src/ParticleEffectEntityItem.h
  libraries/entities/src/PolyLineEntityItem.cpp
  libraries/entities/src/PolyLineEntityItem.h
  libraries/entities/src/PolyVoxEntityItem.cpp
  libraries/entities/src/PolyVoxEntityItem.h
  libraries/entities/src/ShapeEntityItem.cpp
  libraries/entities/src/ShapeEntityItem.h
  libraries/entities/src/TextEntityItem.cpp
  libraries/entities/src/TextEntityItem.h
  libraries/entities/src/WebEntityItem.cpp
  libraries/entities/src/WebEntityItem.h
  libraries/entities/src/ZoneEntityItem.cpp
  libraries/entities/src/ZoneEntityItem.h
  libraries/script-engine/src/ScriptEngine.cpp
  scripts/developer/tests/unit_tests/entityUnitTests.js
  scripts/system/libraries/entityList.js
Labels: Create, Development Approved, JSDocs, Project Approved, QA Approved :tada:, Scripting API change

#14110 get interface building and working with clang-7 on ubuntu 18
  domain-server/src/DomainServer.cpp
  interface/src/Application.cpp
  interface/src/Application_render.cpp
  interface/src/raypick/PathPointer.h
  interface/src/scripting/HMDScriptingInterface.h
  interface/src/ui/OverlayConductor.cpp
  interface/src/ui/overlays/Text3DOverlay.cpp
  libraries/controllers/src/controllers/InputDevice.h
  libraries/controllers/src/controllers/impl/conditionals/AndConditional.h
  libraries/controllers/src/controllers/impl/conditionals/EndpointConditional.h
  libraries/controllers/src/controllers/impl/conditionals/NotConditional.h
  libraries/controllers/src/controllers/impl/filters/ClampFilter.h
  libraries/controllers/src/controllers/impl/filters/ConstrainToIntegerFilter.h
  libraries/controllers/src/controllers/impl/filters/ConstrainToPositiveIntegerFilter.h
  libraries/controllers/src/controllers/impl/filters/DeadZoneFilter.h
  libraries/controllers/src/controllers/impl/filters/ExponentialSmoothingFilter.h
  libraries/controllers/src/controllers/impl/filters/HysteresisFilter.h
  libraries/controllers/src/controllers/impl/filters/InvertFilter.h
  libraries/controllers/src/controllers/impl/filters/LowVelocityFilter.h
  libraries/controllers/src/controllers/impl/filters/NotFilter.h
  libraries/controllers/src/controllers/impl/filters/PostTransformFilter.h
  libraries/controllers/src/controllers/impl/filters/PulseFilter.h
  libraries/controllers/src/controllers/impl/filters/RotateFilter.h
  libraries/controllers/src/controllers/impl/filters/ScaleFilter.h
  libraries/controllers/src/controllers/impl/filters/TransformFilter.h
  libraries/controllers/src/controllers/impl/filters/TranslateFilter.h
  libraries/display-plugins/src/display-plugins/AbstractHMDScriptingInterface.h
  libraries/fbx/src/FBXReader.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLTexture.h
  libraries/gpu-gl/src/gpu/gl41/GL41BackendTexture.cpp
  libraries/gpu-gl/src/gpu/gl45/GL45BackendVariableTexture.cpp
  libraries/gpu/src/gpu/State.h
  libraries/graphics-scripting/src/graphics-scripting/GraphicsScriptingInterface.cpp
  libraries/graphics-scripting/src/graphics-scripting/ScriptableMesh.cpp
  libraries/graphics-scripting/src/graphics-scripting/ScriptableModel.cpp
  libraries/input-plugins/src/input-plugins/KeyboardMouseDevice.h
  libraries/model-networking/src/model-networking/ModelCache.h
  libraries/plugins/src/plugins/InputPlugin.h
  libraries/pointers/src/Pick.h
  libraries/render-utils/src/MeshPartPayload.h
  libraries/render/src/render/DrawSceneOctree.cpp
  libraries/render/src/render/Item.h
  libraries/shared/src/PointerEvent.cpp
  libraries/shared/src/PrioritySortUtil.h
  libraries/shared/src/TransformNode.h
  libraries/task/src/task/Task.h
  libraries/ui/src/OffscreenUi.cpp
  libraries/ui/src/OffscreenUi.h
  libraries/workload/src/workload/Transaction.h
  tests-manual/entities/src/main.cpp
  tests-manual/gpu-textures/src/main.cpp
  tests-manual/gpu/src/main.cpp
  tests-manual/render-perf/src/main.cpp
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14106 Fix some Mac rendering issues
  interface/resources/qml/hifi/avatarapp/TransparencyMask.qml
  libraries/qml/src/qml/impl/SharedObject.cpp
Labels: Development Approved, Engine, Mac Required, Project Approved, QA Approved :tada:

#14105 Fix avatar warp into floor when navigating to a saved bookmark
  interface/src/avatar/MyAvatar.cpp
Labels: Avatar, Development Approved, Project Approved, QA Approved :tada:

#14102 Account-managed wallet flow improvements
  interface/resources/qml/hifi/commerce/checkout/Checkout.qml
  interface/resources/qml/hifi/commerce/wallet/Wallet.qml
  interface/resources/qml/hifi/commerce/wallet/WalletSetup.qml
  scripts/modules/appUi.js
  scripts/system/html/js/marketplacesInject.js
  scripts/system/marketplaces/marketplaces.js
Labels: Commerce, Development Approved, Project Approved, QA Approved :tada:

#14104 fix for row re-ordering causing no change alone
  domain-server/resources/web/js/base-settings.js
Labels: Development Approved, Project Approved, QA Approved :tada:, Server & Network

#14083 call saveRecordingToAsset callback on correct thread
  libraries/script-engine/src/RecordingScriptingInterface.cpp
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14091 Fix case 18465: redirect to domain after login
  android/app/src/main/cpp/native.cpp
  android/app/src/main/java/io/highfidelity/hifiinterface/InterfaceActivity.java
  android/app/src/main/java/io/highfidelity/hifiinterface/MainActivity.java
  interface/src/AndroidHelper.cpp
  interface/src/AndroidHelper.h
  interface/src/Application.cpp
  interface/src/scripting/WindowScriptingInterface.cpp
Labels: Android, Development Approved, Engine, Project Approved, QA Approved :tada:

#14087 fix several uninitialized reads
  interface/src/Application.cpp
  interface/src/Application.h
  libraries/entities/src/EntityTreeElement.cpp
  libraries/shared/src/TriangleSet.cpp
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14055 Do not have active buy button on invalidated items
  scripts/system/html/js/marketplacesInject.js
Labels: Commerce, Development Approved, Project Approved, QA Approved :tada:, bug

#13965 Mini tablet in palm
  interface/src/Application.cpp
  interface/src/scripting/HMDScriptingInterface.h
  libraries/networking/src/MessagesClient.cpp
  scripts/defaultScripts.js
  scripts/system/assets/models/miniTabletBlank.fbx
  scripts/system/assets/sounds/button-click.wav
  scripts/system/assets/sounds/button-hover.wav
  scripts/system/controllers/controllerDispatcher.js
  scripts/system/controllers/controllerModules/nearParentGrabOverlay.js
  scripts/system/controllers/controllerModules/stylusInput.js
  scripts/system/html/css/img/mt-expand-hover.svg
  scripts/system/html/css/img/mt-expand-normal.svg
  scripts/system/html/css/img/mt-goto-hover.svg
  scripts/system/html/css/img/mt-goto-normal.svg
  scripts/system/html/css/img/mt-mute-hover.svg
  scripts/system/html/css/img/mt-mute-normal.svg
  scripts/system/html/css/miniTablet.css
  scripts/system/html/img/expand.svg
  scripts/system/html/js/miniTablet.js
  scripts/system/html/miniTablet.html
  scripts/system/libraries/utils.js
  scripts/system/miniTablet.js
  scripts/system/tablet-ui/tabletUI.js
Labels: Client, Development Approved, Project Approved, QA Approved :tada:, Scripting API change

#14116 get asan to not complain about invalid downcasts during transaction.updateItem
  libraries/entities-renderer/src/RenderableEntityItem.cpp
  libraries/render-utils/src/CauterizedModel.cpp
Labels: Client, Development Approved, Engine, Project Approved, QA Approved :tada:

#14027 Remove UndoStack API
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/Menu.cpp
  libraries/script-engine/src/UndoStackScriptingInterface.cpp
  libraries/script-engine/src/UndoStackScriptingInterface.h
  scripts/system/edit.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#14101 Edit handle pick plane improvements
  scripts/system/libraries/entitySelectionTool.js
Labels: Create, Development Approved, HMD required, Project Approved, QA Approved :tada:

#14068 Fix for bad static_pointer_cast on exit.
  interface/src/avatar/AvatarManager.cpp
Labels: Avatar, Development Approved, Project Approved, QA Approved :tada:

#14080 Fix models with 1^3 dimensions never being resized
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14131 Better deadlock crash
  interface/src/Application.cpp
Labels: Development Approved, Project Approved, QA Approved :tada:

#14118 Disable Hand Touch when Leap Motion is running
  interface/src/Application.cpp
  libraries/controllers/src/controllers/ScriptingInterface.cpp
  libraries/controllers/src/controllers/ScriptingInterface.h
  libraries/plugins/src/plugins/Plugin.h
  libraries/plugins/src/plugins/PluginManager.cpp
  libraries/plugins/src/plugins/PluginManager.h
  plugins/hifiLeapMotion/src/LeapMotionPlugin.cpp
  plugins/hifiLeapMotion/src/LeapMotionPlugin.h
  plugins/hifiNeuron/src/NeuronPlugin.cpp
  plugins/hifiNeuron/src/NeuronPlugin.h
  plugins/hifiSdl2/src/SDL2Manager.cpp
  plugins/hifiSdl2/src/SDL2Manager.h
  scripts/system/controllers/handTouch.js
Labels: Avatar, Development Approved, Project Approved, QA Approved :tada:, Scripting API change

#14111 Fix MS18608: Use new connections api endpoint
  interface/resources/qml/hifi/Pal.qml
Labels: Development Approved, Discovery, Project Approved, QA Approved :tada:, bug

#14075 Teleport with play area
  interface/resources/qml/dialogs/preferences/CheckBoxPreference.qml
  interface/resources/qml/dialogs/preferences/RadioButtonsPreference.qml
  interface/resources/qml/dialogs/preferences/Section.qml
  interface/resources/qml/hifi/tablet/tabletWindows/TabletPreferencesDialog.qml
  interface/resources/qml/hifi/tablet/tabletWindows/preferences/Section.qml
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  interface/src/raypick/ParabolaPointer.cpp
  interface/src/raypick/ParabolaPointer.h
  interface/src/raypick/PointerScriptingInterface.cpp
  interface/src/raypick/PointerScriptingInterface.h
  interface/src/raypick/StylusPointer.cpp
  interface/src/scripting/HMDScriptingInterface.cpp
  interface/src/scripting/HMDScriptingInterface.h
  interface/src/ui/PreferencesDialog.cpp
  libraries/plugins/src/plugins/DisplayPlugin.h
  libraries/pointers/src/PointerManager.cpp
  libraries/render-utils/src/Highlight.slh
  libraries/shared/src/Preferences.h
  libraries/shared/src/RegisteredMetaTypes.cpp
  libraries/shared/src/RegisteredMetaTypes.h
  plugins/oculus/src/OculusBaseDisplayPlugin.cpp
  plugins/oculus/src/OculusBaseDisplayPlugin.h
  plugins/openvr/src/OpenVrDisplayPlugin.cpp
  plugins/openvr/src/OpenVrDisplayPlugin.h
  scripts/system/assets/models/oculusSensorv11.fbx
  scripts/system/assets/models/teleportationSpotBasev8.fbx
  scripts/system/assets/models/trackingSpacev18.fbx
  scripts/system/controllers/controllerModules/teleport.js
Labels: Client, Development Approved, Project Approved, QA Approved :tada:, Scripting API change

#14113 Audio Mixer Scaling
  assignment-client/src/audio/AudioMixer.cpp
  assignment-client/src/audio/AudioMixer.h
  assignment-client/src/audio/AudioMixerClientData.cpp
  assignment-client/src/audio/AudioMixerClientData.h
  assignment-client/src/audio/AudioMixerSlave.cpp
  assignment-client/src/audio/AudioMixerSlave.h
  assignment-client/src/audio/AudioMixerSlavePool.cpp
  assignment-client/src/audio/AudioMixerSlavePool.h
  assignment-client/src/audio/AudioMixerStats.cpp
  assignment-client/src/audio/AudioMixerStats.h
  assignment-client/src/audio/AvatarAudioStream.cpp
  assignment-client/src/audio/AvatarAudioStream.h
  assignment-client/src/avatars/AvatarMixer.cpp
  assignment-client/src/avatars/AvatarMixerClientData.cpp
  assignment-client/src/avatars/AvatarMixerClientData.h
  assignment-client/src/avatars/AvatarMixerSlave.cpp
  libraries/audio/src/AudioHRTF.cpp
  libraries/audio/src/AudioHRTF.h
  libraries/audio/src/AudioStreamStats.h
  libraries/audio/src/InboundAudioStream.cpp
  libraries/audio/src/InboundAudioStream.h
  libraries/audio/src/InjectedAudioStream.cpp
  libraries/audio/src/InjectedAudioStream.h
  libraries/audio/src/PositionalAudioStream.cpp
  libraries/audio/src/PositionalAudioStream.h
  libraries/networking/src/Node.cpp
  libraries/networking/src/Node.h
Labels: Development Approved, Project Approved, QA Approved :tada:, Server & Network

#14000 New Pick Parenting for Ray Picks and Parabola Picks
  docs/LICENSE_highlight.js.txt
  docs/LICENSE_markdeep.txt
  docs/interface/raypick/pick-parenting.md.html
  docs/markdeep.min.js
  docs/markdeep_apidoc.css
  interface/src/Application.cpp
  interface/src/raypick/CollisionPick.cpp
  interface/src/raypick/CollisionPick.h
  interface/src/raypick/JointParabolaPick.cpp
  interface/src/raypick/JointParabolaPick.h
  interface/src/raypick/JointRayPick.cpp
  interface/src/raypick/JointRayPick.h
  interface/src/raypick/LaserPointer.cpp
  interface/src/raypick/LaserPointer.h
  interface/src/raypick/MouseParabolaPick.cpp
  interface/src/raypick/MouseParabolaPick.h
  interface/src/raypick/MouseRayPick.cpp
  interface/src/raypick/MouseRayPick.h
  interface/src/raypick/ParabolaPick.cpp
  interface/src/raypick/ParabolaPick.h
  interface/src/raypick/ParabolaPointer.cpp
  interface/src/raypick/ParabolaPointer.h
  interface/src/raypick/PathPointer.cpp
  interface/src/raypick/PathPointer.h
  interface/src/raypick/PickScriptingInterface.cpp
  interface/src/raypick/PickScriptingInterface.h
  interface/src/raypick/PointerScriptingInterface.cpp
  interface/src/raypick/RayPick.cpp
  interface/src/raypick/RayPick.h
  interface/src/raypick/RayPickScriptingInterface.cpp
  interface/src/raypick/StaticParabolaPick.cpp
  interface/src/raypick/StaticParabolaPick.h
  interface/src/raypick/StaticRayPick.cpp
  interface/src/raypick/StaticRayPick.h
  interface/src/raypick/StylusPick.cpp
  interface/src/raypick/StylusPick.h
  libraries/pointers/src/Pick.h
  libraries/pointers/src/PickManager.cpp
  libraries/pointers/src/PickManager.h
  libraries/shared/src/RegisteredMetaTypes.h
  scripts/system/controllers/controllerDispatcher.js
  scripts/system/controllers/controllerModules/teleport.js
  scripts/system/controllers/grab.js
Labels: Development Approved, Engine, Feedback Welcome, HMD required, JSDocs, Project Approved, QA Approved :tada:, Scripting API change

#14141 Fix avatars transit on domain enter
  interface/src/avatar/AvatarManager.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
  libraries/avatars/src/AvatarData.h
  libraries/avatars/src/AvatarHashMap.cpp
Labels: Avatar, Development Approved, Project Approved, QA Approved :tada:

#14137 Bug fix for rotation culling in AvatarData::toByteArray()
  libraries/avatars/src/AvatarData.cpp
Labels: Avatar, Development Approved, Project Approved, QA Approved :tada:

#14100 update soft entities and fix deadlock from qml.
  interface/resources/qml/hifi/avatarapp/AdjustWearables.qml
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/entities/src/EntityScriptingInterface.cpp
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14146 RC73.2: suppress traits larger than INT16_MAX bytes
  assignment-client/src/avatars/AvatarMixerClientData.cpp
  assignment-client/src/avatars/AvatarMixerSlave.cpp
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarTraits.h
  libraries/networking/src/NodeList.cpp
Labels: Development Approved, Project Approved, QA Approved :tada:

#14088 Sys tray setup
  CMakeLists.txt
  cmake/macros/InstallBesideConsole.cmake
  cmake/macros/SetPackagingParameters.cmake
  cmake/modules/MacOSXBundleInfo.plist.in
  cmake/templates/CPackProperties.cmake.in
  cmake/templates/MacOSXBundleConsoleComponentsInfo.plist.in
  cmake/templates/NSIS.template.in
  server-console/CMakeLists.txt
  server-console/package.json
  server-console/packager.js
  server-console/src/main.js
  server-console/src/modules/hf-acctinfo.js
  server-console/src/modules/hf-app.js
  server-console/src/modules/hf-notifications.js
  server-console/src/modules/hf-process.js
  server-console/src/modules/path-finder.js
Labels: Development Approved, Discovery, Project Approved, QA Approved :tada:

#14151 remove expired avatarEntities from their avatars 0.73.2
  interface/src/Application.cpp
  interface/src/avatar/AvatarManager.cpp
  interface/src/avatar/AvatarManager.h
  interface/src/avatar/MyAvatar.cpp
  libraries/entities/src/EntitySimulation.h
  libraries/physics/src/PhysicalEntitySimulation.cpp
  libraries/physics/src/PhysicalEntitySimulation.h
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14152 RC73.2: avoid backwards seek for skipped trait deletes
  libraries/avatars/src/AvatarHashMap.cpp
Labels: Development Approved, Project Approved, QA Approved :tada:

#14150 remove expired avatarEntities from their avatars
  interface/src/Application.cpp
  interface/src/avatar/AvatarManager.cpp
  interface/src/avatar/AvatarManager.h
  interface/src/avatar/MyAvatar.cpp
  libraries/entities/src/EntitySimulation.h
  libraries/physics/src/PhysicalEntitySimulation.cpp
  libraries/physics/src/PhysicalEntitySimulation.h
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14153 Reduce the glitches of far away animating avatars
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
Labels: Avatar, Development Approved, Project Approved, QA Approved :tada:

#14154 Build libplugins_libhifiCodec.so
  android/app/CMakeLists.txt
  android/app/build.gradle
  android/build.gradle
  cmake/macros/TargetHifiAudioCodec.cmake
  plugins/hifiCodec/CMakeLists.txt
Labels: Android, Android Smoke Required, Development Approved, Project Approved, QA Approved :tada:

#14147 suppress traits larger than INT16_MAX bytes
  assignment-client/src/avatars/AvatarMixerClientData.cpp
  assignment-client/src/avatars/AvatarMixerSlave.cpp
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarHashMap.cpp
  libraries/avatars/src/AvatarTraits.h
  libraries/networking/src/NodeList.cpp
Labels: Development Approved, Project Approved, QA Approved :tada:, Server & Network

#14094 Merged interstitial page/redirect domain improvements
  interface/resources/images/interstitialPage/button.png
  interface/resources/images/interstitialPage/button_back.png
  interface/resources/images/interstitialPage/button_hover.png
  interface/resources/images/interstitialPage/button_tryAgain.png
  interface/resources/serverless/redirect.json
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/octree/SafeLanding.cpp
  interface/src/octree/SafeLanding.h
  interface/src/scripting/WindowScriptingInterface.cpp
  interface/src/scripting/WindowScriptingInterface.h
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.h
  libraries/entities-renderer/src/RenderableParticleEffectEntityItem.cpp
  libraries/entities/src/ParticleEffectEntityItem.cpp
  libraries/model-networking/src/model-networking/ModelCache.cpp
  libraries/networking/src/AddressManager.cpp
  libraries/networking/src/AddressManager.h
  libraries/networking/src/DomainHandler.cpp
  libraries/networking/src/DomainHandler.h
  scripts/defaultScripts.js
  scripts/developer/utilities/render/textureMonitor.qml
  scripts/modules/appUi.js
  scripts/system/controllers/controllerModules/farActionGrabEntity.js
  scripts/system/interstitialPage.js
  scripts/system/redirectOverlays.js
Labels: Client, Development Approved, Project Approved, QA Approved :tada:, Scripting API change

#14160 (RC 74) Fix: Interstitial page restoring ignored entities
  scripts/system/controllers/controllerModules/farActionGrabEntity.js
Labels: Client, Critical Fix, Development Approved, Project Approved, QA Approved :tada:

#14052 updates for deprecating cmake policies and MacOS 10.14 build
  cmake/compiler.cmake
  cmake/externals/quazip/CMakeLists.txt
  cmake/init.cmake
  cmake/macros/TargetZlib.cmake
Labels: Development Approved, Project Approved, QA Approved :tada:

#14202 Fix js array never being cleared
  scripts/system/controllers/controllerModules/webSurfaceLaserInput.js
Labels: Client, Development Approved, Project Approved, QA Approved :tada:, QA Ready

#14190 Interstitital Mode - disable teleport and fix avatar outside of interstitial bubble (RC74)
  scripts/system/controllers/controllerModules/teleport.js
  scripts/system/interstitialPage.js
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14199 v0.74.0: go to error-room when failing to connect to a full domain
  libraries/networking/src/DomainHandler.cpp
  scripts/system/redirectOverlays.js
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14206 0.74.0: new treatment for hmd/tablet login
  scripts/system/libraries/accountUtils.js
Labels: Client, Development Approved, Project Approved, QA Approved :tada:, bug

#14208 Hide mini tablet immediately upon near grabbing an entity (RC74)
  scripts/system/miniTablet.js
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14201 Attempt of making the interstitial loading bar to be more accurate. (RC74)
  interface/resources/sounds/crystals_and_voices.mp3
  scripts/system/interstitialPage.js
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14205 new treatment for hmd/tablet login
  scripts/system/libraries/accountUtils.js
Labels: Client, Development Approved, Project Approved, QA Approved :tada:, bug

#14166 Allow avatar to fly when its scale is very small
  libraries/physics/src/CharacterController.cpp
Labels: Avatar, Development Approved, Project Approved, QA Approved :tada:

#14165 Increase velocity increments when the avatar is really small.
  interface/src/avatar/MyAvatar.cpp
Labels: Avatar, Development Approved, QA Approved :tada:

#14136 MS19053: [CreateApp/EntityList] Move export selection button to bottom of the list
  scripts/system/html/css/edit-style.css
  scripts/system/html/entityList.html
  scripts/system/html/js/entityList.js
Labels: Create, Development Approved, Feedback Welcome, Project Approved, QA Approved :tada:

#14156 Fix "Good" collision not honoring mesh groups in OBJ files
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities/src/ModelEntityItem.cpp
  libraries/entities/src/ModelEntityItem.h
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:, bug

#14139 Fix various ResourceCache bugs
  interface/src/Application.cpp
  interface/src/ui/Stats.cpp
  libraries/animation/src/AnimationCache.cpp
  libraries/audio/src/SoundCache.cpp
  libraries/model-networking/src/model-networking/TextureCache.h
  libraries/networking/src/ResourceCache.cpp
  libraries/networking/src/ResourceCache.h
Labels: Beware: Threading/Deadlock, Development Approved, Engine, Project Approved, QA Approved :tada:, Server & Network

#14119 Move stage frames to Varyings
  libraries/render-utils/src/BackgroundStage.cpp
  libraries/render-utils/src/BackgroundStage.h
  libraries/render-utils/src/BloomEffect.cpp
  libraries/render-utils/src/BloomEffect.h
  libraries/render-utils/src/BloomStage.cpp
  libraries/render-utils/src/BloomStage.h
  libraries/render-utils/src/DebugDeferredBuffer.cpp
  libraries/render-utils/src/DebugDeferredBuffer.h
  libraries/render-utils/src/DeferredLightingEffect.cpp
  libraries/render-utils/src/DeferredLightingEffect.h
  libraries/render-utils/src/DrawHaze.cpp
  libraries/render-utils/src/DrawHaze.h
  libraries/render-utils/src/HazeStage.cpp
  libraries/render-utils/src/HazeStage.h
  libraries/render-utils/src/LightClusters.cpp
  libraries/render-utils/src/LightClusters.h
  libraries/render-utils/src/LightStage.cpp
  libraries/render-utils/src/LightStage.h
  libraries/render-utils/src/RenderCommonTask.cpp
  libraries/render-utils/src/RenderCommonTask.h
  libraries/render-utils/src/RenderDeferredTask.cpp
  libraries/render-utils/src/RenderDeferredTask.h
  libraries/render-utils/src/RenderForwardTask.cpp
  libraries/render-utils/src/RenderForwardTask.h
  libraries/render-utils/src/RenderShadowTask.cpp
  libraries/render-utils/src/RenderShadowTask.h
  libraries/render-utils/src/ZoneRenderer.cpp
  libraries/render-utils/src/ZoneRenderer.h
  libraries/task/src/task/Task.h
  libraries/task/src/task/Varying.h
Labels: Android, Android Smoke Required, Development Approved, Engine, Project Approved, QA Approved :tada:

#14124 Don't render particles without textures
  libraries/entities-renderer/src/RenderableParticleEffectEntityItem.cpp
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14223 Fix for Case 19395
  server-console/src/main.js
Labels: Critical Fix, Development Approved, Discovery, Project Approved, QA Approved :tada:, bug

#14219 QueryAACube fixes and materials expand to include their parent
  interface/src/ui/overlays/Base3DOverlay.cpp
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/MaterialEntityItem.cpp
  libraries/entities/src/MaterialEntityItem.h
  libraries/shared/src/SpatiallyNestable.cpp
  libraries/shared/src/SpatiallyNestable.h
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14142 Fix audio overlay not working while in edit apps
  scripts/system/controllers/controllerModules/hudOverlayPointer.js
  scripts/system/controllers/controllerModules/inEditMode.js
  scripts/system/controllers/controllerModules/inVREditMode.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#14231 Fix lasers going through tablet to drawInFrontOverlays
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/ui/overlays/Overlays.cpp
  interface/src/ui/overlays/Overlays.h
Labels: Client, Create, Development Approved, Engine, Project Approved, QA Approved :tada:, QA Ready

#14096 Added generateTextureMipsWithPipeline function in gpu::Batch
  libraries/gpu-gl-common/src/gpu/gl/GLBackend.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLBackend.h
  libraries/gpu-gl-common/src/gpu/gl/GLBackendTexture.cpp
  libraries/gpu-gl/src/gpu/gl41/GL41Backend.cpp
  libraries/gpu-gl/src/gpu/gl41/GL41Backend.h
  libraries/gpu-gl/src/gpu/gl45/GL45Backend.cpp
  libraries/gpu-gl/src/gpu/gl45/GL45Backend.h
  libraries/gpu-gles/src/gpu/gles/GLESBackend.cpp
  libraries/gpu-gles/src/gpu/gles/GLESBackend.h
  libraries/gpu/src/gpu/Batch.cpp
  libraries/gpu/src/gpu/Batch.h
  libraries/gpu/src/gpu/MipGeneration.slh
  libraries/gpu/src/gpu/ShaderConstants.h
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14215 Hide mini tablet immediately upon near grabbing an entity
  scripts/system/miniTablet.js
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14211 Bug Fix for Crazy Legs when you sit on the floor (Manuscript 17045).
  interface/src/avatar/MySkeletonModel.cpp
Labels: Avatar, Development Approved, HMD required, Project Approved, QA Approved :tada:, bug

#14196 go to error-room when failing to connect to a full domain
  libraries/networking/src/DomainHandler.cpp
  scripts/system/redirectOverlays.js
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14191 new images for My Purchases rez tutorial
  interface/resources/qml/hifi/commerce/common/images/Purchase-First-Run-1.jpg
  interface/resources/qml/hifi/commerce/common/images/Purchase-First-Run-2.jpg
Labels: Commerce, Development Approved, Project Approved, QA Approved :tada:

#14185 make room for keyboard and help in SendAsset
  interface/resources/qml/hifi/commerce/common/sendAsset/SendAsset.qml
  interface/resources/qml/hifi/commerce/purchases/Purchases.qml
  interface/resources/qml/hifi/commerce/wallet/Wallet.qml
Labels: Commerce, Development Approved, Project Approved, QA Approved :tada:, bug

#14179 Sys tray submenus
  server-console/src/main.js
  server-console/src/modules/hf-notifications.js
Labels: Development Approved, Discovery, Project Approved, QA Approved :tada:

#14053 make extracted from resources avatarbookmarks.json writable
  interface/src/AvatarBookmarks.cpp
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14162 Clean up elbow smoothing code
  interface/src/avatar/MyAvatar.h
  libraries/animation/src/Rig.cpp
  libraries/animation/src/Rig.h
Labels: Avatar, Development Approved, Project Approved, QA Approved :tada:, Scripting API change

#14140 Make EntityScriptingInterface aware of distributed physics simulation (DPS) rules
  interface/src/AvatarBookmarks.cpp
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityScriptingInterface.cpp
  libraries/physics/src/EntityMotionState.cpp
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14173 fix build on clang 7
  assignment-client/src/audio/AudioMixerClientData.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14012 Adding handshake control to image in Controls Reference
  interface/resources/html/img/tablet-help-keyboard.jpg
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14241 Setup a higher memory limit for android build
  android/gradle.properties
Labels: Android, Development Approved, Project Approved, QA Approved :tada:, Windows Required

#14184 Move blendshape buffers to render thread
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
  libraries/entities-renderer/src/RenderableModelEntityItem.h
  libraries/render-utils/src/CauterizedModel.cpp
  libraries/render-utils/src/MeshPartPayload.cpp
  libraries/render-utils/src/MeshPartPayload.h
  libraries/render-utils/src/MetaModelPayload.cpp
  libraries/render-utils/src/MetaModelPayload.h
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
  libraries/render-utils/src/SoftAttachmentModel.cpp
Labels: Android, Beware: Threading/Deadlock, Development Approved, Engine, Mac Required, Project Approved, QA Approved :tada:, Windows Required

#14169 Fix highlight not working after HMD switch
  libraries/render-utils/src/HighlightEffect.cpp
  libraries/render-utils/src/HighlightEffect.h
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:, bug

#14221 Disable user hand controllers if they are too far away or not moving.
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  libraries/shared/src/AtRestDetector.cpp
  libraries/shared/src/AtRestDetector.h
Labels: Avatar, Development Approved, Project Approved, QA Approved :tada:

#14015 Add automated daily tests
  tools/auto-tester/AppDataHighFidelity/Interface.json
  tools/auto-tester/AppDataHighFidelity/Interface/AccountInfo.bin
  tools/auto-tester/AppDataHighFidelity/Interface/avatarbookmarks.json
  tools/auto-tester/AppDataHighFidelity/assignment-client/entities/models.json.gz
  tools/auto-tester/AppDataHighFidelity/domain-server/AccountInfo.bin
  tools/auto-tester/AppDataHighFidelity/domain-server/config.json
  tools/auto-tester/AppDataHighFidelity/domain-server/entities/models.json.gz
  tools/auto-tester/CMakeLists.txt
  tools/auto-tester/Create.PNG
  tools/auto-tester/Evaluate.PNG
  tools/auto-tester/README.md
  tools/auto-tester/Run.PNG
  tools/auto-tester/TestRail.PNG
  tools/auto-tester/Web Interface.PNG
  tools/auto-tester/WebInterface.PNG
  tools/auto-tester/Windows.PNG
  tools/auto-tester/src/AWSInterface.cpp
  tools/auto-tester/src/AWSInterface.h
  tools/auto-tester/src/Downloader.cpp
  tools/auto-tester/src/Downloader.h
  tools/auto-tester/src/PythonInterface.cpp
  tools/auto-tester/src/PythonInterface.h
  tools/auto-tester/src/Test.cpp
  tools/auto-tester/src/Test.h
  tools/auto-tester/src/TestRailInterface.cpp
  tools/auto-tester/src/TestRailInterface.h
  tools/auto-tester/src/TestRunner.cpp
  tools/auto-tester/src/TestRunner.h
  tools/auto-tester/src/common.h
  tools/auto-tester/src/main.cpp
  tools/auto-tester/src/ui/AutoTester.cpp
  tools/auto-tester/src/ui/AutoTester.h
  tools/auto-tester/src/ui/AutoTester.ui
  tools/auto-tester/src/ui/MismatchWindow.cpp
  tools/auto-tester/src/ui/MismatchWindow.h
  tools/auto-tester/src/ui/TestRailResultsSelectorWindow.cpp
  tools/auto-tester/src/ui/TestRailRunSelectorWindow.cpp
  tools/auto-tester/src/ui/TestRailTestCasesSelectorWindow.cpp
Labels: Engine, Project Approved, QA Approved :tada:

#14144 Fix and fill in JSDoc for MyAvatar flying-related functions
  interface/src/avatar/MyAvatar.h
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#14145 JSDoc fixes
  interface/src/avatar/AvatarManager.h
  libraries/avatars/src/AvatarHashMap.h
  libraries/pointers/src/Pick.h
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#14242 Fix light color serialization
  libraries/entities/src/EntityItemProperties.cpp
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
Labels: Development Approved, Engine, Packet Version Change, Project Approved, QA Approved :tada:, bug

#14225 hide progress overlays if interstitial mode
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/scripting/WindowScriptingInterface.cpp
  interface/src/scripting/WindowScriptingInterface.h
  scripts/system/interstitialPage.js
  scripts/system/libraries/globals.js
  scripts/system/progress.js
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14234 18518 - Make record.js unsubscribe from messaging channel
  unpublishedScripts/marketplace/record/record.js
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14170 Fix non-avatar agents appearing as avatars
  assignment-client/src/Agent.cpp
  assignment-client/src/avatars/AvatarMixerSlave.cpp
  assignment-client/src/avatars/ScriptableAvatar.h
Labels: Development Approved, Project Approved, QA Approved :tada:, Server & Network

#13889 Updating highlight textures on Rift Controller
  interface/resources/meshes/controller/touch/touch_l_bumper.fbx
  interface/resources/meshes/controller/touch/touch_l_button_x.fbx
  interface/resources/meshes/controller/touch/touch_l_button_y.fbx
  interface/resources/meshes/controller/touch/touch_l_joystick.fbx
  interface/resources/meshes/controller/touch/touch_l_trigger.fbx
  interface/resources/meshes/controller/touch/touch_r_bumper.fbx
  interface/resources/meshes/controller/touch/touch_r_button_a.fbx
  interface/resources/meshes/controller/touch/touch_r_button_b.fbx
  interface/resources/meshes/controller/touch/touch_r_joystick.fbx
  interface/resources/meshes/controller/touch/touch_r_trigger.fbx
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14157 Cap the number of domain-server duplicate check-ins sent upon retransmission
  libraries/networking/src/NodeList.cpp
Labels: Development Approved, Project Approved, QA Approved :tada:, Server & Network

#14222 Fix material entity opacity maps
  libraries/entities-renderer/src/RenderableMaterialEntityItem.cpp
  libraries/entities-renderer/src/RenderableMaterialEntityItem.h
  libraries/model-networking/src/model-networking/ModelCache.cpp
  libraries/model-networking/src/model-networking/ModelCache.h
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:, bug

#13979 minor bug fix and optimization in ModelEntity animation
  libraries/animation/src/AnimationCache.h
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.h
  libraries/entities/src/ModelEntityItem.cpp
  libraries/entities/src/ModelEntityItem.h
Labels: Engine, Project Approved, QA Approved :tada:

#14037 fix agent audio packet send when encoder is flushed
  assignment-client/src/Agent.cpp
Labels: Development Approved, Project Approved, QA Approved :tada:, Server & Network

#14207 Remove pending avatars data structure
  interface/src/avatar/AvatarManager.cpp
  libraries/avatars/src/AvatarHashMap.cpp
  libraries/avatars/src/AvatarHashMap.h
Labels: Development Approved, Project Approved, QA Approved :tada:, Server & Network

#14125 Fix new Mac warnings
  domain-server/src/DomainServer.cpp
  interface/src/raypick/CollisionPick.h
  interface/src/raypick/PathPointer.h
  libraries/animation/src/AnimVariant.cpp
  libraries/controllers/src/controllers/InputDevice.h
  libraries/controllers/src/controllers/impl/Conditional.h
  libraries/controllers/src/controllers/impl/Filter.h
  libraries/controllers/src/controllers/impl/conditionals/AndConditional.h
  libraries/controllers/src/controllers/impl/conditionals/EndpointConditional.h
  libraries/controllers/src/controllers/impl/conditionals/NotConditional.h
  libraries/controllers/src/controllers/impl/filters/ClampFilter.h
  libraries/controllers/src/controllers/impl/filters/ConstrainToIntegerFilter.h
  libraries/controllers/src/controllers/impl/filters/ConstrainToPositiveIntegerFilter.h
  libraries/controllers/src/controllers/impl/filters/DeadZoneFilter.h
  libraries/controllers/src/controllers/impl/filters/ExponentialSmoothingFilter.h
  libraries/controllers/src/controllers/impl/filters/HysteresisFilter.h
  libraries/controllers/src/controllers/impl/filters/InvertFilter.h
  libraries/controllers/src/controllers/impl/filters/LowVelocityFilter.h
  libraries/controllers/src/controllers/impl/filters/NotFilter.h
  libraries/controllers/src/controllers/impl/filters/PostTransformFilter.h
  libraries/controllers/src/controllers/impl/filters/PulseFilter.h
  libraries/controllers/src/controllers/impl/filters/RotateFilter.h
  libraries/controllers/src/controllers/impl/filters/ScaleFilter.h
  libraries/controllers/src/controllers/impl/filters/TransformFilter.h
  libraries/controllers/src/controllers/impl/filters/TranslateFilter.h
  libraries/gpu-gl-common/src/gpu/gl/GLShared.h
  libraries/gpu-gl-common/src/gpu/gl/GLTexture.h
  libraries/gpu/src/gpu/State.h
  libraries/graphics/src/graphics/Material.h
  libraries/input-plugins/src/input-plugins/KeyboardMouseDevice.h
  libraries/model-networking/src/model-networking/ModelCache.h
  libraries/plugins/src/plugins/InputPlugin.h
  libraries/pointers/src/Pick.h
  libraries/render-utils/src/GeometryCache.cpp
  libraries/render-utils/src/MeshPartPayload.h
  libraries/render/src/render/Item.h
  libraries/shared/src/NestableTransformNode.h
  libraries/shared/src/PrioritySortUtil.h
  libraries/shared/src/TransformNode.h
  libraries/task/src/task/Task.h
  plugins/hifiNeuron/src/NeuronPlugin.h
  tests/recording/src/main.cpp
Labels: Development Approved, Project Approved, QA Approved :tada:, Server & Network

#14189 Increase content archive upload timeout
  domain-server/resources/web/content/js/content.js
Labels: Project Approved, QA Approved :tada:, Server & Network

#14181 Timebox packet processing
  libraries/networking/src/udt/Socket.cpp
  libraries/networking/src/udt/Socket.h
Labels: Development Approved, Project Approved, QA Approved :tada:, Server & Network

#14220 Fix PickManager::removePick heap use after free
  libraries/pointers/src/PickManager.cpp
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14217 Squelch cmake warning CMP0074 without requiring an update to cmake 3.12.
  CMakeLists.txt
Labels: Avatar, Client, Development Approved, Project Approved, QA Approved :tada:, Server & Network

#14163 Fix crash with BandwidthRecorder
  interface/src/Application.h
  libraries/networking/src/BandwidthRecorder.cpp
  libraries/networking/src/BandwidthRecorder.h
  libraries/networking/src/NetworkPeer.cpp
  libraries/networking/src/NetworkPeer.h
Labels: Development Approved, Project Approved, QA Approved :tada:, Server & Network

#14245 Add a 'grabbable' option to the new-model dialog
  interface/resources/qml/hifi/tablet/NewModelDialog.qml
  scripts/system/edit.js
Labels: Create, Development Approved, Project Approved, QA Ready

#14226 Only track stats for compatible packets
  interface/src/octree/OctreePacketProcessor.cpp
Labels: Development Approved, Project Approved, QA Ready, Server & Network

#14176 Add additional safety checks to gl::Uniform::load
  libraries/gl/src/gl/GLShaders.cpp
Labels: Development Approved, Engine, Project Approved, QA Ready

#14257 Bug 19488: Fix access to uniforms at index 0
  libraries/gl/src/gl/GLShaders.cpp
Labels: Development Approved, Engine, Project Approved, QA Ready

#14049 update some server console dependencies after npm audit
  server-console/package-lock.json
  server-console/package.json
  server-console/src/main.js
Labels: Development Approved, Project Approved, QA Approved :tada:, Server & Network

#13884 Highlight tablet when it is near-grabbable
  scripts/system/controllers/controllerDispatcher.js
  scripts/system/controllers/controllerModules/farActionGrabEntity.js
  scripts/system/controllers/controllerModules/farActionGrabEntityDynOnly.js
  scripts/system/controllers/controllerModules/farParentGrabEntity.js
  scripts/system/controllers/controllerModules/inEditMode.js
  scripts/system/controllers/controllerModules/inVREditMode.js
  scripts/system/controllers/controllerModules/nearTabletHighlight.js
  scripts/system/controllers/controllerModules/stylusInput.js
  scripts/system/controllers/controllerModules/webSurfaceLaserInput.js
  scripts/system/controllers/controllerScripts.js
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14235 Add copy/paste functionality to edit.js
  interface/resources/controllers/keyboardMouse.json
  scripts/system/edit.js
  scripts/system/libraries/entityCameraTool.js
  scripts/system/libraries/entitySelectionTool.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#14183 Add ccache support for Linux and Mac
  cmake/compiler.cmake
  cmake/macros/ConfigureCCache.cmake
  cmake/templates/launch-c.in
  cmake/templates/launch-cxx.in
Labels: Development Approved, Project Approved, QA Approved :tada:, Server & Network

#14249 Merged interstitial bug fixes
  scripts/system/assets/models/black-sphere.fbx
  scripts/system/assets/sounds/crystals_and_voices.mp3
  scripts/system/controllers/controllerModules/farActionGrabEntity.js
  scripts/system/controllers/controllerModules/teleport.js
  scripts/system/controllers/controllerModules/webSurfaceLaserInput.js
  scripts/system/interstitialPage.js
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14192 Prevent race on internal client traits members
  assignment-client/src/Agent.h
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  libraries/avatars/src/ClientTraitsHandler.cpp
  libraries/avatars/src/ClientTraitsHandler.h
Labels: Development Approved, Project Approved, QA Ready, Server & Network

#14260 Fix ResourceCache crash on shutdown
  libraries/networking/src/ResourceCache.cpp
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14232 Display resource-access events in marketplace item tester
  assignment-client/src/Agent.cpp
  assignment-client/src/AssignmentClient.cpp
  interface/resources/qml/hifi/commerce/marketplaceItemTester/ItemUnderTest.qml
  interface/resources/qml/hifi/commerce/marketplaceItemTester/MarketplaceItemTester.qml
  interface/resources/qml/hifi/commerce/marketplaceItemTester/spinner.gif
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/assets/ATPAssetMigrator.cpp
  interface/src/commerce/QmlCommerce.cpp
  interface/src/commerce/QmlCommerce.h
  interface/src/scripting/ClipboardScriptingInterface.cpp
  interface/src/scripting/ClipboardScriptingInterface.h
  interface/src/ui/overlays/Web3DOverlay.cpp
  libraries/avatars/src/AvatarData.cpp
  libraries/entities/src/EntityEditFilters.cpp
  libraries/fbx/src/GLTFReader.cpp
  libraries/fbx/src/OBJReader.cpp
  libraries/model-networking/src/model-networking/TextureCache.cpp
  libraries/networking/src/AssetResourceRequest.cpp
  libraries/networking/src/AssetResourceRequest.h
  libraries/networking/src/AtpReply.cpp
  libraries/networking/src/FileResourceRequest.h
  libraries/networking/src/HTTPResourceRequest.h
  libraries/networking/src/ResourceCache.cpp
  libraries/networking/src/ResourceManager.cpp
  libraries/networking/src/ResourceManager.h
  libraries/networking/src/ResourceRequest.cpp
  libraries/networking/src/ResourceRequest.h
  libraries/octree/src/Octree.cpp
  libraries/octree/src/Octree.h
  libraries/script-engine/src/FileScriptingInterface.cpp
  libraries/script-engine/src/ScriptCache.cpp
  libraries/script-engine/src/XMLHttpRequestClass.cpp
  libraries/shared/src/ResourceRequestObserver.cpp
  libraries/shared/src/ResourceRequestObserver.h
  scripts/system/marketplaces/marketplaces.js
Labels: Commerce, Development Approved, Project Approved, QA Approved :tada:

#14186 MS19056: [CreateApp/Entity List] Context Menu
  scripts/system/html/css/edit-style.css
  scripts/system/html/entityList.html
  scripts/system/html/js/entityList.js
  scripts/system/html/js/entityListContextMenu.js
  scripts/system/libraries/entityList.js
  scripts/system/libraries/entitySelectionTool.js
Labels: Create, Development Approved, Feedback Welcome, Project Approved, QA Approved :tada:

#14214 Update default entity properties in Create
  scripts/system/edit.js
Labels: Create, Development Approved, Feedback Welcome, Project Approved, QA Approved :tada:

#14253 Case 19446 - Update via Sandbox Popup -- opens Old Interface
  server-console/src/main.js
  server-console/src/modules/hf-notifications.js
Labels: Development Approved, Discovery, Project Approved, QA Approved :tada:, bug

#14149 MS19054: [CreateApp/EntityList] auto scroll
  scripts/system/edit.js
  scripts/system/html/js/entityList.js
  scripts/system/html/js/listView.js
  scripts/system/libraries/entityList.js
  scripts/system/libraries/entitySelectionTool.js
Labels: Create, Development Approved, Feedback Welcome, Project Approved, QA Approved :tada:

#14187 Add animations to Avatar Transit
  interface/resources/avatar/network-animation.json
  interface/src/avatar/AvatarActionHold.cpp
  interface/src/avatar/AvatarManager.cpp
  interface/src/avatar/AvatarManager.h
  interface/src/avatar/MyAvatar.cpp
  libraries/animation/src/AnimClip.h
  libraries/animation/src/Rig.cpp
  libraries/animation/src/Rig.h
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
Labels: Avatar, Development Approved, Project Approved, QA Approved :tada:

#14243 Small avatars now have a minimum jump height of 0.25 meters
  interface/src/avatar/MySkeletonModel.cpp
  libraries/animation/src/Rig.cpp
  libraries/animation/src/Rig.h
  libraries/physics/src/CharacterController.cpp
  libraries/shared/src/AvatarConstants.h
Labels: Avatar, Development Approved, Project Approved, QA Approved :tada:

#14172 Entity properties refactor / reorder and merge particle explorer into properties
  interface/resources/qml/hifi/tablet/EditTabView.qml
  interface/resources/qml/hifi/tablet/EditToolsTabView.qml
  scripts/system/edit.js
  scripts/system/html/css/edit-style.css
  scripts/system/html/entityProperties.html
  scripts/system/html/js/entityProperties.js
  scripts/system/html/js/underscore-min.js
Labels: Create, Development Approved, HMD required, Project Approved, QA Approved :tada:

#14269 Possible fix for yet another blendshape crash
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
Labels: Engine, Project Approved, QA Approved :tada:, bug

#13904 Resorting Developer menu organization
  interface/src/Menu.cpp
  scripts/defaultScripts.js
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14274 Add optional default scripts log suppression to the script debug window
  scripts/developer/debugging/debugWindow.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#14262 Fix and expose Particle Entity emitRadiusStart
  libraries/entities/src/ParticleEffectEntityItem.cpp
  libraries/entities/src/ParticleEffectEntityItem.h
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, Engine, Project Approved, QA Approved :tada:

#14279 Remove particle explorer
  scripts/system/particle_explorer/hifi-entity-ui.js
  scripts/system/particle_explorer/particle-style.css
  scripts/system/particle_explorer/particleExplorer.html
  scripts/system/particle_explorer/particleExplorer.js
  scripts/system/particle_explorer/particleExplorerTool.js
  scripts/system/particle_explorer/underscore-min.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#14229 MS19052 [CreateApp]: Tooltips
  scripts/system/assets/data/createAppTooltips.json
  scripts/system/edit.js
  scripts/system/html/css/edit-style.css
  scripts/system/html/entityProperties.html
  scripts/system/html/js/createAppTooltip.js
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, Feedback Welcome, HMD required, Project Approved, QA Approved :tada:

#14246 keep userData and new grab properties in sync
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityScriptingInterface.cpp
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/EntityTree.h
  libraries/entities/src/GrabPropertyGroup.cpp
  scripts/system/controllers/controllerModules/equipEntity.js
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14281 Fix Collides With subproperties
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#14123 Additional Mac OpenGL work
  CMakeLists.txt
  interface/src/Application.cpp
  interface/src/main.cpp
  interface/src/ui/ApplicationOverlay.cpp
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.cpp
  libraries/entities-renderer/src/RenderableWebEntityItem.cpp
  libraries/gl/src/gl/Context.cpp
  libraries/gl/src/gl/Context.h
  libraries/gl/src/gl/ContextQt.cpp
  libraries/gl/src/gl/GLHelpers.cpp
  libraries/gl/src/gl/GLHelpers.h
  libraries/gl/src/gl/GLWidget.cpp
  libraries/gl/src/gl/GLWidget.h
  libraries/gl/src/gl/GLWindow.cpp
  libraries/gl/src/gl/OffscreenGLCanvas.cpp
  libraries/gl/src/gl/OffscreenGLCanvas.h
  libraries/gl/src/gl/QOpenGLContextWrapper.cpp
  libraries/gl/src/gl/QOpenGLContextWrapper.h
  libraries/gpu-gl-common/src/gpu/gl/GLBackend.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLBackend.h
  libraries/qml/src/qml/impl/RenderEventHandler.cpp
  libraries/qml/src/qml/impl/TextureCache.cpp
  tests-manual/qml/qml/MacQml.qml
  tests-manual/qml/src/MacQml.cpp
  tests-manual/qml/src/MacQml.h
  tests-manual/qml/src/StressWeb.cpp
  tests-manual/qml/src/StressWeb.h
  tests-manual/qml/src/TestCase.cpp
  tests-manual/qml/src/TestCase.h
  tests-manual/qml/src/main.cpp
Labels: Android Smoke Required, Engine, Mac Required, Project Approved, QA Approved :tada:

#14286 Fix Interface eating memory when minimized
  interface/src/Application.cpp
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14291 Fix avatars remain stuck in place for other users intermittently [v0.75.0-rc]
  interface/src/avatar/AvatarManager.cpp
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
Labels: Avatar, Development Approved, Project Approved, QA Approved :tada:

#14288 Fix avatars remain stuck in place for other users intermittently
  interface/src/avatar/AvatarManager.cpp
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
Labels: Avatar, Development Approved, Project Approved, QA Approved :tada:

#14296 RC 75: Fix shape not getting marked changed
  libraries/entities/src/EntityItemProperties.cpp
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:, bug

#14295 Fix shape not getting marked changed
  libraries/entities/src/EntityItemProperties.cpp
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:, bug

#14302 Don't update QueryAACube in setParentID if _parentID didn't change
  libraries/shared/src/SpatiallyNestable.cpp
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14304 RC75: avoid ambiguous RTT calcs and enable udt fast retransmit
  libraries/networking/src/udt/CongestionControl.h
  libraries/networking/src/udt/Connection.cpp
  libraries/networking/src/udt/SendQueue.cpp
  libraries/networking/src/udt/TCPVegasCC.cpp
  libraries/networking/src/udt/TCPVegasCC.h
Labels: Development Approved, Project Approved, QA Approved :tada:, Server & Network

#14306 Case 19495 for v0.75.0-rc: zero velocities of non-dynamic entities on nearGrab release
  scripts/system/controllers/controllerModules/farParentGrabEntity.js
  scripts/system/controllers/controllerModules/nearParentGrabEntity.js
Labels: Client, Development Approved, Engine, Project Approved, QA Approved :tada:

#14314 avoid ambiguous RTT calcs and enable udt fast retransmit
  libraries/networking/src/udt/CongestionControl.h
  libraries/networking/src/udt/Connection.cpp
  libraries/networking/src/udt/SendQueue.cpp
  libraries/networking/src/udt/TCPVegasCC.cpp
  libraries/networking/src/udt/TCPVegasCC.h
Labels: Development Approved, Project Approved, QA Approved :tada:, Server & Network
