Repository highfidelity/hifi, pull requests merged in 2019-04, with the labels that each got.

#15300 Case 21993: Globally disallow use of the camera or microphone by hosted web content
  interface/src/Application.cpp
  libraries/networking/src/udt/PacketHeaders.h
Labels: Development Approved, QA Ready

#15305 Case 22003: Reuse Blank Space from Volume Slider
  interface/resources/qml/hifi/NameCard.qml
Labels: Design, Development Approved, Project Approved

#15285 Case 21415: Avatars stay behind after they disconnect
  interface/src/avatar/AvatarManager.cpp
  interface/src/avatar/AvatarManager.h
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/OtherAvatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
  libraries/avatars/src/AvatarHashMap.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.h
  libraries/entities-renderer/src/RenderableEntityItem.cpp
  libraries/render/src/render/Scene.cpp
  libraries/render/src/render/Scene.h
  libraries/render/src/render/Transition.h
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Ready

#15304 case 22001: Fixed calls to addingWearable() and deletingWearable()
  libraries/entities/src/EntityScriptingInterface.cpp
Labels: Development Approved, Engine, Project Approved

#15270 Case 20964, 21758: Avatar Exporter v0.4.1 - bone rule fixes
  tools/unity-avatar-exporter/Assets/Editor/AvatarExporter/AvatarExporter.cs
  tools/unity-avatar-exporter/Assets/README.txt
  tools/unity-avatar-exporter/avatarExporter.unitypackage
Labels: Avatar, Create, Development Approved, Project Approved

#15293 Case 20826: Add damping to new dynamic entities in Create
  scripts/system/edit.js
Labels: Create, Development Approved, Project Approved

#15286 Case 20928: Fix some URLs with query params not working with model baker
  libraries/baking/src/baking/BakerLibrary.cpp
Labels: Create, Development Approved, Project Approved

#15309 Case 22010: Bump protocol number to fix joint order mismatch
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
Labels: Avatar, Development Approved, Packet Version Change, Project Approved

#15287 Case 21893: Remove disabling of --url for Android.
  interface/src/Application.cpp
Labels: Android, Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:, Quest Required

#15314 Case 20991: more correct collision group during grabs
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/physics/src/EntityMotionState.cpp
Labels: Development Approved, Engine, Project Approved

#15275 DDV all, including domainUnlimited
  assignment-client/src/entities/EntityServer.cpp
  interface/src/commerce/Ledger.h
  interface/src/commerce/QmlCommerce.h
  interface/src/commerce/Wallet.cpp
  interface/src/ui/overlays/ContextOverlayInterface.cpp
  interface/src/ui/overlays/ContextOverlayInterface.h
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/EntityTree.h
Labels: Development Approved, Metaverse, Project Approved

#15237 Case 21859: Particle Entity emitter shapes, including model
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities-renderer/src/RenderableParticleEffectEntityItem.cpp
  libraries/entities-renderer/src/RenderableParticleEffectEntityItem.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/LineEntityItem.h
  libraries/entities/src/ModelEntityItem.h
  libraries/entities/src/ParticleEffectEntityItem.cpp
  libraries/entities/src/ParticleEffectEntityItem.h
  libraries/entities/src/ShapeEntityItem.h
  libraries/entities/src/ZoneEntityItem.cpp
  libraries/entities/src/ZoneEntityItem.h
  libraries/networking/src/udt/PacketHeaders.h
  libraries/shared/src/GeometryUtil.cpp
  libraries/shared/src/GeometryUtil.h
  scripts/system/assets/data/createAppTooltips.json
  scripts/system/html/js/entityProperties.js
Labels: Development Approved, Engine, Packet Version Change, Project Approved

#15308 Case 20410 - Automatic Content Archives doesn't restore correctly with old Tutorial content set
  domain-server/src/DomainServer.cpp
  libraries/octree/src/OctreeEntitiesFileParser.cpp
Labels: Development Approved, Metaverse, Project Approved, bug

#15122 Case 21502: skinned gltf
  libraries/fbx/src/GLTFSerializer.cpp
  libraries/fbx/src/GLTFSerializer.h
Labels: Development Approved, Engine, Project Approved

#15317 Case 21730: Restore composite framebuffer to display plugins
  libraries/display-plugins/src/display-plugins/Basic2DWindowOpenGLDisplayPlugin.cpp
  libraries/display-plugins/src/display-plugins/Basic2DWindowOpenGLDisplayPlugin.h
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.cpp
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.h
  libraries/display-plugins/src/display-plugins/hmd/DebugHmdDisplayPlugin.h
  libraries/display-plugins/src/display-plugins/hmd/HmdDisplayPlugin.cpp
  libraries/display-plugins/src/display-plugins/hmd/HmdDisplayPlugin.h
  libraries/display-plugins/src/display-plugins/stereo/InterleavedStereoDisplayPlugin.cpp
  libraries/display-plugins/src/display-plugins/stereo/InterleavedStereoDisplayPlugin.h
  libraries/oculusMobilePlugin/src/OculusMobileDisplayPlugin.cpp
  libraries/oculusMobilePlugin/src/OculusMobileDisplayPlugin.h
  libraries/plugins/src/plugins/DisplayPlugin.cpp
  libraries/plugins/src/plugins/DisplayPlugin.h
  libraries/render-utils/src/RenderCommonTask.cpp
  libraries/render/src/render/Args.h
  plugins/oculus/src/OculusDebugDisplayPlugin.h
  plugins/oculus/src/OculusDisplayPlugin.cpp
  plugins/oculus/src/OculusDisplayPlugin.h
  plugins/oculusLegacy/src/OculusLegacyDisplayPlugin.cpp
  plugins/oculusLegacy/src/OculusLegacyDisplayPlugin.h
  plugins/openvr/src/OpenVrDisplayPlugin.cpp
  plugins/openvr/src/OpenVrDisplayPlugin.h
Labels: Android Smoke Required, Development Approved, PRE-MERGE TESTING REQUIRED, QA Approved :tada:

#15311 Case 21415: Avatars stay behind after they disconnect
  interface/src/avatar/AvatarManager.cpp
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, QA Approved :tada:

#15264 Case 22045: Added support for OpenEXR files (mostly for skyboxes)
  assignment-client/src/assets/AssetServer.cpp
  cmake/macros/TargetOpenEXR.cmake
  cmake/ports/hifi-deps/CONTROL
  cmake/ports/openexr/CONTROL
  cmake/ports/openexr/FindOpenEXR.cmake
  cmake/ports/openexr/fix_install_ilmimf.patch
  cmake/ports/openexr/portfile.cmake
  libraries/baking/src/TextureBaker.cpp
  libraries/baking/src/TextureBaker.h
  libraries/baking/src/baking/TextureFileNamer.h
  libraries/graphics-scripting/src/graphics-scripting/ScriptableModel.cpp
  libraries/image/CMakeLists.txt
  libraries/image/src/image/Image.cpp
  libraries/image/src/image/Image.h
  libraries/image/src/image/OpenEXRReader.cpp
  libraries/image/src/image/OpenEXRReader.h
  libraries/image/src/image/TGAReader.cpp
  libraries/image/src/image/TGAReader.h
  libraries/image/src/image/TextureProcessing.cpp
  libraries/image/src/image/TextureProcessing.h
  libraries/material-networking/src/material-networking/TextureCache.cpp
  libraries/material-networking/src/material-networking/TextureCache.h
  tools/oven/src/Oven.cpp
  tools/oven/src/OvenCLIApplication.cpp
Labels: Development Approved, Engine, Project Approved

#15312 Case 19858 - crashpad_handler is duplicated outside of the Interface/…
  cmake/macros/AddCrashpad.cmake
Labels: Development Approved, Metaverse, Project Approved, bug

#15313 Case 22021: specific thresholds per GPU vendor v3.2.0
  tools/nitpick/src/AWSInterface.cpp
  tools/nitpick/src/Nitpick.cpp
  tools/nitpick/src/Nitpick.h
  tools/nitpick/src/Platform.cpp
  tools/nitpick/src/Platform.h
  tools/nitpick/src/TestCreator.cpp
  tools/nitpick/src/TestCreator.h
  tools/nitpick/src/common.h
  tools/nitpick/ui/Nitpick.ui
Labels: Development Approved, Engine, Project Approved, nitpick

#15324 Case 22054: flat models can introduce nan into geometry
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
Labels: Development Approved, Engine, Project Approved

#15322 Case 18299: Fix ScriptEngine not being destroyed on its own thread
  libraries/script-engine/src/ScriptEngine.cpp
Labels: Create, Development Approved, Project Approved

#14738 Case 21777: Locomotion Project
  interface/resources/controllers/oculus_touch.json
  interface/resources/controllers/standard.json
  interface/resources/controllers/vive.json
  interface/src/Application.cpp
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  interface/src/ui/PreferencesDialog.cpp
  libraries/shared/src/AvatarConstants.h
  scripts/system/controllers/controllerModules/farGrabEntity.js
  scripts/system/controllers/controllerModules/teleport.js
  scripts/system/controllers/controllerScripts.js
  scripts/system/libraries/controllerDispatcherUtils.js
  scripts/system/tablet-ui/tabletUI.js
Labels: Design, Development Approved, HMD required, PRE-MERGE TESTING REQUIRED, Project Approved, Scripting API change

#15326 Lambda capture was referencing something on the local stack
  libraries/entities/src/EntityTree.cpp
Labels: Development Approved, Metaverse, Project Approved, bug

#15318 Case 22025 - Create temporary placename doesn't appear when no places are listed
  domain-server/resources/web/settings/js/settings.js
Labels: Development Approved, Development Ready, Metaverse, Project Approved

#15263 AnimationCache, ModelCache, SoundCache, and TextureCache JSDoc
  libraries/animation/src/AnimationCache.h
  libraries/animation/src/AnimationCacheScriptingInterface.h
  libraries/animation/src/AnimationObject.h
  libraries/audio/src/Sound.h
  libraries/audio/src/SoundCacheScriptingInterface.h
  libraries/hfm/src/hfm/HFM.h
  libraries/image/src/image/TextureProcessing.h
  libraries/material-networking/src/material-networking/TextureCacheScriptingInterface.h
  libraries/model-networking/src/model-networking/ModelCacheScriptingInterface.h
  libraries/networking/src/ResourceCache.h
  libraries/networking/src/ResourceScriptingInterface.h
  libraries/script-engine/src/AudioScriptingInterface.h
  libraries/script-engine/src/ScriptEngine.cpp
  tools/jsdoc/plugins/hifi.js
Labels: Development Ready, JSDocs

#15277 Case 20896: Fix continual edit handle translation when moving
  scripts/system/libraries/entitySelectionTool.js
Labels: Create, Development Approved, Project Approved, bug

#15291 Fix avatar multi-sphere bad scaling on some avatars
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/physics/src/MultiSphereShape.cpp
  libraries/physics/src/MultiSphereShape.h
Labels: Avatar, Development Approved, Project Approved

#15296 Add joint rotation offset to the avatar multi-sphere shapes
  libraries/fbx/src/FBXSerializer.cpp
  libraries/hfm/src/hfm/HFM.cpp
  libraries/hfm/src/hfm/HFM.h
  libraries/model-baker/src/model-baker/Baker.cpp
  libraries/physics/src/CharacterController.cpp
Labels: Avatar, Development Approved, Project Approved

#15290 Case 20880: Fix delete key doing ctrl + delete in HMD
  interface/src/Menu.cpp
Labels: Client, Development Approved, Project Approved, bug

#15328 Case 21925: Warn mixer about stopped injectors
  assignment-client/src/audio/AudioMixer.cpp
  assignment-client/src/audio/AudioMixerClientData.cpp
  assignment-client/src/audio/AudioMixerClientData.h
  libraries/audio/src/AudioInjector.cpp
  libraries/audio/src/AudioInjector.h
  libraries/audio/src/AudioInjectorManager.cpp
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
Labels: Development Approved, Metaverse, Project Approved

#15333 Case 22070: Revert "Case 20060: Grab correct stencil masks from display plugins"
  cmake/externals/LibOVR/CMakeLists.txt
  interface/src/Application.cpp
  libraries/display-plugins/src/display-plugins/hmd/HmdDisplayPlugin.h
  libraries/graphics/src/graphics/Geometry.cpp
  libraries/plugins/src/plugins/DisplayPlugin.h
  libraries/render-utils/src/StencilMaskPass.cpp
  libraries/render-utils/src/StencilMaskPass.h
  libraries/render/src/render/Args.h
  libraries/shared/src/RegisteredMetaTypes.cpp
  libraries/shared/src/RegisteredMetaTypes.h
  libraries/shared/src/StencilMode.h
  plugins/oculus/CMakeLists.txt
  plugins/oculus/src/OculusBaseDisplayPlugin.cpp
  plugins/oculus/src/OculusBaseDisplayPlugin.h
  plugins/openvr/src/OpenVrDisplayPlugin.cpp
  plugins/openvr/src/OpenVrDisplayPlugin.h
Labels: Development Approved, Engine, Project Approved

#15340 Case 21890 - Marketplace search doesn't refresh when enter is pressed
  interface/resources/qml/hifi/commerce/marketplace/Marketplace.qml
Labels: Development Approved, Metaverse, Project Approved, bug

#15276 Case 20739: Add new web and base properties to Create
  scripts/system/assets/data/createAppTooltips.json
  scripts/system/html/js/createAppTooltip.js
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, Project Approved

#15337 Case22025 - Show 'create temporary place' button when no places are present
  domain-server/resources/web/js/shared.js
  domain-server/resources/web/settings/js/settings.js
  domain-server/src/DomainServer.cpp
Labels: Development Approved, Metaverse, Project Approved

#15342 Case 20513: Extra check to make sure we remove materials from MyAvatar
  libraries/avatars/src/AvatarHashMap.cpp
  libraries/entities-renderer/src/RenderableMaterialEntityItem.cpp
Labels: Development Approved, Engine, Project Approved

#15338 Case 22074: Avatars ignored via PAL or bubble (shield) leave semi-permanent copies of themselves
  interface/src/avatar/AvatarManager.cpp
Labels: Development Approved, Engine, Project Approved

#15336 Case 22069: Update Controller Help Screen
  interface/resources/html/img/tablet-help-gamepad.jpg
  interface/resources/html/img/tablet-help-keyboard.jpg
  interface/resources/html/img/tablet-help-oculus.jpg
  interface/resources/html/img/tablet-help-vive.jpg
  interface/resources/html/img/tablet-help-windowsMR.jpg
  interface/resources/html/tabletHelp.html
Labels: Design, Development Approved, Project Approved

#15325 Case 20738: add dynamic multiselect for material target property
  scripts/system/edit.js
  scripts/system/html/css/edit-style.css
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, Project Approved

#15343 Fix error extracting SIM joints on Flow
  libraries/animation/src/Flow.cpp
Labels: Avatar, Development Approved, Project Approved

#15281 case 21980: Allow copying grandchild entities
  scripts/system/edit.js
  scripts/system/libraries/entitySelectionTool.js
Labels: Create, Development Approved, Project Approved

#15346 (RC82) Fix out of bounds computing KDOPs when the model url is incorrect
  libraries/hfm/src/hfm/HFM.cpp
Labels: Avatar, Development Approved, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#15347 Fix out of bounds computing KDOPs when the model url is incorrect
  libraries/hfm/src/hfm/HFM.cpp
Labels: Avatar, Development Approved, PRE-MERGE TESTING REQUIRED, Project Approved

#15359 Case 22107: Use # instead of ? for material URL name selection (82)
  libraries/baking/src/ModelBaker.cpp
  libraries/entities-renderer/src/RenderableMaterialEntityItem.cpp
  libraries/entities/src/EntityItemProperties.cpp
  libraries/render-utils/src/Model.cpp
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#15358 Case 22108: Use # instead of ? for material URL name selection
  libraries/baking/src/ModelBaker.cpp
  libraries/entities-renderer/src/RenderableMaterialEntityItem.cpp
  libraries/entities/src/EntityItemProperties.cpp
  libraries/render-utils/src/Model.cpp
Labels: Development Approved, Engine, Project Approved

#15349 Case 22095: Disable JSBaker for now (RC82)
  tools/oven/src/BakerCLI.cpp
  tools/oven/src/DomainBaker.cpp
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#15348 Case 22093: Disable JSBaker for now
  tools/oven/src/BakerCLI.cpp
  tools/oven/src/DomainBaker.cpp
  tools/oven/src/OvenCLIApplication.cpp
Labels: Development Approved, Engine

#15267 Case 21930: Don't change OpenGL context state every frame
  interface/src/Application.cpp
  interface/src/Application.h
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.cpp
  libraries/shared/src/Profile.cpp
  libraries/shared/src/Profile.h
  libraries/shared/src/Trace.cpp
  libraries/shared/src/Trace.h
Labels: Development Approved, Engine, Project Approved

#15283 case 21978: Eliminated some JavaScript warnings due to missing commas
  scripts/tutorials/makeBlocks.js
  unpublishedScripts/DomainContent/Toybox/basketball/createHoop.js
Labels: Development Approved, Engine, Project Approved

#15280 case 21981: Fix startup race conditions in Interface
  interface/src/Application.cpp
  interface/src/Application.h
Labels: Development Approved, Engine, Project Approved

#15302 case 21994: cooperate, rather than fight with, Linux window managers
  interface/src/main.cpp
  interface/src/ui/DialogsManager.cpp
Labels: Client, Development Approved, Engine, Project Approved

#15307 Case 22019: Audio clicks/pops when gain is rapidly changing
  assignment-client/src/audio/AudioMixerSlave.cpp
  libraries/audio-client/src/AudioClient.cpp
  libraries/audio/src/AudioFOA.cpp
  libraries/audio/src/AudioFOA.h
  libraries/audio/src/AudioHRTF.cpp
  libraries/audio/src/AudioHRTF.h
  libraries/audio/src/avx2/AudioFOA_avx2.cpp
Labels: Development Approved, Engine, Project Approved, bug

#15282 Case 21883: Fix safe landing code improperly finding local entities
  interface/src/avatar/MyAvatar.cpp
  libraries/entities/src/EntityTreeElement.cpp
Labels: Development Approved, Engine, Project Approved

#15357 Case 21417: Fix cauterization of entities that are children of MyAvatar's head
  interface/src/avatar/MyAvatar.cpp
  libraries/entities-renderer/src/RenderableEntityItem.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.h
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/render-utils/src/MeshPartPayload.cpp
  libraries/render-utils/src/MeshPartPayload.h
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
  libraries/render-utils/src/RenderHifi.h
  libraries/render-utils/src/RenderShadowTask.cpp
  libraries/render-utils/src/RenderShadowTask.h
  libraries/render/src/render/Args.h
  libraries/render/src/render/RenderFetchCullSortTask.h
  libraries/shared/src/SpatiallyNestable.cpp
Labels: Development Approved, Engine, Project Approved

#15353 Case 819 - Add min-listen-port command line parameter to assignment monitor
  assignment-client/src/AssignmentClientApp.cpp
  assignment-client/src/AssignmentClientApp.h
  assignment-client/src/AssignmentClientMonitor.cpp
  assignment-client/src/AssignmentClientMonitor.h
Labels: Development Approved, Metaverse, Project Approved

#15366 Case 20896: Fix continual edit handle translation when moving (RC82)
  scripts/system/libraries/entitySelectionTool.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:, bug

#15368 Case 22140 - Dynamic Jitter Buffer switch on admin UI disables dynamic buffers when it's set to enable them.
  assignment-client/src/audio/AudioMixer.cpp
Labels: Development Approved, Metaverse, Project Approved, bug

#15370 Case 22139: Fix lack of ranges on numerical types in Create
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityItemPropertiesMacros.h
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#15371 Case 22167: Fix lack of ranges on numerical types in Create
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityItemPropertiesMacros.h
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved

#15351 Case 22092: Fix avatar/shape material targets, refresh material target when parent changes (RC82)
  scripts/system/edit.js
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#15352 Case 22082, 22101: PR 15325 follow up and PR 15351 RC82 > Master
  scripts/system/edit.js
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved

#15316 Bug fixed for MyAvatar.getJointRotation(name, quat) and MyAvatar.setJointRotation(name, quat)
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
Labels: Avatar, Development Approved, Project Approved, bug

#15323 Case 22052: Camera JSDoc
  interface/src/FancyCamera.h
  libraries/shared/src/shared/Camera.h
Labels: JSDocs

#15320 Case 21989: AvatarList and AvatarManager JSDoc
  interface/src/avatar/AvatarManager.cpp
  interface/src/avatar/AvatarManager.h
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
  libraries/avatars/src/AvatarHashMap.h
  libraries/avatars/src/ScriptAvatarData.h
  libraries/render-utils/src/Model.cpp
  libraries/shared/src/GeometryUtil.h
  tools/jsdoc/plugins/hifi.js
Labels: JSDocs

#15372 (case 22170) Fix TextureBaker failures and heap corruption in MaterialBaker (RC82)
  libraries/baking/src/MaterialBaker.cpp
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#15284 Fixes Bug that Prevented Eye Rotation Override When Procedural Eye Movement is Disabled
  interface/src/avatar/MySkeletonModel.cpp
Labels: Avatar, Development Approved, Project Approved

#15387 Case 22157: Shield/bubble animation and sound plays when other users are ignored by PAL or their own shields
  interface/src/avatar/AvatarManager.cpp
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#15380 Case 22092: Fix material targets when re-opening properties to same entity (RC82)
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:, bug

#15384 Case21707 - Wallet doesn't work if user has unicode characters in windows username
  interface/src/commerce/Wallet.cpp
Labels: Development Approved, Metaverse, Project Approved, bug

#15390 Disable baking of embedded material textures in material entities
  tools/oven/src/DomainBaker.cpp
Labels: Critical Fix, Development Approved, Engine, Project Approved, QA Approved :tada:, Release Blocker

#15373 (case 21906) Fix TextureBaker failures and heap corruption in MaterialBaker
  libraries/baking/src/MaterialBaker.cpp
Labels: Development Approved, Engine, Project Approved

#15386 Case 22203: Shield/bubble animation and sound plays when other users are ignored by PAL or their own shields of RC83
  interface/src/avatar/AvatarManager.cpp
Labels: Development Approved, Engine, Project Approved

#15391 (master) Disable baking of embedded material textures in material entities
  tools/oven/src/DomainBaker.cpp
Labels: Development Approved, Engine, Project Approved

#15375 Increase ping interval for unconnected Nodes
  libraries/networking/src/NetworkPeer.h
  libraries/networking/src/NodeList.cpp
Labels: Development Approved, Metaverse, Project Approved, bug

#15376 Clear delayed Node-adds upon restart
  libraries/networking/src/LimitedNodeList.cpp
Labels: Development Approved, Metaverse, bug

#15381 Case 22195: PR 15380 changes from v82 to Master
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, Project Approved, bug

#15388 Case 22192: Adjust run speed constants.
  interface/src/avatar/MyAvatar.cpp
  libraries/shared/src/AvatarConstants.h
Labels: Design, Development Approved

#15365 Better head vs camera checks for avatar head cauterization
  interface/src/avatar/MyAvatar.cpp
  libraries/animation/src/AnimUtil.cpp
  libraries/animation/src/AnimUtil.h
  libraries/animation/src/Rig.cpp
  libraries/animation/src/Rig.h
  libraries/avatars-renderer/src/avatars-renderer/SkeletonModel.cpp
  libraries/shared/src/AvatarConstants.h
Labels: Avatar, Development Approved, Project Approved

#15367 Case 22130: PR 15366 changes from v82 to Master
  scripts/system/libraries/entitySelectionTool.js
Labels: Create, Development Approved, Project Approved, bug

#15354 Case 20960: Fix Create's undo edit order
  scripts/system/edit.js
Labels: Create, Development Approved, Project Approved

#15344 Fixed out of range error in AnimTwoBoneIK
  libraries/animation/src/AnimTwoBoneIK.cpp
Labels: Avatar, Development Approved, HMD required, Project Approved

#15329 case 22219: Improved ambient maps
  interface/src/raypick/LaserPointer.cpp
  libraries/baking/src/TextureBaker.cpp
  libraries/entities-renderer/src/RenderableZoneEntityItem.cpp
  libraries/image/CMakeLists.txt
  libraries/image/src/image/CubeMap.cpp
  libraries/image/src/image/CubeMap.h
  libraries/image/src/image/Image.cpp
  libraries/image/src/image/Image.h
  libraries/image/src/image/TextureProcessing.cpp
  libraries/image/src/image/TextureProcessing.h
  libraries/material-networking/src/material-networking/TextureCache.cpp
  libraries/render-utils/src/AntialiasingEffect.cpp
  libraries/render-utils/src/DeferredLightingEffect.cpp
  libraries/render-utils/src/DeferredLightingEffect.h
  libraries/render-utils/src/LightAmbient.slh
  libraries/render-utils/src/LightingModel.cpp
  libraries/render-utils/src/LightingModel.h
  libraries/render-utils/src/RenderCommonTask.cpp
  libraries/render-utils/src/RenderDeferredTask.cpp
  libraries/render-utils/src/RenderForwardTask.cpp
  libraries/render-utils/src/render-utils/ShaderConstants.h
  libraries/shared/src/BRDF.cpp
  libraries/shared/src/BRDF.h
  libraries/shared/src/RandomAndNoise.h
  libraries/shared/src/TBBHelpers.h
  tools/oven/src/BakerCLI.cpp
  tools/oven/src/DomainBaker.cpp
  tools/oven/src/ui/SkyboxBakeWidget.cpp
  tools/oven/src/ui/SkyboxBakeWidget.h
Labels: Android, Development Approved, Engine, Mac Required, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:, Windows Required

#15033 Added coding standard file to repo
  CODING_STANDARD.md
  CONTRIBUTING.md
Labels: Development Approved, Documentation

#15294 case 21977: fix asan reported error when returning QString reference to refreshGroupsCache
  domain-server/src/DomainGatekeeper.cpp
  libraries/networking/src/NodePermissions.h
Labels: Development Approved, Project Approved, Server & Network

#15271 Allow Hand Animations to be Overridden
  interface/resources/avatar/avatar-animation.json
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  libraries/animation/src/Rig.cpp
  libraries/animation/src/Rig.h
Labels: Avatar, Development Approved, HMD required, Scripting API change

#15397 Case 22222: Fix oven crash
  libraries/baking/src/FBXBaker.cpp
  libraries/render-utils/src/Model.cpp
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#15399 (case 22201) Fix Interface not loading some baked models correctly
  libraries/fbx/src/FBXSerializer_Mesh.cpp
  libraries/graphics/src/graphics/Material.h
  libraries/material-networking/src/material-networking/MaterialCache.cpp
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#15403 Avatar-Mixer restart issues (RC82)
  libraries/networking/src/LimitedNodeList.cpp
  libraries/networking/src/NetworkPeer.h
  libraries/networking/src/NodeList.cpp
Labels: Development Approved, Metaverse, Project Approved, QA Approved :tada:

#15332 Case 22060 fix model
  libraries/fbx/src/GLTFSerializer.cpp
  libraries/fbx/src/GLTFSerializer.h
Labels: Development Approved, Engine

#15310 Case 21513: Keyboad doesn't scale to avatar after reloading content
  interface/src/ui/Keyboard.cpp
  interface/src/ui/Keyboard.h
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, QA Approved :tada:

#15412 Case 22259: Fix Mute Warning Switch Text
  interface/resources/qml/hifi/audio/Audio.qml
Labels: Design, Development Approved, Project Approved, QA Approved :tada:, bug

#15404 (case 22163) Fix baked models unable to rebake
  libraries/baking/src/ModelBaker.cpp
  libraries/baking/src/ModelBaker.h
  libraries/fbx/src/FSTReader.h
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#15417 Case 22276: Fix transparent textures on baked assets (RC82)
  libraries/model-networking/src/model-networking/ModelCache.cpp
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#15396 Case 22244: Fix oven crash (RC83)
  libraries/baking/src/FBXBaker.cpp
  libraries/render-utils/src/Model.cpp
Labels: Development Approved, Engine, Project Approved

#15356 Case 22096: Added vhacd-util and Oven to all installers.
  tools/CMakeLists.txt
  tools/oven/CMakeLists.txt
  tools/vhacd-util/CMakeLists.txt
Labels: Development Approved, Engine, Project Approved

#15418 Case 22287: Fix warnings
  interface/src/Application.cpp
  interface/src/Menu.cpp
Labels: Development Approved, Engine, Project Approved

#15339 Case 22076: Use optional environment variable for timestamp server URL
  CMakeLists.txt
  cmake/macros/OptionalWinExecutableSigning.cmake
Labels: Development Approved, Engine, Project Approved

#15402 (case 22216) Fix Interface not loading some baked models correctly
  libraries/fbx/src/FBXSerializer_Mesh.cpp
  libraries/graphics/src/graphics/Material.h
  libraries/material-networking/src/material-networking/MaterialCache.cpp
Labels: Development Approved, Engine, Project Approved

#15335 Case 22067: Added 'metaverse' to dev-build URL - v3.2.1
  tools/nitpick/src/TestRunner.h
  tools/nitpick/src/common.h
Labels: Development Approved, Engine, Project Approved, nitpick

#15395 Case 22213: Fix materialJSON paths in domain baker
  libraries/baking/src/MaterialBaker.cpp
  libraries/baking/src/MaterialBaker.h
  tools/oven/src/DomainBaker.cpp
  tools/oven/src/DomainBaker.h
Labels: Development Approved, Engine, Project Approved

#15406 (case 22271) (RC83) Fix baked models unable to rebake
  libraries/baking/src/ModelBaker.cpp
  libraries/baking/src/ModelBaker.h
  libraries/fbx/src/FSTReader.h
Labels: Development Approved, Engine, Project Approved

#15415 Case 22263: Persist Mute Settings Between Sessions
  interface/src/scripting/Audio.cpp
  interface/src/scripting/Audio.h
Labels: Design, Development Approved, Project Approved, QA Approved :tada:, bug

#15416 Case 22283: Fix transparent textures on baked assets
  libraries/model-networking/src/model-networking/ModelCache.cpp
Labels: Development Approved, Engine

#15360 Case 21228: [Create App] allow editing properties of multiple entities simultaneously
  scripts/system/edit.js
  scripts/system/html/css/edit-style.css
  scripts/system/html/js/draggableNumber.js
  scripts/system/html/js/entityProperties.js
  scripts/system/html/js/utils.js
Labels: Create, Development Approved, PRE-MERGE TESTING REQUIRED, QA Approved :tada:

#15424 Case 22299: Fix domain baker not finishing
  tools/oven/src/DomainBaker.cpp
Labels: Create, Development Approved, Engine, Project Approved, QA Approved :tada:

#15420 Case 22289: Fixing Shield Icon Behavior in Desktop Mode
  interface/resources/qml/BubbleIcon.qml
Labels: Design, Development Approved, Project Approved, QA Approved :tada:, bug

#15425 (case 22011) Fix model processing occurring on main thread
  libraries/material-networking/src/material-networking/MaterialCache.h
  libraries/model-networking/src/model-networking/ModelCache.cpp
Labels: Development Approved, Engine, Project Approved

#15426 (case 22282) Fix some baked models not preserving texture scale (master)
  libraries/baking/src/FBXBaker.cpp
  libraries/graphics-scripting/src/graphics-scripting/Forward.h
  libraries/graphics-scripting/src/graphics-scripting/GraphicsScriptingInterface.cpp
  libraries/graphics-scripting/src/graphics-scripting/ScriptableModel.cpp
  libraries/graphics/src/graphics/Material.h
  libraries/material-networking/src/material-networking/MaterialCache.cpp
  libraries/shared/src/RegisteredMetaTypes.cpp
  libraries/shared/src/RegisteredMetaTypes.h
Labels: Development Approved, Engine, Project Approved

#15421 (case 22277) Fix some baked models not preserving texture scale (RC82)
  libraries/baking/src/FBXBaker.cpp
  libraries/graphics-scripting/src/graphics-scripting/Forward.h
  libraries/graphics-scripting/src/graphics-scripting/GraphicsScriptingInterface.cpp
  libraries/graphics-scripting/src/graphics-scripting/ScriptableModel.cpp
  libraries/graphics/src/graphics/Material.h
  libraries/material-networking/src/material-networking/MaterialCache.cpp
  libraries/shared/src/RegisteredMetaTypes.cpp
  libraries/shared/src/RegisteredMetaTypes.h
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#15437 Case 22314: Fix "Version" not being preserved during baking (RC82)
  tools/oven/src/DomainBaker.cpp
  tools/oven/src/DomainBaker.h
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#15436 Case 22288: Fix "Version" not being preserved during baking
  tools/oven/src/DomainBaker.cpp
  tools/oven/src/DomainBaker.h
Labels: Development Approved, Engine, Project Approved

#15411 Case 22117: Shadows Appear Incorrectly Placed Relative to Avatars
  libraries/entities-renderer/src/RenderableMaterialEntityItem.cpp
  libraries/entities-renderer/src/RenderableShapeEntityItem.cpp
  libraries/graphics/src/graphics/Light.cpp
  libraries/graphics/src/graphics/Light.h
  libraries/graphics/src/graphics/MaterialTextures.slh
  libraries/render-utils/src/LightStage.cpp
  libraries/render-utils/src/LightStage.h
  libraries/render-utils/src/MeshPartPayload.cpp
  libraries/render-utils/src/RenderDeferredTask.cpp
  libraries/render-utils/src/RenderPipelines.cpp
  libraries/render-utils/src/RenderPipelines.h
  libraries/render-utils/src/RenderShadowTask.cpp
  libraries/render-utils/src/RenderShadowTask.h
  libraries/render-utils/src/Shadow.slh
  libraries/render-utils/src/deformed_model_shadow.slv
  libraries/render-utils/src/deformed_model_shadow_dq.slv
  libraries/render-utils/src/model_normal_map.slf
  libraries/render-utils/src/model_shadow.slf
  libraries/render-utils/src/model_shadow.slv
  libraries/render-utils/src/model_shadow_fade.slf
  libraries/task/src/task/Task.h
Labels: Development Approved, Engine, Project Approved

#15432 Case 22263: Interface Mute setting does not persist after relaunching interface.
  interface/src/scripting/Audio.cpp
Labels: Design, Development Approved, Project Approved, QA Approved :tada:, bug

#15431 Don't double-free an openssl structure in readKeys()
  interface/src/commerce/Wallet.cpp
Labels: Client, Development Approved, bug

#15441 Case 22195: Fix material target parentIDChanged
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, Project Approved, bug

#15377 case 22175: remove view/Independent-Mode and view/Entity-Mode menu items
  interface/src/Application.cpp
  interface/src/Menu.cpp
  interface/src/Menu.h
  interface/src/ModelSelector.cpp
  scripts/system/hmd.js
  tools/nitpick/AppDataHighFidelity/Interface.json
Labels: Client, Development Approved, Engine, Project Approved

#15427 Case 22079: Bake existing materialMap in FST
  libraries/baking/src/MaterialBaker.cpp
  libraries/baking/src/MaterialBaker.h
  libraries/baking/src/ModelBaker.cpp
  libraries/baking/src/ModelBaker.h
Labels: Development Approved, Engine

#15430 Case 22309: Fix domain baker not finishing (merge to master)
  tools/oven/src/DomainBaker.cpp
Labels: Create, Development Approved, Engine, Project Approved

#15435 Case 22327: Add a qml library to represent and interact with the engine configs, enhance Luci
  scripts/developer/utilities/lib/jet/jet.js
  scripts/developer/utilities/lib/jet/qml/TaskPropView.qml
  scripts/developer/utilities/lib/jet/qml/qmldir
  scripts/developer/utilities/lib/prop/PropBool.qml
  scripts/developer/utilities/lib/prop/PropColor.qml
  scripts/developer/utilities/lib/prop/PropEnum.qml
  scripts/developer/utilities/lib/prop/PropGroup.qml
  scripts/developer/utilities/lib/prop/PropItem.qml
  scripts/developer/utilities/lib/prop/PropScalar.qml
  scripts/developer/utilities/lib/prop/qmldir
  scripts/developer/utilities/lib/prop/style/Global.qml
  scripts/developer/utilities/lib/prop/style/PiCanvasIcon.qml
  scripts/developer/utilities/lib/prop/style/PiCheckBox.qml
  scripts/developer/utilities/lib/prop/style/PiComboBox.qml
  scripts/developer/utilities/lib/prop/style/PiFolderPanel.qml
  scripts/developer/utilities/lib/prop/style/PiLabel.qml
  scripts/developer/utilities/lib/prop/style/PiSplitter.qml
  scripts/developer/utilities/lib/prop/style/PiText.qml
  scripts/developer/utilities/render/antialiasing.js
  scripts/developer/utilities/render/antialiasing.qml
  scripts/developer/utilities/render/debugCulling.js
  scripts/developer/utilities/render/deferredLighting.qml
  scripts/developer/utilities/render/luci.js
  scripts/developer/utilities/render/luci.qml
  scripts/developer/utilities/render/luci/Antialiasing.qml
  scripts/developer/utilities/render/luci/BoundingBoxes.qml
  scripts/developer/utilities/render/luci/Culling.qml
  scripts/developer/utilities/render/luci/Framebuffer.qml
  scripts/developer/utilities/render/luci/Page.js
  scripts/developer/utilities/render/luci/ShadingModel.qml
  scripts/developer/utilities/render/luci/ToneMapping.qml
  scripts/developer/utilities/render/luci/qmldir
  scripts/developer/utilities/render/luci2.js
  scripts/developer/utilities/render/materialInspector.js
Labels: Development Approved, Engine, Project Approved

#15444 Case 22262: Comment out QScript type warning
  libraries/shared/src/VariantMapToScriptValue.cpp
Labels: Development Approved, Engine

#15446 Case 22340 : turning on blit present for quest
  libraries/oculusMobile/src/ovr/VrHandler.cpp
Labels: Development Approved, Engine

#15447 Case 22329: Don't try to bake materialURL if it points to materialData
  tools/oven/src/DomainBaker.cpp
Labels: Development Approved, Engine

#15405 Case 20060: Grab correct stencil masks from display plugins
  cmake/externals/LibOVR/CMakeLists.txt
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/SecondaryCamera.cpp
  interface/src/graphics/GraphicsEngine.cpp
  interface/src/ui/Snapshot.cpp
  interface/src/ui/Snapshot.h
  interface/src/ui/SnapshotAnimated.cpp
  interface/src/ui/SnapshotAnimated.h
  libraries/display-plugins/src/display-plugins/NullDisplayPlugin.cpp
  libraries/display-plugins/src/display-plugins/NullDisplayPlugin.h
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.cpp
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.h
  libraries/display-plugins/src/display-plugins/hmd/HmdDisplayPlugin.cpp
  libraries/display-plugins/src/display-plugins/hmd/HmdDisplayPlugin.h
  libraries/gpu/src/gpu/Frame.h
  libraries/plugins/src/plugins/DisplayPlugin.h
  libraries/render-utils/src/StencilMaskPass.cpp
  libraries/render-utils/src/StencilMaskPass.h
  libraries/render/src/render/Args.h
  libraries/shared/src/RegisteredMetaTypes.cpp
  libraries/shared/src/RegisteredMetaTypes.h
  libraries/shared/src/StencilMaskMode.h
  plugins/oculus/CMakeLists.txt
  plugins/oculus/src/OculusBaseDisplayPlugin.cpp
  plugins/oculus/src/OculusBaseDisplayPlugin.h
  plugins/openvr/src/OpenVrDisplayPlugin.cpp
  plugins/openvr/src/OpenVrDisplayPlugin.h
Labels: Development Ready, Engine, Oculus Required, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:, Vive Required

#15428 case 22347: glTF move debug code
  libraries/fbx/src/GLTFSerializer.cpp
  libraries/fbx/src/GLTFSerializer.h
Labels: Development Approved, Engine, Project Approved

#15449 Case 22337: Market -- Please Login -- does not work
  interface/resources/qml/hifi/commerce/marketplace/Marketplace.qml
  interface/resources/qml/hifi/commerce/wallet/NeedsLogIn.qml
Labels: Development Approved, Metaverse, Project Approved, QA Approved :tada:, bug

#15401 Case 22229: Create Grid ignorePickIntersection
  scripts/system/libraries/gridTool.js
Labels: Create, Development Approved, Project Approved

#15448 Case 22346: Market -- Please Login -- does not work
  interface/resources/qml/hifi/commerce/marketplace/Marketplace.qml
  interface/resources/qml/hifi/commerce/wallet/NeedsLogIn.qml
Labels: Development Ready, Metaverse, bug

#15443 Case 22333: Master: Fix asset server auto-baking
  assignment-client/src/assets/AssetServer.cpp
  assignment-client/src/assets/AssetServer.h
  assignment-client/src/assets/BakeAssetTask.cpp
  assignment-client/src/assets/BakeAssetTask.h
  libraries/material-networking/src/material-networking/TextureCache.cpp
  libraries/model-networking/src/model-networking/ModelCache.cpp
  libraries/model-networking/src/model-networking/ModelCache.h
  libraries/networking/src/ResourceCache.cpp
  libraries/shared/src/PathUtils.cpp
  libraries/shared/src/PathUtils.h
Labels: Development Approved, Project Approved

#15414 Case 22298: Persist Mute Settings Between Sessions
  interface/src/scripting/Audio.cpp
  interface/src/scripting/Audio.h
Labels: Design, Development Approved, Project Approved, bug

#15409 Case 22290: Fixing Shield Icon Behavior in Desktop Mode
  interface/resources/qml/BubbleIcon.qml
Labels: Design, Development Approved, Project Approved, bug

#15327 Case 22065: Fix mac warnings
  interface/src/Application.cpp
  interface/src/avatar/AvatarManager.cpp
  interface/src/ui/LoginDialog.cpp
  libraries/animation/src/AnimVariant.h
  libraries/entities/src/EntityItem.cpp
  libraries/model-baker/src/model-baker/BuildDracoMeshTask.cpp
Labels: Development Approved, Project Approved

#15452 Case 21884: send update after changing AvatarEntity via AvatarBookmarks.updateAvatarEntities()
  interface/src/avatar/MyAvatar.cpp
Labels: Development Approved, Engine, Project Approved

#15393 Update Record app per Marketplace certification requirements
  unpublishedScripts/marketplace/record/assets/avatar-record-a.svg
  unpublishedScripts/marketplace/record/assets/avatar-record-i.svg
  unpublishedScripts/marketplace/record/record.app.json
  unpublishedScripts/marketplace/record/record.js
Labels: Create, Development Approved, Project Approved

#15459 Fix crash sending other avatars hands to flow
  interface/src/avatar/MyAvatar.cpp
Labels: Avatar, Development Approved, Project Approved

#15458 Case 22361: openUrl fix (82)
  interface/resources/qml/LoginDialog/CompleteProfileBody.qml
  interface/resources/qml/LoginDialog/LinkAccountBody.qml
  interface/resources/qml/LoginDialog/SignUpBody.qml
  interface/resources/qml/LoginDialog/UsernameCollisionBody.qml
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/scripting/WindowScriptingInterface.cpp
  interface/src/scripting/WindowScriptingInterface.h
  interface/src/ui/LoginDialog.cpp
  interface/src/ui/LoginDialog.h
  libraries/ui/src/FileDialogHelper.cpp
  libraries/ui/src/FileDialogHelper.h
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, QA Approved :tada:

#15456 Case 22334: openUrl fix
  interface/resources/qml/LoginDialog/CompleteProfileBody.qml
  interface/resources/qml/LoginDialog/LinkAccountBody.qml
  interface/resources/qml/LoginDialog/SignUpBody.qml
  interface/resources/qml/LoginDialog/UsernameCollisionBody.qml
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/scripting/WindowScriptingInterface.cpp
  interface/src/scripting/WindowScriptingInterface.h
  interface/src/ui/LoginDialog.cpp
  interface/src/ui/LoginDialog.h
  libraries/ui/src/FileDialogHelper.cpp
  libraries/ui/src/FileDialogHelper.h
Labels: Development Approved, Engine, Project Approved

#15457 Tiny logical error in wallet creation
  interface/src/commerce/Wallet.cpp
Labels: Development Approved, QA Ready

#15298 Cased 21976: Added Script command to test if GPU memory size is stable.
  interface/src/Application.h
  interface/src/scripting/TestScriptingInterface.cpp
  interface/src/scripting/TestScriptingInterface.h
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:, Scripting API change

#15321 Case 21956: Audio JSDoc
  interface/src/scripting/Audio.h
  libraries/audio/src/AudioInjectorOptions.cpp
  libraries/audio/src/Sound.h
  libraries/script-engine/src/AudioScriptingInterface.h
  libraries/script-engine/src/ScriptAudioInjector.h
Labels: JSDocs

#15410 Case 22297: Fix Mute Warning Switch Text
  interface/resources/qml/hifi/audio/Audio.qml
Labels: Design, Development Approved, Development Ready, Project Approved, bug

#15450 Case 22350: Setting mac default for resolution render scale
  interface/src/Menu.cpp
Labels: Development Approved, Engine, Project Approved

#15468 Case 22012: Morph Targets for glTF Avatars
  libraries/fbx/src/GLTFSerializer.cpp
  libraries/fbx/src/GLTFSerializer.h
Labels: Development Approved, Engine, Project Approved

#15439 Case 22322: Oven handles TextureBakers with same URL but different usage + fix domain baking
  libraries/baking/src/FBXBaker.cpp
  libraries/baking/src/FBXBaker.h
  libraries/baking/src/MaterialBaker.cpp
  libraries/baking/src/MaterialBaker.h
  libraries/baking/src/OBJBaker.h
  libraries/baking/src/TextureBaker.cpp
  libraries/baking/src/TextureBaker.h
  libraries/gpu/src/gpu/Texture.cpp
  libraries/gpu/src/gpu/Texture.h
  libraries/image/src/image/TextureProcessing.cpp
  libraries/image/src/image/TextureProcessing.h
  libraries/material-networking/src/material-networking/TextureCache.cpp
  libraries/material-networking/src/material-networking/TextureCache.h
  tools/oven/src/DomainBaker.cpp
  tools/oven/src/DomainBaker.h
  tools/oven/src/ui/SkyboxBakeWidget.cpp
Labels: Development Approved, Engine, Project Approved

#15455 Case 22330: Regularize JSDoc deprecation notices
  assignment-client/src/avatars/ScriptableAvatar.h
  assignment-client/src/octree/OctreeHeadlessViewer.h
  interface/src/avatar/AvatarManager.cpp
  interface/src/avatar/MyAvatar.h
  interface/src/scripting/ControllerScriptingInterface.h
  libraries/animation/src/IKTarget.h
  libraries/avatars/src/AvatarData.h
  libraries/avatars/src/ScriptAvatarData.h
  libraries/controllers/src/controllers/Actions.cpp
  libraries/controllers/src/controllers/ScriptingInterface.h
  libraries/entities/src/EntityScriptingInterface.h
  libraries/shared/src/RegisteredMetaTypes.h
  libraries/ui/src/ui/TabletScriptingInterface.h
Labels: JSDocs

#15438 Skeleton Trait Implementation
  assignment-client/src/avatars/AvatarMixerClientData.cpp
  interface/src/Menu.cpp
  interface/src/Menu.h
  interface/src/avatar/AvatarManager.cpp
  interface/src/avatar/AvatarManager.h
  interface/src/avatar/OtherAvatar.cpp
  interface/src/avatar/OtherAvatar.h
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
  libraries/avatars/src/AvatarTraits.h
  libraries/avatars/src/ClientTraitsHandler.cpp
Labels: Avatar, Development Approved, Project Approved

#15460 Avatar network bandwidth optimization
  interface/src/avatar/MyAvatar.cpp
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
  libraries/shared/src/ThreadSafeValueCache.h
  tools/dissectors/3-hf-avatar.lua
Labels: Avatar, Development Approved, Project Approved

#15394 Case 22223: Messages JSDoc update
  libraries/networking/src/MessagesClient.h
Labels: JSDocs

#15400 Case 22253: Refresh Rate Controller
  interface/resources/qml/Stats.qml
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/RefreshRateManager.cpp
  interface/src/RefreshRateManager.h
  interface/src/scripting/RefreshRateScriptingInterface.h
  interface/src/ui/PreferencesDialog.cpp
  interface/src/ui/Stats.cpp
  interface/src/ui/Stats.h
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.cpp
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.h
  libraries/display-plugins/src/display-plugins/RefreshRateController.cpp
  libraries/display-plugins/src/display-plugins/RefreshRateController.h
  libraries/plugins/src/plugins/DisplayPlugin.h
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved

#15465 Case 22371: Fix domain baking (RC82)
  tools/oven/src/DomainBaker.cpp
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#15461 There is no anon restriction - only open, hifi, acl
  domain-server/src/DomainMetadata.cpp
Labels: Development Ready, QA Ready

#15466 Case 22255: Add size checks for trait packets parsing
  assignment-client/src/avatars/AvatarMixerClientData.cpp
  libraries/avatars/src/AvatarHashMap.cpp
  libraries/avatars/src/ClientTraitsHandler.cpp
  libraries/networking/src/ReceivedMessage.cpp
Labels: Development Approved
