Repository highfidelity/hifi, pull requests merged in 2019-09, with the labels that each got.

#16123 Don't cache when fetching Thunder's build info
  launchers/darwin/src/LatestBuildRequest.m
Labels: Development Approved, Project Approved

#16129 Feet position
  interface/src/avatar/MyAvatar.h
Labels: Development Approved, Project Approved, UI/UX

#16109 apply fake eye saccades if eye joints aren't overridden
  interface/src/avatar/MySkeletonModel.cpp
  libraries/animation/src/Rig.cpp
Labels: Development Approved, Project Approved

#16130 BUGZ-1405: Add context object to timer connection
  assignment-client/src/avatars/MixerAvatar.cpp
Labels: Development Approved, Metaverse, Project Approved

#16124 Call Interface "High Fidelity" on macOS
  interface/CMakeLists.txt
Labels: Development Approved, Project Approved

#16131 BUGZ-1114: Fixing Luci issues related to zone not rendering and other minor clean up
  libraries/render-utils/src/AntialiasingEffect.cpp
  libraries/render-utils/src/AntialiasingEffect.h
  libraries/render-utils/src/BloomEffect.cpp
  libraries/render-utils/src/BloomEffect.h
  libraries/render-utils/src/RenderDeferredTask.cpp
  scripts/developer/utilities/render/bloom.qml
  scripts/developer/utilities/render/debugBloom.js
  scripts/developer/utilities/render/deferredLighting.qml
  scripts/developer/utilities/render/luci.js
  scripts/developer/utilities/render/luci.qml
  scripts/developer/utilities/render/luci/Antialiasing.qml
  scripts/developer/utilities/render/luci/Bloom.qml
  scripts/developer/utilities/render/luci/BoundingBoxes.qml
  scripts/developer/utilities/render/luci/ShadingModel.qml
  scripts/developer/utilities/render/luci/qmldir
  scripts/developer/utilities/render/luci2.js
Labels: Development Approved, Engine

#16128 Error handling for Launcher's update
  launchers/darwin/src/updater/main.m
Labels: Development Approved, Project Approved

#16132 Dev-486 : emote indicator should still be showing
  interface/resources/qml/hifi/simplifiedUI/settingsApp/general/General.qml
  scripts/simplifiedUI/simplifiedEmote/simplifiedEmote.js
  scripts/simplifiedUI/simplifiedEmote/ui/qml/SimplifiedEmoteIndicator.qml
Labels: Development Approved, Project Approved, QA Approved :tada:

#16134 DOC-134: Fix some miscellaneous JSDoc issues
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityScriptingInterface.h
  libraries/script-engine/src/ScriptEngine.cpp
  libraries/script-engine/src/ScriptEngine.h
  plugins/openvr/src/ViveControllerManager.cpp
Labels: DO NOT MERGE, JSDocs, Project Approved

#16118 Additive animation support
  libraries/animation/src/AnimBlendLinear.cpp
  libraries/animation/src/AnimBlendLinear.h
  libraries/animation/src/AnimClip.cpp
  libraries/animation/src/AnimClip.h
  libraries/animation/src/AnimContext.h
  libraries/animation/src/AnimNodeLoader.cpp
  libraries/animation/src/AnimUtil.cpp
  libraries/animation/src/AnimUtil.h
  libraries/animation/src/Rig.cpp
Labels: Avatar, Development Approved, Project Approved

#16032 BUGZ-1176: rework polyvox state-machine
  libraries/entities-renderer/src/RenderablePolyVoxEntityItem.cpp
  libraries/entities-renderer/src/RenderablePolyVoxEntityItem.h
Labels: Beware: Threading/Deadlock, Development Approved, Engine, Project Approved, bug

#16135 [bugz-1415] :: Emoji App trying to shut down twice
  scripts/simplifiedUI/simplifiedEmote/emojiApp/simplifiedEmoji.js
  scripts/simplifiedUI/simplifiedEmote/simplifiedEmote.js
  scripts/simplifiedUI/ui/simplifiedNametag/simplifiedNametag.js
  scripts/simplifiedUI/ui/simplifiedStatusIndicator/simplifiedStatusIndicator.js
  scripts/simplifiedUI/ui/simplifiedUI.js
Labels: Development Approved, Project Approved, UI/UX

#16127 case DEV-492: Ensure launcher cannot be pinned
  launchers/win32/LauncherDlg.cpp
  launchers/win32/LauncherDlg.h
  launchers/win32/LauncherUtils.cpp
Labels: Development Approved, Project Approved

#16138 Check macOS Launcher's zip size before unzipping
  launchers/darwin/src/DownloadLauncher.m
Labels: Client, Development Approved, Project Approved

#16140 Fix webrtc link errors in debug builds
  cmake/macros/TargetWebRTC.cmake
Labels: Development Approved, Project Approved

#16137 BUGZ-1398: Tablet access to local HTML
  libraries/qml/src/qml/OffscreenSurface.cpp
  libraries/qml/src/qml/OffscreenSurface.h
  libraries/script-engine/src/ScriptEngine.cpp
  libraries/shared/src/shared/LocalFileAccessGate.cpp
  libraries/shared/src/shared/LocalFileAccessGate.h
  libraries/ui/src/ui/OffscreenQmlSurface.cpp
  libraries/ui/src/ui/OffscreenQmlSurface.h
  libraries/ui/src/ui/TabletScriptingInterface.cpp
  libraries/ui/src/ui/TabletScriptingInterface.h
Labels: Development Approved, Engine, Project Approved

#16142 Percent decode URL from Thunder
  launchers/darwin/src/LatestBuildRequest.m
Labels: Development Approved, Project Approved

#16136 Directional Blending Support
  interface/src/ui/AnimStats.cpp
  libraries/animation/src/AnimBlendDirectional.cpp
  libraries/animation/src/AnimBlendDirectional.h
  libraries/animation/src/AnimBlendLinear.cpp
  libraries/animation/src/AnimClip.cpp
  libraries/animation/src/AnimContext.h
  libraries/animation/src/AnimNode.h
  libraries/animation/src/AnimNodeLoader.cpp
  libraries/animation/src/AnimUtil.cpp
  libraries/animation/src/AnimUtil.h
  libraries/animation/src/AnimVariant.cpp
  libraries/avatars/src/ClientTraitsHandler.cpp
Labels: Avatar, Development Approved, Project Approved

#16148 Bugz 1395/persistent emoji after shutdown
  scripts/simplifiedUI/simplifiedEmote/emojiApp/simplifiedEmoji.js
  scripts/simplifiedUI/simplifiedEmote/simplifiedEmote.js
  scripts/simplifiedUI/ui/simplifiedUI.js
Labels: Development Approved, PRE-MERGE TESTING REQUIRED, Project Approved

#16147 Support updater in Contents/{MacOS,Resources}
  launchers/darwin/CMakeLists.txt
  launchers/darwin/src/Launcher.m
Labels: Client, Development Approved, Project Approved

#16149 BUGZ-1360: Avoid bad normal values leading to black pixels in Forward
  libraries/graphics/src/graphics/MaterialTextures.slh
Labels: Development Approved, Engine, Project Approved

#16153 Revert "Percent decode URL from Thunder"
  launchers/darwin/src/LatestBuildRequest.m
Labels: Client, Development Approved, Project Approved

#16150 Add signing 2.0 rebase
  cmake/macros/SetPackagingParameters.cmake
  interface/interface.entitlements
  interface/src/main.cpp
  launchers/darwin/HQ Launcher.entitlements
  launchers/darwin/src/DownloadInterface.m
  launchers/darwin/src/Settings.m
Labels: Development Ready, Project Approved

#16146 BUGZ-1385: allow entity-script-server to move entities kinematically
  assignment-client/src/entities/EntityServer.cpp
  assignment-client/src/entities/EntityServer.h
  assignment-client/src/scripts/EntityScriptServer.cpp
  assignment-client/src/scripts/EntityScriptServer.h
  interface/src/avatar/OtherAvatar.cpp
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/entities/src/EntityTree.cpp
  libraries/networking/src/udt/PacketHeaders.h
  libraries/physics/src/EntityMotionState.cpp
Labels: Development Approved, Engine, Packet Version Change, Project Approved

#16141 Error bad status while downloading launcher
  launchers/darwin/src/DownloadLauncher.h
  launchers/darwin/src/DownloadLauncher.m
Labels: Development Approved, Project Approved

#16156 BUGZ-1434: use existing audio settings on startup
  interface/src/scripting/AudioDevices.cpp
Labels: Client, Development Approved, Engine, HMD required, Project Approved, bug

#16143 Sitting emote variants, revisions on stand emote agree anims, point bug fix
  interface/resources/avatar/animations/emote_agree_acknowledge.fbx
  interface/resources/avatar/animations/emote_agree_headnod.fbx
  interface/resources/avatar/animations/emote_agree_headnodyes.fbx
  interface/resources/avatar/animations/emote_agree_longheadnod.fbx
  interface/resources/avatar/animations/emote_agree_thoughtfulheadnod.fbx
  interface/resources/avatar/animations/emote_clap01_all.fbx
  interface/resources/avatar/animations/emote_point01_all.fbx
  interface/resources/avatar/animations/sitting_emote_agree_acknowledge.fbx
  interface/resources/avatar/animations/sitting_emote_agree_cheer.fbx
  interface/resources/avatar/animations/sitting_emote_clap02_all.fbx
  interface/resources/avatar/animations/sitting_emote_clap03_all.fbx
  interface/resources/avatar/animations/sitting_emote_disagree_dismiss.fbx
  interface/resources/avatar/animations/sitting_emote_disagree_headshake.fbx
  interface/resources/avatar/animations/sitting_emote_point_all.fbx
  interface/resources/avatar/animations/sitting_emote_raisehand03_all.fbx
  interface/resources/avatar/avatar-animation.json
Labels: Avatar, Development Approved, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#16121 BUGZ-1234: Mitigate the effect of audio noise on talking animations
  interface/src/avatar/MySkeletonModel.cpp
  libraries/animation/src/Rig.cpp
  libraries/avatars-renderer/src/avatars-renderer/Head.cpp
Labels: Avatar, Development Approved, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#16160 Emoji app duplicates sound on opening from toolbar
  interface/resources/qml/hifi/simplifiedUI/simplifiedControls/TextField.qml
Labels: Development Approved, Project Approved, UI/UX, bug

#16158 BUGZ-1394: Fix avatars with rotation offsets
  libraries/model-baker/src/model-baker/PrepareJointsTask.cpp
Labels: Avatar, Development Approved, Project Approved

#16159 (BUGZ-143) Fix Oven not finishing when Re-bake originals checked
  libraries/baking/src/ModelBaker.cpp
  libraries/baking/src/ModelBaker.h
  libraries/baking/src/TextureBaker.cpp
  tools/oven/src/DomainBaker.cpp
Labels: Development Approved, Engine, Project Approved

#16164 RC84: BUGZ-1416: Always stop challenge timer from the right thread
  assignment-client/src/avatars/AvatarMixer.cpp
  assignment-client/src/avatars/MixerAvatar.cpp
  assignment-client/src/avatars/MixerAvatar.h
Labels: Metaverse, Project Approved

#16163 BUGZ-1416: Always stop challenge timer from the right thread
  assignment-client/src/avatars/AvatarMixer.cpp
  assignment-client/src/avatars/MixerAvatar.cpp
  assignment-client/src/avatars/MixerAvatar.h
Labels: Development Approved, Metaverse, Project Approved

#16161 BUGZ-1321: Address race condition on accessing a resource of the OpenGLDisplayPlugin before it s garanteed to be allocated
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.cpp
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.h
  libraries/display-plugins/src/display-plugins/hmd/HmdDisplayPlugin.cpp
  libraries/display-plugins/src/display-plugins/hmd/HmdDisplayPlugin.h
Labels: Development Approved, Engine, HMD required, PRE-MERGE TESTING REQUIRED

#16167 BUGZ-1451: Update links in controller reference
  interface/resources/html/tabletHelp.html
Labels: Development Approved, Project Approved, UI/UX, bug

#16168 DEV-555: Ensure 'href' entity property supports relative paths (coordinates and named paths)
  libraries/entities/src/EntityItem.cpp
Labels: Development Approved, Engine, Project Approved

#16170 BUGZ-1445: Protect against engine not returning a valid CPU/GPU object in Help -> About
  interface/resources/qml/hifi/simplifiedUI/helpApp/about/HelpAbout.qml
Labels: Development Approved, Project Approved, UI/UX, bug

#16172 [BUGZ-1370] :: Clapping Noise While Descending After Flying
  scripts/simplifiedUI/simplifiedEmote/simplifiedEmote.js
Labels: Development Approved, Project Approved

#16169 BUGZ-1167: remove unwanted binaries from bad client-only installers
  cmake/templates/NSIS.template.in
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#16174 BUGZ-1167 - v84 version of fix
  cmake/templates/NSIS.template.in
Labels: Development Approved, Project Approved

#15906 Kasen Plugin Infrastructure v½ Codename "Modkit Mini"
  assignment-client/src/Agent.cpp
  assignment-client/src/AssignmentClientApp.cpp
  assignment-client/src/entities/EntityServer.cpp
  assignment-client/src/scripts/EntityScriptServer.cpp
  cmake/macros/SetupHifiClientServerPlugin.cmake
  interface/resources/qml/hifi/dialogs/security/Security.qml
  interface/src/Application.cpp
  interface/src/scripting/SettingsScriptingInterface.cpp
  interface/src/scripting/SettingsScriptingInterface.h
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities/src/EntityEditFilters.cpp
  libraries/networking/src/Assignment.cpp
  libraries/networking/src/ThreadedAssignment.cpp
  libraries/plugins/src/plugins/PluginManager.cpp
  libraries/plugins/src/plugins/PluginManager.h
  libraries/script-engine/src/ScriptEngine.cpp
  libraries/script-engine/src/ScriptEngine.h
  libraries/script-engine/src/ScriptEngines.cpp
  libraries/script-engine/src/ScriptEngines.h
  libraries/shared/src/shared/ScriptInitializerMixin.h
  plugins/CMakeLists.txt
  plugins/KasenAPIExample/CMakeLists.txt
  plugins/KasenAPIExample/src/ExampleScriptPlugin.h
  plugins/KasenAPIExample/src/KasenAPIExample.cpp
  plugins/KasenAPIExample/src/plugin.json
Labels: Development Approved, Open Source, Project Approved, Scripting API change

#16176 BUGZ-1456/HMD-audio-setting-shows-up-when-desktop-mode
  interface/resources/qml/hifi/audio/Audio.qml
Labels: Development Approved, Project Approved, UI/UX, bug

#16178 BUGZ-1339: Disable the Emote Indicator animation to prevent it from being 'jittery'
  scripts/simplifiedUI/simplifiedEmote/ui/qml/SimplifiedEmoteIndicator.qml
Labels: Development Approved, Project Approved, UI/UX, bug

#16177 DEV-565/Reconsider-the-emoji-pop-sound-on-the-out-animation
  scripts/simplifiedUI/simplifiedEmote/emojiApp/resources/sounds/emojiPopSound2.wav
  scripts/simplifiedUI/simplifiedEmote/emojiApp/simplifiedEmoji.js
Labels: Development Approved, Project Approved, UI/UX

#16175 DEV-551/hide-crash-menu-behind-environment-variable
  interface/src/Menu.cpp
Labels: Client, Development Approved, Project Approved, QA Approved :tada:, UI/UX

#16179 DEV-551/hide-crash-menu-behind-environment-variable (rc84)
  interface/src/Menu.cpp
Labels: Client, Development Approved, Project Approved, UI/UX, bug

#16180 DOC-163: Fix up Workload JSDoc stubs
  libraries/task/src/task/Config.h
Labels: JSDocs

#16133 DOC-59: Assets JSDoc
  libraries/networking/src/AssetClient.cpp
  libraries/networking/src/BaseAssetScriptingInterface.cpp
  libraries/networking/src/BaseAssetScriptingInterface.h
  libraries/script-engine/src/AssetScriptingInterface.cpp
  libraries/script-engine/src/AssetScriptingInterface.h
Labels: JSDocs

#16182 Bugz 1452/entity link property right button disable
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
Labels: Client, Development Approved, Project Approved, UI/UX, bug

#16183 BUGZ-1435: Re-enable head IK when seated on HMD
  libraries/animation/src/Rig.cpp
Labels: Avatar, Development Approved, Project Approved

#16186 RC84: BUGZ-1435: Re-enable head IK when seated on HMD
  libraries/animation/src/Rig.cpp
Labels: Avatar, Development Approved, Project Approved

#16193 remove duplicate references to crashMenu outside scope
  interface/src/Menu.cpp
Labels: Development Approved, Project Approved

#16190 BUGZ-1398: HMD Tablet Apps blocked by Web access error
  interface/resources/qml/Web3DSurface.qml
  libraries/entities-renderer/src/RenderableWebEntityItem.cpp
  libraries/entities/src/WebEntityItem.cpp
  libraries/entities/src/WebEntityItem.h
  libraries/ui/src/ui/TabletScriptingInterface.cpp
  libraries/ui/src/ui/TabletScriptingInterface.h
Labels: Client, Development Approved, Project Approved

#16189 BUGZ-1459: don't rely on final simulation update for kinematic entities
  libraries/physics/src/EntityMotionState.cpp
Labels: Development Approved, Engine, Project Approved

#16192 BUGZ-1398: HMD Tablet Apps blocked by Web access error RC-84
  interface/resources/qml/Web3DSurface.qml
  libraries/entities-renderer/src/RenderableWebEntityItem.cpp
  libraries/entities/src/WebEntityItem.cpp
  libraries/entities/src/WebEntityItem.h
  libraries/ui/src/ui/TabletScriptingInterface.cpp
  libraries/ui/src/ui/TabletScriptingInterface.h
Labels: Client, Development Approved, Development Ready, Project Approved

#16191 BUGZ-1459 for 0.84: don't rely on final simulation update for kinematic entities
  libraries/physics/src/EntityMotionState.cpp
Labels: Critical Fix, Development Approved, Engine, Project Approved

#16194 (DEV-557) Introduce hfm::Shape
  assignment-client/src/avatars/ScriptableAvatar.cpp
  interface/src/ModelPropertiesDialog.cpp
  interface/src/avatar/AvatarDoctor.cpp
  interface/src/raypick/CollisionPick.cpp
  libraries/avatars-renderer/src/avatars-renderer/SkeletonModel.cpp
  libraries/baking/src/FBXBaker.cpp
  libraries/baking/src/FBXBaker.h
  libraries/baking/src/MaterialBaker.cpp
  libraries/baking/src/MaterialBaker.h
  libraries/baking/src/ModelBaker.cpp
  libraries/baking/src/OBJBaker.cpp
  libraries/baking/src/OBJBaker.h
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities-renderer/src/RenderableParticleEffectEntityItem.cpp
  libraries/fbx/src/FBXSerializer.cpp
  libraries/fbx/src/FBXSerializer_Mesh.cpp
  libraries/fbx/src/FST.cpp
  libraries/fbx/src/GLTFSerializer.cpp
  libraries/fbx/src/OBJSerializer.cpp
  libraries/hfm/src/hfm/HFM.cpp
  libraries/hfm/src/hfm/HFM.h
  libraries/model-baker/src/model-baker/Baker.cpp
  libraries/render-utils/src/Model.cpp
  tools/vhacd-util/src/VHACDUtil.cpp
  tools/vhacd-util/src/VHACDUtilApp.cpp
Labels: Engine, Feedback Welcome

#16195 BUGZ-1456/HMD-audio-setting-shows-up-when-desktop-mode (84)
  interface/resources/qml/hifi/audio/Audio.qml
Labels: Client, Development Approved, Project Approved, UI/UX

#16185 BUGZ-1441: Update logo on login popup
  interface/resources/images/high-fidelity-banner.svg
Labels: Client, Development Approved, Project Approved

#16201 BUGZ-1441: Update logo on login popup (84)
  interface/resources/images/high-fidelity-banner.svg
Labels: Client, Development Approved, Project Approved

#16173 DEV-444 - OAuth administration improvements
  domain-server/resources/describe-settings.json
  domain-server/resources/web/js/base-settings.js
  domain-server/resources/web/settings/js/settings.js
  domain-server/src/DomainServer.cpp
  domain-server/src/DomainServer.h
  domain-server/src/DomainServerSettingsManager.cpp
Labels: Development Approved, Metaverse, PRE-MERGE TESTING REQUIRED, QA Approved :tada:

#16204 BUGZ-1497: Replacing key combination to trigger a frame capture
  interface/src/Application.cpp
Labels: Development Approved, Engine, Project Approved

#16206 v84: BUGZ-1485: Fix Copyright date in About dialog
  interface/resources/qml/hifi/dialogs/TabletAboutDialog.qml
Labels: Development Approved, Project Approved, UI/UX, bug

#16205 v85: BUGZ-1485: Fix Copyright date in About dialog
  interface/resources/qml/hifi/dialogs/TabletAboutDialog.qml
Labels: Development Approved, Project Approved, UI/UX, bug

#16208 BUGZ-1487: bug fix for inability to pick entities after unowned kinematic motion
  libraries/entities/src/EntitySimulation.cpp
  libraries/physics/src/EntityMotionState.cpp
  libraries/physics/src/PhysicalEntitySimulation.cpp
Labels: Development Ready, Engine, PRE-MERGE TESTING REQUIRED, Project Approved

#16209 BUGZ-1487: bug fix for inability to pick entities after unowned kinematic motion - 0.84 version
  libraries/entities/src/EntitySimulation.cpp
  libraries/physics/src/EntityMotionState.cpp
  libraries/physics/src/PhysicalEntitySimulation.cpp
Labels: Critical Fix, Development Ready, Engine, PRE-MERGE TESTING REQUIRED, Project Approved

#16212 DEV-521: Update Emoji window's search field to display emoji's name during hover
  interface/resources/qml/hifi/simplifiedUI/simplifiedControls/TextField.qml
  scripts/simplifiedUI/simplifiedEmote/emojiApp/ui/qml/SimplifiedEmoji.qml
Labels: Development Approved, Project Approved, UI/UX

#16213 DEV-576: Allow users to type HiFi locations into the SimplifiedUI top bar just like GOTO
  interface/resources/qml/hifi/simplifiedUI/topBar/SimplifiedTopBar.qml
Labels: Development Approved, UI/UX

#16207 Sit bug fixes
  interface/resources/avatar/avatar-animation.json
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
Labels: Avatar, Development Approved, Project Approved

#16157 DEV-605: Vive pro groundwork
  cmake/modules/FindiViewHMD.cmake
  interface/external/iViewHMD/readme.txt
  interface/resources/controllers/standard.json
  interface/resources/controllers/standard_nomovement.json
  interface/resources/controllers/vive.json
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/Menu.cpp
  interface/src/Menu.h
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  interface/src/avatar/MyHead.cpp
  interface/src/avatar/MySkeletonModel.cpp
  libraries/animation/src/Rig.cpp
  libraries/animation/src/Rig.h
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
  libraries/avatars-renderer/src/avatars-renderer/Head.cpp
  libraries/avatars-renderer/src/avatars-renderer/SkeletonModel.cpp
  libraries/avatars-renderer/src/avatars-renderer/SkeletonModel.h
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/HeadData.cpp
  libraries/avatars/src/HeadData.h
  libraries/controllers/src/controllers/Actions.cpp
  libraries/controllers/src/controllers/Actions.h
  libraries/controllers/src/controllers/AxisValue.cpp
  libraries/controllers/src/controllers/AxisValue.h
  libraries/controllers/src/controllers/InputDevice.cpp
  libraries/controllers/src/controllers/StandardController.cpp
  libraries/controllers/src/controllers/StandardControls.h
  libraries/controllers/src/controllers/UserInputMapper.cpp
  libraries/controllers/src/controllers/UserInputMapper.h
  libraries/controllers/src/controllers/impl/Endpoint.h
  libraries/controllers/src/controllers/impl/endpoints/ActionEndpoint.cpp
  libraries/controllers/src/controllers/impl/endpoints/ActionEndpoint.h
  libraries/controllers/src/controllers/impl/endpoints/CompositeEndpoint.cpp
  libraries/controllers/src/controllers/impl/endpoints/InputEndpoint.cpp
  libraries/controllers/src/controllers/impl/endpoints/ScriptEndpoint.h
  libraries/controllers/src/controllers/impl/filters/ClampFilter.h
  libraries/controllers/src/controllers/impl/filters/ConstrainToIntegerFilter.h
  libraries/controllers/src/controllers/impl/filters/ConstrainToPositiveIntegerFilter.h
  libraries/controllers/src/controllers/impl/filters/DeadZoneFilter.cpp
  libraries/controllers/src/controllers/impl/filters/HysteresisFilter.cpp
  libraries/controllers/src/controllers/impl/filters/NotFilter.cpp
  libraries/controllers/src/controllers/impl/filters/PulseFilter.cpp
  libraries/controllers/src/controllers/impl/filters/ScaleFilter.h
  libraries/render-utils/src/AnimDebugDraw.cpp
  libraries/shared/src/DebugDraw.cpp
  libraries/shared/src/DebugDraw.h
  libraries/shared/src/GeometryUtil.cpp
  libraries/shared/src/GeometryUtil.h
  libraries/trackers/src/trackers/EyeTracker.cpp
  libraries/trackers/src/trackers/EyeTracker.h
  plugins/openvr/src/OpenVrDisplayPlugin.h
Labels: Avatar, Development Approved, Engine, Project Approved, Scripting API change

#16214 Fix additive blending on avatars with non identity scale.
  libraries/animation/src/AnimUtil.cpp
Labels: Avatar, Development Approved

#16220 DEV-613: Remove unnecessary audio injector logging
  libraries/audio/src/AudioInjector.cpp
Labels: Client, Development Approved, Project Approved

#16219 DEV-152: Implement 'Smooth/Snap Turn' setting in SimplifiedUI > Settings > VR
  interface/resources/qml/hifi/simplifiedUI/settingsApp/vr/VR.qml
Labels: Development Approved, Project Approved, UI/UX

#16222 BUGZ-1529: Iteration on JumpTo Field visuals/interaction states
  interface/resources/qml/hifi/simplifiedUI/simplifiedControls/TextField.qml
  interface/resources/qml/hifi/simplifiedUI/topBar/SimplifiedTopBar.qml
Labels: Development Approved, Project Approved, UI/UX

#16218 BUGZ-1457: scripted edits of avatar entites should succeed when in the void
  libraries/entities/src/EntityScriptingInterface.cpp
Labels: Development Approved, Engine, Project Approved

#16223 Whoops! New placeholder text color
  interface/resources/qml/hifi/simplifiedUI/topBar/SimplifiedTopBar.qml
Labels: UI/UX, bug

#16202 DEV-594: add trace stats for workload region sizes
  libraries/workload/src/workload/ViewTask.cpp
Labels: Development Approved, Engine, Project Approved

#16217 BUGZ-489: Make sure the flush timer is not spawned too early
  assignment-client/src/AssignmentClientApp.cpp
  domain-server/src/DomainServer.cpp
  interface/src/Application.cpp
  libraries/shared/src/LogHandler.cpp
  libraries/shared/src/LogHandler.h
Labels: Development Approved, Metaverse, Project Approved

#16226 BUGZ-1522: Snap app on tablet is blocked when saving/canceling out of its Settings page
  interface/resources/qml/hifi/tablet/TabletGeneralPreferences.qml
  interface/resources/qml/hifi/tablet/TabletRoot.qml
  interface/resources/qml/hifi/tablet/tabletWindows/TabletPreferencesDialog.qml
  libraries/ui/src/ui/TabletScriptingInterface.cpp
  libraries/ui/src/ui/TabletScriptingInterface.h
  scripts/system/snapshot.js
Labels: Client, Development Approved, Project Approved

#16227 BUGZ-1522: Snap app on tablet is blocked when saving/canceling out of its Settings page - RC-84
  interface/resources/qml/hifi/tablet/TabletGeneralPreferences.qml
  interface/resources/qml/hifi/tablet/TabletRoot.qml
  interface/resources/qml/hifi/tablet/tabletWindows/TabletPreferencesDialog.qml
  libraries/ui/src/ui/TabletScriptingInterface.cpp
  libraries/ui/src/ui/TabletScriptingInterface.h
  scripts/system/snapshot.js
Labels: Client, Development Approved, Project Approved

#16144 DEV-391: Keyboard Input Controls Camera Not Avatar Orientation
  interface/resources/avatar/animations/idle_aimoffsets.fbx
  interface/resources/avatar/avatar-animation.json
  interface/resources/controllers/keyboardMouse.json
  interface/src/Application.cpp
  interface/src/Menu.cpp
  interface/src/Menu.h
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  libraries/animation/src/Rig.cpp
  libraries/animation/src/Rig.h
  libraries/shared/src/shared/Camera.cpp
  libraries/shared/src/shared/Camera.h
Labels: Avatar, Development Approved, Feedback Welcome, Project Approved, Scripting API change

#16232 BUGZ-1522: Snap app on tablet is blocked when saving/canceling out of its Settings page RC 84
  interface/resources/qml/hifi/tablet/tabletWindows/TabletPreferencesDialog.qml
Labels: Client, Development Approved

#16231 BUGZ-1522: Snap app on tablet is blocked when saving/canceling out of its Settings page
  interface/resources/qml/hifi/tablet/tabletWindows/TabletPreferencesDialog.qml
Labels: Client, Development Approved, Project Approved

#16229 BUGZ-1551: Do not download Qt if Qt_CMAKE_PREFIX_PATH is set as an environment variable
  hifi_vcpkg.py
Labels: Development Approved, Project Approved

#16233 Put flush timer on right thread without parenting
  assignment-client/src/AssignmentClientApp.cpp
  domain-server/src/DomainServer.cpp
  interface/src/Application.cpp
Labels: Development Approved, Metaverse, Project Approved

#16210 DEV-544: Add account settings to the AccountManager
  libraries/networking/src/AccountManager.cpp
  libraries/networking/src/AccountManager.h
  libraries/networking/src/AccountSettings.cpp
  libraries/networking/src/AccountSettings.h
Labels: Development Approved, Metaverse, Project Approved

#16236 Removing connections to use inspect mode on mouse events
  interface/src/ui/overlays/ContextOverlayInterface.cpp
Labels: Development Approved, Project Approved, UI/UX

#16238 Prereq work for 'Reduce User Friction'
  interface/resources/qml/hifi/simplifiedUI/topBar/SimplifiedTopBar.qml
  scripts/simplifiedUI/ui/simplifiedUI.js
Labels: Development Approved, Project Approved, UI/UX

#16216 (DEV-591) Change BuildGraphicsMeshTask to use new deformers
  libraries/fbx/src/FBXSerializer.cpp
  libraries/hfm/src/hfm/HFM.cpp
  libraries/hfm/src/hfm/HFM.h
  libraries/model-baker/src/model-baker/Baker.cpp
  libraries/model-baker/src/model-baker/BuildGraphicsMeshTask.cpp
  libraries/model-baker/src/model-baker/BuildGraphicsMeshTask.h
Labels: Engine

#16242 Revert "BUGZ-1551: Do not download Qt if Qt_CMAKE_PREFIX_PATH is set as an environment variable"
  hifi_vcpkg.py
Labels: Development Approved, Project Approved

#16235 BUGZ-1553: Reset look at params when the avatar's location is set
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
Labels: Avatar, Development Approved, Project Approved

#16241 Undo removal of User Inspection
  interface/src/ui/overlays/ContextOverlayInterface.cpp
Labels: Development Approved, Project Approved, UI/UX

#16237 Transition between walk/emote should be faster
  interface/resources/avatar/animations/emote_point01_all.fbx
  interface/resources/avatar/avatar-animation.json
Labels: Avatar, Development Approved, Project Approved

#16240 BUGZ-577: Implement Recording.setPlayerVolume()
  assignment-client/src/Agent.cpp
  libraries/recording/src/recording/Deck.cpp
  libraries/recording/src/recording/Deck.h
  libraries/script-engine/src/RecordingScriptingInterface.cpp
  libraries/script-engine/src/RecordingScriptingInterface.h
Labels: Client, Development Approved, Project Approved

#16243 DEV-648: Add flag for account settings feature
  interface/src/Application.cpp
  libraries/networking/src/AccountManager.cpp
  libraries/networking/src/AccountManager.h
  tools/ac-client/src/ACClientApp.cpp
  tools/atp-client/src/ATPClientApp.cpp
Labels: Critical Fix, Development Approved, Metaverse, bug

#16247 Dev 148/add mirror mode to settings
  interface/resources/qml/hifi/simplifiedUI/helpApp/controls/ControlsTable.qml
  interface/resources/qml/hifi/simplifiedUI/settingsApp/general/General.qml
Labels: Development Approved, Project Approved, UI/UX

#16250 DEV-648: Limit the amount of account settings pull retries
  libraries/networking/src/AccountManager.cpp
  libraries/networking/src/AccountManager.h
Labels: Development Approved, Metaverse, bug

#16253 Add hfm::Shape::transformedExtents. Deprecate hfm fields.
  libraries/hfm/src/hfm/HFM.h
Labels: Engine

#16196 DEV-469: Default Audio device
  interface/src/scripting/Audio.cpp
  interface/src/scripting/Audio.h
  interface/src/scripting/AudioDevices.cpp
  interface/src/scripting/AudioDevices.h
  libraries/audio-client/src/AudioClient.cpp
  libraries/audio-client/src/AudioClient.h
  libraries/audio-client/src/HifiAudioDeviceInfo.cpp
  libraries/audio-client/src/HifiAudioDeviceInfo.h
  libraries/ui/src/ui/OffscreenQmlSurface.cpp
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved

#16244 BUGZ-1503: Don't move unused Connection class upon address change
  assignment-client/src/avatars/MixerAvatar.cpp
  libraries/networking/src/udt/Connection.cpp
  libraries/networking/src/udt/Connection.h
  libraries/networking/src/udt/Socket.cpp
Labels: Development Approved, Metaverse, Project Approved

#16249 BUGZ-1381 - domain server creates blank/undefined group when adding groups
  domain-server/resources/web/js/base-settings.js
Labels: Development Approved, Metaverse, Project Approved, bug

#16239 BUGZ-1510: don't forget to cleanup expired mortal entities
  libraries/physics/src/PhysicalEntitySimulation.cpp
Labels: Development Approved, Engine, Project Approved

#16255 BUGZ-1599: Free camera fixes
  interface/resources/controllers/keyboardMouse.json
  interface/src/avatar/MyAvatar.cpp
Labels: Avatar, Development Approved, Project Approved

#16257 Fix Android clang warnings due to unused compiler flags
  cmake/macros/SetupHifiLibrary.cmake
Labels: Android, Development Approved, Project Approved

#16256 BUGZ-1543: Suppress repeated socket logging
  libraries/networking/src/udt/Socket.cpp
Labels: Development Approved, Metaverse, Project Approved

#16262 BUGZ-573: Fix loadOtherBase in tablet.gotoWebScreen() not working
  interface/resources/qml/hifi/tablet/+webengine/BlocksWebView.qml
  libraries/ui/src/ui/TabletScriptingInterface.h
  unpublishedScripts/marketplace/blocks/blocksApp.js
Labels: Client, Development Approved, Development Ready, Project Approved, Scripting API change

#16230 [INFRA-196] Add mac notarization script
  tools/ci-scripts/notarize
Labels: Development Approved

#16260 BUGZ-1596: Cleaning up android build warnings
  interface/src/Application.cpp
  libraries/audio-client/src/AudioClient.cpp
  libraries/audio-client/src/AudioClient.h
  libraries/gpu-gl-common/src/gpu/gl/GLBackendQuery.cpp
  libraries/gpu-gles/src/gpu/gles/GLESBackendOutput.cpp
  libraries/qml/src/qml/OffscreenSurface.cpp
  libraries/shaders/src/shaders/Shaders.cpp
  libraries/shared/src/GLMHelpers.h
Labels: Development Approved, Engine

#16252 Emotes revisions per feedback
  interface/resources/avatar/animations/emote_clap01_all.fbx
  interface/resources/avatar/animations/emote_clap02_all.fbx
  interface/resources/avatar/animations/emote_clap03_all.fbx
  interface/resources/avatar/animations/emote_disagree_annoyedheadshake.fbx
  interface/resources/avatar/animations/emote_disagree_drophead.fbx
  interface/resources/avatar/animations/emote_disagree_thoughtfulheadshake.fbx
  interface/resources/avatar/animations/sitting_emote_agree_acknowledge.fbx
  interface/resources/avatar/animations/sitting_emote_agree_headnod.fbx
  interface/resources/avatar/animations/sitting_emote_agree_headnodyes.fbx
  interface/resources/avatar/animations/sitting_emote_agree_longheadnod.fbx
  interface/resources/avatar/animations/sitting_emote_clap02_all.fbx
  interface/resources/avatar/animations/sitting_emote_clap03_all.fbx
  interface/resources/avatar/animations/sitting_emote_clap_all.fbx
  interface/resources/avatar/avatar-animation.json
Labels: Avatar, Development Approved, Project Approved

#16258 DEV-1815: Investigating rendering issues with opacity map and adding tools to debug resource caches
  interface/src/Application.cpp
  libraries/entities-renderer/src/RenderableEntityItem.h
  libraries/graphics-scripting/src/graphics-scripting/Forward.h
  libraries/graphics-scripting/src/graphics-scripting/GraphicsScriptingInterface.cpp
  libraries/graphics-scripting/src/graphics-scripting/ScriptableModel.cpp
  libraries/graphics/src/graphics/Material.cpp
  libraries/graphics/src/graphics/Material.h
  libraries/graphics/src/graphics/Material.slh
  libraries/graphics/src/graphics/MaterialTextures.slh
  libraries/material-networking/src/material-networking/MaterialCache.cpp
  libraries/material-networking/src/material-networking/MaterialCache.h
  libraries/material-networking/src/material-networking/MaterialCacheScriptingInterface.cpp
  libraries/material-networking/src/material-networking/MaterialCacheScriptingInterface.h
  libraries/model-networking/src/model-networking/ModelCache.cpp
  libraries/networking/src/ResourceCache.cpp
  libraries/networking/src/ResourceCache.h
  libraries/render-utils/src/RenderPipelines.cpp
  libraries/render-utils/src/model.slf
  libraries/render/src/render/EngineStats.cpp
  libraries/render/src/render/EngineStats.h
  scripts/developer/utilities/cache/cash.js
  scripts/developer/utilities/cache/cash.qml
  scripts/developer/utilities/cache/cash/AnimationCacheInspector.qml
  scripts/developer/utilities/cache/cash/MaterialCacheInspector.qml
  scripts/developer/utilities/cache/cash/ModelCacheInspector.qml
  scripts/developer/utilities/cache/cash/ResourceCacheInspector.qml
  scripts/developer/utilities/cache/cash/ResourceInspector.qml
  scripts/developer/utilities/cache/cash/SoundCacheInspector.qml
  scripts/developer/utilities/cache/cash/TextureCacheInspector.qml
  scripts/developer/utilities/cache/cash/qmldir
  scripts/developer/utilities/lib/jet/qml/TaskListView.qml
  scripts/developer/utilities/lib/prop/PropEnum.qml
  scripts/developer/utilities/lib/prop/PropItem.qml
  scripts/developer/utilities/lib/prop/PropScalar.qml
  scripts/developer/utilities/lib/prop/qmldir
  scripts/developer/utilities/lib/prop/style/PiButton.qml
  scripts/developer/utilities/lib/prop/style/PiComboBox.qml
  scripts/developer/utilities/lib/prop/style/PiTextField.qml
  scripts/developer/utilities/lib/skit/Page.js
  scripts/developer/utilities/lib/skit/qml/SortFilterModel.qml
  scripts/developer/utilities/lib/skit/qml/qmldir
  scripts/developer/utilities/render/luci.js
  scripts/developer/utilities/render/materialInspector.js
  tools/gpu-frame-player/src/RenderThread.cpp
  tools/gpu-frame-player/src/RenderThread.h
Labels: Development Approved, Project Approved, Scripting API change

#16265 DEV-2223: Add shutdown annotations for crash reporting
  assignment-client/src/AssignmentClient.cpp
  domain-server/src/DomainServer.cpp
  domain-server/src/DomainServer.h
  domain-server/src/main.cpp
  libraries/shared/src/CrashAnnotations.cpp
  libraries/shared/src/CrashAnnotations.h
Labels: Development Approved, Metaverse, Project Approved
