Repository highfidelity/hifi, pull requests merged in 2019-05, with the labels that each got.

#15487 Case 22433: Query shape type outside lock
  libraries/entities/src/EntityItem.cpp
  libraries/networking/src/udt/PacketHeaders.h
Labels: Critical Fix, Development Approved, Project Approved, QA Approved :tada:, Release Blocker

#15478 Case 22378: System cursor in desktop mode instead of rendering texture from Displayplugin
  interface/src/Application.cpp
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.cpp
Labels: Development Approved, Engine, Project Approved

#15479 Case 22145: Fix BackTrace upload failures
  tools/ci-scripts/hifi_backtrace_post.py
Labels: Critical Fix, Development Approved, Engine, Project Approved

#15482 Fixed: turning on your microphone will now take you out of Away mode
  scripts/system/away.js
Labels: Development Approved, Project Approved, bug

#15489 Fix memory corruption in _modelJointIndicesCache QHash
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
Labels: Avatar, Beware: Threading/Deadlock, Development Approved, Project Approved

#15480 Case 22418: Fix model bounds on resize
  libraries/avatars-renderer/src/avatars-renderer/SkeletonModel.cpp
  libraries/render-utils/src/CauterizedModel.cpp
  libraries/render-utils/src/MeshPartPayload.cpp
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#15494 case 22438: setting default cursor after display initialization for systems that …
  interface/src/Application.cpp
Labels: Development Approved, Engine, Project Approved

#15363 Case 22068: Clipboard JSDoc
  interface/src/scripting/ClipboardScriptingInterface.h
  libraries/shared/src/ResourceRequestObserver.cpp
  libraries/shared/src/ResourceRequestObserver.h
Labels: JSDocs

#15500 Enable `--ci-build` setting via an environment variable
  prebuild.py
Labels: Development Approved, Project Approved

#15362 Case 22075: Controller JSDoc update
  interface/src/Application.cpp
  interface/src/scripting/ControllerScriptingInterface.h
  libraries/controllers/src/controllers/Actions.cpp
  libraries/controllers/src/controllers/InputDevice.h
  libraries/controllers/src/controllers/ScriptingInterface.cpp
  libraries/controllers/src/controllers/ScriptingInterface.h
  libraries/controllers/src/controllers/StandardController.cpp
  libraries/controllers/src/controllers/impl/MappingBuilderProxy.h
  libraries/controllers/src/controllers/impl/RouteBuilderProxy.cpp
  libraries/controllers/src/controllers/impl/RouteBuilderProxy.h
  libraries/input-plugins/src/input-plugins/KeyboardMouseDevice.cpp
  plugins/oculus/src/OculusControllerManager.cpp
  plugins/openvr/src/ViveControllerManager.cpp
Labels: JSDocs

#15464 Case 22370: Fix cmake 3.14 warnings
  cmake/compiler.cmake
  cmake/externals/LibOVR/CMakeLists.txt
  cmake/externals/LibOVRPlatform/CMakeLists.txt
  cmake/externals/hifiAudioCodec/CMakeLists.txt
  cmake/externals/neuron/CMakeLists.txt
  cmake/externals/sixense/CMakeLists.txt
  cmake/externals/steamworks/CMakeLists.txt
  cmake/externals/tbb/CMakeLists.txt
  cmake/macros/TargetBreakpad.cmake
  cmake/macros/TargetBullet.cmake
  cmake/macros/TargetDraco.cmake
  cmake/macros/TargetHifiAudioCodec.cmake
  cmake/macros/TargetNvtt.cmake
  cmake/macros/TargetOpenSSL.cmake
  cmake/macros/TargetPolyvox.cmake
Labels: Development Approved, Project Approved

#15429 Case 20989: Call leaveEntity when script on containing entity stops
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.h
Labels: Development Approved, Engine

#15502 (case 22368) Fix snapshots freezing Interface when no snap directory defined
  interface/src/Application.cpp
Labels: Development Approved, Engine

#15498 Case 22444: Try to fix materialMapping crash
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
Labels: Development Approved, Engine

#15499 BUGZ-92: Refresh rate Throttling refinements
  interface/src/Application.cpp
  interface/src/RefreshRateManager.cpp
  interface/src/RefreshRateManager.h
Labels: Development Approved, Engine, Project Approved

#15493 When you unmute using ctrl-m during push to talk, you now see that reflected in the audio icon
  interface/src/Application.cpp
Labels: Development Approved, Project Approved, bug

#15504 Fixed possible divide by zero error in setPacketSendPeriod()
  libraries/networking/src/udt/CongestionControl.cpp
Labels: Avatar, Development Approved, Project Approved, bug

#15505 Case 22419: Try to fix transition crash
  libraries/render/src/render/Scene.cpp
Labels: Development Approved, Engine, Project Approved

#15422 Case 22224: Midi JSDoc
  libraries/midi/src/Midi.cpp
  libraries/midi/src/Midi.h
Labels: JSDocs

#15501 BUGZ-73: Fix crash for active async messageBoxes on exit of client
  libraries/ui/src/OffscreenUi.cpp
Labels: Client, Create, Development Approved

#15483 22431: Set default avatar-mixer connection rate to effectively unlimited
  domain-server/resources/describe-settings.json
Labels: Development Approved, Development Ready, Metaverse, Project Approved

#15497 (case 22429) Do sanity checks on FBX data array lengths
  libraries/fbx/src/FBXSerializer_Node.cpp
Labels: Development Approved, Engine, Project Approved

#15433 Dependencies have correct osx deploy target
  CMakeLists.txt
  cmake/compiler.cmake
Labels: Development Approved, Project Approved

#15490 Case 22424: gltf avatars break all other available avatars when used
  libraries/fbx/src/GLTFSerializer.cpp
Labels: Development Approved, Engine, Project Approved

#15496 Increase max heartbeat time to 10 sec on mac
  interface/src/Application.cpp
Labels: Development Approved, Project Approved

#15503 Case 22447: The "MUTED" indicator (which warns when talking while muted) constantly flickers
  interface/resources/qml/hifi/audio/MicBarApplication.qml
Labels: Design, Development Approved, Project Approved, bug

#15495 Case 22433: master: Query shape type outside lock
  libraries/entities/src/EntityItem.cpp
  libraries/networking/src/udt/PacketHeaders.h
Labels: Development Approved, Development Ready, Project Approved

#15515 Case 20521: Unplugging headphones with hifi open causes freeze
  interface/src/Application.cpp
  libraries/midi/src/Midi.cpp
Labels: Client, Critical Fix, Development Approved, Project Approved, bug

#15488 case 22412: allow independent camera to be set by scripts
  interface/src/Application.cpp
Labels: Development Approved, Engine, Project Approved, QA Ready

#15517 Case 22483: Disable the use of tbb::parallel_for in Blender
  libraries/render-utils/src/Model.cpp
  libraries/shaders/src/shaders/Shaders.h
Labels: Development Approved, Engine

#15516 Fix VS2019 build failure
  libraries/shaders/src/shaders/Shaders.h
Labels: Development Ready

#15519 SharedObject::onRender deadlock fix
  libraries/qml/src/qml/impl/RenderEventHandler.cpp
  libraries/qml/src/qml/impl/RenderEventHandler.h
  libraries/qml/src/qml/impl/SharedObject.cpp
  libraries/qml/src/qml/impl/SharedObject.h
Labels: Beware: Threading/Deadlock, Development Approved, Engine, Project Approved

#15507 case LILY-30: Dockable Interactive Windows
  interface/src/Application.cpp
  interface/src/scripting/DesktopScriptingInterface.cpp
  interface/src/scripting/DesktopScriptingInterface.h
  interface/src/ui/InteractiveWindow.cpp
  interface/src/ui/InteractiveWindow.h
  libraries/ui/src/DockWidget.cpp
  libraries/ui/src/DockWidget.h
  libraries/ui/src/MainWindow.cpp
  libraries/ui/src/MainWindow.h
Labels: Development Approved, Engine, Project Approved

#15523 Case 22466, BUGZ-102: Fix zone rendering issues
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.h
  libraries/entities-renderer/src/RenderableZoneEntityItem.cpp
  libraries/entities-renderer/src/RenderableZoneEntityItem.h
  libraries/render-utils/src/ZoneRenderer.cpp
  libraries/render/src/render/Scene.cpp
  libraries/render/src/render/Scene.h
  libraries/render/src/render/Selection.h
Labels: Development Approved, Engine

#15525 Add gpu_name, gpu_driver & gpu_memory to crash annotations
  interface/src/Application.cpp
Labels: Development Approved, Engine, Project Approved

#15532 Bugz-129 JS APIs accessible to new dockable windows QML items is not the same as JS APIs accessible to floating / overlay QML windows
  interface/src/Application.h
  interface/src/ui/InteractiveWindow.cpp
Labels: Development Ready, Engine

#15534 Reduce echo when push-to-talk is used
  interface/src/scripting/Audio.cpp
  libraries/audio-client/src/AudioClient.cpp
  libraries/audio-client/src/AudioClient.h
Labels: Client, Development Approved, Project Approved

#15536 BUGZ-135: Edit entity icons ignorePickIntersection when not visible
  scripts/system/libraries/entityIconOverlayManager.js
Labels: Create, Development Approved, Project Approved

#15511 case 22166: Build complex shapes in ThreadPool instead of MainLoop
  assignment-client/src/entities/EntityTreeHeadlessViewer.cpp
  interface/src/Application.cpp
  interface/src/avatar/AvatarManager.cpp
  interface/src/avatar/AvatarManager.h
  interface/src/avatar/AvatarMotionState.cpp
  interface/src/avatar/AvatarMotionState.h
  interface/src/avatar/DetailedMotionState.cpp
  interface/src/avatar/DetailedMotionState.h
  interface/src/avatar/MyCharacterController.cpp
  interface/src/avatar/MyCharacterController.h
  interface/src/avatar/OtherAvatar.cpp
  interface/src/avatar/OtherAvatar.h
  interface/src/octree/SafeLanding.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.h
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities-renderer/src/RenderablePolyVoxEntityItem.h
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/entities/src/EntitySimulation.cpp
  libraries/entities/src/EntitySimulation.h
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/EntityTree.h
  libraries/entities/src/ModelEntityItem.cpp
  libraries/entities/src/ModelEntityItem.h
  libraries/entities/src/ParticleEffectEntityItem.h
  libraries/entities/src/PolyVoxEntityItem.h
  libraries/entities/src/ShapeEntityItem.h
  libraries/entities/src/SimpleEntitySimulation.cpp
  libraries/entities/src/SimpleEntitySimulation.h
  libraries/entities/src/SimulationOwner.h
  libraries/entities/src/ZoneEntityItem.h
  libraries/octree/src/Octree.h
  libraries/octree/src/OctreePersistThread.cpp
  libraries/physics/src/EntityMotionState.cpp
  libraries/physics/src/EntityMotionState.h
  libraries/physics/src/ObjectActionTractor.cpp
  libraries/physics/src/ObjectActionTravelOriented.cpp
  libraries/physics/src/ObjectDynamic.h
  libraries/physics/src/ObjectMotionState.cpp
  libraries/physics/src/ObjectMotionState.h
  libraries/physics/src/PhysicalEntitySimulation.cpp
  libraries/physics/src/PhysicalEntitySimulation.h
  libraries/physics/src/PhysicsEngine.cpp
  libraries/physics/src/PhysicsEngine.h
  libraries/physics/src/ShapeFactory.cpp
  libraries/physics/src/ShapeFactory.h
  libraries/physics/src/ShapeManager.cpp
  libraries/physics/src/ShapeManager.h
  libraries/shared/src/HashKey.cpp
  libraries/shared/src/HashKey.h
  libraries/shared/src/ShapeInfo.cpp
  libraries/shared/src/SimulationFlags.h
  libraries/workload/src/workload/View.cpp
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#15529 Add instrumentation to help track down connection issues
  assignment-client/src/AssignmentClient.cpp
  domain-server/src/DomainGatekeeper.cpp
  domain-server/src/DomainServer.cpp
  domain-server/src/DomainServer.h
  interface/src/Application.cpp
  libraries/networking/src/AddressManager.cpp
  libraries/networking/src/DomainHandler.cpp
  libraries/networking/src/DomainHandler.h
  libraries/networking/src/LimitedNodeList.cpp
  libraries/networking/src/NetworkLogging.cpp
  libraries/networking/src/NetworkLogging.h
  libraries/networking/src/NetworkPeer.h
  libraries/networking/src/NodeList.cpp
  libraries/networking/src/NodeList.h
  libraries/networking/src/ThreadedAssignment.cpp
  tools/ac-client/src/ACClientApp.cpp
  tools/atp-client/src/ATPClientApp.cpp
Labels: Development Approved

#15530 BUGZ-85 - extrapolate audio on network lag spike to reduce pop
  assignment-client/src/audio/AvatarAudioStream.cpp
  libraries/audio/src/InboundAudioStream.cpp
  libraries/audio/src/InboundAudioStream.h
  libraries/audio/src/MixedProcessedAudioStream.cpp
Labels: Development Ready, Metaverse, PRE-MERGE TESTING REQUIRED, QA Approved :tada:

#15539 BUGZ-131: Reduce spam from watchdog thread
  interface/src/Application.cpp
Labels: Development Approved, Project Approved

#15542 Make DependencyManager thread-safe
  libraries/shared/src/DependencyManager.cpp
  libraries/shared/src/DependencyManager.h
  libraries/shared/src/Profile.cpp
  tests/shared/src/DependencyManagerTests.cpp
  tests/shared/src/DependencyManagerTests.h
Labels: Beware: Threading/Deadlock, Development Approved, Engine

#15543 BUGZ-139, Case 22502: Fix zone inheritance
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.h
Labels: Development Approved, Engine, Project Approved

#15522 Case 22494, BUGZ-127: Render lightmaps in the forward renderer
  libraries/render-utils/src/RenderPipelines.cpp
  libraries/render-utils/src/forward_model_lightmap.slf
  libraries/render-utils/src/forward_model_normal_map_lightmap.slf
  libraries/render-utils/src/render-utils/forward_model_lightmap.slp
  libraries/render-utils/src/render-utils/forward_model_normal_map_lightmap.slp
Labels: Development Approved, Engine, Project Approved

#15469 Case 22379: Run-time switch for deferred/forward rendering
  interface/src/Application.cpp
  interface/src/SecondaryCamera.cpp
  interface/src/SecondaryCamera.h
  interface/src/graphics/GraphicsEngine.cpp
  interface/src/graphics/GraphicsEngine.h
  interface/src/graphics/WorldBox.cpp
  interface/src/raypick/ParabolaPointer.cpp
  interface/src/raypick/ParabolaPointer.h
  interface/src/workload/GameWorkloadRenderer.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
  libraries/entities-renderer/src/RenderableGizmoEntityItem.cpp
  libraries/entities-renderer/src/RenderableGridEntityItem.cpp
  libraries/entities-renderer/src/RenderableLineEntityItem.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities-renderer/src/RenderablePolyLineEntityItem.cpp
  libraries/entities-renderer/src/RenderablePolyLineEntityItem.h
  libraries/entities-renderer/src/RenderableShapeEntityItem.cpp
  libraries/entities-renderer/src/RenderableTextEntityItem.cpp
  libraries/procedural/src/procedural/Procedural.cpp
  libraries/render-utils/src/GeometryCache.cpp
  libraries/render-utils/src/GeometryCache.h
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
  libraries/render-utils/src/RenderCommonTask.h
  libraries/render-utils/src/RenderForwardTask.cpp
  libraries/render-utils/src/RenderViewTask.cpp
  libraries/render-utils/src/RenderViewTask.h
  libraries/render-utils/src/TextRenderer3D.cpp
  libraries/render-utils/src/TextRenderer3D.h
  libraries/render-utils/src/forward_grid.slf
  libraries/render-utils/src/forward_grid_translucent.slf
  libraries/render-utils/src/forward_parabola.slf
  libraries/render-utils/src/parabola_forward.slv
  libraries/render-utils/src/render-utils/forward_grid.slp
  libraries/render-utils/src/render-utils/forward_grid_translucent.slp
  libraries/render-utils/src/render-utils/forward_parabola.slp
  libraries/render-utils/src/text/Font.cpp
  libraries/render-utils/src/text/Font.h
  libraries/render/src/render/Args.h
  libraries/shared/src/DisableDeferred.h
  libraries/shared/src/RenderForward.h
  libraries/task/src/task/Config.cpp
  libraries/task/src/task/Config.h
  libraries/task/src/task/Task.h
Labels: Development Approved, Engine, Project Approved, Quest Required

#15485 (case 22026) Fix crash due to invalid indices in baker::calculateNormals
  libraries/model-baker/src/model-baker/CalculateBlendshapeNormalsTask.cpp
  libraries/model-baker/src/model-baker/CalculateMeshNormalsTask.cpp
  libraries/model-baker/src/model-baker/ModelMath.h
Labels: Development Approved, Engine, Project Approved

#15508 Case 22467: Fix material target tooltip
  scripts/system/assets/data/createAppTooltips.json
Labels: Create, Development Approved, Project Approved

#15535 Fix mac build warnings
  CMakeLists.txt
  libraries/model-networking/src/model-networking/ModelCache.cpp
Labels: Development Approved

#15541 Clear any reliable connection state upon Node ID change
  interface/src/avatar/MyAvatar.cpp
  libraries/networking/src/NodeList.cpp
Labels: Development Approved, Metaverse

#15540 BUGZ-125: Error message instead of crash if the GL version is too low
  interface/src/main.cpp
  libraries/gl/src/gl/GLHelpers.cpp
  libraries/gl/src/gl/GLHelpers.h
  tests-manual/gl/src/main.cpp
Labels: Development Approved, Engine

#15301 case 22190: Disable triggering away state when interface focus lost
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/scripting/HMDScriptingInterface.cpp
  interface/src/scripting/HMDScriptingInterface.h
  interface/src/ui/PreferencesDialog.cpp
  scripts/system/away.js
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, QA Approved :tada:

#15544 (BUGZ-40) Check for possible avatar fade race condition
  interface/src/avatar/AvatarManager.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
Labels: Development Approved, Engine, Project Approved

#15476 Case 22407: Quat JSDoc update
  interface/src/FancyCamera.h
  libraries/script-engine/src/Quat.h
Labels: JSDocs, Project Approved

#15521 Case 22489: Scene JSDoc
  libraries/script-engine/src/SceneScriptingInterface.h
Labels: JSDocs

#15550 BUGZ-89: Suppress getTransform spam
  libraries/shared/src/SpatiallyNestable.cpp
Labels: Client, Development Approved, Engine, Project Approved

#15454 Case 22246: Picks, PickType, RayPick JSDoc update
  interface/src/raypick/CollisionPick.cpp
  interface/src/raypick/ParabolaPick.h
  interface/src/raypick/PickScriptingInterface.cpp
  interface/src/raypick/PickScriptingInterface.h
  interface/src/raypick/PointerScriptingInterface.h
  interface/src/raypick/RayPick.h
  interface/src/raypick/RayPickScriptingInterface.h
  interface/src/raypick/StylusPick.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/pointers/src/Pick.h
  libraries/render-utils/src/Model.cpp
  libraries/shared/src/PhysicsCollisionGroups.h
  libraries/shared/src/PickFilter.h
  libraries/shared/src/RegisteredMetaTypes.h
  libraries/shared/src/ShapeInfo.cpp
Labels: JSDocs, Project Approved

#15548 BUGZ-173: Fix deadlock on startup
  libraries/shared/src/DependencyManager.h
Labels: Development Approved, Engine, Project Approved

#15554 case 123: delete children of deleted avatar-entity
  interface/src/avatar/AvatarManager.cpp
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
Labels: Development Approved, Engine, Project Approved, bug

#15549 Call correct NodeList::reset() from Application
  interface/src/Application.cpp
Labels: Development Approved, Metaverse, Project Approved

#15556 BUGZ-131: Additional silencing of watchdog spam
  interface/src/Application.cpp
Labels: Development Approved, Project Approved

#15514 New Entity Property: Private User Data
  assignment-client/src/entities/EntityTreeSendThread.cpp
  domain-server/resources/describe-settings.json
  domain-server/src/DomainGatekeeper.cpp
  domain-server/src/DomainServerSettingsManager.cpp
  libraries/entities/src/EntityEditPacketSender.cpp
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityItemPropertiesDefaults.h
  libraries/entities/src/EntityPropertyFlags.h
  libraries/entities/src/EntityScriptingInterface.cpp
  libraries/entities/src/EntityScriptingInterface.h
  libraries/entities/src/EntityTree.cpp
  libraries/networking/src/LimitedNodeList.cpp
  libraries/networking/src/LimitedNodeList.h
  libraries/networking/src/Node.h
  libraries/networking/src/NodePermissions.cpp
  libraries/networking/src/NodePermissions.h
  libraries/networking/src/udt/PacketHeaders.h
Labels: Development Approved, Packet Version Change, Project Approved, QA Ready, Scripting API change

#15232 Update BUILD_WIN.md
  BUILD_WIN.md
Labels: Development Approved, Documentation

#15558 BUGZ-178: avoid crash for RenderableModelEntityItem with invalid model
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities/src/ModelEntityItem.cpp
  libraries/physics/src/PhysicalEntitySimulation.cpp
Labels: Development Approved, Engine, Project Approved

#15506 Case 19510: Unify cube and sphere edit menu entries into one.
  interface/resources/qml/hifi/tablet/EditTabView.qml
  interface/resources/qml/hifi/tablet/EditToolsTabView.qml
  scripts/developer/tests/toolbarTest.js
  scripts/system/edit.js
Labels: Create, Development Approved, PRE-MERGE TESTING REQUIRED, Project Approved

#15559 Allow for delayed challenges if salt is empty
  assignment-client/src/avatars/MixerAvatar.cpp
  assignment-client/src/avatars/MixerAvatar.h
  interface/resources/images/AvatarTheftBanner.png
  interface/src/commerce/Ledger.cpp
  interface/src/commerce/Wallet.cpp
  interface/src/commerce/Wallet.h
Labels: Avatar, Development Approved, Metaverse, Project Approved

#15551 Queue depth debugging code
  assignment-client/src/audio/AudioMixer.cpp
  assignment-client/src/audio/AudioMixerSlavePool.cpp
  assignment-client/src/audio/AudioMixerSlavePool.h
  assignment-client/src/avatars/AvatarMixer.cpp
  assignment-client/src/avatars/AvatarMixerSlavePool.cpp
  assignment-client/src/avatars/AvatarMixerSlavePool.h
  cmake/macros/SetupQt.cmake
  interface/resources/qml/Stats.qml
  interface/src/Application.cpp
  interface/src/ui/Stats.cpp
  interface/src/ui/Stats.h
  libraries/networking/src/DomainHandler.cpp
  libraries/networking/src/ThreadedAssignment.cpp
  libraries/shared/CMakeLists.txt
  libraries/shared/src/shared/QtHelpers.cpp
  libraries/shared/src/shared/QtHelpers.h
Labels: Development Approved, Metaverse, PRE-MERGE TESTING REQUIRED, Project Approved

#15560 BUGZ-87 - loading/physics stuck when entering domain
  libraries/physics/src/ShapeManager.cpp
Labels: Development Approved, Metaverse, Project Approved, bug

#15538 Simplified UI v1
  interface/resources/fonts/Graphik-Medium.ttf
  interface/resources/fonts/Graphik-Regular.ttf
  interface/resources/fonts/Graphik-Semibold.ttf
  interface/resources/qml/AvatarInputsBar.qml
  interface/resources/qml/hifi/simplifiedUI/avatarApp/AvatarApp.qml
  interface/resources/qml/hifi/simplifiedUI/avatarApp/components/AvatarAppListDelegate.qml
  interface/resources/qml/hifi/simplifiedUI/avatarApp/components/DisplayNameHeader.qml
  interface/resources/qml/hifi/simplifiedUI/images/accent.svg
  interface/resources/qml/hifi/simplifiedUI/images/loading.gif
  interface/resources/qml/hifi/simplifiedUI/inputDeviceButton/InputDeviceButton.qml
  interface/resources/qml/hifi/simplifiedUI/inputDeviceButton/images/mic-clip-i.svg
  interface/resources/qml/hifi/simplifiedUI/inputDeviceButton/images/mic-gate-i.svg
  interface/resources/qml/hifi/simplifiedUI/inputDeviceButton/images/mic-mute-a.svg
  interface/resources/qml/hifi/simplifiedUI/inputDeviceButton/images/mic-mute-i.svg
  interface/resources/qml/hifi/simplifiedUI/inputDeviceButton/images/mic-ptt-a.svg
  interface/resources/qml/hifi/simplifiedUI/inputDeviceButton/images/mic-ptt-i.svg
  interface/resources/qml/hifi/simplifiedUI/inputDeviceButton/images/mic-unmute-a.svg
  interface/resources/qml/hifi/simplifiedUI/inputDeviceButton/images/mic-unmute-i.svg
  interface/resources/qml/hifi/simplifiedUI/settingsApp/SettingsApp.qml
  interface/resources/qml/hifi/simplifiedUI/settingsApp/audio/Audio.qml
  interface/resources/qml/hifi/simplifiedUI/settingsApp/general/General.qml
  interface/resources/qml/hifi/simplifiedUI/settingsApp/vr/VR.qml
  interface/resources/qml/hifi/simplifiedUI/simplifiedConstants/SimplifiedConstants.qml
  interface/resources/qml/hifi/simplifiedUI/simplifiedControls/Button.qml
  interface/resources/qml/hifi/simplifiedUI/simplifiedControls/CheckBox.qml
  interface/resources/qml/hifi/simplifiedUI/simplifiedControls/InputPeak.qml
  interface/resources/qml/hifi/simplifiedUI/simplifiedControls/RadioButton.qml
  interface/resources/qml/hifi/simplifiedUI/simplifiedControls/Slider.qml
  interface/resources/qml/hifi/simplifiedUI/simplifiedControls/Switch.qml
  interface/resources/qml/hifi/simplifiedUI/simplifiedControls/TextField.qml
  interface/resources/qml/hifi/simplifiedUI/topBar/SimplifiedTopBar.qml
  interface/resources/qml/hifi/simplifiedUI/topBar/images/defaultAvatar.jpg
  interface/resources/qml/stylesUit/GraphikMedium.qml
  interface/resources/qml/stylesUit/GraphikRegular.qml
  interface/resources/qml/stylesUit/GraphikSemiBold.qml
  interface/resources/qml/stylesUit/qmldir
  interface/src/Application.cpp
  interface/src/avatar/MyAvatar.h
  interface/src/ui/AvatarInputs.cpp
  interface/src/ui/AvatarInputs.h
  scripts/system/simplifiedNametag/resources/modules/defaultLocalEntityProps.js
  scripts/system/simplifiedNametag/resources/modules/entityMaker.js
  scripts/system/simplifiedNametag/resources/modules/nameTagListManager.js
  scripts/system/simplifiedNametag/resources/modules/objectAssign.js
  scripts/system/simplifiedNametag/resources/modules/pickRayController.js
  scripts/system/simplifiedNametag/resources/modules/textHelper.js
  scripts/system/simplifiedNametag/simplifiedNametag.js
  scripts/system/simplifiedUI/images/inputDeviceMuted.svg
  scripts/system/simplifiedUI/images/outputDeviceMuted.svg
  scripts/system/simplifiedUI/simplifiedUI.js
Labels: Development Ready, Project Approved

#15561 Added node requirement to BUILD_LINUX.md
  BUILD_LINUX.md
Labels: Development Ready

#14945 Case 19748: Audio loss statistic occasionally displays a huge number
  libraries/networking/src/SequenceNumberStats.cpp
Labels: Development Approved, Server & Network, bug

#15513 Case 22147: Desktop, Paths, PlatformInfo, Window, and location JSDoc
  interface/src/scripting/DesktopScriptingInterface.cpp
  interface/src/scripting/DesktopScriptingInterface.h
  interface/src/scripting/PlatformInfoScriptingInterface.h
  interface/src/scripting/WindowScriptingInterface.h
  interface/src/ui/InteractiveWindow.cpp
  interface/src/ui/InteractiveWindow.h
  libraries/material-networking/src/material-networking/TextureCache.cpp
  libraries/networking/src/AddressManager.h
  libraries/shared/src/PathUtils.h
Labels: JSDocs, Project Approved

#14519 Use QSaveFile when persisting domain settings to disk
  domain-server/src/DomainServerSettingsManager.cpp
Labels: Development Approved

#15512 case lily-29: Feature/platform. Creating a single point api to get system info
  interface/CMakeLists.txt
  interface/src/Application.h
  libraries/platform/CMakeLists.txt
  libraries/platform/src/AndroidPlatform.cpp
  libraries/platform/src/AndroidPlatform.h
  libraries/platform/src/LinuxPlatform.cpp
  libraries/platform/src/LinuxPlatform.h
  libraries/platform/src/MACOSPlatform.cpp
  libraries/platform/src/MACOSPlatform.h
  libraries/platform/src/WINPlatform.cpp
  libraries/platform/src/WINPlatform.h
  libraries/platform/src/platform.cpp
  libraries/platform/src/platform.h
  libraries/platform/src/platformInstance.cpp
  libraries/platform/src/platformInstance.h
  libraries/platform/src/platformJsonKeys.h
  libraries/shared/CMakeLists.txt
  libraries/shared/src/GPUIdent.cpp
  libraries/shared/src/GPUIdent.h
Labels: Development Approved, Engine, Project Approved

#14366 Case 22169: GLTF Importer Improvements
  libraries/fbx/src/GLTFSerializer.cpp
  libraries/fbx/src/GLTFSerializer.h
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#15566 BUGZ-141: Fix the LOD target value not in sync with the RefreshRate setting
  interface/src/LODManager.cpp
  libraries/display-plugins/src/display-plugins/RefreshRateController.cpp
  libraries/display-plugins/src/display-plugins/RefreshRateController.h
  libraries/plugins/src/plugins/DisplayPlugin.h
Labels: Development Approved, Engine, Project Approved

#15567 Fix JS to QML event bridge messages with Docked Windows
  interface/src/ui/InteractiveWindow.cpp
  interface/src/ui/InteractiveWindow.h
Labels: Client, Development Approved, Project Approved, bug

#15568 BUGZ-145: Fix Window innerWidth and innerHeight after support for Docked window
  interface/src/scripting/WindowScriptingInterface.cpp
Labels: Development Ready, Engine

#15562 BUGZ-133: Expose additional functionality to QML/Scripts
  interface/src/Application.cpp
  interface/src/RefreshRateManager.cpp
  interface/src/RefreshRateManager.h
  interface/src/scripting/PerformanceScriptingInterface.cpp
  interface/src/scripting/PerformanceScriptingInterface.h
  interface/src/scripting/RefreshRateScriptingInterface.h
  interface/src/scripting/WindowScriptingInterface.cpp
  interface/src/scripting/WindowScriptingInterface.h
Labels: Development Approved, Engine, Project Approved

#15570 Add guard for Client-challenging Node not connected
  interface/src/commerce/Wallet.cpp
Labels: Development Approved, Metaverse, Project Approved

#15573 Simplified UI v1 Improvements
  interface/resources/qml/hifi/simplifiedUI/avatarApp/AvatarApp.qml
  interface/resources/qml/hifi/simplifiedUI/avatarApp/components/AvatarAppListDelegate.qml
  interface/resources/qml/hifi/simplifiedUI/avatarApp/components/DisplayNameHeader.qml
  interface/resources/qml/hifi/simplifiedUI/images/defaultAvatar.svg
  interface/resources/qml/hifi/simplifiedUI/inputDeviceButton/InputDeviceButton.qml
  interface/resources/qml/hifi/simplifiedUI/inputDeviceButton/images/mic-clip-i.svg
  interface/resources/qml/hifi/simplifiedUI/inputDeviceButton/images/mic-gate-i.svg
  interface/resources/qml/hifi/simplifiedUI/inputDeviceButton/images/mic-mute-a.svg
  interface/resources/qml/hifi/simplifiedUI/inputDeviceButton/images/mic-mute-i.svg
  interface/resources/qml/hifi/simplifiedUI/inputDeviceButton/images/mic-ptt-a.svg
  interface/resources/qml/hifi/simplifiedUI/inputDeviceButton/images/mic-ptt-i.svg
  interface/resources/qml/hifi/simplifiedUI/inputDeviceButton/images/mic-unmute-a.svg
  interface/resources/qml/hifi/simplifiedUI/inputDeviceButton/images/mic-unmute-i.svg
  interface/resources/qml/hifi/simplifiedUI/topBar/SimplifiedTopBar.qml
  interface/resources/qml/hifi/simplifiedUI/topBar/images/defaultAvatar.jpg
  interface/resources/qml/hifi/simplifiedUI/topBar/images/desktopMode.svg
  interface/resources/qml/hifi/simplifiedUI/topBar/images/outputDeviceLoud.svg
  interface/resources/qml/hifi/simplifiedUI/topBar/images/outputDeviceMuted.svg
  interface/resources/qml/hifi/simplifiedUI/topBar/images/settings.svg
  interface/resources/qml/hifi/simplifiedUI/topBar/images/vrMode.svg
  scripts/system/simplifiedUI/simplifiedUI.js
Labels: Development Ready, UI/UX

#14533 Case 22439: Fix HMD auto switch detection
  interface/src/Application.cpp
  interface/src/Application.h
Labels: Development Approved, Engine, Oculus Required, Project Approved

#15576 Simplified UI v1: Implement Performance settings and VR mode top bar switch
  interface/resources/qml/hifi/simplifiedUI/settingsApp/general/General.qml
  interface/resources/qml/hifi/simplifiedUI/topBar/SimplifiedTopBar.qml
Labels: Development Approved, QA Ready (internal), UI/UX

#15569 BUGZ-187: Proper Render Scripting Interface with renderMethod property
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/scripting/RenderScriptingInterface.cpp
  interface/src/scripting/RenderScriptingInterface.h
  libraries/render-utils/src/RenderViewTask.cpp
  libraries/task/src/task/Config.h
Labels: Development Approved, Engine, Scripting API change

#15575 case BUGZ-57: Populate macos gpu _name
  libraries/platform/src/AndroidPlatform.cpp
  libraries/platform/src/AndroidPlatform.h
  libraries/platform/src/LinuxPlatform.cpp
  libraries/platform/src/LinuxPlatform.h
  libraries/platform/src/MACOSPlatform.cpp
  libraries/platform/src/MACOSPlatform.h
  libraries/platform/src/WINPlatform.cpp
  libraries/platform/src/WINPlatform.h
  libraries/platform/src/platform.cpp
  libraries/platform/src/platform.h
  libraries/platform/src/platformInstance.cpp
  libraries/platform/src/platformInstance.h
  libraries/platform/src/platformJsonKeys.h
  libraries/shared/src/GPUIdent.cpp
Labels: Development Approved, Engine, Project Approved

#15572 Fix blender::run crash
  libraries/hfm/src/hfm/HFM.h
  libraries/model-networking/src/model-networking/ModelCache.h
  libraries/render-utils/src/CauterizedModel.cpp
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
  libraries/render-utils/src/SoftAttachmentModel.cpp
Labels: Beware: Threading/Deadlock, Development Approved, Engine, Project Approved

#15578 Case 22520: Tidy new Window API plugin functions' JSDoc
  interface/src/scripting/WindowScriptingInterface.h
  libraries/networking/src/MessagesClient.h
Labels: JSDocs

#15563 Make avatar-theft banner emissive
  interface/src/ui/AvatarCertifyBanner.cpp
Labels: Client, Development Approved, Project Approved

#15579 Defer avatar PoP check
  assignment-client/src/avatars/AvatarMixerClientData.cpp
Labels: Development Approved, Metaverse, Project Approved

#15581 Simplified UI V1: Remove some extra menus from top bar; Only show VR button if headset connected at startup
  interface/resources/qml/hifi/simplifiedUI/topBar/SimplifiedTopBar.qml
  scripts/system/simplifiedUI/simplifiedUI.js
Labels: Development Approved, Project Approved, QA Ready (internal)

#15580 changed size of always on overlays to be smaller
  scripts/system/simplifiedUI/simplifiedNametag/resources/modules/defaultLocalEntityProps.js
  scripts/system/simplifiedUI/simplifiedNametag/resources/modules/entityMaker.js
  scripts/system/simplifiedUI/simplifiedNametag/resources/modules/nameTagListManager.js
  scripts/system/simplifiedUI/simplifiedNametag/resources/modules/objectAssign.js
  scripts/system/simplifiedUI/simplifiedNametag/resources/modules/pickRayController.js
  scripts/system/simplifiedUI/simplifiedNametag/resources/modules/textHelper.js
  scripts/system/simplifiedUI/simplifiedNametag/simplifiedNametag.js
  scripts/system/simplifiedUI/simplifiedUI.js
Labels: Development Approved, Project Approved

#15584 BUGZ-132: Fix avatar loading spheres
  interface/src/avatar/AvatarManager.cpp
  interface/src/avatar/OtherAvatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
Labels: Development Approved, Engine, Project Approved

#15583 BUGZ-243: Attempt to fix material crash
  libraries/render-utils/src/Model.cpp
Labels: Development Approved, Engine, Project Approved

#15582 put DomainServerCheckIn on NodeList thread
  interface/src/Application.cpp
  libraries/networking/src/NodeList.cpp
Labels: Development Approved, Metaverse, Project Approved

#15586 debian-style package for interface
  debian/changelog
  debian/compat
  debian/control
  debian/copyright
  debian/hifi-interface-docs.docs
  debian/hifi-interface.dirs
  debian/patches/hifi_use_system_qt.diff
  debian/patches/series
  debian/rules
  debian/source/format
  debian/source/include-binaries
Labels: Development Approved, Engine, Project Approved

#15588 (BUGZ-262) Add debug tool for transitions
  interface/src/Menu.cpp
  interface/src/Menu.h
  libraries/entities-renderer/src/RenderableEntityItem.cpp
  libraries/render/src/render/DrawStatus.cpp
  libraries/render/src/render/DrawStatus.h
  libraries/render/src/render/Item.h
Labels: Development Approved, Engine, Project Approved

#15589 BUGZ-250: Don't crash on trying to add items to non-existent menus
  libraries/ui-plugins/src/ui-plugins/PluginContainer.cpp
Labels: Development Approved, Engine, Project Approved

#15510 Case 22007: vcpkg update for Qt
  BUILD.md
  BUILD_LINUX.md
  BUILD_OSX.md
  BUILD_WIN.md
  CMakeLists.txt
  cmake/macros/FixupInterface.cmake
  cmake/macros/FixupNitpick.cmake
  cmake/macros/PackageLibrariesForDeployment.cmake
  cmake/macros/SetupQt.cmake
  hifi_vcpkg.py
  interface/CMakeLists.txt
  prebuild.py
  tools/nitpick/CMakeLists.txt
  tools/nitpick/src/PythonInterface.cpp
  tools/nitpick/src/PythonInterface.h
  tools/qt-builder/README.md
  tools/qt-builder/patches/aec.patch
  tools/qt-builder/patches/qfloat16.patch
  tools/qt-builder/qt.conf
  tools/qt-builder/qt5vars.bat
Labels: Development Approved, Engine, Project Approved

#15587 reduce time in which you see yourself going away
  libraries/networking/src/LimitedNodeList.h
Labels: Development Approved, Metaverse, Project Approved

#15593 obey QT_CMAKE_PREFIX_PATH for non DEV_BUILD on UNIX
  cmake/macros/SetupQt.cmake
Labels: Development Approved, Engine, Project Approved

#15594 DEV-54: Add support for application config
  interface/src/main.cpp
Labels: Client, Development Approved, Project Approved

#15597 Case BUGZ-277 : Android build error (on windows host) stat properties missing (please review suggestion)
  interface/src/ui/Stats.h
Labels: Development Approved, Development Ready, Engine, Project Approved

#15598 BUGZ-283: Fix MyAvatar.skeletonModelURL
  assignment-client/src/avatars/ScriptableAvatar.h
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
  libraries/avatars/src/AvatarData.h
Labels: Development Approved, Engine, Project Approved

#15599 (BUGZ-167) Always calculate tangents
  libraries/model-baker/src/model-baker/Baker.cpp
  libraries/model-baker/src/model-baker/CalculateBlendshapeTangentsTask.cpp
  libraries/model-baker/src/model-baker/CalculateBlendshapeTangentsTask.h
  libraries/model-baker/src/model-baker/CalculateMeshTangentsTask.cpp
  libraries/model-baker/src/model-baker/CalculateMeshTangentsTask.h
Labels: Development Approved, Engine

#15596 BUGZ-178: avoid crash for RenderableModelEntityItem with invalid model (redux)
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
Labels: Development Approved, Engine, Project Approved

#15590 BUGZ-284: Add shadows, AA, and AO to RenderScriptingInterface
  interface/src/Menu.cpp
  interface/src/scripting/RenderScriptingInterface.cpp
  interface/src/scripting/RenderScriptingInterface.h
  libraries/render-utils/src/AntialiasingEffect.cpp
  libraries/render-utils/src/AntialiasingEffect.h
  libraries/render-utils/src/RenderDeferredTask.cpp
Labels: Development Approved, Engine, Project Approved

#15591 Case 22493: Script JSDoc
  libraries/entities/src/EntityScriptingInterface.h
  libraries/script-engine/src/ScriptEngine.cpp
  libraries/script-engine/src/ScriptEngine.h
  libraries/shared/src/BaseScriptEngine.h
Labels: Development Approved, JSDocs, Project Approved

#15600 BUGZ-223 - Physics was not starting in TheSpot-dev
  interface/src/octree/SafeLanding.cpp
  interface/src/octree/SafeLanding.h
Labels: Development Approved, Metaverse, PRE-MERGE TESTING REQUIRED, Project Approved, bug

#15595 BUGZ-296: Linux platform implementation
  libraries/platform/src/LinuxPlatform.cpp
  libraries/shared/src/GPUIdent.cpp
Labels: Development Approved, Development Ready, Engine

#15601 Simplified UI: Updates! (See Description)
  interface/resources/qml/hifi/simplifiedUI/settingsApp/audio/Audio.qml
  interface/resources/qml/hifi/simplifiedUI/settingsApp/general/General.qml
  interface/resources/qml/hifi/simplifiedUI/settingsApp/vr/VR.qml
  interface/resources/qml/hifi/simplifiedUI/simplifiedConstants/SimplifiedConstants.qml
  interface/resources/qml/hifi/simplifiedUI/simplifiedControls/RadioButton.qml
  interface/resources/qml/hifi/simplifiedUI/topBar/SimplifiedTopBar.qml
  interface/resources/qml/hifi/simplifiedUI/topBar/images/focus.svg
  interface/resources/qml/hifi/simplifiedUI/topBar/images/status.svg
  libraries/display-plugins/src/display-plugins/AbstractHMDScriptingInterface.h
  scripts/system/simplifiedUI/simplifiedStatusIndicator/simplifiedStatusIndicator.js
  scripts/system/simplifiedUI/simplifiedUI.js
Labels: Development Approved, Project Approved, QA Ready (internal), UI/UX

#15603 BUGZ-223 - Fix crash when adding a tracked entity to the safe landing code
  interface/src/octree/SafeLanding.cpp
Labels: Development Approved, Project Approved

#15604 Case 22527: Settings JSDoc
  interface/src/scripting/SettingsScriptingInterface.h
Labels: JSDocs, Project Approved

#15605 Case 22528: Snapshot JSDoc
  interface/src/scripting/WindowScriptingInterface.h
  interface/src/ui/Snapshot.h
Labels: JSDocs, Project Approved

#15606 Simplified UI - two quick fixes.
  interface/resources/qml/hifi/simplifiedUI/topBar/SimplifiedTopBar.qml
  scripts/system/simplifiedUI/simplifiedStatusIndicator/simplifiedStatusIndicator.js
  scripts/system/simplifiedUI/simplifiedUI.js
Labels: Development Approved, Project Approved, QA Ready (internal), UI/UX

#15608 Fix environment volume slider (BUGZ-213); optimize sliders
  interface/resources/qml/hifi/simplifiedUI/settingsApp/audio/Audio.qml
  interface/resources/qml/hifi/simplifiedUI/simplifiedControls/Slider.qml
Labels: Development Approved, Project Approved, QA Ready (internal), UI/UX

#15609 (BUGZ-298) Fix crash calculating tangents without texcoords
  libraries/model-baker/src/model-baker/CalculateBlendshapeTangentsTask.cpp
  libraries/model-baker/src/model-baker/CalculateMeshTangentsTask.cpp
Labels: Development Approved, Engine, Project Approved

#15612 BUGZ-322 - add domain checkin lag logging
  domain-server/src/DomainGatekeeper.cpp
  domain-server/src/DomainServer.cpp
  domain-server/src/DomainServerNodeData.h
  domain-server/src/NodeConnectionData.cpp
  domain-server/src/NodeConnectionData.h
  libraries/networking/src/NodeList.cpp
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
Labels: Development Approved, Metaverse, Packet Version Change, Project Approved, bug

#15614 Case 22513: Selection JSDoc
  interface/src/scripting/SelectionScriptingInterface.cpp
  interface/src/scripting/SelectionScriptingInterface.h
Labels: Development Approved, JSDocs, Project Approved

#15616 Define/show some error states in the Avatar app
  interface/resources/qml/hifi/simplifiedUI/avatarApp/AvatarApp.qml
Labels: Development Approved, Project Approved, QA Ready (internal), UI/UX

#15613 Fix the janky audio output settings UI
  interface/resources/qml/hifi/simplifiedUI/settingsApp/audio/Audio.qml
  interface/resources/qml/hifi/simplifiedUI/simplifiedConstants/SimplifiedConstants.qml
  interface/resources/qml/hifi/simplifiedUI/topBar/SimplifiedTopBar.qml
  interface/src/scripting/Audio.cpp
  interface/src/scripting/Audio.h
  scripts/system/simplifiedUI/simplifiedUI.js
Labels: Development Approved, JSDocs, Project Approved, QA Ready (internal), UI/UX

#15617 BUGZ-320: Fix nodelist reset on logout/username change
  libraries/networking/src/NodeList.cpp
Labels: Development Approved, Metaverse, Project Approved

#15620 Revert "BUGZ-322 - add domain checkin lag logging"
  domain-server/src/DomainGatekeeper.cpp
  domain-server/src/DomainServer.cpp
  domain-server/src/DomainServerNodeData.h
  domain-server/src/NodeConnectionData.cpp
  domain-server/src/NodeConnectionData.h
  libraries/networking/src/NodeList.cpp
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
Labels: Development Approved, Metaverse, Project Approved

#15621 BUGZ-340: Move SimplifiedUI folder and create new defaultScripts.js
  scripts/simplifiedUI/defaultScripts.js
  scripts/simplifiedUI/images/inputDeviceMuted.svg
  scripts/simplifiedUI/images/outputDeviceMuted.svg
  scripts/simplifiedUI/simplifiedNametag/resources/modules/defaultLocalEntityProps.js
  scripts/simplifiedUI/simplifiedNametag/resources/modules/entityMaker.js
  scripts/simplifiedUI/simplifiedNametag/resources/modules/nameTagListManager.js
  scripts/simplifiedUI/simplifiedNametag/resources/modules/objectAssign.js
  scripts/simplifiedUI/simplifiedNametag/resources/modules/pickRayController.js
  scripts/simplifiedUI/simplifiedNametag/resources/modules/textHelper.js
  scripts/simplifiedUI/simplifiedNametag/simplifiedNametag.js
  scripts/simplifiedUI/simplifiedStatusIndicator/simplifiedStatusIndicator.js
  scripts/simplifiedUI/simplifiedUI.js
Labels: Client, Development Approved, Development Ready, QA Ready (internal)

#15622 Fix a bunch of Simplified UI issues (see description)
  interface/resources/qml/hifi/simplifiedUI/settingsApp/audio/Audio.qml
  interface/resources/qml/hifi/simplifiedUI/settingsApp/vr/VR.qml
  scripts/simplifiedUI/simplifiedUI.js
Labels: Development Approved, Project Approved, QA Ready (internal), UI/UX

#15623 BUGZ 345: avoid resource leak in AvatarManger::_otherAvatarsToChangeInPhysics
  interface/src/avatar/AvatarManager.cpp
Labels: Development Approved, Engine, Project Approved

#15625 Fix BUGZ-336: Microphone test does not stop unless you press the button to "stop test"
  interface/resources/qml/hifi/simplifiedUI/settingsApp/audio/Audio.qml
  interface/resources/qml/hifi/simplifiedUI/settingsApp/vr/VR.qml
Labels: Development Approved, Project Approved, QA Ready (internal), UI/UX

#15619 BUGZ-158: Crash when switching audio devices on Mac
  libraries/audio-client/src/AudioClient.cpp
  libraries/audio/src/InboundAudioStream.cpp
Labels: Client, Critical Fix, Development Approved, Mac Required, Project Approved, bug

#15607 only worry about Ubuntu major versions when selecting Qt package
  hifi_vcpkg.py
Labels: Development Approved, Engine

#15624 Update windows build with symbols for release qt-5.12.3
  cmake/ports/bullet3/portfile.cmake
  hifi_vcpkg.py
  tools/qt-builder/README.md
  tools/qt-builder/qt5vars.bat
Labels: Development Approved, Project Approved

#15618 Pass tokens as params for automatic login
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/main.cpp
  libraries/networking/src/AccountManager.cpp
  libraries/networking/src/AccountManager.h
Labels: Client, Development Approved, Project Approved

#15615 DEV-50: Add postbuild script
  tools/ci-scripts/postbuild.py
Labels: Development Approved, Project Approved

#15628 Move SimplifiedUI folder again, and make the associated defaultScripts.js actually work
  scripts/simplifiedUI/defaultScripts.js
  scripts/simplifiedUI/modules/appUi.js
  scripts/simplifiedUI/modules/request.js
  scripts/simplifiedUI/modules/vec3.js
  scripts/simplifiedUI/system/away.js
  scripts/simplifiedUI/system/controllers/+android_questInterface/controllerScripts.js
  scripts/simplifiedUI/system/controllers/controllerDispatcher.js
  scripts/simplifiedUI/system/controllers/controllerDisplay.js
  scripts/simplifiedUI/system/controllers/controllerDisplayManager.js
  scripts/simplifiedUI/system/controllers/controllerModules/disableOtherModule.js
  scripts/simplifiedUI/system/controllers/controllerModules/equipEntity.js
  scripts/simplifiedUI/system/controllers/controllerModules/farActionGrabEntity.js
  scripts/simplifiedUI/system/controllers/controllerModules/farGrabEntity.js
  scripts/simplifiedUI/system/controllers/controllerModules/farTrigger.js
  scripts/simplifiedUI/system/controllers/controllerModules/hudOverlayPointer.js
  scripts/simplifiedUI/system/controllers/controllerModules/inEditMode.js
  scripts/simplifiedUI/system/controllers/controllerModules/inVREditMode.js
  scripts/simplifiedUI/system/controllers/controllerModules/mouseHMD.js
  scripts/simplifiedUI/system/controllers/controllerModules/nearGrabEntity.js
  scripts/simplifiedUI/system/controllers/controllerModules/nearGrabHyperLinkEntity.js
  scripts/simplifiedUI/system/controllers/controllerModules/nearParentGrabOverlay.js
  scripts/simplifiedUI/system/controllers/controllerModules/nearTabletHighlight.js
  scripts/simplifiedUI/system/controllers/controllerModules/nearTrigger.js
  scripts/simplifiedUI/system/controllers/controllerModules/pushToTalk.js
  scripts/simplifiedUI/system/controllers/controllerModules/scaleAvatar.js
  scripts/simplifiedUI/system/controllers/controllerModules/scaleEntity.js
  scripts/simplifiedUI/system/controllers/controllerModules/stylusInput.js
  scripts/simplifiedUI/system/controllers/controllerModules/teleport.js
  scripts/simplifiedUI/system/controllers/controllerModules/webSurfaceLaserInput.js
  scripts/simplifiedUI/system/controllers/controllerScripts.js
  scripts/simplifiedUI/system/controllers/godView.js
  scripts/simplifiedUI/system/controllers/grab.js
  scripts/simplifiedUI/system/controllers/handTouch.js
  scripts/simplifiedUI/system/controllers/squeezeHands.js
  scripts/simplifiedUI/system/controllers/toggleAdvancedMovementForHandControllers.js
  scripts/simplifiedUI/system/controllers/touchControllerConfiguration.js
  scripts/simplifiedUI/system/controllers/viveControllerConfiguration.js
  scripts/simplifiedUI/system/progress.js
  scripts/simplifiedUI/system/request-service.js
  scripts/simplifiedUI/ui/images/inputDeviceMuted.svg
  scripts/simplifiedUI/ui/images/outputDeviceMuted.svg
  scripts/simplifiedUI/ui/simplifiedNametag/resources/modules/defaultLocalEntityProps.js
  scripts/simplifiedUI/ui/simplifiedNametag/resources/modules/entityMaker.js
  scripts/simplifiedUI/ui/simplifiedNametag/resources/modules/nameTagListManager.js
  scripts/simplifiedUI/ui/simplifiedNametag/resources/modules/objectAssign.js
  scripts/simplifiedUI/ui/simplifiedNametag/resources/modules/pickRayController.js
  scripts/simplifiedUI/ui/simplifiedNametag/resources/modules/textHelper.js
  scripts/simplifiedUI/ui/simplifiedNametag/simplifiedNametag.js
  scripts/simplifiedUI/ui/simplifiedStatusIndicator/simplifiedStatusIndicator.js
  scripts/simplifiedUI/ui/simplifiedUI.js
Labels: Client, Development Approved, Project Approved, UI/UX

#15629 Fix BUGZ-344: Avatar Menu says "You have not created any avatars" but I have
  interface/resources/qml/hifi/simplifiedUI/avatarApp/AvatarApp.qml
Labels: Development Approved, Project Approved, QA Ready (internal), UI/UX, bug

#15630 Fix BUGZ-312; BUGZ-311
  interface/resources/qml/hifi/simplifiedUI/settingsApp/audio/Audio.qml
  interface/resources/qml/hifi/simplifiedUI/settingsApp/vr/VR.qml
Labels: Development Approved, Project Approved, QA Ready (internal), UI/UX, bug

#15632 Name tag display name fix
  scripts/simplifiedUI/ui/simplifiedNametag/resources/modules/nameTagListManager.js
Labels: Development Ready, Project Approved

#15633 BUGZ 220: Docked Widget Whitelisting
  interface/src/ui/InteractiveWindow.cpp
  libraries/ui/src/ui/OffscreenQmlSurface.cpp
  libraries/ui/src/ui/OffscreenQmlSurface.h
Labels: Development Approved, Engine, Project Approved

#15636 BUGZ-354: Update Android and Windows build documentation to reflect latest changes
  BUILD_ANDROID.md
  BUILD_QUEST.md
  BUILD_WIN.md
Labels: Development Approved, Documentation, Project Approved

#15637 BUGZ-158: Crash when switching audio devices on Mac
  libraries/audio-client/src/AudioClient.cpp
  libraries/audio-client/src/AudioClient.h
Labels: Beware: Threading/Deadlock, Client, Critical Fix, Development Approved, Mac Required, Project Approved, bug

#15634 BUGZ-380: Revert skybox color behavior
  libraries/graphics/src/graphics/skybox.slf
Labels: Development Ready, Engine, Project Approved

#15635 BUGZ-164: fix crash when processing physics simulation ownership bids
  interface/src/Application.cpp
  libraries/physics/src/PhysicalEntitySimulation.cpp
  libraries/physics/src/PhysicalEntitySimulation.h
Labels: Development Approved, Engine, Project Approved

#15641 Fix BUGZ-146: Clicking on the gear icon causes three click sounds
  interface/resources/qml/hifi/simplifiedUI/simplifiedControls/Switch.qml
Labels: Development Approved, Project Approved, UI/UX, bug

#15631 BUGZ-413: Re-enable Quest 3D Keyboard
  interface/src/ui/Keyboard.h
Labels: Development Approved, Engine, Project Approved, Quest Required

#15640 DEV-50: Post-build script tweaks
  tools/ci-scripts/postbuild.py
Labels: Development Approved, Project Approved

#15644 DEV-50: Fix release build zip name
  tools/ci-scripts/postbuild.py
Labels: Development Approved, Development Ready, Project Approved

#15642 BUGZ-403: Add ignorePickIntersection to Create
  scripts/system/assets/data/createAppTooltips.json
  scripts/system/html/js/entityProperties.js
Labels: Client, Create, Development Approved, Project Approved

#15645 Fix minor memory leak using unique_ptr
  interface/src/commerce/Wallet.cpp
Labels: Commerce, Development Approved, Metaverse, Project Approved

#15626 BUGZ-322 add domain checkin time-spent logging
  domain-server/src/DomainGatekeeper.cpp
  domain-server/src/DomainGatekeeper.h
  domain-server/src/DomainServer.cpp
  domain-server/src/DomainServer.h
  domain-server/src/DomainServerNodeData.h
  domain-server/src/NodeConnectionData.cpp
  domain-server/src/NodeConnectionData.h
  libraries/networking/src/NodeList.cpp
  libraries/networking/src/ReceivedMessage.cpp
  libraries/networking/src/ReceivedMessage.h
  libraries/networking/src/udt/Packet.cpp
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
  libraries/networking/src/udt/PacketList.cpp
  libraries/networking/src/udt/PacketList.h
  libraries/networking/src/udt/Socket.cpp
Labels: Development Approved, Metaverse, Project Approved, bug

#15648 BUGZ-335: Clear traits ack data on node disconnect
  assignment-client/src/avatars/AvatarMixerClientData.cpp
Labels: Development Approved, Project Approved

#15646 DEV-62: Add getHomeLocationAddress to bookmark API
  interface/src/LocationBookmarks.cpp
  interface/src/LocationBookmarks.h
Labels: Client, Development Approved, Project Approved

#15651 BUGZ-414: crash fix and don't add local entities to physics simulation
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/physics/src/PhysicalEntitySimulation.cpp
Labels: Development Approved, Engine, Project Approved
