Repository highfidelity/hifi, pull requests merged in 2019-12, with the labels that each got.

#16540 DEV-2700: Add screenshare property to zones and evaluate in avatar mixer
  assignment-client/src/avatars/AvatarMixerClientData.cpp
  assignment-client/src/avatars/MixerAvatar.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityPropertyFlags.h
  libraries/entities/src/ZoneEntityItem.cpp
  libraries/entities/src/ZoneEntityItem.h
  libraries/networking/src/udt/PacketHeaders.h
  scripts/system/create/assets/data/createAppTooltips.json
  scripts/system/create/edit.js
  scripts/system/create/entityProperties/html/js/entityProperties.js
Labels: Development Approved, Metaverse, Packet Version Change, Project Approved, Scripting API change

#16539 DOC-227: Stats JSDoc
  interface/src/RefreshRateManager.cpp
  interface/src/ui/Stats.h
Labels: JSDocs

#16553 Dev-2812: Broadcasting from MacOs won't work
  interface/CMakeLists.txt
  interface/src/scripting/ScreenshareScriptingInterface.h
  screenshare/CMakeLists.txt
Labels: Development Approved, Project Approved, UI/UX

#16552 Github Actions master builds
  .github/workflows/cmake.yml
  .github/workflows/dump.yml
  .github/workflows/master_build.yml
  .github/workflows/pr_build.yml
  CMakeLists.txt
  android/containerized_build.sh
  cmake/macros/SetPackagingParameters.cmake
  hifi_vcpkg.py
  tools/ci-scripts/codesign.pfx.gpg
  tools/ci-scripts/postbuild.py
  tools/ci-scripts/pr_comment.py
  tools/ci-scripts/upload.py
  tools/gpu-frame-player/CMakeLists.txt
Labels: Development Approved, Project Approved

#16554 Attempt to fix DEV-2859 with tighter constraints on screenshare resolution and framerate
  screenshare/src/screenshareApp.js
Labels: Development Approved, Project Approved, UI/UX, bug

#16555 DEV-2858: White screen displayed when using screenshare
  domain-server/src/DomainServer.cpp
  domain-server/src/DomainServer.h
  interface/src/scripting/ScreenshareScriptingInterface.cpp
  interface/src/scripting/ScreenshareScriptingInterface.h
  libraries/networking/src/AccountManager.cpp
  libraries/networking/src/AccountManager.h
Labels: Development Approved, Project Approved, QA Ready, UI/UX, bug

#16558 DOC-236: Account and GlobalServices JSDoc
  interface/src/scripting/AccountServicesScriptingInterface.h
Labels: Development Approved, JSDocs, Project Approved

#16560 DOC-237: DialogsManager JSDoc
  interface/src/scripting/DialogsManagerScriptingInterface.h
Labels: Development Approved, JSDocs, Project Approved

#16561 DOC-238: AddressManager JSDoc
  libraries/networking/src/AddressManager.h
Labels: JSDocs

#16556 DOC-235: DriveKeys JSDoc
  interface/src/avatar/MyAvatar.h
  libraries/pointers/src/Pick.h
Labels: Development Approved, JSDocs, Project Approved

#16563 DOC-198: OffscreenFlags JSDoc
  libraries/ui/src/OffscreenUi.cpp
Labels: Development Approved, JSDocs, Project Approved

#16559 Dump installer logs on failure
  .github/workflows/master_build.yml
  .github/workflows/pr_build.yml
Labels: Development Ready, Project Approved

#16566 allow Linux interface to connect to domain when DISABLE_QML is true
  interface/src/Application.cpp
Labels: Development Ready

#16565 DEV-2572: Linux GHA PR builds
  .github/workflows/pr_build.yml
  assignment-client/CMakeLists.txt
  cmake/macros/TargetPolyvox.cmake
  cmake/macros/TargetQuazip.cmake
  tools/ci-scripts/linux-gha/Dockerfile
  tools/ci-scripts/linux-gha/Dockerfile_linuxbase
  tools/ci-scripts/linux-gha/hifi.conf
Labels: Development Ready, Project Approved

#16567 DOC-240: console JSDoc
  libraries/script-engine/src/ConsoleScriptingInterface.h
  libraries/script-engine/src/ScriptEngine.cpp
  libraries/script-engine/src/ScriptEngine.h
Labels: JSDocs

#16564 DOC-239: Rates JSDoc
  interface/src/scripting/DesktopScriptingInterface.h
  interface/src/scripting/RatesScriptingInterface.h
  tools/jsdoc/plugins/hifi.js
Labels: Development Ready, JSDocs

#16573 DOC-244: OverlayWindow and OverlayWebWindow JSDoc
  interface/src/ui/InteractiveWindow.h
  libraries/ui/src/QmlWebWindowClass.h
  libraries/ui/src/QmlWindowClass.cpp
  libraries/ui/src/QmlWindowClass.h
Labels: Development Approved, JSDocs, Project Approved

#16571 DOC-243: EntityScriptServerLog JSDoc
  libraries/entities/src/EntityScriptServerLogClient.h
Labels: Development Approved, JSDocs, Project Approved

#16570 DOC-241: ContextOverlay JSDoc
  interface/src/scripting/WalletScriptingInterface.h
  interface/src/ui/overlays/ContextOverlayInterface.h
Labels: Development Approved, JSDocs, Project Approved

#16551 DEV-1943: Make MyAvatar.getAvatarEntityData() return all properties
  assignment-client/src/avatars/ScriptableAvatar.cpp
  assignment-client/src/avatars/ScriptableAvatar.h
  interface/src/AvatarBookmarks.cpp
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
  libraries/avatars/src/ScriptAvatarData.cpp
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/shared/src/VariantMapToScriptValue.cpp
  scripts/system/libraries/WebTablet.js
Labels: Client, Development Approved, Project Approved, Scripting API change

#16499 Procedural vertex shaders
  interface/src/Application.cpp
  libraries/entities-renderer/src/RenderableMaterialEntityItem.cpp
  libraries/entities-renderer/src/RenderableMaterialEntityItem.h
  libraries/entities-renderer/src/RenderableShapeEntityItem.cpp
  libraries/entities-renderer/src/RenderableShapeEntityItem.h
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/EntityTree.h
  libraries/entities/src/MaterialEntityItem.cpp
  libraries/entities/src/MaterialEntityItem.h
  libraries/procedural/src/procedural/Procedural.cpp
  libraries/procedural/src/procedural/Procedural.h
  libraries/procedural/src/procedural/ProceduralCommon.slh
  libraries/render-utils/src/MeshPartPayload.cpp
  libraries/render-utils/src/simple_procedural.slv
Labels: Development Approved, Engine, Feedback Welcome, JSDocs, Open Source, Project Approved, Scripting API change

#16546 Material Entities can specify face culling method, support GLTF doubleSided property
  interface/src/graphics/WorldBox.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/entities-renderer/src/RenderableGizmoEntityItem.cpp
  libraries/entities-renderer/src/RenderableLineEntityItem.cpp
  libraries/entities-renderer/src/RenderableShapeEntityItem.cpp
  libraries/fbx/src/GLTFSerializer.cpp
  libraries/fbx/src/GLTFSerializer.h
  libraries/graphics-scripting/src/graphics-scripting/Forward.h
  libraries/graphics-scripting/src/graphics-scripting/GraphicsScriptingInterface.cpp
  libraries/graphics-scripting/src/graphics-scripting/ScriptableModel.cpp
  libraries/graphics/src/graphics/Material.cpp
  libraries/graphics/src/graphics/Material.h
  libraries/graphics/src/graphics/MaterialTextures.slh
  libraries/hfm/src/hfm/HFM.h
  libraries/procedural/src/procedural/ProceduralMaterialCache.cpp
  libraries/render-utils/src/GeometryCache.cpp
  libraries/render-utils/src/GeometryCache.h
  libraries/render-utils/src/MeshPartPayload.cpp
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/RenderPipelines.cpp
  libraries/render-utils/src/model.slf
  libraries/render/src/render/ShapePipeline.h
Labels: Development Approved, Open Source, Project Approved, Scripting API change

#16548 Case 17368: Fix wearables not disappearing with avatar
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
  libraries/entities-renderer/src/RenderableEntityItem.cpp
  libraries/entities-renderer/src/RenderableEntityItem.h
  libraries/entities-renderer/src/RenderableMaterialEntityItem.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.h
  libraries/entities-renderer/src/RenderableParticleEffectEntityItem.cpp
  libraries/entities-renderer/src/RenderablePolyLineEntityItem.cpp
  libraries/entities-renderer/src/RenderablePolyVoxEntityItem.cpp
  libraries/entities-renderer/src/RenderablePolyVoxEntityItem.h
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/render-utils/src/MeshPartPayload.cpp
  libraries/render-utils/src/MeshPartPayload.h
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
  libraries/render-utils/src/RenderShadowTask.cpp
  libraries/render/src/render/CullTask.cpp
  libraries/render/src/render/CullTask.h
  libraries/render/src/render/Item.h
  libraries/render/src/render/RenderFetchCullSortTask.cpp
Labels: Development Approved, Engine, Open Source, Project Approved

#16557 DEV-2810: Rename Stats.audioAudioInboundPPS to Stats.audioInboundPPS
  interface/resources/qml/+android_interface/Stats.qml
  interface/resources/qml/Stats.qml
  interface/src/ui/Stats.cpp
  interface/src/ui/Stats.h
Labels: Client, Development Approved, Project Approved, Scripting API change

#16562 DEV-2442: Fix main gamepad (XBox controller) controls
  interface/resources/controllers/xbox.json
  interface/src/Application.cpp
  interface/src/Menu.h
  libraries/controllers/src/controllers/Actions.cpp
  scripts/system/controllers/controllerModules/teleport.js
Labels: Client, Development Approved, Project Approved, Scripting API change

#16574 DOC-242: WebSocket and WebSocketServer JSDoc
  libraries/script-engine/src/WebSocketClass.cpp
  libraries/script-engine/src/WebSocketClass.h
  libraries/script-engine/src/WebSocketServerClass.h
Labels: Development Approved, JSDocs, Project Approved

#16576 DOC-157: LODManager and Performance JSDoc
  interface/src/LODManager.h
  interface/src/RefreshRateManager.cpp
  interface/src/RefreshRateManager.h
  interface/src/scripting/PerformanceScriptingInterface.h
  interface/src/ui/Stats.h
Labels: Development Ready, JSDocs

#16577 DOC-55: XMLHttpRequest JSDoc
  libraries/script-engine/src/WebSocketClass.cpp
  libraries/script-engine/src/WebSocketClass.h
  libraries/script-engine/src/XMLHttpRequestClass.cpp
  libraries/script-engine/src/XMLHttpRequestClass.h
Labels: Development Ready, JSDocs

#16509 Added environment variables to change domain server ports
  libraries/networking/src/DomainHandler.h
Labels: Metaverse, Open Source, Project Approved
