Repository highfidelity/hifi, pull requests merged in 2019-01, with the labels that each got.

#14634 Case 20200: Update EntityScriptingInterface to not find local entities (#2)
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/avatar/MyAvatar.cpp
  interface/src/raypick/LaserPointer.cpp
  interface/src/raypick/LaserPointerScriptingInterface.h
  interface/src/raypick/ParabolaPick.cpp
  interface/src/raypick/PathPointer.cpp
  interface/src/raypick/PickScriptingInterface.cpp
  interface/src/raypick/PickScriptingInterface.h
  interface/src/raypick/PointerScriptingInterface.h
  interface/src/raypick/RayPick.cpp
  interface/src/raypick/RayPickScriptingInterface.h
  interface/src/raypick/StylusPointer.cpp
  interface/src/ui/Keyboard.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities/src/EntityScriptingInterface.cpp
  libraries/entities/src/EntityScriptingInterface.h
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/EntityTree.h
  libraries/entities/src/EntityTreeElement.cpp
  libraries/entities/src/EntityTreeElement.h
  libraries/pointers/src/Pick.cpp
  libraries/pointers/src/Pick.h
  libraries/pointers/src/PickCacheOptimizer.h
  libraries/shared/src/PickFilter.h
  scripts/developer/utilities/tests/entityPerfTest.js
  unpublishedScripts/DomainContent/Toybox/pistol/pistol.js
Labels: Client, Development Approved, Engine, JSDocs, Project Approved, QA Approved :tada:

#14620 VIVE can now auto-detect hmd and desktop modes
  plugins/openvr/src/OpenVrDisplayPlugin.cpp
  plugins/openvr/src/OpenVrDisplayPlugin.h
  plugins/openvr/src/OpenVrHelpers.cpp
  plugins/openvr/src/OpenVrHelpers.h
Labels: Avatar, Development Approved, HMD required, Project Approved, QA Approved :tada:, Vive Required, bug

#14610 Case 20106-AC agents spawned with -n don't come back
  assignment-client/src/AssignmentClientMonitor.cpp
Labels: Development Approved, Project Approved, QA Approved :tada:, Server & Network

#14648 Fix for Oculus reset view issue
  interface/src/Application.cpp
  interface/src/Application.h
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14638 Fix texture MB column not sorting correctly in entity list
  scripts/system/html/js/entityList.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#14624 ACs don't need to call into flagtimeForConnecitonStep
  interface/src/Application.cpp
  libraries/networking/src/LimitedNodeList.cpp
  libraries/networking/src/LimitedNodeList.h
Labels: Development Approved, Project Approved, QA Approved :tada:, Server & Network, bug

#14569 Case 20281: Add missing Text Entity properties
  interface/src/ui/overlays/Text3DOverlay.cpp
  libraries/entities-renderer/src/RenderableShapeEntityItem.cpp
  libraries/entities-renderer/src/RenderableShapeEntityItem.h
  libraries/entities-renderer/src/RenderableTextEntityItem.cpp
  libraries/entities-renderer/src/RenderableTextEntityItem.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityPropertyFlags.h
  libraries/entities/src/TextEntityItem.cpp
  libraries/entities/src/TextEntityItem.h
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
  libraries/render-utils/src/TextRenderer3D.cpp
  libraries/render-utils/src/TextRenderer3D.h
  libraries/render-utils/src/text/Font.cpp
  libraries/render-utils/src/text/Font.h
Labels: Development Approved, Development Ready, Engine, Packet Version Change, Project Approved, QA Approved :tada:

#14472 use Traits system for grabbing
  assignment-client/src/avatars/AvatarMixerClientData.cpp
  interface/src/Application.cpp
  interface/src/avatar/AvatarActionHold.cpp
  interface/src/avatar/AvatarActionHold.h
  interface/src/avatar/AvatarManager.cpp
  interface/src/avatar/AvatarManager.h
  interface/src/avatar/GrabManager.cpp
  interface/src/avatar/GrabManager.h
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
  libraries/avatars/src/AvatarTraits.h
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.h
  libraries/entities/src/EntityDynamicInterface.h
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityPropertyFlags.cpp
  libraries/entities/src/EntityPropertyFlags.h
  libraries/entities/src/EntityScriptingInterface.cpp
  libraries/entities/src/EntityScriptingInterface.h
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/EntityTree.h
  libraries/entities/src/GrabPropertyGroup.cpp
  libraries/entities/src/GrabPropertyGroup.h
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
  libraries/physics/src/ObjectActionTractor.cpp
  libraries/physics/src/ObjectDynamic.h
  libraries/shared/src/Grab.cpp
  libraries/shared/src/Grab.h
  libraries/shared/src/SpatiallyNestable.cpp
  libraries/shared/src/SpatiallyNestable.h
  scripts/developer/debugging/queryAACubeInspector.js
  scripts/system/controllers/controllerModules/farGrabEntity.js
  scripts/system/controllers/controllerModules/nearActionGrabEntity.js
  scripts/system/controllers/controllerModules/nearGrabEntity.js
  scripts/system/controllers/controllerModules/scaleEntity.js
  scripts/system/controllers/controllerScripts.js
  scripts/system/libraries/controllerDispatcherUtils.js
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14551 Fix non self-sufficient headers.
  libraries/octree/src/OctreeEntitiesFileParser.cpp
  libraries/shared/src/GLMHelpers.cpp
  libraries/shared/src/ResourceRequestObserver.cpp
  libraries/shared/src/ResourceRequestObserver.h
Labels: Development Approved, Project Approved, QA Approved :tada:

#14585 Case 20321: More Entity Property Cleanup
  libraries/entities-renderer/src/RenderableLineEntityItem.cpp
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityItemPropertiesDefaults.h
  libraries/entities/src/EntityItemPropertiesMacros.h
  libraries/entities/src/EntityPropertyFlags.cpp
  libraries/entities/src/EntityPropertyFlags.h
  libraries/entities/src/ImageEntityItem.cpp
  libraries/entities/src/LightEntityItem.cpp
  libraries/entities/src/LineEntityItem.cpp
  libraries/entities/src/LineEntityItem.h
  libraries/entities/src/ModelEntityItem.cpp
  libraries/entities/src/ParticleEffectEntityItem.cpp
  libraries/entities/src/PolyLineEntityItem.cpp
  libraries/entities/src/PolyLineEntityItem.h
  libraries/entities/src/ShapeEntityItem.cpp
  libraries/entities/src/ZoneEntityItem.cpp
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
  libraries/render-utils/src/glowLine.slv
  libraries/shared/src/AABox.cpp
  scripts/developer/tests/avatarToWorldTests.js
  scripts/developer/tests/worldToAvatarTests.js
Labels: Development Approved, Engine, Packet Version Change, Project Approved, QA Approved :tada:

#14646 Make the Out of Range Strategy drop down wider
  interface/resources/qml/hifi/tablet/OpenVrConfiguration.qml
Labels: Avatar, Development Approved, Project Approved, QA Approved :tada:

#14591 Fix network stats to use low-level values
  assignment-client/src/assets/AssetServer.cpp
  assignment-client/src/audio/AudioMixer.cpp
  assignment-client/src/avatars/AvatarMixer.cpp
  assignment-client/src/messages/MessagesMixer.cpp
  interface/resources/qml/+android/Stats.qml
  interface/resources/qml/Stats.qml
  interface/src/Application.cpp
  interface/src/ui/Stats.cpp
  libraries/networking/src/BandwidthRecorder.cpp
  libraries/networking/src/BandwidthRecorder.h
  libraries/networking/src/LimitedNodeList.cpp
  libraries/networking/src/LimitedNodeList.h
  libraries/networking/src/NetworkPeer.cpp
  libraries/networking/src/NetworkPeer.h
  libraries/networking/src/Node.cpp
  libraries/networking/src/Node.h
  libraries/networking/src/PacketReceiver.cpp
  libraries/networking/src/udt/Connection.cpp
  libraries/networking/src/udt/Connection.h
  libraries/networking/src/udt/ConnectionStats.cpp
  libraries/networking/src/udt/ConnectionStats.h
  libraries/networking/src/udt/SendQueue.cpp
  libraries/networking/src/udt/SendQueue.h
  libraries/networking/src/udt/Socket.cpp
  tools/udt-test/src/UDTTest.cpp
Labels: Development Approved, Project Approved, QA Approved :tada:, Server & Network

#14647 Update eye look at interest calculation
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
Labels: Avatar, Development Approved, Project Approved, QA Approved :tada:

#14592 Fix MyAvatar::collisionWithEntity not firing
  interface/src/avatar/AvatarManager.cpp
Labels: Create, Development Approved, Engine, Project Approved, QA Approved :tada:

#14622 Correctly set avatar-scale timestamp when changing in Avatar class
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
Labels: Avatar, Development Approved, Project Approved, QA Approved :tada:, Server & Network

#14655 omit unknown device names from clear-story data
  libraries/networking/src/UserActivityLogger.cpp
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14637 data url for web entity
  libraries/entities-renderer/src/RenderableWebEntityItem.cpp
  libraries/networking/src/NetworkingConstants.h
Labels: Development Approved, Project Approved, QA Approved :tada:

#14653 Avatar Exporter - reference thumb rotations
  .gitignore
  tools/unity-avatar-exporter/Assets/Editor.meta
  tools/unity-avatar-exporter/Assets/Editor/AvatarExporter.cs
  tools/unity-avatar-exporter/Assets/Editor/AvatarExporter.cs.meta
  tools/unity-avatar-exporter/Assets/README.txt
  tools/unity-avatar-exporter/Assets/README.txt.meta
  tools/unity-avatar-exporter/avatarExporter.unitypackage
  tools/unity-avatar-exporter/packager.bat
Labels: Avatar, Create, Development Approved, QA Approved :tada:, Windows Required

#14650 Case 20301 - add platform info
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/scripting/PlatformInfoScriptingInterface.cpp
  interface/src/scripting/PlatformInfoScriptingInterface.h
  tools/nitpick/src/TestRunner.cpp
  tools/nitpick/src/ui/HelpWindow.cpp
  tools/nitpick/src/ui/HelpWindow.h
  tools/nitpick/src/ui/HelpWindow.ui
  tools/nitpick/src/ui/Nitpick.cpp
  tools/nitpick/src/ui/Nitpick.h
  tools/nitpick/src/ui/Nitpick.ui
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:, nitpick

#14632 MS19925: Avatar Packager
  interface/resources/icons/checkmark-stroke.svg
  interface/resources/icons/loader-snake-256-wf.gif
  interface/resources/icons/loader-snake-256.gif
  interface/resources/images/loader-snake-128.png
  interface/resources/qml/controlsUit/Button.qml
  interface/resources/qml/hifi/AvatarPackagerWindow.qml
  interface/resources/qml/hifi/avatarPackager/AvatarPackagerApp.qml
  interface/resources/qml/hifi/avatarPackager/AvatarPackagerFooter.qml
  interface/resources/qml/hifi/avatarPackager/AvatarPackagerHeader.qml
  interface/resources/qml/hifi/avatarPackager/AvatarPackagerState.qml
  interface/resources/qml/hifi/avatarPackager/AvatarProject.qml
  interface/resources/qml/hifi/avatarPackager/AvatarProjectCard.qml
  interface/resources/qml/hifi/avatarPackager/AvatarProjectUpload.qml
  interface/resources/qml/hifi/avatarPackager/AvatarUploadStatusItem.qml
  interface/resources/qml/hifi/avatarPackager/ClickableArea.qml
  interface/resources/qml/hifi/avatarPackager/CreateAvatarProject.qml
  interface/resources/qml/hifi/avatarPackager/InfoBox.qml
  interface/resources/qml/hifi/avatarPackager/LoadingCircle.qml
  interface/resources/qml/hifi/avatarPackager/ProjectInputControl.qml
  interface/resources/qml/hifi/avatarPackager/RalewayButton.qml
  interface/resources/qml/hifi/avatarPackager/Style.qml
  interface/resources/qml/hifi/avatarPackager/qmldir
  interface/resources/qml/hifi/avatarapp/MessageBox.qml
  interface/resources/qml/hifi/tablet/AvatarPackager.qml
  interface/src/Application.cpp
  interface/src/Menu.cpp
  interface/src/Menu.h
  interface/src/avatar/AvatarPackager.cpp
  interface/src/avatar/AvatarPackager.h
  interface/src/avatar/AvatarProject.cpp
  interface/src/avatar/AvatarProject.h
  interface/src/avatar/MarketplaceItemUploader.cpp
  interface/src/avatar/MarketplaceItemUploader.h
  libraries/avatars/src/ProjectFile.h
  libraries/fbx/src/FST.cpp
  libraries/fbx/src/FST.h
  libraries/fbx/src/FSTReader.cpp
  libraries/fbx/src/FSTReader.h
  libraries/networking/src/AccountManager.cpp
  libraries/networking/src/AccountManager.h
Labels: Create, Development Approved, Feedback Welcome, QA Approved :tada:

#14659 Add menu checkbox to toggle collisions with other avatars
  interface/resources/qml/hifi/AvatarApp.qml
  interface/resources/qml/hifi/avatarapp/Settings.qml
  interface/src/avatar/AvatarManager.cpp
  interface/src/avatar/AvatarMotionState.cpp
  interface/src/avatar/AvatarMotionState.h
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  interface/src/avatar/OtherAvatar.cpp
  interface/src/avatar/OtherAvatar.h
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
  scripts/system/avatarapp.js
Labels: Avatar, Development Approved, Packet Version Change, Project Approved, QA Approved :tada:, Scripting API change

#14658 Only keep aggregated thread stats for Avatar Mixer
  assignment-client/src/avatars/AvatarMixer.cpp
  libraries/networking/src/LimitedNodeList.cpp
  libraries/networking/src/LimitedNodeList.h
  libraries/networking/src/PacketReceiver.cpp
  libraries/networking/src/PacketReceiver.h
  libraries/networking/src/ThreadedAssignment.cpp
Labels: Development Approved, Project Approved, QA Approved :tada:, Server & Network

#14661 allow mouse pointer to pick against collidable entities
  interface/src/Application.cpp
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14660 MS20170: Update Image/Text Entity properties in Create with new properties
  scripts/system/assets/data/createAppTooltips.json
  scripts/system/html/css/edit-style.css
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Ready, Project Approved, QA Approved :tada:

#14586 Case 20322, Case 12279, Case 15803: Improve PolyLines to support glow and faceCamera
  libraries/entities-renderer/src/RenderablePolyLineEntityItem.cpp
  libraries/entities-renderer/src/RenderablePolyLineEntityItem.h
  libraries/entities-renderer/src/paintStroke.slf
  libraries/entities-renderer/src/paintStroke.slh
  libraries/entities-renderer/src/paintStroke.slv
  libraries/entities-renderer/src/paintStroke_Shared.slh
  libraries/entities-renderer/src/paintStroke_fade.slf
  libraries/entities-renderer/src/paintStroke_fade.slv
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityPropertyFlags.h
  libraries/entities/src/PolyLineEntityItem.cpp
  libraries/entities/src/PolyLineEntityItem.h
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
Labels: Development Approved, Engine, Packet Version Change, Project Approved, QA Approved :tada:

#14663 MS20142 - CreateApp - Fix active colorPicker to update on selection update
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#14657 Case 20504: Trying to fix avatar entity issue
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/entities/src/AnimationPropertyGroup.cpp
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityItemPropertiesMacros.h
  libraries/entities/src/EntityPropertyFlags.h
  libraries/entities/src/EntityPsuedoPropertyFlags.h
  libraries/entities/src/EntityScriptingInterface.cpp
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/GrabPropertyGroup.cpp
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
Labels: Critical Fix, Development Approved, Engine, Packet Version Change, Project Approved, QA Approved :tada:, bug

#14665 Case 20533: Fix export entities
  interface/src/scripting/ClipboardScriptingInterface.cpp
  interface/src/scripting/ClipboardScriptingInterface.h
Labels: Critical Fix, Development Approved, Engine, Project Approved, QA Approved :tada:, bug

#14668 Fix crash
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
Labels: Development Approved, Engine, Packet Version Change, Project Approved, QA Approved :tada:

#14439 Case 15518: shaped zones
  assignment-client/CMakeLists.txt
  assignment-client/src/entities/EntityServer.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.h
  libraries/entities-renderer/src/RenderableZoneEntityItem.cpp
  libraries/entities/CMakeLists.txt
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/ZoneEntityItem.cpp
  libraries/entities/src/ZoneEntityItem.h
  libraries/hfm/src/hfm/HFM.cpp
  libraries/hfm/src/hfm/HFM.h
  libraries/physics/CMakeLists.txt
  libraries/physics/src/EntityMotionState.cpp
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
  libraries/shared/src/ShapeInfo.cpp
  libraries/shared/src/ShapeInfo.h
  scripts/system/edit.js
  scripts/system/html/js/entityProperties.js
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14642 Entity property range/step audit
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityItemPropertiesDefaults.h
  libraries/entities/src/EntityItemPropertiesMacros.h
  libraries/entities/src/EntityScriptingInterface.cpp
  libraries/entities/src/EntityScriptingInterface.h
  libraries/entities/src/LightEntityItem.cpp
  libraries/entities/src/LightEntityItem.h
  libraries/script-engine/src/ScriptEngine.cpp
  scripts/system/edit.js
  scripts/system/html/js/draggableNumber.js
  scripts/system/html/js/entityProperties.js
  scripts/system/libraries/entitySelectionTool.js
Labels: Create, Development Ready, Project Approved, QA Approved :tada:

#14662 Add grid entities to create
  interface/resources/fonts/hifi-glyphs.ttf
  scripts/system/assets/data/createAppTooltips.json
  scripts/system/html/entityList.html
  scripts/system/html/entityProperties.html
  scripts/system/html/js/entityList.js
  scripts/system/html/js/entityProperties.js
  scripts/system/html/js/includes.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#14670 MS20150: add missing Text properties to Create App
  scripts/system/assets/data/createAppTooltips.json
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#14671 Case 20534: Fix light crash
  libraries/render-utils/src/RenderShadowTask.cpp
  libraries/render-utils/src/RenderShadowTask.h
Labels: Critical Fix, Development Approved, Engine, Project Approved, QA Approved :tada:, bug

#14669 Apply master volume to audio streams when solo is active
  assignment-client/src/audio/AudioMixerSlave.cpp
Labels: Development Approved, Project Approved, QA Approved :tada:, Server & Network, bug

#14627 case 20304: please don't flood the avatar-mixer with unnecessary AvatarEntity udpates
  interface/src/AvatarBookmarks.cpp
  interface/src/ui/overlays/Base3DOverlay.cpp
  interface/src/ui/overlays/Base3DOverlay.h
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/SimulationOwner.h
  libraries/physics/src/EntityMotionState.cpp
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14601 Set minimum timeout for retransmits within reliable network service
  libraries/networking/src/udt/SendQueue.cpp
  libraries/networking/src/udt/SendQueue.h
Labels: Development Approved, Project Approved, QA Approved :tada:, Server & Network

#14633 Trait-level flow control
  assignment-client/src/avatars/AvatarMixer.cpp
  assignment-client/src/avatars/AvatarMixerClientData.cpp
  assignment-client/src/avatars/AvatarMixerClientData.h
  assignment-client/src/avatars/AvatarMixerSlave.cpp
  assignment-client/src/avatars/AvatarMixerSlave.h
  interface/src/Application.cpp
  libraries/avatars/src/AvatarHashMap.cpp
  libraries/avatars/src/AvatarTraits.h
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
Labels: Development Approved, Packet Version Change, Project Approved, QA Approved :tada:, Server & Network

#14672 Track avatar-mixer send-stats with finer granularity
  assignment-client/src/avatars/AvatarMixer.cpp
  assignment-client/src/avatars/AvatarMixerClientData.cpp
  assignment-client/src/avatars/AvatarMixerClientData.h
  assignment-client/src/avatars/AvatarMixerSlave.cpp
  assignment-client/src/avatars/AvatarMixerSlave.h
  libraries/avatars/src/AvatarData.cpp
Labels: Development Approved, Project Approved, QA Approved :tada:, Server & Network

#14621 cap the number of considered message channels in PacketQueue
  libraries/networking/src/udt/PacketQueue.cpp
  libraries/networking/src/udt/PacketQueue.h
Labels: Development Approved, Project Approved, QA Approved :tada:, Server & Network

#14686 faster-avatar-entities for 0.78 (case 20020)
  assignment-client/src/avatars/AvatarMixerClientData.cpp
  assignment-client/src/avatars/ScriptableAvatar.cpp
  assignment-client/src/avatars/ScriptableAvatar.h
  interface/src/Application.cpp
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  interface/src/avatar/OtherAvatar.cpp
  interface/src/avatar/OtherAvatar.h
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
  libraries/entities/src/EntityEditPacketSender.cpp
  libraries/entities/src/EntityEditPacketSender.h
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/EntityTypes.cpp
  libraries/entities/src/EntityTypes.h
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
  libraries/octree/src/OctreePacketData.cpp
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14688 Bulk Avatar Traits related ack data was not reset when avatars were ignored.
  assignment-client/src/avatars/AvatarMixerClientData.cpp
Labels: Development Approved, Infrastructure, QA Approved :tada:, bug

#14682 Bulk Avatar Traits related ack data was not reset in certain cases when it should be
  assignment-client/src/avatars/AvatarMixerClientData.cpp
Labels: Development Approved, Infrastructure, Project Approved, QA Approved :tada:

#14692 RC78: Case 20394: Fix multi-frustum view updating
  interface/src/Application.cpp
Labels: Critical Fix, Development Approved, Engine, Project Approved, QA Approved :tada:

#14690 Plugin versioning
  interface/src/Application.cpp
  interface/src/Application.h
  libraries/plugins/src/plugins/PluginManager.cpp
  libraries/plugins/src/plugins/PluginManager.h
  plugins/hifiCodec/src/plugin.json
  plugins/hifiKinect/src/plugin.json
  plugins/hifiLeapMotion/src/plugin.json
  plugins/hifiNeuron/src/plugin.json
  plugins/hifiSdl2/src/plugin.json
  plugins/hifiSixense/src/plugin.json
  plugins/hifiSpacemouse/src/plugin.json
  plugins/oculus/src/oculus.json
  plugins/oculusLegacy/src/oculus.json
  plugins/openvr/src/plugin.json
  plugins/pcmCodec/src/plugin.json
  plugins/steamClient/src/plugin.json
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14674 Fix ASAN warning due to mixed signed/unsigned arithmetic
  libraries/audio/src/AudioFOA.cpp
  libraries/audio/src/avx2/AudioFOA_avx2.cpp
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14704 RC78 / fix for continuous color picker update loop
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, QA Approved :tada:

#14689 RC78: Case 20580: Trying to fix wearables and avatar app
  interface/resources/qml/hifi/avatarapp/AdjustWearables.qml
  interface/src/AvatarBookmarks.cpp
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  libraries/avatars/src/AvatarData.cpp
  libraries/entities/src/EntityItemProperties.cpp
  scripts/system/avatarapp.js
Labels: Client, Critical Fix, Development Approved, Engine, Project Approved, QA Approved :tada:

#14701 Case20615 - Changing Avatars doesn't update to everyone intermittently
  assignment-client/src/avatars/AvatarMixerClientData.cpp
  assignment-client/src/avatars/AvatarMixerSlave.cpp
Labels: Development Approved, Infrastructure, Project Approved, QA Approved :tada:, bug

#14708 Case20615 - Changing Avatars doesn't update to everyone intermittently
  assignment-client/src/avatars/AvatarMixerClientData.cpp
  assignment-client/src/avatars/AvatarMixerSlave.cpp
Labels: Development Approved, Development Ready, Infrastructure, Project Approved, QA Approved :tada:, bug

#14700 New icons for interface and server-console
  interface/icon/interface-beta.icns
  interface/icon/interface-beta.ico
  interface/icon/interface.icns
  interface/icon/interface.ico
  server-console/resources/console-beta.icns
  server-console/resources/console-beta.ico
  server-console/resources/console-beta.png
  server-console/resources/console.icns
  server-console/resources/console.ico
  server-console/resources/console.png
Labels: Development Approved, Infrastructure, Project Approved, QA Approved :tada:

#14706 (RC78) Change Avatar App design for avatar collisions
  interface/resources/qml/hifi/avatarapp/Settings.qml
Labels: Avatar, Development Approved, Project Approved, QA Approved :tada:

#14654 Fix the distance attenuation of stereo local injectors
  libraries/audio-client/src/AudioClient.cpp
Labels: Client, Development Approved, QA Approved :tada:, bug

#14609 fix a couple shutdown crashes and a class of asan warning
  interface/src/scripting/MenuScriptingInterface.cpp
  libraries/animation/src/AnimClip.cpp
  libraries/animation/src/Rig.cpp
  libraries/fbx/src/FBXSerializer.h
  libraries/hfm/src/hfm/HFMSerializer.h
  libraries/script-engine/src/ScriptEngine.cpp
  libraries/script-engine/src/ScriptEngine.h
Labels: Client, Development Approved, QA Approved :tada:

#14556 Fix Avatar apps warnings.
  interface/resources/qml/hifi/AvatarApp.qml
  interface/resources/qml/hifi/avatarapp/AdjustWearables.qml
  interface/resources/qml/hifi/avatarapp/Settings.qml
  libraries/display-plugins/src/display-plugins/AbstractHMDScriptingInterface.h
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#12899 Log a warning if an entity's property is too large
  libraries/entities/src/EntityEditPacketSender.cpp
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14709 add message fragment handling to wireshark dissectors
  tools/dissectors/1-hfudt.lua
  tools/dissectors/3-hf-avatar.lua
Labels: Development Approved, QA Approved :tada:, Server & Network

#14697 log purge
  libraries/script-engine/src/ScriptCache.cpp
  libraries/script-engine/src/ScriptEngine.cpp
Labels: Development Approved, Infrastructure, Project Approved, QA Approved :tada:

#14699 JSDoc > Grav directory change
  tools/jsdoc/gravPrep.js
Labels: Development Approved, JSDocs, Project Approved, QA Approved :tada:

#14645 Make mouselook directly proportional to right-click mouse
  interface/resources/controllers/keyboardMouse.json
  interface/src/Application.cpp
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  interface/src/raypick/PathPointer.cpp
  interface/src/scripting/ControllerScriptingInterface.h
  libraries/controllers/src/controllers/Actions.cpp
  libraries/controllers/src/controllers/Actions.h
  libraries/controllers/src/controllers/AxisValue.cpp
  libraries/controllers/src/controllers/AxisValue.h
  libraries/controllers/src/controllers/InputDevice.cpp
  libraries/controllers/src/controllers/InputDevice.h
  libraries/controllers/src/controllers/InputRecorder.cpp
  libraries/controllers/src/controllers/InputRecorder.h
  libraries/controllers/src/controllers/ScriptingInterface.cpp
  libraries/controllers/src/controllers/UserInputMapper.cpp
  libraries/controllers/src/controllers/UserInputMapper.h
  libraries/controllers/src/controllers/impl/Endpoint.h
  libraries/controllers/src/controllers/impl/Filter.h
  libraries/controllers/src/controllers/impl/conditionals/EndpointConditional.h
  libraries/controllers/src/controllers/impl/endpoints/ActionEndpoint.cpp
  libraries/controllers/src/controllers/impl/endpoints/ActionEndpoint.h
  libraries/controllers/src/controllers/impl/endpoints/AnyEndpoint.cpp
  libraries/controllers/src/controllers/impl/endpoints/AnyEndpoint.h
  libraries/controllers/src/controllers/impl/endpoints/ArrayEndpoint.h
  libraries/controllers/src/controllers/impl/endpoints/CompositeEndpoint.cpp
  libraries/controllers/src/controllers/impl/endpoints/CompositeEndpoint.h
  libraries/controllers/src/controllers/impl/endpoints/InputEndpoint.cpp
  libraries/controllers/src/controllers/impl/endpoints/InputEndpoint.h
  libraries/controllers/src/controllers/impl/endpoints/JSEndpoint.cpp
  libraries/controllers/src/controllers/impl/endpoints/JSEndpoint.h
  libraries/controllers/src/controllers/impl/endpoints/ScriptEndpoint.cpp
  libraries/controllers/src/controllers/impl/endpoints/ScriptEndpoint.h
  libraries/controllers/src/controllers/impl/endpoints/StandardEndpoint.h
  libraries/controllers/src/controllers/impl/filters/AccelerationLimiterFilter.h
  libraries/controllers/src/controllers/impl/filters/ClampFilter.h
  libraries/controllers/src/controllers/impl/filters/ConstrainToIntegerFilter.h
  libraries/controllers/src/controllers/impl/filters/ConstrainToPositiveIntegerFilter.h
  libraries/controllers/src/controllers/impl/filters/DeadZoneFilter.cpp
  libraries/controllers/src/controllers/impl/filters/DeadZoneFilter.h
  libraries/controllers/src/controllers/impl/filters/ExponentialSmoothingFilter.h
  libraries/controllers/src/controllers/impl/filters/HysteresisFilter.cpp
  libraries/controllers/src/controllers/impl/filters/HysteresisFilter.h
  libraries/controllers/src/controllers/impl/filters/LowVelocityFilter.h
  libraries/controllers/src/controllers/impl/filters/NotFilter.cpp
  libraries/controllers/src/controllers/impl/filters/NotFilter.h
  libraries/controllers/src/controllers/impl/filters/PostTransformFilter.h
  libraries/controllers/src/controllers/impl/filters/PulseFilter.cpp
  libraries/controllers/src/controllers/impl/filters/PulseFilter.h
  libraries/controllers/src/controllers/impl/filters/RotateFilter.h
  libraries/controllers/src/controllers/impl/filters/ScaleFilter.h
  libraries/controllers/src/controllers/impl/filters/TransformFilter.h
  libraries/controllers/src/controllers/impl/filters/TranslateFilter.h
  libraries/input-plugins/src/input-plugins/KeyboardMouseDevice.cpp
  libraries/input-plugins/src/input-plugins/KeyboardMouseDevice.h
  libraries/input-plugins/src/input-plugins/TouchscreenDevice.cpp
  libraries/input-plugins/src/input-plugins/TouchscreenVirtualPadDevice.cpp
  plugins/hifiSdl2/src/Joystick.cpp
  plugins/oculus/src/OculusControllerManager.cpp
  plugins/openvr/src/ViveControllerManager.cpp
Labels: Client, Development Approved, Engine, Project Approved, QA Approved :tada:, Scripting API change

#14720 pepper AssociatedTraitValues with some needed comments
  libraries/avatars/src/AssociatedTraitValues.h
Labels: Development Approved, Project Approved, QA Approved :tada:, Server & Network

#14676 case 20654: Updating user activity logging for login experience
  interface/resources/qml/LoginDialog/CompleteProfileBody.qml
  interface/resources/qml/LoginDialog/LinkAccountBody.qml
  interface/resources/qml/LoginDialog/LoggingInBody.qml
  interface/resources/qml/LoginDialog/SignUpBody.qml
  interface/resources/qml/LoginDialog/UsernameCollisionBody.qml
  interface/src/Application.cpp
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14724 case 15942: fix bug that caused avatar cauterization code to run constantly
  libraries/avatars/src/AvatarData.h
  libraries/shared/src/SpatiallyNestable.cpp
  libraries/shared/src/SpatiallyNestable.h
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14730 cases 20709 and 20715: wear and see mexico hats in 0.78
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
  scripts/system/controllers/controllerModules/farGrabEntity.js
  scripts/system/controllers/controllerModules/nearGrabEntity.js
  scripts/system/libraries/controllerDispatcherUtils.js
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14729 RC78: Case 20411: Fix crash on subsequent entitlements checks
  plugins/oculus/src/OculusHelpers.cpp
Labels: Critical Fix, Development Approved, Engine, Project Approved, QA Approved :tada:

#14723 Make Connection class a Qt-child of Socket class
  libraries/networking/src/udt/Connection.cpp
Labels: Development Approved, Infrastructure, QA Approved :tada:

#14717 Case20277 - Ignoring user causes loading orb to appear at /0,0,0
  interface/src/avatar/AvatarManager.cpp
  interface/src/avatar/AvatarManager.h
  interface/src/avatar/OtherAvatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars/src/AvatarHashMap.cpp
  libraries/avatars/src/AvatarHashMap.h
Labels: Client, Development Approved, Project Approved, QA Approved :tada:, bug

#14705 Change Avatar App design for avatar collisions
  interface/resources/qml/hifi/avatarapp/Settings.qml
Labels: Avatar, Development Approved, Development Ready, Project Approved, QA Approved :tada:

#14710 case 15962: case 20481: Mouse grab with traits
  interface/src/avatar/GrabManager.cpp
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityTree.cpp
  scripts/system/controllers/controllerModules/equipEntity.js
  scripts/system/controllers/controllerModules/farActionGrabEntityDynOnly.js
  scripts/system/controllers/controllerModules/farParentGrabEntity.js
  scripts/system/controllers/controllerModules/nearActionGrabEntity.js
  scripts/system/controllers/controllerModules/nearParentGrabEntity.js
  scripts/system/controllers/controllerScripts.js
  scripts/system/controllers/grab.js
  scripts/system/libraries/controllerDispatcherUtils.js
Labels: Client, Development Approved, QA Approved :tada:

#14736 Case 20724: Fix Snap app settings issue (RC78)
  interface/resources/qml/hifi/tablet/TabletRoot.qml
Labels: Client, Development Approved, Engine, Project Approved, QA Approved :tada:

#14735 Case 20724: Fix Snap app settings issue
  interface/resources/qml/hifi/tablet/TabletRoot.qml
Labels: Client, Development Approved, Engine, Project Approved, QA Ready

#14721 Limit upstream bandwidth to the Avatar Mixer
  assignment-client/src/Agent.cpp
  assignment-client/src/Agent.h
  assignment-client/src/avatars/AvatarMixer.cpp
  assignment-client/src/avatars/AvatarMixer.h
  assignment-client/src/avatars/ScriptableAvatar.cpp
  assignment-client/src/avatars/ScriptableAvatar.h
  interface/src/Application.cpp
  interface/src/avatar/AvatarManager.cpp
  interface/src/avatar/AvatarManager.h
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
  libraries/avatars/src/AvatarHashMap.h
  libraries/avatars/src/ClientTraitsHandler.cpp
  libraries/avatars/src/ClientTraitsHandler.h
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
Labels: Development Approved, Project Approved, QA Approved :tada:, Server & Network

#14741 Case 20731 for 0.78: send updates when grabbing AvatarEntities
  interface/src/avatar/MyAvatar.cpp
  libraries/entities/src/EntityTree.cpp
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14754 Gabriel Calero's fix (78.0)
  android/docker/Dockerfile
Labels: Android, Development Approved, Project Approved, QA Approved :tada:

#14750 Gabriel Calero's fix (79.0/master)
  android/docker/Dockerfile
Labels: Android, Development Approved, Project Approved, QA Approved :tada:

#14743 RC78: Model collision shape property fix
  scripts/system/assets/data/createAppTooltips.json
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:, bug

#14749 Case 20759: Possible fix for procedurals on mac (RC78)
  libraries/render-utils/src/simple.slf
  libraries/render-utils/src/simple_transparent.slf
Labels: Critical Fix, Development Approved, Engine, Project Approved, QA Approved :tada:, bug

#14748 Case 20774: Possible fix for procedurals on mac
  libraries/render-utils/src/simple.slf
  libraries/render-utils/src/simple_transparent.slf
Labels: Development Approved, Engine, QA Approved :tada:, bug

#14740 Case 20731: send updates when grabbing AvatarEntities
  interface/src/avatar/MyAvatar.cpp
  libraries/entities/src/EntityTree.cpp
Labels: Critical Fix, Development Approved, Engine, Project Approved, QA Approved :tada:

#14731 cases 20709 and 20715: wear and see mexico hats
  interface/src/avatar/MyAvatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
  scripts/system/controllers/controllerModules/farGrabEntity.js
  scripts/system/controllers/controllerModules/nearGrabEntity.js
  scripts/system/libraries/controllerDispatcherUtils.js
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14760 Treat QmlCommerce as a singleton class
  interface/src/Application.cpp
  interface/src/commerce/QmlCommerce.cpp
  interface/src/commerce/QmlCommerce.h
Labels: Commerce, Development Approved, Infrastructure, Project Approved, QA Approved :tada:, bug

#14747 Fix security-image display in HMD
  interface/src/Application.cpp
Labels: Commerce, Development Approved, Infrastructure, Project Approved, QA Approved :tada:, tablet-ui

#14733 Avatar Protocol: Fix for precision issues with translation
  libraries/animation/src/Rig.cpp
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
  libraries/shared/src/JointData.h
  tools/dissectors/3-hf-avatar.lua
Labels: Avatar, Development Approved, Packet Version Change, Project Approved, QA Approved :tada:, Server & Network

#14728 Case 20411: Fix crash on subsequent entitlements checks
  plugins/oculus/src/OculusHelpers.cpp
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14619 Case 20240: Better material entity targeting
  libraries/entities/src/EntityItemProperties.cpp
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
Labels: Create, Development Approved, Engine, JSDocs, Project Approved, QA Approved :tada:

#14667 Case 20535: renderLayer, primitiveMode, groupCulled Entity properties
  interface/src/ui/overlays/ModelOverlay.cpp
  interface/src/ui/overlays/ModelOverlay.h
  libraries/entities-renderer/src/RenderableEntityItem.cpp
  libraries/entities-renderer/src/RenderableEntityItem.h
  libraries/entities-renderer/src/RenderableGridEntityItem.cpp
  libraries/entities-renderer/src/RenderableImageEntityItem.cpp
  libraries/entities-renderer/src/RenderableMaterialEntityItem.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.h
  libraries/entities-renderer/src/RenderableParticleEffectEntityItem.cpp
  libraries/entities-renderer/src/RenderablePolyLineEntityItem.cpp
  libraries/entities-renderer/src/RenderablePolyVoxEntityItem.cpp
  libraries/entities-renderer/src/RenderablePolyVoxEntityItem.h
  libraries/entities-renderer/src/RenderableShapeEntityItem.cpp
  libraries/entities-renderer/src/RenderableTextEntityItem.cpp
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityPropertyFlags.h
  libraries/entities/src/ModelEntityItem.cpp
  libraries/entities/src/ModelEntityItem.h
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
  libraries/octree/src/OctreePacketData.h
  libraries/render-utils/src/CauterizedModel.cpp
  libraries/render-utils/src/GeometryCache.cpp
  libraries/render-utils/src/GeometryCache.h
  libraries/render-utils/src/MeshPartPayload.cpp
  libraries/render-utils/src/MeshPartPayload.h
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
  libraries/shared/src/BillboardMode.cpp
  libraries/shared/src/MaterialMappingMode.cpp
  libraries/shared/src/PrimitiveMode.cpp
  libraries/shared/src/PrimitiveMode.h
  libraries/shared/src/RenderLayer.cpp
  libraries/shared/src/RenderLayer.h
Labels: Development Approved, Engine, Packet Version Change, Project Approved, QA Approved :tada:

#14744 Shape type and compound shape property fixes
  libraries/entities/src/EntityItemProperties.cpp
  scripts/system/assets/data/createAppTooltips.json
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, QA Approved :tada:, bug

#14664 Case 20526 - update readme
  tools/nitpick/README.md
Labels: Development Approved, Engine, Project Approved, QA Ready, nitpick

#14763 Allow filtering on plugin metadata to avoid inappropriate plugins
  assignment-client/src/audio/AudioMixer.cpp
  libraries/plugins/src/plugins/PluginManager.cpp
  libraries/plugins/src/plugins/PluginManager.h
Labels: Development Approved, Infrastructure, QA Approved :tada:

#14759 Enable "Add To World" Asset Browser button for glTF
  interface/resources/qml/hifi/AssetServer.qml
  interface/resources/qml/hifi/dialogs/TabletAssetServer.qml
Labels: Development Approved, Infrastructure, QA Approved :tada:, Server & Network

#14755 Bug fix for avatars that have mesh/joint name duplicates
  libraries/animation/src/AnimSkeleton.cpp
  libraries/fbx/src/FBXSerializer.cpp
Labels: Avatar, Development Approved, Engine, QA Approved :tada:

#14707 fix for continuous color picker update loop
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#14771 Bug fixes for avatarData protocol
  libraries/avatars/src/AvatarData.cpp
Labels: Avatar, Development Approved, QA Ready, Server & Network

#14713 20565 Avatar::_collideWithOtherAvatars does not scale
  interface/src/avatar/AvatarManager.cpp
  interface/src/avatar/AvatarMotionState.cpp
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  interface/src/avatar/MyCharacterController.cpp
  interface/src/avatar/MyCharacterController.h
  interface/src/avatar/MySkeletonModel.cpp
  interface/src/avatar/OtherAvatar.cpp
  interface/src/avatar/OtherAvatar.h
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
  libraries/physics/src/CharacterController.cpp
  libraries/physics/src/CharacterController.h
Labels: Development Approved, Engine, QA Approved :tada:

#14772 MS20825: Login Screen Aspect/Crop with resizing
  interface/resources/qml/LoginDialog.qml
  interface/resources/qml/LoginDialog/images/background.jpg
  interface/resources/qml/LoginDialog/images/background.png
  interface/resources/qml/LoginDialog/images/background_tablet.jpg
  interface/resources/qml/LoginDialog/images/background_tablet.png
  interface/resources/qml/OverlayLoginDialog.qml
  interface/resources/qml/dialogs/TabletLoginDialog.qml
Labels: Client, Development Approved, QA Approved :tada:

#14711 Case 20585: Add missing Web Overlay functionality to Web Entities
  interface/resources/qml/+android/Web3DSurface.qml
  interface/resources/qml/Web3DSurface.qml
  interface/resources/qml/controls/+android/WebEntityView.qml
  interface/resources/qml/controls/WebEntityView.qml
  interface/resources/qml/controlsUit/Key.qml
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/ui/overlays/Web3DOverlay.cpp
  interface/src/ui/overlays/Web3DOverlay.h
  libraries/entities-renderer/src/RenderableWebEntityItem.cpp
  libraries/entities-renderer/src/RenderableWebEntityItem.h
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityPropertyFlags.h
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/EntityTreeElement.cpp
  libraries/entities/src/ShapeEntityItem.cpp
  libraries/entities/src/ShapeEntityItem.h
  libraries/entities/src/WebEntityItem.cpp
  libraries/entities/src/WebEntityItem.h
  libraries/networking/src/udt/PacketHeaders.h
  libraries/octree/src/OctreePacketData.h
  libraries/qml/src/qml/impl/RenderEventHandler.cpp
  libraries/qml/src/qml/impl/RenderEventHandler.h
  libraries/qml/src/qml/impl/SharedObject.cpp
  libraries/shared/src/WebInputMode.cpp
  libraries/shared/src/WebInputMode.h
  libraries/ui/src/ui/OffscreenQmlSurface.h
Labels: Beware: Threading/Deadlock, DO NOT MERGE, Development Approved, Engine, JSDocs, Packet Version Change, Project Approved, QA Approved :tada:, Scripting API change

#14656 Case 20241: Material entity fallthrough
  libraries/entities-renderer/src/RenderableShapeEntityItem.cpp
  libraries/entities-renderer/src/RenderableShapeEntityItem.h
  libraries/entities/src/ShapeEntityItem.cpp
  libraries/entities/src/ShapeEntityItem.h
  libraries/graphics-scripting/src/graphics-scripting/Forward.h
  libraries/graphics-scripting/src/graphics-scripting/GraphicsScriptingInterface.cpp
  libraries/graphics-scripting/src/graphics-scripting/ScriptableModel.cpp
  libraries/graphics/src/graphics/Material.cpp
  libraries/graphics/src/graphics/Material.h
  libraries/model-networking/src/model-networking/MaterialCache.cpp
  libraries/render-utils/src/MeshPartPayload.cpp
  libraries/render-utils/src/MeshPartPayload.h
  libraries/render-utils/src/RenderPipelines.cpp
  libraries/render-utils/src/RenderPipelines.h
Labels: Development Approved, Engine, JSDocs, Project Approved, QA Approved :tada:

#14773 Add failed backup as corrupted during creation
  domain-server/src/AssetsBackupHandler.cpp
Labels: Development Approved, Project Approved, QA Approved :tada:, Server & Network

#14727 MS20311: Oculus login feature
  interface/resources/qml/LoginDialog.qml
  interface/resources/qml/LoginDialog/CompleteProfileBody.qml
  interface/resources/qml/LoginDialog/LinkAccountBody.qml
  interface/resources/qml/LoginDialog/LoggingInBody.qml
  interface/resources/qml/LoginDialog/SignUpBody.qml
  interface/resources/qml/LoginDialog/UsernameCollisionBody.qml
  interface/resources/qml/OverlayLoginDialog.qml
  interface/resources/qml/dialogs/TabletLoginDialog.qml
  interface/src/Application.cpp
  interface/src/ui/LoginDialog.cpp
  interface/src/ui/LoginDialog.h
  libraries/display-plugins/src/display-plugins/Basic2DWindowOpenGLDisplayPlugin.h
  libraries/display-plugins/src/display-plugins/NullDisplayPlugin.h
  libraries/display-plugins/src/display-plugins/hmd/HmdDisplayPlugin.h
  libraries/display-plugins/src/display-plugins/stereo/StereoDisplayPlugin.h
  libraries/networking/src/AccountManager.cpp
  libraries/networking/src/AccountManager.h
  libraries/plugins/src/plugins/DisplayPlugin.h
  libraries/plugins/src/plugins/Forward.h
  libraries/plugins/src/plugins/OculusPlatformPlugin.h
  libraries/plugins/src/plugins/PluginManager.cpp
  libraries/plugins/src/plugins/PluginManager.h
  libraries/plugins/src/plugins/RuntimePlugin.h
  plugins/oculus/src/OculusBaseDisplayPlugin.cpp
  plugins/oculus/src/OculusBaseDisplayPlugin.h
  plugins/oculus/src/OculusHelpers.cpp
  plugins/oculus/src/OculusHelpers.h
  plugins/oculus/src/OculusPlatformPlugin.cpp
  plugins/oculus/src/OculusPlatformPlugin.h
  plugins/oculus/src/OculusProvider.cpp
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14679 (case 20096) Fix missing support for UV scaling parameters in FBX files
  libraries/fbx/src/FBXSerializer.cpp
  libraries/fbx/src/FBXSerializer.h
  libraries/fbx/src/FBXSerializer_Material.cpp
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14684 Case 20550 - nitpick installer
  .gitignore
  INSTALL.md
  server-console/package-lock.json
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:, nitpick

#14678 Added HMD Avatar Alignment Type
  interface/resources/qml/hifi/AvatarApp.qml
  interface/resources/qml/hifi/avatarapp/Settings.qml
  interface/src/Application.cpp
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  libraries/controllers/src/controllers/Input.h
  libraries/shared/src/AvatarConstants.h
  plugins/oculus/src/OculusControllerManager.cpp
  plugins/openvr/src/ViveControllerManager.cpp
  scripts/system/avatarapp.js
Labels: Avatar, Development Approved, Project Approved, QA Approved :tada:

#14712 case 20597: fix zones using FBX models with non-trivial mesh.modelTransform
  libraries/hfm/src/hfm/HFM.cpp
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14742 Settings > Controls > User Recenter Model now saves properly
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
Labels: Avatar, Development Approved, Project Approved, QA Approved :tada:

#14745 (case 20748) Add material inspector to Luci.js
  scripts/developer/utilities/render/deferredLighting.qml
  scripts/developer/utilities/render/luci.js
  scripts/developer/utilities/render/materialInspector.js
  scripts/developer/utilities/render/materialInspector.qml
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14703 Avatar Exporter v0.1 - add bone rules and versioning
  tools/unity-avatar-exporter/Assets/Editor/AvatarExporter.cs
  tools/unity-avatar-exporter/Assets/README.txt
  tools/unity-avatar-exporter/avatarExporter.unitypackage
Labels: Avatar, Create, Development Approved, Project Approved, QA Approved :tada:

#14769 Switch to nvtt with no openmp dependency (remove vcomp140.dll dependency)
  cmake/ports/nvtt/CONTROL
  cmake/ports/nvtt/portfile.cmake
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:, QA Ready

#14774 case 20705: Allow log window to stay on top
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/ui/BaseLogDialog.cpp
  interface/src/ui/LogDialog.cpp
  interface/src/ui/LogDialog.h
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14695 Fixed Sinking Trump Avatar Bug: Stops unnecessary vertical re-centering with big-headed avatar
  interface/src/avatar/MyAvatar.cpp
Labels: Avatar, Development Approved, HMD required, Project Approved, QA Ready, bug

#14781 Case: 20770 allow debug prints in the log by default
  interface/src/Application.cpp
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#14725 Case 20700: Add missing pulse properties to certain Entity types
  libraries/entities-renderer/src/RenderableEntityItem.cpp
  libraries/entities-renderer/src/RenderableEntityItem.h
  libraries/entities-renderer/src/RenderableGridEntityItem.cpp
  libraries/entities-renderer/src/RenderableGridEntityItem.h
  libraries/entities-renderer/src/RenderableImageEntityItem.cpp
  libraries/entities-renderer/src/RenderableImageEntityItem.h
  libraries/entities-renderer/src/RenderableParticleEffectEntityItem.cpp
  libraries/entities-renderer/src/RenderableParticleEffectEntityItem.h
  libraries/entities-renderer/src/RenderableShapeEntityItem.cpp
  libraries/entities-renderer/src/RenderableShapeEntityItem.h
  libraries/entities-renderer/src/RenderableTextEntityItem.cpp
  libraries/entities-renderer/src/RenderableTextEntityItem.h
  libraries/entities-renderer/src/RenderableWebEntityItem.cpp
  libraries/entities-renderer/src/RenderableWebEntityItem.h
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityItemPropertiesMacros.h
  libraries/entities/src/EntityPropertyFlags.h
  libraries/entities/src/GridEntityItem.cpp
  libraries/entities/src/GridEntityItem.h
  libraries/entities/src/ImageEntityItem.cpp
  libraries/entities/src/ImageEntityItem.h
  libraries/entities/src/ParticleEffectEntityItem.cpp
  libraries/entities/src/ParticleEffectEntityItem.h
  libraries/entities/src/PulsePropertyGroup.cpp
  libraries/entities/src/PulsePropertyGroup.h
  libraries/entities/src/ShapeEntityItem.cpp
  libraries/entities/src/ShapeEntityItem.h
  libraries/entities/src/TextEntityItem.cpp
  libraries/entities/src/TextEntityItem.h
  libraries/entities/src/WebEntityItem.cpp
  libraries/entities/src/WebEntityItem.h
  libraries/networking/src/udt/PacketHeaders.h
  libraries/octree/src/OctreePacketData.h
  libraries/shared/src/PulseMode.cpp
  libraries/shared/src/PulseMode.h
Labels: Development Approved, Engine, JSDocs, Packet Version Change, Project Approved, QA Approved :tada:

#14778 MS20501 [CreateApp/Properties] ignore scripted key events from the JSON Editors
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#14696 MS20292 - [CreateApp] Make it easier to see zones while you're editing them
  scripts/system/assets/images/icon-zone.svg
  scripts/system/assets/images/materials/GridPattern.json
  scripts/system/assets/images/materials/GridPattern.png
  scripts/system/edit.js
  scripts/system/modules/entityShapeVisualizer.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#14770 (case 20822) Add normal/tangent generation to HFM preparation step
  libraries/fbx/src/FBXSerializer.cpp
  libraries/hfm/src/hfm/HFM.cpp
  libraries/hfm/src/hfm/HFM.h
  libraries/model-baker/CMakeLists.txt
  libraries/model-baker/src/model-baker/Baker.cpp
  libraries/model-baker/src/model-baker/BakerTypes.h
  libraries/model-baker/src/model-baker/BuildGraphicsMeshTask.cpp
  libraries/model-baker/src/model-baker/BuildGraphicsMeshTask.h
  libraries/model-baker/src/model-baker/CalculateBlendshapeNormalsTask.cpp
  libraries/model-baker/src/model-baker/CalculateBlendshapeNormalsTask.h
  libraries/model-baker/src/model-baker/CalculateBlendshapeTangentsTask.cpp
  libraries/model-baker/src/model-baker/CalculateBlendshapeTangentsTask.h
  libraries/model-baker/src/model-baker/CalculateMeshNormalsTask.cpp
  libraries/model-baker/src/model-baker/CalculateMeshNormalsTask.h
  libraries/model-baker/src/model-baker/CalculateMeshTangentsTask.cpp
  libraries/model-baker/src/model-baker/CalculateMeshTangentsTask.h
  libraries/model-baker/src/model-baker/ModelMath.cpp
  libraries/model-baker/src/model-baker/ModelMath.h
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14767 Switch to nvtt with no openmp dependency (remove vcomp140.dll dependency)
  cmake/ports/nvtt/CONTROL
  cmake/ports/nvtt/portfile.cmake
Labels: Development Approved, Project Approved, QA Approved :tada:

#14779 MS20333: [CreateApp] add missing Material Entity tooltips
  scripts/system/assets/data/createAppTooltips.json
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#14766 case 20701: fixes for grab
  interface/src/avatar/AvatarActionHold.cpp
  interface/src/avatar/AvatarManager.cpp
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/OtherAvatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/SimulationOwner.h
  libraries/physics/src/EntityMotionState.cpp
  libraries/physics/src/EntityMotionState.h
  libraries/physics/src/ObjectMotionState.h
  libraries/physics/src/ThreadSafeDynamicsWorld.cpp
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14764 Case 20722: Ring Gizmo Entities to replace Circle Overlays
  libraries/entities-renderer/src/RenderableEntityItem.cpp
  libraries/entities-renderer/src/RenderableGizmoEntityItem.cpp
  libraries/entities-renderer/src/RenderableGizmoEntityItem.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityItemPropertiesDefaults.h
  libraries/entities/src/EntityPropertyFlags.h
  libraries/entities/src/EntityTypes.cpp
  libraries/entities/src/EntityTypes.h
  libraries/entities/src/GizmoEntityItem.cpp
  libraries/entities/src/GizmoEntityItem.h
  libraries/entities/src/ParticleEffectEntityItem.h
  libraries/entities/src/RingGizmoPropertyGroup.cpp
  libraries/entities/src/RingGizmoPropertyGroup.h
  libraries/networking/src/udt/PacketHeaders.h
  libraries/octree/src/OctreePacketData.h
  libraries/render-utils/src/GeometryCache.cpp
  libraries/render-utils/src/GeometryCache.h
  libraries/shared/src/GizmoType.cpp
  libraries/shared/src/GizmoType.h
Labels: Development Approved, Engine, Packet Version Change, Project Approved, QA Approved :tada:

#14722 Multi-sphere avatar detailed collisions
  interface/src/Application.cpp
  interface/src/avatar/AvatarManager.cpp
  interface/src/avatar/AvatarManager.h
  interface/src/avatar/DetailedMotionState.cpp
  interface/src/avatar/DetailedMotionState.h
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  interface/src/avatar/MyCharacterController.cpp
  interface/src/avatar/MyCharacterController.h
  interface/src/avatar/OtherAvatar.cpp
  interface/src/avatar/OtherAvatar.h
  interface/src/raypick/RayPick.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
  libraries/physics/src/CharacterController.cpp
  libraries/physics/src/CharacterController.h
  libraries/physics/src/MultiSphereShape.cpp
  libraries/physics/src/MultiSphereShape.h
  libraries/physics/src/ObjectMotionState.cpp
  libraries/physics/src/ObjectMotionState.h
  libraries/physics/src/PhysicsEngine.cpp
  libraries/physics/src/ShapeFactory.cpp
  libraries/physics/src/ThreadSafeDynamicsWorld.cpp
  libraries/physics/src/ThreadSafeDynamicsWorld.h
  libraries/shared/src/DebugDraw.cpp
  libraries/shared/src/DebugDraw.h
  libraries/shared/src/PhysicsCollisionGroups.h
  libraries/shared/src/PhysicsHelpers.cpp
  libraries/shared/src/ShapeInfo.cpp
  libraries/shared/src/ShapeInfo.h
Labels: Avatar, Development Approved, Project Approved, QA Ready

#14757 Choose avatar and set display name
  android/apps/interface/src/main/assets/avatars.json
  android/apps/interface/src/main/cpp/native.cpp
  android/apps/interface/src/main/java/io/highfidelity/hifiinterface/MainActivity.java
  android/apps/interface/src/main/java/io/highfidelity/hifiinterface/fragment/ProfileFragment.java
  android/apps/interface/src/main/java/io/highfidelity/hifiinterface/provider/AvatarProvider.java
  android/apps/interface/src/main/java/io/highfidelity/hifiinterface/provider/view/AvatarAdapter.java
  android/apps/interface/src/main/res/layout/avatar_item.xml
  android/apps/interface/src/main/res/layout/fragment_profile.xml
  android/apps/interface/src/main/res/menu/menu_navigation.xml
  android/apps/interface/src/main/res/values/dimens.xml
  android/apps/interface/src/main/res/values/strings.xml
  interface/src/AndroidHelper.cpp
  interface/src/AndroidHelper.h
Labels: Android, Client, Development Approved, Project Approved, QA Approved :tada:

#14784 case 20805: RC78.1: Fix the distance attenuation of stereo local injectors
  interface/src/Application.cpp
  libraries/audio-client/src/AudioClient.cpp
  libraries/audio/src/AudioInjector.h
  libraries/audio/src/AudioInjectorOptions.cpp
  libraries/audio/src/AudioInjectorOptions.h
  libraries/script-engine/src/AudioScriptingInterface.cpp
  libraries/script-engine/src/AudioScriptingInterface.h
  libraries/ui/src/ui/TabletScriptingInterface.cpp
Labels: Client, Development Approved, Project Approved, QA Approved :tada:, bug

#14789 Case 20771: Make sure that the script log is in the correct location when switching to and from HMD
  scripts/developer/debugging/debugWindow.js
Labels: Client, Development Approved, Engine, Project Approved, QA Approved :tada:

#14797 case 20805: RC78.1 to master: Fix the distance attenuation of stereo local injectors
  interface/src/Application.cpp
  libraries/audio-client/src/AudioClient.cpp
  libraries/audio/src/AudioInjector.h
  libraries/audio/src/AudioInjectorOptions.cpp
  libraries/audio/src/AudioInjectorOptions.h
  libraries/script-engine/src/AudioScriptingInterface.cpp
  libraries/script-engine/src/AudioScriptingInterface.h
  libraries/ui/src/ui/TabletScriptingInterface.cpp
Labels: Client, Development Approved, QA Approved :tada:, bug

#14798 79.0/master: Fix erroneous 'CMAKE_TOOLCHAIN_FILE has changed' errors on Jenkins
  hifi_vcpkg.py
Labels: Critical Fix, Development Approved, Project Approved, QA Ready

#14793 79.0/master: Fix errors and intermittent failures in Android gradle builds in containers
  android/containerized_build.sh
Labels: Development Approved, Project Approved, QA Ready

#14800 78.1: Fix errors and intermittent failures in Android gradle builds in containers
  android/containerized_build.sh
Labels: Development Approved, Project Approved, QA Approved :tada:

#14785 RC78.1: Bug fixes and improvements to audio distance attenuation
  assignment-client/src/audio/AudioMixer.cpp
  assignment-client/src/audio/AudioMixerSlave.cpp
  libraries/audio-client/src/AudioClient.cpp
  libraries/audio/src/AudioHRTF.h
  libraries/shared/src/AudioHelpers.h
Labels: Development Approved, Project Approved, QA Approved :tada:

#14799 78.1: Fix erroneous 'CMAKE_TOOLCHAIN_FILE has changed' errors on Jenkins
  hifi_vcpkg.py
Labels: Critical Fix, Development Approved, Project Approved, QA Approved :tada:

#14732 Bug fixes and improvements to audio distance attenuation
  assignment-client/src/audio/AudioMixer.cpp
  assignment-client/src/audio/AudioMixerSlave.cpp
  libraries/audio-client/src/AudioClient.cpp
  libraries/audio/src/AudioHRTF.h
  libraries/shared/src/AudioHelpers.h
Labels: Development Approved, Project Approved, QA Approved :tada:, Server & Network, bug

#14796 [78.1] Add failed backup as corrupted during creation
  domain-server/src/AssetsBackupHandler.cpp
Labels: Development Approved, Project Approved, QA Approved :tada:, Server & Network

#14791 Don't update PAL namecard with empty strings
  interface/resources/qml/hifi/Pal.qml
Labels: Development Approved, Infrastructure, Project Approved, QA Approved :tada:

#14415 RC branch script
  tools/scripts/Readme.md
  tools/scripts/rc-branches.py
  tools/scripts/requirements.txt
Labels: Development Approved, Project Approved

#14805 Case 20902: Give SendAsset.qml a background color
  interface/resources/qml/hifi/commerce/common/sendAsset/SendAsset.qml
Labels: Client, Development Approved, Engine, Project Approved, QA Ready

#14801 Case 20867: Fix translucent textures not getting reset
  libraries/entities-renderer/src/RenderableShapeEntityItem.cpp
  libraries/model-networking/src/model-networking/ModelCache.cpp
  libraries/render-utils/src/MeshPartPayload.cpp
  libraries/render-utils/src/RenderPipelines.cpp
Labels: Critical Fix, Development Approved, Engine, Project Approved, QA Approved :tada:, bug

#14794 Case 20888: Fix color space
  libraries/entities-renderer/src/RenderableShapeEntityItem.cpp
  libraries/render-utils/src/RenderPipelines.cpp
Labels: Critical Fix, Development Ready, Engine, Project Approved, QA Approved :tada:, bug

#14806 MS20893 [CreateApp] Ignore children of mismatching entityHostTypes
  scripts/system/edit.js
  scripts/system/libraries/entitySelectionTool.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#14807 Case 20906: Give SendAsset.qml a background color
  interface/resources/qml/hifi/commerce/common/sendAsset/SendAsset.qml
Labels: Client, Development Approved, Engine, Project Approved, QA Approved :tada:

#14810 Case 20833: Fix procedural skybox depth testing
  libraries/procedural/src/procedural/ProceduralSkybox.cpp
Labels: Critical Fix, Development Approved, Engine, Project Approved, QA Approved :tada:, bug

#14812 80.0/master: Fix small miscalculation in space requirements for serialized avatar-data
  libraries/avatars/src/AvatarData.cpp
Labels: Development Approved, Infrastructure, Project Approved, QA Approved :tada:

#14820 [78.1] Fix reload mechanic for entity server scripts
  assignment-client/src/scripts/EntityScriptServer.cpp
  assignment-client/src/scripts/EntityScriptServer.h
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
Labels: Development Approved, Infrastructure, Project Approved, QA Approved :tada:

#14819 MS20921: Oculus login button not appearing (RC79)
  interface/src/Application.cpp
Labels: Client, Critical Fix, Development Approved, Project Approved, QA Approved :tada:, bug

#14828 Fix procedural skybox depth testing (78.1)
  libraries/procedural/src/procedural/ProceduralSkybox.cpp
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14833 Case 20940: Goto the spot on first launch (78.1)
  interface/src/ui/AddressBarDialog.cpp
  libraries/networking/src/AddressManager.cpp
  libraries/networking/src/AddressManager.h
Labels: Client, Development Approved, Engine, Project Approved, QA Approved :tada:

#14832 Case 20941: Goto the spot on first launch (79.0)
  interface/src/ui/AddressBarDialog.cpp
  libraries/networking/src/AddressManager.cpp
  libraries/networking/src/AddressManager.h
Labels: Client, Development Approved, Engine, Project Approved, QA Approved :tada:

#14831 Case 20942: Goto the spot on first launch (80.0/master)
  interface/src/ui/AddressBarDialog.cpp
  libraries/networking/src/AddressManager.cpp
  libraries/networking/src/AddressManager.h
Labels: Client, Development Approved, Engine, Project Approved, QA Approved :tada:
