Repository highfidelity/hifi, pull requests merged in 2019-08, with the labels that each got.

#15936 acoustic echo cancellation
  cmake/macros/TargetWebRTC.cmake
  cmake/ports/hifi-deps/CONTROL
  cmake/ports/webrtc/CONTROL
  cmake/ports/webrtc/portfile.cmake
  hifi_android.py
  interface/resources/qml/hifi/audio/Audio.qml
  interface/resources/qml/hifi/simplifiedUI/settingsApp/audio/Audio.qml
  interface/src/scripting/Audio.cpp
  interface/src/scripting/Audio.h
  libraries/audio-client/CMakeLists.txt
  libraries/audio-client/src/AudioClient.cpp
  libraries/audio-client/src/AudioClient.h
  libraries/shared/src/shared/WebRTC.h
Labels: Development Approved, Project Approved, Scripting API change

#16004 Dev319 - Show user who installed content in 'Installed Content' section of domain admin pages
  domain-server/resources/web/content/js/content.js
  domain-server/src/AssetsBackupHandler.cpp
  domain-server/src/AssetsBackupHandler.h
  domain-server/src/BackupHandler.h
  domain-server/src/ContentSettingsBackupHandler.cpp
  domain-server/src/ContentSettingsBackupHandler.h
  domain-server/src/DomainContentBackupManager.cpp
  domain-server/src/DomainContentBackupManager.h
  domain-server/src/DomainServer.cpp
  domain-server/src/DomainServer.h
  domain-server/src/EntitiesBackupHandler.cpp
  domain-server/src/EntitiesBackupHandler.h
Labels: Development Approved, Metaverse, QA Approved :tada:

#16012 BUGZ-1069: fix crash in oven for lack of MaterialCache instance in DependencyManager
  tools/oven/src/Oven.cpp
Labels: Development Approved, Engine, Project Approved

#16019 BUGZ-1158: fix uninitialized variables
  libraries/entities/src/EntityScriptingInterface.h
Labels: Development Approved, Engine, Project Approved

#16018 DEV-279: Add rendering API information to the platform JSON object
  interface/src/Application.cpp
  libraries/gl/src/gl/GLHelpers.cpp
  libraries/gl/src/gl/GLHelpers.h
  libraries/gl/src/gl/GLWindow.cpp
  libraries/gl/src/gl/OffscreenGLCanvas.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLBackend.cpp
  libraries/platform/CMakeLists.txt
  libraries/platform/src/platform/PlatformKeys.h
  libraries/platform/src/platform/backend/MACOSPlatform.cpp
  libraries/platform/src/platform/backend/MACOSPlatform.h
  libraries/platform/src/platform/backend/Platform.cpp
  libraries/platform/src/platform/backend/PlatformInstance.cpp
  libraries/platform/src/platform/backend/PlatformInstance.h
  libraries/platform/src/platform/backend/WINPlatform.cpp
  libraries/platform/src/platform/backend/WINPlatform.h
  libraries/ui/src/ui/OffscreenQmlSurface.cpp
Labels: Development Approved, Engine, Project Approved, Scripting API change

#16021 BUGZ-352: Persist the audio volume settings across sessions
  interface/src/scripting/Audio.cpp
  interface/src/scripting/Audio.h
  libraries/networking/src/NodeList.cpp
Labels: Client, Development Approved, QA Approved :tada:

#16008 Supporting text effects + fonts on Text Entities
  interface/src/ui/overlays/QmlOverlay.cpp
  interface/src/ui/overlays/QmlOverlay.h
  interface/src/ui/overlays/TextOverlay.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/entities-renderer/src/RenderableEntityItem.cpp
  libraries/entities-renderer/src/RenderableEntityItem.h
  libraries/entities-renderer/src/RenderableTextEntityItem.cpp
  libraries/entities-renderer/src/RenderableTextEntityItem.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityPropertyFlags.h
  libraries/entities/src/TextEntityItem.cpp
  libraries/entities/src/TextEntityItem.h
  libraries/networking/src/udt/PacketHeaders.h
  libraries/octree/src/OctreePacketData.h
  libraries/render-utils/src/TextRenderer3D.cpp
  libraries/render-utils/src/TextRenderer3D.h
  libraries/render-utils/src/sdf_text3D.slf
  libraries/render-utils/src/sdf_text3D.slh
  libraries/render-utils/src/sdf_text3D.slv
  libraries/render-utils/src/text/EffectType.h
  libraries/render-utils/src/text/Font.cpp
  libraries/render-utils/src/text/Font.h
  libraries/render-utils/src/text/FontFamilies.h
  libraries/render-utils/src/text/Glyph.cpp
  libraries/shared/src/FontFamilies.h
  libraries/shared/src/TextEffect.cpp
  libraries/shared/src/TextEffect.h
Labels: Development Approved, JSDocs, Open Source, Packet Version Change, Project Approved, QA Approved :tada:, Scripting API change

#16023 BUGZ-1145: check for Win7 before using SHCore.dll API
  libraries/platform/src/platform/backend/WINPlatform.cpp
Labels: Development Approved, Development Ready, Engine, Project Approved

#15985 DEV-264: Lilypad Launcher (Mac): Auto-update Launcher
  launchers/darwin/CMakeLists.txt
  launchers/darwin/src/DownloadLauncher.h
  launchers/darwin/src/DownloadLauncher.m
  launchers/darwin/src/LatestBuildRequest.m
  launchers/darwin/src/Launcher.h
  launchers/darwin/src/Launcher.m
  launchers/darwin/src/LauncherCommandlineArgs.h
  launchers/darwin/src/LauncherCommandlineArgs.m
  launchers/darwin/src/main.mm
  launchers/darwin/src/updater/main.m
Labels: Client, Development Ready, Project Approved

#16024 case BUGZ-1168: adding default script location setting for defaultscriptoverride run…
  libraries/script-engine/src/ScriptEngines.cpp
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#16028 RC84: Fix BUGZ-1131: Add Shield icon back to HUD for Metaverse users
  interface/src/ui/AvatarInputs.cpp
  interface/src/ui/AvatarInputs.h
Labels: Development Approved, Project Approved, UI/UX, bug

#16029 BUGZ-1171: Fix audio output not working (alternate fix)
  libraries/audio-client/src/AudioClient.cpp
Labels: Client, Development Approved, PRE-MERGE TESTING REQUIRED, Project Approved, bug

#16030 fix updater typo
  launchers/darwin/src/DownloadLauncher.m
Labels: Client, Development Approved, Project Approved

#15992 Refined reaction and sitting animations
  interface/resources/avatar/animations/emote_agree_acknowledge.fbx
  interface/resources/avatar/animations/emote_agree_headnod.fbx
  interface/resources/avatar/animations/emote_agree_headnodyes.fbx
  interface/resources/avatar/animations/emote_agree_longheadnod.fbx
  interface/resources/avatar/animations/emote_agree_thisorthat.fbx
  interface/resources/avatar/animations/emote_agree_thoughtfulheadnod.fbx
  interface/resources/avatar/animations/emote_clap01_all.fbx
  interface/resources/avatar/animations/emote_clap02_all.fbx
  interface/resources/avatar/animations/emote_clap03_all.fbx
  interface/resources/avatar/animations/emote_disagree_annoyedheadshake.fbx
  interface/resources/avatar/animations/emote_disagree_defeated.fbx
  interface/resources/avatar/animations/emote_disagree_drophead.fbx
  interface/resources/avatar/animations/emote_disagree_no.fbx
  interface/resources/avatar/animations/emote_disagree_thoughtfulheadshake.fbx
  interface/resources/avatar/animations/emote_point01_all.fbx
  interface/resources/avatar/animations/emote_raisehand01_all.fbx
  interface/resources/avatar/animations/emote_raisehand03_all.fbx
  interface/resources/avatar/animations/emote_raisehand04_all.fbx
  interface/resources/avatar/animations/sitting_idle.fbx
  interface/resources/avatar/animations/sitting_idle03.fbx
  interface/resources/avatar/animations/sitting_talk02.fbx
  interface/resources/avatar/animations/sitting_talk03.fbx
  interface/resources/avatar/avatar-animation.json
  interface/resources/avatar/old-avatar-animation.json
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  libraries/animation/src/AnimNodeLoader.cpp
  libraries/animation/src/AnimOverlay.cpp
  libraries/animation/src/AnimRandomSwitch.cpp
  libraries/animation/src/AnimRandomSwitch.h
  libraries/animation/src/AnimStateMachine.cpp
  libraries/animation/src/AnimStateMachine.h
  libraries/animation/src/AnimUtil.cpp
  libraries/animation/src/AnimUtil.h
  libraries/animation/src/Rig.cpp
  libraries/animation/src/Rig.h
  libraries/shared/src/AvatarConstants.h
Labels: Avatar, Development Approved, Project Approved

#16011 Case 22106: DebugDraw JSDoc
  libraries/shared/src/DebugDraw.h
Labels: JSDocs

#15959 DOC-124: Tidy JSDoc from some recent API changes
  interface/src/avatar/MyAvatar.h
  interface/src/scripting/Audio.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/KeyLightPropertyGroup.h
  libraries/material-networking/src/material-networking/MaterialCache.cpp
Labels: JSDocs, Project Approved

#16034 BUGZ-1103: Use 'Master GPU' information in About screen
  interface/resources/qml/hifi/simplifiedUI/settingsApp/about/About.qml
Labels: Development Approved, Engine, Project Approved, UI/UX, bug

#16005 DOC-61: Render API JSDoc
  interface/src/scripting/RenderScriptingInterface.h
  libraries/avatars/src/AvatarData.h
  libraries/task/src/task/Config.h
Labels: JSDocs

#16003 DOC-84: Update JSDoc with glTF
  assignment-client/src/avatars/ScriptableAvatar.h
  interface/src/avatar/MyAvatar.h
  interface/src/ui/overlays/Overlays.cpp
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
  libraries/entities/src/AnimationPropertyGroup.cpp
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityTypes.h
  libraries/shared/src/RegisteredMetaTypes.cpp
Labels: JSDocs

#15988 DOC-98, DOC-114: PlatformInfo API changes JSDoc
  interface/src/scripting/PlatformInfoScriptingInterface.h
  libraries/platform/src/platform/backend/Platform.cpp
  tools/jsdoc/plugins/hifi.js
Labels: JSDocs

#16036 BUGZ-1185: WL Fix update process
  launchers/win32/LauncherApp.cpp
  launchers/win32/LauncherDlg.cpp
  launchers/win32/LauncherManager.cpp
  launchers/win32/LauncherManager.h
Labels: Development Approved, Project Approved

#16039 Fix BUGZ-1197 (and others): Ensure enterEntity is emitted when avatar is inside entity and script is reloaded
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
Labels: Client, Development Approved, Project Approved, UI/UX, bug

#16025 (BUGZ-1059) Improve debug API for picks/pointers
  interface/src/avatar/MyAvatarHeadTransformNode.cpp
  interface/src/avatar/MyAvatarHeadTransformNode.h
  interface/src/raypick/CollisionPick.cpp
  interface/src/raypick/CollisionPick.h
  interface/src/raypick/LaserPointer.cpp
  interface/src/raypick/LaserPointer.h
  interface/src/raypick/LaserPointerScriptingInterface.cpp
  interface/src/raypick/MouseTransformNode.cpp
  interface/src/raypick/MouseTransformNode.h
  interface/src/raypick/ParabolaPick.h
  interface/src/raypick/ParabolaPointer.cpp
  interface/src/raypick/ParabolaPointer.h
  interface/src/raypick/PickScriptingInterface.cpp
  interface/src/raypick/PickScriptingInterface.h
  interface/src/raypick/PointerScriptingInterface.cpp
  interface/src/raypick/PointerScriptingInterface.h
  interface/src/raypick/RayPick.h
  interface/src/raypick/RayPickScriptingInterface.cpp
  interface/src/raypick/StylusPick.h
  interface/src/raypick/StylusPointer.cpp
  interface/src/raypick/StylusPointer.h
  libraries/avatars-renderer/src/avatars-renderer/AvatarTransformNode.cpp
  libraries/avatars-renderer/src/avatars-renderer/AvatarTransformNode.h
  libraries/graphics-scripting/src/graphics-scripting/GraphicsScriptingInterface.cpp
  libraries/graphics-scripting/src/graphics-scripting/GraphicsScriptingInterface.h
  libraries/pointers/src/Pick.cpp
  libraries/pointers/src/Pick.h
  libraries/pointers/src/PickManager.cpp
  libraries/pointers/src/PickManager.h
  libraries/pointers/src/PickTransformNode.cpp
  libraries/pointers/src/PickTransformNode.h
  libraries/pointers/src/Pointer.cpp
  libraries/pointers/src/Pointer.h
  libraries/pointers/src/PointerManager.cpp
  libraries/pointers/src/PointerManager.h
  libraries/shared/src/NestableTransformNode.cpp
  libraries/shared/src/NestableTransformNode.h
  libraries/shared/src/RegisteredMetaTypes.cpp
  libraries/shared/src/RegisteredMetaTypes.h
  libraries/shared/src/TransformNode.h
Labels: Development Approved, Engine, Feedback Welcome, Project Approved, Scripting API change

#16017 BUGZ-1046 - send entity packets reliably for initial query
  assignment-client/src/entities/EntityTreeSendThread.cpp
  assignment-client/src/octree/OctreeSendThread.cpp
  libraries/networking/src/udt/Packet.h
  libraries/octree/src/OctreeQueryNode.cpp
  libraries/octree/src/OctreeSceneStats.h
Labels: Development Approved, Metaverse, PRE-MERGE TESTING REQUIRED, QA Approved :tada:

#16040 Better detection of audio clipping during echo cancellation
  libraries/audio-client/src/AudioClient.cpp
Labels: Client, Development Approved, Project Approved

#16042 DEV-327: Prevent AnimRandomSwitch from repeating same animation twice in a row
  libraries/animation/src/AnimNodeLoader.cpp
  libraries/animation/src/AnimRandomSwitch.cpp
  libraries/animation/src/AnimRandomSwitch.h
Labels: Avatar, Development Approved, Project Approved

#16026 DEV-263: HQ Launcher/Interface (Mac) - appear to consolidate apps
  launchers/darwin/CMakeLists.txt
  launchers/darwin/src/Launcher.m
  launchers/darwin/src/NSTask+NSTaskExecveAdditions.h
  launchers/darwin/src/NSTask+NSTaskExecveAdditions.m
Labels: Development Approved

#16037 BUGZ-1184: Fix create duplication key conflicting with camera orbit
  scripts/system/libraries/entityCameraTool.js
Labels: Client, Create, Development Approved, Documentation, Project Approved

#16041 BUGZ-830: Fix memory leak in the ESS
  libraries/script-engine/src/XMLHttpRequestClass.cpp
  libraries/script-engine/src/XMLHttpRequestClass.h
  scripts/modules/request.js
Labels: Development Approved, Metaverse, Project Approved

#16033 BUGZ-1187: Allow developers to bootstrap vcpkg via the traditional method
  BUILD_WIN.md
  hifi_vcpkg.py
Labels: Development Approved, Project Approved

#15922 BUGZ-993: Bump minimum threadpool size to 2
  interface/src/Application.cpp
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.h
  libraries/display-plugins/src/display-plugins/hmd/HmdDisplayPlugin.h
Labels: Development Approved, Engine, Metaverse, PRE-MERGE TESTING REQUIRED, QA Approved :tada:

#16047 BUGZ-1097: Fix invalid rendering of splash frame on AMD based macs
  interface/src/graphics/GraphicsEngine.cpp
Labels: Development Approved, Engine, bug

#16045 Higher quality standing and seated reactions
  interface/resources/avatar/animations/emote_clap02_all.fbx
  interface/resources/avatar/animations/sitting_emote_agree_headnod.fbx
  interface/resources/avatar/animations/sitting_emote_agree_headnodyes.fbx
  interface/resources/avatar/animations/sitting_emote_agree_longheadnod.fbx
  interface/resources/avatar/animations/sitting_emote_clap_all.fbx
  interface/resources/avatar/animations/sitting_emote_disagree_drophead.fbx
  interface/resources/avatar/animations/sitting_emote_disagree_headshake.fbx
  interface/resources/avatar/animations/sitting_emote_point_all.fbx
  interface/resources/avatar/animations/sitting_emote_raisehand_all.fbx
  interface/resources/avatar/animations/sitting_talk04.fbx
  interface/resources/avatar/avatar-animation.json
  libraries/animation/src/AnimRandomSwitch.cpp
  libraries/animation/src/AnimStateMachine.cpp
  libraries/animation/src/Rig.cpp
Labels: Avatar, Development Approved, Project Approved

#16043 BUGZ-1205: fix Linux builds when -DBUILD_SHARED_LIBS=ON
  tools/nitpick/CMakeLists.txt
Labels: Development Approved, Engine, Project Approved

#16044 BUGZ-1161: Report count of dropped packets in Socket::checkForReadyReadBackup()
  assignment-client/src/avatars/AvatarMixerSlavePool.h
  libraries/networking/src/udt/Socket.cpp
  libraries/shared/src/shared/QtHelpers.h
Labels: Development Approved, Metaverse, Project Approved

#16048 DEV-332: Ramp on and off Head IK to make reactions smoother
  libraries/animation/src/AnimInverseKinematics.cpp
  libraries/animation/src/AnimInverseKinematics.h
Labels: Avatar, Development Rejected, Project Approved

#16049 (BUGZ-1112) Make 20:20 vision equal seeing 1m cube from 400 meters away
  interface/resources/qml/hifi/dialogs/TabletLODTools.qml
  interface/src/Application.cpp
  interface/src/LODManager.cpp
  interface/src/LODManager.h
  interface/src/ui/LodToolsDialog.cpp
  libraries/octree/src/OctreeConstants.h
  libraries/octree/src/OctreeUtils.cpp
  libraries/octree/src/OctreeUtils.h
  libraries/render/src/render/DrawSceneOctree.cpp
  scripts/developer/utilities/render/lod.qml
  scripts/simplifiedUI/ui/simplifiedUI.js
Labels: Development Approved, Engine, HMD required, Project Approved, Scripting API change

#16054 BUGZ-919: Skybox broken on older AMD drivers
  libraries/gpu-gl-common/src/gpu/gl/GLTexelFormat.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLTexelFormat.h
  libraries/gpu-gl/src/gpu/gl45/GL45Backend.h
  libraries/gpu-gl/src/gpu/gl45/GL45BackendTexture.cpp
Labels: Development Approved, Engine, Project Approved, bug

#16055 BUGZ-1233: Remove keyboard shortcut to LoD tools
  interface/src/Application.cpp
Labels: Client, Development Approved, Project Approved

#16051 DEV-352: Add --version to the Oven
  libraries/shared/src/Profile.cpp
  tools/oven/src/OvenCLIApplication.cpp
  tools/oven/src/OvenCLIApplication.h
  tools/oven/src/main.cpp
Labels: Development Approved, Metaverse, Project Approved

#16056 BUGZ-1239: Delete reply after the callback is executed
  libraries/script-engine/src/XMLHttpRequestClass.cpp
Labels: Development Approved, Project Approved, bug

#16060 BUGZ-1081: Put Macs into "Low" rendering tier if INtel GPU
  libraries/platform/src/platform/Profiler.cpp
Labels: Development Approved, Engine, Project Approved

#16058 BUGZ-1119: workaround for race condition crash in QML rendering
  libraries/qml/src/qml/impl/RenderEventHandler.cpp
Labels: Development Approved, Engine, Project Approved

#16053 BUGZ-1173, BUGZ-1175: On Windows, Fix black edges on whiteboard lines in Forward and more issues in GL41Backend
  interface/src/scripting/RenderScriptingInterface.cpp
  libraries/entities-renderer/src/RenderablePolyLineEntityItem.cpp
  libraries/entities-renderer/src/paintStroke.slf
  libraries/gpu-gl-common/src/gpu/gl/GLBackend.h
  libraries/gpu-gl-common/src/gpu/gl/GLBackendShader.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLPipeline.cpp
  libraries/gpu-gl/src/gpu/gl41/GL41BackendShader.cpp
  libraries/gpu/src/gpu/Shader.cpp
  libraries/gpu/src/gpu/Shader.h
  libraries/procedural/src/procedural/Procedural.cpp
  libraries/render-utils/src/RenderForwardTask.cpp
  libraries/render-utils/src/RenderForwardTask.h
  libraries/render/src/render/Engine.h
  libraries/render/src/render/ShapePipeline.cpp
  libraries/shaders/src/shaders/Shaders.cpp
  libraries/shaders/src/shaders/Shaders.h
  libraries/task/src/task/Config.cpp
  libraries/task/src/task/Config.h
  libraries/task/src/task/Task.h
  scripts/developer/utilities/lib/jet/jet.js
  scripts/developer/utilities/lib/jet/qml/TaskPropView.qml
  scripts/developer/utilities/lib/prop/PropGroup.qml
  scripts/developer/utilities/lib/prop/PropItem.qml
  scripts/developer/utilities/lib/prop/PropScalar.qml
  scripts/developer/utilities/lib/prop/style/Global.qml
  scripts/developer/utilities/render/engineInspector.js
  scripts/developer/utilities/render/engineInspector.qml
  scripts/developer/utilities/render/engineList.js
  scripts/developer/utilities/render/engineList.qml
  scripts/developer/utilities/render/luci.qml
  scripts/developer/utilities/render/luci/Antialiasing.qml
  scripts/developer/utilities/render/luci2.js
Labels: Development Approved, Engine, Project Approved

#16015 BUGZ-902: Drastically reduce locking and branching necessary for render updates
  interface/src/octree/SafeLanding.cpp
  libraries/entities-renderer/src/RenderableEntityItem.cpp
  libraries/entities-renderer/src/RenderableEntityItem.h
  libraries/entities-renderer/src/RenderableGizmoEntityItem.cpp
  libraries/entities-renderer/src/RenderableGizmoEntityItem.h
  libraries/entities-renderer/src/RenderableGridEntityItem.cpp
  libraries/entities-renderer/src/RenderableGridEntityItem.h
  libraries/entities-renderer/src/RenderableImageEntityItem.cpp
  libraries/entities-renderer/src/RenderableImageEntityItem.h
  libraries/entities-renderer/src/RenderableLightEntityItem.cpp
  libraries/entities-renderer/src/RenderableLightEntityItem.h
  libraries/entities-renderer/src/RenderableLineEntityItem.cpp
  libraries/entities-renderer/src/RenderableLineEntityItem.h
  libraries/entities-renderer/src/RenderableMaterialEntityItem.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities-renderer/src/RenderableParticleEffectEntityItem.cpp
  libraries/entities-renderer/src/RenderableParticleEffectEntityItem.h
  libraries/entities-renderer/src/RenderablePolyLineEntityItem.cpp
  libraries/entities-renderer/src/RenderablePolyVoxEntityItem.cpp
  libraries/entities-renderer/src/RenderableShapeEntityItem.cpp
  libraries/entities-renderer/src/RenderableTextEntityItem.cpp
  libraries/entities-renderer/src/RenderableWebEntityItem.cpp
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/entities/src/GizmoEntityItem.cpp
  libraries/entities/src/GridEntityItem.cpp
  libraries/entities/src/ImageEntityItem.cpp
  libraries/entities/src/LightEntityItem.cpp
  libraries/entities/src/LightEntityItem.h
  libraries/entities/src/LineEntityItem.cpp
  libraries/entities/src/LineEntityItem.h
  libraries/entities/src/MaterialEntityItem.cpp
  libraries/entities/src/MaterialEntityItem.h
  libraries/entities/src/ModelEntityItem.cpp
  libraries/entities/src/ParticleEffectEntityItem.cpp
  libraries/entities/src/ParticleEffectEntityItem.h
  libraries/entities/src/PolyLineEntityItem.cpp
  libraries/entities/src/PolyLineEntityItem.h
  libraries/entities/src/PolyVoxEntityItem.cpp
  libraries/entities/src/ShapeEntityItem.cpp
  libraries/entities/src/ShapeEntityItem.h
  libraries/entities/src/TextEntityItem.cpp
  libraries/entities/src/WebEntityItem.cpp
Labels: Beware: Threading/Deadlock, Development Approved, Engine, Open Source, Project Approved

#16059 BUGZ-1156: Allow collapsing of all multi spheres
  libraries/physics/src/MultiSphereShape.cpp
Labels: Avatar, Development Approved, Project Approved

#16061 BUGZ-984: Wait for client entity-scripts to unload when shutting down
  interface/src/Application.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/script-engine/src/ScriptEngine.cpp
  libraries/script-engine/src/ScriptEngine.h
Labels: Client, Development Approved, Metaverse, Project Approved, bug

#16063 BUGZ-1242: Fix linux specific script engine crash
  scripts/modules/request.js
Labels: Development Approved, Metaverse, Project Approved

#16067 Fix BUGZ-1263 and probably BUGZ-1273: Fix input device muted banner
  scripts/simplifiedUI/ui/simplifiedUI.js
Labels: Development Approved, Project Approved, UI/UX, bug

#16073 Fix some engine bugs that fix muted state in all UIs including simplifiedUI
  interface/src/scripting/Audio.cpp
Labels: Client, Development Approved, Project Approved, UI/UX, bug

#16074 BUGZ-1295: Fix typo in Help > Controls > Turn Right
  interface/resources/qml/hifi/simplifiedUI/helpApp/controls/ControlsTable.qml
Labels: Development Ready, Project Approved, UI/UX, bug

#16062 Tuning pass on anim-graph, using the new blend modes and engine features
  interface/resources/avatar/animations/emote_agree_thisorthat.fbx
  interface/resources/avatar/animations/emote_disagree_no.fbx
  interface/resources/avatar/animations/idle_LFF_all.fbx
  interface/resources/avatar/animations/idle_RFF_all.fbx
  interface/resources/avatar/avatar-animation.json
Labels: Avatar, Development Approved, PRE-MERGE TESTING REQUIRED, Project Approved

#16070 BUGZ-1293: Fix mac launcher not correctly reading interface version
  launchers/darwin/src/Interface.m
Labels: Client, Development Approved, Project Approved

#16068 DOC-95: Fix callback functions' display in JSDoc
  tools/jsdoc/hifi-jsdoc-template/tmpl/container.tmpl
  tools/jsdoc/hifi-jsdoc-template/tmpl/method.tmpl
Labels: JSDocs

#16069 BUGZ-1247: Better handling of other-avatar verify-failed appearance
  assignment-client/src/avatars/AvatarMixerSlave.cpp
  interface/src/avatar/MyAvatar.h
  interface/src/commerce/Wallet.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
  libraries/avatars/src/AvatarHashMap.cpp
Labels: Avatar, Development Approved, Metaverse

#16076 Remove 'About' tab from Settings
  interface/resources/qml/hifi/simplifiedUI/settingsApp/SettingsApp.qml
  interface/resources/qml/hifi/simplifiedUI/settingsApp/about/About.qml
  interface/resources/qml/hifi/simplifiedUI/settingsApp/about/images/logo.png
Labels: Development Approved, Project Approved, UI/UX

#16066 Avatar sitting bug fixes
  interface/resources/avatar/avatar-animation.json
  interface/src/avatar/MyAvatar.cpp
  libraries/animation/src/Rig.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
Labels: Avatar, Development Approved, Project Approved

#16079 Remove unused TabletAddressDialog internal property, fixing BUGZ-1294
  interface/resources/qml/hifi/tablet/TabletAddressDialog.qml
Labels: Client, Development Approved, Project Approved, UI/UX, bug

#16075 BUGZ-374: Fix Mac getting stuck in mouse look
  interface/src/Application.cpp
Labels: Client, Development Approved, Project Approved

#16016 BUGZ-1139: try to prevent MyAvatar from getting stuck in the floor
  interface/src/Application.cpp
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyCharacterController.cpp
  interface/src/avatar/MyCharacterController.h
  libraries/physics/src/CharacterController.cpp
  libraries/physics/src/CharacterController.h
  libraries/physics/src/PhysicsEngine.cpp
  libraries/physics/src/PhysicsEngine.h
  libraries/physics/src/TemporaryPairwiseCollisionFilter.cpp
  libraries/physics/src/TemporaryPairwiseCollisionFilter.h
  libraries/shared/src/PhysicsHelpers.h
Labels: Development Approved, Engine, Project Approved

#16080 BUGZ-1275 Additional Grapics API info was added to the system info, which overflowed the amount of info that could be sent in a packet.
  libraries/networking/src/NodeList.cpp
Labels: Development Approved, Metaverse, Project Approved, bug

#16082 DEV-417: Add User-Agent string to macOS Launcher
  launchers/darwin/CMakeLists.txt
  launchers/darwin/src/CredentialsRequest.m
  launchers/darwin/src/DownloadDomainContent.m
  launchers/darwin/src/DownloadInterface.m
  launchers/darwin/src/DownloadLauncher.m
  launchers/darwin/src/DownloadScripts.m
  launchers/darwin/src/LatestBuildRequest.m
  launchers/darwin/src/OrganizationRequest.m
Labels: Client, Development Approved, Project Approved

#16083 DEV-418: Add version to UserAgent on Win launcher
  launchers/win32/LauncherManager.cpp
  launchers/win32/LauncherManager.h
Labels: Client, Development Approved, Project Approved

#16087 Add platform to Mac Launcher's user-agent string
  launchers/darwin/CMakeLists.txt
Labels: Client, Development Approved, Project Approved

#16088 BUGZ-1327: Fix PTT icon when PTTing and clipping
  interface/resources/qml/hifi/simplifiedUI/inputDeviceButton/InputDeviceButton.qml
  interface/resources/qml/hifi/simplifiedUI/inputDeviceButton/images/mic-ptt-clip-i.svg
Labels: Development Approved, Project Approved, UI/UX, bug

#16081 DEV-336: Fixes for avatar-verify failures with rapid avatar selection
  assignment-client/src/avatars/AvatarMixer.cpp
  assignment-client/src/avatars/AvatarMixer.h
  assignment-client/src/avatars/AvatarMixerClientData.cpp
  assignment-client/src/avatars/MixerAvatar.cpp
  assignment-client/src/avatars/MixerAvatar.h
Labels: Development Approved, Metaverse, Project Approved

#16072 BUGZ-1156: Improve sphere collapsing mode
  libraries/physics/src/MultiSphereShape.cpp
  libraries/physics/src/MultiSphereShape.h
Labels: Avatar, Development Approved, Engine, Project Approved

#16090 Fix formatting in API docs (DOC-112, DOC-113, DOC-142, DOC-143)
  tools/jsdoc/hifi-jsdoc-template/static/styles/jsdoc.css
Labels: JSDocs, Project Approved

#16089 Push To Talk Bugs 1207/1208
  interface/resources/qml/hifi/audio/Audio.qml
  interface/src/scripting/Audio.cpp
Labels: Development Approved, Project Approved, UI/UX, bug

#16065 BUGZ-186: Make sure joint names are unique
  libraries/model-baker/src/model-baker/PrepareJointsTask.cpp
Labels: Avatar, Development Approved, Project Approved

#16091 BUGZ-1265: Don't allow reactions refcount go bellow 0
  interface/src/avatar/MyAvatar.cpp
Labels: Avatar, Development Approved, Project Approved

#16086 BUGZ-1170: improved render bounding box for PolyLines, and use opaque render pipeline when possible
  libraries/entities-renderer/src/RenderableEntityItem.h
  libraries/entities-renderer/src/RenderablePolyLineEntityItem.cpp
  libraries/entities-renderer/src/RenderablePolyLineEntityItem.h
  libraries/entities-renderer/src/entities-renderer/paintStroke.slp
  libraries/entities-renderer/src/paintStroke.slf
  libraries/entities/src/PolyLineEntityItem.cpp
  libraries/entities/src/PolyLineEntityItem.h
  libraries/render-utils/src/DeferredBufferWrite.slh
Labels: Development Approved, Engine, Project Approved

#16038 DEV-256: Add build tags to Windows launcher
  launchers/win32/LauncherManager.cpp
  launchers/win32/LauncherManager.h
  launchers/win32/LauncherUtils.cpp
  launchers/win32/LauncherUtils.h
Labels: Development Approved, Project Approved, QA Approved :tada:

#16092 Fix for PTT not working
  interface/src/scripting/Audio.cpp
Labels: Development Approved, Project Approved, bug

#16111 Remove android build dependency on jherico/hifi fork
  android/docker/Dockerfile
Labels: Development Approved, Project Approved

#16106 BUGZ-1325 prevent MyAvatar from pushing through mesh barrier
  interface/src/avatar/MyAvatar.cpp
  libraries/physics/src/CharacterController.cpp
  libraries/physics/src/CharacterController.h
Labels: Development Approved, Engine, Project Approved

#16115 Attempt to fix crash from script running too late
  libraries/script-engine/src/ScriptEngine.cpp
Labels: Development Approved, Engine, Project Approved

#16105 CASE DEV-186: HQ Launcher/Interface Icons and wording need to be standardized
  cmake/macros/SetPackagingParameters.cmake
  interface/CMakeLists.txt
  interface/icon/interface-beta.icns
  interface/icon/interface-beta.ico
  interface/icon/interface.icns
  interface/icon/interface.ico
  interface/src/Application.cpp
  interface/src/main.cpp
Labels: DO NOT MERGE, Development Approved, Engine, Project Approved

#16117 BUGZ-1316: Fix crashes in Assets API
  libraries/script-engine/src/AssetScriptingInterface.cpp
Labels: Development Approved, Metaverse, Project Approved

#16114 DEV-457: Add HIFI_THUNDER_URL to win32 launcher
  launchers/win32/LauncherManager.cpp
Labels: Development Approved, Project Approved

#16119 do not unzip or parse entities-backup on message thread
  domain-server/src/DomainServer.cpp
Labels: Metaverse, Project Approved, bug

#16116 BUGZ-1274: Use UTC with QDateTime rather than local time in AccountManager
  libraries/networking/src/AccountManager.cpp
Labels: Development Approved, Metaverse, Project Approved

#16126 BUGZ-1386: Update simplifiedStatusIndicator to use domainID as org name instead of location.hostname
  scripts/simplifiedUI/ui/simplifiedStatusIndicator/simplifiedStatusIndicator.js
Labels: Development Approved, Project Approved, UI/UX

#16113 BUGZ-1363: crash when checking for web content restrictions
  interface/src/ui/InteractiveWindow.cpp
  libraries/ui/src/QmlWindowClass.cpp
  libraries/ui/src/ui/types/ContextAwareProfile.cpp
  libraries/ui/src/ui/types/ContextAwareProfile.h
  libraries/ui/src/ui/types/FileTypeProfile.cpp
  libraries/ui/src/ui/types/HFWebEngineProfile.cpp
  libraries/ui/src/ui/types/RequestFilters.cpp
  libraries/ui/src/ui/types/RequestFilters.h
Labels: Development Approved, Engine, Project Approved

#16103 DOC-64: ScriptDiscoveryService API JSDoc
  libraries/script-engine/src/ScriptEngine.h
  libraries/script-engine/src/ScriptEngines.cpp
  libraries/script-engine/src/ScriptEngines.h
  libraries/script-engine/src/ScriptsModel.h
  libraries/script-engine/src/ScriptsModelFilter.h
  tools/jsdoc/hifi-jsdoc-template/tmpl/container.tmpl
Labels: Development Approved, JSDocs, Project Approved
