Repository highfidelity/hifi, pull requests merged in 2019-06, with the labels that each got.

#15663 BUGZ-328: Some microphones are unable to hear themselves in test mic audio setting
  libraries/audio-client/src/AudioClient.cpp
  libraries/audio-client/src/AudioClient.h
  libraries/audio/src/avx2/AudioSRC_avx2.cpp
Labels: Client, Development Approved, Project Approved, bug

#15666 Allow microphone permission when debugging on the Mac
  cmake/modules/MacOSXBundleInfo.plist.in
Labels: Client, Development Approved, Mac Required, Project Approved, bug

#15668 BUGZ-197, BUGZ-372: Fix some transparency issues on AMD
  libraries/entities-renderer/src/RenderableImageEntityItem.cpp
  libraries/entities-renderer/src/RenderableShapeEntityItem.cpp
  libraries/render-utils/src/ShadingModel.slh
Labels: Development Approved, Engine, Project Approved

#15669 Bug fix for crash in QScriptEngine::reportAdditionalMemoryCost()
  cmake/ports/bullet3/portfile.cmake
  hifi_vcpkg.py
  libraries/script-engine/src/ArrayBufferClass.cpp
  libraries/script-engine/src/ScriptEngine.cpp
  tools/qt-builder/README.md
  tools/qt-builder/patches/qtscript-crash-fix.patch
  tools/qt-builder/prepare-windows-symbols-for-backtrace.py
Labels: Development Approved, Project Approved

#15672 BUGZ-395: Updated build of Qt WASAPI audio plugin with symbols
  cmake/externals/wasapi/CMakeLists.txt
Labels: Client, Project Approved, Windows Required

#15670 BUGZ-467 and BUGZ-488 : Fixing buggy performance preset setup behavior
  interface/src/Application.cpp
  interface/src/PerformanceManager.cpp
  interface/src/PerformanceManager.h
  interface/src/scripting/PerformanceScriptingInterface.cpp
  interface/src/scripting/PerformanceScriptingInterface.h
  interface/src/scripting/PlatformInfoScriptingInterface.h
  interface/src/scripting/RenderScriptingInterface.cpp
  interface/src/scripting/RenderScriptingInterface.h
  scripts/developer/utilities/lib/jet/qml/TaskPropView.qml
  scripts/developer/utilities/lib/prop/PropEnum.qml
  scripts/developer/utilities/lib/prop/style/Global.qml
  scripts/developer/utilities/lib/prop/style/PiCanvasIcon.qml
  scripts/developer/utilities/lib/prop/style/PiCheckBox.qml
  scripts/developer/utilities/lib/prop/style/PiComboBox.qml
  scripts/developer/utilities/lib/prop/style/PiFolderPanel.qml
  scripts/developer/utilities/render/luci/PerformanceSettings.qml
  scripts/developer/utilities/render/luci/Platform.qml
  scripts/developer/utilities/render/performanceSetup.qml
Labels: Development Approved, Engine, Project Approved

#15673 Don't send AvatarIdentity from mixer if socket inactive
  assignment-client/src/avatars/AvatarMixer.cpp
Labels: Development Approved, Metaverse

#15667 DEV-100: High Fidelity windows build guide updates
  BUILD_WIN.md
Labels: Development Approved, Documentation, Project Approved

#15675 Resolve DEV-99: Remove all menus from top bar
  scripts/simplifiedUI/ui/simplifiedUI.js
Labels: Development Approved, Project Approved, QA Ready (internal), UI/UX

#15585 Logging for DomainList reception & timebox overruns
  libraries/networking/src/NodeList.cpp
  libraries/networking/src/udt/Socket.cpp
Labels: Development Approved, Metaverse, Project Approved

#15664 BUGZ-516: last-heard-from monitoring on domain server
  domain-server/src/AssetsBackupHandler.cpp
  domain-server/src/DomainContentBackupManager.cpp
  domain-server/src/DomainServer.cpp
  domain-server/src/DomainServer.h
  libraries/networking/src/SequenceNumberStats.cpp
  libraries/networking/src/udt/Socket.cpp
Labels: Development Approved, Metaverse

#15674 Quiet some warnings
  debian/patches/hifi_use_system_qt.diff
  interface/src/Application.cpp
  interface/src/avatar/MyAvatar.h
  libraries/animation/src/AnimationCache.cpp
  libraries/avatars-renderer/src/avatars-renderer/Head.cpp
  libraries/entities-renderer/src/RenderableGizmoEntityItem.h
  libraries/entities-renderer/src/RenderableMaterialEntityItem.h
  libraries/entities-renderer/src/RenderablePolyLineEntityItem.cpp
  libraries/entities-renderer/src/RenderablePolyLineEntityItem.h
  libraries/entities/src/EntityTree.cpp
  libraries/fbx/src/FBXSerializer_Node.cpp
  libraries/image/src/image/Image.h
  libraries/material-networking/src/material-networking/TextureCache.h
  libraries/networking/src/LimitedNodeList.cpp
  libraries/networking/src/LimitedNodeList.h
  libraries/render-utils/src/AmbientOcclusionEffect.cpp
  libraries/shared/src/GizmoType.h
  libraries/shared/src/MaterialMappingMode.h
Labels: Development Approved, Engine, Project Approved

#15680 BUGZ-471: Support AirPods on MacOS
  libraries/audio-client/src/AudioClient.cpp
Labels: Client, Development Ready, Project Approved, bug

#15679 DOC-76: Polish Uuid JSDoc
  interface/src/ui/overlays/Overlays.h
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
  libraries/controllers/src/controllers/ScriptingInterface.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityScriptingInterface.h
  libraries/networking/src/AddressManager.h
  libraries/script-engine/src/ScriptEngine.h
  libraries/script-engine/src/ScriptUUID.h
  libraries/shared/src/RegisteredMetaTypes.h
Labels: JSDocs, Project Approved

#15678 DOC-75: Polish Users JSDoc
  libraries/script-engine/src/UsersScriptingInterface.h
Labels: JSDocs, Project Approved

#15683 Remove mac warnings from HQ Launcher.
  launchers/darwin/src/DownloadDomainContent.h
  launchers/darwin/src/DownloadDomainContent.m
  launchers/darwin/src/DownloadInterface.h
  launchers/darwin/src/DownloadInterface.m
  launchers/darwin/src/ProcessScreen.m
  launchers/darwin/src/main.mm
Labels: Development Approved, Project Approved

#15682 BUGZ-530: Rename 'System Sounds' to 'UI FX'
  interface/resources/qml/hifi/audio/Audio.qml
  interface/resources/qml/hifi/simplifiedUI/settingsApp/audio/Audio.qml
Labels: Development Approved, Project Approved, QA Ready (internal), UI/UX

#15677 Log socket error string when socket error happens
  libraries/networking/src/LimitedNodeList.cpp
  libraries/networking/src/udt/Socket.cpp
Labels: Development Approved, Metaverse, Project Approved

#15684 DOC-78: Polish Vec3 JSDoc
  libraries/script-engine/src/Vec3.h
  libraries/shared/src/RegisteredMetaTypes.h
Labels: JSDocs, Project Approved

#15681 DEV-77: Enable mac launcher builds
  launchers/darwin/CMakeLists.txt
  launchers/darwin/src/OrganizationRequest.m
  launchers/win32/CMakeLists.txt
  launchers/win32/LauncherDlg.cpp
  tools/ci-scripts/postbuild.py
Labels: Development Approved, Project Approved

#15691 DEV-113: Remove headphones icon from status indicator in top bar
  interface/resources/qml/hifi/simplifiedUI/topBar/SimplifiedTopBar.qml
  interface/resources/qml/hifi/simplifiedUI/topBar/images/focus.svg
Labels: Development Approved, Project Approved, QA Ready (internal), UI/UX

#15686 BUGZ-442: Adding extra check when setting Performance & render api enums
  interface/src/PerformanceManager.cpp
  interface/src/PerformanceManager.h
  interface/src/RefreshRateManager.cpp
  interface/src/RefreshRateManager.h
  interface/src/scripting/RenderScriptingInterface.cpp
  interface/src/scripting/RenderScriptingInterface.h
  scripts/developer/utilities/lib/prop/PropBool.qml
  scripts/developer/utilities/lib/prop/PropEnum.qml
  scripts/developer/utilities/lib/prop/PropItem.qml
  scripts/developer/utilities/lib/prop/PropScalar.qml
  scripts/developer/utilities/render/luci/Framebuffer.qml
  scripts/developer/utilities/render/luci/PerformanceSettings.qml
  scripts/developer/utilities/render/performanceSetup.qml
Labels: Development Approved, Engine, Project Approved

#15690 Fixing mac luancher bugs.
  launchers/darwin/src/CredentialsRequest.m
  launchers/darwin/src/DownloadInterface.m
  launchers/darwin/src/OrganizationRequest.m
Labels: Development Approved, Project Approved

#15696 Fix BUGZ-201: Prevent MUTED banner from being cut off when muted on startup
  interface/src/ui/InteractiveWindow.cpp
Labels: Development Approved, Engine, Project Approved, QA Ready (internal)

#15693 (BUGZ-559) Improve transition debugging and transition clean-up
  interface/resources/icons/statusIconAtlas.svg
  interface/src/avatar/AvatarManager.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities-renderer/src/RenderablePolyVoxEntityItem.cpp
  libraries/render-utils/src/FadeEffectJobs.cpp
  libraries/render/src/render/DrawStatus.cpp
  libraries/render/src/render/Item.h
  libraries/render/src/render/Scene.cpp
  libraries/render/src/render/Scene.h
  libraries/render/src/render/TransitionStage.h
Labels: Development Approved, Engine, Project Approved

#15688 DEV-94: Push to Talk
  interface/resources/qml/hifi/simplifiedUI/inputDeviceButton/InputDeviceButton.qml
Labels: Development Approved, Project Approved, QA Ready (internal), UI/UX

#15687 Dissectors: Limit message number & position values
  tools/dissectors/1-hfudt.lua
Labels: Development Approved, Metaverse, Packet Dissectors, Project Approved

#15697 Fix spurious error from prebuilt script
  prebuild.py
Labels: Development Approved, Project Approved

#15699 BUGZ-373, BUGZ-407: Put avatar spheres in R3 in simulation
  interface/src/avatar/OtherAvatar.cpp
Labels: Development Approved, Engine, Project Approved

#15704 case BUGZ-566: don't hang if somehow setting display plugin to the current one
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.cpp
Labels: Development Approved, Engine, Project Approved

#15692 Windows Launcher Fixes
  launchers/win32/LauncherDlg.cpp
  launchers/win32/LauncherDlg.h
  launchers/win32/LauncherManager.cpp
  launchers/win32/LauncherManager.h
  launchers/win32/LauncherUtils.cpp
  launchers/win32/LauncherUtils.h
Labels: Development Approved, Project Approved

#15706 (BUGZ-429) Fix stuck transition due to removing sub render items before parent
  libraries/render/src/render/Scene.cpp
Labels: Development Approved, Engine, Project Approved

#15555 Case 22352: gltf walking, bounding, collision
  libraries/fbx/src/GLTFSerializer.cpp
Labels: Development Approved, Engine, Project Approved

#15695 BUGZ-346: QML Logspam
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  interface/src/scripting/AudioDevices.h
  libraries/shared/src/shared/Camera.h
Labels: Development Approved, Project Approved, QA Ready (internal), UI/UX, bug

#15703 case : BUGZ 560: disabling dde initialization due to random crashes while closing down…
  interface/src/Application.cpp
  interface/src/devices/DdeFaceTracker.h
  interface/src/ui/PreferencesDialog.cpp
Labels: Development Approved, Engine

#15711 DEV-108: Removed ctrl+b and ctrl+n as shortcuts
  interface/resources/qml/hifi/Desktop.qml
  interface/src/Application.cpp
Labels: Development Approved, Project Approved, QA Ready (internal), UI/UX

#15714 Fix crash using Settings in the Tablet in VR
  interface/resources/qml/hifi/tablet/TabletMenuStack.qml
Labels: Development Approved, UI/UX

#15712 case BUGS:560 . wrapping dependencyManager::get<ddeFacetracker>with ifdef
  interface/src/Application.cpp
Labels: Development Approved, Engine, Project Approved

#15715 BUGZ-399: Fix shutdown crash in AudioInjectorManager::stop()
  interface/src/Application.cpp
Labels: Client, Critical Fix, Development Approved, Project Approved, bug

#15710 BUGZ-596: Fix baking of light maps
  libraries/entities-renderer/src/RenderableMaterialEntityItem.cpp
  libraries/entities-renderer/src/RenderableShapeEntityItem.cpp
  libraries/entities/src/MaterialEntityItem.h
  libraries/graphics-scripting/src/graphics-scripting/Forward.h
  libraries/graphics-scripting/src/graphics-scripting/GraphicsScriptingInterface.cpp
  libraries/graphics-scripting/src/graphics-scripting/ScriptableModel.cpp
  libraries/graphics/src/graphics/Material.cpp
  libraries/graphics/src/graphics/Material.h
  libraries/graphics/src/graphics/MaterialTextures.slh
  libraries/material-networking/src/material-networking/MaterialCache.cpp
  libraries/material-networking/src/material-networking/MaterialCache.h
  libraries/render-utils/src/MeshPartPayload.cpp
  libraries/render-utils/src/RenderPipelines.cpp
  libraries/render/src/render/ShapePipeline.h
Labels: Development Approved, Engine, Scripting API change

#15705 BUGZ-588: MAC LAUNCHER: We can not run from inside of the DMG
  launchers/darwin/src/Launcher.h
  launchers/darwin/src/Launcher.m
Labels: Development Approved, Project Approved

#15717 BUGZ-297: QT - Crash when opening a menu that spawns a desktop popup window while in VR (running scripts, settings, etc)
  interface/resources/qml/hifi/tablet/Edit.qml
  interface/resources/qml/hifi/tablet/EditTools.qml
  interface/resources/qml/hifi/tablet/TabletAudioBuffers.qml
  interface/resources/qml/hifi/tablet/TabletAvatarPreferences.qml
  interface/resources/qml/hifi/tablet/TabletGeneralPreferences.qml
  interface/resources/qml/hifi/tablet/TabletGraphicsPreferences.qml
  interface/resources/qml/hifi/tablet/TabletLodPreferences.qml
  interface/resources/qml/hifi/tablet/TabletNetworkingPreferences.qml
Labels: Development Approved, Engine, Project Approved

#15694 BUGZ-516 - attempt to rebind bound sockets on silent domain checkin
  libraries/networking/src/NodeList.cpp
  libraries/networking/src/udt/Socket.cpp
Labels: Development Approved, Metaverse, Project Approved

#15718 case #BUGZ-608: App Shutdown toolbar undefined crash
  scripts/simplifiedUI/ui/simplifiedUI.js
Labels: Client, Development Ready

#15719 BUGZ-545: Possible fix for Mac PolyLine-related crash
  libraries/entities-renderer/src/RenderablePolyLineEntityItem.h
Labels: Development Approved, Engine, Project Approved

#15698 BUGZ-544: Refine the LOD manager target rate with the Refreshrate current target
  interface/resources/qml/+android_interface/Stats.qml
  interface/resources/qml/Stats.qml
  interface/src/LODManager.cpp
  interface/src/PerformanceManager.cpp
  interface/src/RefreshRateManager.cpp
  interface/src/RefreshRateManager.h
  interface/src/ui/Stats.cpp
  interface/src/ui/Stats.h
  libraries/platform/src/platform/backend/MACOSPlatform.cpp
  libraries/platform/src/platform/backend/MACOSPlatform.h
  libraries/platform/src/platform/backend/PlatformInstance.cpp
  libraries/platform/src/platform/backend/PlatformInstance.h
  scripts/developer/utilities/render/lodWindow.js
Labels: Development Approved, Engine, Project Approved, Scripting API change

#15713 case BUGZ-599: CREATE app will now recognize newer-style baked models and skyboxes as baked in entity-list
  scripts/system/libraries/entityList.js
Labels: Create, Development Approved, Project Approved

#15722 (BUGZ-563) Fix crash using null DisplayPlugin in GraphicsEngine
  interface/src/graphics/GraphicsEngine.cpp
Labels: Development Approved, Engine, Project Approved

#15725 Crash fix for ResourceCache::getResource()
  libraries/networking/src/ResourceCache.cpp
Labels: Beware: Threading/Deadlock, Development Approved, Engine

#15723 BUGZ-627: don't divide by zero if a grid entity-item has a zero dimension
  libraries/render-utils/src/GeometryCache.cpp
Labels: Development Approved, Engine, Project Approved

#15726 BUGZ-511: fix crash in MyAvatar::updateStaleAvatarEntityBlobs()
  interface/src/avatar/MyAvatar.cpp
Labels: Development Approved, Engine, Project Approved

#15728 Adjust run and jog anims to better align head with 1p camera
  interface/resources/avatar/animations/jog_fwd.fbx
  interface/resources/avatar/animations/run_fwd.fbx
  interface/resources/avatar/avatar-animation.json
Labels: Avatar, Development Approved, Project Approved

#15689 DEV-77: Light launcher Windows build
  launchers/darwin/CMakeLists.txt
  launchers/win32/CMakeLists.txt
  tools/ci-scripts/postbuild.py
Labels: Project Approved

#15730 BUGZ-631: Don't normalize zero vector in flipNormalsMyAvatarVsBackfacingTriangles
  libraries/physics/src/PhysicsEngine.cpp
Labels: Development Approved, Engine, Project Approved

#15731 Implement BUGZ-226: Forward keypresses made while Top Bar is in focus
  interface/resources/qml/hifi/simplifiedUI/topBar/SimplifiedTopBar.qml
  interface/src/ui/InteractiveWindow.cpp
  interface/src/ui/InteractiveWindow.h
Labels: Development Approved, Project Approved, QA Ready (internal), UI/UX

#15729 AvatarData: Fix avatarDataByteArray max size computation
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
Labels: Avatar, Development Approved, Metaverse

#15732 BUGZ-638: simplified UI must work correctly on clean install from launcher
  interface/src/Application.cpp
  launchers/darwin/src/Launcher.m
Labels: Development Approved, Project Approved

#15734 Implement BUGZ-633: Change 'Graphics Preset'
  interface/resources/qml/hifi/simplifiedUI/settingsApp/general/General.qml
Labels: Development Approved, Project Approved, QA Ready (internal), UI/UX

#15736 BUGZ-610: Auto-select the first avatar from your inventory if you have avatars in your inventory
  interface/resources/qml/hifi/simplifiedUI/topBar/SimplifiedTopBar.qml
Labels: Development Approved, Project Approved, QA Ready (internal), UI/UX

#15733 Load simplifiedUI using the windows launcher
  launchers/win32/LauncherApp.cpp
  launchers/win32/LauncherApp.h
  launchers/win32/LauncherDlg.cpp
  launchers/win32/LauncherDlg.h
  launchers/win32/LauncherManager.cpp
  launchers/win32/LauncherManager.h
  launchers/win32/LauncherUtils.cpp
  launchers/win32/LauncherUtils.h
  launchers/win32/res/button.png
Labels: Development Approved, Project Approved

#15735 DEV-118: Add signing for the windows launcher
  tools/ci-scripts/postbuild.py
Labels: Development Approved, Project Approved

#15738 DEV-118: More logging on signing / non-signing conditional
  tools/ci-scripts/postbuild.py
Labels: Development Approved, Project Approved

#15720 Verbose logging 2
  libraries/networking/src/udt/Socket.cpp
Labels: Development Approved, Metaverse, Project Approved

#15737 DEV-122: Add a developer menu in Settings
  interface/resources/qml/hifi/simplifiedUI/settingsApp/SettingsApp.qml
  interface/resources/qml/hifi/simplifiedUI/settingsApp/dev/Dev.qml
Labels: Development Approved, Development Ready, Project Approved, QA Ready (internal), UI/UX

#15676 DOC-33: MyAvatar API JSDoc catch-up
  assignment-client/src/avatars/ScriptableAvatar.h
  interface/src/avatar/MyAvatar.h
  libraries/avatars/src/AvatarData.h
Labels: JSDocs, Project Approved

#15741 BUGZ-484: Add --setBookmark and getAddress API
  interface/src/Application.cpp
  interface/src/Bookmarks.h
  interface/src/LocationBookmarks.cpp
  interface/src/LocationBookmarks.h
  interface/src/main.cpp
Labels: Development Approved, Project Approved

#15743 BUGZ-592: Lilypad Launcher (Mac): Upon Login Standard/Common Shortcuts Not Enabled
  launchers/darwin/nib/Window.xib
  launchers/darwin/src/CustomUI.m
  launchers/darwin/src/main.mm
Labels: Development Approved, Project Approved

#15742 Add mutex for Socket::_connectionsHash
  libraries/networking/src/udt/Socket.cpp
  libraries/networking/src/udt/Socket.h
Labels: Development Approved, Metaverse, Project Approved, bug

#15700 DOC-63: Tablet JSDoc
  interface/resources/qml/hifi/tablet/TabletButton.qml
  interface/resources/qml/hifi/toolbars/ToolbarButton.qml
  libraries/ui/src/ui/TabletScriptingInterface.cpp
  libraries/ui/src/ui/TabletScriptingInterface.h
Labels: JSDocs, Project Approved

#15721 BUGZ-623: Quiet asan gpu stats
  interface/src/ui/Stats.h
  libraries/gpu-gl-common/src/gpu/gl/GLBackendPipeline.cpp
  libraries/gpu/src/gpu/Context.cpp
  libraries/gpu/src/gpu/Context.h
  libraries/render/src/render/EngineStats.h
Labels: Development Approved, Engine, Project Approved

#15745 BUGZ-355: Persistent UI Element
  scripts/simplifiedUI/ui/simplifiedUI.js
Labels: Development Ready, Project Approved, UI/UX

#15724 dev-79: Lilypad Launcher: (Mac) Implement the error state page.
  launchers/darwin/src/DownloadDomainContent.m
  launchers/darwin/src/DownloadInterface.m
Labels: Development Approved, Project Approved

#15749 BUGZ-656 & DEV-126: updating org url and trim whitespace for org and username
  launchers/darwin/src/CredentialsRequest.m
  launchers/darwin/src/OrganizationRequest.m
Labels: Development Approved, Project Approved

#15750 Windows Launcher fixes and updates
  launchers/win32/LauncherDlg.cpp
  launchers/win32/LauncherDlg.h
  launchers/win32/LauncherManager.cpp
  launchers/win32/LauncherManager.h
  launchers/win32/LauncherUtils.cpp
  launchers/win32/LauncherUtils.h
Labels: Development Approved, Project Approved

#15751 DEV-128: Update settings screen with latest design
  interface/resources/qml/hifi/simplifiedUI/avatarApp/AvatarApp.qml
  interface/resources/qml/hifi/simplifiedUI/avatarApp/images/accent.svg
  interface/resources/qml/hifi/simplifiedUI/settingsApp/SettingsApp.qml
  interface/resources/qml/hifi/simplifiedUI/settingsApp/audio/Audio.qml
  interface/resources/qml/hifi/simplifiedUI/settingsApp/dev/Dev.qml
  interface/resources/qml/hifi/simplifiedUI/settingsApp/general/General.qml
  interface/resources/qml/hifi/simplifiedUI/settingsApp/images/accent1.svg
  interface/resources/qml/hifi/simplifiedUI/settingsApp/images/accent2.svg
  interface/resources/qml/hifi/simplifiedUI/settingsApp/images/accent3.svg
  interface/resources/qml/hifi/simplifiedUI/settingsApp/vr/VR.qml
  interface/resources/qml/hifi/simplifiedUI/simplifiedConstants/SimplifiedConstants.qml
Labels: Development Approved, Project Approved, UI/UX

#15746 BUGZ-628 - Add quasi-MTBF logging to track disconnects
  domain-server/src/DomainGatekeeper.cpp
  domain-server/src/DomainServer.cpp
  domain-server/src/DomainServer.h
  domain-server/src/NodeConnectionData.cpp
  domain-server/src/NodeConnectionData.h
  libraries/networking/src/LimitedNodeList.cpp
  libraries/networking/src/LimitedNodeList.h
  libraries/networking/src/NodeList.cpp
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
  libraries/networking/src/udt/Socket.cpp
Labels: Development Approved, Metaverse, Packet Version Change, Project Approved

#15752 BUGZ-666: Toolbar Artifact Always Present
  interface/resources/qml/hifi/Desktop.qml
  libraries/ui/src/OffscreenUi.cpp
  libraries/ui/src/ui/ToolbarScriptingInterface.h
  scripts/simplifiedUI/ui/simplifiedUI.js
Labels: Development Approved, PRE-MERGE TESTING REQUIRED, QA Approved :tada:

#15756 BUGZ-543:Fix avatar picking not working on some avatars
  interface/src/avatar/AvatarManager.cpp
Labels: Development Approved, Engine, Project Approved

#15760 BUGZ-671: Make 'Your Profile' Home button go to bookmark 'hqhome'
  interface/resources/qml/hifi/simplifiedUI/avatarApp/AvatarApp.qml
Labels: Development Approved, Project Approved, UI/UX

#15759 BUGZ-658: Don't let the user switch avatar models to Woody
  interface/resources/qml/hifi/simplifiedUI/topBar/SimplifiedTopBar.qml
Labels: Development Approved, PRE-MERGE TESTING REQUIRED, Project Approved, UI/UX, bug

#15757 DEV-124 : Windows Launcher add Home Bookmark parameter
  launchers/win32/LauncherManager.cpp
Labels: Development Approved, Project Approved

#15754 BUGZ-512: avoid MacOS crash on shutdown: destroy WebSurfaces before exit
  interface/src/Application.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities-renderer/src/RenderableWebEntityItem.cpp
  libraries/entities-renderer/src/RenderableWebEntityItem.h
  libraries/entities/src/WebEntityItem.cpp
Labels: Development Approved, Engine, Project Approved

#15758 DEV-123 & BUGZ-602: Adding bookmark arg and making launcher appear on top
  launchers/darwin/src/Launcher.m
Labels: Development Approved, Project Approved

#15763 BUGZ-676: Remove references to interstitial from SUI version of progress.js
  scripts/simplifiedUI/system/progress.js
Labels: Development Approved, Project Approved, UI/UX, bug

#15755 BUGZ-637: Detecting the problematic GPU on MAC not running properly Deferred render method right now
  interface/src/PerformanceManager.cpp
  libraries/platform/src/platform/Profiler.cpp
  libraries/platform/src/platform/Profiler.h
  libraries/shared/src/GPUIdent.cpp
  scripts/developer/utilities/render/luci.qml
  scripts/developer/utilities/render/performanceSetup.qml
Labels: Development Approved, Engine, Project Approved

#15764 BUGZ-512: rollback fixes for bugz512
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities-renderer/src/RenderableWebEntityItem.cpp
  libraries/entities-renderer/src/RenderableWebEntityItem.h
Labels: Critical Fix, Development Approved, Engine, Project Approved

#15766 DEV-132 : Update window launcher icon
  launchers/win32/res/interface.ico
Labels: Development Approved, Project Approved

#15768 DEV-133: Update mac launcher icon
  launchers/darwin/images/interface.icns
Labels: Development Approved, Project Approved

#15769 Increased bottom margin on muted overlay
  scripts/simplifiedUI/ui/simplifiedUI.js
Labels: Development Approved, Project Approved, UI/UX, bug

#15762 BUGZ-531: Quest tablet login missing keyboard
  BUILD.md
  interface/resources/qml/LoginDialog.qml
  interface/resources/qml/dialogs/TabletLoginDialog.qml
  libraries/ui/src/ui/OffscreenQmlSurface.cpp
Labels: Development Approved, Engine, Project Approved, Quest Required

#15770 BUGZ-658: Actually write some code that doesn't let the user switch avatar models to Woody
  interface/resources/qml/hifi/simplifiedUI/topBar/SimplifiedTopBar.qml
Labels: Development Approved, PRE-MERGE TESTING REQUIRED, Project Approved, UI/UX, bug

#15767 BUGZ-686: fix drawcalls stat broken in pr-15721
  interface/src/ui/Stats.h
Labels: Development Approved, Engine, Project Approved

#15765 stop rebinding
  libraries/networking/src/NodeList.cpp
  libraries/networking/src/udt/Socket.cpp
Labels: Development Approved, Metaverse, Project Approved, bug

#15772 BUGZ-694: Excluding all Intel gpu on mac from being deferred capable
  libraries/platform/src/platform/Profiler.cpp
Labels: Development Approved, Engine, Project Approved

#15771 BUGZ-696 Drop non DS UDP packets when silent domain checkins exceeds 3 seconds
  domain-server/src/DomainServer.cpp
  libraries/networking/src/DomainHandler.cpp
  libraries/networking/src/LimitedNodeList.cpp
  libraries/networking/src/LimitedNodeList.h
  libraries/networking/src/NodeList.cpp
Labels: Development Approved, Metaverse, Project Approved

#15777 BUGZ-707: HQ Launcher says "lastest and greatest"
  launchers/darwin/src/ProcessScreen.m
Labels: Development Approved, Project Approved

#15775 BUGZ-702: fix crash in btCollisionWorld on shutdown
  interface/src/avatar/AvatarManager.cpp
  interface/src/avatar/AvatarManager.h
  interface/src/avatar/MyCharacterController.cpp
  interface/src/avatar/MyCharacterController.h
  interface/src/avatar/OtherAvatar.cpp
  interface/src/avatar/OtherAvatar.h
Labels: Development Approved, Engine, Project Approved

#15778 DEV-142 & DEV-140: Scrollbars in Your Profile and Settings
  interface/resources/qml/InteractiveWindow.qml
  interface/resources/qml/hifi/simplifiedUI/avatarApp/AvatarApp.qml
  interface/resources/qml/hifi/simplifiedUI/settingsApp/SettingsApp.qml
  interface/resources/qml/hifi/simplifiedUI/settingsApp/audio/Audio.qml
  interface/resources/qml/hifi/simplifiedUI/settingsApp/dev/Dev.qml
  interface/resources/qml/hifi/simplifiedUI/settingsApp/general/General.qml
  interface/resources/qml/hifi/simplifiedUI/settingsApp/vr/VR.qml
  interface/resources/qml/hifi/simplifiedUI/simplifiedConstants/SimplifiedConstants.qml
  interface/resources/qml/hifi/simplifiedUI/simplifiedControls/VerticalScrollBar.qml
Labels: Critical Fix, Development Approved, Project Approved, UI/UX

#15779 bugz-709: don't try to create collision shape before compound shape resource is finished loading
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
Labels: Development Approved, Engine, Project Approved, bug

#15782 BUGZ-699: Make PSFListModel fetch early when making container bigger
  interface/resources/qml/hifi/models/PSFListModel.qml
  interface/resources/qml/hifi/models/qmldir
Labels: Development Approved, Project Approved, UI/UX, bug

#15784 BUGZ-685: StatusIndicator is yellow in specific cases
  scripts/simplifiedUI/ui/simplifiedStatusIndicator/simplifiedStatusIndicator.js
Labels: Development Approved, Project Approved, UI/UX, bug

#15781 BUGZ-693: Renaming HQ Launcher on Mac OS breaks the bundle
  launchers/darwin/CMakeLists.txt
  launchers/darwin/cmake/modules/MacOSXBundleInfo.plist.in
Labels: Development Approved, Development Ready, Project Approved

#15783 Improvement to Developer > Avatar > Draw Animation
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  libraries/animation/src/AnimClip.cpp
  libraries/animation/src/AnimNode.h
  libraries/animation/src/Rig.cpp
  libraries/animation/src/Rig.h
Labels: Avatar, Development Approved, Project Approved, Scripting API change

#15787 Updated readme with new cmake
  BUILD_WIN.md
Labels: Development Ready, Project Approved

#15790 Implement an "About" tab in the Settings app
  interface/resources/qml/hifi/simplifiedUI/settingsApp/SettingsApp.qml
  interface/resources/qml/hifi/simplifiedUI/settingsApp/about/About.qml
  interface/resources/qml/hifi/simplifiedUI/settingsApp/about/images/logo.png
Labels: Development Ready, Project Approved, UI/UX

#15788 Fix UBSan warnings due to SIMD intrinsics
  libraries/audio/src/AudioReverb.cpp
  libraries/audio/src/AudioSRC.cpp
Labels: Development Approved, Project Approved

#15791 BUGZ-732: Enable text selection by mouse in Profile/Display Name field
  interface/resources/qml/hifi/simplifiedUI/avatarApp/components/DisplayNameHeader.qml
Labels: Development Approved, Project Approved, UI/UX, bug

#15793 BUGZ-742: Q_OBJECT and template classes don't mix
  libraries/shared/src/Preferences.h
Labels: Development Approved, Engine

#15796 BUGZ-730: Fix deferred rendering on macbook air
  libraries/render-utils/src/DeferredBufferWrite.slh
  libraries/render-utils/src/DeferredLightingEffect.cpp
  libraries/render-utils/src/DeferredLightingEffect.h
  libraries/render-utils/src/deferred_light.slv
Labels: Development Approved, Engine, Mac Required, Project Approved

#15708 Force new IP port on local address change
  domain-server/src/DomainServer.cpp
  libraries/networking/src/LimitedNodeList.cpp
  libraries/networking/src/udt/Socket.cpp
Labels: Development Approved, Metaverse, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#15794 Limit the stats-dump rate on packet error
  libraries/networking/src/LimitedNodeList.cpp
  libraries/networking/src/LimitedNodeList.h
Labels: Development Approved, Metaverse, Project Approved

#15798 BUGZ-721: nitpick: [mac] preserve symlinks when installing interface.app
  tools/nitpick/src/TestRunnerDesktop.cpp
Labels: Development Approved, Project Approved, nitpick

#15789 JIRA 659-Create App shows a File not found message in the Properties and Grid Tab
  interface/resources/qml/controls/qmldir
  interface/resources/qml/hifi/dialogs/qmldir
  interface/resources/qml/hifi/toolbars/qmldir
  scripts/system/create/Edit.qml
  scripts/system/create/EditEntityList.qml
  scripts/system/create/EditTabButton.qml
  scripts/system/create/EditTabView.qml
  scripts/system/create/EditTools.qml
  scripts/system/create/EditToolsTabView.qml
  scripts/system/create/EntityList.qml
  scripts/system/create/NewEntityButton.qml
  scripts/system/create/NewMaterialDialog.qml
  scripts/system/create/NewMaterialWindow.qml
  scripts/system/create/NewModelDialog.qml
  scripts/system/create/NewModelWindow.qml
  scripts/system/create/create-icons/126-material-01.svg
  scripts/system/create/create-icons/20-text-01.svg
  scripts/system/create/create-icons/21-cube-01.svg
  scripts/system/create/create-icons/22-sphere-01.svg
  scripts/system/create/create-icons/23-zone-01.svg
  scripts/system/create/create-icons/24-light-01.svg
  scripts/system/create/create-icons/25-web-1-01.svg
  scripts/system/create/create-icons/90-particles-01.svg
  scripts/system/create/create-icons/94-model-01.svg
  scripts/system/create/create-icons/image.svg
  scripts/system/edit.js
  scripts/system/libraries/entityList.js
Labels: Create, Development Approved, QA Approved :tada:, bug

#15792 Bugz-504: more stable nametag updates
  scripts/simplifiedUI/ui/simplifiedNametag/resources/modules/nameTagListManager.js
  scripts/simplifiedUI/ui/simplifiedNametag/simplifiedNametag.js
Labels: Development Approved, Project Approved, QA Ready

#15797 BUGZ-271: Android gamma correction is too high
  libraries/display-plugins/src/display-plugins/Basic2DWindowOpenGLDisplayPlugin.cpp
  libraries/display-plugins/src/display-plugins/Basic2DWindowOpenGLDisplayPlugin.h
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.cpp
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.h
  libraries/pointers/src/PickManager.cpp
  plugins/oculus/src/OculusDisplayPlugin.cpp
  plugins/oculus/src/OculusDisplayPlugin.h
Labels: Development Approved, Engine, HMD required, QA Ready, Quest Required, Windows Required

#15785 Quest optimization
  libraries/pointers/src/PickManager.cpp
Labels: DO NOT MERGE, Engine

#15748 DOC-85: Revise new MyAvatar signals' JSDoc
  interface/src/avatar/MyAvatar.h
Labels: JSDocs, Project Approved

#15800 BUGZ-402: Don't request an OpenGL 2.0 context via the dock widget
  libraries/ui/src/DockWidget.cpp
Labels: Development Approved, Engine, Project Approved

#15799 BUGZ-516 - add OS type to connect message for logging
  domain-server/src/DomainGatekeeper.cpp
  domain-server/src/NodeConnectionData.cpp
  domain-server/src/NodeConnectionData.h
  libraries/networking/src/NodeList.cpp
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
Labels: Development Approved, Metaverse, Packet Version Change

#15801 A null recording clip should be considered an error
  libraries/recording/src/recording/ClipCache.cpp
  libraries/script-engine/src/RecordingScriptingInterface.cpp
Labels: Development Approved, Project Approved, bug

#15802 Small warning fix
  libraries/display-plugins/src/display-plugins/Basic2DWindowOpenGLDisplayPlugin.cpp
Labels: Development Approved, Engine

#15804 DEV-146, BUGZ-747: Add one call in PlatformInfo::getPlatform() returning the complete description of the platform
  interface/src/scripting/PlatformInfoScriptingInterface.cpp
  interface/src/scripting/PlatformInfoScriptingInterface.h
  libraries/platform/src/platform/Platform.h
  libraries/platform/src/platform/PlatformKeys.h
  libraries/platform/src/platform/backend/AndroidPlatform.cpp
  libraries/platform/src/platform/backend/AndroidPlatform.h
  libraries/platform/src/platform/backend/LinuxPlatform.cpp
  libraries/platform/src/platform/backend/LinuxPlatform.h
  libraries/platform/src/platform/backend/MACOSPlatform.cpp
  libraries/platform/src/platform/backend/MACOSPlatform.h
  libraries/platform/src/platform/backend/Platform.cpp
  libraries/platform/src/platform/backend/PlatformInstance.cpp
  libraries/platform/src/platform/backend/PlatformInstance.h
  libraries/platform/src/platform/backend/WINPlatform.cpp
  libraries/platform/src/platform/backend/WINPlatform.h
  libraries/shared/src/GPUIdent.cpp
Labels: Development Approved, Engine, Project Approved, Scripting API change

#15803 BUGZ-703: Possible fix for do_setPipeline crash and other Mac fixes
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.cpp
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.h
  libraries/display-plugins/src/display-plugins/hmd/HmdDisplayPlugin.cpp
  libraries/display-plugins/src/display-plugins/hmd/HmdDisplayPlugin.h
  libraries/physics/src/PhysicalEntitySimulation.cpp
  libraries/physics/src/ThreadSafeDynamicsWorld.cpp
  libraries/plugins/src/plugins/DisplayPlugin.cpp
  libraries/plugins/src/plugins/DisplayPlugin.h
  libraries/render-utils/src/RenderCommonTask.cpp
  libraries/render/src/render/Args.h
Labels: Development Ready, Engine, Project Approved

#15805 BUGZ-777: Clean up SharedObject code
  CMakeLists.txt
  libraries/gl/src/gl/Context.cpp
  libraries/gl/src/gl/Context.h
  libraries/qml/src/qml/impl/RenderEventHandler.cpp
  libraries/qml/src/qml/impl/SharedObject.cpp
  libraries/qml/src/qml/impl/SharedObject.h
  libraries/qml/src/qml/impl/TextureCache.h
Labels: Beware: Threading/Deadlock, Development Approved, Engine, Project Approved

#15808 Add more detail logging to mac launcher
  launchers/darwin/src/LatestBuildRequest.m
Labels: Development Ready, Project Approved

#15809 BUGZ-776 : Detect AMD gpu on more than one possible token
  libraries/platform/src/platform/backend/PlatformInstance.cpp
Labels: Development Approved, Engine, Project Approved

#15807 BUGZ-512: fix MacOS crash in FakeAudioInputStream on domain-change and shutdown
  interface/src/Application.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities-renderer/src/RenderableWebEntityItem.cpp
Labels: Development Approved, Engine, Project Approved

#15812 Add extra logging to Windows launcher
  launchers/win32/LauncherDlg.cpp
  launchers/win32/LauncherManager.cpp
  launchers/win32/LauncherUtils.cpp
Labels: Development Approved, Project Approved

#15814 Disable handTouch.js to prevent finger twitching
  interface/resources/qml/AnimStats.qml
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  interface/src/ui/AnimStats.cpp
  interface/src/ui/AnimStats.h
  libraries/animation/src/Rig.cpp
  libraries/animation/src/Rig.h
  scripts/simplifiedUI/system/controllers/handTouch.js
  scripts/system/controllers/handTouch.js
Labels: Avatar, Development Approved

#15811 Emergency fix to restore create in non-launcher builds
  scripts/system/create/NewMaterialDialog.qml
  scripts/system/create/NewModelDialog.qml
Labels: Create, Critical Fix, Development Approved, Development Ready, Project Approved, QA Approved :tada:

#15810 BUGS 665: Audio client crash on timer during shutdown
  interface/src/Application.cpp
  libraries/audio-client/src/AudioClient.cpp
Labels: Development Ready, Engine, Project Approved

#15816 BUGZ-761 Add locks to OctreeEditPacketSender to protect various members
  libraries/octree/src/OctreeEditPacketSender.cpp
  libraries/octree/src/OctreeEditPacketSender.h
Labels: Development Approved, Metaverse, bug

#15818 (BUGZ-619) Fix potential crash when ending script on main thread
  libraries/script-engine/src/ScriptEngine.cpp
Labels: Development Approved, Engine, Project Approved

#15817 BUGZ-734: Possible fix for black shape issue
  libraries/entities-renderer/src/RenderableShapeEntityItem.cpp
  libraries/entities-renderer/src/RenderableShapeEntityItem.h
Labels: Development Approved, Engine

#15820 Actually fix BUGZ-657.
  scripts/simplifiedUI/ui/simplifiedUI.js
Labels: Client, Development Approved, Project Approved, UI/UX, bug

#15829 BUGZ-746: About tab: Better CPU/GPU info reporting; New copied info (including OS version)
  interface/resources/qml/hifi/simplifiedUI/settingsApp/about/About.qml
  interface/resources/qml/hifi/simplifiedUI/simplifiedControls/Button.qml
Labels: Development Approved, Project Approved, UI/UX

#15830 BUGZ-771: Prevent duplicates from accumulating in EntityTree::_needsParentFixup
  libraries/entities/src/EntityTree.cpp
Labels: Development Approved, Project Approved

#15828 BUGZ-812 - Log system info on domain connect or connect refusal
  domain-server/src/DomainGatekeeper.cpp
  domain-server/src/NodeConnectionData.cpp
  libraries/networking/CMakeLists.txt
  libraries/networking/src/NodeList.cpp
  libraries/networking/src/ThreadedAssignment.cpp
  libraries/networking/src/ThreadedAssignment.h
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
  libraries/platform/CMakeLists.txt
Labels: Development Approved, Metaverse, Packet Version Change, Project Approved

#15831 BUGZ-774: Lilypad Launcher (Mac) text issue
  launchers/darwin/cmake/modules/MacOSXBundleInfo.plist.in
  launchers/darwin/nib/DisplayNameScreen.xib
  launchers/darwin/src/DisplayNameScreen.m
Labels: Client, Development Approved, Project Approved

#15834 BUGZ-811: Fix bugs in EntityTreeRenderer::updateChangedEntities
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.h
  libraries/shared/src/PrioritySortUtil.h
Labels: Development Approved, Engine, Project Approved

#15824 A couple macOS HQ Launcher bug fixes
  launchers/darwin/CMakeLists.txt
  launchers/darwin/src/Interface.h
  launchers/darwin/src/Interface.m
  launchers/darwin/src/LatestBuildRequest.m
Labels: Development Approved, Project Approved

#15825 Blendshape CPU optimization
  libraries/render-utils/src/Model.cpp
  libraries/shared/src/avx2/BlendshapePacking_avx2.cpp
  tests/shared/src/BlendshapePackingTests.cpp
  tests/shared/src/BlendshapePackingTests.h
Labels: Client, Development Approved, Engine, Project Approved

#15837 DEV-170: Increase the speed of the animation when clicking between tabs in Settings
  interface/resources/qml/hifi/simplifiedUI/settingsApp/SettingsApp.qml
Labels: Development Approved, Project Approved, UI/UX

#15833 Fix aspect ratio of splash logo in win32 launcher
  launchers/win32/LauncherDlg.cpp
Labels: Development Approved, Project Approved

#15832 BUGZ-710: Update win32 launcher with working ToS link
  launchers/win32/Launcher.rc
  launchers/win32/LauncherDlg.cpp
  launchers/win32/LauncherDlg.h
  launchers/win32/resource.h
Labels: Development Approved, Project Approved

#15838 Fix Mac crash caused by PR#15825
  libraries/render-utils/src/Model.cpp
  libraries/shared/src/avx2/BlendshapePacking_avx2.cpp
Labels: Development Approved, Engine, Project Approved, bug

#15823 DOC-79: Entities JSDoc Update
  interface/src/avatar/AvatarActionFarGrab.h
  interface/src/avatar/AvatarActionHold.cpp
  interface/src/scripting/TestScriptingInterface.h
  libraries/entities/src/AmbientLightPropertyGroup.h
  libraries/entities/src/AnimationPropertyGroup.cpp
  libraries/entities/src/BloomPropertyGroup.h
  libraries/entities/src/EntityDynamicInterface.cpp
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityScriptingInterface.h
  libraries/entities/src/EntityTypes.h
  libraries/entities/src/GrabPropertyGroup.h
  libraries/entities/src/HazePropertyGroup.h
  libraries/entities/src/KeyLightPropertyGroup.h
  libraries/entities/src/PolyVoxEntityItem.h
  libraries/entities/src/PulsePropertyGroup.h
  libraries/entities/src/RingGizmoPropertyGroup.h
  libraries/entities/src/ShapeEntityItem.cpp
  libraries/entities/src/SkyboxPropertyGroup.h
  libraries/material-networking/src/material-networking/MaterialCache.cpp
  libraries/octree/src/OctreeScriptingInterface.h
  libraries/physics/src/ObjectActionOffset.cpp
  libraries/physics/src/ObjectActionTractor.cpp
  libraries/physics/src/ObjectActionTravelOriented.cpp
  libraries/physics/src/ObjectConstraintBallSocket.cpp
  libraries/physics/src/ObjectConstraintConeTwist.cpp
  libraries/physics/src/ObjectConstraintHinge.cpp
  libraries/physics/src/ObjectConstraintSlider.cpp
  libraries/physics/src/ObjectDynamic.cpp
  libraries/script-engine/src/ScriptEngine.cpp
  libraries/script-engine/src/ScriptEngine.h
  libraries/shared/src/BillboardMode.h
  libraries/shared/src/ComponentMode.cpp
  libraries/shared/src/GizmoType.h
  libraries/shared/src/PointerEvent.cpp
  libraries/shared/src/PrimitiveMode.h
  libraries/shared/src/PulseMode.h
  libraries/shared/src/RegisteredMetaTypes.h
  libraries/shared/src/RenderLayer.h
  libraries/shared/src/ShapeInfo.cpp
  libraries/shared/src/SpatiallyNestable.cpp
  libraries/shared/src/WebInputMode.h
Labels: Development Approved, JSDocs, Project Approved

#15822 BUGZ-664: Introduce scaling of rendering for forward renderer
  interface/resources/qml/Stats.qml
  interface/src/Application.cpp
  interface/src/Menu.cpp
  interface/src/Menu.h
  interface/src/scripting/RenderScriptingInterface.cpp
  interface/src/scripting/RenderScriptingInterface.h
  interface/src/ui/PreferencesDialog.cpp
  interface/src/ui/Stats.cpp
  libraries/plugins/src/plugins/DisplayPlugin.h
  libraries/render-utils/src/DeferredLightingEffect.cpp
  libraries/render-utils/src/DeferredLightingEffect.h
  libraries/render-utils/src/RenderCommonTask.cpp
  libraries/render-utils/src/RenderCommonTask.h
  libraries/render-utils/src/RenderDeferredTask.cpp
  libraries/render-utils/src/RenderDeferredTask.h
  libraries/render-utils/src/RenderForwardTask.cpp
  libraries/render-utils/src/RenderForwardTask.h
  libraries/render-utils/src/RenderHUDLayerTask.cpp
  libraries/render-utils/src/RenderHUDLayerTask.h
  libraries/render-utils/src/ToneMappingEffect.cpp
  libraries/render-utils/src/ToneMappingEffect.h
  libraries/render/src/render/ResampleTask.cpp
  libraries/render/src/render/ResampleTask.h
  scripts/developer/utilities/lib/prop/PropGroup.qml
  scripts/developer/utilities/lib/prop/PropScalar.qml
  scripts/developer/utilities/render/luci/Platform.qml
  scripts/developer/utilities/render/luci/RenderSettings.qml
Labels: Development Approved, Engine, Project Approved, Scripting API change

#15840 BUGZ-837: Fix Launcher crash (mac)
  launchers/darwin/src/LatestBuildRequest.m
  launchers/darwin/src/main.mm
Labels: Client, Development Approved, Project Approved

#15815 BUGZ-765: Snaps Photos are Dark
  libraries/display-plugins/src/display-plugins/Basic2DWindowOpenGLDisplayPlugin.cpp
  libraries/display-plugins/src/display-plugins/Basic2DWindowOpenGLDisplayPlugin.h
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.cpp
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.h
  plugins/oculus/src/OculusDisplayPlugin.cpp
  plugins/oculus/src/OculusDisplayPlugin.h
Labels: Development Approved, Engine, Project Approved
