Repository highfidelity/hifi, pull requests merged in 2019-10, with the labels that each got.

#16268 DEV-2125: Rotation while seated do not trigger re-centering
  interface/src/avatar/MyAvatar.cpp
Labels: Avatar, Development Approved, Project Approved

#16254 BUGZ-1117: On Mac OS, disable App Nap to prevent audio glitches
  interface/CMakeLists.txt
  interface/src/AppNapDisabler.h
  interface/src/AppNapDisabler.mm
  interface/src/Application.cpp
Labels: Client, Development Approved, Mac Required, Project Approved, QA Approved :tada:

#16245 DEV-442: Implement directional blending node for point reaction
  interface/resources/avatar/animations/emote_point01_aimoffsets.fbx
  interface/resources/avatar/animations/sitting_emote_point_aimoffsets.fbx
  interface/resources/avatar/avatar-animation.json
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  scripts/simplifiedUI/simplifiedEmote/simplifiedEmote.js
Labels: Avatar, Development Approved, Project Approved, Scripting API change

#16271 DEV-2121: Restore previous control keys for look at camera
  interface/resources/controllers/keyboardMouse.json
Labels: Avatar, Development Approved, Project Approved

#16272 Fix for avatars that are stuck in idle pose for observers
  libraries/animation/src/Rig.h
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
Labels: Avatar, Development Approved, Project Approved

#16263 (DEV-654) Define ShapeVertices in model preparation step
  libraries/model-baker/src/model-baker/Baker.cpp
  libraries/model-baker/src/model-baker/BakerTypes.h
  libraries/model-baker/src/model-baker/BuildGraphicsMeshTask.cpp
  libraries/model-baker/src/model-baker/BuildGraphicsMeshTask.h
  libraries/model-baker/src/model-baker/CollectShapeVerticesTask.cpp
  libraries/model-baker/src/model-baker/CollectShapeVerticesTask.h
  libraries/model-baker/src/model-baker/ReweightDeformersTask.cpp
  libraries/model-baker/src/model-baker/ReweightDeformersTask.h
Labels: Engine

#16274 dev- 470: Audio device rename and reduction of audio output spam
  interface/src/scripting/AudioDevices.cpp
  libraries/audio-client/src/AudioClient.cpp
Labels: Development Approved, Development Ready, Engine, Project Approved

#16276 DEV-2275: Move 'input device muted' banner and make it slightly smaller
  scripts/simplifiedUI/ui/simplifiedUI.js
Labels: Development Approved, Project Approved, UI/UX

#16277 Fix skinning deformer data always being added to graphics::Mesh
  libraries/model-baker/src/model-baker/ReweightDeformersTask.cpp
Labels: Engine

#16267 DEV-625: Free Look Camera in first person mode
  interface/src/Application.cpp
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
Labels: Avatar, Development Approved, Project Approved

#16269 DEV-1898: Make Assets.initializeCache() script i/f blocking
  libraries/script-engine/src/AssetScriptingInterface.cpp
  libraries/script-engine/src/AssetScriptingInterface.h
Labels: Development Approved, Project Approved

#16273 DEV-1836 - handle urls in the form 'hifi://<domain>:<port>
  libraries/networking/src/AddressManager.cpp
Labels: Development Approved, Project Approved

#16279 (DEV-559) Update FBXSerializer to reference shapes (deformers WIP)
  libraries/fbx/src/FBXSerializer.cpp
  libraries/fbx/src/FBXSerializer.h
  libraries/fbx/src/FBXSerializer_Mesh.cpp
  libraries/hfm/src/hfm/HFM.h
  libraries/model-baker/src/model-baker/CollectShapeVerticesTask.cpp
Labels: Engine

#16291 DEV-2202: Apply same random factors to both eyes blink
  libraries/avatars-renderer/src/avatars-renderer/Head.cpp
Labels: Avatar, Development Approved, Project Approved

#16293 DEV-2044 - add notification that temporary domains won't show up in domain list
  domain-server/resources/web/settings/js/settings.js
Labels: Development Approved, Metaverse, Project Approved

#16284 DEV-653 - give warning not to change address for cloud domains
  domain-server/resources/web/js/shared.js
  domain-server/resources/web/settings/js/settings.js
Labels: Development Approved, Metaverse, Project Approved

#16283 DEV-2217: Fix MyAvatar::isInAir() so takes into account the new seated state
  interface/src/avatar/MyAvatar.cpp
Labels: Avatar, Development Approved, Project Approved

#16278 DEV-2291: Add audio input entitlement to mac launcher
  launchers/darwin/HQ Launcher.entitlements
Labels: Client, Development Approved, Project Approved

#16285 DEV-2292: Alerting requirements for domain-server failure cases
  domain-server/src/DomainServer.cpp
  libraries/networking/src/AccountManager.cpp
  libraries/networking/src/LimitedNodeList.cpp
Labels: Development Approved, Feedback Welcome, Metaverse

#16246 BUGZ-711: Clarify frustum property values used by Entities.findEntitiesInFrustum()
  libraries/entities/src/EntityScriptingInterface.h
Labels: Client, JSDocs

#16298 DEV-2011: Add MyAvatar::isSeated API method
  interface/src/avatar/MyAvatar.h
Labels: Avatar, Development Approved, Project Approved, Scripting API change

#16266 DOC-107: Fix description of entity acceleraton property and deprecate
  libraries/entities/src/EntityItemProperties.cpp
Labels: Development Approved, JSDocs

#16300 Fix for Mat4.getForward, getRight and getUp
  libraries/script-engine/src/Mat4.cpp
  scripts/developer/tests/mat4test.js
Labels: Avatar, Client, Development Approved, Project Approved

#16221 DEV-611: Ensure that entities with the link property set can be clicked in Desktop and VR modes
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
Labels: Client, Development Approved, HMD required, Project Approved, QA Approved :tada:, UI/UX

#16295 DEV-2309: Report ESS stats to domain server
  assignment-client/src/scripts/EntityScriptServer.cpp
Labels: Development Approved, Metaverse, Project Approved

#16299 DOC-187: Mat4 JSDoc
  libraries/script-engine/src/Mat4.h
Labels: Development Approved, JSDocs

#16275 Sit variants and fidgets
  interface/resources/avatar/animations/sitting_idle02.fbx
  interface/resources/avatar/animations/sitting_idle04.fbx
  interface/resources/avatar/animations/sitting_idle05.fbx
  interface/resources/avatar/animations/sitting_idle_once_fidget.fbx
  interface/resources/avatar/animations/sitting_idle_once_leanforward.fbx
  interface/resources/avatar/animations/sitting_idle_once_lookaround.fbx
  interface/resources/avatar/animations/sitting_idle_once_lookfidget.fbx
  interface/resources/avatar/animations/sitting_idle_once_lookleftright.fbx
  interface/resources/avatar/animations/sitting_idle_once_shakelegs.fbx
  interface/resources/avatar/animations/sitting_idle_once_shifting.fbx
  interface/resources/avatar/animations/sitting_idle_once_shiftweight.fbx
  interface/resources/avatar/avatar-animation.json
Labels: Avatar, Development Approved, Project Approved, QA Approved :tada:

#16251 DOC-155: EntityViewer JSDoc
  assignment-client/src/entities/EntityTreeHeadlessViewer.h
  assignment-client/src/octree/OctreeHeadlessViewer.h
  libraries/entities/src/EntityScriptingInterface.h
Labels: JSDocs

#16166 DOC-159: File JSDoc
  libraries/script-engine/src/FileScriptingInterface.h
Labels: JSDocs

#16303 DOC-188: Steam JSDoc
  libraries/plugins/src/plugins/SteamClientPlugin.h
Labels: JSDocs

#16261 BUGZ-491: Fix tablet.loadWebScreenOnTop()
  libraries/ui/src/ui/TabletScriptingInterface.cpp
  libraries/ui/src/ui/TabletScriptingInterface.h
Labels: Client, Development Approved, Project Approved, Scripting API change

#16224 DOC-110, DOC-111, DOC-167: JSDoc fixes and tidying
  interface/src/FancyCamera.h
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  interface/src/raypick/PickScriptingInterface.cpp
  interface/src/raypick/PickScriptingInterface.h
  interface/src/raypick/PointerScriptingInterface.h
  interface/src/scripting/AccountServicesScriptingInterface.h
  interface/src/scripting/ControllerScriptingInterface.h
  interface/src/scripting/DesktopScriptingInterface.cpp
  interface/src/scripting/MenuScriptingInterface.h
  interface/src/scripting/SelectionScriptingInterface.cpp
  interface/src/scripting/WalletScriptingInterface.h
  interface/src/scripting/WindowScriptingInterface.h
  interface/src/ui/InteractiveWindow.h
  interface/src/ui/overlays/Overlays.cpp
  libraries/animation/src/AnimInverseKinematics.h
  libraries/animation/src/AnimOverlay.h
  libraries/animation/src/IKTarget.h
  libraries/animation/src/Rig.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
  libraries/controllers/src/controllers/Actions.cpp
  libraries/controllers/src/controllers/StandardController.cpp
  libraries/controllers/src/controllers/impl/MappingBuilderProxy.h
  libraries/controllers/src/controllers/impl/RouteBuilderProxy.h
  libraries/entities/src/EntityDynamicInterface.cpp
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityScriptingInterface.h
  libraries/entities/src/EntityTypes.h
  libraries/input-plugins/src/input-plugins/KeyboardMouseDevice.cpp
  libraries/midi/src/Midi.h
  libraries/networking/src/AddressManager.h
  libraries/networking/src/MessagesClient.h
  libraries/script-engine/src/Quat.h
  libraries/script-engine/src/ScriptEngine.cpp
  libraries/ui/src/ui/TabletScriptingInterface.h
  tools/jsdoc/hifi-jsdoc-template/static/styles/jsdoc.css
  tools/jsdoc/hifi-jsdoc-template/tmpl/container.tmpl
  tools/jsdoc/hifi-jsdoc-template/tmpl/description.tmpl
  tools/jsdoc/hifi-jsdoc-template/tmpl/details.tmpl
  tools/jsdoc/hifi-jsdoc-template/tmpl/example.tmpl
  tools/jsdoc/hifi-jsdoc-template/tmpl/members.tmpl
  tools/jsdoc/hifi-jsdoc-template/tmpl/method.tmpl
  tools/jsdoc/hifi-jsdoc-template/tmpl/methodList.tmpl
  tools/jsdoc/hifi-jsdoc-template/tmpl/params.tmpl
  tools/jsdoc/hifi-jsdoc-template/tmpl/properties.tmpl
  tools/jsdoc/hifi-jsdoc-template/tmpl/signal.tmpl
  tools/jsdoc/hifi-jsdoc-template/tmpl/signalList.tmpl
Labels: JSDocs

#16311 DEV-2352: Modify Release Notes URL
  interface/src/Menu.cpp
Labels: Development Approved, Project Approved, Release Blocker, UI/UX

#16310 DEV-2261: DEV-2320: Fix strafe while flying, and ramp up diagonal movement
  interface/src/avatar/MyAvatar.cpp
Labels: Avatar, Development Approved, Project Approved, Release Blocker

#16312 DEV-2350: Prevent duplicate default scripts from running
  scripts/defaultScripts.js
Labels: Client, Development Approved, Project Approved, Release Blocker

#16308 DOC-189: SpeechRecognizer JSDoc
  interface/src/SpeechRecognizer.h
Labels: JSDocs

#16309 DEV-2329: Identify Alerting requirements for Assignment Client reliable operation
  assignment-client/src/AssignmentClient.cpp
  assignment-client/src/AssignmentFactory.cpp
  libraries/networking/src/LimitedNodeList.cpp
Labels: Development Approved, Metaverse, Project Approved

#16313 Added flag to ensure mouse event signals are not connected twice
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.h
  scripts/system/controllers/controllerDispatcher.js
Labels: Development Approved, Project Approved, UI/UX, bug

#16296 DEV-2117: new version of webrtc library for osx
  cmake/ports/webrtc/portfile.cmake
Labels: Development Approved, Engine, Mac Required, PRE-MERGE TESTING REQUIRED, QA Approved :tada:

#16316 DEV-2285: Fix eye look at forward vector
  interface/src/avatar/MyAvatar.cpp
Labels: Avatar, Development Approved, Project Approved

#16314 DEV-841: Fix oculus calibration screen crash if touch is not turned on
  plugins/oculus/src/OculusControllerManager.cpp
  plugins/oculus/src/OculusControllerManager.h
Labels: Client, Development Approved, Project Approved, QA Approved :tada:

#16315 Qt 5.13 changes
  assignment-client/src/AssignmentClientMonitor.cpp
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/main.cpp
  libraries/display-plugins/src/display-plugins/CompositorHelper.cpp
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.cpp
  libraries/display-plugins/src/display-plugins/hmd/HmdDisplayPlugin.cpp
  libraries/entities/src/EntityScriptingInterface.cpp
  libraries/fbx/src/GLTFSerializer.cpp
  libraries/image/src/image/Image.cpp
  libraries/networking/src/HifiSockAddr.cpp
  libraries/networking/src/HifiSockAddr.h
  libraries/networking/src/LimitedNodeList.cpp
  libraries/networking/src/udt/Socket.cpp
  libraries/render-utils/src/text/Font.cpp
  libraries/shared/src/MovingPercentile.cpp
  libraries/shared/src/SharedUtil.cpp
  libraries/task/src/task/Config.h
  libraries/ui/src/InfoView.cpp
  libraries/ui/src/MainWindow.cpp
Labels: Development Approved, Engine, Project Approved

#16319 force LOD to be 20-20 on android, and force lodAngleDeg to 0.248
  scripts/+android_interface/defaultScripts.js
Labels: Development Approved, Project Approved

#16306 DEV-2374: Add serverless content back to launcher builds
  tools/ci-scripts/postbuild.py
Labels: Client, Development Approved

#16318 dev-2082/cannot-click-yourself-in-third-person-for-nametag
  scripts/simplifiedUI/ui/simplifiedNametag/resources/modules/nameTagListManager.js
Labels: Development Approved, Project Approved, QA Approved :tada:, UI/UX

#16301 Drivekey anim triggers
  interface/resources/avatar/avatar-animation.json
  interface/src/avatar/MySkeletonModel.cpp
  libraries/animation/src/Rig.cpp
  libraries/animation/src/Rig.h
Labels: Avatar, Development Approved, Project Approved

#16326 DEV-2379: Modify Shadow-related tooltips in Create
  scripts/system/create/assets/data/createAppTooltips.json
Labels: Client, Development Approved, Project Approved, UI/UX

#16325 DEV-2386: Remove 'Run Client Script Test'
  interface/src/Menu.cpp
  interface/src/Menu.h
  interface/src/ui/DialogsManager.cpp
  interface/src/ui/DialogsManager.h
Labels: Development Approved, Project Approved, UI/UX

#16307 DEV-1811: apply deletion rules to linked entities
  interface/src/InterfaceParentFinder.cpp
  interface/src/avatar/AvatarManager.cpp
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/OtherAvatar.cpp
  interface/src/ui/AvatarCertifyBanner.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.h
  libraries/entities-renderer/src/RenderableEntityItem.cpp
  libraries/entities/src/DeleteEntityOperator.cpp
  libraries/entities/src/DeleteEntityOperator.h
  libraries/entities/src/EntityEditFilters.cpp
  libraries/entities/src/EntityEditFilters.h
  libraries/entities/src/EntityEditPacketSender.cpp
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityScriptingInterface.cpp
  libraries/entities/src/EntitySimulation.cpp
  libraries/entities/src/EntitySimulation.h
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/EntityTree.h
  libraries/entities/src/EntityTreeElement.cpp
  libraries/entities/src/SimpleEntitySimulation.cpp
  libraries/entities/src/SimpleEntitySimulation.h
  libraries/physics/src/EntityMotionState.cpp
  libraries/physics/src/EntityMotionState.h
  libraries/physics/src/PhysicalEntitySimulation.cpp
  libraries/physics/src/PhysicalEntitySimulation.h
  libraries/shared/src/PhysicsHelpers.cpp
  libraries/shared/src/SpatialParentFinder.h
  tests/octree/src/ModelTests.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#16327 DEV-1901: No audio in Interface when restoring from sleep
  interface/src/Application.cpp
  libraries/audio-client/src/AudioClient.cpp
  libraries/audio-client/src/AudioClient.h
Labels: Client, Development Ready, bug

#16321 Instancing: applying the new hfm shape to create the render items of the model
  interface/resources/avatar/avatar-animation.json
  interface/src/avatar/AvatarDoctor.cpp
  interface/src/avatar/AvatarDoctor.h
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MySkeletonModel.cpp
  interface/src/raypick/CollisionPick.cpp
  interface/src/raypick/CollisionPick.h
  libraries/animation/src/Rig.cpp
  libraries/animation/src/Rig.h
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/SkeletonModel.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.h
  libraries/entities-renderer/src/RenderableParticleEffectEntityItem.cpp
  libraries/entities-renderer/src/RenderableParticleEffectEntityItem.h
  libraries/entities/src/ZoneEntityItem.cpp
  libraries/entities/src/ZoneEntityItem.h
  libraries/fbx/src/FBXSerializer.cpp
  libraries/fbx/src/FBXSerializer_Mesh.cpp
  libraries/hfm/src/hfm/HFM.h
  libraries/material-networking/src/material-networking/MaterialCache.h
  libraries/model-networking/src/model-networking/ModelCache.cpp
  libraries/model-networking/src/model-networking/ModelCache.h
  libraries/render-utils/src/CauterizedModel.cpp
  libraries/render-utils/src/MeshPartPayload.cpp
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
Labels: Engine

#16330 Fix erratic seated idles and fidgets.
  interface/resources/avatar/avatar-animation.json
Labels: Avatar, Development Approved, Project Approved

#16333 Revert "DEV-1811: apply deletion rules to linked entities"
  interface/src/InterfaceParentFinder.cpp
  interface/src/avatar/AvatarManager.cpp
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/OtherAvatar.cpp
  interface/src/ui/AvatarCertifyBanner.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.h
  libraries/entities-renderer/src/RenderableEntityItem.cpp
  libraries/entities/src/DeleteEntityOperator.cpp
  libraries/entities/src/DeleteEntityOperator.h
  libraries/entities/src/EntityEditFilters.cpp
  libraries/entities/src/EntityEditFilters.h
  libraries/entities/src/EntityEditPacketSender.cpp
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityScriptingInterface.cpp
  libraries/entities/src/EntitySimulation.cpp
  libraries/entities/src/EntitySimulation.h
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/EntityTree.h
  libraries/entities/src/EntityTreeElement.cpp
  libraries/entities/src/SimpleEntitySimulation.cpp
  libraries/entities/src/SimpleEntitySimulation.h
  libraries/physics/src/EntityMotionState.cpp
  libraries/physics/src/EntityMotionState.h
  libraries/physics/src/PhysicalEntitySimulation.cpp
  libraries/physics/src/PhysicalEntitySimulation.h
  libraries/shared/src/PhysicsHelpers.cpp
  libraries/shared/src/SpatialParentFinder.h
  tests/octree/src/ModelTests.cpp
Labels: Development Approved, Project Approved

#16332 Fix stand talk pops
  interface/resources/avatar/avatar-animation.json
Labels: Avatar, Development Approved, Project Approved

#16328 DEV-2376: Don't post account settings after pull
  libraries/networking/src/AccountManager.cpp
Labels: Development Approved, Metaverse, Project Approved, bug

#16341 fix typo
  hifi_vcpkg.py
Labels: Development Approved, Project Approved

#16340 Moved position of settings app
  scripts/simplifiedUI/ui/simplifiedUI.js
Labels: Development Approved, Project Approved, UI/UX

#16337 Added blank placeholder text on focus to text field
  interface/resources/qml/hifi/simplifiedUI/topBar/SimplifiedTopBar.qml
Labels: Development Approved, Project Approved, UI/UX, bug

#16334 RC85: DEV-2376: Don't post account settings after pull
  libraries/networking/src/AccountManager.cpp
Labels: Development Approved, Metaverse, Project Approved, bug

#16342 DEV-2334: New 'Item Invalidated' language in Inventory
  interface/resources/qml/hifi/commerce/purchases/Purchases.qml
Labels: Development Approved, Project Approved, UI/UX

#16336 DEV-1867: Fix toolbarTest.js
  libraries/ui/src/ui/ToolbarScriptingInterface.h
  scripts/developer/tests/toolbarTest.js
Labels: Client, Development Approved, JSDocs, Project Approved

#16343 DEV-2375: ensure web entities stop playing audio
  interface/resources/qml/Web3DSurface.qml
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#16344 RC85 - DEV-2375: Fix for web entity audio
  interface/resources/qml/Web3DSurface.qml
Labels: Development Approved, Engine, Project Approved

#16345 Merge master into instancing
  hifi_vcpkg.py
  interface/resources/avatar/avatar-animation.json
  interface/resources/qml/Web3DSurface.qml
  interface/resources/qml/hifi/commerce/purchases/Purchases.qml
  interface/resources/qml/hifi/simplifiedUI/topBar/SimplifiedTopBar.qml
  interface/src/Application.cpp
  interface/src/Menu.cpp
  interface/src/Menu.h
  interface/src/ui/DialogsManager.cpp
  interface/src/ui/DialogsManager.h
  libraries/audio-client/src/AudioClient.cpp
  libraries/audio-client/src/AudioClient.h
  libraries/networking/src/AccountManager.cpp
  libraries/ui/src/ui/ToolbarScriptingInterface.h
  scripts/developer/tests/toolbarTest.js
  scripts/simplifiedUI/ui/simplifiedUI.js
  scripts/system/create/assets/data/createAppTooltips.json
Labels: Engine

#16322 Add Bullet3 patch for Xcode 11 build
  cmake/ports/bullet3/bullet-git-fix-build-clang-8.patch
  cmake/ports/bullet3/portfile.cmake
  interface/src/avatar/MyAvatar.cpp
Labels: Development Approved, Project Approved

#16339 Fixed calculation of overlay position
  scripts/simplifiedUI/ui/simplifiedUI.js
Labels: Development Approved, Project Approved, UI/UX, bug

#16349 DEV-2426: Update Emote Indicator icon
  scripts/simplifiedUI/simplifiedEmote/ui/qml/images/emote_Icon.svg
Labels: Development Approved, UI/UX

#16348 fix step translate actions
  libraries/controllers/src/controllers/Actions.cpp
Labels: Development Approved, Engine

#16294 First Time User Experience Project
  interface/resources/qml/hifi/simplifiedUI/avatarApp/AvatarApp.qml
  interface/resources/qml/hifi/simplifiedUI/avatarApp/images/avatarProfilePic.png
  interface/resources/qml/hifi/simplifiedUI/avatarApp/images/hero.png
  interface/resources/qml/hifi/simplifiedUI/avatarApp/images/qrCode.jpg
  interface/resources/qml/hifi/simplifiedUI/avatarApp/images/simplifiedAvatar_Blue.png
  interface/resources/qml/hifi/simplifiedUI/avatarApp/images/simplifiedAvatar_Cyan.png
  interface/resources/qml/hifi/simplifiedUI/avatarApp/images/simplifiedAvatar_Green.png
  interface/resources/qml/hifi/simplifiedUI/avatarApp/images/simplifiedAvatar_Magenta.png
  interface/resources/qml/hifi/simplifiedUI/avatarApp/images/simplifiedAvatar_Red.png
  interface/resources/qml/hifi/simplifiedUI/avatarApp/images/simplifiedAvatar_Yellow.png
  interface/resources/qml/hifi/simplifiedUI/topBar/SimplifiedTopBar.qml
  interface/src/scripting/DesktopScriptingInterface.cpp
  interface/src/scripting/DesktopScriptingInterface.h
  interface/src/ui/InteractiveWindow.cpp
  interface/src/ui/InteractiveWindow.h
  libraries/ui/src/MainWindow.h
  scripts/simplifiedUI/simplifiedEmote/simplifiedEmote.js
  scripts/simplifiedUI/ui/simplifiedFTUE/InitialLaunchWindow.qml
  scripts/simplifiedUI/ui/simplifiedFTUE/SecondLaunchWindow.qml
  scripts/simplifiedUI/ui/simplifiedFTUE/images/cameraControls.png
  scripts/simplifiedUI/ui/simplifiedFTUE/images/defaultBottomRight.png
  scripts/simplifiedUI/ui/simplifiedFTUE/images/defaultTopLeft.png
  scripts/simplifiedUI/ui/simplifiedFTUE/images/mouseControls.png
  scripts/simplifiedUI/ui/simplifiedFTUE/images/runJumpControls.png
  scripts/simplifiedUI/ui/simplifiedFTUE/images/standOutBottomRight.png
  scripts/simplifiedUI/ui/simplifiedFTUE/images/standOutTopLeft.png
  scripts/simplifiedUI/ui/simplifiedFTUE/images/walkingControls.png
  scripts/simplifiedUI/ui/simplifiedUI.js
Labels: Development Approved, Project Approved, UI/UX

#16352 Bugfix for legacy sit scripts
  libraries/animation/src/AnimClip.h
  libraries/animation/src/Rig.cpp
Labels: Avatar, Development Approved, Project Approved, Release Blocker

#16353 RC85-Bugfix for legacy sit scripts
  libraries/animation/src/AnimClip.h
  libraries/animation/src/Rig.cpp
Labels: Avatar, Development Approved, Project Approved, Release Blocker

#16357 RC-85: Fix for HMD mode flying
  interface/src/avatar/MyAvatar.cpp
Labels: Avatar, Development Approved, Release Blocker

#16355 Fix for HMD mode flying
  interface/src/avatar/MyAvatar.cpp
Labels: Avatar, Development Approved

#16351 Fix sliding when stopping from run.
  interface/resources/avatar/avatar-animation.json
  libraries/animation/src/Rig.cpp
  libraries/animation/src/Rig.h
Labels: Avatar, Development Approved, Project Approved

#16346 New AFK "away" animation
  scripts/system/away.js
Labels: Avatar, Development Approved, Project Approved

#16358 RC-85: DEV-2316: Fix camera position in first person
  interface/src/Application.cpp
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
Labels: Avatar, Development Approved, Project Approved

#16356 DEV-2316: Fix camera position in first person
  interface/src/Application.cpp
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
Labels: Avatar, Development Ready, Project Approved

#16359 DNM: Instancing: Rendering correctly the DEFORMED hfm::SHapes
  libraries/animation/src/AnimSkeleton.cpp
  libraries/animation/src/AnimSkeleton.h
  libraries/fbx/src/FBXSerializer.cpp
  libraries/hfm/src/hfm/HFM.h
  libraries/model-baker/src/model-baker/Baker.cpp
  libraries/model-baker/src/model-baker/BuildGraphicsMeshTask.cpp
  libraries/model-baker/src/model-baker/BuildGraphicsMeshTask.h
  libraries/model-baker/src/model-baker/CollectShapeVerticesTask.cpp
  libraries/model-baker/src/model-baker/CollectShapeVerticesTask.h
  libraries/model-baker/src/model-baker/ReweightDeformersTask.cpp
  libraries/model-baker/src/model-baker/ReweightDeformersTask.h
  libraries/model-networking/src/model-networking/ModelCache.cpp
  libraries/render-utils/src/CauterizedMeshPartPayload.cpp
  libraries/render-utils/src/CauterizedMeshPartPayload.h
  libraries/render-utils/src/CauterizedModel.cpp
  libraries/render-utils/src/MeshPartPayload.cpp
  libraries/render-utils/src/MeshPartPayload.h
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
Labels: Engine

#16350 DEV-2391: Fix Recording.stopRecording() crash
  libraries/script-engine/src/RecordingScriptingInterface.cpp
Labels: Client, Development Approved, Project Approved

#16324 (DEV-561) Enable instancing for GLTF static meshes (WIP)
  libraries/fbx/src/FBXSerializer.cpp
  libraries/fbx/src/GLTFSerializer.cpp
  libraries/fbx/src/GLTFSerializer.h
  libraries/hfm/src/hfm/HFMModelMath.cpp
  libraries/hfm/src/hfm/HFMModelMath.h
  libraries/model-baker/src/model-baker/Baker.cpp
  libraries/model-baker/src/model-baker/CalculateExtentsTask.cpp
  libraries/model-baker/src/model-baker/CalculateExtentsTask.h
  libraries/model-baker/src/model-baker/CalculateMeshTangentsTask.cpp
  tests-manual/fbx/CMakeLists.txt
  tests-manual/fbx/src/main.cpp
Labels: Engine

#16365 RC85: DEV-2316: Tweak camera position in first person to further hide neck
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
Labels: Avatar, Development Approved, Project Approved

#16364 DEV-2316: Tweak camera position in first person to further hide neck
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
Labels: Avatar, Development Approved

#16362 DEV-830: Remove call to processEvents on Mac in ~Application
  interface/src/Application.cpp
Labels: Development Approved, Project Approved

#16366 DEV-830 - RC85 - Remove call to processEvents on Mac in ~Application
  interface/src/Application.cpp
Labels: Project Approved

#16368 DEV-2413: Restate legacy first person camera mode
  interface/resources/controllers/keyboardMouse.json
  interface/resources/qml/hifi/simplifiedUI/settingsApp/general/General.qml
  interface/src/Application.cpp
  interface/src/Menu.cpp
  interface/src/Menu.h
  interface/src/avatar/MyAvatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/shared/src/shared/Camera.cpp
  libraries/shared/src/shared/Camera.h
  scripts/simplifiedUI/ui/simplifiedUI.js
  scripts/system/firstPersonHMD.js
  scripts/system/interstitialPage.js
  scripts/system/libraries/WebTablet.js
  scripts/system/miniTablet.js
Labels: Avatar, Development Approved, Project Approved, Scripting API change

#16363 DEV-606: Remove excessive avatar-mixer logging
  assignment-client/src/avatars/AvatarMixerSlave.cpp
Labels: Avatar, Development Approved, Metaverse, Project Approved

#16370 DEV-2293: secondary canera shadow config should recognize performance tier restrictions
  interface/src/scripting/RenderScriptingInterface.cpp
Labels: Development Approved, Engine, Project Approved

#16376 DEV-589: Rebase our audio plugin to Qt 5.12.3 / Qt 5.13
  cmake/externals/wasapi/CMakeLists.txt
Labels: Client, Development Ready, Project Approved, QA Ready, Windows Required

#16378 (DEV-559) Move skinning reweighting code out of model prep
  libraries/fbx/src/FBXSerializer.cpp
  libraries/fbx/src/GLTFSerializer.cpp
  libraries/fbx/src/OBJSerializer.cpp
  libraries/hfm/src/hfm/HFM.h
  libraries/hfm/src/hfm/HFMModelMath.cpp
  libraries/hfm/src/hfm/HFMModelMath.h
  libraries/model-baker/src/model-baker/Baker.cpp
  libraries/model-baker/src/model-baker/BuildGraphicsMeshTask.cpp
  libraries/model-baker/src/model-baker/BuildGraphicsMeshTask.h
  libraries/model-baker/src/model-baker/CollectShapeVerticesTask.cpp
  libraries/model-baker/src/model-baker/CollectShapeVerticesTask.h
  libraries/model-baker/src/model-baker/ReweightDeformersTask.cpp
  libraries/model-baker/src/model-baker/ReweightDeformersTask.h
Labels: Engine

#16379 Merge master into instancing
  assignment-client/src/avatars/AvatarMixerSlave.cpp
  cmake/externals/wasapi/CMakeLists.txt
  interface/resources/controllers/keyboardMouse.json
  interface/resources/qml/hifi/simplifiedUI/settingsApp/general/General.qml
  interface/src/Application.cpp
  interface/src/Menu.cpp
  interface/src/Menu.h
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  interface/src/scripting/RenderScriptingInterface.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/script-engine/src/RecordingScriptingInterface.cpp
  libraries/shared/src/shared/Camera.cpp
  libraries/shared/src/shared/Camera.h
  scripts/simplifiedUI/ui/simplifiedUI.js
  scripts/system/firstPersonHMD.js
  scripts/system/interstitialPage.js
  scripts/system/libraries/WebTablet.js
  scripts/system/miniTablet.js
Labels: Engine

#16377 Instancing: Clean ups, simpler Skin Cluster(s) updates
  libraries/animation/src/AnimSkeleton.cpp
  libraries/animation/src/AnimSkeleton.h
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/fbx/src/OBJSerializer.cpp
  libraries/hfm/src/hfm/HFM.h
  libraries/model-networking/src/model-networking/ModelCache.cpp
  libraries/render-utils/src/CauterizedModel.cpp
  libraries/render-utils/src/CauterizedModel.h
  libraries/render-utils/src/MeshPartPayload.cpp
  libraries/render-utils/src/MeshPartPayload.h
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
  libraries/render-utils/src/SoftAttachmentModel.cpp
  tools/vhacd-util/src/VHACDUtil.cpp
Labels: Engine

#16380 DEV-2471: Fix an issue with InteractiveWindow anchors that caused windows without anchors to move when the Interface window geometry changes
  interface/src/scripting/DesktopScriptingInterface.cpp
  interface/src/ui/InteractiveWindow.cpp
  interface/src/ui/InteractiveWindow.h
Labels: Development Approved, Project Approved, Scripting API change, UI/UX, bug

#16383 Fix glitches when strafing left <-> right.
  interface/resources/avatar/avatar-animation.json
Labels: Avatar, Development Approved, Project Approved

#16387 Implement DEV-257: Allow scripts running on the ESS to access avatar info via the AvatarHashMap
  assignment-client/src/avatars/AvatarMixerSlave.cpp
  assignment-client/src/scripts/EntityScriptServer.cpp
Labels: Client, Development Approved, Metaverse, Project Approved, Scripting API change

#16388 Adding more detailed description of the Material properties from the material inspector tool
  scripts/developer/utilities/lib/prop/PropColor.qml
  scripts/developer/utilities/render/materialInspector.qml
Labels: Development Approved, Engine, Project Approved

#16385 DEV-2425: web video playback on OSX
  cmake/ports/hifi-deps/CONTROL
  hifi_vcpkg.py
  tests-manual/qml/qml/MacQml.qml
  tests-manual/qml/src/MacQml.cpp
  tests-manual/qml/src/MacQml.h
  tests-manual/qml/src/StressWeb.h
  tests-manual/qml/src/TestCase.h
  tests-manual/qml/src/main.cpp
  tools/qt-builder/README.md
  tools/qt-builder/patches/mac-web-video.patch
Labels: Development Approved, PRE-MERGE TESTING REQUIRED, Project Approved, bug

#16394 DEV-2541: Update 'Jump To' top bar expanded text
  interface/resources/qml/hifi/simplifiedUI/topBar/SimplifiedTopBar.qml
Labels: Development Approved, Project Approved, UI/UX

#16395 DEV-2498: Fix a crash in MenuScriptingInterface
  interface/src/scripting/MenuScriptingInterface.cpp
Labels: Development Approved, Engine, Project Approved, bug

#16347 DOC-195: Keyboard JSDoc
  interface/src/scripting/KeyboardScriptingInterface.h
Labels: JSDocs

#16396 DEV-2463: Put FTUE users in an empty serverless domain instead of the tutorial
  interface/resources/serverless/empty.json
  scripts/simplifiedUI/ui/simplifiedUI.js
Labels: Development Approved, Project Approved, UI/UX

#16386 DEV-2475: Fix head twitching when strafing
  interface/src/avatar/MyAvatar.cpp
Labels: Avatar, Development Approved, Project Approved

#16393 DEV-2521: Volume of other programs is reduced by approx 50%
  cmake/externals/wasapi/CMakeLists.txt
Labels: Client, Development Ready, Project Approved, QA Ready, Windows Required, bug

#16397 (DEV-561) First pass at skinning for GLTF
  libraries/animation/src/AnimSkeleton.cpp
  libraries/fbx/src/FBXSerializer.cpp
  libraries/fbx/src/GLTFSerializer.cpp
  libraries/fbx/src/GLTFSerializer.h
  libraries/hfm/src/hfm/HFM.h
  libraries/hfm/src/hfm/HFMModelMath.cpp
  libraries/hfm/src/hfm/HFMModelMath.h
  libraries/model-baker/src/model-baker/BuildGraphicsMeshTask.cpp
  libraries/model-baker/src/model-baker/CollectShapeVerticesTask.cpp
Labels: Engine

#16317 DEV-2285: Improve eyes look at
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  libraries/avatars-renderer/src/avatars-renderer/Head.cpp
  libraries/avatars-renderer/src/avatars-renderer/Head.h
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
  libraries/avatars/src/HeadData.h
Labels: Avatar, Development Approved, Project Approved, Scripting API change

#16372 DEV-2055: Sanitize LODManager.setWorldQualityDetail() parameter value
  interface/resources/qml/hifi/dialogs/graphics/GraphicsSettings.qml
  interface/src/Application.cpp
  interface/src/LODManager.cpp
  interface/src/LODManager.h
  interface/src/PerformanceManager.cpp
  interface/src/ui/PreferencesDialog.cpp
Labels: Development Approved, Engine, Scripting API change

#16402 (DEV-561) GLTF fixes
  libraries/animation/src/AnimSkeleton.cpp
  libraries/fbx/src/GLTFSerializer.cpp
  libraries/fbx/src/OBJSerializer.cpp
  libraries/render-utils/src/CauterizedModel.cpp
Labels: Engine

#16381 case Dev 471: HMD default audio behavior
  interface/resources/qml/hifi/simplifiedUI/settingsApp/audio/Audio.qml
  interface/resources/qml/hifi/simplifiedUI/settingsApp/vr/VR.qml
  interface/src/scripting/AudioDevices.cpp
  interface/src/scripting/AudioDevices.h
  libraries/audio-client/CMakeLists.txt
  libraries/audio-client/src/AudioClient.cpp
  libraries/audio-client/src/AudioClient.h
  libraries/audio-client/src/HifiAudioDeviceInfo.cpp
  libraries/audio-client/src/HifiAudioDeviceInfo.h
  libraries/plugins/src/plugins/PluginManager.cpp
  libraries/plugins/src/plugins/PluginManager.h
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#16404 Merge master into instancing
  assignment-client/src/avatars/AvatarMixerSlave.cpp
  assignment-client/src/scripts/EntityScriptServer.cpp
  cmake/externals/wasapi/CMakeLists.txt
  cmake/ports/hifi-deps/CONTROL
  hifi_vcpkg.py
  interface/resources/avatar/avatar-animation.json
  interface/resources/qml/hifi/dialogs/graphics/GraphicsSettings.qml
  interface/resources/qml/hifi/simplifiedUI/settingsApp/audio/Audio.qml
  interface/resources/qml/hifi/simplifiedUI/settingsApp/vr/VR.qml
  interface/resources/qml/hifi/simplifiedUI/topBar/SimplifiedTopBar.qml
  interface/resources/serverless/empty.json
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/LODManager.cpp
  interface/src/LODManager.h
  interface/src/PerformanceManager.cpp
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  interface/src/scripting/AudioDevices.cpp
  interface/src/scripting/AudioDevices.h
  interface/src/scripting/DesktopScriptingInterface.cpp
  interface/src/scripting/KeyboardScriptingInterface.h
  interface/src/scripting/MenuScriptingInterface.cpp
  interface/src/ui/InteractiveWindow.cpp
  interface/src/ui/InteractiveWindow.h
  interface/src/ui/PreferencesDialog.cpp
  libraries/audio-client/CMakeLists.txt
  libraries/audio-client/src/AudioClient.cpp
  libraries/audio-client/src/AudioClient.h
  libraries/audio-client/src/HifiAudioDeviceInfo.cpp
  libraries/audio-client/src/HifiAudioDeviceInfo.h
  libraries/avatars-renderer/src/avatars-renderer/Head.cpp
  libraries/avatars-renderer/src/avatars-renderer/Head.h
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
  libraries/avatars/src/HeadData.h
  libraries/plugins/src/plugins/PluginManager.cpp
  libraries/plugins/src/plugins/PluginManager.h
  scripts/developer/utilities/lib/prop/PropColor.qml
  scripts/developer/utilities/render/materialInspector.qml
  scripts/simplifiedUI/ui/simplifiedUI.js
  tests-manual/qml/qml/MacQml.qml
  tests-manual/qml/src/MacQml.cpp
  tests-manual/qml/src/MacQml.h
  tests-manual/qml/src/StressWeb.h
  tests-manual/qml/src/TestCase.h
  tests-manual/qml/src/main.cpp
  tools/qt-builder/README.md
  tools/qt-builder/patches/mac-web-video.patch
Labels: Engine

#16403 Remove AvatarTransit log spam
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
Labels: Avatar, Development Approved, Project Approved

#16405 Merge master into instancing
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
Labels: Engine

#16407 Fix for unused avatar transit warnings on mac and linux
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
Labels: Avatar, Development Approved, Project Approved

#16408 DEV-2575: Automatically lower raised hand if talking
  scripts/simplifiedUI/simplifiedEmote/simplifiedEmote.js
Labels: Development Approved, Project Approved, UI/UX

#16414 Server console fix
  server-console/packager.js
Labels: Development Approved, Project Approved, UI/UX

#16398 Gray emote window
  interface/resources/qml/InteractiveWindow.qml
Labels: Development Ready, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:, UI/UX, bug

#16415 DEV-2574: Make emote shortcuts case-insensitive
  scripts/simplifiedUI/simplifiedEmote/simplifiedEmote.js
Labels: Development Approved, Project Approved, UI/UX

#16418 DEV-1828: hifi_vcpkg.py crashes try downloading not defined qt url on an unknown linux system or unknown operating system
  hifi_vcpkg.py
Labels: Development Approved, Project Approved

#16420 temp reverting the call to display plugin
  libraries/audio-client/src/AudioClient.cpp
Labels: Development Approved, Development Ready, Engine, Project Approved, QA Approved :tada:

#16422 Added extra attempt to parent interactive window content on creation
  interface/resources/qml/InteractiveWindow.qml
Labels: Development Approved, Project Approved, UI/UX, bug

#16419 DEV-2285: Fix look at update and allow to release control
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  libraries/avatars-renderer/src/avatars-renderer/Head.cpp
Labels: Avatar, Development Approved, Development Ready, Project Approved, Scripting API change

#16390 Fixed the sprint speeds of Desktop vs HMD
  interface/src/avatar/MyAvatar.cpp
  libraries/shared/src/AvatarConstants.h
Labels: Client, Development Approved, HMD required, Open Source, Project Approved

#16423 DEV-2302: Fix for head not turning in third person look at camera mode
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
Labels: Avatar, Development Approved, Project Approved

#16424 Specified color on text edit for console
  interface/ui/console.ui
Labels: Development Approved, UI/UX, bug

#16392 In Bookmarks, attach avatar entities after the skeleton is loaded
  interface/src/AvatarBookmarks.cpp
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  libraries/animation/src/Rig.cpp
  libraries/animation/src/Rig.h
Labels: Avatar, Development Approved, Open Source, Project Approved

#16426 Dev-2602: Update Text on new QT Launcher
  launchers/qt/resources/qml/HFBase/CreateAccountBase.qml
  launchers/qt/resources/qml/HFBase/Error.qml
  launchers/qt/resources/qml/HFBase/LoginBase.qml
Labels: Development Approved, Project Approved, UI/UX

#16367 DOC-199: AudioScope JSDoc
  interface/src/audio/AudioScope.h
  interface/src/avatar/MyAvatar.h
  interface/src/raypick/LaserPointerScriptingInterface.h
  tools/jsdoc/plugins/hifi.js
Labels: JSDocs

#16335 DOC-191: Recording JSDoc
  libraries/script-engine/src/AssetScriptingInterface.h
  libraries/script-engine/src/RecordingScriptingInterface.h
Labels: JSDocs

#16338 DOC-126: Toolbars JSDoc
  libraries/ui/src/ui/TabletScriptingInterface.h
  libraries/ui/src/ui/ToolbarScriptingInterface.h
Labels: JSDocs

#16417 (DEV-559) Instancing: FBX and OBJ fixes
  libraries/fbx/src/FBXSerializer.cpp
  libraries/fbx/src/FBXSerializer_Mesh.cpp
  libraries/fbx/src/GLTFSerializer.cpp
  libraries/fbx/src/OBJSerializer.cpp
  libraries/fbx/src/OBJSerializer.h
  libraries/hfm/src/hfm/HFM.cpp
  libraries/hfm/src/hfm/HFM.h
  libraries/hfm/src/hfm/HFMModelMath.cpp
  libraries/hfm/src/hfm/HFMSerializer.h
Labels: Engine

#16421 case DEV-2771: Audio client shutdown lock
  interface/resources/qml/hifi/audio/Audio.qml
  interface/src/scripting/AudioDevices.cpp
  interface/src/scripting/AudioDevices.h
  libraries/audio-client/CMakeLists.txt
  libraries/audio-client/src/AudioClient.cpp
  libraries/audio-client/src/AudioClient.h
  libraries/plugins/src/plugins/PluginManager.cpp
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#16430 Attempt to fix DEV-2615 and DEV-2618 with more menu scripting interface guards
  interface/src/scripting/MenuScriptingInterface.cpp
Labels: Development Approved, Project Approved, UI/UX, bug

#16400 Extended avatar blendshape support for ARKit compatiblity
  assignment-client/src/Agent.cpp
  assignment-client/src/avatars/ScriptableAvatar.cpp
  assignment-client/src/avatars/ScriptableAvatar.h
  interface/CMakeLists.txt
  interface/resources/controllers/standard.json
  interface/resources/controllers/standard_nomovement.json
  interface/resources/controllers/vive.json
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/Menu.cpp
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  interface/src/avatar/MyHead.cpp
  interface/src/avatar/MySkeletonModel.cpp
  interface/src/avatar/OtherAvatar.cpp
  interface/src/devices/DdeFaceTracker.cpp
  interface/src/devices/DdeFaceTracker.h
  interface/src/ui/AvatarInputs.cpp
  interface/src/ui/AvatarInputs.h
  interface/src/ui/PreferencesDialog.cpp
  libraries/avatars-renderer/CMakeLists.txt
  libraries/avatars-renderer/src/avatars-renderer/Head.cpp
  libraries/avatars-renderer/src/avatars-renderer/SkeletonModel.cpp
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
  libraries/avatars/src/HeadData.cpp
  libraries/avatars/src/HeadData.h
  libraries/controllers/src/controllers/Actions.cpp
  libraries/controllers/src/controllers/Actions.h
  libraries/controllers/src/controllers/StandardController.cpp
  libraries/controllers/src/controllers/StandardControls.h
  libraries/fbx/src/FBXSerializer.cpp
  libraries/fbx/src/FSTReader.cpp
  libraries/fbx/src/GLTFSerializer.cpp
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
  libraries/render-utils/src/Model.cpp
  libraries/shared/src/BlendshapeConstants.cpp
  libraries/shared/src/BlendshapeConstants.h
  libraries/shared/src/FaceshiftConstants.h
  libraries/trackers/CMakeLists.txt
  libraries/trackers/src/trackers/FaceTracker.cpp
  libraries/trackers/src/trackers/FaceTracker.h
  libraries/trackers/src/trackers/Logging.cpp
  libraries/trackers/src/trackers/Logging.h
  tools/jsdoc/plugins/hifi.js
Labels: Avatar, Development Approved, PRE-MERGE TESTING REQUIRED, Packet Version Change, Project Approved, Scripting API change

#16431 (DEV-564) Introduce and populate geometry-only mesh representation from hfm::Mesh
  libraries/hfm/src/hfm/HFM.h
  libraries/hfm/src/hfm/HFMModelMath.cpp
  libraries/hfm/src/hfm/HFMModelMath.h
  libraries/model-baker/src/model-baker/Baker.cpp
  libraries/shared/src/GLMHelpers.h
Labels: Engine
