Repository highfidelity/hifi, pull requests merged in 2019-11, with the labels that each got.

#16434 DEV-2619: WebRTC spamming logs
  libraries/audio-client/src/AudioClient.cpp
Labels: Client, Development Approved, Development Ready, Project Approved

#16435 Hooked up seated version of aim offset animation
  interface/resources/avatar/animations/sitting_idle_aimoffsets.fbx
  interface/resources/avatar/avatar-animation.json
  interface/src/avatar/MyAvatar.cpp
Labels: Avatar, Development Approved, Project Approved

#16437 Instancing: Attempt fix for Android build
  CMakeLists.txt
Labels: Engine

#16439 Ending a joke
  scripts/simplifiedUI/simplifiedEmote/emojiApp/resources/images/emojis/512px/sam.png
  scripts/simplifiedUI/simplifiedEmote/emojiApp/resources/images/emojis/52px/sam.png
  scripts/simplifiedUI/simplifiedEmote/emojiApp/resources/modules/customEmojiList.js
Labels: Engine

#16438 Changed default interface window size on mac
  libraries/ui/src/MainWindow.cpp
Labels: Development Approved, Project Approved, UI/UX, bug

#16444 Instancing: Calculate shape extents using existing extents in simple mesh
  libraries/fbx/src/FBXSerializer.cpp
  libraries/hfm/src/hfm/HFM.h
  libraries/hfm/src/hfm/HFMModelMath.cpp
  libraries/hfm/src/hfm/HFMModelMath.h
  libraries/model-baker/src/model-baker/Baker.cpp
  libraries/model-baker/src/model-baker/CalculateTransformedExtentsTask.cpp
  libraries/model-baker/src/model-baker/CalculateTransformedExtentsTask.h
Labels: Engine

#16399 Case 7120, Case 14963: Procedural material entities on primitives and meshes
  assignment-client/CMakeLists.txt
  interface/src/Application.cpp
  interface/src/Menu.cpp
  interface/src/Menu.h
  interface/src/ui/PreferencesDialog.cpp
  libraries/avatars-renderer/CMakeLists.txt
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
  libraries/avatars/CMakeLists.txt
  libraries/avatars/src/AvatarData.h
  libraries/baking/CMakeLists.txt
  libraries/baking/src/MaterialBaker.h
  libraries/baking/src/TextureBaker.h
  libraries/display-plugins/CMakeLists.txt
  libraries/entities-renderer/src/RenderableMaterialEntityItem.cpp
  libraries/entities-renderer/src/RenderableMaterialEntityItem.h
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities-renderer/src/RenderableShapeEntityItem.cpp
  libraries/entities-renderer/src/RenderableShapeEntityItem.h
  libraries/entities/CMakeLists.txt
  libraries/gpu/src/gpu/Shader.h
  libraries/gpu/src/gpu/ShaderConstants.h
  libraries/graphics-scripting/src/graphics-scripting/Forward.h
  libraries/graphics-scripting/src/graphics-scripting/GraphicsScriptingInterface.cpp
  libraries/graphics-scripting/src/graphics-scripting/ScriptableModel.cpp
  libraries/graphics/src/graphics/Material.cpp
  libraries/graphics/src/graphics/Material.h
  libraries/model-baker/CMakeLists.txt
  libraries/model-baker/src/model-baker/ParseMaterialMappingTask.h
  libraries/model-networking/CMakeLists.txt
  libraries/model-networking/src/model-networking/ModelCache.h
  libraries/physics/CMakeLists.txt
  libraries/procedural/CMakeLists.txt
  libraries/procedural/src/procedural/MaterialCacheScriptingInterface.cpp
  libraries/procedural/src/procedural/MaterialCacheScriptingInterface.h
  libraries/procedural/src/procedural/Procedural.cpp
  libraries/procedural/src/procedural/Procedural.h
  libraries/procedural/src/procedural/ProceduralCommon.slh
  libraries/procedural/src/procedural/ProceduralMaterialCache.cpp
  libraries/procedural/src/procedural/ProceduralMaterialCache.h
  libraries/procedural/src/procedural/ProceduralSkybox.cpp
  libraries/procedural/src/procedural/ShaderConstants.h
  libraries/render-utils/src/CauterizedMeshPartPayload.cpp
  libraries/render-utils/src/CauterizedMeshPartPayload.h
  libraries/render-utils/src/CauterizedModel.cpp
  libraries/render-utils/src/MeshPartPayload.cpp
  libraries/render-utils/src/MeshPartPayload.h
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
  libraries/render-utils/src/RenderPipelines.cpp
  libraries/render-utils/src/render-utils/simple_procedural.slp
  libraries/render-utils/src/simple_procedural.slv
  libraries/script-engine/CMakeLists.txt
  libraries/script-engine/src/Quat.cpp
  libraries/script-engine/src/SceneScriptingInterface.cpp
  libraries/script-engine/src/SceneScriptingInterface.h
  tests-manual/render-perf/src/main.cpp
  tools/oven/CMakeLists.txt
  tools/oven/src/Oven.cpp
  tools/oven/src/OvenCLIApplication.cpp
Labels: Development Approved, Engine, Open Source, Project Approved, Scripting API change

#16441 Implement DEV-2654: Allow ESS to make use of signals like `avatarRemovedEvent`
  assignment-client/src/avatars/AvatarMixer.cpp
  libraries/avatars/src/AvatarHashMap.h
Labels: Development Approved, Project Approved, UI/UX, bug

#16446 Renaming the env variable to enable Material Procedural Shaders
  interface/src/Menu.cpp
  interface/src/Menu.h
  interface/src/ui/PreferencesDialog.cpp
  libraries/render-utils/src/MeshPartPayload.cpp
  libraries/render-utils/src/MeshPartPayload.h
Labels: Development Approved, Engine, Project Approved

#16454 Fix DEV-2598: Upgrading from Old Launcher to QT Launcher now places Start Menu shortcuts in the right place
  launchers/qt/src/PathUtils.cpp
  launchers/qt/src/main.cpp
Labels: Development Approved, Project Approved, UI/UX, bug

#16455 Instancing: Fix build error with _drawTransform
  libraries/render-utils/src/MeshPartPayload.cpp
Labels: Engine

#16442 dev-2641: Uninstall does not show in the Windows Start Menu until the second launch of the app
  launchers/qt/src/LauncherInstaller_windows.cpp
  launchers/qt/src/LauncherInstaller_windows.h
Labels: Development Approved, Project Approved, UI/UX

#16449 case dev-2662: removing double calls to switch devices, handling default changes fro…
  interface/src/scripting/AudioDevices.cpp
  libraries/audio-client/src/AudioClient.cpp
  libraries/audio-client/src/AudioClient.h
  libraries/audio-client/src/HifiAudioDeviceInfo.cpp
  libraries/audio-client/src/HifiAudioDeviceInfo.h
Labels: Development Approved, Engine, Project Approved

#16445 Remove LipsUpperOpen and LipsLowerOpen, the last of the legacy blendshapes
  interface/resources/controllers/standard.json
  interface/resources/controllers/standard_nomovement.json
  interface/src/avatar/MyHead.cpp
  libraries/controllers/src/controllers/Actions.cpp
  libraries/controllers/src/controllers/Actions.h
  libraries/controllers/src/controllers/StandardController.cpp
  libraries/controllers/src/controllers/StandardControls.h
  libraries/fbx/src/FSTReader.cpp
  libraries/shared/src/BlendshapeConstants.cpp
  libraries/shared/src/BlendshapeConstants.h
Labels: Avatar, Development Approved, Project Approved, Scripting API change

#16457 DOC-193 Clarified legacy vs current camera modes
  libraries/shared/src/shared/Camera.cpp
Labels: Development Approved, JSDocs, Project Approved

#16448 "deep" codesign Interface on macOS
  cmake/init.cmake
  interface/src/AvatarBookmarks.cpp
Labels: Development Approved, Development Ready, Project Approved

#16447 DEV-2461: Head woes in 1st person part 2
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
Labels: Avatar, Development Approved, Project Approved

#16456 Fix for avatar recordings not playing back blendshapes
  assignment-client/src/Agent.cpp
Labels: Avatar, Development Approved, Project Approved

#16463 DEV-2695: Update Zone Haze floor and ceiling mins and maxes in the UI
  scripts/system/create/entityProperties/html/js/entityProperties.js
Labels: Create, Development Approved, Project Approved, UI/UX

#16462 DEV-2701: Remove the home icon from the profile app
  interface/resources/qml/hifi/simplifiedUI/avatarApp/AvatarApp.qml
Labels: Development Approved, Project Approved, UI/UX

#16464 Reduce fidgety motions in seated fidgets
  interface/resources/avatar/animations/sitting_idle04.fbx
  interface/resources/avatar/animations/sitting_idle05.fbx
  interface/resources/avatar/animations/sitting_idle_once_leanforward.fbx
  interface/resources/avatar/animations/sitting_idle_once_lookfidget.fbx
  interface/resources/avatar/animations/sitting_idle_once_shakelegs.fbx
  interface/resources/avatar/animations/sitting_idle_once_shiftweight.fbx
Labels: Avatar, Development Approved, Project Approved

#16458 Fix for assert in AnimBlendDirectional on startup
  libraries/animation/src/AnimBlendDirectional.cpp
Labels: Avatar, Development Approved, Project Approved

#16451 DEV-2650: Remove "user" icon from Entities List
  scripts/system/create/entityList/entityList.js
  scripts/system/create/entityList/html/entityList.html
  scripts/system/create/entityList/html/js/entityList.js
Labels: Development Approved, Project Approved, UI/UX

#16440 DEV-2648: Fix Cmd-click multi-select in entity list on Mac
  scripts/system/create/entityList/html/js/entityList.js
Labels: Development Approved, Project Approved, UI/UX

#16470 Procedural Material crashes in shadow pass on deformed shape renderItems
  libraries/render-utils/src/RenderShadowTask.cpp
Labels: Development Approved, Engine, Project Approved

#16474 Fix unused variables/implicit type conversions
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/physics/src/ShapeFactory.cpp
Labels: Engine

#16475 Merge master into instancing
  assignment-client/src/Agent.cpp
  cmake/init.cmake
  interface/resources/avatar/animations/sitting_idle04.fbx
  interface/resources/avatar/animations/sitting_idle05.fbx
  interface/resources/avatar/animations/sitting_idle_once_leanforward.fbx
  interface/resources/avatar/animations/sitting_idle_once_lookfidget.fbx
  interface/resources/avatar/animations/sitting_idle_once_shakelegs.fbx
  interface/resources/avatar/animations/sitting_idle_once_shiftweight.fbx
  interface/resources/controllers/standard.json
  interface/resources/controllers/standard_nomovement.json
  interface/resources/qml/hifi/simplifiedUI/avatarApp/AvatarApp.qml
  interface/resources/qml/hifi/simplifiedUI/topBar/SimplifiedTopBar.qml
  interface/src/AvatarBookmarks.cpp
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  interface/src/avatar/MyHead.cpp
  interface/src/scripting/AudioDevices.cpp
  launchers/qt/src/LauncherInstaller_windows.cpp
  launchers/qt/src/LauncherInstaller_windows.h
  launchers/qt/src/PathUtils.cpp
  launchers/qt/src/main.cpp
  libraries/animation/src/AnimBlendDirectional.cpp
  libraries/audio-client/src/AudioClient.cpp
  libraries/audio-client/src/AudioClient.h
  libraries/audio-client/src/HifiAudioDeviceInfo.cpp
  libraries/audio-client/src/HifiAudioDeviceInfo.h
  libraries/controllers/src/controllers/Actions.cpp
  libraries/controllers/src/controllers/Actions.h
  libraries/controllers/src/controllers/StandardController.cpp
  libraries/controllers/src/controllers/StandardControls.h
  libraries/fbx/src/FSTReader.cpp
  libraries/render-utils/src/RenderShadowTask.cpp
  libraries/shared/src/BlendshapeConstants.cpp
  libraries/shared/src/BlendshapeConstants.h
  libraries/shared/src/shared/Camera.cpp
  scripts/system/create/entityList/entityList.js
  scripts/system/create/entityList/html/entityList.html
  scripts/system/create/entityList/html/js/entityList.js
  scripts/system/create/entityProperties/html/js/entityProperties.js
Labels: Engine

#16471 DEV-2711: Fix with procedural material and shadows applied on deformed mesh
  libraries/render-utils/src/HighlightEffect.cpp
  libraries/render-utils/src/RenderShadowTask.cpp
Labels: Development Approved, Engine, Project Approved, QA Ready

#16468 Made web entities not grabbable by default
  scripts/system/create/edit.js
Labels: Development Approved, Project Approved, UI/UX

#16461 DEV-2649: Fix entities list "filter to frustum" eye button
  scripts/system/create/entityList/entityList.js
Labels: Development Approved, Project Approved, UI/UX

#16473 Oculus Quest: Fix for the hand controllers in the latest version
  android/apps/questInterface/src/main/AndroidManifest.xml
Labels: Development Approved, HMD required, Project Approved

#16472 Update WindowScriptingInterface.h
  interface/src/scripting/WindowScriptingInterface.h
Labels: Development Approved, Open Source, Project Approved, Scripting API change

#16478 (DEV-563) Use HFM::Shapes when initializing raypick geometry
  libraries/render-utils/src/Model.cpp
Labels: Engine

#16467 Different settle transition depending on momentum
  interface/resources/avatar/animations/settle_to_idle.fbx
  interface/resources/avatar/animations/settle_to_idle02.fbx
  interface/resources/avatar/animations/settle_to_idle03.fbx
  interface/resources/avatar/animations/settle_to_idle04.fbx
  interface/resources/avatar/animations/settle_to_idle_small.fbx
  interface/resources/avatar/avatar-animation.json
  libraries/animation/src/Rig.cpp
  libraries/animation/src/Rig.h
Labels: Avatar, Development Approved, Project Approved

#16480 DEV-2330: Improved attenuation zones
  assignment-client/src/audio/AudioMixerSlave.cpp
  libraries/audio/src/AudioHRTF.cpp
  libraries/audio/src/AudioHRTF.h
Labels: Development Approved, Project Approved, Server & Network

#16485 Merge master into instancing
  android/apps/questInterface/src/main/AndroidManifest.xml
  assignment-client/src/audio/AudioMixerSlave.cpp
  interface/resources/avatar/animations/settle_to_idle.fbx
  interface/resources/avatar/animations/settle_to_idle02.fbx
  interface/resources/avatar/animations/settle_to_idle03.fbx
  interface/resources/avatar/animations/settle_to_idle04.fbx
  interface/resources/avatar/animations/settle_to_idle_small.fbx
  interface/resources/avatar/avatar-animation.json
  interface/src/scripting/WindowScriptingInterface.h
  libraries/animation/src/Rig.cpp
  libraries/animation/src/Rig.h
  libraries/audio/src/AudioHRTF.cpp
  libraries/audio/src/AudioHRTF.h
  scripts/system/create/edit.js
  scripts/system/create/entityList/entityList.js
Labels: Engine

#16484 (DEV-2593) Instancing: Fix model baking to work with new hfm::Shape material definition
  libraries/baking/src/OBJBaker.cpp
  libraries/baking/src/OBJBaker.h
  libraries/fbx/src/FBXSerializer.cpp
  libraries/fbx/src/OBJSerializer.cpp
  libraries/hfm/src/hfm/HFM.h
  libraries/model-baker/src/model-baker/Baker.cpp
  libraries/model-baker/src/model-baker/BuildDracoMeshTask.cpp
  libraries/model-baker/src/model-baker/BuildDracoMeshTask.h
  tools/vhacd-util/src/VHACDUtil.cpp
Labels: Development Approved, Engine

#16481 case dev-2663: Adding safeguard in case device list is empty
  libraries/audio-client/src/AudioClient.cpp
Labels: Development Approved, Engine, Project Approved

#16486 Fix HMD strafe locomotion animation.
  interface/resources/avatar/avatar-animation.json
  libraries/animation/src/Rig.cpp
Labels: Avatar, Development Approved, Project Approved

#16487 case DEV-2709: reset QAudioDevInfo on switch
  libraries/audio-client/src/AudioClient.cpp
Labels: Development Approved, Engine, Project Approved

#16477 DEV-2711: Fix crash when highlighting custom pipeline shapes
  libraries/render-utils/src/HighlightEffect.cpp
Labels: Development Approved, Engine, Project Approved

#16489 RC86: Handle HMD in input vars and remove/fix json transitions in/out of HMD strafe states
  interface/resources/avatar/avatar-animation.json
  libraries/animation/src/Rig.cpp
Labels: Avatar, Development Approved, Project Approved, Release Blocker

#16491 Fix code style / remove cruft
  libraries/animation/src/AnimSkeleton.cpp
  libraries/animation/src/AnimSkeleton.h
  libraries/baking/src/MaterialBaker.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/fbx/src/FBXSerializer.cpp
  libraries/fbx/src/OBJSerializer.cpp
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/SoftAttachmentModel.cpp
  tests-manual/fbx/CMakeLists.txt
  tests-manual/fbx/src/main.cpp
Labels: Engine

#16488 Bugfix for t-pose avatar when moving
  interface/resources/avatar/avatar-animation-optimized-ik.json
  interface/resources/avatar/avatar-animation_withSplineIKNode.json
  interface/src/avatar/MyAvatar.cpp
Labels: Android, Avatar, Development Approved, Project Approved

#16479 Speculative fix for infinite loop in SafeLanding
  interface/src/octree/SafeLanding.cpp
  interface/src/octree/SafeLanding.h
Labels: Avatar, Beware: Threading/Deadlock, Development Approved, Engine, Project Approved, Server & Network

#16494 Revert safe landing "fix"
  interface/src/octree/SafeLanding.cpp
  interface/src/octree/SafeLanding.h
Labels: Avatar, Development Approved, Engine, Metaverse, Project Approved

#16361 DEV-1811 redux: apply entity deletion rules
  interface/src/InterfaceParentFinder.cpp
  interface/src/avatar/AvatarManager.cpp
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  interface/src/avatar/OtherAvatar.cpp
  interface/src/ui/AvatarCertifyBanner.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.h
  libraries/entities-renderer/src/RenderableEntityItem.cpp
  libraries/entities/src/DeleteEntityOperator.cpp
  libraries/entities/src/DeleteEntityOperator.h
  libraries/entities/src/EntityEditFilters.cpp
  libraries/entities/src/EntityEditFilters.h
  libraries/entities/src/EntityEditPacketSender.cpp
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityScriptingInterface.cpp
  libraries/entities/src/EntitySimulation.cpp
  libraries/entities/src/EntitySimulation.h
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/EntityTree.h
  libraries/entities/src/EntityTreeElement.cpp
  libraries/entities/src/SimpleEntitySimulation.cpp
  libraries/entities/src/SimpleEntitySimulation.h
  libraries/physics/src/EntityMotionState.cpp
  libraries/physics/src/EntityMotionState.h
  libraries/physics/src/PhysicalEntitySimulation.cpp
  libraries/physics/src/PhysicalEntitySimulation.h
  libraries/shared/src/PhysicsHelpers.cpp
  libraries/shared/src/SpatialParentFinder.h
  tests/octree/src/ModelTests.cpp
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#16496 DEV-2760 - Fix Realtime Unfocused to be 60hz
  interface/src/RefreshRateManager.cpp
Labels: Development Approved, Engine, Project Approved

#16490 DEV-2742: Fix Graphics.exportModelToOBJ() JavaScript crash
  libraries/graphics-scripting/src/graphics-scripting/GraphicsScriptingInterface.cpp
  libraries/graphics-scripting/src/graphics-scripting/GraphicsScriptingInterface.h
Labels: Client, Development Approved, Project Approved

#16497 DEV-2769: Remove the "acceleration" entity property from Create app
  scripts/system/create/assets/data/createAppTooltips.json
  scripts/system/create/entityProperties/html/js/entityProperties.js
Labels: Client, Development Approved, Project Approved

#16429 Screenshare in Interface!
  CMakeLists.txt
  assignment-client/src/avatars/AvatarMixer.cpp
  assignment-client/src/avatars/AvatarMixerClientData.cpp
  cmake/macros/SetPackagingParameters.cmake
  domain-server/src/DomainServer.cpp
  domain-server/src/DomainServer.h
  interface/resources/qml/Web3DSurface.qml
  interface/src/Application.cpp
  interface/src/scripting/ScreenshareScriptingInterface.cpp
  interface/src/scripting/ScreenshareScriptingInterface.h
  libraries/networking/src/udt/PacketHeaders.h
  screenshare/.gitignore
  screenshare/CMakeLists.txt
  screenshare/README.md
  screenshare/package-lock.json
  screenshare/package.json
  screenshare/packager.js
  screenshare/src/resources/Graphik-Regular.ttf
  screenshare/src/resources/interface.png
  screenshare/src/screenshareApp.html
  screenshare/src/screenshareApp.js
  screenshare/src/screenshareMainProcess.js
  screenshare/src/styles.css
  scripts/simplifiedUI/clickToZoom/clickToZoom.js
  scripts/simplifiedUIBootstrapper.js
Labels: Development Approved, Project Approved, UI/UX

#16500 Fix for inadvertent comment
  libraries/avatars/src/ClientTraitsHandler.cpp
Labels: Avatar, Development Approved, Project Approved

#16502 dev-2718/models-brought-in-at-incorrect-dimensions
  scripts/system/create/edit.js
Labels: Development Approved, Project Approved, UI/UX

#16504 added desktopSharing var
  screenshare/src/screenshareApp.html
  screenshare/src/screenshareApp.js
Labels: Development Approved, Project Approved, UI/UX

#16483 Add tools for debugging entity workload proxies
  interface/src/raypick/PickScriptingInterface.h
  interface/src/scripting/SelectionScriptingInterface.cpp
  interface/src/scripting/SelectionScriptingInterface.h
  interface/src/workload/GameWorkload.cpp
  interface/src/workload/GameWorkloadRenderer.cpp
  interface/src/workload/SelectedWorkloadRenderer.cpp
  interface/src/workload/SelectedWorkloadRenderer.h
  libraries/entities/src/EntityTreeElement.cpp
  libraries/shared/src/PickFilter.h
  libraries/workload/src/workload/Space.cpp
  libraries/workload/src/workload/Space.h
  scripts/developer/debugging/debugWorkloadWithMouseHover.js
Labels: Development Approved, Engine, Scripting API change

#15278 case 21983: Clear more disk caches
  interface/src/Menu.cpp
  interface/src/Menu.h
  libraries/ui/src/ui/types/FileTypeProfile.cpp
  libraries/ui/src/ui/types/FileTypeProfile.h
  libraries/ui/src/ui/types/HFWebEngineProfile.cpp
  libraries/ui/src/ui/types/HFWebEngineProfile.h
Labels: Development Ready, Engine, Open Source, Project Approved, Server & Network

#16495 DOC-209: AudioStats JSDoc
  libraries/audio-client/src/AudioIOStats.h
Labels: JSDocs

#16508 Fix DEV-2789: Implement retry timer when retrieving screen share info
  interface/src/scripting/ScreenshareScriptingInterface.cpp
  interface/src/scripting/ScreenshareScriptingInterface.h
Labels: Development Approved, UI/UX, bug

#16498 Improve seated rotation
  interface/resources/avatar/animations/settle_sitturnleft_to_sitidle.fbx
  interface/resources/avatar/animations/settle_sitturnright_to_sitidle.fbx
  interface/resources/avatar/animations/sitting_turn_left.fbx
  interface/resources/avatar/animations/sitting_turn_right.fbx
  interface/resources/avatar/avatar-animation.json
  interface/src/avatar/MyAvatar.cpp
  libraries/animation/src/Rig.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
Labels: Avatar, Development Approved, Project Approved

#16510 dev-2791/update-hardcoded-screen-values
  interface/src/scripting/ScreenshareScriptingInterface.cpp
Labels: Development Approved, Project Approved, UI/UX

#16492 DOC-208: Revisions to JSDoc added by developers since July 2019
  assignment-client/src/avatars/ScriptableAvatar.h
  interface/src/avatar/MyAvatar.h
  interface/src/raypick/PickScriptingInterface.cpp
  interface/src/raypick/PickScriptingInterface.h
  interface/src/raypick/PointerScriptingInterface.cpp
  interface/src/raypick/PointerScriptingInterface.h
  libraries/avatars/src/AvatarData.h
Labels: JSDocs

#15334 case 22189: Add display name field to the log in screen.
  interface/resources/qml/LoginDialog/LinkAccountBody.qml
  interface/resources/qml/LoginDialog/LoggingInBody.qml
Labels: Design, Development Approved, Open Source, Project Approved, QA Approved :tada:

#16506 DEV-2764, DEV-2113: Remove Avatar app links to AvatarIsland and BodyMart
  interface/resources/images/avatarapp/AvatarIsland.jpg
  interface/resources/images/avatarapp/BodyMart.PNG
  interface/resources/qml/hifi/AvatarApp.qml
  interface/resources/qml/hifi/avatarapp/AdjustWearables.qml
  interface/resources/qml/hifi/avatarapp/MessageBoxes.qml
  libraries/networking/src/AddressManager.h
  scripts/system/interstitialPage.js
Labels: Development Approved, Project Approved, UI/UX

#16512 DEV-2585: fix for whiteboard poly lines getting their parentID incorrectly reverted
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityTree.cpp
Labels: Development Approved, Engine

#16514 dev-2795/fix-multiple-color-sphere-pops
  interface/src/scripting/ScreenshareScriptingInterface.cpp
Labels: Development Approved, Project Approved, UI/UX

#16505 Touchpad improvements: pinch to zoom camera, two finger swipe to look around, bug fixes
  interface/resources/controllers/keyboardMouse.json
  interface/src/Application.cpp
  libraries/input-plugins/src/input-plugins/KeyboardMouseDevice.cpp
  libraries/input-plugins/src/input-plugins/KeyboardMouseDevice.h
Labels: Avatar, Development Approved, Project Approved

#16443 DEV-2646: Use Alt to clone entities on Mac
  scripts/system/create/entitySelectionTool/entitySelectionTool.js
Labels: Development Approved, Development Ready, Project Approved, UI/UX

#16513 Edge case fix for seated rotation - it would bounce forward if you let go of Q/E at exact right time.
  interface/src/avatar/MyAvatar.cpp
Labels: Avatar, Development Approved, Development Ready, Project Approved

#16519 DEV-2797/ DEV-2798: Click to zoom fixes and comments
  scripts/simplifiedUI/clickToZoom/clickToZoom.js
Labels: Development Approved, UI/UX

#16516 remove worklist.net references
  README.md
Labels: Development Approved, Project Approved

#16511 fix handleUrl helper regex
  libraries/networking/src/AddressManager.cpp
Labels: Development Approved, Metaverse, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:, bug

#16522 DEV-2794: Update BUILD.MD
  BUILD.md
Labels: Development Ready, Project Approved, UI/UX

#16523 Move "away" animation from S3 bucket to local resource
  interface/resources/avatar/animations/afk_texting.fbx
  scripts/system/away.js
Labels: Avatar, Development Approved, Project Approved

#16524 Remove upload step and unlabel job from builds
  .github/workflows/cmake.yml
Labels: Development Approved, Project Approved

#16527 On Linux, remove quazip5 dynamic libs
  cmake/ports/quazip/portfile.cmake
Labels: Development Approved, Project Approved

#16526 Call updateGeometry before Model::createRenderItemSet
  libraries/render-utils/src/Model.cpp
Labels: Development Approved, Engine, Project Approved

#16525 DEV-2871: signal connection check before emit of devices changed
  libraries/audio-client/src/AudioClient.cpp
Labels: Development Approved, Development Ready, Engine, Project Approved

#16530 fix linux build
  libraries/shared/src/shared/QtHelpers.h
  tools/nitpick/CMakeLists.txt
Labels: Development Approved, Project Approved

#16517 Input plugin for streaming blendshapes from an iPhone
  cmake/macros/TargetLiblo.cmake
  cmake/ports/hifi-client-deps/CONTROL
  cmake/ports/liblo/CONTROL
  cmake/ports/liblo/portfile.cmake
  hifi_vcpkg.py
  interface/resources/controllers/osc.json
  interface/resources/qml/hifi/tablet/ControllerSettings.qml
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyHead.cpp
  libraries/avatars-renderer/src/avatars-renderer/Head.cpp
  libraries/avatars/src/AvatarData.cpp
  plugins/CMakeLists.txt
  plugins/hifiOsc/CMakeLists.txt
  plugins/hifiOsc/src/OscPlugin.cpp
  plugins/hifiOsc/src/OscPlugin.h
  plugins/hifiOsc/src/OscProvider.cpp
  plugins/hifiOsc/src/plugin.json
Labels: Avatar, Development Approved, Project Approved

#16533 DEV-2800: Fix crash in Stats.forceUpdateStats() at start-up
  interface/src/ui/Stats.cpp
Labels: Development Approved, Engine

#16536 Update prebuilt dependencies
  cmake/macros/TargetAristo.cmake
  cmake/macros/TargetSRanipalEye.cmake
  cmake/ports/aristo/CONTROL
  cmake/ports/aristo/portfile.cmake
  cmake/ports/hifi-client-deps/CONTROL
  cmake/ports/sranipal/CONTROL
  cmake/ports/sranipal/portfile.cmake
  cmake/ports/zlib/CONTROL
  cmake/ports/zlib/portfile.cmake
  hifi_vcpkg.py
Labels: Development Ready, Project Approved

#16537 DEV-491: Create a README.md file to document the Qt Launcher
  launchers/qt/BUILD.md
  launchers/qt/readme.md
Labels: UI/UX

#16531 DEV-2825: Fix camera pitch by mouse wheel
  libraries/input-plugins/src/input-plugins/KeyboardMouseDevice.cpp
Labels: Development Approved, Project Approved, UI/UX

#16532 Added animedit avatar-animation.json graph editor tool
  tools/animedit/.gitignore
  tools/animedit/LICENCE
  tools/animedit/README.md
  tools/animedit/animedit.pro
  tools/animedit/main.cpp
  tools/animedit/qml.qrc
  tools/animedit/qml/TreeDelegate.qml
  tools/animedit/qml/fields/BooleanField.qml
  tools/animedit/qml/fields/IdField.qml
  tools/animedit/qml/fields/JSONField.qml
  tools/animedit/qml/fields/NumberArrayField.qml
  tools/animedit/qml/fields/NumberField.qml
  tools/animedit/qml/fields/StringField.qml
  tools/animedit/qml/fields/TypeField.qml
  tools/animedit/qml/main.qml
  tools/animedit/qml/nodes/BlendDirectional.qml
  tools/animedit/qml/nodes/BlendLinear.qml
  tools/animedit/qml/nodes/BlendLinearMove.qml
  tools/animedit/qml/nodes/ClipData.qml
  tools/animedit/qml/nodes/DefaultPose.qml
  tools/animedit/qml/nodes/InverseKinematics.qml
  tools/animedit/qml/nodes/Manipulator.qml
  tools/animedit/qml/nodes/Overlay.qml
  tools/animedit/qml/nodes/PoleVector.qml
  tools/animedit/qml/nodes/RandomStateMachine.qml
  tools/animedit/qml/nodes/SplineIK.qml
  tools/animedit/qml/nodes/StateMachine.qml
  tools/animedit/qml/nodes/TwoBoneIK.qml
  tools/animedit/treeitem.cpp
  tools/animedit/treeitem.h
  tools/animedit/treemodel.cpp
  tools/animedit/treemodel.h
Labels: Avatar, Development Approved, Project Approved

#16534 Fix a few Screenshare bugs (see description)
  interface/src/scripting/ScreenshareScriptingInterface.cpp
  interface/src/scripting/ScreenshareScriptingInterface.h
Labels: Development Approved, Project Approved, UI/UX, bug

#16544 ignore anonymous screenshare zone entry
  domain-server/src/DomainServer.cpp
Labels: Development Approved, Metaverse, Project Approved

#16545 Add automaticLookAt.js to developer scripts
  scripts/developer/automaticLookAt.js
Labels: Avatar, Development Approved, Project Approved

#16547 DEV-2840: Fix z-fighting issues in Smartboard and enable quicker positional iteration in the future
  interface/src/scripting/ScreenshareScriptingInterface.cpp
  interface/src/scripting/ScreenshareScriptingInterface.h
Labels: Development Approved, Project Approved, UI/UX, bug

#16549 DEV-2832, DEV-2816, DEV-2843: Auto-minimize Screen Share; enable switching between windows; prevent video dropout
  screenshare/src/screenshareApp.js
Labels: Development Approved, Project Approved, UI/UX

#16541 DOC-233: MaterialCache JSDoc
  libraries/animation/src/AnimationCacheScriptingInterface.h
  libraries/audio/src/SoundCacheScriptingInterface.h
  libraries/material-networking/src/material-networking/TextureCacheScriptingInterface.h
  libraries/model-networking/src/model-networking/ModelCacheScriptingInterface.h
  libraries/networking/src/ResourceCache.h
  libraries/procedural/src/procedural/MaterialCacheScriptingInterface.h
  libraries/procedural/src/procedural/ProceduralMaterialCache.cpp
  tools/jsdoc/plugins/hifi.js
Labels: JSDocs, Project Approved

#16542 dev-829: waiting on local injector prep
  libraries/audio-client/src/AudioClient.cpp
  libraries/audio-client/src/AudioClient.h
Labels: Development Approved, Engine, Project Approved

#16550 DEV-2729: Airpods starve on startup
  libraries/audio-client/src/AudioClient.cpp
Labels: Development Approved, Engine, Project Approved
