Repository highfidelity/hifi, pull requests merged in 2019-07, with the labels that each got.

#15857 DEV-193: Disallow mic and webcam access always.
  interface/resources/qml/+webengine/BrowserWebView.qml
  interface/resources/qml/+webengine/TabletBrowser.qml
  interface/resources/qml/controls/+webengine/FlickableWebViewCore.qml
  interface/resources/qml/controlsUit/+webengine/BaseWebView.qml
Labels: Client, Development Approved, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#15854 BUGZ-692: Laucner is not movable & BUGZ-831 handle org and credentials erros.
  launchers/darwin/CMakeLists.txt
  launchers/darwin/nib/DisplayNameScreen.xib
  launchers/darwin/nib/ErrorScreen.xib
  launchers/darwin/nib/LoginScreen.xib
  launchers/darwin/nib/ProcessScreen.xib
  launchers/darwin/nib/SplashScreen.xib
  launchers/darwin/src/CredentialsRequest.h
  launchers/darwin/src/CredentialsRequest.m
  launchers/darwin/src/DownloadDomainContent.m
  launchers/darwin/src/DownloadInterface.m
  launchers/darwin/src/ImageView.h
  launchers/darwin/src/ImageView.m
  launchers/darwin/src/LatestBuildRequest.m
  launchers/darwin/src/Launcher.h
  launchers/darwin/src/Launcher.m
  launchers/darwin/src/OrganizationRequest.h
  launchers/darwin/src/OrganizationRequest.m
  launchers/darwin/src/Window.h
  launchers/darwin/src/Window.m
Labels: Client, Development Ready, PRE-MERGE TESTING REQUIRED, Project Approved

#15858 DEV-194: Iterate on PTT Ducking Slider design
  interface/resources/qml/hifi/simplifiedUI/settingsApp/audio/Audio.qml
  interface/src/scripting/Audio.h
Labels: Development Approved, Project Approved, UI/UX

#15860 add network card info to platform info
  libraries/platform/CMakeLists.txt
  libraries/platform/src/platform/PlatformKeys.h
  libraries/platform/src/platform/backend/Platform.cpp
  libraries/platform/src/platform/backend/PlatformInstance.cpp
  libraries/platform/src/platform/backend/PlatformInstance.h
  libraries/platform/src/platform/backend/WINPlatform.cpp
  libraries/platform/src/platform/backend/WINPlatform.h
Labels: Development Approved, Metaverse, Project Approved

#15859 BUGZ-787: fix SafeLanding to load correct set of objects before enabling physics simulation
  interface/src/Application.cpp
  interface/src/octree/SafeLanding.cpp
  libraries/shared/src/shared/ConicalViewFrustum.cpp
  libraries/shared/src/shared/ConicalViewFrustum.h
Labels: Development Ready, Engine

#15863 BUGZ-894: Propagate a Node's public address change, part 2
  libraries/networking/src/LimitedNodeList.cpp
  libraries/networking/src/udt/Socket.h
Labels: Development Approved, Metaverse, Project Approved

#15864 Fix for DependencyManager crash on shutdown on Mac
  interface/src/Application.cpp
  libraries/baking/src/MaterialBaker.cpp
  libraries/entities-renderer/src/RenderableMaterialEntityItem.cpp
  libraries/material-networking/src/material-networking/MaterialCache.cpp
  libraries/material-networking/src/material-networking/MaterialCache.h
  libraries/model-baker/src/model-baker/ParseMaterialMappingTask.cpp
  libraries/networking/src/AccountManager.cpp
  libraries/script-engine/src/ScriptEngine.cpp
Labels: Development Approved, Engine, Project Approved

#15861 DOC-66: Show deprecated notices for signals.
  tools/jsdoc/hifi-jsdoc-template/tmpl/signal.tmpl
Labels: Development Ready, JSDocs, Project Approved

#15869 [Dev-897] :: add unlit property to nametags
  scripts/simplifiedUI/ui/simplifiedNametag/resources/modules/defaultLocalEntityProps.js
Labels: Development Approved, Project Approved

#15862 BUGZ-838, BUGZ-850, BUGZ-853: Muted sign displays backwards in second person view, Fix lossy/duplicate color format conversions, Adjust wearables screen is flipped
  libraries/display-plugins/src/display-plugins/Basic2DWindowOpenGLDisplayPlugin.cpp
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.cpp
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.h
  libraries/display-plugins/src/display-plugins/hmd/HmdDisplayPlugin.cpp
  libraries/display-plugins/src/display-plugins/hmd/HmdDisplayPlugin.h
  libraries/gpu/src/gpu/DrawTextureLinearToSRGB.slf
  libraries/gpu/src/gpu/DrawTextureLinearToSRGB.slp
  libraries/gpu/src/gpu/DrawTextureMirroredX.slf
  libraries/gpu/src/gpu/DrawTextureMirroredX.slp
  libraries/gpu/src/gpu/DrawTextureOpaque.slf
  libraries/gpu/src/gpu/DrawTextureSRGBToLinear.slf
  libraries/gpu/src/gpu/DrawTextureSRGBToLinear.slp
  libraries/plugins/src/plugins/DisplayPlugin.h
  libraries/render-utils/src/RenderCommonTask.cpp
  libraries/render-utils/src/RenderForwardTask.cpp
  libraries/render-utils/src/RenderHUDLayerTask.cpp
  libraries/render-utils/src/hmd_ui.slf
  libraries/render-utils/src/toneMapping.slf
  libraries/render/src/render/Args.h
  libraries/render/src/render/ResampleTask.cpp
  libraries/render/src/render/ResampleTask.h
  plugins/oculus/src/OculusDisplayPlugin.cpp
Labels: Development Approved, Engine, Project Approved, Vive Required

#15870 BUGZ 887 Error in Webtablet.js
  script-archive/example/ui/MyEnergyBar.js
  script-archive/example/ui/energyBar.js
  scripts/simplifiedUI/system/libraries/WebTablet.js
  scripts/simplifiedUI/system/libraries/utils.js
  scripts/system/libraries/WebTablet.js
  scripts/system/libraries/utils.js
Labels: Development Approved, Project Approved, UI/UX, bug

#15874 [Bugz-893] :: Name tag in body fix
  scripts/simplifiedUI/ui/simplifiedNametag/resources/modules/nameTagListManager.js
Labels: Development Ready, Project Approved, QA Ready

#15876 Removed secondary camera tone mapping compensation
  interface/src/ui/Snapshot.cpp
Labels: Development Approved, Engine, Project Approved

#15868 case BUGZ-103: HMD Mouse rendering
  interface/src/Application.cpp
Labels: Development Ready, Engine, Project Approved

#15871 BUGZ-882: Improve error handling on Windows Launcher
  launchers/win32/Launcher.rc
  launchers/win32/LauncherApp.cpp
  launchers/win32/LauncherDlg.cpp
  launchers/win32/LauncherDlg.h
  launchers/win32/LauncherManager.cpp
  launchers/win32/LauncherManager.h
  launchers/win32/LauncherUtils.cpp
  launchers/win32/LauncherUtils.h
Labels: Client, Development Approved, Project Approved

#15878 BUGZ-911: Place selected audio I/O information in About tab and in 'Copy to Clipboard' clipboard text
  interface/resources/qml/hifi/simplifiedUI/settingsApp/about/About.qml
Labels: Development Approved, Project Approved, UI/UX

#15875 BUGZ-910: Return entity load priority operator to proper state after safe landing
  interface/src/octree/SafeLanding.cpp
  interface/src/octree/SafeLanding.h
  libraries/entities-renderer/src/EntityTreeRenderer.h
Labels: Development Approved, Engine, Project Approved

#15662 DEV-203: Add ability for .slp files to define shader variants
  cmake/macros/AutoScribeShader.cmake
  tools/shadergen.py
Labels: Development Approved, Engine, Feedback Welcome, Project Approved

#15879 BUGZ-845: Shut down interface when executing the Windows Launcher
  launchers/win32/LauncherApp.cpp
  launchers/win32/LauncherDlg.cpp
  launchers/win32/LauncherManager.cpp
  launchers/win32/LauncherUtils.cpp
  launchers/win32/LauncherUtils.h
Labels: Client, Development Approved, Project Approved

#15865 DOC-105: Pointers JSDoc revision
  interface/src/raypick/LaserPointerScriptingInterface.h
  interface/src/raypick/PickScriptingInterface.cpp
  interface/src/raypick/PickScriptingInterface.h
  interface/src/raypick/PointerScriptingInterface.cpp
  interface/src/raypick/PointerScriptingInterface.h
  interface/src/raypick/RayPickScriptingInterface.h
Labels: JSDocs

#15886 BUGZ-874: Don't shut down launcher's splash screen until interface's window is shown
  launchers/win32/LauncherApp.cpp
  launchers/win32/LauncherDlg.cpp
  launchers/win32/LauncherManager.cpp
  launchers/win32/LauncherUtils.cpp
  launchers/win32/LauncherUtils.h
Labels: Client, Development Approved, Project Approved

#15882 BUGZ-661: Fix Image Entity Y flip and Text Entity shutdown crash
  libraries/entities-renderer/src/RenderableImageEntityItem.cpp
  libraries/entities-renderer/src/RenderableTextEntityItem.cpp
Labels: Development Approved, Engine, Project Approved

#15892 BUGZ-917: Fix log spam in NameCard.qml
  interface/resources/qml/hifi/NameCard.qml
Labels: Development Approved, Project Approved, UI/UX, bug

#15891 BUGZ-923: Fix an edge case in Audio I/O devices in Settings -> About
  interface/resources/qml/hifi/simplifiedUI/settingsApp/about/About.qml
Labels: Development Approved, Project Approved, UI/UX, bug

#15888 BUGZ-706: Allow the launcher window to be moved
  launchers/win32/LauncherDlg.cpp
  launchers/win32/LauncherDlg.h
Labels: Client, Development Approved, Project Approved

#15894 BUGZ 915 Create does not work in HMD
  scripts/system/create/entityList/qml/EntityList.qml
  scripts/system/create/qml/EditTabView.qml
Labels: Development Approved, Project Approved, UI/UX, bug

#15884 BUGZ-736 / BUGZ-914 : Improve the enumeration of the platform and profiler / apply a specific PPI per Tier
  interface/src/PerformanceManager.cpp
  interface/src/scripting/PlatformInfoScriptingInterface.cpp
  interface/src/scripting/PlatformInfoScriptingInterface.h
  libraries/platform/src/platform/Platform.h
  libraries/platform/src/platform/PlatformKeys.h
  libraries/platform/src/platform/Profiler.cpp
  libraries/platform/src/platform/backend/AndroidPlatform.cpp
  libraries/platform/src/platform/backend/AndroidPlatform.h
  libraries/platform/src/platform/backend/LinuxPlatform.cpp
  libraries/platform/src/platform/backend/LinuxPlatform.h
  libraries/platform/src/platform/backend/MACOSPlatform.cpp
  libraries/platform/src/platform/backend/MACOSPlatform.h
  libraries/platform/src/platform/backend/Platform.cpp
  libraries/platform/src/platform/backend/PlatformInstance.cpp
  libraries/platform/src/platform/backend/PlatformInstance.h
  libraries/platform/src/platform/backend/WINPlatform.cpp
  libraries/platform/src/platform/backend/WINPlatform.h
  scripts/developer/utilities/lib/prop/PropGroup.qml
  scripts/developer/utilities/render/performanceSetup.qml
Labels: Development Approved, Engine, Project Approved, Scripting API change

#15890 BUGZ-930: No more auto-LOD adjustment for SimplifiedUI users
  scripts/simplifiedUI/ui/simplifiedUI.js
Labels: Development Approved, Project Approved, UI/UX

#15881 BUGZ-781: Additional debugging for dropped avatar data
  assignment-client/src/avatars/AvatarMixerSlave.cpp
  libraries/avatars/src/AvatarHashMap.cpp
Labels: Development Approved, Metaverse, Project Approved

#15887 BUGZ-926: use the correct gl format when creating the initial platform window
  interface/src/Application.cpp
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#15893 BUGZ-768: Keep config.json when updating to avoid relogin.
  launchers/win32/LauncherDlg.cpp
  launchers/win32/LauncherManager.cpp
  launchers/win32/LauncherUtils.cpp
  launchers/win32/LauncherUtils.h
Labels: Client, Development Approved, Project Approved

#15877 case BUGZ-690 & BUGZ382 : adding a null check escape to the activeItem. On right click back to …
  interface/src/Application.cpp
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#15898 log wakeup (on client and report to DS) during connection on Windows
  domain-server/src/DomainGatekeeper.cpp
  domain-server/src/DomainServer.cpp
  interface/src/Application.cpp
  libraries/networking/src/LimitedNodeList.cpp
  libraries/networking/src/LimitedNodeList.h
  libraries/networking/src/NodeList.cpp
Labels: Development Approved, Metaverse, Project Approved

#15903 BUGZ 951-952 Fix create for HMD
  interface/src/Application.cpp
  scripts/simplifiedUI/system/assets/images/hourglass.svg
  scripts/simplifiedUI/system/create/assets/data/createAppTooltips.json
  scripts/simplifiedUI/system/create/assets/images/hourglass.svg
  scripts/simplifiedUI/system/create/assets/images/icon-particles.svg
  scripts/simplifiedUI/system/create/assets/images/icon-point-light.svg
  scripts/simplifiedUI/system/create/assets/images/icon-spot-light.svg
  scripts/simplifiedUI/system/create/assets/images/icon-zone.svg
  scripts/simplifiedUI/system/create/edit.js
  scripts/simplifiedUI/system/create/entityList/entityList.js
  scripts/simplifiedUI/system/create/entityList/html/entityList.html
  scripts/simplifiedUI/system/create/entityList/html/js/entityList.js
  scripts/simplifiedUI/system/create/entityList/html/js/entityListContextMenu.js
  scripts/simplifiedUI/system/create/entityList/html/js/listView.js
  scripts/simplifiedUI/system/create/entityList/qml/EditEntityList.qml
  scripts/simplifiedUI/system/create/entityList/qml/EntityList.qml
  scripts/simplifiedUI/system/create/entityProperties/html/entityProperties.html
  scripts/simplifiedUI/system/create/entityProperties/html/js/createAppTooltip.js
  scripts/simplifiedUI/system/create/entityProperties/html/js/draggableNumber.js
  scripts/simplifiedUI/system/create/entityProperties/html/js/entityProperties.js
  scripts/simplifiedUI/system/create/entityProperties/html/js/underscore-min.js
  scripts/simplifiedUI/system/create/entitySelectionTool/entitySelectionTool.js
  scripts/simplifiedUI/system/create/modules/createWindow.js
  scripts/simplifiedUI/system/create/modules/entityShapeVisualizer.js
  scripts/simplifiedUI/system/create/qml/Edit.qml
  scripts/simplifiedUI/system/create/qml/EditTabButton.qml
  scripts/simplifiedUI/system/create/qml/EditTabView.qml
  scripts/simplifiedUI/system/create/qml/EditTools.qml
  scripts/simplifiedUI/system/create/qml/EditToolsTabView.qml
  scripts/simplifiedUI/system/create/qml/NewEntityButton.qml
  scripts/simplifiedUI/system/create/qml/NewMaterialDialog.qml
  scripts/simplifiedUI/system/create/qml/NewMaterialWindow.qml
  scripts/simplifiedUI/system/create/qml/NewModelDialog.qml
  scripts/simplifiedUI/system/create/qml/NewModelWindow.qml
  scripts/simplifiedUI/system/create/qml/icons/126-material-01.svg
  scripts/simplifiedUI/system/create/qml/icons/20-text-01.svg
  scripts/simplifiedUI/system/create/qml/icons/21-cube-01.svg
  scripts/simplifiedUI/system/create/qml/icons/22-sphere-01.svg
  scripts/simplifiedUI/system/create/qml/icons/23-zone-01.svg
  scripts/simplifiedUI/system/create/qml/icons/24-light-01.svg
  scripts/simplifiedUI/system/create/qml/icons/25-web-1-01.svg
  scripts/simplifiedUI/system/create/qml/icons/90-particles-01.svg
  scripts/simplifiedUI/system/create/qml/icons/94-model-01.svg
  scripts/simplifiedUI/system/create/qml/icons/image.svg
  scripts/simplifiedUI/system/keyboardShortcuts/keyboardShortcuts.js
  scripts/system/create/qml/Edit.qml
  scripts/system/create/qml/NewModelDialog.qml
Labels: Create, Development Approved, QA Approved :tada:, bug

#15900 DEV-180: Lilypad Launcher: (Mac) Launcher progress indicator
  launchers/darwin/nib/ProcessScreen.xib
  launchers/darwin/src/CustomUI.h
  launchers/darwin/src/CustomUI.m
  launchers/darwin/src/DownloadDomainContent.h
  launchers/darwin/src/DownloadDomainContent.m
  launchers/darwin/src/DownloadInterface.h
  launchers/darwin/src/DownloadInterface.m
  launchers/darwin/src/ErrorViewController.m
  launchers/darwin/src/LatestBuildRequest.m
  launchers/darwin/src/Launcher.h
  launchers/darwin/src/Launcher.m
  launchers/darwin/src/LoginScreen.m
  launchers/darwin/src/ProcessScreen.m
Labels: Development Approved, Project Approved

#15902 DEV-179: Windows Launcher progress indicator
  launchers/win32/Launcher.rc
  launchers/win32/LauncherDlg.cpp
  launchers/win32/LauncherDlg.h
  launchers/win32/LauncherManager.cpp
  launchers/win32/LauncherManager.h
  launchers/win32/LauncherUtils.cpp
  launchers/win32/LauncherUtils.h
  launchers/win32/resource.h
Labels: Client, Development Approved, Project Approved

#15897 Implement DEV-218 & DEV-219 and commit a starting point for the Emote app
  interface/resources/qml/InteractiveWindow.qml
  interface/resources/qml/hifi/simplifiedUI/emoteApp/bar/EmoteAppBar.qml
  interface/resources/qml/hifi/simplifiedUI/simplifiedConstants/SimplifiedConstants.qml
  interface/src/ui/InteractiveWindow.cpp
  scripts/developer/tests/interactiveWindowTest.js
  scripts/developer/utilities/render/engineProfiler.js
  scripts/developer/utilities/render/lod.js
  scripts/developer/utilities/workload/avatars.js
  scripts/developer/utilities/workload/workload.js
  scripts/simplifiedUI/system/create/modules/createWindow.js
  scripts/simplifiedUI/ui/simplifiedUI.js
  scripts/system/create/edit.js
  scripts/system/create/modules/createWindow.js
Labels: Development Approved, Project Approved, UI/UX

#15866 DEV-164: Add defaultScriptsOverride option
  interface/src/Application.cpp
  interface/src/main.cpp
  libraries/script-engine/src/ScriptEngines.cpp
  libraries/script-engine/src/ScriptEngines.h
Labels: Client, Development Approved, Project Approved

#15904 new-account wallets in simplified UI
  interface/resources/qml/hifi/simplifiedUI/topBar/SimplifiedTopBar.qml
Labels: Development Approved, Metaverse, Project Approved, QA Approved :tada:, UI/UX

#15908 BUGZ-918: Verbose RSA-keypair logging
  libraries/networking/src/RSAKeypairGenerator.cpp
Labels: Development Approved, Metaverse, Project Approved

#15899 Case bugz-907: On launch default to non hmd device
  interface/src/Application.cpp
Labels: Development Approved, Engine, Project Approved

#15909 BUGZ-656: Trim spaces for orgname and username fields on Windows Launcher
  launchers/win32/LauncherDlg.cpp
Labels: Client, Development Approved, Project Approved

#15905 BUGZ-967: Fix text visibility toggle
  libraries/entities-renderer/src/RenderableEntityItem.cpp
  libraries/entities-renderer/src/RenderableTextEntityItem.cpp
Labels: Development Approved, Engine, Project Approved

#15910 DEV-166: Instrument the Windows Launcher to use the defaultScriptsOverride parameter
  launchers/win32/LauncherManager.cpp
Labels: Client, Development Ready, Project Approved

#15915 DEV-172: Lilypad Launcher (Mac): Instrument the launcher to use the new "override default scripts" command line switch
  launchers/darwin/src/Launcher.m
Labels: Client, Development Approved, Project Approved

#15917 disabled P shortcut and re-enabled in metaverse
  interface/src/Application.cpp
  scripts/system/keyboardShortcuts/keyboardShortcuts.js
Labels: Development Approved, Project Approved, UI/UX

#15912 BUGZ-918: Generate RSA key-pair early in start-up
  interface/src/Application.cpp
  libraries/networking/src/AccountManager.cpp
  libraries/networking/src/AccountManager.h
Labels: Development Approved, Metaverse, Project Approved

#15873 BUGZ-820: Remove QT_CMAKE_PREFIX_PATH prod hack
  cmake/macros/SetupQt.cmake
  hifi_vcpkg.py
Labels: DO NOT MERGE

#15924 Move debian packaging files to hifi repo
  tools/ci-scripts/linux-package-release/after-install.sh
  tools/ci-scripts/linux-package-release/assignment-client-before-install.sh
  tools/ci-scripts/linux-package-release/before-remove.sh
  tools/ci-scripts/linux-package-release/domain-server-before-install.sh
  tools/ci-scripts/linux-package-release/hifi-assignment-client
  tools/ci-scripts/linux-package-release/hifi-domain-server
  tools/ci-scripts/linux-package-release/hifi-ice-server
  tools/ci-scripts/linux-package-release/ice-server-before-install.sh
  tools/ci-scripts/linux-package-release/package-and-upload.sh
Labels: Development Ready, Project Approved

#15925 Use absolute path in ci script
  tools/ci-scripts/linux-package-release/package-and-upload.sh
Labels: Development Ready

#15843 Fix ScriptEngines::loadScript invoke call
  libraries/script-engine/src/ScriptEngines.cpp
Labels: Development Approved, Engine, Open Source, Project Approved

#15880 BUGZ-863: wait for objects to be added to physics before completing SafeLanding
  interface/src/avatar/OtherAvatar.cpp
  interface/src/octree/SafeLanding.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.h
  libraries/physics/src/PhysicalEntitySimulation.cpp
  libraries/workload/src/workload/Region.h
  libraries/workload/src/workload/RegionState.cpp
  libraries/workload/src/workload/RegionState.h
  libraries/workload/src/workload/RegionTracker.cpp
  libraries/workload/src/workload/Space.cpp
  libraries/workload/src/workload/View.cpp
  libraries/workload/src/workload/View.h
  libraries/workload/src/workload/ViewTask.cpp
  libraries/workload/src/workload/ViewTask.h
Labels: Development Approved, Engine, Project Approved

#15911 case Bugz-968 adding a null check to the display plugin. Possible that display plug…
  interface/src/Application.cpp
  libraries/display-plugins/src/display-plugins/AbstractHMDScriptingInterface.cpp
Labels: Development Approved, Engine, Project Approved

#15916 BUGZ-989: Get recent builds asynchronously while the windows launcher is showing the splash screen
  launchers/win32/LauncherDlg.cpp
  launchers/win32/LauncherManager.cpp
  launchers/win32/LauncherManager.h
  launchers/win32/LauncherUtils.cpp
  launchers/win32/LauncherUtils.h
Labels: Client, Development Approved, Project Approved

#15918 New Settings -> Graphics... dialog for Classic UI users
  interface/resources/qml/controlsUit/ComboBox.qml
  interface/resources/qml/hifi/dialogs/graphics/GraphicsSettings.qml
  interface/src/Menu.cpp
  interface/src/PerformanceManager.cpp
  interface/src/scripting/PlatformInfoScriptingInterface.cpp
  interface/src/scripting/PlatformInfoScriptingInterface.h
Labels: Development Approved, Engine, Project Approved, Scripting API change, UI/UX

#15919 Mac sleep monitor
  interface/src/Application.cpp
  interface/src/MacHelper.cpp
  interface/src/MacHelper.h
Labels: Development Approved, Metaverse, Project Approved

#15927 Possible fix for shader compilation error
  libraries/render-utils/src/ssao_gather.slf
Labels: Development Approved, Engine, Open Source, Project Approved

#15761 BUGZ-400: Crash in Application::notify
  interface/src/scripting/DesktopScriptingInterface.cpp
  interface/src/scripting/DesktopScriptingInterface.h
  interface/src/ui/InteractiveWindow.cpp
  interface/src/ui/InteractiveWindow.h
Labels: Client, Development Approved, Project Approved

#15533 Case 21663: comfort mode
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/VisionSqueeze.cpp
  interface/src/VisionSqueeze.h
  interface/src/avatar/MyAvatar.cpp
  interface/src/scripting/HMDScriptingInterface.cpp
  interface/src/scripting/HMDScriptingInterface.h
  interface/src/ui/PreferencesDialog.cpp
  libraries/display-plugins/src/display-plugins/DrawTextureWithVisionSqueeze.slf
  libraries/display-plugins/src/display-plugins/DrawTextureWithVisionSqueeze.slp
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.cpp
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.h
  libraries/display-plugins/src/display-plugins/VisionSqueeze.slh
  libraries/display-plugins/src/display-plugins/hmd/HmdDisplayPlugin.cpp
  libraries/display-plugins/src/display-plugins/hmd/HmdDisplayPlugin.h
  libraries/gpu/src/gpu/Context.cpp
  libraries/plugins/src/plugins/DisplayPlugin.h
  libraries/render/src/render/Args.h
  plugins/oculus/src/OculusDisplayPlugin.cpp
  plugins/openvr/src/OpenVrDisplayPlugin.cpp
  plugins/openvr/src/OpenVrDisplayPlugin.h
Labels: Design, Development Approved, HMD required, Project Approved, Scripting API change

#15923 BUGZ-991: Added conditionals to shortcuts to remove overlap
  scripts/system/keyboardShortcuts/keyboardShortcuts.js
Labels: Development Approved, UI/UX, bug

#15931 Fix debug builds not compiling
  libraries/workload/src/workload/RegionState.cpp
Labels: Development Approved, Engine, Project Approved

#15933 BUGZ-1014: Crash when opening Create
  interface/src/scripting/DesktopScriptingInterface.cpp
  interface/src/ui/InteractiveWindow.cpp
Labels: Client, Development Approved, Project Approved

#15935 BUGZ-1017: fix bug that caused comfort-mode to be active at all times in HMD
  libraries/display-plugins/src/display-plugins/hmd/HmdDisplayPlugin.cpp
  plugins/oculus/src/OculusDisplayPlugin.cpp
Labels: Development Approved, Engine, HMD required, Project Approved, QA Approved :tada:, bug

#15929 add teleport.fbx back to avatar/animations
  interface/resources/avatar/animations/teleport.fbx
Labels: Avatar, Development Approved, QA Approved :tada:

#15938 Warning fixes for MacOSX
  libraries/animation/src/AnimInverseKinematics.cpp
  plugins/oculusLegacy/src/OculusLegacyDisplayPlugin.cpp
Labels: Avatar, Development Approved, Engine, Project Approved

#15941 Fix BUGZ-814 in VR mode: Add a top margin to tablet graphics settings
  interface/resources/qml/hifi/dialogs/graphics/GraphicsSettings.qml
Labels: Development Approved, Project Approved, UI/UX, bug

#15932 BUGZ-781: Remove loading-orb upon killing of avatar
  interface/src/avatar/AvatarManager.cpp
  interface/src/avatar/OtherAvatar.cpp
Labels: Development Approved, Metaverse, Project Approved

#15937 [BUGZ-537] :: removed session display name from nametag
  scripts/simplifiedUI/ui/simplifiedNametag/resources/modules/nameTagListManager.js
  scripts/simplifiedUI/ui/simplifiedStatusIndicator/simplifiedStatusIndicator.js
Labels: Development Approved, Project Approved, UI/UX

#15942 DEV-262 - Improve logging on failure to load resource
  libraries/networking/src/ResourceCache.cpp
Labels: Development Approved, Metaverse, Project Approved

#15940 BUGZ-753: bad skyboxes on Intel GPUs
  libraries/gl/src/gl/GLHelpers.cpp
  libraries/gl/src/gl/GLHelpers.h
  tests-manual/gpu/CMakeLists.txt
Labels: Development Approved, Project Approved, QA Approved :tada:

#15943 [Bugz-1039] :: changed sessionDisplayName logic
  interface/resources/qml/hifi/simplifiedUI/avatarApp/components/DisplayNameHeader.qml
Labels: Development Approved, Project Approved

#15928 BUGZ-942: fix SafeLanding to not accidentally "neglect to track" incoming entity packet when connecting to new domain
  interface/src/Application.cpp
  interface/src/octree/OctreePacketProcessor.cpp
  interface/src/octree/OctreePacketProcessor.h
  interface/src/octree/SafeLanding.cpp
  interface/src/octree/SafeLanding.h
Labels: Development Approved, Engine, Project Approved

#15945 BUGZ-998: Fix create window being destroyed when closed
  interface/resources/qml/InteractiveWindow.qml
Labels: Development Approved, Development Ready, Project Approved

#15952 Fix BUGZ-1062: Set the correct Settings value for bubble tools
  interface/src/ui/AvatarInputs.cpp
Labels: Client, Development Approved, Project Approved, bug

#15926 DOC-115: Comfort mode JSDoc
  interface/src/scripting/HMDScriptingInterface.h
Labels: DO NOT MERGE, JSDocs

#15946 BUGZ-870: MyAvatar's scripted motor needs to filter against NaN input
  interface/src/avatar/MyAvatar.cpp
Labels: Development Approved, Engine, Project Approved

#15954 BUGZ-1022: Restore avatar theft functionality to Lilypad
  assignment-client/src/avatars/AvatarMixerClientData.cpp
  scripts/system/clickToAvatarApp.js
Labels: Avatar, Development Approved, Metaverse, Project Approved

#15953 DOC-123: AvatarInputs JSDoc
  interface/src/ui/AvatarInputs.h
Labels: JSDocs

#15944 DEV-117: the signing of MAC HQ launcher AND the interface exe
  interface/CMakeLists.txt
  interface/interface.entitlements
  launchers/darwin/CMakeLists.txt
  launchers/darwin/HQ Launcher.entitlements
  tools/ci-scripts/postbuild.py
Labels: Client, Development Approved, Development Ready, Project Approved

#15934 DOC-62: Reticle JSDoc
  libraries/display-plugins/src/display-plugins/CompositorHelper.h
Labels: JSDocs

#15950 DOC-121: AvatarBookmarks JSDoc
  interface/src/AvatarBookmarks.cpp
  interface/src/AvatarBookmarks.h
  interface/src/avatar/AvatarManager.h
  interface/src/avatar/MyAvatar.h
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
Labels: DO NOT MERGE, JSDocs

#15913 DOC-102: Overlays JSDoc Update
  interface/src/raypick/PickScriptingInterface.h
  interface/src/raypick/RayPickScriptingInterface.h
  interface/src/scripting/Audio.h
  interface/src/scripting/HMDScriptingInterface.h
  interface/src/scripting/WindowScriptingInterface.h
  interface/src/ui/overlays/Overlays.cpp
  interface/src/ui/overlays/Overlays.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityScriptingInterface.h
  libraries/entities/src/ShapeEntityItem.cpp
  libraries/pointers/src/Pick.h
  libraries/shared/src/PickFilter.h
  libraries/shared/src/RenderLayer.h
Labels: JSDocs

#15921 Make Create app use Ctrl key to duplicate entities instead of Alt
  scripts/system/create/entitySelectionTool/entitySelectionTool.js
Labels: Development Approved, Documentation, Open Source, Project Approved

#15961 Revert "Merge pull request #15944 from danteruiz/add-signing"
  interface/CMakeLists.txt
  interface/interface.entitlements
  launchers/darwin/CMakeLists.txt
  launchers/darwin/HQ Launcher.entitlements
  tools/ci-scripts/postbuild.py
Labels: Client, Development Approved, Project Approved

#15951 DOC-122: LocationBookmarks JSDoc
  interface/src/Bookmarks.h
  interface/src/LocationBookmarks.h
Labels: JSDocs, Project Approved

#15957 BUGZ-937: more readable debug stats on MacOS
  interface/resources/qml/StatText.qml
Labels: Development Approved, Engine, Project Approved

#15948 Packet dissectors: Don't read HMAC for 'nonverified' packets
  tools/dissectors/1-hfudt.lua
Labels: Development Approved, Metaverse, Packet Dissectors, Project Approved

#15963 Initial version of Avatar Reaction API
  interface/resources/avatar/animations/emote_agree_acknowledge.fbx
  interface/resources/avatar/animations/emote_clap01_all.fbx
  interface/resources/avatar/animations/emote_disagree_defeated.fbx
  interface/resources/avatar/animations/emote_point01_all.fbx
  interface/resources/avatar/animations/emote_raisehand01_all.fbx
  interface/resources/avatar/avatar-animation.json
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  interface/src/avatar/MySkeletonModel.cpp
  libraries/animation/src/Rig.cpp
  libraries/animation/src/Rig.h
  libraries/shared/src/AvatarConstants.h
Labels: Avatar, Development Approved, Project Approved, Scripting API change

#15967 (BUGZ-955) Disable unnecessary picking (conservative subset)
  scripts/system/controllers/controllerDispatcher.js
  scripts/system/controllers/controllerModules/mouseHMD.js
  scripts/system/controllers/controllerModules/teleport.js
  scripts/system/controllers/grab.js
Labels: Development Approved, Engine, HMD required, Project Approved, UI/UX

#15966 BUGZ-987: fix depth testing of HUD layer 3D objects
  libraries/gpu/src/gpu/Format.cpp
  libraries/gpu/src/gpu/Format.h
  libraries/render-utils/src/FramebufferCache.cpp
Labels: Development Approved, Engine, Project Approved

#15956 Force build with x64 toolchain
  BUILD_WIN.md
  CMakeLists.txt
Labels: Development Approved, Project Approved

#15939 Condense directional light shaders using slp defines
  libraries/render-utils/src/DeferredLightingEffect.cpp
  libraries/render-utils/src/directional_ambient_light.slf
  libraries/render-utils/src/directional_ambient_light_shadow.slf
  libraries/render-utils/src/directional_skybox_light.slf
  libraries/render-utils/src/directional_skybox_light_shadow.slf
  libraries/render-utils/src/render-utils/directional_ambient_light.slp
  libraries/render-utils/src/render-utils/directional_ambient_light_shadow.slp
  libraries/render-utils/src/render-utils/directional_skybox_light.slp
  libraries/render-utils/src/render-utils/directional_skybox_light_shadow.slp
Labels: Development Approved, Development Ready, Engine, Open Source, Project Approved

#15970 Make sure the send thread terminates before delete
  assignment-client/src/octree/OctreeServer.cpp
Labels: Development Approved, Project Approved

#15969 BUGZ-1015: Don't store unused cpuident data arrays
  libraries/shared/src/CPUIdent.cpp
  libraries/shared/src/CPUIdent.h
Labels: Critical Fix, Development Approved, Engine, Metaverse, Project Approved, bug

#15960 Fix link to coding standards
  README.md
Labels: Development Approved, Open Source, Project Approved

#15968 BUGZ-996: Android app crashes on startup
  libraries/platform/src/platform/backend/PlatformInstance.cpp
Labels: Development Approved, Engine, Project Approved

#15955 DEV-220: Lilypad Launcher: (Mac) Add versioning info to Launcher screen
  launchers/darwin/CMakeLists.txt
  launchers/darwin/cmake/macros/SetPackagingParameters.cmake
  launchers/darwin/nib/DisplayNameScreen.xib
  launchers/darwin/nib/ErrorScreen.xib
  launchers/darwin/nib/LoginScreen.xib
  launchers/darwin/nib/ProcessScreen.xib
  launchers/darwin/nib/SplashScreen.xib
  launchers/darwin/src/DisplayNameScreen.m
  launchers/darwin/src/ErrorViewController.m
  launchers/darwin/src/LoginScreen.m
  launchers/darwin/src/ProcessScreen.m
  launchers/darwin/src/SplashScreen.m
Labels: Client, Development Approved, Project Approved

#15972 DEV-301: Adjust size of VR-mode header icon
  interface/resources/qml/hifi/simplifiedUI/topBar/SimplifiedTopBar.qml
Labels: Development Approved, Project Approved, UI/UX

#15973 BUGZ-972: Fix errant log involving 'gated' property
  interface/resources/qml/hifi/audio/MicBarApplication.qml
Labels: Development Approved, Project Approved, UI/UX, bug

#15975 BUGZ-1028: Fix qmlToScript getting called on script thread and causing crash
  interface/src/ui/InteractiveWindow.cpp
Labels: Client, Development Approved, Project Approved

#15979 fix android local build
  CMakeLists.txt
Labels: Development Approved, Project Approved

#15984 BUGZ-969: Remove some audio-related code that hasn't worked in a while
  interface/resources/html/createGlobalEventBridge.js
Labels: Client, Development Approved, Project Approved, bug

#15980 BUGZ-985: Guard against AudioInjectorManager takedown in scripted audio injector destructor
  interface/src/Application.cpp
  libraries/script-engine/src/ScriptAudioInjector.cpp
Labels: Development Approved, Project Approved, bug

#15981 DEV-243 | DEV-221: Display Window Launcher version number and autoupdate
  launchers/win32/CMakeLists.txt
  launchers/win32/Launcher.rc
  launchers/win32/LauncherApp.cpp
  launchers/win32/LauncherDlg.cpp
  launchers/win32/LauncherDlg.h
  launchers/win32/LauncherManager.cpp
  launchers/win32/LauncherManager.h
  launchers/win32/cmake/macros/SetPackagingParameters.cmake
  launchers/win32/resource.h
Labels: Client, Development Approved, Project Approved

#15976 DEV-266: Add serverless tutorial
  cmake/macros/SetPackagingParameters.cmake
  interface/resources/serverless/tutorial.json
  libraries/networking/src/AddressManager.cpp
Labels: Client, Development Approved, Project Approved

#15986 Fix non-functional Create
  interface/src/ui/InteractiveWindow.cpp
  interface/src/ui/InteractiveWindow.h
Labels: Client, Development Approved, Project Approved

#15987 DEV-317: Edit postbiuld.py to produce zip file for the Mac Launcher.
  tools/ci-scripts/postbuild.py
Labels: Client, Development Approved, Project Approved

#15989 [BUGZ-1073] - Add extra padding to the nametag
  scripts/simplifiedUI/ui/simplifiedNametag/resources/modules/nameTagListManager.js
Labels: Development Approved, Project Approved

#15977 [DEV-190] + [DEV-191] :: Permissions UI
  interface/resources/qml/+webengine/TabletBrowser.qml
  interface/resources/qml/controls/+webengine/FlickableWebViewCore.qml
  interface/resources/qml/controlsUit/+webengine/BaseWebView.qml
  interface/resources/qml/controlsUit/PermissionPopup.qml
  interface/resources/qml/controlsUit/PermissionPopupBackground.qml
  interface/resources/qml/controlsUit/qmldir
Labels: Development Approved, Project Approved, QA Approved :tada:, UI/UX

#15993 BUGZ-815: WL Display error when connection fails
  launchers/win32/LauncherManager.cpp
Labels: Client, Development Approved, Project Approved

#15974 DEV-269: First Class Sitting API
  interface/resources/avatar/animations/sitting_idle.fbx
  interface/resources/avatar/avatar-animation.json
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  interface/src/avatar/MySkeletonModel.cpp
  libraries/animation/src/Rig.cpp
  libraries/animation/src/Rig.h
  libraries/physics/src/CharacterController.cpp
  libraries/physics/src/CharacterController.h
Labels: Avatar, Development Approved, Project Approved, Scripting API change

#15983 BUGZ-1080: Changing the default Intel GPU platform profile from mid to low
  libraries/platform/src/platform/Profiler.cpp
Labels: Development Approved, Engine, Project Approved

#15982 (BUGZ-1040) Fix LOD randomly being too low in simplified UI
  interface/src/LODManager.cpp
  interface/src/LODManager.h
  scripts/simplifiedUI/ui/simplifiedUI.js
Labels: Development Approved, Engine, Scripting API change

#15996 BUGZ-1101: Improved diagnostics for avatar-verify failures in mixer
  assignment-client/src/avatars/MixerAvatar.cpp
Labels: Development Approved, Metaverse, Project Approved

#15994 steam gets the oculus store commerce treatment
  interface/src/Application.cpp
Labels: DO NOT MERGE, Metaverse, Project Approved

#15995 BUGZ 1029: changing raw pointer to unique pointer with custom deleter
  interface/src/ui/InteractiveWindow.cpp
  interface/src/ui/InteractiveWindow.h
Labels: Development Approved, Engine, Project Approved

#16000 Avatar verification more diagnostics 83
  assignment-client/src/avatars/MixerAvatar.cpp
Labels: Metaverse, Project Approved

#15978 BUGZ-829 DEV-168 - domain backup/content management improvements
  domain-server/resources/describe-settings.json
  domain-server/resources/web/content/js/content.js
  domain-server/resources/web/js/domain-server.js
  domain-server/resources/web/js/shared.js
  domain-server/src/AssetsBackupHandler.cpp
  domain-server/src/AssetsBackupHandler.h
  domain-server/src/BackupHandler.h
  domain-server/src/ContentSettingsBackupHandler.cpp
  domain-server/src/ContentSettingsBackupHandler.h
  domain-server/src/DomainContentBackupManager.cpp
  domain-server/src/DomainContentBackupManager.h
  domain-server/src/DomainServer.cpp
  domain-server/src/DomainServer.h
  domain-server/src/DomainServerSettingsManager.h
  domain-server/src/EntitiesBackupHandler.cpp
  domain-server/src/EntitiesBackupHandler.h
  interface/resources/qml/hifi/commerce/checkout/Checkout.qml
  interface/resources/qml/hifi/commerce/marketplaceItemTester/ItemUnderTest.qml
  interface/resources/qml/hifi/commerce/purchases/PurchasedItem.qml
  interface/resources/qml/hifi/commerce/purchases/Purchases.qml
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/commerce/QmlCommerce.cpp
  interface/src/commerce/QmlCommerce.h
  libraries/embedded-webserver/src/HTTPConnection.cpp
  libraries/embedded-webserver/src/HTTPConnection.h
Labels: Development Approved, Metaverse, QA Approved :tada:

#15999 Steam store commerce 83
  interface/src/Application.cpp
Labels: Metaverse, Project Approved

#16002 [BUGZ-972] :: changed root to micBar which had the gated property
  interface/resources/qml/hifi/audio/MicBarApplication.qml
Labels: Development Approved, Project Approved

#15991 BUGZ-964: fix for incorrect color curve when rendering 3D into QML
  interface/src/ui/ResourceImageItem.cpp
  interface/src/ui/ResourceImageItem.h
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, QA Approved :tada:

#16006 BUGZ-964: fix for incorrect color curve when rendering 3D into QML
  interface/src/ui/ResourceImageItem.cpp
  interface/src/ui/ResourceImageItem.h
Labels: Development Approved, Project Approved

#16010 changed root to micBar which had the gated property
  interface/resources/qml/hifi/audio/MicBarApplication.qml
Labels: Development Approved, Development Ready, Project Approved

#15997 DEV-243: WL Fix auto-installer bugs
  launchers/win32/LauncherApp.cpp
  launchers/win32/LauncherDlg.cpp
  launchers/win32/LauncherManager.cpp
  launchers/win32/LauncherManager.h
Labels: Client, Development Approved, Project Approved

#15990 BUGZ-984: Delete script audio-injector wrapper when wrapped object is deleted
  libraries/script-engine/src/ScriptAudioInjector.cpp
  libraries/script-engine/src/ScriptAudioInjector.h
Labels: Client, Metaverse, Project Approved, QA Approved :tada:
