Repository highfidelity/hifi, pull requests merged in 2019-03, with the labels that each got.

#15054 Case 21484: Fix context overlay (RC80)
  interface/src/ui/overlays/ContextOverlayInterface.cpp
  interface/src/ui/overlays/ContextOverlayInterface.h
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#15053 Case 21486: Fix context overlay
  interface/src/ui/overlays/ContextOverlayInterface.cpp
  interface/src/ui/overlays/ContextOverlayInterface.h
Labels: Development Approved, Engine, Project Approved

#15056 Case 21160: Tablet does not properly resize when scaling avatar.
  libraries/entities-renderer/src/RenderableWebEntityItem.cpp
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityPropertyFlags.h
  libraries/entities/src/ModelEntityItem.cpp
  libraries/entities/src/ModelEntityItem.h
  libraries/networking/src/udt/PacketHeaders.h
  libraries/physics/src/ObjectActionTractor.cpp
  libraries/shared/src/NestableTransformNode.h
  libraries/shared/src/SpatiallyNestable.cpp
  libraries/shared/src/SpatiallyNestable.h
  scripts/system/controllers/controllerModules/nearParentGrabOverlay.js
  scripts/system/libraries/WebTablet.js
  scripts/system/libraries/utils.js
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Packet Version Change, Project Approved, QA Approved :tada:

#15051 Case 21219: Limit new connection rate to the avatar mixer
  assignment-client/src/avatars/AvatarMixer.cpp
  domain-server/resources/describe-settings.json
  domain-server/src/DomainServer.cpp
  libraries/networking/src/LimitedNodeList.cpp
  libraries/networking/src/LimitedNodeList.h
  libraries/networking/src/NodeList.cpp
Labels: Development Approved, Metaverse, Project Approved, QA Approved :tada:

#15057 Case 21483: Fix lasers and keyboard on reload (RC80)
  interface/src/Application.cpp
  interface/src/ui/Keyboard.cpp
  interface/src/ui/Keyboard.h
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#15050 Case 21446: clear workload::Space proxies for old content when switching domains
  interface/src/Application.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities/src/EntityTree.cpp
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#15062 Case 21489: Fix chat.js textSize (RC80)
  scripts/system/chat.js
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#15063 Case 21496: Fix chat.js textSize
  scripts/system/chat.js
Labels: Development Approved, Engine

#15058 Case 21490: Fix lasers and keyboard on reload
  interface/src/Application.cpp
  interface/src/ui/Keyboard.cpp
  interface/src/ui/Keyboard.h
Labels: Development Approved, Engine, Project Approved

#15060 Case 21494: Avoid mem leaked entities
  interface/src/Application.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities/src/EntityTree.cpp
Labels: Development Approved, Engine, Project Approved

#15019 Case 21422: fix crash for nullptr deref when looking at recently uploaded avatar in inventory
  interface/src/avatar/AvatarProject.cpp
Labels: Create, Development Approved, Project Approved

#15022 Case 21424: Tablet does not properly resize when scaling avatar.
  libraries/entities-renderer/src/RenderableWebEntityItem.cpp
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityPropertyFlags.h
  libraries/entities/src/ModelEntityItem.cpp
  libraries/entities/src/ModelEntityItem.h
  libraries/networking/src/udt/PacketHeaders.h
  libraries/physics/src/ObjectActionTractor.cpp
  libraries/shared/src/NestableTransformNode.h
  libraries/shared/src/SpatiallyNestable.cpp
  libraries/shared/src/SpatiallyNestable.h
  scripts/system/controllers/controllerModules/nearParentGrabOverlay.js
  scripts/system/libraries/WebTablet.js
  scripts/system/libraries/utils.js
Labels: Development Approved, Engine, Packet Version Change, Project Approved

#15065 Case 21264: HMD Login Encouragement Screen is not Usable
  interface/src/Application.cpp
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#15061 [MS#21495] Enable Bubble/Shield on Away
  scripts/system/away.js
Labels: Design, Development Approved, Project Approved, QA Approved :tada:

#14991 Case 21379: Remove nitpick installer from Linux
  tools/CMakeLists.txt
  tools/nitpick/CMakeLists.txt
Labels: Development Approved, Engine, Project Approved, nitpick

#15066 Case 19188: Potential 2D overlay + Tablet threading fixes
  interface/src/ui/overlays/Overlay.cpp
  interface/src/ui/overlays/Overlay.h
  interface/src/ui/overlays/Overlay2D.cpp
  interface/src/ui/overlays/Overlay2D.h
  interface/src/ui/overlays/Overlays.cpp
  interface/src/ui/overlays/QmlOverlay.cpp
  interface/src/ui/overlays/QmlOverlay.h
  libraries/ui/src/ui/TabletScriptingInterface.cpp
Labels: Beware: Threading/Deadlock, Development Approved, Engine

#15064 Case 21451: HMD Login Encouragement Screen is not Usable
  interface/src/Application.cpp
Labels: Development Approved, Engine, Project Approved

#15068 Fix for case when animated joints are missing from the target avatar
  libraries/animation/src/AnimClip.cpp
  libraries/animation/src/AnimSkeleton.cpp
  libraries/animation/src/AnimSkeleton.h
Labels: Development Approved, Project Approved

#15059 Case 21492 - High incoming datagram traffic blocks ac->domain server ping
  assignment-client/src/avatars/AvatarMixer.cpp
  libraries/networking/src/NodeList.cpp
  libraries/networking/src/ThreadedAssignment.cpp
Labels: Development Approved, Metaverse, Project Approved, QA Approved :tada:

#15070 Case 21508: Fix audio mixer deadlock
  assignment-client/src/audio/AudioMixerSlavePool.cpp
  assignment-client/src/avatars/AvatarMixer.cpp
  assignment-client/src/avatars/AvatarMixerSlavePool.cpp
  libraries/networking/src/LimitedNodeList.cpp
  libraries/networking/src/LimitedNodeList.h
Labels: Development Approved, Metaverse, Project Approved, QA Approved :tada:

#15043 FarGrab Entity Rotation with Off-Hand
  scripts/system/controllers/controllerModules/farGrabEntity.js
Labels: Design, Development Approved, HMD required, Project Approved

#15052 case 21485: removing quest-demo specific changes
  android/apps/interface/build.gradle
  android/apps/keystore.jks
  android/apps/questInterface/build.gradle
  android/apps/questInterface/src/main/cpp/native.cpp
  android/apps/questInterface/src/main/java/io/highfidelity/questInterface/InterfaceActivity.java
  android/apps/questInterface/src/main/java/io/highfidelity/questInterface/PermissionsChecker.java
  android/build_android.sh
  android/containerized_build.sh
  android/docker/Dockerfile
  android/libraries/oculus/src/main/java/io/highfidelity/oculus/OculusMobileActivity.java
  android/libraries/qt/src/main/java/org/qtproject/qt5/android/bindings/QtActivity.java
  interface/src/AndroidHelper.cpp
  interface/src/AndroidHelper.h
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/LODManager.h
  libraries/animation/src/AnimInverseKinematics.cpp
  libraries/animation/src/Rig.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.cpp
  libraries/display-plugins/src/display-plugins/SrgbToLinear.slf
  libraries/display-plugins/src/display-plugins/SrgbToLinear.slp
  libraries/entities-renderer/src/RenderablePolyLineEntityItem.cpp
  libraries/entities-renderer/src/RenderableShapeEntityItem.cpp
  libraries/entities-renderer/src/entities-renderer/paintStroke_forward.slp
  libraries/entities-renderer/src/paintStroke_forward.slf
  libraries/gpu/src/gpu/Color.slh
  libraries/gpu/src/gpu/DrawTextureGammaLinearToSRGB.slf
  libraries/gpu/src/gpu/DrawTextureGammaLinearToSRGB.slp
  libraries/gpu/src/gpu/DrawTextureGammaSRGBToLinear.slf
  libraries/gpu/src/gpu/DrawTextureGammaSRGBToLinear.slp
  libraries/oculusMobile/src/ovr/Framebuffer.cpp
  libraries/oculusMobile/src/ovr/VrHandler.cpp
  libraries/oculusMobilePlugin/src/OculusMobileDisplayPlugin.cpp
  libraries/render-utils/src/RenderForwardTask.cpp
  scripts/+android_questInterface/defaultScripts.js
  scripts/developer/utilities/render/deferredLighting.qml
  scripts/system/away.js
  tools/unity-avatar-exporter/Assets/README.txt
Labels: Development Approved, Engine, Project Approved

#14966 Case: 21139 gltf model parts
  libraries/fbx/src/GLTFSerializer.cpp
Labels: Development Approved, Engine, Project Approved

#15074 Case 21504: Very difficult to use the close button on the tablet (0.80.0)
  interface/src/ui/overlays/Overlays.cpp
  scripts/system/libraries/utils.js
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#15075 Fix CI release builds
  android/containerized_build.sh
Labels: Android, Critical Fix, Development Approved, Project Approved

#14941 Artist stocking inventory for 80
  interface/resources/qml/hifi/commerce/checkout/Checkout.qml
  interface/resources/qml/hifi/commerce/marketplace/Marketplace.qml
  interface/resources/qml/hifi/commerce/marketplace/MarketplaceItem.qml
  interface/resources/qml/hifi/commerce/marketplace/MarketplaceListItem.qml
  interface/resources/qml/hifi/commerce/purchases/PurchasedItem.qml
  interface/resources/qml/hifi/commerce/wallet/Wallet.qml
Labels: Metaverse, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#15081 Prevent HUD and Web Surface lasers from interrupting FarGrab.
  scripts/system/controllers/controllerModules/hudOverlayPointer.js
  scripts/system/controllers/controllerModules/webSurfaceLaserInput.js
Labels: Design, Development Approved, HMD required, Project Approved, QA Ready

#15079 Case 21517: Fix resource crash on invalid resource (RC80)
  libraries/networking/src/ResourceCache.cpp
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Ready, bug

#15078 Case 21516: Lasers scale with avatar (RC80)
  interface/src/raypick/LaserPointer.cpp
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Ready, bug

#15030 Case 21456, Case 21463: Clock On Tablet (81.0/master)
  interface/resources/fonts/rawline-500.ttf
  interface/resources/qml/hifi/tablet/TabletHome.qml
  interface/resources/qml/hifi/tablet/TabletRoot.qml
  interface/resources/qml/styles-uit/Rawline.qml
  interface/resources/qml/stylesUit/Rawline.qml
  interface/src/Application.cpp
Labels: Design, Development Approved, Project Approved, QA Ready

#15077 Case 21344: Fix resource crash on invalid resource
  libraries/networking/src/ResourceCache.cpp
Labels: Development Approved, Engine, Project Approved, bug

#15073 Case 21512: Very difficult to use the close button on the tablet (0.81.0)
  interface/src/ui/overlays/Overlays.cpp
  scripts/system/libraries/utils.js
Labels: Development Approved, Engine

#15046 Bug Fix for the Hips not translating correctly when Hips and Root have the same location
  libraries/animation/src/AnimClip.cpp
  libraries/animation/src/AnimInverseKinematics.cpp
  libraries/animation/src/AnimSkeleton.cpp
  libraries/animation/src/AnimSkeleton.h
Labels: Avatar, Development Approved, HMD required, Project Approved, bug

#15076 Case 21514: Lasers scale with avatar
  interface/src/raypick/LaserPointer.cpp
Labels: Development Ready, Engine, Project Approved, QA Approved :tada:, bug

#15036 Connection class should run in NodeList thread
  libraries/networking/src/udt/Connection.cpp
  libraries/networking/src/udt/Socket.cpp
Labels: Metaverse, bug

#15091 RC79-HERO: Detailed picking if avatar is not null
  interface/src/avatar/AvatarManager.cpp
Labels: Avatar, Development Approved, Project Approved, QA Approved :tada:

#15092 Case 21530: fix crash after uploading avatar asset - HERO
  interface/src/avatar/AvatarProject.cpp
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#15086 Case 21533: avoid stalls in PrePhysics for HERO project
  interface/src/Application.cpp
  interface/src/ui/ApplicationOverlay.cpp
  libraries/physics/src/ShapeManager.cpp
  libraries/physics/src/ShapeManager.h
  libraries/shared/src/HashKey.h
  libraries/shared/src/ShapeInfo.cpp
  libraries/shared/src/ShapeInfo.h
  tests/physics/src/ShapeInfoTests.cpp
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#15084 Case 21531: Fix avatar deadlock (RC79.HERO)
  libraries/avatars/src/AvatarHashMap.cpp
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#15067 Avatar priority (hero) zone improvements
  assignment-client/src/avatars/AvatarMixer.cpp
  assignment-client/src/avatars/AvatarMixerClientData.cpp
  assignment-client/src/avatars/AvatarMixerSlave.cpp
  assignment-client/src/avatars/MixerAvatar.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/ZoneEntityItem.cpp
  libraries/entities/src/ZoneEntityItem.h
  scripts/system/assets/data/createAppTooltips.json
  scripts/system/edit.js
  scripts/system/html/js/entityProperties.js
Labels: Development Approved, Metaverse, Project Approved, QA Approved :tada:

#15082 Case 21528: Possible fix for model crash
  libraries/render-utils/src/Model.cpp
Labels: Development Approved, Engine, Project Approved

#15083 Case 21493: Possible fix for model crash (RC80)
  libraries/render-utils/src/Model.cpp
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#15095 case 21563: adding modelScale initialization so that it does not fail the validSc…
  libraries/entities/src/ModelEntityItem.h
Labels: Development Approved, Engine, Project Approved

#15089 Case 21510: Fix mouse on create in HMD (RC80)
  interface/src/Application.cpp
  interface/src/ui/overlays/Overlays.cpp
  interface/src/ui/overlays/Overlays.h
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.h
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/EntityTree.h
  libraries/script-engine/src/ScriptEngine.cpp
Labels: Create, Development Approved, Development Ready, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#15008 Case 21128: AccountServices, HifiAbout, and WalletScriptingInterface JSDoc review
  interface/src/AboutUtil.h
  interface/src/commerce/Wallet.h
  interface/src/scripting/AccountServicesScriptingInterface.cpp
  interface/src/scripting/AccountServicesScriptingInterface.h
  interface/src/scripting/WalletScriptingInterface.h
Labels: JSDocs

#15094 Move newly-created Connection to NodeList thread
  libraries/networking/src/udt/Connection.cpp
  libraries/networking/src/udt/Socket.cpp
Labels: Development Approved, Metaverse, Project Approved, QA Approved :tada:, bug

#15100 Guard against accidentally calling wrong api/v1/places endpoint
  domain-server/src/DomainServer.cpp
  libraries/networking/src/AddressManager.cpp
  scripts/system/interstitialPage.js
Labels: Development Approved, Metaverse, Project Approved, QA Approved :tada:

#15088 Case 21541: Fix mouse on create in HMD
  interface/src/Application.cpp
  interface/src/ui/overlays/Overlays.cpp
  interface/src/ui/overlays/Overlays.h
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.h
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/EntityTree.h
  libraries/script-engine/src/ScriptEngine.cpp
Labels: Create, Development Approved, Engine, Project Approved

#15087 Case 21537, merge v0.79.HERO-rc into v0.80.0 rc
  assignment-client/src/audio/AudioMixerSlavePool.cpp
  assignment-client/src/avatars/AvatarMixer.cpp
  assignment-client/src/avatars/AvatarMixer.h
  assignment-client/src/avatars/AvatarMixerClientData.cpp
  assignment-client/src/avatars/AvatarMixerClientData.h
  assignment-client/src/avatars/AvatarMixerSlave.cpp
  assignment-client/src/avatars/AvatarMixerSlave.h
  assignment-client/src/avatars/AvatarMixerSlavePool.cpp
  assignment-client/src/avatars/MixerAvatar.h
  assignment-client/src/octree/OctreeServer.cpp
  domain-server/resources/describe-settings.json
  domain-server/src/DomainServer.cpp
  domain-server/src/DomainServerSettingsManager.cpp
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityPropertyFlags.h
  libraries/entities/src/ZoneEntityItem.cpp
  libraries/entities/src/ZoneEntityItem.h
  libraries/networking/src/LimitedNodeList.cpp
  libraries/networking/src/LimitedNodeList.h
  libraries/networking/src/NodeList.cpp
  libraries/networking/src/ThreadedAssignment.cpp
  libraries/networking/src/udt/PacketHeaders.h
  scripts/system/assets/data/createAppTooltips.json
  scripts/system/edit.js
  scripts/system/html/js/entityProperties.js
Labels: Development Approved, Metaverse, Packet Version Change, Project Approved, QA Approved :tada:

#15099 case 21525:A dding modelScale initialization so that it does not fail the validSc…
  libraries/entities/src/ModelEntityItem.h
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#15072 Case 11775: Don't clear my avatar entities on domain switch
  interface/src/Application.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.h
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/EntityTree.h
  libraries/entities/src/EntityTreeElement.cpp
  libraries/entities/src/EntityTreeElement.h
  libraries/octree/src/Octree.h
  libraries/octree/src/OctreeProcessor.cpp
  libraries/octree/src/OctreeProcessor.h
Labels: Development Approved, Engine, Project Approved

#15103 ensure error message when marketplace update fails
  interface/resources/qml/hifi/commerce/checkout/Checkout.qml
Labels: Development Approved, Metaverse, QA Approved :tada:, bug

#15031 Read and apply the upVector parameter when importing FBX files
  libraries/fbx/src/FBXSerializer.cpp
Labels: Avatar, Development Approved, Project Approved

#15107 Connection class should run in NodeList thread (RC80)
  libraries/networking/src/udt/Connection.cpp
  libraries/networking/src/udt/Socket.cpp
Labels: Development Approved, Metaverse, Project Approved, QA Approved :tada:, bug

#15069 Case 21482: add SSIM results image
  tools/nitpick/src/AWSInterface.cpp
  tools/nitpick/src/AWSInterface.h
  tools/nitpick/src/ImageComparer.cpp
  tools/nitpick/src/ImageComparer.h
  tools/nitpick/src/MismatchWindow.cpp
  tools/nitpick/src/MismatchWindow.h
  tools/nitpick/src/Nitpick.cpp
  tools/nitpick/src/Nitpick.h
  tools/nitpick/src/Test.cpp
  tools/nitpick/src/Test.h
  tools/nitpick/src/common.h
  tools/nitpick/ui/Nitpick.ui
Labels: Development Approved, Engine, Project Approved, nitpick

#15013 Case 21340: avatar doctor project page status
  interface/resources/qml/hifi/avatarPackager/AvatarProject.qml
  interface/src/avatar/AvatarProject.h
Labels: Create, Development Approved

#15049 Case 21474: relative paths in FST material parsing
  libraries/model-baker/src/model-baker/Baker.cpp
  libraries/model-baker/src/model-baker/Baker.h
  libraries/model-baker/src/model-baker/BakerTypes.h
  libraries/model-baker/src/model-baker/ParseMaterialMappingTask.cpp
  libraries/model-baker/src/model-baker/ParseMaterialMappingTask.h
  libraries/model-baker/src/model-baker/PrepareJointsTask.cpp
  libraries/model-baker/src/model-baker/PrepareJointsTask.h
  libraries/model-networking/src/model-networking/ModelCache.cpp
  libraries/model-networking/src/model-networking/ModelCache.h
Labels: Development Approved, Engine, Project Approved

#14955 Case 18299: Remove workaround for Interactive window crash now that it is fixed
  scripts/system/modules/createWindow.js
Labels: Create, Development Approved, Project Approved, bug

#15104 merge PR 15026 15051 15067 15070 from v0.79.HERO-rc into master
  assignment-client/src/audio/AudioMixerSlavePool.cpp
  assignment-client/src/avatars/AvatarMixer.cpp
  assignment-client/src/avatars/AvatarMixer.h
  assignment-client/src/avatars/AvatarMixerClientData.cpp
  assignment-client/src/avatars/AvatarMixerClientData.h
  assignment-client/src/avatars/AvatarMixerSlave.cpp
  assignment-client/src/avatars/AvatarMixerSlave.h
  assignment-client/src/avatars/AvatarMixerSlavePool.cpp
  assignment-client/src/avatars/MixerAvatar.h
  assignment-client/src/octree/OctreeServer.cpp
  domain-server/resources/describe-settings.json
  domain-server/src/DomainServer.cpp
  interface/src/avatar/OtherAvatar.cpp
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityPropertyFlags.h
  libraries/entities/src/ZoneEntityItem.cpp
  libraries/entities/src/ZoneEntityItem.h
  libraries/networking/src/LimitedNodeList.cpp
  libraries/networking/src/LimitedNodeList.h
  libraries/networking/src/NodeList.cpp
  libraries/networking/src/ThreadedAssignment.cpp
  libraries/networking/src/udt/PacketHeaders.h
  scripts/system/assets/data/createAppTooltips.json
  scripts/system/edit.js
  scripts/system/html/js/entityProperties.js
Labels: Development Approved, Metaverse, Packet Version Change, Project Approved, bug

#15110 (case 21579) (RC80) Fix crash when FST model used as both graphics and physics model
  libraries/model-networking/src/model-networking/ModelCache.cpp
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:, bug

#15108 (case 21585) Fix crash when FST model used as both graphics and physics model
  libraries/model-networking/src/model-networking/ModelCache.cpp
Labels: Development Approved, Engine, Project Approved, bug

#15114 Ik enabled fix
  libraries/animation/src/Rig.cpp
Labels: Avatar, Development Approved, HMD required, Project Approved, bug

#15120 Case 21532: Fix wearable scale on position change (RC80)
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItemProperties.cpp
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#15071 Case 21507: replace Qt network access manager with python
  tools/nitpick/README.md
  tools/nitpick/src/AWSInterface.cpp
  tools/nitpick/src/AdbInterface.cpp
  tools/nitpick/src/AdbInterface.h
  tools/nitpick/src/Downloader.cpp
  tools/nitpick/src/Downloader.h
  tools/nitpick/src/Nitpick.cpp
  tools/nitpick/src/Nitpick.h
  tools/nitpick/src/TestCreator.cpp
  tools/nitpick/src/TestCreator.h
  tools/nitpick/src/TestRailInterface.cpp
  tools/nitpick/src/TestRunner.cpp
  tools/nitpick/src/TestRunner.h
  tools/nitpick/src/TestRunnerDesktop.cpp
  tools/nitpick/src/TestRunnerDesktop.h
  tools/nitpick/src/TestRunnerMobile.cpp
  tools/nitpick/src/TestRunnerMobile.h
  tools/nitpick/ui/Nitpick.ui
Labels: Development Approved, Engine, Project Approved, nitpick

#15117 Case 21596: Fix wearable scale on position change
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItemProperties.cpp
Labels: Development Approved, Engine, Project Approved

#15101 Fixed: Avatar hovers off ground while running
  interface/resources/avatar/animations/run_fwd.fbx
  interface/resources/avatar/avatar-animation.json
Labels: Avatar, Development Approved, Project Approved, bug

#15113 Stock to master
  interface/resources/qml/hifi/commerce/checkout/Checkout.qml
  interface/resources/qml/hifi/commerce/marketplace/Marketplace.qml
  interface/resources/qml/hifi/commerce/marketplace/MarketplaceItem.qml
  interface/resources/qml/hifi/commerce/purchases/PurchasedItem.qml
  interface/resources/qml/hifi/commerce/wallet/Wallet.qml
Labels: Development Approved, Metaverse

#15125 Case 21557, Case 21582: Fix shapes app and debugAvatarMixer (RC80)
  interface/src/avatar/MyAvatar.cpp
  interface/src/ui/overlays/Overlays.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.h
  libraries/entities-renderer/src/RenderableZoneEntityItem.h
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/LightEntityItem.cpp
  libraries/entities/src/LightEntityItem.h
  libraries/shared/src/SpatiallyNestable.cpp
  libraries/shared/src/SpatiallyNestable.h
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#15124 Case 21605: Fix shapes app and debugAvatarMixer
  interface/src/avatar/MyAvatar.cpp
  interface/src/ui/overlays/Overlays.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.h
  libraries/entities-renderer/src/RenderableZoneEntityItem.h
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/LightEntityItem.cpp
  libraries/entities/src/LightEntityItem.h
  libraries/shared/src/SpatiallyNestable.cpp
  libraries/shared/src/SpatiallyNestable.h
  scripts/developer/debugging/debugAvatarMixer.js
Labels: Development Approved, Engine, Project Approved

#15111 Load flow bone data from FST file
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  libraries/hfm/src/hfm/HFM.h
  libraries/model-baker/src/model-baker/Baker.cpp
  libraries/model-baker/src/model-baker/ParseFlowDataTask.cpp
  libraries/model-baker/src/model-baker/ParseFlowDataTask.h
Labels: Avatar, Development Approved, Project Approved

#15123 Case 21581: Tablet X button is nearly impossible to hit with a stylus
  interface/src/raypick/RayPick.cpp
  interface/src/raypick/RayPick.h
  interface/src/raypick/StylusPick.cpp
  libraries/entities/src/ShapeEntityItem.h
  scripts/system/libraries/WebTablet.js
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#14891 Case 21114: SIMD optimized blendshape packing
  libraries/graphics/src/graphics/BufferViewHelpers.cpp
  libraries/graphics/src/graphics/BufferViewHelpers.h
  libraries/model-baker/src/model-baker/BuildGraphicsMeshTask.cpp
  libraries/render-utils/src/Model.cpp
  libraries/shared/src/GLMHelpers.h
Labels: Client, Development Approved, Project Approved

#14938 Case 20662: Entity Properties - fix disabling draggable numbers
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, Project Approved, bug

#15085 Case 21500: Keyboard handle appears huge when scaling down avatar
  interface/src/ui/Keyboard.cpp
Labels: Development Approved, Engine, Project Approved

#15102 Case 21144: Can't enter text in a Web Entity with the new keyboard
  interface/src/Application.cpp
  interface/src/ui/Keyboard.cpp
Labels: Development Approved, Engine, Project Approved

#14940 Case 21273: Avatar Exporter - fix .gitignore to include all unneeded files
  .gitignore
  tools/unity-avatar-exporter/Assets/Editor.meta
  tools/unity-avatar-exporter/Assets/Editor/AvatarExporter.cs.meta
  tools/unity-avatar-exporter/Assets/README.txt.meta
Labels: Create, Development Approved, Project Approved

#15112 Add the version code to the Quest android build
  android/apps/interface/build.gradle
  android/apps/questInterface/build.gradle
Labels: Android, Development Approved, Engine, Project Approved

#14967 Case 21073: Avatar Exporter v0.3 - use root bone name from skeleton list
  tools/unity-avatar-exporter/Assets/Editor/AvatarExporter.cs
  tools/unity-avatar-exporter/Assets/README.txt
  tools/unity-avatar-exporter/avatarExporter.unitypackage
Labels: Avatar, Create, Development Approved, Project Approved

#15105 Case 20830: Disable entity scaling while grabbing
  scripts/system/controllers/controllerModules/nearGrabEntity.js
  scripts/system/controllers/controllerScripts.js
Labels: Development Approved, Engine, Project Approved

#15121 Case 21603: Tablet x button is nearly impossible to hit with stylus
  interface/src/raypick/RayPick.cpp
  interface/src/raypick/RayPick.h
  interface/src/raypick/StylusPick.cpp
  libraries/entities/src/ShapeEntityItem.h
  scripts/system/libraries/WebTablet.js
Labels: Development Approved, Engine, Project Approved

#15127 Case 20734: HMD lasers on 3D overlay do not appear + trigger event does not get called
  scripts/system/controllers/controllerModules/webSurfaceLaserInput.js
Labels: Development Approved, Engine, Project Approved

#15131 Case 15127: Esc key doesn't consistently set my avatar to 'Away' mode
  interface/resources/qml/dialogs/CustomQueryDialog.qml
  interface/resources/qml/dialogs/FileDialog.qml
  interface/resources/qml/dialogs/QueryDialog.qml
Labels: Development Approved, Engine, Project Approved

#15130 Fix mixer crash with Zones that have compound shapes
  assignment-client/src/avatars/AvatarMixer.cpp
Labels: Development Approved, Metaverse, Project Approved, QA Ready

#15132 Case 21621: Fix crash on startup
  libraries/model-baker/src/model-baker/ParseFlowDataTask.cpp
  libraries/model-baker/src/model-baker/ParseFlowDataTask.h
Labels: Development Approved, Engine, Project Approved

#15119 Improve AnimPose support for negative scale
  libraries/animation/src/AnimPose.cpp
  libraries/animation/src/AnimTwoBoneIK.cpp
  tests/animation/CMakeLists.txt
  tests/animation/src/AnimTests.cpp
Labels: Avatar, Development Approved, Project Approved

#15115 Case 21226: Avatar Exporter v0.3.1 - export Unity material data to fst
  tools/unity-avatar-exporter/Assets/Editor/AvatarExporter.cs
  tools/unity-avatar-exporter/Assets/README.txt
  tools/unity-avatar-exporter/avatarExporter.unitypackage
Labels: Avatar, Create, Development Approved, Project Approved

#15128 Case 21315, Case 21326, Case 21370
  interface/resources/qml/hifi/commerce/marketplace/Marketplace.qml
  interface/resources/qml/hifi/commerce/marketplace/MarketplaceItem.qml
  interface/resources/qml/hifi/commerce/marketplace/MarketplaceListItem.qml
Labels: Development Approved, Metaverse, Project Approved

#15106 Case 21559: increased threshold to 0.9999
  tools/nitpick/src/AWSInterface.cpp
  tools/nitpick/src/Downloader.cpp
  tools/nitpick/src/Nitpick.cpp
  tools/nitpick/src/TestCreator.cpp
  tools/nitpick/src/TestCreator.h
  tools/nitpick/src/TestRailInterface.cpp
Labels: Development Approved, Engine, Project Approved, nitpick

#15138 Fix mixer crash with Zones that have compound shapes (RC80)
  assignment-client/src/avatars/AvatarMixer.cpp
Labels: Development Approved, Metaverse, Project Approved, QA Approved :tada:

#15126 unlimited certified copies in a domain
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityItemPropertiesDefaults.h
  libraries/entities/src/EntityPropertyFlags.h
  libraries/entities/src/EntityTree.cpp
  libraries/networking/src/udt/PacketHeaders.h
  scripts/system/libraries/cloneEntityUtils.js
Labels: Development Ready, Metaverse, Project Approved

#15133 Case 21613: Fix text rendering on AMD/Mac (RC79.HERO)
  interface/src/Application.cpp
  libraries/entities-renderer/src/RenderableTextEntityItem.cpp
  libraries/render-utils/src/GeometryCache.cpp
  libraries/render-utils/src/TextRenderer3D.cpp
  libraries/render-utils/src/TextRenderer3D.h
  libraries/render-utils/src/sdf_text3D.slv
  libraries/render-utils/src/sdf_text3D_transparent.slf
  libraries/render-utils/src/text/Font.cpp
  libraries/render-utils/src/text/Font.h
  libraries/shared/src/DisableDeferred.h
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#15136 Fix mixer crash with Zones that have compound shapes (master)
  assignment-client/src/avatars/AvatarMixer.cpp
Labels: Development Approved, Metaverse, Project Approved

#15134 Case 21627: Fix text rendering on AMD/Mac (RC80)
  interface/src/Application.cpp
  libraries/entities-renderer/src/RenderableTextEntityItem.cpp
  libraries/render-utils/src/GeometryCache.cpp
  libraries/render-utils/src/TextRenderer3D.cpp
  libraries/render-utils/src/TextRenderer3D.h
  libraries/render-utils/src/sdf_text3D.slv
  libraries/render-utils/src/sdf_text3D_transparent.slf
  libraries/render-utils/src/text/Font.cpp
  libraries/render-utils/src/text/Font.h
  libraries/shared/src/DisableDeferred.h
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#15142 Case 21010 - Tag domains and marketplace items as stand-alone device optimized
  interface/resources/icons/standalone-optimized.svg
  interface/resources/qml/hifi/Card.qml
  interface/resources/qml/hifi/Feed.qml
  interface/resources/qml/hifi/commerce/inspectionCertificate/InspectionCertificate.qml
  interface/resources/qml/hifi/commerce/marketplace/Marketplace.qml
  interface/resources/qml/hifi/commerce/marketplace/MarketplaceItem.qml
  interface/resources/qml/hifi/commerce/marketplace/MarketplaceListItem.qml
  interface/resources/qml/hifi/commerce/purchases/PurchasedItem.qml
  interface/resources/qml/hifi/commerce/purchases/Purchases.qml
  interface/resources/qml/hifi/tablet/TADLightbox.qml
  interface/resources/qml/hifi/tablet/TabletAddressDialog.qml
  interface/src/Application.cpp
  interface/src/scripting/PlatformInfoScriptingInterface.cpp
  interface/src/scripting/PlatformInfoScriptingInterface.h
  libraries/shared/src/shared/GlobalAppProperties.cpp
  libraries/shared/src/shared/GlobalAppProperties.h
Labels: Development Approved, Metaverse, Project Approved

#15118 Case 21060: Avatar Exporter v0.3.2 - New jointRotationOffset field
  tools/unity-avatar-exporter/Assets/Editor/AvatarExporter.cs
  tools/unity-avatar-exporter/Assets/README.txt
  tools/unity-avatar-exporter/avatarExporter.unitypackage
Labels: Avatar, Create, Development Approved, Project Approved

#15143 loading jointRotationOffset2 from FST and deal with the shadow joints
  libraries/model-baker/src/model-baker/PrepareJointsTask.cpp
Labels: Avatar, Development Approved, Project Approved, bug

#15035 Case 21449: [AvatarPackager/AvatarDoctor] Warnings update
  interface/src/avatar/AvatarDoctor.cpp
  interface/src/avatar/AvatarDoctor.h
  libraries/animation/src/Rig.cpp
  libraries/animation/src/Rig.h
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
Labels: Create, Development Approved, Project Approved

#15139 Case 21220: Add more complete support for .tga files
  libraries/image/src/image/Image.cpp
  libraries/image/src/image/TGAReader.cpp
  libraries/image/src/image/TGAReader.h
Labels: Create, Development Approved, Project Approved

#15090 Case 21167: When using Oculus HMD, continue to track hand position and movement when focus is off High Fidelity
  interface/resources/qml/hifi/tablet/OculusConfiguration.qml
  interface/src/ui/PreferencesDialog.cpp
  plugins/oculus/src/OculusControllerManager.cpp
  plugins/oculus/src/OculusControllerManager.h
Labels: Development Ready, Engine, Project Approved

#15135 Case 21628: Fix text rendering on AMD/Mac
  interface/src/Application.cpp
  libraries/entities-renderer/src/RenderablePolyLineEntityItem.cpp
  libraries/entities-renderer/src/RenderableShapeEntityItem.cpp
  libraries/entities-renderer/src/RenderableTextEntityItem.cpp
  libraries/render-utils/src/GeometryCache.cpp
  libraries/render-utils/src/TextRenderer3D.cpp
  libraries/render-utils/src/TextRenderer3D.h
  libraries/render-utils/src/sdf_text3D.slv
  libraries/render-utils/src/sdf_text3D_transparent.slf
  libraries/render-utils/src/text/Font.cpp
  libraries/render-utils/src/text/Font.h
  libraries/shared/src/DisableDeferred.h
Labels: Development Approved, Engine, Project Approved

#15137 Case 21069: Avatar Exporter v0.3.3 - temporary de-optimize game objects during the export process
  tools/unity-avatar-exporter/Assets/Editor/AvatarExporter.cs
  tools/unity-avatar-exporter/Assets/README.txt
  tools/unity-avatar-exporter/avatarExporter.unitypackage
Labels: Avatar, Create, Development Approved, Project Approved

#15144 Change "about" blockchain from Elements to EOS
  interface/resources/qml/hifi/dialogs/TabletAboutDialog.qml
Labels: Metaverse, Project Approved

#15146 do not scroll inventory items underneath modal dialog
  interface/resources/qml/hifi/commerce/purchases/Purchases.qml
Labels: Development Approved, Metaverse, Project Approved

#15145 Case 21642 - verification dialog when user hits return in goto search
  interface/resources/qml/hifi/Feed.qml
  interface/resources/qml/hifi/tablet/TabletAddressDialog.qml
Labels: Development Approved, Metaverse, Project Approved

#15129 Case 21638: RC79 HERO: Adding Hero support in simulation of avatars
  assignment-client/src/avatars/AvatarMixerClientData.cpp
  assignment-client/src/avatars/MixerAvatar.h
  interface/resources/qml/+android/Stats.qml
  interface/resources/qml/Stats.qml
  interface/src/avatar/AvatarManager.cpp
  interface/src/avatar/AvatarManager.h
  interface/src/avatar/OtherAvatar.cpp
  interface/src/avatar/OtherAvatar.h
  interface/src/ui/Stats.cpp
  interface/src/ui/Stats.h
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
Labels: Development Approved, Engine, Metaverse, Project Approved

#15141 add getFlowData method to MyAvatar
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  libraries/animation/src/Flow.cpp
  libraries/animation/src/Flow.h
Labels: Avatar, Development Approved, Project Approved, Scripting API change

#15116 Case 21595: Oculus SDK Update
  android/apps/questFramePlayer/src/main/cpp/RenderThread.cpp
  cmake/macros/TargetOculusMobile.cmake
  hifi_android.py
  libraries/oculusMobile/src/ovr/GLContext.cpp
  libraries/oculusMobile/src/ovr/GLContext.h
  libraries/oculusMobile/src/ovr/VrHandler.cpp
  libraries/oculusMobile/src/ovr/VrHandler.h
Labels: Android, Development Ready, Project Approved

#15150 don't allow others' grabs to move locked or ungrabbable things
  interface/src/avatar/GrabManager.cpp
Labels: Development Ready, Project Approved, QA Approved :tada:

#15147 Case 21640: RC80: Adding Hero support in simulation of avatars
  assignment-client/src/avatars/AvatarMixerClientData.cpp
  assignment-client/src/avatars/MixerAvatar.h
  interface/resources/qml/+android_interface/Stats.qml
  interface/resources/qml/Stats.qml
  interface/src/avatar/AvatarManager.cpp
  interface/src/avatar/AvatarManager.h
  interface/src/avatar/OtherAvatar.cpp
  interface/src/ui/Stats.cpp
  interface/src/ui/Stats.h
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
Labels: Development Approved, Engine, Metaverse, Project Approved, QA Approved :tada:

#15152 Case 21326 - missing marketplaceInject.js
  scripts/system/html/js/marketplacesInject.js
Labels: Development Ready, Metaverse

#15148 Case 21639: RC81: Adding Hero support in simulation of avatars
  assignment-client/src/avatars/AvatarMixerClientData.cpp
  assignment-client/src/avatars/MixerAvatar.h
  interface/resources/qml/+android_interface/Stats.qml
  interface/resources/qml/Stats.qml
  interface/src/avatar/AvatarManager.cpp
  interface/src/avatar/AvatarManager.h
  interface/src/avatar/OtherAvatar.cpp
  interface/src/ui/Stats.cpp
  interface/src/ui/Stats.h
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
Labels: Development Approved, Engine, Metaverse, Project Approved

#15155 Fix cloneables
  scripts/system/libraries/cloneEntityUtils.js
  scripts/system/libraries/controllerDispatcherUtils.js
  scripts/system/miniTablet.js
Labels: Client, Development Approved, Engine, Project Approved, QA Ready

#14932 Case 21227: don't enforce MOTION_TYPE_STATIC on mesh shapes
  libraries/entities/src/EntityItem.cpp
  libraries/physics/src/EntityMotionState.cpp
Labels: Development Approved, Engine, Project Approved

#15098 Case 21564: Warn When Muted
  interface/resources/qml/hifi/audio/Audio.qml
  interface/src/scripting/Audio.cpp
  interface/src/scripting/Audio.h
  libraries/audio-client/src/AudioClient.cpp
  libraries/audio-client/src/AudioClient.h
  scripts/defaultScripts.js
  scripts/system/audioMuteOverlay.js
Labels: Design, Development Ready, HMD required, Project Approved

#15109 Case 21658: Push-To-Talk
  interface/resources/controllers/keyboardMouse.json
  interface/resources/icons/tablet-icons/mic-ptt-a.svg
  interface/resources/icons/tablet-icons/mic-ptt-i.svg
  interface/resources/qml/hifi/audio/Audio.qml
  interface/resources/qml/hifi/audio/MicBar.qml
  interface/src/Application.cpp
  interface/src/scripting/Audio.cpp
  interface/src/scripting/Audio.h
  libraries/controllers/src/controllers/Actions.cpp
  libraries/controllers/src/controllers/Actions.h
  scripts/system/audio.js
  scripts/system/controllers/controllerDispatcher.js
  scripts/system/controllers/controllerModules/pushToTalk.js
  scripts/system/controllers/controllerScripts.js
Labels: Design, Development Approved, HMD required, Project Approved

#15153 Case 21618: menithal's avatar is constantly flashing
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
Labels: Development Approved, Engine, Project Approved

#15159 Case 21669: Fix joint renaming with jointRotationOffset2
  libraries/model-baker/src/model-baker/PrepareJointsTask.cpp
Labels: Avatar, Development Approved, Project Approved, bug

#15158 Case 7295: Fix rendering of unrigged vertices
  .vs/slnx.sqlite
  libraries/fbx/src/FBXSerializer.cpp
  libraries/render-utils/src/CauterizedModel.cpp
  libraries/render-utils/src/Model.cpp
Labels: Development Ready, Engine, Project Approved

#15029 Resolve Linux Build Guide's Cmake issue
  BUILD_LINUX.md
Labels: Development Approved, Project Approved

#15151 Case 20622 - Qml Marketplace - Fix categories dropdown UI issues
  interface/resources/qml/hifi/commerce/marketplace/Marketplace.qml
Labels: Development Approved, Metaverse, Project Approved

#15167 Fix android build for 0.80.0 branch
  android/build_android.sh
Labels: Development Approved, Project Approved, QA Approved :tada:

#15170 Case 21687: Unable to create new profile during steam login
  interface/resources/qml/LoginDialog/CompleteProfileBody.qml
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:, bug

#15171 Case 21693: Unable to create new profile during steam login
  interface/resources/qml/LoginDialog/CompleteProfileBody.qml
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:, bug

#15172 Case 21695: Unable to create new profile during steam login
  interface/resources/qml/LoginDialog/CompleteProfileBody.qml
Labels: Development Approved, Engine, Project Approved, bug

#15177 Case 21708: Remove .vs folder from version control
  .gitignore
  .vs/slnx.sqlite
Labels: Development Approved, Project Approved

#15179 Case 21703, Case 21704, Case 21701 - random marketplace UI fixes
  interface/resources/qml/controlsUit/Button.qml
  interface/resources/qml/hifi/commerce/common/sendAsset/SendAsset.qml
  interface/resources/qml/hifi/commerce/marketplace/Marketplace.qml
  interface/resources/qml/hifi/commerce/marketplace/MarketplaceItem.qml
Labels: Development Ready, Metaverse, bug

#15192 Fixed Memory Corruption in AnimClip.cpp
  libraries/animation/src/AnimClip.cpp
Labels: Avatar, Development Approved, Project Approved, bug

#15183 Case 21653: Fix User is not able to update input fields and scroll past selected object in Create Tools [RC81]
  scripts/system/html/js/entityList.js
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, Project Approved, QA Approved :tada:

#15185 Case 21653: Fix User is not able to update input fields and scroll past selected object in Create Tools [master]
  scripts/system/html/js/entityList.js
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, Project Approved

#15181 Case 21703, Case 21704, Case 21701 into 81 - random marketplace UI fixes
  interface/resources/qml/controlsUit/Button.qml
  interface/resources/qml/hifi/commerce/common/sendAsset/SendAsset.qml
  interface/resources/qml/hifi/commerce/marketplace/Marketplace.qml
  interface/resources/qml/hifi/commerce/marketplace/MarketplaceItem.qml
Labels: Development Approved, Metaverse, Project Approved, QA Approved :tada:, bug

#15184 Case 21716: adding scrolling in audio settings window
  interface/resources/qml/hifi/audio/Audio.qml
  interface/resources/qml/hifi/audio/AudioTabButton.qml
Labels: Design, Development Approved, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:, bug

#15164 Case 21674: Microphone is still live after reopening Interface
  interface/src/scripting/Audio.cpp
Labels: Design, Development Approved, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:, bug

#15174 Case 20427: Avatar Exporter v0.3.5 - add scaling, fix colon prefixed joint names and material issues, add exporter version field
  tools/unity-avatar-exporter/Assets/Editor/AvatarExporter/AvatarExporter.cs
  tools/unity-avatar-exporter/Assets/Editor/AvatarExporter/Average.mat
  tools/unity-avatar-exporter/Assets/Editor/AvatarExporter/Floor.mat
  tools/unity-avatar-exporter/Assets/Editor/AvatarExporter/HeightReference.prefab
  tools/unity-avatar-exporter/Assets/Editor/AvatarExporter/Line.mat
  tools/unity-avatar-exporter/Assets/Editor/AvatarExporter/ShortOrTall.mat
  tools/unity-avatar-exporter/Assets/Editor/AvatarExporter/TooShortOrTall.mat
  tools/unity-avatar-exporter/Assets/README.txt
  tools/unity-avatar-exporter/avatarExporter.unitypackage
Labels: Avatar, Create, Development Approved, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#15195 Case 21353: Avatar Doctor documentation / Video URLs [RC81]
  interface/resources/qml/hifi/avatarPackager/AvatarPackagerApp.qml
  interface/resources/qml/hifi/avatarPackager/AvatarPackagerHeader.qml
  interface/src/avatar/AvatarDoctor.cpp
  interface/src/avatar/AvatarDoctor.h
Labels: Create, Development Approved, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#15193 RC81: Fixed Memory Corruption in AnimClip.cpp
  libraries/animation/src/AnimClip.cpp
Labels: Avatar, Development Approved, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:, bug

#15188 Case 21676: Fix wearable duplication on domain switch (RC81)
  interface/src/Application.cpp
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  libraries/entities/src/EntityScriptingInterface.cpp
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#15187 Case 21721: Fix wearable duplication on domain switch
  interface/src/Application.cpp
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  libraries/entities/src/EntityScriptingInterface.cpp
Labels: Development Approved, Engine, Project Approved

#15210 Case 21757: show up audio screen using Settings > Audio
  interface/resources/qml/hifi/dialogs/Audio.qml
  interface/src/Menu.cpp
Labels: Design, Development Approved, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:, bug

#15208 Case 21727: Possible Entity Script Ban incident (RC 80)
  interface/resources/qml/dialogs/TabletMessageBox.qml
  interface/resources/qml/hifi/tablet/TabletRoot.qml
  interface/src/Application.cpp
  interface/src/Application.h
  libraries/script-engine/src/UsersScriptingInterface.cpp
  libraries/script-engine/src/UsersScriptingInterface.h
  libraries/ui/src/OffscreenUi.cpp
  libraries/ui/src/OffscreenUi.h
  libraries/ui/src/ui/TabletScriptingInterface.cpp
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#15209 Case 21770: Possible Entity Script Ban incident (RC 81)
  interface/resources/qml/dialogs/TabletMessageBox.qml
  interface/resources/qml/hifi/tablet/TabletRoot.qml
  interface/src/Application.cpp
  interface/src/Application.h
  libraries/script-engine/src/UsersScriptingInterface.cpp
  libraries/script-engine/src/UsersScriptingInterface.h
  libraries/ui/src/OffscreenUi.cpp
  libraries/ui/src/OffscreenUi.h
  libraries/ui/src/ui/TabletScriptingInterface.cpp
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, QA Approved :tada:

#15215 Stand-alone Tagging: tagged places not coming first in GOTO list
  interface/resources/qml/hifi/Feed.qml
Labels: Development Ready, Metaverse, bug

#15216 allow baseURL to be specified in fst
  libraries/model-networking/src/model-networking/ModelCache.cpp
Labels: Metaverse

#15220 Case21795 - Stand-alone Tagging: tagged places not coming first in GOTO list (v81)
  interface/resources/qml/hifi/Feed.qml
Labels: Development Approved, Metaverse, Project Approved, QA Approved :tada:, bug

#15224 Case 21792: don't ignore updates that originate from entityPropertiesTool itself [RC81]
  scripts/system/edit.js
  scripts/system/html/js/entityProperties.js
  scripts/system/libraries/entitySelectionTool.js
Labels: Create, Development Approved, QA Approved :tada:

#15221 Case 21769 - updatable items not showing up as updatable after clicking 'show updates' button.
  interface/resources/qml/hifi/commerce/purchases/PurchasedItem.qml
  interface/resources/qml/hifi/commerce/purchases/Purchases.qml
Labels: Development Approved, Metaverse, Project Approved, QA Approved :tada:, bug

#15223 Case 21807 - updatable items not showing up as updatable after clicking 'show updates' button. (master)
  interface/resources/qml/hifi/commerce/purchases/PurchasedItem.qml
  interface/resources/qml/hifi/commerce/purchases/Purchases.qml
Labels: Development Approved, Metaverse, Project Approved, bug

#15190 Case20393 - Add item counts to interface categories
  interface/resources/qml/hifi/commerce/marketplace/Marketplace.qml
  interface/src/avatar/MarketplaceItemUploader.cpp
Labels: Development Approved, Metaverse, QA Approved :tada:

#15226 Case 21392 - Excise unneeded code from marketplacesInject.js
  scripts/system/html/js/marketplacesInject.js
Labels: Development Approved, Metaverse, Project Approved, QA Approved :tada:

#15227 Case 21816: don't ignore updates that originate from entityPropertiesTool itself [master]
  scripts/system/edit.js
  scripts/system/html/js/entityProperties.js
  scripts/system/libraries/entitySelectionTool.js
Labels: Create, Development Approved, Project Approved

#15222 Allow base url to be specified in fst for 81
  libraries/model-networking/src/model-networking/ModelCache.cpp
Labels: Development Approved, Metaverse, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:
