Repository highfidelity/hifi, pull requests merged in 2019-02, with the labels that each got.

#14826 [RC79] Fix assertion when trying to create multisphere shapeInfo with empty data.
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/shared/src/ShapeInfo.cpp
Labels: Avatar, Development Approved, Project Approved, QA Approved :tada:

#14842 Case 20908: Fix SendAsset.qml has wrong color
  interface/resources/qml/hifi/commerce/common/sendAsset/SendAsset.qml
  interface/resources/qml/hifi/tablet/TabletRoot.qml
Labels: Client, Development Approved, Engine, Project Approved, QA Approved :tada:

#14824 [79.0] Fix reload mechanic for entity server scripts
  assignment-client/src/scripts/EntityScriptServer.cpp
  assignment-client/src/scripts/EntityScriptServer.h
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
Labels: Development Ready, Infrastructure, Project Approved, QA Approved :tada:

#14841 Case 20972: Fix SendAsset.qml has wrong color
  interface/resources/qml/hifi/commerce/common/sendAsset/SendAsset.qml
  interface/resources/qml/hifi/tablet/TabletRoot.qml
Labels: Client, Development Approved, Engine, QA Approved :tada:

#14846 case 20954: fix crash for incorrect parsing of ModelEntityItem jointTranslation data
  libraries/octree/src/OctreePacketData.cpp
Labels: Critical Fix, Development Approved, Drunk PR, Engine, Project Approved, QA Approved :tada:

#14822 Make Animation Unit Tests Pass Again
  libraries/animation/src/AnimBlendLinearMove.cpp
  libraries/animation/src/AnimVariant.h
  libraries/animation/src/Rig.cpp
  tests/animation/CMakeLists.txt
  tests/animation/src/AnimInverseKinematicsTests.cpp
  tests/animation/src/AnimTests.cpp
Labels: Avatar, Development Approved, Project Approved, QA Approved :tada:

#14818 MS20925: Oculus login button not appearing
  interface/src/Application.cpp
Labels: Client, Critical Fix, Development Approved, Project Approved, QA Ready, bug

#14848 Case 20958: fix crash for incorrect parsing of AvatarEntity data, for 0.79.0
  libraries/octree/src/OctreePacketData.cpp
Labels: Critical Fix, Development Approved, Engine, Project Approved, QA Approved :tada:

#14849 Case 21011: Fix getEntityProperties (79)
  libraries/entities/src/EntityItem.cpp
Labels: Critical Fix, Development Approved, Engine, Project Approved, QA Approved :tada:, bug

#14844 case 21032: Feature/quest life cycle
  android/libraries/qt/src/main/java/org/qtproject/qt5/android/bindings/QtActivity.java
Labels: Android, DO NOT MERGE

#14814 case 20919: Fix edit in release grab
  interface/src/avatar/MyAvatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/entities/src/EntityDynamicInterface.h
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/physics/src/EntityMotionState.cpp
  libraries/shared/src/Grab.h
  libraries/shared/src/SpatiallyNestable.cpp
  libraries/shared/src/SpatiallyNestable.h
Labels: Development Approved, QA Approved :tada:, bug

#14788 Case 20876: Quest: Support gpu timing on systems with disjoint timer extension
  libraries/gpu-gl-common/src/gpu/gl/GLBackendQuery.cpp
Labels: Android, Development Approved, Engine, QA Approved :tada:

#14854 Case 21037: Allow the script engine to use FileSeclector when loading scriopts
  libraries/script-engine/src/ScriptEngines.cpp
  libraries/shared/src/shared/FileUtils.cpp
  scripts/+android_questInterface/defaultScripts.js
Labels: Client, Development Approved, Development Ready, Engine, QA Approved :tada:

#14859 Make sure that the quest controllers are connected after initialization
  libraries/oculusMobilePlugin/src/OculusMobileControllerManager.cpp
Labels: Engine

#14855 case 21040: fix Interface crash on early shutdown
  libraries/shared/src/LogHandler.cpp
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14847 Case 20959: fix crash for incorrect parsing of AvatarEntity data
  libraries/octree/src/OctreePacketData.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#14775 Qml marketplace
  interface/resources/qml/hifi/commerce/checkout/Checkout.qml
  interface/resources/qml/hifi/commerce/common/EmulatedMarketplaceHeader.qml
  interface/resources/qml/hifi/commerce/inspectionCertificate/InspectionCertificate.qml
  interface/resources/qml/hifi/commerce/marketplace/Marketplace.qml
  interface/resources/qml/hifi/commerce/marketplace/MarketplaceItem.qml
  interface/resources/qml/hifi/commerce/marketplace/MarketplaceListItem.qml
  interface/resources/qml/hifi/commerce/marketplace/SortButton.qml
  interface/resources/qml/hifi/commerce/purchases/PurchasedItem.qml
  interface/resources/qml/hifi/commerce/purchases/Purchases.qml
  interface/resources/qml/hifi/commerce/wallet/WalletHome.qml
  interface/src/Application.cpp
  interface/src/commerce/QmlCommerce.cpp
  interface/src/commerce/QmlMarketplace.cpp
  interface/src/commerce/QmlMarketplace.h
  interface/src/scripting/PlatformInfoScriptingInterface.cpp
  interface/src/scripting/PlatformInfoScriptingInterface.h
  libraries/networking/src/AccountManager.cpp
  libraries/networking/src/AccountManager.h
  scripts/system/commerce/wallet.js
  scripts/system/html/js/marketplacesInject.js
  scripts/system/marketplaces/marketplace.js
  scripts/system/marketplaces/marketplaces.js
Labels: Commerce, DO NOT MERGE, Development Approved, Infrastructure, Metaverse, QA Approved :tada:

#14851 case 20048: don't allow MyAvatar to move until physics enabled
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  libraries/shared/src/CrashHelpers.cpp
  libraries/shared/src/CrashHelpers.h
Labels: Development Approved, Engine, QA Approved :tada:

#14856 case 21042: fix interface crash on early shutdown, 0.80.0 redux
  libraries/shared/src/LogHandler.cpp
Labels: Development Approved, Engine, QA Approved :tada:

#14821 Case 20932: Fix getEntityProperties
  libraries/entities/src/EntityItem.cpp
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:, bug

#14795 case 17773: reduce likelihood MyAvatar will get stuck in mesh geometry when flying around
  interface/src/Application.cpp
  libraries/physics/src/CharacterController.cpp
  libraries/physics/src/PhysicsEngine.cpp
  libraries/physics/src/PhysicsEngine.h
Labels: Development Approved, Engine, QA Approved :tada:

#14867 Quest addressing the low resolution
  libraries/oculusMobilePlugin/src/OculusMobileDisplayPlugin.cpp
Labels: Development Ready, Engine

#14870 Case 21048: Fix black albedo coloring
  libraries/graphics/src/graphics/Material.cpp
Labels: Critical Fix, Development Approved, Engine, Project Approved, QA Approved :tada:, bug

#14825 Case 20829: Always fall when flying is not allowed
  interface/src/avatar/MyAvatar.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/physics/src/CharacterController.cpp
Labels: Avatar, Development Approved, Engine, Project Approved, QA Approved :tada:

#14783 Case 20816: install on android (Mac and Windows installers)
  CMakeLists.txt
  cmake/macros/FixupNitpick.cmake
  cmake/macros/SetPackagingParameters.cmake
  tools/nitpick/CMakeLists.txt
  tools/nitpick/README.md
  tools/nitpick/compiledResources/resources.rcc
  tools/nitpick/icon/nitpick.icns
  tools/nitpick/icon/nitpick.ico
  tools/nitpick/src/AWSInterface.h
  tools/nitpick/src/BusyWindow.cpp
  tools/nitpick/src/BusyWindow.h
  tools/nitpick/src/MismatchWindow.cpp
  tools/nitpick/src/MismatchWindow.h
  tools/nitpick/src/Nitpick.cpp
  tools/nitpick/src/Nitpick.h
  tools/nitpick/src/PythonInterface.cpp
  tools/nitpick/src/Test.cpp
  tools/nitpick/src/Test.h
  tools/nitpick/src/TestRailInterface.h
  tools/nitpick/src/TestRailResultsSelectorWindow.cpp
  tools/nitpick/src/TestRailResultsSelectorWindow.h
  tools/nitpick/src/TestRailRunSelectorWindow.cpp
  tools/nitpick/src/TestRailRunSelectorWindow.h
  tools/nitpick/src/TestRailTestCasesSelectorWindow.cpp
  tools/nitpick/src/TestRailTestCasesSelectorWindow.h
  tools/nitpick/src/TestRunner.cpp
  tools/nitpick/src/TestRunner.h
  tools/nitpick/src/TestRunnerDesktop.cpp
  tools/nitpick/src/TestRunnerDesktop.h
  tools/nitpick/src/TestRunnerMobile.cpp
  tools/nitpick/src/TestRunnerMobile.h
  tools/nitpick/src/main.cpp
  tools/nitpick/ui/BusyWindow.ui
  tools/nitpick/ui/MismatchWindow.ui
  tools/nitpick/ui/Nitpick.ui
  tools/nitpick/ui/TestRailResultsSelectorWindow.ui
  tools/nitpick/ui/TestRailRunSelectorWindow.ui
  tools/nitpick/ui/TestRailTestCasesSelectorWindow.ui
Labels: Development Ready, Engine, Mac Required, Project Approved, QA Approved :tada:, Windows Required, nitpick

#14882 DNM Case 21084 - removed unneeded copying of SSL DLL's.
  tools/nitpick/CMakeLists.txt
Labels: Development Approved, Engine, Project Approved, QA Ready, bug, nitpick

#14874 (case 21076) Fix missing normal textures on models (RC80)
  libraries/model-baker/src/model-baker/CalculateMeshTangentsTask.cpp
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14865 Animation System Optimizations
  interface/src/avatar/AvatarActionHold.cpp
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MySkeletonModel.cpp
  libraries/animation/src/AnimClip.cpp
  libraries/animation/src/AnimInverseKinematics.cpp
  libraries/animation/src/AnimManipulator.cpp
  libraries/animation/src/AnimPoleVectorConstraint.cpp
  libraries/animation/src/AnimPose.cpp
  libraries/animation/src/AnimPose.h
  libraries/animation/src/AnimSkeleton.cpp
  libraries/animation/src/AnimSkeleton.h
  libraries/animation/src/Rig.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/render-utils/src/AnimDebugDraw.cpp
  libraries/render-utils/src/CauterizedModel.cpp
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
  libraries/shared/src/CubicHermiteSpline.h
  tests/animation/src/AnimTests.cpp
  tests/animation/src/AnimTests.h
Labels: Avatar, Development Approved, Project Approved

#14737 Case 19291: Fix zone bugs
  libraries/entities-renderer/src/RenderableZoneEntityItem.cpp
  libraries/entities/src/ZoneEntityItem.cpp
  libraries/entities/src/ZoneEntityItem.h
  libraries/graphics/src/graphics/Haze.cpp
  libraries/graphics/src/graphics/Haze.h
  libraries/render-utils/src/Haze.slh
Labels: Development Approved, Engine, Project Approved, bug

#14739 Case 20398: Fix animation URL change
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.h
Labels: Development Approved, Engine, Project Approved, bug

#14816 Case 20924: Cleaning up Avatar findRayIntersection
  interface/src/avatar/AvatarManager.cpp
  interface/src/raypick/RayPick.cpp
Labels: Avatar, Development Approved, Engine, Project Approved

#14862 Case 21047: Render backfaces of triangles on Procedural Entities
  libraries/procedural/src/procedural/Procedural.cpp
Labels: Development Approved, Engine, Project Approved, bug

#14868 Case 21070: Fix black albedo coloring
  libraries/graphics/src/graphics/Material.cpp
Labels: Development Approved, Engine, Project Approved, bug

#14837 Assign lowest available suffix when display-names collide
  assignment-client/src/avatars/AvatarMixer.cpp
  assignment-client/src/avatars/AvatarMixer.h
Labels: Development Approved, Infrastructure, Project Approved

#14860 Case 19385: local compare in entity list sorting
  scripts/system/html/js/entityList.js
Labels: Create, Development Approved, Project Approved

#14802 Case 20887: Move FST joint property handling to the model preparation step
  interface/resources/meshes/defaultAvatar_full.fst
  interface/src/ModelPackager.cpp
  interface/src/ModelPropertiesDialog.cpp
  interface/src/ModelPropertiesDialog.h
  libraries/animation/src/AnimSkeleton.cpp
  libraries/avatars-renderer/src/avatars-renderer/SkeletonModel.cpp
  libraries/avatars-renderer/src/avatars-renderer/SkeletonModel.h
  libraries/fbx/src/FBXSerializer.cpp
  libraries/fbx/src/FST.cpp
  libraries/fbx/src/FSTReader.cpp
  libraries/fbx/src/FSTReader.h
  libraries/fbx/src/GLTFSerializer.cpp
  libraries/fbx/src/OBJSerializer.cpp
  libraries/hfm/src/hfm/HFM.h
  libraries/model-baker/src/model-baker/Baker.cpp
  libraries/model-baker/src/model-baker/Baker.h
  libraries/model-baker/src/model-baker/PrepareJointsTask.cpp
  libraries/model-baker/src/model-baker/PrepareJointsTask.h
  libraries/model-networking/src/model-networking/ModelCache.cpp
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
Labels: Development Approved, Engine, Project Approved

#14876 Case 20653: QmlMarketplace - disable links if 3dhtml surfaces are not available
  interface/resources/qml/hifi/commerce/marketplace/Marketplace.qml
  interface/resources/qml/hifi/commerce/marketplace/MarketplaceItem.qml
  interface/src/commerce/QmlMarketplace.cpp
  interface/src/commerce/QmlMarketplace.h
  libraries/networking/src/AccountManager.cpp
  libraries/networking/src/AccountManager.h
Labels: Commerce, Development Approved, Infrastructure, Project Approved

#14827 Case 14722: Fix assertion when trying to create multisphere shapeInfo with empty data (80.0/master)
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/shared/src/ShapeInfo.cpp
Labels: Avatar, Development Approved, Project Approved

#14843 Case 20937: gltf embedded data
  libraries/fbx/src/GLTFSerializer.cpp
  libraries/fbx/src/GLTFSerializer.h
Labels: Development Approved, Engine, Project Approved

#14786 Case 20866: gltf color attribute
  libraries/fbx/src/GLTFSerializer.cpp
Labels: Development Approved, Engine, Project Approved

#14885 Case 21095: Do not include nitpick in Ubuntu production builds.
  tools/CMakeLists.txt
Labels: Development Approved, Engine, Project Approved, bug

#14884 Pack all non-instanced avatar traits
  libraries/avatars/src/ClientTraitsHandler.cpp
Labels: Avatar, Development Approved, Project Approved, Server & Network

#14880 Case 21091: Improved audio metering
  interface/resources/qml/hifi/audio/MicBar.qml
  interface/src/scripting/Audio.cpp
  interface/src/scripting/Audio.h
  libraries/audio-client/src/AudioClient.cpp
  libraries/audio-client/src/AudioClient.h
  libraries/audio/src/AudioGate.cpp
  libraries/audio/src/AudioGate.h
Labels: Client, Development Approved, Project Approved

#14830 MS20909: ignore pickRay for zone shape visualizers
  scripts/system/modules/entityShapeVisualizer.js
Labels: Create, Development Approved, Project Approved

#14892 Case 21111: simplify recursive scripts
  tools/nitpick/src/Nitpick.cpp
  tools/nitpick/src/Test.cpp
  tools/nitpick/src/Test.h
  tools/nitpick/ui/Nitpick.ui
Labels: Development Approved, Engine, Project Approved, nitpick

#14879 Add prebuild metrics logging for CI system
  prebuild.py
Labels: Development Approved, Project Approved

#14878 Case 20966: glb files
  libraries/fbx/src/GLTFSerializer.cpp
  libraries/fbx/src/GLTFSerializer.h
Labels: Development Approved, Engine, Project Approved

#14896 Case 20502: Fix not being able to type text into particle url field
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, Project Approved

#14858 Case 21046: Fix Subsurface Scattering and ResourceCache "extra" bug
  libraries/animation/src/AnimationCache.cpp
  libraries/animation/src/AnimationCache.h
  libraries/audio/src/SoundCache.cpp
  libraries/audio/src/SoundCache.h
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/fbx/src/FBXSerializer_Material.cpp
  libraries/fbx/src/FSTReader.cpp
  libraries/graphics/src/graphics/Material.cpp
  libraries/model-networking/src/model-networking/MaterialCache.cpp
  libraries/model-networking/src/model-networking/MaterialCache.h
  libraries/model-networking/src/model-networking/ModelCache.cpp
  libraries/model-networking/src/model-networking/ModelCache.h
  libraries/model-networking/src/model-networking/ShaderCache.cpp
  libraries/model-networking/src/model-networking/ShaderCache.h
  libraries/model-networking/src/model-networking/TextureCache.cpp
  libraries/model-networking/src/model-networking/TextureCache.h
  libraries/networking/src/ResourceCache.cpp
  libraries/networking/src/ResourceCache.h
  libraries/recording/src/recording/ClipCache.cpp
  libraries/recording/src/recording/ClipCache.h
  libraries/render-utils/src/RenderPipelines.cpp
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Server & Network

#14898 Case 21102: Wearer and observer disagree on whether a worn item is correctly placed
  interface/src/avatar/OtherAvatar.cpp
Labels: Client, Development Approved, Engine, Project Approved, QA Approved :tada:

#14883 case:21032 Fixing Lifecycle of the android app
  android/apps/interface/src/main/java/io/highfidelity/hifiinterface/MainActivity.java
  android/apps/questInterface/src/main/AndroidManifest.xml
  android/apps/questInterface/src/main/cpp/native.cpp
  android/apps/questInterface/src/main/java/io/highfidelity/questInterface/MainActivity.java
  android/apps/questInterface/src/main/java/io/highfidelity/questInterface/PermissionsChecker.java
  android/apps/questInterface/src/main/java/io/highfidelity/questInterface/QuestActivity.java
  android/build.gradle
  android/libraries/oculus/build.gradle
  android/libraries/oculus/src/main/java/io/highfidelity/oculus/OculusMobileActivity.java
  android/libraries/qt/src/main/java/org/qtproject/qt5/android/bindings/QtActivity.java
  android/settings.gradle
  interface/src/Application.cpp
  libraries/oculusMobile/src/ovr/VrHandler.cpp
Labels: Android, Development Ready, Engine

#14875 Case 20882: Support custom display / input plugin lists and small tweaks
  CMakeLists.txt
  android/apps/framePlayer/build.gradle
  android/apps/questFramePlayer/build.gradle
  android/libraries/qt/src/main/java/org/qtproject/qt5/android/bindings/QtActivity.java
  interface/CMakeLists.txt
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/octree/OctreePacketProcessor.cpp
  libraries/display-plugins/src/display-plugins/DisplayPlugin.cpp
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.cpp
  libraries/display-plugins/src/display-plugins/hmd/DebugHmdDisplayPlugin.cpp
  libraries/display-plugins/src/display-plugins/hmd/HmdDisplayPlugin.h
  libraries/gpu-gl-common/src/gpu/gl/GLBackend.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLBackend.h
  libraries/input-plugins/src/input-plugins/InputPlugin.cpp
  libraries/oculusMobilePlugin/src/OculusMobileControllerManager.cpp
  libraries/oculusMobilePlugin/src/OculusMobileDisplayPlugin.cpp
  libraries/qml/src/qml/OffscreenSurface.cpp
  libraries/qml/src/qml/OffscreenSurface.h
  libraries/ui/src/ui/OffscreenQmlSurface.cpp
  plugins/oculus/src/OculusDisplayPlugin.cpp
  tools/gpu-frame-player/CMakeLists.txt
Labels: Android, Development Approved, Engine, Project Approved

#14899 Case 21146: Adding support for MSAA textures and framebuffer to gpu lib and backends.
  libraries/gpu-gl-common/src/gpu/gl/GLTexture.cpp
  libraries/gpu-gl/src/gpu/gl41/GL41BackendOutput.cpp
  libraries/gpu-gl/src/gpu/gl41/GL41BackendTexture.cpp
  libraries/gpu-gl/src/gpu/gl45/GL45BackendOutput.cpp
  libraries/gpu-gl/src/gpu/gl45/GL45BackendTexture.cpp
  libraries/gpu-gles/src/gpu/gles/GLESBackendOutput.cpp
  libraries/gpu-gles/src/gpu/gles/GLESBackendTexture.cpp
  libraries/gpu/src/gpu/Texture.cpp
  libraries/gpu/src/gpu/Texture.h
  libraries/render-utils/src/ToneMappingEffect.cpp
  libraries/render-utils/src/toneMapping.slf
  scripts/developer/utilities/render/deferredLighting.qml
Labels: Development Approved, Engine

#14897 Case 21142: Wearer and observer disagree on whether a worn item is correctly placed
  interface/src/avatar/OtherAvatar.cpp
Labels: Client, Development Approved, Engine

#14893 Adjust Inventory's send-to-trash confirm message
  interface/resources/qml/hifi/commerce/purchases/Purchases.qml
Labels: Commerce, Development Approved, Metaverse

#14900 Fixed MS21059: Avatar App Keyboard Raise in Desktop
  interface/resources/qml/hifi/avatarapp/Settings.qml
Labels: Client, Development Approved, QA Approved :tada:, bug

#14908 Revert "Pack all non-instanced traits"
  libraries/avatars/src/ClientTraitsHandler.cpp
Labels: Avatar, Project Approved, Server & Network

#14910 Quest re-enable IK.
  libraries/animation/src/AnimInverseKinematics.cpp
Labels: Development Approved, Engine

#14894 Case 21093: recompute collision group/mask when Grab ends
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  interface/src/avatar/OtherAvatar.cpp
  interface/src/avatar/OtherAvatar.h
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
  libraries/avatars/src/AvatarData.h
  libraries/entities/src/EntityItem.cpp
Labels: Critical Fix, Development Approved, Engine, Project Approved, QA Approved :tada:

#14890 (case 20980) Add support for Roughness/Metallic in GLTF models
  libraries/animation/CMakeLists.txt
  libraries/baking/src/TextureBaker.cpp
  libraries/fbx/src/GLTFSerializer.cpp
  libraries/hfm/CMakeLists.txt
  libraries/hfm/src/hfm/HFM.h
  libraries/image/src/image/ColorChannel.h
  libraries/image/src/image/Image.cpp
  libraries/image/src/image/Image.h
  libraries/model-baker/CMakeLists.txt
  libraries/model-networking/src/model-networking/ModelCache.cpp
  libraries/model-networking/src/model-networking/TextureCache.cpp
  libraries/model-networking/src/model-networking/TextureCache.h
  libraries/procedural/CMakeLists.txt
  tools/skeleton-dump/CMakeLists.txt
  tools/vhacd-util/CMakeLists.txt
Labels: Development Approved, Engine, Project Approved

#14903 Case 21129: improve nitpick usability
  tools/nitpick/README.md
  tools/nitpick/src/AdbInterface.cpp
  tools/nitpick/src/AdbInterface.h
  tools/nitpick/src/Nitpick.cpp
  tools/nitpick/src/Nitpick.h
  tools/nitpick/src/PathUtils.cpp
  tools/nitpick/src/PathUtils.h
  tools/nitpick/src/PythonInterface.cpp
  tools/nitpick/src/PythonInterface.h
  tools/nitpick/src/Test.cpp
  tools/nitpick/src/Test.h
  tools/nitpick/src/TestRailInterface.cpp
  tools/nitpick/src/TestRunnerMobile.cpp
  tools/nitpick/src/TestRunnerMobile.h
  tools/nitpick/ui/Nitpick.ui
Labels: Development Approved, Engine, Project Approved, nitpick

#14857 Case 15420: Fix ESS sometimes not getting the parents/children of entities with scripts.
  assignment-client/src/entities/EntityTreeSendThread.cpp
  assignment-client/src/entities/EntityTreeSendThread.h
  libraries/entities/src/DiffTraversal.cpp
  libraries/entities/src/DiffTraversal.h
  libraries/entities/src/EntityItem.cpp
  libraries/model-networking/src/model-networking/TextureCache.cpp
Labels: Development Approved, Infrastructure, Project Approved

#14913 Case 21147, Case 20944: Fix setTextures (pal, etc.)
  libraries/audio/src/Sound.h
  libraries/gpu/src/gpu/Texture.h
  libraries/hfm/src/hfm/HFM.h
  libraries/model-networking/src/model-networking/ModelCache.cpp
  libraries/model-networking/src/model-networking/TextureCache.cpp
  libraries/networking/src/ResourceCache.cpp
  libraries/networking/src/ResourceCache.h
Labels: Development Approved, Engine, Project Approved

#14912 Case 21185: protect nitpick from bad filename
  tools/CMakeLists.txt
  tools/nitpick/src/AWSInterface.cpp
  tools/nitpick/src/AWSInterface.h
  tools/nitpick/src/Nitpick.cpp
  tools/nitpick/src/Test.cpp
  tools/nitpick/src/TestRunnerDesktop.cpp
  tools/nitpick/src/TestRunnerDesktop.h
Labels: Development Approved, Project Approved, nitpick

#14809 case 19113: Recreated changes due to CLA issue in previous pr. Adding args to int…
  android/apps/interface/src/main/java/io/highfidelity/hifiinterface/InterfaceActivity.java
  android/apps/interface/src/main/java/io/highfidelity/hifiinterface/PermissionChecker.java
  android/apps/interface/src/main/java/io/highfidelity/hifiinterface/SplashActivity.java
  interface/CMakeLists.txt
Labels: Android, Development Approved, Engine, Project Approved

#14907 Case 21157: Fix Desktop.qml crash on local mac build
  interface/resources/qml/+webengine/Browser.qml
  interface/resources/qml/+webengine/BrowserWebView.qml
  interface/resources/qml/+webengine/InfoView.qml
  interface/resources/qml/+webengine/QmlWebWindow.qml
  interface/resources/qml/+webengine/QmlWebWindowView.qml
  interface/resources/qml/Browser.qml
  interface/resources/qml/BrowserWebView.qml
  interface/resources/qml/InfoView.qml
  interface/resources/qml/QmlWebWindow.qml
  interface/resources/qml/QmlWebWindowView.qml
  interface/resources/qml/controlsUit/ProxyWebView.qml
  interface/resources/qml/hifi/tablet/+webengine/BlocksWebView.qml
  interface/resources/qml/hifi/tablet/BlocksWebView.qml
Labels: Client, Development Approved, Engine, Project Approved

#14901 Case 19999: Update edit.js to auto close dropdowns when clicking outside
  scripts/system/html/js/entityProperties.js
Labels: Create, Development Approved, Project Approved

#14853 Case 20496: Windows (NSIS) installer shouldn't remove unselected component upon reinstall
  cmake/templates/NSIS.template.in
Labels: Development Ready, Infrastructure, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:, Windows Required

#14909 Case 21159: fixes for more grab bugs
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  interface/src/avatar/OtherAvatar.cpp
  interface/src/avatar/OtherAvatar.h
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
  libraries/avatars/src/AvatarData.h
  libraries/entities/src/EntityItem.cpp
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#14924 Case 21032: Quest lifecycle start/stop fix. Partial fix to pause/resume
  android/apps/questFramePlayer/src/main/java/io/highfidelity/frameplayer/QuestQtActivity.java
  android/apps/questInterface/src/main/cpp/native.cpp
  android/libraries/oculus/src/main/java/io/highfidelity/oculus/OculusMobileActivity.java
  android/libraries/qt/src/main/java/org/qtproject/qt5/android/bindings/QtActivity.java
  libraries/animation/src/AnimInverseKinematics.cpp
  libraries/oculusMobile/src/ovr/VrHandler.cpp
Labels: Android, Development Ready, Engine

#14887 Case 21066: restore shape caching in ShapeManager
  interface/src/Application.cpp
  interface/src/ui/ApplicationOverlay.cpp
  libraries/physics/src/ShapeManager.cpp
  libraries/physics/src/ShapeManager.h
  libraries/shared/src/HashKey.h
  libraries/shared/src/ShapeInfo.cpp
  libraries/shared/src/ShapeInfo.h
  tests/physics/src/ShapeInfoTests.cpp
Labels: Development Approved, Engine, Project Approved

#14838 Case 20962: Billboard mode improvements
  interface/src/Application.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.h
  libraries/entities-renderer/src/RenderableImageEntityItem.cpp
  libraries/entities-renderer/src/RenderableImageEntityItem.h
  libraries/entities-renderer/src/RenderableTextEntityItem.cpp
  libraries/entities-renderer/src/RenderableTextEntityItem.h
  libraries/entities-renderer/src/RenderableWebEntityItem.cpp
  libraries/entities-renderer/src/RenderableWebEntityItem.h
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityPropertyFlags.h
  libraries/entities/src/ImageEntityItem.cpp
  libraries/entities/src/ImageEntityItem.h
  libraries/entities/src/TextEntityItem.cpp
  libraries/entities/src/TextEntityItem.h
  libraries/entities/src/WebEntityItem.cpp
  libraries/entities/src/WebEntityItem.h
  libraries/networking/src/udt/PacketHeaders.h
Labels: Development Approved, Engine, Packet Version Change

#14864 Case 19724: If sorting PAL by loudness re-sort upon loudness updates
  interface/resources/qml/hifi/Pal.qml
Labels: Development Approved, Metaverse, Project Approved

#14925 Revert anim pose optimization
  interface/src/avatar/AvatarActionHold.cpp
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MySkeletonModel.cpp
  libraries/animation/src/AnimClip.cpp
  libraries/animation/src/AnimInverseKinematics.cpp
  libraries/animation/src/AnimManipulator.cpp
  libraries/animation/src/AnimPoleVectorConstraint.cpp
  libraries/animation/src/AnimPose.cpp
  libraries/animation/src/AnimPose.h
  libraries/animation/src/Rig.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/render-utils/src/AnimDebugDraw.cpp
  libraries/render-utils/src/CauterizedModel.cpp
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
  tests/animation/src/AnimTests.cpp
  tests/animation/src/AnimTests.h
Labels: Development Approved, Project Approved

#14919 Case 19930: Entity List - add select/clear all to entity type dropdown
  scripts/system/html/css/edit-style.css
  scripts/system/html/entityList.html
  scripts/system/html/js/entityList.js
Labels: Create, Development Approved, Project Approved

#14922 Case 21232: avoid entity update storm from entity-server
  assignment-client/src/octree/OctreeSendThread.cpp
Labels: Critical Fix, Development Approved, Infrastructure, Project Approved

#14905 Case 20242: FST materialMapping supports our material JSON format
  assignment-client/CMakeLists.txt
  interface/CMakeLists.txt
  interface/src/Application.cpp
  libraries/animation/src/AnimationCache.cpp
  libraries/audio/src/SoundCache.cpp
  libraries/avatars-renderer/CMakeLists.txt
  libraries/display-plugins/CMakeLists.txt
  libraries/entities-renderer/CMakeLists.txt
  libraries/entities/CMakeLists.txt
  libraries/entities/src/MaterialEntityItem.h
  libraries/fbx/src/FBXSerializer.cpp
  libraries/fbx/src/FBXSerializer.h
  libraries/fbx/src/FBXSerializer_Material.cpp
  libraries/graphics-scripting/CMakeLists.txt
  libraries/material-networking/CMakeLists.txt
  libraries/material-networking/src/material-networking/KTXCache.cpp
  libraries/material-networking/src/material-networking/KTXCache.h
  libraries/material-networking/src/material-networking/MaterialCache.cpp
  libraries/material-networking/src/material-networking/MaterialCache.h
  libraries/material-networking/src/material-networking/MaterialNetworkingLogging.cpp
  libraries/material-networking/src/material-networking/MaterialNetworkingLogging.h
  libraries/material-networking/src/material-networking/ShaderCache.cpp
  libraries/material-networking/src/material-networking/ShaderCache.h
  libraries/material-networking/src/material-networking/TextureCache.cpp
  libraries/material-networking/src/material-networking/TextureCache.h
  libraries/material-networking/src/material-networking/TextureCacheScriptingInterface.cpp
  libraries/material-networking/src/material-networking/TextureCacheScriptingInterface.h
  libraries/model-baker/CMakeLists.txt
  libraries/model-baker/src/model-baker/Baker.cpp
  libraries/model-baker/src/model-baker/Baker.h
  libraries/model-baker/src/model-baker/ParseMaterialMappingTask.cpp
  libraries/model-baker/src/model-baker/ParseMaterialMappingTask.h
  libraries/model-networking/CMakeLists.txt
  libraries/model-networking/src/model-networking/MaterialCache.h
  libraries/model-networking/src/model-networking/ModelCache.cpp
  libraries/model-networking/src/model-networking/ModelCache.h
  libraries/model-networking/src/model-networking/ModelNetworkingLogging.cpp
  libraries/networking/src/ResourceCache.h
  libraries/physics/CMakeLists.txt
  libraries/procedural/CMakeLists.txt
  libraries/procedural/src/procedural/Procedural.h
  libraries/recording/src/recording/ClipCache.cpp
  libraries/render-utils/CMakeLists.txt
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
  libraries/render-utils/src/RenderPipelines.cpp
  libraries/render-utils/src/TextureCache.h
  libraries/script-engine/CMakeLists.txt
  plugins/openvr/CMakeLists.txt
Labels: Avatar, Development Approved, Engine, Project Approved

#14930 Case 21241: Fix CMake problem for ubuntu build of nitpick
  tools/CMakeLists.txt
  tools/nitpick/src/Nitpick.cpp
  tools/nitpick/src/Nitpick.h
  tools/nitpick/src/Test.cpp
  tools/nitpick/src/Test.h
  tools/nitpick/ui/Nitpick.ui
Labels: Critical Fix, Development Approved, Engine, Project Approved, nitpick

#14914 Case 21165: tangent attribute
  libraries/fbx/src/GLTFSerializer.cpp
Labels: Development Approved, Engine, Project Approved

#14902 Case 21029: Fix duplicating non-dynamic grabbed entities in edit.js
  scripts/system/libraries/entitySelectionTool.js
Labels: Create, Development Ready, Project Approved

#14921 Compilation error on Qt 5.12
  tools/nitpick/src/AWSInterface.cpp
Labels: Development Approved, Engine, Project Approved, nitpick

#14927 Case 16349: Fix asset browser being hidden in incorrect way on server switch
  interface/src/Application.cpp
Labels: Create, Development Approved, Project Approved

#14915 Case 21190: Introducing msaa to forward renderer
  libraries/gpu/src/gpu/State.h
  libraries/render-utils/src/RenderCommonTask.cpp
  libraries/render-utils/src/RenderCommonTask.h
  libraries/render-utils/src/RenderDeferredTask.cpp
  libraries/render-utils/src/RenderForwardTask.cpp
  libraries/render-utils/src/RenderForwardTask.h
Labels: Development Approved, Engine, Project Approved

#14906 Qml marketplace - multiple improvements/bugfixes
  interface/resources/qml/hifi/commerce/marketplace/Marketplace.qml
  interface/resources/qml/hifi/commerce/marketplace/MarketplaceItem.qml
  interface/resources/qml/hifi/commerce/marketplace/SortButton.qml
  interface/resources/qml/hifi/commerce/marketplace/licenses/Popv1.txt
  interface/src/commerce/QmlMarketplace.cpp
  interface/src/commerce/QmlMarketplace.h
  scripts/system/html/js/marketplacesInject.js
Labels: Commerce, Development Approved, Infrastructure, QA Ready

#14928 Fix android release build APK
  android/build_android.sh
  android/containerized_build.sh
Labels: Critical Fix, Development Ready, Project Approved

#14881 Case 20613: Avatar Exporter v0.2 - copy external textures
  tools/unity-avatar-exporter/Assets/Editor/AvatarExporter.cs
  tools/unity-avatar-exporter/Assets/README.txt
  tools/unity-avatar-exporter/avatarExporter.unitypackage
Labels: Avatar, Create, Development Approved, Project Approved

#14918 Case 21128: AccountServices, HifiAbout, and WalletScriptingInterface JSDoc
  interface/src/AboutUtil.h
  interface/src/commerce/Wallet.h
  interface/src/scripting/AccountServicesScriptingInterface.cpp
  interface/src/scripting/AccountServicesScriptingInterface.h
  interface/src/scripting/WalletScriptingInterface.h
Labels: Development Ready, JSDocs, Project Approved

#14834 Case 20936: Set message dialog text width so wrap mode takes effect
  interface/resources/qml/dialogs/MessageDialog.qml
Labels: Android, Development Approved, Engine, Project Approved

#14920 Case 21193: update nitpick readme
  tools/nitpick/ConnectedDevice.PNG
  tools/nitpick/Create.PNG
  tools/nitpick/Evaluate.PNG
  tools/nitpick/README.md
  tools/nitpick/Run.PNG
  tools/nitpick/TestOnDesktop.PNG
  tools/nitpick/TestOnMobile.PNG
  tools/nitpick/Web Interface.PNG
  tools/nitpick/WebInterface.PNG
  tools/nitpick/Windows.PNG
  tools/nitpick/setup_7z.PNG
Labels: Development Approved, Engine, Project Approved, nitpick

#14917 Case 21012: Avatar Doctor
  interface/resources/qml/hifi/avatarPackager/AvatarDoctorDiagnose.qml
  interface/resources/qml/hifi/avatarPackager/AvatarDoctorErrorReport.qml
  interface/resources/qml/hifi/avatarPackager/AvatarPackagerApp.qml
  interface/resources/qml/hifi/avatarPackager/AvatarPackagerState.qml
  interface/resources/qml/hifi/avatarPackager/AvatarProjectCard.qml
  interface/resources/qml/hifi/avatarPackager/CreateAvatarProject.qml
  interface/src/avatar/AvatarDoctor.cpp
  interface/src/avatar/AvatarDoctor.h
  interface/src/avatar/AvatarPackager.cpp
  interface/src/avatar/AvatarPackager.h
  interface/src/avatar/AvatarProject.cpp
  interface/src/avatar/AvatarProject.h
Labels: Create, Development Approved, Project Approved

#14936 (case 21231) Fix GLTF materials
  libraries/material-networking/src/material-networking/TextureCache.cpp
  libraries/material-networking/src/material-networking/TextureCache.h
  libraries/model-networking/src/model-networking/ModelCache.cpp
  libraries/networking/src/ResourceCache.cpp
  libraries/networking/src/ResourceCache.h
Labels: Development Approved, Engine, Project Approved

#14942 Case 21277: Fix avatar deadlock
  libraries/avatars/src/AvatarHashMap.cpp
Labels: Development Approved, Engine

#14954 Feature/quest
  android/apps/questInterface/src/main/java/io/highfidelity/questInterface/InterfaceActivity.java
  android/apps/questInterface/src/main/java/io/highfidelity/questInterface/PermissionsChecker.java
Labels: Android, Development Approved, Engine, bug

#14765 Case 20657: artist stocking inventory
  interface/resources/qml/hifi/commerce/checkout/Checkout.qml
  interface/resources/qml/hifi/commerce/marketplace/Marketplace.qml
  interface/resources/qml/hifi/commerce/marketplace/MarketplaceItem.qml
  interface/resources/qml/hifi/commerce/marketplace/MarketplaceListItem.qml
Labels: Development Approved, Infrastructure, Metaverse, PRE-MERGE TESTING REQUIRED, Project Approved

#14952 Case 21305: Fix text overlay color property
  interface/src/ui/overlays/Overlays.cpp
Labels: Development Approved, Engine, Project Approved

#14935 Case 20920: Move Material Entity logic to render thread
  interface/src/Application.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.h
  libraries/entities-renderer/src/RenderableEntityItem.cpp
  libraries/entities-renderer/src/RenderableMaterialEntityItem.cpp
  libraries/entities-renderer/src/RenderableMaterialEntityItem.h
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/EntityTree.h
  libraries/entities/src/MaterialEntityItem.cpp
  libraries/entities/src/MaterialEntityItem.h
Labels: Development Approved, Engine, Project Approved

#14947 Case 21291, Case 21292, Case 21293: Working on overlay bugs
  interface/src/Application.cpp
  interface/src/raypick/StylusPick.cpp
  interface/src/ui/overlays/ContextOverlayInterface.cpp
  interface/src/ui/overlays/ContextOverlayInterface.h
  interface/src/ui/overlays/Overlays.cpp
  interface/src/ui/overlays/Overlays.h
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.h
  scripts/system/away.js
  scripts/system/controllers/controllerModules/teleport.js
  scripts/system/pal.js
  scripts/system/tablet-ui/tabletUI.js
Labels: Development Approved, Engine, Project Approved

#14948 Case 21274, Case 21267, Case 21290: Working on overlay bugs (RC80)
  interface/src/Application.cpp
  interface/src/raypick/StylusPick.cpp
  interface/src/ui/overlays/ContextOverlayInterface.cpp
  interface/src/ui/overlays/ContextOverlayInterface.h
  interface/src/ui/overlays/Overlays.cpp
  interface/src/ui/overlays/Overlays.h
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.h
  scripts/system/away.js
  scripts/system/controllers/controllerModules/teleport.js
  scripts/system/pal.js
  scripts/system/tablet-ui/tabletUI.js
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14951 Case 20993: Fix AO
  libraries/render-utils/src/AmbientOcclusionEffect.cpp
  libraries/render-utils/src/LightingModel.h
  scripts/developer/utilities/render/deferredLighting.qml
Labels: Development Approved, Engine, Project Approved

#14943 Case 21278: Fix avatar deadlock (RC80)
  libraries/avatars/src/AvatarHashMap.cpp
Labels: Critical Fix, Development Approved, Engine, Project Approved, QA Approved :tada:

#14933 Case 21271: Remove unnessary picks for quest
  interface/src/raypick/PickScriptingInterface.cpp
  interface/src/raypick/PointerScriptingInterface.cpp
  libraries/pointers/src/PickManager.cpp
  libraries/shared/src/Profile.cpp
  libraries/shared/src/Profile.h
  scripts/system/controllers/+android_questInterface/controllerScripts.js
  scripts/system/controllers/controllerDispatcher.js
Labels: Development Approved, Engine, Project Approved

#14946 Case 21288: Move Material Entity logic to render thread (RC80)
  interface/src/Application.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.h
  libraries/entities-renderer/src/RenderableEntityItem.cpp
  libraries/entities-renderer/src/RenderableMaterialEntityItem.cpp
  libraries/entities-renderer/src/RenderableMaterialEntityItem.h
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/EntityTree.h
  libraries/entities/src/MaterialEntityItem.cpp
  libraries/entities/src/MaterialEntityItem.h
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14964 fixing compile errors
  android/apps/interface/src/main/java/io/highfidelity/hifiinterface/InterfaceActivity.java
  libraries/gpu/src/gpu/Transform.slh
Labels: Android, Engine

#14953 Case 21304: Fix text overlay color property (RC80)
  interface/src/ui/overlays/Overlays.cpp
Labels: Development Approved, Engine, Project Approved, QA Approved :tada:

#14960 Case 21317: Unable to click icons on tablet when in HMD (0.81.0)
  interface/src/ui/overlays/Overlays.cpp
Labels: Development Approved, Engine, Project Approved

#14937 Case 21259: Pal textures don't change
  interface/src/ui/overlays/Overlays.cpp
  libraries/material-networking/src/material-networking/TextureCache.cpp
  libraries/material-networking/src/material-networking/TextureCache.h
  libraries/model-networking/src/model-networking/ModelCache.cpp
  libraries/networking/src/ResourceCache.cpp
  libraries/networking/src/ResourceCache.h
  libraries/shared/src/RegisteredMetaTypes.cpp
  libraries/shared/src/VariantMapToScriptValue.cpp
Labels: Development Approved, Engine, Project Approved

#14965 Case 21255: PickManager performance is slow when keyboard mallets are enabled
  interface/src/raypick/RayPick.h
  interface/src/raypick/StylusPick.cpp
  interface/src/ui/Keyboard.cpp
  interface/src/ui/Keyboard.h
Labels: Development Approved, Engine

#14949 Case 21300, Case 21301: Group cull all entity descendants of avatars
  interface/src/Application.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
  libraries/entities-renderer/src/RenderableEntityItem.cpp
  libraries/entities-renderer/src/RenderableEntityItem.h
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityScriptingInterface.cpp
  libraries/shared/src/SpatiallyNestable.cpp
  libraries/shared/src/SpatiallyNestable.h
Labels: Avatar, Development Approved, Engine, Project Approved

#14950 Case 19548, Case 20827: Group cull all entity descendants of avatars (RC80)
  interface/src/Application.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
  libraries/entities-renderer/src/RenderableEntityItem.cpp
  libraries/entities-renderer/src/RenderableEntityItem.h
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityScriptingInterface.cpp
  libraries/shared/src/SpatiallyNestable.cpp
  libraries/shared/src/SpatiallyNestable.h
Labels: Avatar, Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#14961 Case 21316: Unable to click tablet app icons with lasers when in HMD (0.80.0)
  interface/src/ui/overlays/Overlays.cpp
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#13901 case 20058: Android - Handshake implementation
  interface/resources/controllers/touchscreenvirtualpad.json
  interface/resources/images/handshake.png
  libraries/animation/src/AnimInverseKinematics.cpp
  libraries/display-plugins/src/display-plugins/Basic2DWindowOpenGLDisplayPlugin.cpp
  libraries/display-plugins/src/display-plugins/Basic2DWindowOpenGLDisplayPlugin.h
  libraries/input-plugins/src/input-plugins/TouchscreenVirtualPadDevice.cpp
  libraries/input-plugins/src/input-plugins/TouchscreenVirtualPadDevice.h
  libraries/ui/src/VirtualPadManager.cpp
  libraries/ui/src/VirtualPadManager.h
  scripts/+android_interface/defaultScripts.js
Labels: Android, Development Approved, Engine, Project Approved

#14939 Case 21270: Pal textures don't change (RC80)
  interface/src/ui/overlays/Overlays.cpp
  libraries/material-networking/src/material-networking/TextureCache.cpp
  libraries/material-networking/src/material-networking/TextureCache.h
  libraries/model-networking/src/model-networking/ModelCache.cpp
  libraries/networking/src/ResourceCache.cpp
  libraries/networking/src/ResourceCache.h
  libraries/shared/src/RegisteredMetaTypes.cpp
  libraries/shared/src/VariantMapToScriptValue.cpp
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#14969 Case 21334: PickManager is slow when 3D keyboard mallets are enabled (0.80.0)
  interface/src/raypick/RayPick.h
  interface/src/raypick/StylusPick.cpp
  interface/src/ui/Keyboard.cpp
  interface/src/ui/Keyboard.h
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#14957 Add README.md file to tools/jsdoc/out dir to prevent jsdoc build failures
  tools/jsdoc/.gitignore
  tools/jsdoc/out/README.md
Labels: Development Approved, JSDocs, Project Approved

#14971 Changing twitter handle from inc to VR
  scripts/system/html/js/SnapshotReview.js
Labels: Development Approved, Project Approved

#14970 Case 21335: Use old tablet keyboard for quest
  interface/src/ui/Keyboard.h
Labels: Client, Development Approved, Engine

#14975 case 21032: Life cycle pause
  android/libraries/oculus/src/main/java/io/highfidelity/oculus/OculusMobileActivity.java
  android/libraries/qt/src/main/java/org/qtproject/qt5/android/bindings/QtActivity.java
Labels: Development Approved, Engine

#14981 Automatically go to quest-dev domain on startup
  libraries/oculusMobilePlugin/src/OculusMobileDisplayPlugin.cpp
Labels: Development Approved, Engine

#14979 Case 21356:Fine tune the LOD manager max render target and world detail default for Quest / Tier Low
  interface/src/LODManager.h
Labels: Development Ready, Engine

#14926 Cpp implementation of the Flow script
  interface/src/avatar/AvatarManager.cpp
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  interface/src/avatar/OtherAvatar.cpp
  interface/src/avatar/OtherAvatar.h
  libraries/animation/src/Flow.cpp
  libraries/animation/src/Flow.h
  libraries/animation/src/Rig.cpp
  libraries/animation/src/Rig.h
  libraries/render-utils/src/Model.cpp
Labels: Avatar, Development Approved, Project Approved, Scripting API change

#14817 AnimSplineIK node added to inverse kinematics
  CMakeLists.txt
  interface/resources/avatar/avatar-animation_withSplineIKNode.json
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MySkeletonModel.cpp
  libraries/animation/src/AnimContext.h
  libraries/animation/src/AnimNodeLoader.cpp
  libraries/animation/src/AnimPoleVectorConstraint.cpp
  libraries/animation/src/AnimSplineIK.cpp
  libraries/animation/src/AnimSplineIK.h
  libraries/animation/src/AnimStateMachine.cpp
  libraries/animation/src/IKTarget.h
  libraries/animation/src/Rig.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
  libraries/shared/src/AvatarConstants.h
  libraries/shared/src/CubicHermiteSpline.h
Labels: Avatar, Development Approved, HMD required, Project Approved

#14986 case 21374 : Away mode on Quest when device is paused
  android/apps/questInterface/src/main/cpp/native.cpp
  android/libraries/oculus/src/main/java/io/highfidelity/oculus/OculusMobileActivity.java
  interface/src/AndroidHelper.cpp
  interface/src/AndroidHelper.h
  interface/src/Application.cpp
  interface/src/Application.h
  libraries/oculusMobile/src/ovr/VrHandler.cpp
  scripts/+android_questInterface/defaultScripts.js
  scripts/system/away.js
Labels: Development Approved, Engine

#14985 Fix crash on AvatarManager::findRayIntersectionVector when Avatar becomes null
  interface/src/avatar/AvatarManager.cpp
Labels: Avatar, Development Approved, Project Approved

#14987 (RC80) Fix crash on AvatarManager::findRayIntersectionVector when Avatar becomes null
  interface/src/avatar/AvatarManager.cpp
Labels: Avatar, Development Approved, Project Approved

#14973 Case 21342: Fix billboard mode in secondary camera (RC80)
  interface/src/Application.cpp
  libraries/entities-renderer/src/RenderableImageEntityItem.cpp
  libraries/entities-renderer/src/RenderableTextEntityItem.cpp
  libraries/entities-renderer/src/RenderableWebEntityItem.cpp
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/entities/src/ImageEntityItem.cpp
  libraries/entities/src/TextEntityItem.cpp
  libraries/entities/src/WebEntityItem.cpp
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#14988 Case 21199: Fix borken shaders for forward rendering (quest)
  libraries/entities-renderer/src/RenderablePolyLineEntityItem.cpp
  libraries/entities-renderer/src/RenderableShapeEntityItem.cpp
  libraries/entities-renderer/src/entities-renderer/paintStroke_forward.slp
  libraries/entities-renderer/src/paintStroke_forward.slf
  libraries/render-utils/src/RenderForwardTask.cpp
Labels: Development Approved, Engine

#14972 Case 21341: Fix billboard mode in secondary camera
  interface/src/Application.cpp
  libraries/entities-renderer/src/RenderableImageEntityItem.cpp
  libraries/entities-renderer/src/RenderableTextEntityItem.cpp
  libraries/entities-renderer/src/RenderableWebEntityItem.cpp
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/entities/src/ImageEntityItem.cpp
  libraries/entities/src/TextEntityItem.cpp
  libraries/entities/src/WebEntityItem.cpp
Labels: Development Approved, Engine, Project Approved

#14998 Start quest in quest-dev domain
  interface/src/Application.cpp
Labels: Development Approved, Engine

#14984 Case 21384: Avatar mouth blendshapes are not working correctly (master)
  interface/src/scripting/Audio.cpp
  libraries/audio-client/src/AudioClient.cpp
  libraries/audio-client/src/AudioClient.h
Labels: Client, Critical Fix, Development Approved, Project Approved, bug

#14992 Quest demo with avatar ik optimizations
  CMakeLists.txt
  interface/resources/avatar/avatar-animation_withSplineIKNode.json
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MySkeletonModel.cpp
  libraries/animation/src/AnimContext.h
  libraries/animation/src/AnimInverseKinematics.cpp
  libraries/animation/src/AnimNodeLoader.cpp
  libraries/animation/src/AnimPoleVectorConstraint.cpp
  libraries/animation/src/AnimSplineIK.cpp
  libraries/animation/src/AnimSplineIK.h
  libraries/animation/src/AnimStateMachine.cpp
  libraries/animation/src/IKTarget.h
  libraries/animation/src/Rig.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
  libraries/shared/src/AvatarConstants.h
  libraries/shared/src/CubicHermiteSpline.h
  tools/unity-avatar-exporter/Assets/README.txt
Labels: Avatar, Development Approved, Engine

#14978 Case 21313: Add "modelScale" property to fix pal (RC80)
  interface/src/ui/overlays/Overlays.cpp
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityPropertyFlags.h
  libraries/entities/src/ModelEntityItem.cpp
  libraries/entities/src/ModelEntityItem.h
  libraries/networking/src/udt/PacketHeaders.h
  libraries/render-utils/src/CauterizedModel.cpp
  libraries/render-utils/src/Model.cpp
  libraries/shared/src/SpatiallyNestable.cpp
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Packet Version Change, Project Approved, QA Approved :tada:

#14977 Case 21354: Add "modelScale" property to fix pal
  interface/src/ui/overlays/Overlays.cpp
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityPropertyFlags.h
  libraries/entities/src/ModelEntityItem.cpp
  libraries/entities/src/ModelEntityItem.h
  libraries/networking/src/udt/PacketHeaders.h
  libraries/render-utils/src/CauterizedModel.cpp
  libraries/render-utils/src/Model.cpp
  libraries/shared/src/SpatiallyNestable.cpp
Labels: Development Approved, Engine, Packet Version Change

#14989 Case 21315, Case 21326, Case 21370 - QML Marketplace fixes
  interface/resources/qml/hifi/commerce/marketplace/Marketplace.qml
  interface/resources/qml/hifi/commerce/marketplace/MarketplaceItem.qml
  interface/resources/qml/hifi/commerce/marketplace/MarketplaceListItem.qml
  scripts/system/html/js/marketplacesInject.js
Labels: Commerce, Development Ready, Metaverse, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:, bug

#14982 Case 21268: Avatar mouth blendshapes are not working correctly (RC80)
  interface/src/scripting/Audio.cpp
  libraries/audio-client/src/AudioClient.cpp
  libraries/audio-client/src/AudioClient.h
Labels: Client, Critical Fix, Development Approved, Engine, Project Approved, QA Approved :tada:, bug

#15003 Case 21397: Fix nametag rotation
  interface/src/ui/overlays/Overlays.cpp
Labels: Development Approved, Engine, Project Approved

#14999 case 21395: Adjust culling matrix
  libraries/oculusMobilePlugin/src/OculusMobileDisplayPlugin.cpp
Labels: Development Approved

#14996 Case 21376: Fix parent loop crash (RC80)
  libraries/shared/src/SpatiallyNestable.cpp
  libraries/shared/src/SpatiallyNestable.h
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#14976 Guard against accidentally calling wrong api/v1/places endpoint
  domain-server/src/DomainServer.cpp
  libraries/networking/src/AddressManager.cpp
  scripts/system/interstitialPage.js
Labels: Development Approved, Metaverse, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#14980 Case 21309: don't corrupt workload system
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
Labels: Development Approved, Engine, Project Approved

#14995 Case 21391: Fix parent loop crash
  libraries/shared/src/SpatiallyNestable.cpp
  libraries/shared/src/SpatiallyNestable.h
Labels: Development Approved, Engine, Project Approved

#15010 Case 21408: Quest demo - Fixing the gamma correction
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.cpp
  libraries/display-plugins/src/display-plugins/SrgbToLinear.slf
  libraries/display-plugins/src/display-plugins/SrgbToLinear.slp
  libraries/gpu/src/gpu/Color.slh
  libraries/gpu/src/gpu/DrawTextureGammaLinearToSRGB.slf
  libraries/gpu/src/gpu/DrawTextureGammaLinearToSRGB.slp
  libraries/gpu/src/gpu/DrawTextureGammaSRGBToLinear.slf
  libraries/gpu/src/gpu/DrawTextureGammaSRGBToLinear.slp
  libraries/oculusMobile/src/ovr/Framebuffer.cpp
  libraries/oculusMobilePlugin/src/OculusMobileDisplayPlugin.cpp
  scripts/developer/utilities/render/deferredLighting.qml
Labels: Development Approved, Engine, Project Approved

#14983 Case 21372: don't corrupt workload system on 80
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#15001 Case 21260, Case 21352: Trying to fix overlay rotation (RC 80)
  interface/src/ui/overlays/Overlays.cpp
  interface/src/ui/overlays/Overlays.h
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#15016 Case 21373: Allow flying in HMD if you would otherwise fall forever (RC80)
  interface/src/avatar/MyAvatar.cpp
  libraries/physics/src/CharacterController.cpp
  libraries/physics/src/CharacterController.h
Labels: Development Approved, Engine, PRE-MERGE TESTING REQUIRED, Project Approved, QA Approved :tada:

#15017 bug fix: Ik is on by default in desktop mode
  libraries/animation/src/Rig.cpp
Labels: Avatar, Development Approved, HMD required, Project Approved, bug

#15015 Case 21418: Allow flying in HMD if you would otherwise fall forever
  interface/src/avatar/MyAvatar.cpp
  libraries/physics/src/CharacterController.cpp
  libraries/physics/src/CharacterController.h
Labels: Development Approved, Engine, Project Approved

#15012 Case 21397: Trying to fix overlay rotation
  interface/src/ui/overlays/Overlays.cpp
  interface/src/ui/overlays/Overlays.h
Labels: Development Approved, Engine

#14968 Guard against accidentally calling wrong api/v1/places endpoint
  domain-server/src/DomainServer.cpp
  libraries/networking/src/AddressManager.cpp
  scripts/system/interstitialPage.js
Labels: Metaverse

#15021 case 21425: Fix grab earthquake for 80
  interface/src/avatar/GrabManager.cpp
Labels: Client, Development Approved, Engine, Project Approved, QA Approved :tada:, bug

#15014 case 21411: don't allow others' grabs to move locked or ungrabbable things
  interface/src/avatar/GrabManager.cpp
Labels: Client, Development Approved, Engine, Project Approved, bug
